# Flexible Search via GPU

We update the search algorithm to utilize the new GPU backend for dimension computations. We also improve the initialization of the search space to reduce the time needed to process and filter the search space.

In [46]:
# %load dim_backprop_gpu_only.py
"""Exact GPU based computation of polynomial-network neurovariety dimensions. This module has no SageMath or NumPy backend.   

It requires CuPy and a CUDA-capable NVIDIA GPU. CuPy replaces Numpy and provides GPU-accelerated array operations.

Comment: I used an ASUS Dual GeForce RTX 4070 Super.

The public function keeps the original calling convention of the Sage implementation: compute_dimension(network_widths, network_exponent) so that I can use the previous notebooks.

The returned tuple like before is: (sizes, exponent, ambient_dim, expected_dim, dimension, defect).

The computation is exact over the finite fields listed in ``DEFAULT_PRIMES``. One might want to pick larger primes for large runs.

All samples and all output-coordinate pullbacks are differentiated in one batched GPU computation.  

The final Jacobian rank is computed modulo each prime by GPU-parallel row elimination.
"""

from __future__ import annotations

from math import comb
from typing import Iterator, Sequence

try:
    import cupy as cp
except ImportError as exc:
    raise RuntimeError(
        "This GPU-only module requires CuPy. Install the CuPy package that "
        "matches your CUDA version, for example `pip install cupy-cuda12x`."
    ) from exc


DEFAULT_PRIMES = (100003, 100153)
_INT64_MAX = (1 << 63) - 1


def _require_cuda() -> None:
    """Raise a clear error unless a usable CUDA device is visible."""
    try:
        device_count = int(cp.cuda.runtime.getDeviceCount())
    except cp.cuda.runtime.CUDARuntimeError as exc:
        raise RuntimeError(
            "CuPy is installed, but CUDA could not be initialized. Check the "
            "NVIDIA driver, CUDA/CuPy compatibility, and notebook kernel."
        ) from exc

    if device_count < 1:
        raise RuntimeError("No CUDA-capable GPU is visible to CuPy.")


def gpu_information() -> dict[str, object]:
    """Return basic information about the CUDA device used by this module."""
    _require_cuda()
    device_id = int(cp.cuda.runtime.getDevice())
    properties = cp.cuda.runtime.getDeviceProperties(device_id)
    name = properties["name"]
    if isinstance(name, bytes):
        name = name.decode("utf-8", errors="replace")
    return {
        "device_id": device_id,
        "name": name,
        "device_count": int(cp.cuda.runtime.getDeviceCount()),
        "cupy_version": cp.__version__,
        "cuda_runtime_version": int(cp.cuda.runtime.runtimeGetVersion()),
        "driver_version": int(cp.cuda.runtime.driverGetVersion()),
    }


def _is_prime(value: int) -> bool:
    """Deterministic Miller--Rabin test for unsigned 64-bit integers to check for primality."""
    if value < 2:
        return False

    small_primes = (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37)
    if value in small_primes:
        return True
    if any(value % prime == 0 for prime in small_primes):
        return False

    odd_part = value - 1
    power_of_two = 0
    while odd_part % 2 == 0:
        power_of_two += 1
        odd_part //= 2

    # Deterministic for every n < 2^64.
    for base in (2, 325, 9375, 28178, 450775, 9780504, 1795265022):
        if base % value == 0:
            continue
        witness = pow(base, odd_part, value)
        if witness in (1, value - 1):
            continue
        for _ in range(power_of_two - 1):
            witness = (witness * witness) % value
            if witness == value - 1:
                break
        else:
            return False

    return True


def _weak_compositions(total: int, length: int) -> Iterator[tuple[int, ...]]:
    """Yield nonnegative ``length``-tuples whose entries sum to ``total``. 
    These will be used to form a unisolvent evaluation set for 
    homogeneous polynomials of total degree ``total`` in 
    ``length``-many variables. Tuples should be generated in lexicographic order."""
    if length == 0:
        if total == 0:
            yield ()
        return
    if length == 1:
        yield (total,)
        return

    for first in range(total + 1):
        for rest in _weak_compositions(total - first, length - 1):
            yield (first,) + rest


def _unisolvent_samples(input_dim: int, degree: int, prime: int):
    r"""Construct the homogeneous interpolation points directly on the GPU.

    On the chart ``x_0 = 1``, homogeneous degree-``degree`` forms become
    polynomials of total degree at most ``degree`` in ``input_dim - 1``
    variables.  The integer simplex is an unisolvent evaluation set when
    ``prime > degree``.
    """
    if input_dim < 1:
        raise ValueError("the input layer must have positive width")
    if degree < 0:
        raise ValueError("degree must be nonnegative")
    if prime <= degree:
        raise ValueError(
            f"prime {prime} must exceed polynomial degree {degree}"
        )

    expected = comb(degree + input_dim - 1, input_dim - 1)
    if input_dim == 1:
        return cp.ones((1, 1), dtype=cp.int64)

    points: list[tuple[int, ...]] = []
    for total in range(degree + 1):
        for alpha in _weak_compositions(total, input_dim - 1):
            points.append((1,) + alpha)

    if len(points) != expected:
        raise RuntimeError(
            f"internal sample-count error: got {len(points)}, expected {expected}"
        )

    return cp.asarray(points, dtype=cp.int64) % prime


def _mod_pow(base, exponent: int, prime: int):
    """Elementwise matrix + mod p exponentiation on the GPU."""
    if exponent < 0:
        raise ValueError("exponent must be nonnegative")

    result = cp.ones_like(base, dtype=cp.int64)
    if exponent == 0:
        return result

    power = base.astype(cp.int64, copy=False) % prime
    remaining = int(exponent)
    while remaining:
        if remaining & 1:
            result = (result * power) % prime
        remaining >>= 1
        if remaining:
            power = (power * power) % prime

    return result


def _check_dot_product_safety(widths: Sequence[int], prime: int) -> None:
    """Prevent signed int64 overflow before a matrix product is reduced."""
    largest_inner_dimension = max(int(width) for width in widths)
    worst_case = largest_inner_dimension * (prime - 1) ** 2
    if worst_case > _INT64_MAX:
        raise OverflowError(
            "An int64 GPU matrix product may overflow before reduction modulo "
            "the prime. Use a smaller prime or narrower layers."
        )


def _random_weights(
    widths: Sequence[int], prime: int, seed: int
) -> list[cp.ndarray]:
    """Generate all network weight matrices directly in GPU memory.
    The random number generator is seeded for reproducibility. 
    The generation is uniform over ``0, 1, ..., prime - 1``.
    """
    rng = cp.random.RandomState(seed)
    return [
        rng.randint(
            0,
            prime,
            size=(out_width, in_width),
            dtype=cp.int64,
        )
        for in_width, out_width in zip(widths[:-1], widths[1:])
    ]


def _parameter_offsets(
    weights: Sequence[cp.ndarray],
) -> tuple[list[int], int]:
    offsets: list[int] = []
    total = 0
    for weight in weights:
        offsets.append(total)
        total += int(weight.shape[0] * weight.shape[1])
    return offsets, total


def _batched_weight_jacobian(
    weights: Sequence[cp.ndarray],
    samples: cp.ndarray,
    exponent: int,
    prime: int,
) -> cp.ndarray:
    """Evaluate every output/weight derivative at every sample on the GPU.

    The result has shape ``(number_of_samples, output_width, num_parameters)``.
    Weight matrices are flattened layer by layer in row-major order, matching
    the ordering used by Sage's matrix ``list()`` method in the old code.
    """
    if exponent < 1:
        raise ValueError("network exponent must be at least 1")
    if not weights:
        raise ValueError("the network must contain at least one weight layer")

    activations = [samples]
    preactivations: list[cp.ndarray] = []
    activation = samples

    # Hidden layers use z -> z^exponent; the final layer is linear.
    for weight in weights[:-1]:
        preactivation = cp.matmul(activation, weight.T) % prime
        preactivations.append(preactivation)
        activation = _mod_pow(preactivation, exponent, prime)
        activations.append(activation)

    batch_size = int(samples.shape[0])
    output_width = int(weights[-1].shape[0])
    offsets, num_parameters = _parameter_offsets(weights)

    jacobian = cp.zeros(
        (batch_size, output_width, num_parameters), dtype=cp.int64
    )

    # Final linear layer.
    final_input = activations[-1]
    final_offset = offsets[-1]
    final_input_width = int(weights[-1].shape[1])
    for output_index in range(output_width):
        start = final_offset + output_index * final_input_width
        stop = start + final_input_width
        jacobian[:, output_index, start:stop] = final_input

    if len(weights) == 1:
        return jacobian

    # Derivatives of all output coordinates with respect to the last hidden
    # preactivation: shape (sample, output, hidden neuron).
    delta = cp.broadcast_to(
        weights[-1][None, :, :],
        (batch_size, output_width, int(weights[-1].shape[1])),
    ).copy()
    derivative = (
        (exponent % prime)
        * _mod_pow(preactivations[-1], exponent - 1, prime)
    ) % prime
    delta = (delta * derivative[:, None, :]) % prime

    # Hidden layers from last to first.
    for layer_index in range(len(weights) - 2, -1, -1):
        weight = weights[layer_index]
        layer_input = activations[layer_index]

        gradient = (
            delta[:, :, :, None] * layer_input[:, None, None, :]
        ) % prime

        start = offsets[layer_index]
        stop = start + int(weight.shape[0] * weight.shape[1])
        jacobian[:, :, start:stop] = gradient.reshape(
            batch_size, output_width, stop - start
        )

        if layer_index > 0:
            delta = cp.matmul(delta, weight) % prime
            derivative = (
                (exponent % prime)
                * _mod_pow(
                    preactivations[layer_index - 1], exponent - 1, prime
                )
            ) % prime
            delta = (delta * derivative[:, None, :]) % prime

    return jacobian


def _rank_mod_prime_gpu(
    matrix: cp.ndarray,
    prime: int,
    workspace_bytes: int = 512 * 1024**2,
) -> int:
    """Compute exact matrix rank over GF(prime) using GPU row operations.
    
    Question for future: Can we replace this with a predefined CuPy function?
    """
    if matrix.ndim != 2:
        raise ValueError("rank input must be a matrix")
    if workspace_bytes <= 0:
        raise ValueError("workspace_bytes must be positive")

    reduced = matrix.astype(cp.int64, copy=True) % prime

    # Eliminate along the smaller dimension.
    if reduced.shape[1] > reduced.shape[0]:
        reduced = reduced.T.copy()

    nrows, ncols = map(int, reduced.shape)
    pivot_row = 0

    for column in range(ncols):
        if pivot_row == nrows:
            break

        nonzero = reduced[pivot_row:, column] != 0
        if not bool(cp.any(nonzero).item()):
            continue

        pivot = pivot_row + int(cp.argmax(nonzero).item())
        if pivot != pivot_row:
            temporary = reduced[pivot_row, :].copy()
            reduced[pivot_row, :] = reduced[pivot, :]
            reduced[pivot, :] = temporary

        pivot_value = int(reduced[pivot_row, column].item())
        inverse = pow(pivot_value, prime - 2, prime)
        reduced[pivot_row, column:] = (
            reduced[pivot_row, column:] * inverse
        ) % prime

        # The row updates are parallel CUDA kernels. Chunking bounds temporary
        # memory usage for large Jacobians.
        remaining_columns = ncols - column
        bytes_per_row = max(1, 3 * remaining_columns * 8)
        rows_per_chunk = max(1, workspace_bytes // bytes_per_row)

        start = pivot_row + 1
        while start < nrows:
            stop = min(nrows, start + rows_per_chunk)
            factors = reduced[start:stop, column].copy()
            reduced[start:stop, column:] = (
                reduced[start:stop, column:]
                - factors[:, None] * reduced[pivot_row, column:][None, :]
            ) % prime
            start = stop

        pivot_row += 1

    return pivot_row


def compute_dimension(
    network_widths: Sequence[int],
    network_exponent: int,
    *,
    primes: Sequence[int] = DEFAULT_PRIMES,
    seed: int = 20260630,
    rank_workspace_bytes: int = 512 * 1024**2,
    verbose: bool = False,
):
    """Compute the neurovariety dimension entirely with the CUDA backend.

    Parameters
    ----------
    network_widths:
        Layer widths ``[d0, d1, ..., dL]``.
    network_exponent:
        Common hidden-layer activation exponent.
    primes:
        Prime moduli used to cross-check the generic rank.
    seed:
        Base random seed for the network weights.
    rank_workspace_bytes:
        Approximate upper bound for temporary elimination workspace.
    verbose:
        Print GPU and rank information.

    Returns
    -------
    tuple
        ``(sizes, exponent, ambient_dim, expected_dim, dimension, defect)``.
    """
    _require_cuda()

    widths = tuple(int(width) for width in network_widths)
    exponent = int(network_exponent)

    if len(widths) < 2:
        raise ValueError("network_widths must contain input and output widths")
    if any(width <= 0 for width in widths):
        raise ValueError("all network widths must be positive")
    if exponent < 1:
        raise ValueError("network_exponent must be at least 1")
    if not primes:
        raise ValueError("at least one prime is required")

    degree = exponent ** (len(widths) - 2)
    ambient_per_output = comb(degree + widths[0] - 1, widths[0] - 1)
    ambient_dim = ambient_per_output * widths[-1]
    num_parameters = sum(
        in_width * out_width
        for in_width, out_width in zip(widths[:-1], widths[1:])
    )

    dimensions: list[int] = []

    if verbose:
        info = gpu_information()
        print(
            f"GPU {info['device_id']}: {info['name']} | "
            f"CuPy {info['cupy_version']} | "
            f"CUDA runtime {info['cuda_runtime_version']}"
        )

    for prime_index, prime_value in enumerate(primes):
        prime = int(prime_value)
        if not _is_prime(prime):
            raise ValueError(f"modulus {prime} is not prime")
        _check_dot_product_safety(widths, prime)

        samples = _unisolvent_samples(widths[0], degree, prime)
        weights = _random_weights(
            widths,
            prime,
            seed + 1_000_003 * prime_index + prime,
        )

        jacobian = _batched_weight_jacobian(
            weights,
            samples,
            exponent,
            prime,
        )
        rank_matrix = jacobian.reshape(
            ambient_per_output * widths[-1], num_parameters
        )
        dimension = _rank_mod_prime_gpu(
            rank_matrix,
            prime,
            workspace_bytes=rank_workspace_bytes,
        )
        dimensions.append(dimension)

        # Ensure kernels for this prime have completed before reporting and
        # releasing memory.
        cp.cuda.Stream.null.synchronize()

        if verbose:
            print(
                f"prime={prime}, samples={ambient_per_output}, "
                f"rank_matrix={tuple(rank_matrix.shape)}, rank={dimension}"
            )

        del rank_matrix, jacobian, weights, samples
        cp.get_default_memory_pool().free_all_blocks()

    if not all(dimension == dimensions[0] for dimension in dimensions):
        raise ValueError(
            "different dimensions over finite fields: " + str(dimensions)
        )

    naive_bound = sum(
        (in_width - 1) * out_width
        for in_width, out_width in zip(widths[:-1], widths[1:])
    ) + widths[-1]
    expected_dim = min(ambient_dim, naive_bound)
    dimension = dimensions[0]

    return (
        list(widths),
        exponent,
        ambient_dim,
        expected_dim,
        dimension,
        expected_dim - dimension,
    )

# Search Algorithm

In [47]:
import os
import ast
import math
import itertools
import random as py_random
import pandas as pd
from tqdm import tqdm

In [56]:
# Helper Functions

def calculate_parameter_count(hidden: tuple, d_0: int, d_h: int) -> int:
    """Calculates the total number of weights and biases in the network."""
    sizes = [d_0] + list(hidden) + [d_h]
    return sum(m * n for m, n in zip(sizes[:-1], sizes[1:]))

def is_less_or_equal(t1: tuple, t2: tuple) -> bool:
    """Returns True if every element in t1 is <= the corresponding element in t2."""
    if len(t1) != len(t2):
        return False
    return all(a <= b for a, b in zip(t1, t2))

def evaluate_single_architecture(hidden_tuple: tuple, h: int, d_0: int, d_h: int, exponent: int):
    """Worker function to evaluate a single architecture and format the result.
    This uses the previous compute_dimension function.
    """
    sizes = [d_0] + list(hidden_tuple) + [d_h]
    arch_str = str(sizes)
    
    try:
        _, _, amb, _, dim, _ = compute_dimension(sizes, exponent)
        params = calculate_parameter_count(hidden_tuple, d_0, d_h)
        is_full = (dim == amb)
        
        status = "FULL " if is_full else "SHORT"
        print(f"  [{status}] {arch_str} -> Rank: {dim}/{amb} (Params: {params})")
        
        return {
            "h": h,
            "exponent": exponent,
            "architecture": arch_str,
            "num_parameters": params,
            "dimension_computed": int(dim),
            "ambient_dimension": int(amb),
            "is_full_dimension": is_full,
            "is_minimal": False 
        }
    except Exception as e:
        print(f"  [ERROR] {arch_str} failed: {e}")
        return None

In [49]:
# Core Search & Pruning Algorithm

def parameter_boundary_search(
    h_values: list, max_width=6, min_width=1, exponent=2, 
    d_0=2, d_h=1, csv_filename="architecture_search_log.csv", 
    user_guesses=None, layer_bounds=None
):

    # Load or initialize Database
    if os.path.exists(csv_filename):
        print(f"Loading existing database from '{csv_filename}'...")
        df = pd.read_csv(csv_filename)
    else:
        print("No existing database found. Starting fresh...")
        df = pd.DataFrame(columns=[
            "h", "exponent", "architecture", "num_parameters", 
            "dimension_computed", "ambient_dimension", "is_full_dimension", "is_minimal"
        ])

    evaluated_architectures = set(df["architecture"].tolist())
    new_records = []

    for h in h_values:
        print(f"\n--- RANDOM SEARCH: h={h}, exponent={exponent} ---")
        
        num_hidden = h - 1
        degree = exponent ** num_hidden
        ambient_dim = math.comb(degree + d_0 - 1, d_0 - 1) * d_h
        print(f"  Target Ambient Dimension: {ambient_dim}")

        # Extract known boundaries
        known_minimal = set()
        known_short = set()
        
        if not df.empty:
            subset_df = df[(df["h"] == h) & (df["exponent"] == exponent)]
            
            min_df = subset_df[subset_df["is_minimal"] == True]
            known_minimal.update(tuple(ast.literal_eval(a)[1:-1]) for a in min_df["architecture"])
            
            short_df = subset_df[subset_df["is_full_dimension"] == False]
            known_short.update(tuple(ast.literal_eval(a)[1:-1]) for a in short_df["architecture"])

        # 1. Evaluate User Guesses
        if user_guesses and h in user_guesses:
            for guess in user_guesses[h]:
                arch_str = str([d_0] + list(guess) + [d_h])
                if arch_str in evaluated_architectures:
                    continue
                
                print(f"  Evaluating Guess: {guess}...")
                res = evaluate_single_architecture(guess, h, d_0, d_h, exponent)
                if not res: continue
                
                evaluated_architectures.add(res["architecture"])
                new_records.append(res)
                
                if res["is_full_dimension"]:
                    known_minimal.add(guess)
                else:
                    known_short.add(guess)

# 2. Build and Filter Search Pool
        print("  Generating candidate pool...")
        
        # Builds the Search Pool but imposing bounds on the individual layers

        if layer_bounds and h in layer_bounds:
            bounds = layer_bounds[h]
            if len(bounds) != num_hidden:
                print(f"  [WARNING] layer_bounds for h={h} has length {len(bounds)}, but expected {num_hidden} hidden layers. Skipping this depth...")
                continue
            
            print(f"  Using custom per-layer bounds: {bounds}")
            ranges = [range(max(1, b_min), b_max + 1) for b_min, b_max in bounds]
            all_possible = itertools.product(*ranges)
            
            # calculate total items for the progress bar
            total_combinations = math.prod(len(r) for r in ranges)
            
        else:
            print(f"  Using global bounds: min_width={min_width}, max_width={max_width}")
            width_range = range(max(1, min_width), max_width + 1)
            all_possible = itertools.product(width_range, repeat=num_hidden)
            
            # calculate total items for the progress bar
            total_combinations = len(width_range) ** num_hidden
        
        candidate_pool = []
        rejected_count = 0
        
        # wrap in tqdm. useful for long run times.
        for hidden in tqdm(all_possible, total=total_combinations, desc="  Filtering", leave=False, dynamic_ncols=True):
            arch_str = str([d_0] + list(hidden) + [d_h])
            if arch_str in evaluated_architectures:
                continue
                
            params = calculate_parameter_count(hidden, d_0, d_h)
            
            # pruning 
            if (params < ambient_dim or 
                any(is_less_or_equal(m, hidden) for m in known_minimal) or 
                any(is_less_or_equal(hidden, s) for s in known_short)):
                rejected_count += 1
                continue
                
            candidate_pool.append(hidden)
            
        print(f"  Pruned {rejected_count} impossible/redundant architectures.")
        print(f"  Starting sequential evaluation on {len(candidate_pool)} viable candidates.")

        # shuffle queue 
        py_random.shuffle(candidate_pool)

        try:
            while candidate_pool:
                target = candidate_pool.pop(0)
                
                res = evaluate_single_architecture(target, h, d_0, d_h, exponent)
                if not res: continue
                
                evaluated_architectures.add(res["architecture"])
                new_records.append(res)
                
                before_len = len(candidate_pool)
                if res["is_full_dimension"]:
                    known_minimal.add(target)
                    # remove all supersets from the queue
                    candidate_pool = [c for c in candidate_pool if not is_less_or_equal(target, c)]
                    pruned = before_len - len(candidate_pool)
                    if pruned > 0: print(f"    [Upward Pruned] {pruned} supersets removed from queue.")
                else:
                    known_short.add(target)
                    # remove all subsets from the queue
                    candidate_pool = [c for c in candidate_pool if not is_less_or_equal(c, target)]
                    pruned = before_len - len(candidate_pool)
                    if pruned > 0: print(f"    [Downward Pruned] {pruned} subsets removed from queue.")

        except KeyboardInterrupt: # incase one wants to halt a long run early and still save the results
            print("\n[Interrupt] User halted the loop early. Saving progress and continuing execution...")

    # 4. Save and determine minimality based on results in the .csv
    # This does not guarantee the examples are truly minimality -- need to do actual checks elsewhere.
    if new_records:
        new_df = pd.DataFrame(new_records).dropna(axis=1, how='all')
        if not df.empty:
            df = pd.concat([df, new_df], ignore_index=True)
        else:
            df = new_df
        print(f"\nAdded {len(new_records)} new architectures to the database.")

    print("Re-evaluating minimal filling properties (grouped by depth h and exponent)...")
    if not df.empty:
        df["is_minimal"] = False 
        
        # calculate if minimal 
        # this does not actual check minimality fully -- just minimality base on search so far
        # see verify_minimal.ipynb

        for (h_val, exp_val), group in df[df["is_full_dimension"] == True].groupby(["h", "exponent"]):
            full_archs = [ast.literal_eval(arch) for arch in group["architecture"]]
            
            for idx, row in group.iterrows():
                parsed_config = ast.literal_eval(row["architecture"])
                # it is minimal if no other full architecture is strictly smaller than it
                is_min = not any(
                    other != parsed_config and is_less_or_equal(other, parsed_config) 
                    for other in full_archs
                )
                df.at[idx, "is_minimal"] = is_min

        df.to_csv(csv_filename, index=False)
        print(f"Database successfully saved to '{csv_filename}'.\n")
    return df

# Executing the Search

In [51]:
# This adjusts which depths you want to consider
h_values_to_test = [2,3,4,5] 


d0 = 2
dh = 1
r = 5

# Optional: provide guess as tuple for the hidden layers
my_guesses = {} 


# Provide individual bounds for each hidden layer (length must match h - 1)
# Format: { h_value: [(min1, max1), (min2, max2), ...] }

custom_bounds = {
    5: [
        (1, min(dh*(r**d0), math.comb(r**(5-1)+d0-1, r**(5-1))) ),  # d1
        (1, min(dh*(r** (2*d0)), math.comb(r**(5-2)+d0-1, r**(5-2))) ),  # d2
        (1, min(dh*(r** (3*d0)), math.comb(r**(5-3)+d0-1, r**(5-3))) ),  # d3
        (1, min(dh*(r** (4*d0)), math.comb(r**(5-4)+d0-1, r**(5-4))) ), # d4
    ],

    6: [
        (1, min(dh*(r**d0), math.comb(r**(6-1)+d0-1, r**(6-1))) ),  # d1
        (1, min(dh*(r** (2*d0)), math.comb(r**(6-2)+d0-1, r**(6-2))) ),  # d2
        (1, min(dh*(r** (3*d0)), math.comb(r**(6-3)+d0-1, r**(6-3))) ),  # d3
        (1, min(dh*(r** (4*d0)), math.comb(r**(6-4)+d0-1, r**(6-4))) ), # d4
        (1, min(dh*(r** (5*d0)), math.comb(r**(6-5)+d0-1, r**(6-5))) ), # d5
    ],
}

# This is the KTB threshold.

# def bound(L, i, r, d0, dh):
#     return (1, min(dh * r**(i*d0), math.comb(r**(L-i) + d0 - 1, r**(L-i))))

# custom_bounds = {
#     L: [bound(L, i, r, d0, dh) for i in range(1, L)]
#     for L in range(1, 9)  # depths 1 through 8
# }

# Run the bounded frontier search

df_results = parameter_boundary_search(
    h_values=h_values_to_test, 
    max_width=40,        # Fallback if `h` not in layer_bounds
    min_width=1,         # Fallback if `h` not in layer_bounds
    exponent=r,          
    d_0=d0,              
    d_h=dh,              
    csv_filename=f"../data/raw/{d0}_{dh}_r{r}_architectures.csv",
    user_guesses=my_guesses,
    layer_bounds=custom_bounds  # Injecting the new feature here
)

Loading existing database from '../data/raw/2_1_r5_architectures.csv'...

--- RANDOM SEARCH: h=2, exponent=5 ---
  Target Ambient Dimension: 6
  Generating candidate pool...
  Using global bounds: min_width=1, max_width=40

  Pruned 36 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.

--- RANDOM SEARCH: h=3, exponent=5 ---
  Target Ambient Dimension: 26
  Generating candidate pool...
  Using global bounds: min_width=1, max_width=40

  Pruned 1552 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.

--- RANDOM SEARCH: h=4, exponent=5 ---
  Target Ambient Dimension: 126
  Generating candidate pool...
  Using global bounds: min_width=1, max_width=40

  Pruned 62520 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.

--- RANDOM SEARCH: h=5, exponent=5 ---
  Target Ambient Dimension: 626
  Generating candidate pool...
  Using custom per-layer bounds: [(1, 25), (1, 126), (1, 26), (1, 6)]

  Pruned 178610 impossible/redundant architectures.
  Starting sequential evaluation on 308733 viable candidates.
  [SHORT] [2, 13, 124, 20, 4, 1] -> Rank: 504/626 (Params: 4202)
    [Downward Pruned] 77885 subsets removed from queue.
  [SHORT] [2, 10, 104, 6, 5, 1] -> Rank: 180/626 (Params: 1719)
    [Downward Pruned] 2031 subsets removed from queue.
  [SHORT] [2, 13, 65, 11, 5, 1] -> Rank: 330/626 (Params: 1646)
    [Downward Pruned] 1831 subsets removed from queue.
  [SHORT] [2, 19, 108, 23, 2, 1] -> Rank: 252/626 (Params: 4622)
    [Downward Pruned] 24071 subsets removed from queue.
  [SHORT] [2, 14, 51, 12, 4, 1] -> Rank: 348/626 (Params: 1406)
    [Downward Pruned] 263 subsets removed from queue.
  [SHORT] [2, 1, 117, 23, 2, 1] -> Rank: 2/626 (Params: 2858)
    [Downward Pruned] 53 subsets removed from queue.
  [SHORT] [2, 8, 111, 5, 5, 1] -> Rank: 150/626 (Params: 1489)
    [Downward Pruned] 209 subsets removed from queue.
  [SHORT] [2, 23, 110, 11, 1, 1] -> Rank: 126/626 (Params: 3798)
    [Downward Pruned] 3211 subsets removed from queue.
  [FULL ] [2, 13, 43, 22, 5, 1] -> Rank: 626/626 (Params: 1646)
    [Upward Pruned] 671 supersets removed from queue.
  [SHORT] [2, 10, 43, 23, 4, 1] -> Rank: 504/626 (Params: 1535)
    [Downward Pruned] 179 subsets removed from queue.
  [FULL ] [2, 6, 54, 21, 6, 1] -> Rank: 626/626 (Params: 1602)
    [Upward Pruned] 729 supersets removed from queue.
  [SHORT] [2, 13, 91, 7, 5, 1] -> Rank: 210/626 (Params: 1886)
    [Downward Pruned] 798 subsets removed from queue.
  [SHORT] [2, 1, 82, 12, 6, 1] -> Rank: 2/626 (Params: 1146)
    [Downward Pruned] 273 subsets removed from queue.
  [SHORT] [2, 15, 125, 21, 1, 1] -> Rank: 126/626 (Params: 4552)
    [Downward Pruned] 1135 subsets removed from queue.
  [SHORT] [2, 1, 46, 26, 5, 1] -> Rank: 2/626 (Params: 1379)
    [Downward Pruned] 173 subsets removed from queue.
  [SHORT] [2, 14, 47, 20, 3, 1] -> Rank: 378/626 (Params: 1689)
    [Downward Pruned] 55 subsets removed from queue.
  [SHORT] [2, 17, 58, 26, 1, 1] -> Rank: 126/626 (Params: 2555)
    [Downward Pruned] 899 subsets removed from queue.
  [SHORT] [2, 23, 61, 24, 1, 1] -> Rank: 126/626 (Params: 2938)
    [Downward Pruned] 1184 subsets removed from queue.
  [SHORT] [2, 22, 101, 7, 4, 1] -> Rank: 203/626 (Params: 3005)
    [Downward Pruned] 8812 subsets removed from queue.
  [SHORT] [2, 13, 89, 26, 2, 1] -> Rank: 252/626 (Params: 3551)
    [Downward Pruned] 3062 subsets removed from queue.
  [SHORT] [2, 9, 74, 19, 6, 1] -> Rank: 589/626 (Params: 2210)
    [Downward Pruned] 6967 subsets removed from queue.
  [SHORT] [2, 22, 109, 5, 6, 1] -> Rank: 155/626 (Params: 3023)
    [Downward Pruned] 9782 subsets removed from queue.
  [SHORT] [2, 24, 91, 7, 5, 1] -> Rank: 210/626 (Params: 2909)
    [Downward Pruned] 4130 subsets removed from queue.
  [SHORT] [2, 13, 53, 6, 6, 1] -> Rank: 186/626 (Params: 1075)
    [Downward Pruned] 51 subsets removed from queue.
  [SHORT] [2, 19, 124, 20, 6, 1] -> Rank: 620/626 (Params: 5000)
    [Downward Pruned] 57668 subsets removed from queue.
  [SHORT] [2, 21, 107, 6, 2, 1] -> Rank: 162/626 (Params: 2945)
    [Downward Pruned] 11 subsets removed from queue.
  [SHORT] [2, 1, 91, 21, 5, 1] -> Rank: 2/626 (Params: 2114)
    [Downward Pruned] 134 subsets removed from queue.
  [SHORT] [2, 24, 65, 24, 1, 1] -> Rank: 126/626 (Params: 3193)
    [Downward Pruned] 662 subsets removed from queue.
  [FULL ] [2, 9, 120, 22, 5, 1] -> Rank: 626/626 (Params: 3853)
    [Upward Pruned] 27 supersets removed from queue.
  [SHORT] [2, 22, 124, 22, 2, 1] -> Rank: 252/626 (Params: 5546)
    [Downward Pruned] 7488 subsets removed from queue.
  [SHORT] [2, 24, 85, 13, 6, 1] -> Rank: 403/626 (Params: 3277)
    [Downward Pruned] 6999 subsets removed from queue.
  [SHORT] [2, 25, 95, 8, 3, 1] -> Rank: 224/626 (Params: 3212)
    [Downward Pruned] 1539 subsets removed from queue.
  [SHORT] [2, 12, 120, 26, 1, 1] -> Rank: 126/626 (Params: 4611)
    [Downward Pruned] 1250 subsets removed from queue.
  [SHORT] [2, 25, 98, 14, 5, 1] -> Rank: 420/626 (Params: 3947)
    [Downward Pruned] 5484 subsets removed from queue.
  [SHORT] [2, 23, 121, 24, 2, 1] -> Rank: 252/626 (Params: 5783)
    [Downward Pruned] 4326 subsets removed from queue.
  [FULL ] [2, 23, 32, 21, 5, 1] -> Rank: 626/626 (Params: 1564)
    [Upward Pruned] 119 supersets removed from queue.
  [SHORT] [2, 3, 71, 25, 3, 1] -> Rank: 363/626 (Params: 2072)
    [Downward Pruned] 391 subsets removed from queue.
  [SHORT] [2, 15, 124, 23, 2, 1] -> Rank: 252/626 (Params: 4790)
    [Downward Pruned] 89 subsets removed from queue.
  [SHORT] [2, 18, 125, 4, 1, 1] -> Rank: 104/626 (Params: 2791)
    [Downward Pruned] 11 subsets removed from queue.
  [SHORT] [2, 10, 101, 24, 4, 1] -> Rank: 504/626 (Params: 3554)
    [Downward Pruned] 4274 subsets removed from queue.
  [SHORT] [2, 25, 56, 21, 4, 1] -> Rank: 504/626 (Params: 2714)
    [Downward Pruned] 2084 subsets removed from queue.
  [FULL ] [2, 5, 47, 22, 6, 1] -> Rank: 626/626 (Params: 1417)
    [Upward Pruned] 114 supersets removed from queue.
  [SHORT] [2, 24, 112, 4, 2, 1] -> Rank: 108/626 (Params: 3194)
    [Downward Pruned] 111 subsets removed from queue.
  [SHORT] [2, 14, 105, 26, 4, 1] -> Rank: 504/626 (Params: 4336)
    [Downward Pruned] 6472 subsets removed from queue.
  [SHORT] [2, 19, 122, 21, 3, 1] -> Rank: 378/626 (Params: 4984)
    [Downward Pruned] 567 subsets removed from queue.
  [FULL ] [2, 20, 68, 21, 5, 1] -> Rank: 626/626 (Params: 2938)
    [Upward Pruned] 58 supersets removed from queue.
  [SHORT] [2, 22, 98, 17, 4, 1] -> Rank: 493/626 (Params: 3938)
    [Downward Pruned] 755 subsets removed from queue.
  [SHORT] [2, 4, 108, 21, 4, 1] -> Rank: 504/626 (Params: 2796)
    [Downward Pruned] 11 subsets removed from queue.
  [SHORT] [2, 1, 103, 23, 5, 1] -> Rank: 2/626 (Params: 2594)
    [Downward Pruned] 125 subsets removed from queue.
  [FULL ] [2, 17, 29, 25, 5, 1] -> Rank: 626/626 (Params: 1382)
    [Upward Pruned] 127 supersets removed from queue.
  [SHORT] [2, 3, 115, 23, 3, 1] -> Rank: 363/626 (Params: 3068)
    [Downward Pruned] 59 subsets removed from queue.
  [SHORT] [2, 15, 107, 25, 1, 1] -> Rank: 126/626 (Params: 4336)
    [Downward Pruned] 52 subsets removed from queue.
  [SHORT] [2, 22, 125, 4, 6, 1] -> Rank: 124/626 (Params: 3324)
    [Downward Pruned] 1145 subsets removed from queue.
  [SHORT] [2, 24, 59, 20, 6, 1] -> Rank: 620/626 (Params: 2770)
    [Downward Pruned] 1513 subsets removed from queue.
  [SHORT] [2, 22, 124, 9, 4, 1] -> Rank: 261/626 (Params: 3928)
    [Downward Pruned] 677 subsets removed from queue.
  [SHORT] [2, 25, 126, 5, 2, 1] -> Rank: 135/626 (Params: 3842)
    [Downward Pruned] 734 subsets removed from queue.
  [SHORT] [2, 23, 124, 11, 6, 1] -> Rank: 341/626 (Params: 4334)
    [Downward Pruned] 2894 subsets removed from queue.
  [SHORT] [2, 25, 88, 5, 6, 1] -> Rank: 155/626 (Params: 2726)
    [Downward Pruned] 254 subsets removed from queue.
  [FULL ] [2, 16, 26, 22, 5, 1] -> Rank: 626/626 (Params: 1135)
    [Upward Pruned] 476 supersets removed from queue.
  [FULL ] [2, 4, 36, 21, 5, 1] -> Rank: 626/626 (Params: 1018)
    [Upward Pruned] 3934 supersets removed from queue.
  [SHORT] [2, 22, 114, 19, 3, 1] -> Rank: 378/626 (Params: 4778)
    [Downward Pruned] 617 subsets removed from queue.
  [SHORT] [2, 2, 75, 22, 5, 1] -> Rank: 128/626 (Params: 1919)
    [Downward Pruned] 69 subsets removed from queue.
  [SHORT] [2, 4, 125, 17, 5, 1] -> Rank: 510/626 (Params: 2723)
    [Downward Pruned] 203 subsets removed from queue.
  [SHORT] [2, 17, 110, 23, 4, 1] -> Rank: 504/626 (Params: 4530)
    [Downward Pruned] 1317 subsets removed from queue.
  [FULL ] [2, 23, 25, 22, 5, 1] -> Rank: 626/626 (Params: 1286)
    [Upward Pruned] 17 supersets removed from queue.
  [SHORT] [2, 16, 125, 13, 4, 1] -> Rank: 377/626 (Params: 3713)
    [Downward Pruned] 319 subsets removed from queue.
  [SHORT] [2, 18, 123, 25, 3, 1] -> Rank: 378/626 (Params: 5403)
    [Downward Pruned] 2740 subsets removed from queue.
  [SHORT] [2, 23, 77, 21, 4, 1] -> Rank: 504/626 (Params: 3522)
    [Downward Pruned] 641 subsets removed from queue.
  [SHORT] [2, 16, 116, 24, 4, 1] -> Rank: 504/626 (Params: 4772)
    [Downward Pruned] 593 subsets removed from queue.
  [SHORT] [2, 8, 17, 25, 5, 1] -> Rank: 610/626 (Params: 707)
    [Downward Pruned] 10 subsets removed from queue.
  [SHORT] [2, 7, 125, 24, 1, 1] -> Rank: 126/626 (Params: 3914)
    [Downward Pruned] 27 subsets removed from queue.
  [SHORT] [2, 24, 91, 19, 4, 1] -> Rank: 504/626 (Params: 4041)
    [Downward Pruned] 833 subsets removed from queue.
  [SHORT] [2, 24, 82, 15, 5, 1] -> Rank: 450/626 (Params: 3326)
    [Downward Pruned] 114 subsets removed from queue.
  [SHORT] [2, 24, 54, 26, 2, 1] -> Rank: 252/626 (Params: 2802)
    [Downward Pruned] 458 subsets removed from queue.
  [SHORT] [2, 18, 95, 26, 1, 1] -> Rank: 126/626 (Params: 4243)
    [Downward Pruned] 151 subsets removed from queue.
  [SHORT] [2, 24, 121, 6, 5, 1] -> Rank: 180/626 (Params: 3713)
    [Downward Pruned] 459 subsets removed from queue.
  [SHORT] [2, 25, 67, 15, 4, 1] -> Rank: 435/626 (Params: 2794)
    [Downward Pruned] 43 subsets removed from queue.
  [SHORT] [2, 20, 83, 25, 2, 1] -> Rank: 252/626 (Params: 3827)
    [Downward Pruned] 115 subsets removed from queue.
  [SHORT] [2, 19, 86, 24, 3, 1] -> Rank: 378/626 (Params: 3811)
    [Downward Pruned] 143 subsets removed from queue.
  [FULL ] [2, 7, 28, 21, 5, 1] -> Rank: 626/626 (Params: 908)
    [Upward Pruned] 623 supersets removed from queue.
  [SHORT] [2, 2, 104, 21, 6, 1] -> Rank: 128/626 (Params: 2528)
    [Downward Pruned] 157 subsets removed from queue.
  [SHORT] [2, 3, 117, 26, 6, 1] -> Rank: 623/626 (Params: 3561)
    [Downward Pruned] 2492 subsets removed from queue.
  [SHORT] [2, 22, 104, 13, 6, 1] -> Rank: 403/626 (Params: 3768)
    [Downward Pruned] 185 subsets removed from queue.
  [SHORT] [2, 22, 86, 18, 6, 1] -> Rank: 558/626 (Params: 3598)
    [Downward Pruned] 659 subsets removed from queue.
  [SHORT] [2, 21, 99, 18, 5, 1] -> Rank: 540/626 (Params: 3998)
    [Downward Pruned] 129 subsets removed from queue.
  [SHORT] [2, 11, 124, 26, 1, 1] -> Rank: 126/626 (Params: 4637)
    [Downward Pruned] 58 subsets removed from queue.
  [SHORT] [2, 25, 108, 13, 4, 1] -> Rank: 377/626 (Params: 4210)
    [Downward Pruned] 763 subsets removed from queue.
  [SHORT] [2, 24, 125, 16, 2, 1] -> Rank: 252/626 (Params: 5082)
    [Downward Pruned] 658 subsets removed from queue.
  [SHORT] [2, 19, 77, 26, 1, 1] -> Rank: 126/626 (Params: 3530)
    [Downward Pruned] 22 subsets removed from queue.
  [SHORT] [2, 21, 75, 22, 4, 1] -> Rank: 504/626 (Params: 3359)
    [Downward Pruned] 221 subsets removed from queue.
  [SHORT] [2, 24, 109, 3, 6, 1] -> Rank: 93/626 (Params: 3015)
    [Downward Pruned] 62 subsets removed from queue.
  [SHORT] [2, 24, 55, 25, 3, 1] -> Rank: 378/626 (Params: 2821)
    [Downward Pruned] 333 subsets removed from queue.
  [SHORT] [2, 25, 51, 10, 6, 1] -> Rank: 310/626 (Params: 1901)
    [Downward Pruned] 54 subsets removed from queue.
  [SHORT] [2, 25, 70, 26, 3, 1] -> Rank: 378/626 (Params: 3701)
    [Downward Pruned] 1815 subsets removed from queue.
  [FULL ] [2, 7, 22, 26, 5, 1] -> Rank: 626/626 (Params: 875)
    [Upward Pruned] 90 supersets removed from queue.
  [SHORT] [2, 25, 113, 1, 3, 1] -> Rank: 26/626 (Params: 2994)
    [Downward Pruned] 4 subsets removed from queue.
  [SHORT] [2, 19, 100, 23, 3, 1] -> Rank: 378/626 (Params: 4310)
    [Downward Pruned] 27 subsets removed from queue.
  [SHORT] [2, 23, 126, 10, 3, 1] -> Rank: 280/626 (Params: 4237)
    [Downward Pruned] 499 subsets removed from queue.
  [SHORT] [2, 25, 44, 26, 4, 1] -> Rank: 504/626 (Params: 2402)
    [Downward Pruned] 276 subsets removed from queue.
  [SHORT] [2, 16, 125, 24, 4, 1] -> Rank: 504/626 (Params: 5132)
    [Downward Pruned] 1062 subsets removed from queue.
  [SHORT] [2, 25, 103, 18, 2, 1] -> Rank: 252/626 (Params: 4517)
    [Downward Pruned] 321 subsets removed from queue.
  [SHORT] [2, 21, 116, 18, 4, 1] -> Rank: 504/626 (Params: 4642)
    [Downward Pruned] 229 subsets removed from queue.
  [SHORT] [2, 25, 120, 6, 3, 1] -> Rank: 168/626 (Params: 3791)
    [Downward Pruned] 90 subsets removed from queue.
  [SHORT] [2, 23, 69, 20, 5, 1] -> Rank: 600/626 (Params: 3118)
    [Downward Pruned] 109 subsets removed from queue.
  [SHORT] [2, 25, 121, 17, 1, 1] -> Rank: 126/626 (Params: 5150)
    [Downward Pruned] 181 subsets removed from queue.
  [SHORT] [2, 23, 65, 24, 4, 1] -> Rank: 504/626 (Params: 3201)
    [Downward Pruned] 314 subsets removed from queue.
  [SHORT] [2, 23, 111, 25, 4, 1] -> Rank: 504/626 (Params: 5478)
    [Downward Pruned] 3585 subsets removed from queue.
  [SHORT] [2, 25, 114, 24, 1, 1] -> Rank: 126/626 (Params: 5661)
    [Downward Pruned] 528 subsets removed from queue.
  [SHORT] [2, 19, 125, 18, 5, 1] -> Rank: 540/626 (Params: 4758)
    [Downward Pruned] 291 subsets removed from queue.
  [SHORT] [2, 25, 75, 12, 6, 1] -> Rank: 372/626 (Params: 2903)
    [Downward Pruned] 189 subsets removed from queue.
  [SHORT] [2, 23, 125, 7, 4, 1] -> Rank: 203/626 (Params: 3828)
    [Downward Pruned] 15 subsets removed from queue.
  [SHORT] [2, 19, 118, 25, 4, 1] -> Rank: 504/626 (Params: 5334)
    [Downward Pruned] 240 subsets removed from queue.
  [SHORT] [2, 24, 122, 21, 2, 1] -> Rank: 252/626 (Params: 5582)
    [Downward Pruned] 215 subsets removed from queue.
  [SHORT] [2, 23, 70, 18, 6, 1] -> Rank: 558/626 (Params: 3030)
    [Downward Pruned] 57 subsets removed from queue.
  [SHORT] [2, 20, 126, 14, 2, 1] -> Rank: 252/626 (Params: 4354)
    [Downward Pruned] 159 subsets removed from queue.
  [SHORT] [2, 25, 92, 17, 5, 1] -> Rank: 510/626 (Params: 4004)
    [Downward Pruned] 472 subsets removed from queue.
  [SHORT] [2, 25, 86, 16, 6, 1] -> Rank: 496/626 (Params: 3678)
    [Downward Pruned] 399 subsets removed from queue.
  [SHORT] [2, 20, 125, 17, 4, 1] -> Rank: 493/626 (Params: 4737)
    [Downward Pruned] 114 subsets removed from queue.
  [SHORT] [2, 24, 65, 24, 4, 1] -> Rank: 504/626 (Params: 3268)
    [Downward Pruned] 77 subsets removed from queue.
  [SHORT] [2, 25, 107, 16, 2, 1] -> Rank: 252/626 (Params: 4471)
    [Downward Pruned] 11 subsets removed from queue.
  [SHORT] [2, 13, 110, 26, 1, 1] -> Rank: 126/626 (Params: 4343)
    [Downward Pruned] 4 subsets removed from queue.
  [SHORT] [2, 25, 110, 7, 3, 1] -> Rank: 196/626 (Params: 3594)
    [Downward Pruned] 5 subsets removed from queue.
  [SHORT] [2, 24, 119, 22, 2, 1] -> Rank: 252/626 (Params: 5568)
    [Downward Pruned] 53 subsets removed from queue.
  [SHORT] [2, 25, 93, 16, 4, 1] -> Rank: 464/626 (Params: 3931)
    [Downward Pruned] 7 subsets removed from queue.
  [SHORT] [2, 10, 126, 24, 1, 1] -> Rank: 126/626 (Params: 4329)
    [Downward Pruned] 99 subsets removed from queue.
  [SHORT] [2, 13, 125, 18, 6, 1] -> Rank: 558/626 (Params: 4015)
    [Downward Pruned] 181 subsets removed from queue.
  [SHORT] [2, 24, 89, 19, 6, 1] -> Rank: 589/626 (Params: 3995)
    [Downward Pruned] 504 subsets removed from queue.
  [FULL ] [2, 15, 21, 24, 5, 1] -> Rank: 626/626 (Params: 974)
    [Upward Pruned] 118 supersets removed from queue.
  [SHORT] [2, 25, 99, 7, 5, 1] -> Rank: 210/626 (Params: 3258)
    [Downward Pruned] 7 subsets removed from queue.
  [SHORT] [2, 23, 104, 15, 5, 1] -> Rank: 450/626 (Params: 4078)
    [Downward Pruned] 67 subsets removed from queue.
  [SHORT] [2, 15, 126, 25, 4, 1] -> Rank: 504/626 (Params: 5174)
    [Downward Pruned] 1007 subsets removed from queue.
  [SHORT] [2, 25, 112, 16, 6, 1] -> Rank: 496/626 (Params: 4744)
    [Downward Pruned] 2053 subsets removed from queue.
  [SHORT] [2, 3, 126, 5, 5, 1] -> Rank: 123/626 (Params: 1044)
    [Downward Pruned] 8 subsets removed from queue.
  [SHORT] [2, 25, 38, 19, 5, 1] -> Rank: 570/626 (Params: 1822)
    [Downward Pruned] 2 subsets removed from queue.
  [SHORT] [2, 25, 71, 23, 3, 1] -> Rank: 378/626 (Params: 3530)
    [Downward Pruned] 15 subsets removed from queue.
  [SHORT] [2, 25, 114, 15, 6, 1] -> Rank: 465/626 (Params: 4706)
    [Downward Pruned] 297 subsets removed from queue.
  [SHORT] [2, 18, 126, 1, 4, 1] -> Rank: 26/626 (Params: 2438)
    [Downward Pruned] 2 subsets removed from queue.
  [SHORT] [2, 25, 93, 21, 2, 1] -> Rank: 252/626 (Params: 4372)
    [Downward Pruned] 65 subsets removed from queue.
  [SHORT] [2, 24, 124, 14, 5, 1] -> Rank: 420/626 (Params: 4835)
    [Downward Pruned] 581 subsets removed from queue.
  [SHORT] [2, 24, 100, 25, 1, 1] -> Rank: 126/626 (Params: 4974)
    [Downward Pruned] 29 subsets removed from queue.
  [SHORT] [2, 21, 118, 25, 4, 1] -> Rank: 504/626 (Params: 5574)
    [Downward Pruned] 237 subsets removed from queue.
  [SHORT] [2, 22, 111, 26, 3, 1] -> Rank: 378/626 (Params: 5453)
    [Downward Pruned] 1015 subsets removed from queue.
  [SHORT] [2, 25, 116, 11, 5, 1] -> Rank: 330/626 (Params: 4286)
    [Downward Pruned] 63 subsets removed from queue.
  [SHORT] [2, 24, 88, 26, 3, 1] -> Rank: 378/626 (Params: 4529)
    [Downward Pruned] 264 subsets removed from queue.
  [SHORT] [2, 24, 90, 17, 6, 1] -> Rank: 527/626 (Params: 3846)
    [Downward Pruned] 4 subsets removed from queue.
  [SHORT] [2, 24, 121, 25, 3, 1] -> Rank: 378/626 (Params: 6055)
    [Downward Pruned] 768 subsets removed from queue.
  [SHORT] [2, 16, 84, 26, 4, 1] -> Rank: 504/626 (Params: 3668)
    [Downward Pruned] 79 subsets removed from queue.
  [SHORT] [2, 10, 126, 18, 5, 1] -> Rank: 540/626 (Params: 3643)
    [Downward Pruned] 164 subsets removed from queue.
  [SHORT] [2, 25, 120, 2, 6, 1] -> Rank: 56/626 (Params: 3308)
    [Downward Pruned] 39 subsets removed from queue.
  [SHORT] [2, 20, 78, 20, 5, 1] -> Rank: 600/626 (Params: 3265)
    [Downward Pruned] 8 subsets removed from queue.
  [SHORT] [2, 25, 122, 19, 1, 1] -> Rank: 126/626 (Params: 5438)
    [Downward Pruned] 27 subsets removed from queue.
  [SHORT] [2, 25, 109, 18, 3, 1] -> Rank: 378/626 (Params: 4794)
    [Downward Pruned] 66 subsets removed from queue.
  [SHORT] [2, 20, 126, 17, 3, 1] -> Rank: 378/626 (Params: 4756)
    [Downward Pruned] 64 subsets removed from queue.
  [SHORT] [2, 25, 117, 8, 2, 1] -> Rank: 216/626 (Params: 3929)
    [Downward Pruned] 1 subsets removed from queue.
  [SHORT] [2, 21, 126, 25, 4, 1] -> Rank: 504/626 (Params: 5942)
    [Downward Pruned] 842 subsets removed from queue.
  [SHORT] [2, 25, 87, 18, 6, 1] -> Rank: 558/626 (Params: 3905)
    [Downward Pruned] 177 subsets removed from queue.
  [SHORT] [2, 24, 101, 26, 2, 1] -> Rank: 252/626 (Params: 5152)
    [Downward Pruned] 51 subsets removed from queue.
  [SHORT] [2, 24, 108, 19, 5, 1] -> Rank: 570/626 (Params: 4792)
    [Downward Pruned] 285 subsets removed from queue.
  [SHORT] [2, 7, 107, 26, 4, 1] -> Rank: 504/626 (Params: 3653)
    [Downward Pruned] 7 subsets removed from queue.
  [SHORT] [2, 25, 121, 18, 5, 1] -> Rank: 540/626 (Params: 5348)
    [Downward Pruned] 794 subsets removed from queue.
  [SHORT] [2, 24, 125, 16, 3, 1] -> Rank: 378/626 (Params: 5099)
    [Downward Pruned] 45 subsets removed from queue.
  [SHORT] [2, 22, 106, 26, 4, 1] -> Rank: 504/626 (Params: 5240)
    [Downward Pruned] 422 subsets removed from queue.
  [SHORT] [2, 22, 120, 19, 5, 1] -> Rank: 570/626 (Params: 5064)
    [Downward Pruned] 44 subsets removed from queue.
  [SHORT] [2, 21, 112, 19, 6, 1] -> Rank: 589/626 (Params: 4642)
    [Downward Pruned] 135 subsets removed from queue.
  [SHORT] [2, 24, 110, 26, 1, 1] -> Rank: 126/626 (Params: 5575)
    [Downward Pruned] 17 subsets removed from queue.
  [SHORT] [2, 3, 126, 26, 1, 1] -> Rank: 123/626 (Params: 3687)
    [Downward Pruned] 5 subsets removed from queue.
  [SHORT] [2, 23, 93, 26, 3, 1] -> Rank: 378/626 (Params: 4684)
    [Downward Pruned] 4 subsets removed from queue.
  [SHORT] [2, 15, 109, 26, 4, 1] -> Rank: 504/626 (Params: 4607)
    [Downward Pruned] 31 subsets removed from queue.
  [SHORT] [2, 20, 118, 12, 6, 1] -> Rank: 372/626 (Params: 3894)

In [52]:
# # Looped version for searches

# for d0 in range(1,10):
#     for dh in range(1,10):
#         for r in range(1,10):
#             h_values_to_test = [2,3] 
#             my_guesses = {}
#             # Format: { h_value: [(min1, max1), (min2, max2), ...] }
#             custom_bounds = {
#                 6: [
#                     (3, 4),  # d1
#                     (3, 10),  # d2
#                     (5, 28),  # d3
#                     (9, 82), # d4
#                     (6, 18)  # d5
#                 ],
#             }

#             df_results = parameter_boundary_search(
#                 h_values=h_values_to_test, 
#                 max_width=300,        # Fallback if `h` not in layer_bounds
#                 min_width=1,         # Fallback if `h` not in layer_bounds
#                 exponent=r,          
#                 d_0=d0,              
#                 d_h=dh,              
#                 csv_filename=f"../data/raw/{d0}_{dh}_r{r}_architectures.csv",
#                 user_guesses=my_guesses,
#                 layer_bounds=custom_bounds  # Injecting the new feature here
#             )

In [53]:
# Display the minimal architectures found so far
print("\n=== CURRENT MINIMAL FILLING ARCHITECTURES IN DATABASE ===")
if not df_results.empty:
    minimal_archs = df_results[df_results['is_minimal'] == True]
    
    if not minimal_archs.empty:
        # Sort by parameters for easier reading
        minimal_archs = minimal_archs.sort_values(by="num_parameters")
        print(minimal_archs[["architecture", "num_parameters", "dimension_computed"]].to_string(index=False))
    else:
        print("No minimal full architectures found matching the criteria.")
else:
    print("Database is empty.")

=== CURRENT MINIMAL FILLING ARCHITECTURES IN DATABASE ===
          architecture  num_parameters  dimension_computed
             [2, 3, 1]             9.0                 6.0
          [2, 4, 6, 1]            38.0                26.0
          [2, 5, 5, 1]            40.0                26.0
      [2, 5, 11, 7, 1]           149.0               126.0
      [2, 4, 9, 11, 1]           154.0               126.0
      [2, 4, 14, 6, 1]           154.0               126.0
      [2, 5, 14, 5, 1]           155.0               126.0
      [2, 5, 9, 10, 1]           155.0               126.0
       [2, 6, 9, 9, 1]           156.0               126.0
      [2, 4, 7, 15, 1]           156.0               126.0
      [2, 4, 16, 5, 1]           157.0               126.0
      [2, 4, 8, 13, 1]           157.0               126.0
      [2, 5, 7, 14, 1]           157.0               126.0
     [2, 4, 10, 10, 1]           158.0               126.0
      [2, 4, 6, 18, 1]           158.0               126.0
      [2, 4, 13, 7, 1]           158.0               126.0
      [2, 6, 7, 13, 1]           158.0               126.0
      [2, 5, 8, 12, 1]           158.0               126.0
      [2, 6, 8, 11, 1]           159.0               126.0
      [2, 5, 6, 17, 1]           159.0               126.0
      [2, 5, 10, 9, 1]           159.0               126.0
      [2, 5, 13, 6, 1]           159.0               126.0
      [2, 6, 6, 16, 1]           160.0               126.0
      [2, 4, 12, 8, 1]           160.0               126.0
      [2, 6, 13, 5, 1]           160.0               126.0
      [2, 4, 5, 22, 1]           160.0               126.0
      [2, 6, 10, 8, 1]           160.0               126.0
      [2, 4, 11, 9, 1]           160.0               126.0
      [2, 5, 5, 21, 1]           161.0               126.0
      [2, 6, 12, 6, 1]           162.0               126.0
  [2, 4, 17, 26, 6, 1]           680.0               626.0
  [2, 5, 18, 25, 5, 1]           680.0               626.0
  [2, 5, 18, 24, 6, 1]           682.0               626.0
  [2, 4, 18, 26, 5, 1]           683.0               626.0
  [2, 5, 19, 23, 6, 1]           686.0               626.0
  [2, 6, 16, 26, 6, 1]           686.0               626.0
  [2, 5, 19, 24, 5, 1]           686.0               626.0
  [2, 4, 18, 25, 6, 1]           686.0               626.0
  [2, 6, 20, 22, 5, 1]           687.0               626.0
  [2, 5, 20, 22, 6, 1]           688.0               626.0
  [2, 5, 21, 21, 6, 1]           688.0               626.0
  [2, 4, 19, 25, 5, 1]           689.0               626.0
  [2, 6, 21, 21, 5, 1]           689.0               626.0
  [2, 4, 22, 21, 6, 1]           690.0               626.0
  [2, 5, 20, 23, 5, 1]           690.0               626.0
  [2, 4, 19, 24, 6, 1]           690.0               626.0
  [2, 4, 14, 31, 6, 1]           690.0               626.0
  [2, 6, 17, 26, 5, 1]           691.0               626.0
  [2, 5, 21, 22, 5, 1]           692.0               626.0
  [2, 4, 21, 22, 6, 1]           692.0               626.0
  [2, 4, 20, 23, 6, 1]           692.0               626.0
  [2, 5, 22, 21, 5, 1]           692.0               626.0
  [2, 4, 23, 21, 5, 1]           693.0               626.0
  [2, 4, 20, 24, 5, 1]           693.0               626.0
 [2, 4, 14, 22, 14, 1]           694.0               626.0
  [2, 4, 22, 22, 5, 1]           695.0               626.0
  [2, 6, 17, 25, 6, 1]           695.0               626.0
  [2, 4, 21, 23, 5, 1]           695.0               626.0
 [2, 4, 12, 20, 19, 1]           695.0               626.0
  [2, 4, 6, 24, 21, 1]           701.0               626.0
 [2, 4, 19, 21, 10, 1]           703.0               626.0
  [2, 4, 8, 15, 34, 1]           704.0               626.0
  [2, 4, 5, 18, 31, 1]           707.0               626.0
  [2, 4, 9, 27, 15, 1]           707.0               626.0
  [2, 4, 5, 28, 19, 1]           719.0               626.0
 [2, 4, 16, 18, 19, 1]           721.0               626.0
  [2, 4, 4, 21, 28, 1]           724.0               626.0
  [2, 8, 7, 21, 23, 1]           725.0               626.0
  [2, 8, 6, 31, 15, 1]           730.0               626.0
 [2, 4, 10, 23, 19, 1]           734.0               626.0
  [2, 4, 20, 22, 9, 1]           735.0               626.0
 [2, 8, 13, 20, 17, 1]           737.0               626.0
 [2, 4, 25, 17, 12, 1]           749.0               626.0
  [2, 9, 4, 24, 24, 1]           750.0               626.0
  [2, 4, 7, 37, 12, 1]           751.0               626.0
 [2, 16, 4, 19, 29, 1]           752.0               626.0
 [2, 6, 12, 30, 10, 1]           754.0               626.0
 [2, 11, 7, 34, 12, 1]           757.0               626.0
  [2, 4, 5, 20, 30, 1]           758.0               626.0
  [2, 6, 7, 20, 27, 1]           761.0               626.0
 [2, 6, 15, 25, 11, 1]           763.0               626.0
  [2, 13, 8, 37, 9, 1]           768.0               626.0
[2, 13, 10, 24, 15, 1]           771.0               626.0
 [2, 4, 21, 12, 33, 1]           773.0               626.0
  [2, 5, 23, 20, 9, 1]           774.0               626.0
 [2, 11, 5, 26, 21, 1]           774.0               626.0
 [2, 4, 19, 20, 15, 1]           779.0               626.0
 [2, 4, 16, 21, 17, 1]           782.0               626.0
 [2, 11, 14, 30, 6, 1]           782.0               626.0
 [2, 4, 15, 16, 28, 1]           784.0               626.0
 [2, 4, 17, 24, 12, 1]           784.0               626.0
[2, 10, 12, 19, 21, 1]           788.0               626.0
[2, 10, 11, 13, 37, 1]           791.0               626.0
 [2, 4, 13, 30, 11, 1]           791.0               626.0
 [2, 12, 11, 35, 7, 1]           793.0               626.0
 [2, 4, 22, 14, 26, 1]           794.0               626.0
 [2, 19, 6, 25, 19, 1]           796.0               626.0
[2, 10, 17, 11, 35, 1]           797.0               626.0
 [2, 20, 5, 34, 14, 1]           800.0               626.0
 [2, 5, 26, 15, 17, 1]           802.0               626.0
  [2, 5, 8, 19, 30, 1]           802.0               626.0
 [2, 6, 13, 28, 12, 1]           802.0               626.0
 [2, 4, 25, 11, 35, 1]           803.0               626.0
 [2, 4, 16, 14, 34, 1]           806.0               626.0
 [2, 4, 24, 12, 32, 1]           808.0               626.0
 [2, 4, 18, 16, 26, 1]           810.0               626.0
 [2, 6, 13, 13, 40, 1]           819.0               626.0
 [2, 4, 28, 13, 24, 1]           820.0               626.0
[2, 14, 14, 21, 14, 1]           826.0               626.0
 [2, 26, 4, 39, 13, 1]           832.0               626.0
 [2, 12, 8, 17, 32, 1]           832.0               626.0
 [2, 6, 18, 20, 17, 1]           837.0               626.0
 [2, 4, 16, 26, 13, 1]           839.0               626.0
 [2, 5, 15, 30, 10, 1]           845.0               626.0
[2, 16, 13, 22, 14, 1]           848.0               626.0
 [2, 13, 9, 33, 12, 1]           848.0               626.0
 [2, 15, 16, 25, 7, 1]           852.0               626.0
  [2, 4, 6, 35, 17, 1]           854.0               626.0
 [2, 18, 9, 34, 10, 1]           854.0               626.0
 [2, 8, 17, 15, 28, 1]           855.0               626.0
[2, 15, 11, 31, 10, 1]           856.0               626.0
 [2, 9, 17, 15, 27, 1]           858.0               626.0
  [2, 7, 11, 40, 8, 1]           859.0               626.0
 [2, 6, 10, 39, 10, 1]           862.0               626.0
  [2, 5, 4, 30, 23, 1]           863.0               626.0
[2, 12, 19, 13, 26, 1]           863.0               626.0
 [2, 4, 16, 29, 11, 1]           866.0               626.0
 [2, 5, 29, 12, 28, 1]           867.0               626.0
 [2, 5, 10, 38, 11, 1]           869.0               626.0
[2, 17, 10, 33, 10, 1]           874.0               626.0
 [2, 10, 5, 17, 40, 1]           875.0               626.0
 [2, 12, 5, 37, 16, 1]           877.0               626.0
  [2, 4, 4, 32, 22, 1]           878.0               626.0
 [2, 17, 4, 29, 22, 1]           878.0               626.0
[2, 13, 13, 16, 28, 1]           879.0               626.0
[2, 11, 12, 29, 13, 1]           892.0               626.0
[2, 11, 17, 19, 18, 1]           892.0               626.0
 [2, 4, 24, 16, 24, 1]           896.0               626.0
[2, 12, 15, 15, 31, 1]           925.0               626.0
 [2, 34, 5, 40, 12, 1]           930.0               626.0
 [2, 17, 17, 24, 8, 1]           931.0               626.0
 [2, 5, 10, 36, 14, 1]           938.0               626.0
 [2, 24, 5, 33, 18, 1]           945.0               626.0
 [2, 9, 22, 13, 32, 1]           950.0               626.0
[2, 14, 21, 15, 20, 1]           957.0               626.0
 [2, 36, 7, 18, 27, 1]           963.0               626.0
 [2, 39, 5, 23, 24, 1]           964.0               626.0
 [2, 33, 7, 26, 18, 1]           965.0               626.0
 [2, 9, 25, 16, 19, 1]           966.0               626.0
[2, 16, 12, 17, 30, 1]           968.0               626.0
 [2, 36, 4, 32, 19, 1]           971.0               626.0
[2, 21, 16, 21, 12, 1]           978.0               626.0
[2, 10, 26, 10, 40, 1]           980.0               626.0
 [2, 34, 7, 30, 15, 1]           981.0               626.0
[2, 20, 15, 13, 32, 1]           983.0               626.0
[2, 30, 10, 28, 12, 1]           988.0               626.0
[2, 23, 13, 13, 34, 1]           990.0               626.0
 [2, 9, 27, 13, 27, 1]           990.0               626.0
[2, 16, 18, 22, 12, 1]           992.0               626.0
[2, 22, 13, 14, 32, 1]           992.0               626.0
 [2, 4, 37, 14, 22, 1]          1004.0               626.0
 [2, 32, 4, 33, 20, 1]          1004.0               626.0
 [2, 32, 6, 17, 36, 1]          1006.0               626.0
[2, 23, 16, 16, 20, 1]          1010.0               626.0
 [2, 4, 36, 15, 20, 1]          1012.0               626.0
[2, 20, 16, 20, 16, 1]          1016.0               626.0
 [2, 28, 9, 24, 20, 1]          1024.0               626.0
[2, 30, 11, 26, 13, 1]          1027.0               626.0
[2, 19, 14, 18, 25, 1]          1031.0               626.0
 [2, 32, 7, 15, 40, 1]          1033.0               626.0
[2, 27, 11, 19, 24, 1]          1040.0               626.0
 [2, 27, 4, 38, 19, 1]          1055.0               626.0
[2, 28, 11, 21, 21, 1]          1057.0               626.0
 [2, 19, 16, 34, 5, 1]          1061.0               626.0
 [2, 37, 7, 17, 35, 1]          1082.0               626.0
[2, 30, 13, 16, 25, 1]          1083.0               626.0
[2, 22, 20, 19, 11, 1]          1084.0               626.0
[2, 36, 10, 22, 19, 1]          1089.0               626.0
[2, 34, 10, 32, 11, 1]          1091.0               626.0
[2, 33, 11, 14, 34, 1]          1093.0               626.0
[2, 25, 15, 15, 28, 1]          1098.0               626.0
 [2, 30, 12, 32, 9, 1]          1101.0               626.0
[2, 28, 13, 15, 31, 1]          1111.0               626.0
[2, 30, 12, 18, 25, 1]          1111.0               626.0
[2, 29, 13, 29, 10, 1]          1112.0               626.0
[2, 36, 12, 26, 11, 1]          1113.0               626.0
[2, 25, 19, 15, 19, 1]          1114.0               626.0
 [2, 18, 25, 19, 9, 1]          1141.0               626.0
[2, 21, 20, 19, 15, 1]          1142.0               626.0
 [2, 34, 12, 33, 8, 1]          1144.0               626.0
[2, 21, 21, 12, 32, 1]          1151.0               626.0
 [2, 37, 13, 27, 9, 1]          1158.0               626.0
 [2, 28, 16, 32, 5, 1]          1181.0               626.0
[2, 32, 16, 15, 23, 1]          1184.0               626.0
[2, 28, 18, 22, 10, 1]          1186.0               626.0
[2, 18, 20, 17, 25, 1]          1186.0               626.0
[2, 22, 23, 13, 25, 1]          1199.0               626.0
 [2, 25, 22, 20, 9, 1]          1229.0               626.0
[2, 34, 14, 26, 12, 1]          1232.0               626.0
[2, 33, 16, 19, 17, 1]          1238.0               626.0
 [2, 36, 16, 28, 5, 1]          1241.0               626.0
[2, 29, 19, 17, 18, 1]          1256.0               626.0
[2, 33, 16, 14, 30, 1]          1268.0               626.0
 [2, 35, 13, 39, 6, 1]          1272.0               626.0
[2, 30, 20, 14, 25, 1]          1315.0               626.0
[2, 16, 34, 10, 38, 1]          1334.0               626.0
[2, 26, 25, 16, 15, 1]          1357.0               626.0
[2, 25, 24, 18, 15, 1]          1367.0               626.0
[2, 12, 40, 16, 16, 1]          1416.0               626.0
[2, 31, 24, 18, 11, 1]          1447.0               626.0
[2, 35, 20, 12, 34, 1]          1452.0               626.0
[2, 34, 22, 11, 33, 1]          1454.0               626.0
[2, 37, 21, 16, 16, 1]          1459.0               626.0
[2, 31, 24, 16, 16, 1]          1462.0               626.0
[2, 17, 35, 14, 23, 1]          1464.0               626.0
[2, 29, 27, 12, 29, 1]          1542.0               626.0
[2, 33, 23, 18, 16, 1]          1543.0               626.0
 [2, 31, 26, 20, 8, 1]          1556.0               626.0
[2, 28, 31, 11, 34, 1]          1673.0               626.0
[2, 36, 28, 12, 28, 1]          1780.0               626.0
 [2, 24, 37, 20, 8, 1]          1844.0               626.0
 [2, 31, 35, 19, 8, 1]          1972.0               626.0

# Results of the Search

In [54]:
# %load is_unimodal.py

import ast

def is_unimodal(data):
    # 1. Parse the string into a list safely
    if isinstance(data, str):
        try:
            # ast.literal_eval safely evaluates strings containing Python literals
            data = ast.literal_eval(data)
        except (ValueError, SyntaxError):
            raise ValueError(f"Could not parse the string: '{data}'. Ensure it is formatted like '[1, 2, 3]'.")
            
    # 2. Validate the data type
    if not isinstance(data, list):
        raise TypeError("Input must be a list or a string representation of a list.")
        
    # 3. Core unimodal logic
    n = len(data)
    if n <= 2:
        return True
        
    i = 0
    
    # Phase 1: Walk up the non-decreasing slope
    while i + 1 < n and data[i] <= data[i + 1]:
        i += 1
        
    # Phase 2: Walk down the non-increasing slope
    while i + 1 < n and data[i] >= data[i + 1]:
        i += 1
        
    # Phase 3: Check if we reached the end
    return i == n - 1

In [55]:
USER_DEPTH = 5
d0=3
dL=1
r=3

df = pd.read_csv(f'../data/raw/{d0}_{dL}_r{r}_architectures.csv')
df['is_unimodal'] = df['architecture'].apply(is_unimodal)
print("--"*15 + "DISCOVERED FILLING ARCHITECTURES" + "--"*15)
display(df[(df['h']==USER_DEPTH) & (df['is_full_dimension'] == True)])
print(len(df[(df['h']==USER_DEPTH) & (df['is_full_dimension'] == True)]))

df = pd.read_csv(f'../data/raw/{d0}_{dL}_r{r}_architectures.csv')
df['is_unimodal'] = df['architecture'].apply(is_unimodal)
print("--"*15 + "DISCOVERED POTENTIAL MINIMAL FILLING ARCHITECTURES" + "--"*15)
display(df[(df['h']==USER_DEPTH) & (df['is_minimal'] == True)])
print(len(df[(df['h']==USER_DEPTH) & (df['is_minimal'] == True)]))

df = pd.read_csv(f'../data/raw/{d0}_{dL}_r{r}_architectures.csv')
df['is_unimodal'] = df['architecture'].apply(is_unimodal)
print("--"*15 + "DISCOVERED POTENTIAL NONUNIMODAL MINIMAL FILLING ARCHITECTURES" + "--"*15)
display(df[(df['h']==USER_DEPTH) & (df['is_minimal'] == True) & (df['is_unimodal']==False)])
print(len(df[(df['h']==USER_DEPTH) & (df['is_minimal'] == True) & (df['is_unimodal']==False)]))

------------------------------DISCOVERED FILLING ARCHITECTURES------------------------------

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,is_unimodal
635,5,3,"[3, 21, 14, 55, 47, 1]",3759,3403,3403,True,False,False
637,5,3,"[3, 20, 47, 46, 50, 1]",5512,3403,3403,True,False,False
640,5,3,"[3, 11, 44, 55, 48, 1]",5625,3403,3403,True,False,True
641,5,3,"[3, 42, 41, 53, 30, 1]",5641,3403,3403,True,False,False
642,5,3,"[3, 21, 49, 55, 42, 1]",6139,3403,3403,True,False,True
...,...,...,...,...,...,...,...,...,...
12247,5,3,"[3, 6, 48, 53, 13, 1]",3552,3403,3403,True,True,True
12250,5,3,"[3, 8, 45, 33, 51, 1]",3603,3403,3403,True,True,False
12251,5,3,"[3, 8, 33, 47, 36, 1]",3567,3403,3403,True,True,True
12255,5,3,"[3, 6, 35, 46, 37, 1]",3577,3403,3403,True,True,True
12258,5,3,"[3, 9, 33, 45, 38, 1]",3557,3403,3403,True,True,True

5508
------------------------------DISCOVERED POTENTIAL MINIMAL FILLING ARCHITECTURES------------------------------

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,is_unimodal
1345,5,3,"[3, 8, 37, 42, 39, 1]",3551,3403,3403,True,True,True
1442,5,3,"[3, 9, 37, 51, 25, 1]",3547,3403,3403,True,True,True
1625,5,3,"[3, 7, 43, 35, 48, 1]",3555,3403,3403,True,True,False
1784,5,3,"[3, 9, 38, 50, 25, 1]",3544,3403,3403,True,True,True
1962,5,3,"[3, 8, 36, 41, 42, 1]",3552,3403,3403,True,True,True
...,...,...,...,...,...,...,...,...,...
12247,5,3,"[3, 6, 48, 53, 13, 1]",3552,3403,3403,True,True,True
12250,5,3,"[3, 8, 45, 33, 51, 1]",3603,3403,3403,True,True,False
12251,5,3,"[3, 8, 33, 47, 36, 1]",3567,3403,3403,True,True,True
12255,5,3,"[3, 6, 35, 46, 37, 1]",3577,3403,3403,True,True,True
12258,5,3,"[3, 9, 33, 45, 38, 1]",3557,3403,3403,True,True,True

1630
------------------------------DISCOVERED POTENTIAL NONUNIMODAL MINIMAL FILLING ARCHITECTURES------------------------------

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,is_unimodal
1625,5,3,"[3, 7, 43, 35, 48, 1]",3555,3403,3403,True,True,False
2575,5,3,"[3, 7, 45, 37, 42, 1]",3597,3403,3403,True,True,False
2963,5,3,"[3, 6, 47, 35, 45, 1]",3565,3403,3403,True,True,False
3027,5,3,"[3, 6, 46, 35, 47, 1]",3596,3403,3403,True,True,False
3097,5,3,"[3, 15, 42, 36, 44, 1]",3815,3403,3403,True,True,False
...,...,...,...,...,...,...,...,...,...
12198,5,3,"[3, 13, 9, 54, 54, 1]",3612,3403,3403,True,True,False
12215,5,3,"[3, 8, 39, 37, 47, 1]",3565,3403,3403,True,True,False
12231,5,3,"[3, 10, 44, 36, 41, 1]",3571,3403,3403,True,True,False
12239,5,3,"[3, 13, 37, 34, 55, 1]",3703,3403,3403,True,True,False
12250,5,3,"[3, 8, 45, 33, 51, 1]",3603,3403,3403,True,True,False

195