# Examine .csv files

This notebook is a sandbox where one can analyze the results of the searches.

In [1]:
import ast
import pandas as pd

In [2]:
def is_unimodal(data):
    # data should be string formatted as '[1, 2, 3]'
    data = ast.literal_eval(data)
    n = len(data)
    
    if n <= 2:
        return True
    
    i = 0
    
    # walk up the non-decreasing slope
    while i + 1 < n and data[i] <= data[i + 1]:
        i += 1

    # walk down the non-increasing slope
    while i + 1 < n and data[i] >= data[i + 1]:
        i += 1
        
    # check if we reached the end
    return i == n - 1

In [3]:
df = pd.read_csv('2_1_architectures.csv')
df['is_unimodal'] = df['architecture'].apply(is_unimodal)

print("--"*15 + f"DISCOVERED COUNTEREXAMPLES TO THE MINIMAL UNIMODAL CONJECTURE" + "--"*15)
for depth in range(2,10):
    df_display = df[(df['h']==depth) & (df['is_minimal'] == True) & (df['is_unimodal']==False)]
    display(df_display)
    print(f"{len(df_display)} examples of depth {depth}")

------------------------------DISCOVERED COUNTEREXAMPLES TO THE MINIMAL UNIMODAL CONJECTURE------------------------------

Empty DataFrame
Columns: [h, exponent, architecture, num_parameters, dimension_computed, ambient_dimension, is_full_dimension, is_minimal, is_unimodal]
Index: []

0 examples of depth 2

Empty DataFrame
Columns: [h, exponent, architecture, num_parameters, dimension_computed, ambient_dimension, is_full_dimension, is_minimal, is_unimodal]
Index: []

0 examples of depth 3

Empty DataFrame
Columns: [h, exponent, architecture, num_parameters, dimension_computed, ambient_dimension, is_full_dimension, is_minimal, is_unimodal]
Index: []

0 examples of depth 4

Empty DataFrame
Columns: [h, exponent, architecture, num_parameters, dimension_computed, ambient_dimension, is_full_dimension, is_minimal, is_unimodal]
Index: []

0 examples of depth 5

Empty DataFrame
Columns: [h, exponent, architecture, num_parameters, dimension_computed, ambient_dimension, is_full_dimension, is_minimal, is_unimodal]
Index: []

0 examples of depth 6

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,is_unimodal
523,7,2,"[2, 3, 4, 5, 4, 6, 4, 1]",110,65,65,True,True,False

1 examples of depth 7

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,is_unimodal
5886,8,2,"[2, 3, 4, 5, 4, 8, 8, 4, 1]",190,129,129,True,True,False
5937,8,2,"[2, 3, 4, 5, 6, 5, 8, 5, 1]",183,129,129,True,True,False
6044,8,2,"[2, 3, 4, 5, 7, 6, 7, 3, 1]",181,129,129,True,True,False
6117,8,2,"[2, 3, 3, 5, 7, 6, 8, 3, 1]",182,129,129,True,True,False
6277,8,2,"[2, 3, 4, 4, 7, 6, 8, 3, 1]",179,129,129,True,True,False
6303,8,2,"[2, 3, 4, 5, 7, 5, 7, 5, 1]",183,129,129,True,True,False
6305,8,2,"[2, 3, 4, 6, 6, 5, 7, 7, 1]",199,129,129,True,True,False
6308,8,2,"[2, 3, 3, 6, 7, 6, 7, 3, 1]",183,129,129,True,True,False
6311,8,2,"[2, 3, 4, 4, 7, 6, 7, 5, 1]",186,129,129,True,True,False
6352,8,2,"[2, 3, 3, 4, 7, 6, 7, 6, 1]",187,129,129,True,True,False
6401,8,2,"[2, 3, 4, 6, 5, 8, 6, 3, 1]",181,129,129,True,True,False
6418,8,2,"[2, 3, 3, 4, 7, 6, 8, 4, 1]",181,129,129,True,True,False
6428,8,2,"[2, 3, 4, 5, 4, 7, 8, 5, 1]",187,129,129,True,True,False
6445,8,2,"[2, 3, 4, 5, 8, 5, 7, 4, 1]",185,129,129,True,True,False
6476,8,2,"[2, 3, 4, 4, 7, 5, 8, 8, 1]",209,129,129,True,True,False
6481,8,2,"[2, 3, 4, 6, 7, 5, 7, 4, 1]",186,129,129,True,True,False
6482,8,2,"[2, 3, 3, 5, 7, 6, 7, 4, 1]",181,129,129,True,True,False
6484,8,2,"[2, 3, 3, 5, 7, 5, 8, 5, 1]",185,129,129,True,True,False
6486,8,2,"[2, 3, 4, 5, 7, 5, 8, 4, 1]",184,129,129,True,True,False
6493,8,2,"[2, 3, 3, 6, 6, 5, 8, 8, 1]",211,129,129,True,True,False

20 examples of depth 8

Empty DataFrame
Columns: [h, exponent, architecture, num_parameters, dimension_computed, ambient_dimension, is_full_dimension, is_minimal, is_unimodal]
Index: []

0 examples of depth 9

In [4]:
df = pd.read_csv('2_2_architectures.csv')
df['is_unimodal'] = df['architecture'].apply(is_unimodal)

print("--"*15 + f"DISCOVERED COUNTEREXAMPLES TO THE MINIMAL UNIMODAL CONJECTURE" + "--"*15)
for depth in range(2,10):
    df_display = df[(df['h']==depth) & (df['is_minimal'] == True) & (df['is_unimodal']==False)]
    display(df_display)
    print(f"{len(df_display)} examples of depth {depth}")

------------------------------DISCOVERED COUNTEREXAMPLES TO THE MINIMAL UNIMODAL CONJECTURE------------------------------

Empty DataFrame
Columns: [h, exponent, architecture, num_parameters, dimension_computed, ambient_dimension, is_full_dimension, is_minimal, is_unimodal]
Index: []

0 examples of depth 2

Empty DataFrame
Columns: [h, exponent, architecture, num_parameters, dimension_computed, ambient_dimension, is_full_dimension, is_minimal, is_unimodal]
Index: []

0 examples of depth 3

Empty DataFrame
Columns: [h, exponent, architecture, num_parameters, dimension_computed, ambient_dimension, is_full_dimension, is_minimal, is_unimodal]
Index: []

0 examples of depth 4

Empty DataFrame
Columns: [h, exponent, architecture, num_parameters, dimension_computed, ambient_dimension, is_full_dimension, is_minimal, is_unimodal]
Index: []

0 examples of depth 5

Empty DataFrame
Columns: [h, exponent, architecture, num_parameters, dimension_computed, ambient_dimension, is_full_dimension, is_minimal, is_unimodal]
Index: []

0 examples of depth 6

Empty DataFrame
Columns: [h, exponent, architecture, num_parameters, dimension_computed, ambient_dimension, is_full_dimension, is_minimal, is_unimodal]
Index: []

0 examples of depth 7

Empty DataFrame
Columns: [h, exponent, architecture, num_parameters, dimension_computed, ambient_dimension, is_full_dimension, is_minimal, is_unimodal]
Index: []

0 examples of depth 8

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,is_unimodal
14834,9,2,"[2, 3, 4, 4, 10, 17, 11, 12, 4, 2]",619,514,514,True,True,False

1 examples of depth 9