# Examine .csv files

This notebook is a sandbox where one can analyze the results of the searches.

In [1]:
import ast
import pandas as pd
from is_unimodal import is_unimodal

In [4]:
df = pd.read_csv('../data/raw/2_1_r2_architectures.csv')
df['is_unimodal'] = df['architecture'].apply(is_unimodal)

print("--"*15 + f"DISCOVERED COUNTEREXAMPLES TO THE MINIMAL UNIMODAL CONJECTURE" + "--"*15)
for depth in range(2,12):
    df_display = df[(df['h']==depth) & (df['is_minimal'] == True) & (df['is_unimodal']==False)]
    if len(df_display)>0:
        display(df_display)
        print(f"{len(df_display)} examples of depth {depth}")

------------------------------DISCOVERED COUNTEREXAMPLES TO THE MINIMAL UNIMODAL CONJECTURE------------------------------

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,expected_dimension,defect_expected,defect_ambient,backend,primes,elapsed_seconds,status,covered_by_mfa,is_unimodal
4729,7.0,2.0,"[2, 3, 4, 5, 4, 6, 4, 1]",110.0,65.0,65.0,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

1 examples of depth 7

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,expected_dimension,defect_expected,defect_ambient,backend,primes,elapsed_seconds,status,covered_by_mfa,is_unimodal
4910,8.0,2.0,"[2, 3, 3, 5, 7, 6, 7, 4, 1]",181.0,129.0,129.0,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
4911,8.0,2.0,"[2, 3, 3, 6, 7, 6, 7, 3, 1]",183.0,129.0,129.0,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
4915,8.0,2.0,"[2, 3, 4, 5, 7, 6, 7, 3, 1]",181.0,129.0,129.0,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
4926,8.0,2.0,"[2, 3, 3, 4, 7, 6, 8, 4, 1]",181.0,129.0,129.0,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
4930,8.0,2.0,"[2, 3, 3, 5, 7, 6, 8, 3, 1]",182.0,129.0,129.0,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
4937,8.0,2.0,"[2, 3, 4, 4, 7, 6, 8, 3, 1]",179.0,129.0,129.0,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
4942,8.0,2.0,"[2, 3, 4, 6, 5, 8, 6, 3, 1]",181.0,129.0,129.0,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
4975,8.0,2.0,"[2, 3, 4, 5, 4, 7, 9, 3, 1]",179.0,129.0,129.0,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
5000,8.0,2.0,"[2, 3, 3, 4, 7, 6, 7, 6, 1]",187.0,129.0,129.0,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
5001,8.0,2.0,"[2, 3, 4, 4, 7, 6, 7, 5, 1]",186.0,129.0,129.0,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
5002,8.0,2.0,"[2, 3, 4, 5, 7, 5, 7, 5, 1]",183.0,129.0,129.0,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
5003,8.0,2.0,"[2, 3, 4, 6, 7, 5, 7, 4, 1]",186.0,129.0,129.0,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
5012,8.0,2.0,"[2, 3, 3, 5, 7, 5, 8, 5, 1]",185.0,129.0,129.0,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
5021,8.0,2.0,"[2, 3, 4, 5, 4, 7, 8, 5, 1]",187.0,129.0,129.0,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
5022,8.0,2.0,"[2, 3, 4, 5, 4, 8, 8, 4, 1]",190.0,129.0,129.0,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
5023,8.0,2.0,"[2, 3, 4, 5, 6, 5, 8, 5, 1]",183.0,129.0,129.0,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
5024,8.0,2.0,"[2, 3, 4, 5, 7, 5, 8, 4, 1]",184.0,129.0,129.0,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
5025,8.0,2.0,"[2, 3, 4, 5, 8, 5, 7, 4, 1]",185.0,129.0,129.0,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
5071,8.0,2.0,"[2, 3, 4, 5, 4, 6, 9, 5, 1]",186.0,129.0,129.0,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
5179,8.0,2.0,"[2, 3, 3, 4, 7, 5, 9, 6, 1]",195.0,129.0,129.0,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
5182,8.0,2.0,"[2, 3, 3, 5, 6, 5, 9, 6, 1]",195.0,129.0,129.0,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
5355,8.0,2.0,"[2, 3, 4, 6, 6, 5, 7, 7, 1]",199.0,129.0,129.0,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
5641,8.0,2.0,"[2, 3, 3, 6, 6, 5, 8, 8, 1]",211.0,129.0,129.0,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
5646,8.0,2.0,"[2, 3, 4, 4, 7, 5, 8, 8, 1]",209.0,129.0,129.0,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

24 examples of depth 8