# Flexible Search via GPU

This notebook has code to perform searches over $\prod_{i} [m_i,n_i]$. It uses the improved dimension computation algorithm.

We also allow safe interruption of the search if it turnsout to take far too long.

In [174]:
# %load ../dim_backprop_gpu_only.py
"""Exact GPU computation of polynomial-network neurovariety dimensions.

This module has no SageMath or NumPy backend.  It requires CuPy and a
CUDA-capable NVIDIA GPU.

The public function keeps the original calling convention::

    compute_dimension(network_widths, network_exponent)

The returned tuple is

    (sizes, exponent, ambient_dim, expected_dim, dimension, defect).

The computation is exact over the finite fields listed in ``DEFAULT_PRIMES``.
All samples and all output-coordinate pullbacks are differentiated in one
batched GPU computation.  The final Jacobian rank is computed modulo each
prime by GPU-parallel row elimination.
"""

from __future__ import annotations

from math import comb
from typing import Iterator, Sequence

try:
    import cupy as cp
except ImportError as exc:
    raise RuntimeError(
        "This GPU-only module requires CuPy. Install the CuPy package that "
        "matches your CUDA version, for example `pip install cupy-cuda12x`."
    ) from exc


DEFAULT_PRIMES = (100003, 100153)
_INT64_MAX = (1 << 63) - 1


def _require_cuda() -> None:
    """Raise a clear error unless a usable CUDA device is visible."""
    try:
        device_count = int(cp.cuda.runtime.getDeviceCount())
    except cp.cuda.runtime.CUDARuntimeError as exc:
        raise RuntimeError(
            "CuPy is installed, but CUDA could not be initialized. Check the "
            "NVIDIA driver, CUDA/CuPy compatibility, and notebook kernel."
        ) from exc

    if device_count < 1:
        raise RuntimeError("No CUDA-capable GPU is visible to CuPy.")


def gpu_information() -> dict[str, object]:
    """Return basic information about the CUDA device used by this module."""
    _require_cuda()
    device_id = int(cp.cuda.runtime.getDevice())
    properties = cp.cuda.runtime.getDeviceProperties(device_id)
    name = properties["name"]
    if isinstance(name, bytes):
        name = name.decode("utf-8", errors="replace")
    return {
        "device_id": device_id,
        "name": name,
        "device_count": int(cp.cuda.runtime.getDeviceCount()),
        "cupy_version": cp.__version__,
        "cuda_runtime_version": int(cp.cuda.runtime.runtimeGetVersion()),
        "driver_version": int(cp.cuda.runtime.driverGetVersion()),
    }


def _is_prime(value: int) -> bool:
    """Deterministic Miller--Rabin test for unsigned 64-bit integers."""
    if value < 2:
        return False

    small_primes = (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37)
    if value in small_primes:
        return True
    if any(value % prime == 0 for prime in small_primes):
        return False

    odd_part = value - 1
    power_of_two = 0
    while odd_part % 2 == 0:
        power_of_two += 1
        odd_part //= 2

    # Deterministic for every n < 2^64.
    for base in (2, 325, 9375, 28178, 450775, 9780504, 1795265022):
        if base % value == 0:
            continue
        witness = pow(base, odd_part, value)
        if witness in (1, value - 1):
            continue
        for _ in range(power_of_two - 1):
            witness = (witness * witness) % value
            if witness == value - 1:
                break
        else:
            return False

    return True


def _weak_compositions(total: int, length: int) -> Iterator[tuple[int, ...]]:
    """Yield nonnegative ``length``-tuples whose entries sum to ``total``."""
    if length == 0:
        if total == 0:
            yield ()
        return
    if length == 1:
        yield (total,)
        return

    for first in range(total + 1):
        for rest in _weak_compositions(total - first, length - 1):
            yield (first,) + rest


def _unisolvent_samples(input_dim: int, degree: int, prime: int):
    r"""Construct the homogeneous interpolation points directly on the GPU.

    On the chart ``x_0 = 1``, homogeneous degree-``degree`` forms become
    polynomials of total degree at most ``degree`` in ``input_dim - 1``
    variables.  The integer simplex is an unisolvent evaluation set when
    ``prime > degree``.
    """
    if input_dim < 1:
        raise ValueError("the input layer must have positive width")
    if degree < 0:
        raise ValueError("degree must be nonnegative")
    if prime <= degree:
        raise ValueError(
            f"prime {prime} must exceed polynomial degree {degree}"
        )

    expected = comb(degree + input_dim - 1, input_dim - 1)
    if input_dim == 1:
        return cp.ones((1, 1), dtype=cp.int64)

    points: list[tuple[int, ...]] = []
    for total in range(degree + 1):
        for alpha in _weak_compositions(total, input_dim - 1):
            points.append((1,) + alpha)

    if len(points) != expected:
        raise RuntimeError(
            f"internal sample-count error: got {len(points)}, expected {expected}"
        )

    return cp.asarray(points, dtype=cp.int64) % prime


def _mod_pow(base, exponent: int, prime: int):
    """Elementwise modular exponentiation on the GPU."""
    if exponent < 0:
        raise ValueError("exponent must be nonnegative")

    result = cp.ones_like(base, dtype=cp.int64)
    if exponent == 0:
        return result

    power = base.astype(cp.int64, copy=False) % prime
    remaining = int(exponent)
    while remaining:
        if remaining & 1:
            result = (result * power) % prime
        remaining >>= 1
        if remaining:
            power = (power * power) % prime

    return result


def _check_dot_product_safety(widths: Sequence[int], prime: int) -> None:
    """Prevent signed int64 overflow before a matrix product is reduced."""
    largest_inner_dimension = max(int(width) for width in widths)
    worst_case = largest_inner_dimension * (prime - 1) ** 2
    if worst_case > _INT64_MAX:
        raise OverflowError(
            "An int64 GPU matrix product may overflow before reduction modulo "
            "the prime. Use a smaller prime or narrower layers."
        )


def _random_weights(
    widths: Sequence[int], prime: int, seed: int
) -> list[cp.ndarray]:
    """Generate all network weight matrices directly in GPU memory."""
    rng = cp.random.RandomState(seed)
    return [
        rng.randint(
            0,
            prime,
            size=(out_width, in_width),
            dtype=cp.int64,
        )
        for in_width, out_width in zip(widths[:-1], widths[1:])
    ]


def _parameter_offsets(
    weights: Sequence[cp.ndarray],
) -> tuple[list[int], int]:
    offsets: list[int] = []
    total = 0
    for weight in weights:
        offsets.append(total)
        total += int(weight.shape[0] * weight.shape[1])
    return offsets, total


def _batched_weight_jacobian(
    weights: Sequence[cp.ndarray],
    samples: cp.ndarray,
    exponent: int,
    prime: int,
) -> cp.ndarray:
    """Evaluate every output/weight derivative at every sample on the GPU.

    The result has shape ``(number_of_samples, output_width, num_parameters)``.
    Weight matrices are flattened layer by layer in row-major order, matching
    the ordering used by Sage's matrix ``list()`` method in the old code.
    """
    if exponent < 1:
        raise ValueError("network exponent must be at least 1")
    if not weights:
        raise ValueError("the network must contain at least one weight layer")

    activations = [samples]
    preactivations: list[cp.ndarray] = []
    activation = samples

    # Hidden layers use z -> z^exponent; the final layer is linear.
    for weight in weights[:-1]:
        preactivation = cp.matmul(activation, weight.T) % prime
        preactivations.append(preactivation)
        activation = _mod_pow(preactivation, exponent, prime)
        activations.append(activation)

    batch_size = int(samples.shape[0])
    output_width = int(weights[-1].shape[0])
    offsets, num_parameters = _parameter_offsets(weights)

    jacobian = cp.zeros(
        (batch_size, output_width, num_parameters), dtype=cp.int64
    )

    # Final linear layer.
    final_input = activations[-1]
    final_offset = offsets[-1]
    final_input_width = int(weights[-1].shape[1])
    for output_index in range(output_width):
        start = final_offset + output_index * final_input_width
        stop = start + final_input_width
        jacobian[:, output_index, start:stop] = final_input

    if len(weights) == 1:
        return jacobian

    # Derivatives of all output coordinates with respect to the last hidden
    # preactivation: shape (sample, output, hidden neuron).
    delta = cp.broadcast_to(
        weights[-1][None, :, :],
        (batch_size, output_width, int(weights[-1].shape[1])),
    ).copy()
    derivative = (
        (exponent % prime)
        * _mod_pow(preactivations[-1], exponent - 1, prime)
    ) % prime
    delta = (delta * derivative[:, None, :]) % prime

    # Hidden layers from last to first.
    for layer_index in range(len(weights) - 2, -1, -1):
        weight = weights[layer_index]
        layer_input = activations[layer_index]

        gradient = (
            delta[:, :, :, None] * layer_input[:, None, None, :]
        ) % prime

        start = offsets[layer_index]
        stop = start + int(weight.shape[0] * weight.shape[1])
        jacobian[:, :, start:stop] = gradient.reshape(
            batch_size, output_width, stop - start
        )

        if layer_index > 0:
            delta = cp.matmul(delta, weight) % prime
            derivative = (
                (exponent % prime)
                * _mod_pow(
                    preactivations[layer_index - 1], exponent - 1, prime
                )
            ) % prime
            delta = (delta * derivative[:, None, :]) % prime

    return jacobian


def _rank_mod_prime_gpu(
    matrix: cp.ndarray,
    prime: int,
    workspace_bytes: int = 512 * 1024**2,
) -> int:
    """Compute exact matrix rank over GF(prime) using GPU row operations."""
    if matrix.ndim != 2:
        raise ValueError("rank input must be a matrix")
    if workspace_bytes <= 0:
        raise ValueError("workspace_bytes must be positive")

    reduced = matrix.astype(cp.int64, copy=True) % prime

    # Eliminate along the smaller dimension.
    if reduced.shape[1] > reduced.shape[0]:
        reduced = reduced.T.copy()

    nrows, ncols = map(int, reduced.shape)
    pivot_row = 0

    for column in range(ncols):
        if pivot_row == nrows:
            break

        nonzero = reduced[pivot_row:, column] != 0
        if not bool(cp.any(nonzero).item()):
            continue

        pivot = pivot_row + int(cp.argmax(nonzero).item())
        if pivot != pivot_row:
            temporary = reduced[pivot_row, :].copy()
            reduced[pivot_row, :] = reduced[pivot, :]
            reduced[pivot, :] = temporary

        pivot_value = int(reduced[pivot_row, column].item())
        inverse = pow(pivot_value, prime - 2, prime)
        reduced[pivot_row, column:] = (
            reduced[pivot_row, column:] * inverse
        ) % prime

        # The row updates are parallel CUDA kernels. Chunking bounds temporary
        # memory usage for large Jacobians.
        remaining_columns = ncols - column
        bytes_per_row = max(1, 3 * remaining_columns * 8)
        rows_per_chunk = max(1, workspace_bytes // bytes_per_row)

        start = pivot_row + 1
        while start < nrows:
            stop = min(nrows, start + rows_per_chunk)
            factors = reduced[start:stop, column].copy()
            reduced[start:stop, column:] = (
                reduced[start:stop, column:]
                - factors[:, None] * reduced[pivot_row, column:][None, :]
            ) % prime
            start = stop

        pivot_row += 1

    return pivot_row


def compute_dimension(
    network_widths: Sequence[int],
    network_exponent: int,
    *,
    primes: Sequence[int] = DEFAULT_PRIMES,
    seed: int = 20260630,
    rank_workspace_bytes: int = 512 * 1024**2,
    verbose: bool = False,
):
    """Compute the neurovariety dimension entirely with the CUDA backend.

    Parameters
    ----------
    network_widths:
        Layer widths ``[d0, d1, ..., dL]``.
    network_exponent:
        Common hidden-layer activation exponent.
    primes:
        Prime moduli used to cross-check the generic rank.
    seed:
        Base random seed for the network weights.
    rank_workspace_bytes:
        Approximate upper bound for temporary elimination workspace.
    verbose:
        Print GPU and rank information.

    Returns
    -------
    tuple
        ``(sizes, exponent, ambient_dim, expected_dim, dimension, defect)``.
    """
    _require_cuda()

    widths = tuple(int(width) for width in network_widths)
    exponent = int(network_exponent)

    if len(widths) < 2:
        raise ValueError("network_widths must contain input and output widths")
    if any(width <= 0 for width in widths):
        raise ValueError("all network widths must be positive")
    if exponent < 1:
        raise ValueError("network_exponent must be at least 1")
    if not primes:
        raise ValueError("at least one prime is required")

    degree = exponent ** (len(widths) - 2)
    ambient_per_output = comb(degree + widths[0] - 1, widths[0] - 1)
    ambient_dim = ambient_per_output * widths[-1]
    num_parameters = sum(
        in_width * out_width
        for in_width, out_width in zip(widths[:-1], widths[1:])
    )

    dimensions: list[int] = []

    if verbose:
        info = gpu_information()
        print(
            f"GPU {info['device_id']}: {info['name']} | "
            f"CuPy {info['cupy_version']} | "
            f"CUDA runtime {info['cuda_runtime_version']}"
        )

    for prime_index, prime_value in enumerate(primes):
        prime = int(prime_value)
        if not _is_prime(prime):
            raise ValueError(f"modulus {prime} is not prime")
        _check_dot_product_safety(widths, prime)

        samples = _unisolvent_samples(widths[0], degree, prime)
        weights = _random_weights(
            widths,
            prime,
            seed + 1_000_003 * prime_index + prime,
        )

        jacobian = _batched_weight_jacobian(
            weights,
            samples,
            exponent,
            prime,
        )
        rank_matrix = jacobian.reshape(
            ambient_per_output * widths[-1], num_parameters
        )
        dimension = _rank_mod_prime_gpu(
            rank_matrix,
            prime,
            workspace_bytes=rank_workspace_bytes,
        )
        dimensions.append(dimension)

        # Ensure kernels for this prime have completed before reporting and
        # releasing memory.
        cp.cuda.Stream.null.synchronize()

        if verbose:
            print(
                f"prime={prime}, samples={ambient_per_output}, "
                f"rank_matrix={tuple(rank_matrix.shape)}, rank={dimension}"
            )

        del rank_matrix, jacobian, weights, samples
        cp.get_default_memory_pool().free_all_blocks()

    if not all(dimension == dimensions[0] for dimension in dimensions):
        raise ValueError(
            "different dimensions over finite fields: " + str(dimensions)
        )

    naive_bound = sum(
        (in_width - 1) * out_width
        for in_width, out_width in zip(widths[:-1], widths[1:])
    ) + widths[-1]
    expected_dim = min(ambient_dim, naive_bound)
    dimension = dimensions[0]

    return (
        list(widths),
        exponent,
        ambient_dim,
        expected_dim,
        dimension,
        expected_dim - dimension,
    )


if __name__ == "__main__":
    print(compute_dimension([2, 3, 1], 2, verbose=True))

GPU 0: NVIDIA GeForce RTX 4070 SUPER | CuPy 14.1.1 | CUDA runtime 12090
prime=100003, samples=3, rank_matrix=(3, 9), rank=3
prime=100153, samples=3, rank_matrix=(3, 9), rank=3
([2, 3, 1], 2, 3, 3, 3, 0)

# Search Algorithm

In [175]:
import os
import ast
import math
import itertools
import random as py_random
import pandas as pd
from tqdm import tqdm

In [176]:
# Helper Functions

def calculate_parameter_count(hidden: tuple, d_0: int, d_h: int) -> int:
    """Calculates the total number of weights and biases in the network."""
    sizes = [d_0] + list(hidden) + [d_h]
    return sum(m * n for m, n in zip(sizes[:-1], sizes[1:]))

def is_less_or_equal(t1: tuple, t2: tuple) -> bool:
    """Returns True if every element in t1 is <= the corresponding element in t2."""
    if len(t1) != len(t2):
        return False
    return all(a <= b for a, b in zip(t1, t2))

def evaluate_single_architecture(hidden_tuple: tuple, h: int, d_0: int, d_h: int, exponent: int):
    """Worker function to evaluate a single architecture and format the result."""
    sizes = [d_0] + list(hidden_tuple) + [d_h]
    arch_str = str(sizes)
    
    try:
        _, _, amb, _, dim, _ = compute_dimension(sizes, exponent)
        params = calculate_parameter_count(hidden_tuple, d_0, d_h)
        is_full = (dim == amb)
        
        status = "FULL " if is_full else "SHORT"
        print(f"  [{status}] {arch_str} -> Rank: {dim}/{amb} (Params: {params})")
        
        return {
            "h": h,
            "exponent": exponent,
            "architecture": arch_str,
            "num_parameters": params,
            "dimension_computed": int(dim),
            "ambient_dimension": int(amb),
            "is_full_dimension": is_full,
            "is_minimal": False 
        }
    except Exception as e:
        print(f"  [ERROR] {arch_str} failed: {e}")
        return None

In [177]:
# Core Search & Pruning Algorithm

def parameter_boundary_search(
    h_values: list, max_width=6, min_width=1, exponent=2, 
    d_0=2, d_h=1, csv_filename="architecture_search_log.csv", 
    user_guesses=None, layer_bounds=None
):

    # Load or initialize Database
    if os.path.exists(csv_filename):
        print(f"Loading existing database from '{csv_filename}'...")
        df = pd.read_csv(csv_filename)
    else:
        print("No existing database found. Starting fresh...")
        df = pd.DataFrame(columns=[
            "h", "exponent", "architecture", "num_parameters", 
            "dimension_computed", "ambient_dimension", "is_full_dimension", "is_minimal"
        ])

    evaluated_architectures = set(df["architecture"].tolist())
    new_records = []

    for h in h_values:
        print(f"\n--- RANDOM SEARCH: h={h}, exponent={exponent} ---")
        
        num_hidden = h - 1
        degree = exponent ** num_hidden
        ambient_dim = math.comb(degree + d_0 - 1, d_0 - 1) * d_h
        print(f"  Target Ambient Dimension: {ambient_dim}")

        # Extract known boundaries
        known_minimal = set()
        known_short = set()
        
        if not df.empty:
            subset_df = df[(df["h"] == h) & (df["exponent"] == exponent)]
            
            min_df = subset_df[subset_df["is_minimal"] == True]
            known_minimal.update(tuple(ast.literal_eval(a)[1:-1]) for a in min_df["architecture"])
            
            short_df = subset_df[subset_df["is_full_dimension"] == False]
            known_short.update(tuple(ast.literal_eval(a)[1:-1]) for a in short_df["architecture"])

        # 1. Evaluate User Guesses
        if user_guesses and h in user_guesses:
            for guess in user_guesses[h]:
                arch_str = str([d_0] + list(guess) + [d_h])
                if arch_str in evaluated_architectures:
                    continue
                
                print(f"  Evaluating Guess: {guess}...")
                res = evaluate_single_architecture(guess, h, d_0, d_h, exponent)
                if not res: continue
                
                evaluated_architectures.add(res["architecture"])
                new_records.append(res)
                
                if res["is_full_dimension"]:
                    known_minimal.add(guess)
                else:
                    known_short.add(guess)

# 2. Build and Filter Search Pool
        print("  Generating candidate pool...")
        
        # Builds the Search Pool but imposing bounds on the individual layers

        if layer_bounds and h in layer_bounds:
            bounds = layer_bounds[h]
            if len(bounds) != num_hidden:
                print(f"  [WARNING] layer_bounds for h={h} has length {len(bounds)}, but expected {num_hidden} hidden layers. Skipping this depth...")
                continue
            
            print(f"  Using custom per-layer bounds: {bounds}")
            ranges = [range(max(1, b_min), b_max + 1) for b_min, b_max in bounds]
            all_possible = itertools.product(*ranges)
            
            # calculate total items for the progress bar
            total_combinations = math.prod(len(r) for r in ranges)
            
        else:
            print(f"  Using global bounds: min_width={min_width}, max_width={max_width}")
            width_range = range(max(1, min_width), max_width + 1)
            all_possible = itertools.product(width_range, repeat=num_hidden)
            
            # calculate total items for the progress bar
            total_combinations = len(width_range) ** num_hidden
        
        candidate_pool = []
        rejected_count = 0
        
        # wrap in tqdm. useful for long run times.
        for hidden in tqdm(all_possible, total=total_combinations, desc="  Filtering", leave=False, dynamic_ncols=True):
            arch_str = str([d_0] + list(hidden) + [d_h])
            if arch_str in evaluated_architectures:
                continue
                
            params = calculate_parameter_count(hidden, d_0, d_h)
            
            # pruning 
            if (params < ambient_dim or 
                any(is_less_or_equal(m, hidden) for m in known_minimal) or 
                any(is_less_or_equal(hidden, s) for s in known_short)):
                rejected_count += 1
                continue
                
            candidate_pool.append(hidden)
            
        print(f"  Pruned {rejected_count} impossible/redundant architectures.")
        print(f"  Starting sequential evaluation on {len(candidate_pool)} viable candidates.")

        # shuffle queue 
        py_random.shuffle(candidate_pool)

        try:
            while candidate_pool:
                target = candidate_pool.pop(0)
                
                res = evaluate_single_architecture(target, h, d_0, d_h, exponent)
                if not res: continue
                
                evaluated_architectures.add(res["architecture"])
                new_records.append(res)
                
                before_len = len(candidate_pool)
                if res["is_full_dimension"]:
                    known_minimal.add(target)
                    # remove all supersets from the queue
                    candidate_pool = [c for c in candidate_pool if not is_less_or_equal(target, c)]
                    pruned = before_len - len(candidate_pool)
                    if pruned > 0: print(f"    [Upward Pruned] {pruned} supersets removed from queue.")
                else:
                    known_short.add(target)
                    # remove all subsets from the queue
                    candidate_pool = [c for c in candidate_pool if not is_less_or_equal(c, target)]
                    pruned = before_len - len(candidate_pool)
                    if pruned > 0: print(f"    [Downward Pruned] {pruned} subsets removed from queue.")

        except KeyboardInterrupt: # incase one wants to halt a long run early and still save the results
            print("\n[Interrupt] User halted the loop early. Saving progress and continuing execution...")

    # 4. Save and determine minimality based on results in the .csv
    # This does not guarantee the examples are truly minimality -- need to do actual checks elsewhere.
    if new_records:
        new_df = pd.DataFrame(new_records).dropna(axis=1, how='all')
        if not df.empty:
            df = pd.concat([df, new_df], ignore_index=True)
        else:
            df = new_df
        print(f"\nAdded {len(new_records)} new architectures to the database.")

    print("Re-evaluating minimal filling properties (grouped by depth h and exponent)...")
    if not df.empty:
        df["is_minimal"] = False 
        
        # calculate if minimal 
        # this does not actual check minimality fully -- just minimality base on search so far
        # see verify_minimal.ipynb

        for (h_val, exp_val), group in df[df["is_full_dimension"] == True].groupby(["h", "exponent"]):
            full_archs = [ast.literal_eval(arch) for arch in group["architecture"]]
            
            for idx, row in group.iterrows():
                parsed_config = ast.literal_eval(row["architecture"])
                # it is minimal if no other full architecture is strictly smaller than it
                is_min = not any(
                    other != parsed_config and is_less_or_equal(other, parsed_config) 
                    for other in full_archs
                )
                df.at[idx, "is_minimal"] = is_min

        df.to_csv(csv_filename, index=False)
        print(f"Database successfully saved to '{csv_filename}'.\n")
    return df

# Search Algorithm 2

In [178]:
# from __future__ import annotations

# import ast
# import heapq
# import math
# import os
# import random as py_random
# from pathlib import Path
# from typing import Iterable, Sequence

# import pandas as pd


# # =============================================================================
# # Helpers
# # =============================================================================

# def _is_less_or_equal(a: Sequence[int], b: Sequence[int]) -> bool:
#     """
#     Coordinatewise comparison.

#     If the notebook already defines `is_less_or_equal`, that implementation is
#     used. Otherwise, this function supplies the usual coordinatewise order.
#     """
#     try:
#         return bool(is_less_or_equal(a, b))
#     except NameError:
#         return len(a) == len(b) and all(x <= y for x, y in zip(a, b))


# def _as_bool(value: object) -> bool:
#     """Parse booleans stored by pandas or in a CSV."""
#     if pd.isna(value):
#         return False
#     if isinstance(value, str):
#         return value.strip().lower() in {"true", "1", "yes"}
#     return bool(value)


# def _parse_architecture(value: object) -> tuple[int, ...]:
#     """Parse an architecture stored either as a list or as a CSV string."""
#     if isinstance(value, str):
#         value = ast.literal_eval(value)
#     return tuple(int(x) for x in value)


# def _parameter_count(
#     hidden: Sequence[int],
#     d_0: int,
#     d_h: int,
# ) -> int:
#     """
#     Use the project's existing parameter-count function when available.

#     The fallback is the standard parameter-dimension bound
#         sum_i d_{i-1}d_i - sum_hidden d_i.
#     """
#     try:
#         return int(calculate_parameter_count(hidden, d_0, d_h))
#     except NameError:
#         architecture = (d_0, *hidden, d_h)
#         edge_parameters = sum(
#             architecture[i] * architecture[i + 1]
#             for i in range(len(architecture) - 1)
#         )
#         hidden_scalings = sum(hidden)
#         return edge_parameters - hidden_scalings


# def _insert_minimal(
#     antichain: set[tuple[int, ...]],
#     point: tuple[int, ...],
# ) -> set[tuple[int, ...]]:
#     """Insert `point` into an antichain of coordinatewise minimal elements."""
#     if any(_is_less_or_equal(other, point) for other in antichain):
#         return antichain

#     return {
#         other
#         for other in antichain
#         if not _is_less_or_equal(point, other)
#     } | {point}


# def _insert_maximal(
#     antichain: set[tuple[int, ...]],
#     point: tuple[int, ...],
# ) -> set[tuple[int, ...]]:
#     """Insert `point` into an antichain of coordinatewise maximal elements."""
#     if any(_is_less_or_equal(point, other) for other in antichain):
#         return antichain

#     return {
#         other
#         for other in antichain
#         if not _is_less_or_equal(other, point)
#     } | {point}


# def _minimal_antichain(
#     points: Iterable[tuple[int, ...]],
# ) -> set[tuple[int, ...]]:
#     result: set[tuple[int, ...]] = set()
#     for point in sorted(set(points), key=lambda x: (sum(x), x)):
#         result = _insert_minimal(result, point)
#     return result


# def _maximal_antichain(
#     points: Iterable[tuple[int, ...]],
# ) -> set[tuple[int, ...]]:
#     result: set[tuple[int, ...]] = set()
#     for point in sorted(set(points), key=lambda x: (-sum(x), x)):
#         result = _insert_maximal(result, point)
#     return result


# def _save_csv(df: pd.DataFrame, csv_path: Path) -> None:
#     """
#     Save directly to the requested CSV, as in the original implementation.

#     No .pkl checkpoint and no companion state file are created.
#     """
#     csv_path.parent.mkdir(parents=True, exist_ok=True)
#     df.to_csv(csv_path, index=False)


# def _append_result(
#     df: pd.DataFrame,
#     result: dict,
#     *,
#     hidden: tuple[int, ...],
#     h: int,
#     exponent: int,
#     d_0: int,
#     d_h: int,
#     ambient_dim: int,
# ) -> pd.DataFrame:
#     """Append one evaluator result while preserving the original CSV schema."""
#     row = dict(result)

#     row.setdefault("h", h)
#     row.setdefault("exponent", exponent)
#     row.setdefault("architecture", str([d_0, *hidden, d_h]))
#     row.setdefault("num_parameters", _parameter_count(hidden, d_0, d_h))
#     row.setdefault("ambient_dimension", ambient_dim)
#     row.setdefault("is_minimal", False)

#     architecture = _parse_architecture(row["architecture"])
#     row["architecture"] = str(list(architecture))

#     df = pd.concat([df, pd.DataFrame([row])], ignore_index=True)

#     return df.drop_duplicates(
#         subset=["h", "exponent", "architecture"],
#         keep="last",
#     )


# def _recompute_minimality(df: pd.DataFrame) -> pd.DataFrame:
#     """
#     Recompute minimality among all filling architectures currently in the CSV.

#     This has the same meaning as in the original code: it is minimality relative
#     to the filling architectures found so far.
#     """
#     if df.empty:
#         return df

#     df = df.copy()
#     df["is_minimal"] = False

#     full_rows = df[df["is_full_dimension"].map(_as_bool)]

#     for (_, _), group in full_rows.groupby(["h", "exponent"]):
#         architectures = {
#             index: _parse_architecture(row["architecture"])
#             for index, row in group.iterrows()
#         }

#         for index, architecture in architectures.items():
#             df.at[index, "is_minimal"] = not any(
#                 other_index != index
#                 and other_architecture != architecture
#                 and _is_less_or_equal(other_architecture, architecture)
#                 for other_index, other_architecture in architectures.items()
#             )

#     return df


# # =============================================================================
# # Core Search & Pruning Algorithm
# # =============================================================================

# def parameter_boundary_search(
#     h_values: list,
#     max_width=6,
#     min_width=1,
#     exponent=2,
#     d_0=2,
#     d_h=1,
#     csv_filename="architecture_search_log.csv",
#     user_guesses=None,
#     layer_bounds=None,
# ):
#     """
#     Drop-in replacement for the original randomized boundary search.

#     The function signature and the user's execution block are unchanged.

#     Main differences from the original implementation
#     -------------------------------------------------
#     1. The full Cartesian product is never constructed.
#     2. No `candidate_pool` list is materialized.
#     3. Candidates are generated lazily from the current nonfilling frontier.
#     4. The exposed frontier is processed in random order.
#     5. Existing CSV results are loaded before the search and used for:
#          - exact-result reuse;
#          - upward pruning above known filling architectures;
#          - downward pruning below known nonfilling architectures.
#     6. Every completed evaluator call is written immediately to the same CSV.
#     7. On KeyboardInterrupt, the CSV is updated and returned. No .pkl file is
#        created.

#     Important
#     ---------
#     The randomization is among the currently exposed frontier points. This
#     retains the practical benefit of random search without paying the cost of
#     constructing and shuffling the full candidate pool.
#     """
#     required_columns = [
#         "h",
#         "exponent",
#         "architecture",
#         "num_parameters",
#         "dimension_computed",
#         "ambient_dimension",
#         "is_full_dimension",
#         "is_minimal",
#     ]

#     csv_path = Path(csv_filename)

#     # -------------------------------------------------------------------------
#     # Load or initialize the original database.
#     # -------------------------------------------------------------------------
#     if csv_path.exists():
#         print(
#             f"Loading existing database from '{csv_path}'...",
#             flush=True,
#         )
#         df = pd.read_csv(csv_path)

#         for column in required_columns:
#             if column not in df.columns:
#                 df[column] = (
#                     False
#                     if column in {"is_full_dimension", "is_minimal"}
#                     else None
#                 )

#         df = df.drop_duplicates(
#             subset=["h", "exponent", "architecture"],
#             keep="last",
#         )
#     else:
#         print(
#             "No existing database found. Starting fresh...",
#             flush=True,
#         )
#         df = pd.DataFrame(columns=required_columns)

#     for h in h_values:
#         print(
#             f"\n--- RANDOM SEARCH: h={h}, exponent={exponent} ---",
#             flush=True,
#         )

#         num_hidden = h - 1
#         degree = exponent ** num_hidden
#         ambient_dim = (
#             math.comb(degree + d_0 - 1, d_0 - 1) * d_h
#         )

#         print(
#             f"  Target Ambient Dimension: {ambient_dim}",
#             flush=True,
#         )

#         # ---------------------------------------------------------------------
#         # Extract all known evaluations for this depth and exponent.
#         # ---------------------------------------------------------------------
#         evaluation_status: dict[tuple[int, ...], bool] = {}

#         if not df.empty:
#             subset_df = df[
#                 (df["h"] == h)
#                 & (df["exponent"] == exponent)
#             ]

#             for _, row in subset_df.iterrows():
#                 architecture = _parse_architecture(row["architecture"])

#                 if (
#                     len(architecture) != h + 1
#                     or architecture[0] != d_0
#                     or architecture[-1] != d_h
#                 ):
#                     continue

#                 hidden = architecture[1:-1]
#                 evaluation_status[hidden] = _as_bool(
#                     row["is_full_dimension"]
#                 )

#         known_minimal = _minimal_antichain(
#             hidden
#             for hidden, is_full in evaluation_status.items()
#             if is_full
#         )
#         known_short = _maximal_antichain(
#             hidden
#             for hidden, is_full in evaluation_status.items()
#             if not is_full
#         )

#         print(
#             f"  Loaded {len(evaluation_status):,} prior evaluation(s).",
#             flush=True,
#         )
#         print(
#             f"  Known filling boundary:    "
#             f"{sorted(known_minimal)}",
#             flush=True,
#         )
#         print(
#             f"  Known nonfilling boundary: "
#             f"{sorted(known_short)}",
#             flush=True,
#         )

#         # ---------------------------------------------------------------------
#         # Evaluate user guesses first, exactly as in the original workflow.
#         # ---------------------------------------------------------------------
#         if user_guesses and h in user_guesses:
#             for raw_guess in user_guesses[h]:
#                 guess = tuple(int(x) for x in raw_guess)

#                 if len(guess) != num_hidden:
#                     print(
#                         f"  [WARNING] Guess {guess} has length {len(guess)}, "
#                         f"but h={h} requires {num_hidden}. Skipping it.",
#                         flush=True,
#                     )
#                     continue

#                 if guess in evaluation_status:
#                     print(
#                         f"  Guess {guess} already appears in the CSV: "
#                         f"{'FILLING' if evaluation_status[guess] else 'SHORT'}.",
#                         flush=True,
#                     )
#                     continue

#                 print(
#                     f"  Evaluating Guess: {guess}...",
#                     flush=True,
#                 )

#                 result = evaluate_single_architecture(
#                     guess,
#                     h,
#                     d_0,
#                     d_h,
#                     exponent,
#                 )

#                 if not result:
#                     print(
#                         f"  [WARNING] No result returned for guess {guess}.",
#                         flush=True,
#                     )
#                     continue

#                 is_full = _as_bool(result["is_full_dimension"])
#                 evaluation_status[guess] = is_full

#                 df = _append_result(
#                     df,
#                     result,
#                     hidden=guess,
#                     h=h,
#                     exponent=exponent,
#                     d_0=d_0,
#                     d_h=d_h,
#                     ambient_dim=ambient_dim,
#                 )
#                 _save_csv(df, csv_path)

#                 print(
#                     f"    Dimension computed: "
#                     f"{result.get('dimension_computed', 'unknown')} / "
#                     f"{ambient_dim}",
#                     flush=True,
#                 )

#                 if is_full:
#                     known_minimal = _insert_minimal(
#                         known_minimal,
#                         guess,
#                     )
#                     print(
#                         f"    [FILLING] {guess}",
#                         flush=True,
#                     )
#                 else:
#                     known_short = _insert_maximal(
#                         known_short,
#                         guess,
#                     )
#                     print(
#                         f"    [SHORT] {guess}",
#                         flush=True,
#                     )

#         # ---------------------------------------------------------------------
#         # Determine exactly the same search box as the original code.
#         # ---------------------------------------------------------------------
#         print(
#             "  Generating randomized lazy frontier...",
#             flush=True,
#         )

#         if layer_bounds and h in layer_bounds:
#             bounds = layer_bounds[h]

#             if len(bounds) != num_hidden:
#                 print(
#                     f"  [WARNING] layer_bounds for h={h} has length "
#                     f"{len(bounds)}, but expected {num_hidden} hidden "
#                     "layers. Skipping this depth...",
#                     flush=True,
#                 )
#                 continue

#             lower = tuple(
#                 max(1, int(b_min))
#                 for b_min, _ in bounds
#             )
#             upper = tuple(
#                 int(b_max)
#                 for _, b_max in bounds
#             )

#             print(
#                 f"  Using custom per-layer bounds: {bounds}",
#                 flush=True,
#             )
#         else:
#             lower_value = max(1, int(min_width))
#             upper_value = int(max_width)

#             lower = (lower_value,) * num_hidden
#             upper = (upper_value,) * num_hidden

#             print(
#                 f"  Using global bounds: min_width={min_width}, "
#                 f"max_width={max_width}",
#                 flush=True,
#             )

#         if any(lo > hi for lo, hi in zip(lower, upper)):
#             print(
#                 f"  [WARNING] Inconsistent bounds: "
#                 f"lower={lower}, upper={upper}. "
#                 f"Skipping h={h}.",
#                 flush=True,
#             )
#             continue

#         formal_box_size = math.prod(
#             hi - lo + 1
#             for lo, hi in zip(lower, upper)
#         )

#         print(
#             f"  Formal box size: {formal_box_size:,}",
#             flush=True,
#         )
#         print(
#             "  The full candidate pool will not be constructed.",
#             flush=True,
#         )

#         # A fresh random generator preserves the original randomized behavior.
#         rng = py_random.Random()

#         def random_priority(
#             point: tuple[int, ...],
#         ) -> tuple[float, tuple[int, ...]]:
#             return rng.random(), point

#         heap: list[
#             tuple[
#                 tuple[float, tuple[int, ...]],
#                 tuple[int, ...],
#             ]
#         ] = [(random_priority(lower), lower)]

#         scheduled: set[tuple[int, ...]] = {lower}

#         def add_successors(
#             point: tuple[int, ...],
#         ) -> tuple[int, int, int]:
#             """
#             Generate immediate successors lazily.

#             Returns
#             -------
#             added:
#                 Number of successors inserted into the heap.
#             blocked_above_filling:
#                 Number rejected because they lie above a known filling point.
#             already_scheduled:
#                 Number already encountered earlier.
#             """
#             added = 0
#             blocked_above_filling = 0
#             already_scheduled = 0

#             for index in range(num_hidden):
#                 if point[index] >= upper[index]:
#                     continue

#                 successor_list = list(point)
#                 successor_list[index] += 1
#                 successor = tuple(successor_list)

#                 if successor in scheduled:
#                     already_scheduled += 1
#                     continue

#                 if any(
#                     _is_less_or_equal(filling_point, successor)
#                     for filling_point in known_minimal
#                 ):
#                     blocked_above_filling += 1
#                     scheduled.add(successor)
#                     continue

#                 scheduled.add(successor)
#                 heapq.heappush(
#                     heap,
#                     (random_priority(successor), successor),
#                 )
#                 added += 1

#             return (
#                 added,
#                 blocked_above_filling,
#                 already_scheduled,
#             )

#         def remove_queued_supersets(
#             filling_point: tuple[int, ...],
#         ) -> int:
#             """
#             Remove queued supersets of a newly found filling point.

#             This is safe because no such point can be a minimal filling
#             architecture, and none of its successors can be minimal either.
#             """
#             before = len(heap)

#             heap[:] = [
#                 item
#                 for item in heap
#                 if not _is_less_or_equal(
#                     filling_point,
#                     item[1],
#                 )
#             ]
#             heapq.heapify(heap)

#             return before - len(heap)

#         print(
#             f"  Starting randomized sequential evaluation with "
#             f"{len(heap)} exposed frontier point.",
#             flush=True,
#         )

#         # ---------------------------------------------------------------------
#         # Randomized lazy search.
#         # ---------------------------------------------------------------------
#         checked = 0
#         new_evaluations = 0
#         exact_csv_reuses = 0
#         parameter_prunes = 0
#         upward_prunes = 0
#         downward_prunes = 0

#         try:
#             while heap:
#                 _, target = heapq.heappop(heap)
#                 checked += 1

#                 print(
#                     f"\n  Checking {target} "
#                     f"(queue remaining: {len(heap):,})",
#                     flush=True,
#                 )

#                 # -------------------------------------------------------------
#                 # Upward pruning from known filling results.
#                 # -------------------------------------------------------------
#                 filling_witness = next(
#                     (
#                         filling_point
#                         for filling_point in known_minimal
#                         if _is_less_or_equal(
#                             filling_point,
#                             target,
#                         )
#                     ),
#                     None,
#                 )

#                 if filling_witness is not None:
#                     upward_prunes += 1
#                     print(
#                         f"    [Upward Pruned] {target} lies above known "
#                         f"filling architecture {filling_witness}.",
#                         flush=True,
#                     )
#                     continue

#                 # -------------------------------------------------------------
#                 # Downward pruning from known nonfilling results.
#                 #
#                 # In a lazy search, queued lower points are not physically
#                 # deleted, because their other successors may lead to
#                 # incomparable parts of the boundary. Instead, this point is
#                 # skipped and its immediate successors are exposed.
#                 # -------------------------------------------------------------
#                 short_witness = next(
#                     (
#                         short_point
#                         for short_point in known_short
#                         if _is_less_or_equal(
#                             target,
#                             short_point,
#                         )
#                     ),
#                     None,
#                 )

#                 if short_witness is not None:
#                     downward_prunes += 1
#                     added, blocked, duplicate = add_successors(target)

#                     print(
#                         f"    [Downward Pruned] {target} lies below known "
#                         f"nonfilling architecture {short_witness}.",
#                         flush=True,
#                     )
#                     print(
#                         f"    Exposed {added} successor(s); "
#                         f"{blocked} blocked above filling points; "
#                         f"{duplicate} already scheduled.",
#                         flush=True,
#                     )
#                     continue

#                 # -------------------------------------------------------------
#                 # Original cheap parameter-count pruning.
#                 # -------------------------------------------------------------
#                 params = _parameter_count(
#                     target,
#                     d_0,
#                     d_h,
#                 )

#                 print(
#                     f"    Parameter-count bound: {params}; "
#                     f"ambient target: {ambient_dim}.",
#                     flush=True,
#                 )

#                 if params < ambient_dim:
#                     parameter_prunes += 1
#                     known_short = _insert_maximal(
#                         known_short,
#                         target,
#                     )

#                     added, blocked, duplicate = add_successors(target)

#                     print(
#                         f"    [Dimension Pruned] {params} < "
#                         f"{ambient_dim}; no architecture evaluation needed.",
#                         flush=True,
#                     )
#                     print(
#                         f"    [Downward Pruned] The lower orthant of "
#                         f"{target} is now known nonfilling.",
#                         flush=True,
#                     )
#                     print(
#                         f"    Exposed {added} successor(s); "
#                         f"{blocked} blocked above filling points; "
#                         f"{duplicate} already scheduled.",
#                         flush=True,
#                     )
#                     continue

#                 # -------------------------------------------------------------
#                 # Reuse an exact result already present in the CSV.
#                 # -------------------------------------------------------------
#                 if target in evaluation_status:
#                     is_full = evaluation_status[target]
#                     exact_csv_reuses += 1

#                     print(
#                         f"    Reusing CSV result: "
#                         f"{'FILLING' if is_full else 'SHORT'}.",
#                         flush=True,
#                     )
#                 else:
#                     print(
#                         f"    Evaluating architecture "
#                         f"{[d_0, *target, d_h]}...",
#                         flush=True,
#                     )

#                     result = evaluate_single_architecture(
#                         target,
#                         h,
#                         d_0,
#                         d_h,
#                         exponent,
#                     )

#                     if not result:
#                         print(
#                             f"    [WARNING] No result returned for {target}. "
#                             "This branch is left unresolved for a future run.",
#                             flush=True,
#                         )
#                         continue

#                     is_full = _as_bool(
#                         result["is_full_dimension"]
#                     )
#                     evaluation_status[target] = is_full
#                     new_evaluations += 1

#                     print(
#                         f"    Dimension computed: "
#                         f"{result.get('dimension_computed', 'unknown')} / "
#                         f"{ambient_dim}.",
#                         flush=True,
#                     )

#                     df = _append_result(
#                         df,
#                         result,
#                         hidden=target,
#                         h=h,
#                         exponent=exponent,
#                         d_0=d_0,
#                         d_h=d_h,
#                         ambient_dim=ambient_dim,
#                     )

#                     # Save each completed expensive evaluation immediately.
#                     _save_csv(df, csv_path)

#                 # -------------------------------------------------------------
#                 # Update the monotone boundaries.
#                 # -------------------------------------------------------------
#                 if is_full:
#                     known_minimal = _insert_minimal(
#                         known_minimal,
#                         target,
#                     )

#                     removed = remove_queued_supersets(target)

#                     print(
#                         f"    [FILLING] {target}",
#                         flush=True,
#                     )
#                     print(
#                         f"    [Upward Pruned] {removed} queued superset(s) "
#                         "removed. No successors generated.",
#                         flush=True,
#                     )
#                 else:
#                     known_short = _insert_maximal(
#                         known_short,
#                         target,
#                     )

#                     added, blocked, duplicate = add_successors(target)

#                     print(
#                         f"    [SHORT] {target}",
#                         flush=True,
#                     )
#                     print(
#                         f"    [Downward Pruned] The lower orthant of "
#                         f"{target} is now known nonfilling.",
#                         flush=True,
#                     )
#                     print(
#                         f"    Exposed {added} successor(s); "
#                         f"{blocked} blocked above filling points; "
#                         f"{duplicate} already scheduled.",
#                         flush=True,
#                     )

#                 print(
#                     f"    Frontier status: queue={len(heap):,}, "
#                     f"scheduled={len(scheduled):,}, "
#                     f"filling boundary={len(known_minimal):,}, "
#                     f"nonfilling boundary={len(known_short):,}.",
#                     flush=True,
#                 )

#         except KeyboardInterrupt:
#             print(
#                 "\n[Interrupt] User halted the loop early. "
#                 "Saving completed evaluations to the CSV...",
#                 flush=True,
#             )

#             df = _recompute_minimality(df)
#             _save_csv(df, csv_path)

#             print(
#                 f"Database successfully saved to '{csv_path}'.",
#                 flush=True,
#             )
#             print(
#                 "Running the same cell again restarts the randomized "
#                 "frontier and reuses all existing CSV results for pruning.",
#                 flush=True,
#             )
#             return df

#         # ---------------------------------------------------------------------
#         # Finish this depth and save.
#         # ---------------------------------------------------------------------
#         print(
#             f"\n  Search complete for h={h}.",
#             flush=True,
#         )
#         print(
#             f"  Checked frontier points:      {checked:,}",
#             flush=True,
#         )
#         print(
#             f"  New architecture evaluations: {new_evaluations:,}",
#             flush=True,
#         )
#         print(
#             f"  Exact CSV result reuses:       {exact_csv_reuses:,}",
#             flush=True,
#         )
#         print(
#             f"  Parameter-count prunes:        {parameter_prunes:,}",
#             flush=True,
#         )
#         print(
#             f"  Upward order prunes:           {upward_prunes:,}",
#             flush=True,
#         )
#         print(
#             f"  Downward order prunes:         {downward_prunes:,}",
#             flush=True,
#         )
#         print(
#             f"  Current filling boundary:      "
#             f"{sorted(known_minimal)}",
#             flush=True,
#         )

#         print(
#             "Re-evaluating minimal filling properties "
#             "(grouped by depth h and exponent)...",
#             flush=True,
#         )

#         df = _recompute_minimality(df)
#         _save_csv(df, csv_path)

#         print(
#             f"Database successfully saved to '{csv_path}'.",
#             flush=True,
#         )

#     print(
#         f"\nAll requested searches completed. "
#         f"Database saved to '{csv_path}'.",
#         flush=True,
#     )

#     return df

# Execute Search

In [ ]:
# # This adjusts which depths you want to consider
# h_values_to_test = [2,3] 


# d0 = 2
# dh = 2
# r = 5

# # Optional: provide guess as tuple for the hidden layers
# my_guesses = {} 


# # Provide individual bounds for each hidden layer (length must match h - 1)
# # Format: { h_value: [(min1, max1), (min2, max2), ...] }
# custom_bounds = {
#     6: [
#         (3, 4),  # d1
#         (3, 10),  # d2
#         (5, 28),  # d3
#         (9, 82), # d4
#         (6, 18)  # d5
#     ],
# }

# # Run the bounded frontier search

# df_results = parameter_boundary_search(
#     h_values=h_values_to_test, 
#     max_width=300,        # Fallback if `h` not in layer_bounds
#     min_width=2,         # Fallback if `h` not in layer_bounds
#     exponent=r,          
#     d_0=d0,              
#     d_h=dh,              
#     csv_filename=f"../data/raw/{d0}_{dh}_r{r}_architectures.csv",
#     user_guesses=my_guesses,
#     layer_bounds=custom_bounds  # Injecting the new feature here
# )

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=5 ---
  Target Ambient Dimension: 12
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 1 impossible/redundant architectures.
  Starting sequential evaluation on 298 viable candidates.
  [FULL ] [2, 239, 2] -> Rank: 12/12 (Params: 956)
    [Upward Pruned] 61 supersets removed from queue.
  [FULL ] [2, 218, 2] -> Rank: 12/12 (Params: 872)
    [Upward Pruned] 20 supersets removed from queue.
  [FULL ] [2, 198, 2] -> Rank: 12/12 (Params: 792)
    [Upward Pruned] 19 supersets removed from queue.

  [FULL ] [2, 111, 2] -> Rank: 12/12 (Params: 444)
    [Upward Pruned] 86 supersets removed from queue.
  [FULL ] [2, 84, 2] -> Rank: 12/12 (Params: 336)
    [Upward Pruned] 26 supersets removed from queue.
  [FULL ] [2, 26, 2] -> Rank: 12/12 (Params: 104)
    [Upward Pruned] 57 supersets removed from queue.
  [FULL ] [2, 9, 2] -> Rank: 12/12 (Params: 36)
    [Upward Pruned] 16 supersets removed from queue.
  [FULL ] [2, 6, 2] -> Rank: 12/12 (Params: 24)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [2, 4, 2] -> Rank: 12/12 (Params: 16)
    [Upward Pruned] 1 supersets removed from queue.
  [SHORT] [2, 3, 2] -> Rank: 9/12 (Params: 12)

--- RANDOM SEARCH: h=3, exponent=5 ---
  Target Ambient Dimension: 52
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 40 impossible/redundant architectures.
  Starting sequential evaluation on 89361 viable candidates.
  [FULL ] [2, 63, 81, 2] -> Rank: 52/52 (Params: 5391)
    [Upward Pruned] 52359 supersets removed from queue.
  [SHORT] [2, 3, 26, 2] -> Rank: 43/52 (Params: 136)
    [Downward Pruned] 31 subsets removed from queue.
  [FULL ] [2, 160, 39, 2] -> Rank: 52/52 (Params: 6638)
    [Upward Pruned] 5921 supersets removed from queue.
  [FULL ] [2, 56, 101, 2] -> Rank: 52/52 (Params: 5970)
    [Upward Pruned] 1399 supersets removed from queue.
  [FULL ] [2, 42, 58, 2] -> Rank: 52/52 (Params: 2636)
    [Upward Pruned] 5933 supersets removed from queue.
  [FULL ] [2, 18, 34, 2] -> Rank: 52/52 (Params: 716)
    [Upward Pruned] 9944 supersets removed from queue.
  [SHORT] [2, 273, 2, 2] -> Rank: 14/52 (Params: 1096)
    [Downward Pruned] 261 subsets removed from queue.
  [FULL ] [2, 171, 16, 2] -> Rank: 52/52 (Params: 3110)
    [Upward Pruned] 2339 supersets removed from queue.
  [FULL ] [2, 124, 26, 2] -> Rank: 52/52 (Params: 3524)
    [Upward Pruned] 375 supersets removed from queue.
  [FULL ] [2, 66, 16, 2] -> Rank: 52/52 (Params: 1220)
    [Upward Pruned] 1513 supersets removed from queue.
  [FULL ] [2, 103, 15, 2] -> Rank: 52/52 (Params: 1781)
    [Upward Pruned] 197 supersets removed from queue.
  [FULL ] [2, 192, 12, 2] -> Rank: 52/52 (Params: 2712)
    [Upward Pruned] 326 supersets removed from queue.
  [FULL ] [2, 13, 15, 2] -> Rank: 52/52 (Params: 251)
    [Upward Pruned] 2378 supersets removed from queue.
  [FULL ] [2, 187, 11, 2] -> Rank: 52/52 (Params: 2453)
    [Upward Pruned] 128 supersets removed from queue.
  [FULL ] [2, 10, 252, 2] -> Rank: 52/52 (Params: 3044)
    [Upward Pruned] 146 supersets removed from queue.
  [FULL ] [2, 4, 268, 2] -> Rank: 52/52 (Params: 1616)
    [Upward Pruned] 197 supersets removed from queue.
  [FULL ] [2, 9, 126, 2] -> Rank: 52/52 (Params: 1404)
    [Upward Pruned] 519 supersets removed from queue.
  [SHORT] [2, 2, 260, 2] -> Rank: 14/52 (Params: 1044)
    [Downward Pruned] 233 subsets removed from queue.
  [SHORT] [2, 238, 3, 2] -> Rank: 21/52 (Params: 1196)
    [Downward Pruned] 228 subsets removed from queue.
  [FULL ] [2, 8, 71, 2] -> Rank: 52/52 (Params: 726)
    [Upward Pruned] 416 supersets removed from queue.
  [FULL ] [2, 27, 9, 2] -> Rank: 52/52 (Params: 315)
    [Upward Pruned] 1187 supersets removed from queue.
  [FULL ] [2, 7, 10, 2] -> Rank: 52/52 (Params: 104)
    [Upward Pruned] 632 supersets removed from queue.
  [SHORT] [2, 3, 44, 2] -> Rank: 43/52 (Params: 226)
    [Downward Pruned] 17 subsets removed from queue.
  [SHORT] [2, 174, 4, 2] -> Rank: 28/52 (Params: 1052)
    [Downward Pruned] 166 subsets removed from queue.
  [SHORT] [2, 3, 97, 2] -> Rank: 43/52 (Params: 491)
    [Downward Pruned] 52 subsets removed from queue.
  [FULL ] [2, 4, 115, 2] -> Rank: 52/52 (Params: 698)
    [Upward Pruned] 458 supersets removed from queue.
  [FULL ] [2, 6, 80, 2] -> Rank: 52/52 (Params: 652)
    [Upward Pruned] 34 supersets removed from queue.
  [SHORT] [2, 56, 6, 2] -> Rank: 42/52 (Params: 460)
    [Downward Pruned] 102 subsets removed from queue.
  [SHORT] [2, 283, 3, 2] -> Rank: 21/52 (Params: 1421)
    [Downward Pruned] 54 subsets removed from queue.
  [SHORT] [2, 136, 7, 2] -> Rank: 49/52 (Params: 1238)
    [Downward Pruned] 291 subsets removed from queue.
  [FULL ] [2, 58, 8, 2] -> Rank: 52/52 (Params: 596)
    [Upward Pruned] 242 supersets removed from queue.
  [SHORT] [2, 252, 6, 2] -> Rank: 42/52 (Params: 2028)
    [Downward Pruned] 309 subsets removed from queue.
  [FULL ] [2, 4, 17, 2] -> Rank: 52/52 (Params: 110)
    [Upward Pruned] 258 supersets removed from queue.
  [SHORT] [2, 2, 270, 2] -> Rank: 14/52 (Params: 1084)
    [Downward Pruned] 9 subsets removed from queue.
  [FULL ] [2, 41, 8, 2] -> Rank: 52/52 (Params: 426)
    [Upward Pruned] 16 supersets removed from queue.
  [FULL ] [2, 22, 9, 2] -> Rank: 52/52 (Params: 260)
    [Upward Pruned] 4 supersets removed from queue.
  [SHORT] [2, 269, 4, 2] -> Rank: 28/52 (Params: 1622)
    [Downward Pruned] 16 subsets removed from queue.
  [SHORT] [2, 283, 6, 2] -> Rank: 42/52 (Params: 2276)
    [Downward Pruned] 75 subsets removed from queue.
  [SHORT] [2, 3, 131, 2] -> Rank: 43/52 (Params: 661)
    [Downward Pruned] 33 subsets removed from queue.
  [SHORT] [2, 3, 217, 2] -> Rank: 43/52 (Params: 1091)
    [Downward Pruned] 85 subsets removed from queue.
  [SHORT] [2, 291, 5, 2] -> Rank: 35/52 (Params: 2047)
    [Downward Pruned] 31 subsets removed from queue.
  [SHORT] [2, 3, 241, 2] -> Rank: 43/52 (Params: 1211)
    [Downward Pruned] 23 subsets removed from queue.
  [SHORT] [2, 296, 5, 2] -> Rank: 35/52 (Params: 2082)
    [Downward Pruned] 19 subsets removed from queue.
  [SHORT] [2, 300, 5, 2] -> Rank: 35/52 (Params: 2110)
    [Downward Pruned] 15 subsets removed from queue.
  [FULL ] [2, 40, 8, 2] -> Rank: 52/52 (Params: 416)
  [FULL ] [2, 5, 12, 2] -> Rank: 52/52 (Params: 94)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [2, 7, 9, 2] -> Rank: 52/52 (Params: 95)
    [Upward Pruned] 14 supersets removed from queue.
  [SHORT] [2, 259, 7, 2] -> Rank: 49/52 (Params: 2345)
    [Downward Pruned] 122 subsets removed from queue.
  [SHORT] [2, 299, 6, 2] -> Rank: 42/52 (Params: 2404)
    [Downward Pruned] 15 subsets removed from queue.
  [SHORT] [2, 3, 285, 2] -> Rank: 43/52 (Params: 1431)
    [Downward Pruned] 58 subsets removed from queue.
  [FULL ] [2, 30, 8, 2] -> Rank: 52/52 (Params: 316)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [2, 4, 16, 2] -> Rank: 52/52 (Params: 104)
  [FULL ] [2, 23, 8, 2] -> Rank: 52/52 (Params: 246)
    [Upward Pruned] 6 supersets removed from queue.
  [SHORT] [2, 3, 291, 2] -> Rank: 43/52 (Params: 1461)
    [Downward Pruned] 11 subsets removed from queue.
  [FULL ] [2, 10, 8, 2] -> Rank: 52/52 (Params: 116)
    [Upward Pruned] 12 supersets removed from queue.
  [SHORT] [2, 285, 7, 2] -> Rank: 49/52 (Params: 2579)
    [Downward Pruned] 25 subsets removed from queue.
  [SHORT] [2, 293, 7, 2] -> Rank: 49/52 (Params: 2651)
    [Downward Pruned] 7 subsets removed from queue.
  [FULL ] [2, 9, 8, 2] -> Rank: 52/52 (Params: 106)
  [FULL ] [2, 4, 13, 2] -> Rank: 52/52 (Params: 86)
    [Upward Pruned] 2 supersets removed from queue.
  [SHORT] [2, 300, 6, 2] -> Rank: 42/52 (Params: 2412)
  [SHORT] [2, 4, 8, 2] -> Rank: 44/52 (Params: 56)
  [FULL ] [2, 5, 9, 2] -> Rank: 52/52 (Params: 73)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [2, 5, 8, 2] -> Rank: 52/52 (Params: 66)
    [Upward Pruned] 3 supersets removed from queue.
  [SHORT] [2, 2, 295, 2] -> Rank: 14/52 (Params: 1184)
    [Downward Pruned] 3 subsets removed from queue.
  [SHORT] [2, 294, 7, 2] -> Rank: 49/52 (Params: 2660)
  [SHORT] [2, 3, 295, 2] -> Rank: 43/52 (Params: 1481)
    [Downward Pruned] 3 subsets removed from queue.
  [SHORT] [2, 3, 296, 2] -> Rank: 43/52 (Params: 1486)
    [Downward Pruned] 1 subsets removed from queue.
  [SHORT] [2, 299, 7, 2] -> Rank: 49/52 (Params: 2705)
    [Downward Pruned] 4 subsets removed from queue.
  [SHORT] [2, 2, 299, 2] -> Rank: 14/52 (Params: 1200)
    [Downward Pruned] 2 subsets removed from queue.
  [SHORT] [2, 3, 299, 2] -> Rank: 43/52 (Params: 1501)
    [Downward Pruned] 2 subsets removed from queue.
  [SHORT] [2, 4, 9, 2] -> Rank: 49/52 (Params: 62)
  [FULL ] [2, 4, 11, 2] -> Rank: 52/52 (Params: 74)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [2, 4, 10, 2] -> Rank: 52/52 (Params: 68)
  [SHORT] [2, 300, 7, 2] -> Rank: 49/52 (Params: 2714)
  [SHORT] [2, 3, 300, 2] -> Rank: 43/52 (Params: 1506)
    [Downward Pruned] 1 subsets removed from queue.

Added 85 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/2_2_r5_architectures.csv'.

In [ ]:
# Looped version for searches


d0 = 2
dh = 2
r = 5

for d0 in range(1,10):
    for dh in range(1,10):
        for r in range(1,10):
            h_values_to_test = [2,3] 

            # Format: { h_value: [(min1, max1), (min2, max2), ...] }
            custom_bounds = {
                6: [
                    (3, 4),  # d1
                    (3, 10),  # d2
                    (5, 28),  # d3
                    (9, 82), # d4
                    (6, 18)  # d5
                ],
            }

            df_results = parameter_boundary_search(
                h_values=h_values_to_test, 
                max_width=300,        # Fallback if `h` not in layer_bounds
                min_width=2,         # Fallback if `h` not in layer_bounds
                exponent=r,          
                d_0=d0,              
                d_h=dh,              
                csv_filename=f"../data/raw/{d0}_{dh}_r{r}_architectures.csv",
                user_guesses=my_guesses,
                layer_bounds=custom_bounds  # Injecting the new feature here
            )

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=1 ---
  Target Ambient Dimension: 1
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 181, 1] -> Rank: 1/1 (Params: 362)
    [Upward Pruned] 119 supersets removed from queue.
  [FULL ] [1, 88, 1] -> Rank: 1/1 (Params: 176)
    [Upward Pruned] 92 supersets removed from queue.
  [FULL ] [1, 43, 1] -> Rank: 1/1 (Params: 86)
    [Upward Pruned] 44 supersets removed from queue.
  [FULL ] [1, 28, 1] -> Rank: 1/1 (Params: 56)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 14, 1] -> Rank: 1/1 (Params: 28)
    [Upward Pruned] 13 supersets removed from queue.

  [FULL ] [1, 8, 1] -> Rank: 1/1 (Params: 16)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 6, 1] -> Rank: 1/1 (Params: 12)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 5, 1] -> Rank: 1/1 (Params: 10)
  [FULL ] [1, 2, 1] -> Rank: 1/1 (Params: 4)
    [Upward Pruned] 2 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=1 ---
  Target Ambient Dimension: 1
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 252, 69, 1] -> Rank: 1/1 (Params: 17709)
    [Upward Pruned] 11367 supersets removed from queue.
  [FULL ] [1, 211, 275, 1] -> Rank: 1/1 (Params: 58511)
    [Upward Pruned] 1065 supersets removed from queue.
  [FULL ] [1, 218, 117, 1] -> Rank: 1/1 (Params: 25841)
    [Upward Pruned] 5371 supersets removed from queue.
  [FULL ] [1, 82, 259, 1] -> Rank: 1/1 (Params: 21579)
    [Upward Pruned] 5529 supersets removed from queue.
  [FULL ] [1, 46, 295, 1] -> Rank: 1/1 (Params: 13911)
    [Upward Pruned] 215 supersets removed from queue.
  [FULL ] [1, 32, 85, 1] -> Rank: 1/1 (Params: 2837)
    [Upward Pruned] 35335 supersets removed from queue.
  [FULL ] [1, 145, 62, 1] -> Rank: 1/1 (Params: 9197)
    [Upward Pruned] 2803 supersets removed from queue.
  [FULL ] [1, 142, 81, 1] -> Rank: 1/1 (Params: 11725)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 207, 40, 1] -> Rank: 1/1 (Params: 8527)
    [Upward Pruned] 2067 supersets removed from queue.
  [FULL ] [1, 295, 11, 1] -> Rank: 1/1 (Params: 3551)
    [Upward Pruned] 173 supersets removed from queue.
  [FULL ] [1, 73, 55, 1] -> Rank: 1/1 (Params: 4143)
    [Upward Pruned] 2581 supersets removed from queue.
  [FULL ] [1, 279, 33, 1] -> Rank: 1/1 (Params: 9519)
    [Upward Pruned] 111 supersets removed from queue.
  [FULL ] [1, 79, 39, 1] -> Rank: 1/1 (Params: 3199)
    [Upward Pruned] 2119 supersets removed from queue.
  [FULL ] [1, 141, 13, 1] -> Rank: 1/1 (Params: 1987)
    [Upward Pruned] 3907 supersets removed from queue.
  [FULL ] [1, 60, 30, 1] -> Rank: 1/1 (Params: 1890)
    [Upward Pruned] 1422 supersets removed from queue.
  [FULL ] [1, 5, 193, 1] -> Rank: 1/1 (Params: 1163)
    [Upward Pruned] 2915 supersets removed from queue.
  [FULL ] [1, 105, 8, 1] -> Rank: 1/1 (Params: 953)
    [Upward Pruned] 1579 supersets removed from queue.
  [FULL ] [1, 93, 23, 1] -> Rank: 1/1 (Params: 2255)
    [Upward Pruned] 83 supersets removed from queue.
  [FULL ] [1, 55, 48, 1] -> Rank: 1/1 (Params: 2743)
    [Upward Pruned] 184 supersets removed from queue.
  [FULL ] [1, 94, 14, 1] -> Rank: 1/1 (Params: 1424)
    [Upward Pruned] 98 supersets removed from queue.
  [FULL ] [1, 73, 22, 1] -> Rank: 1/1 (Params: 1701)
    [Upward Pruned] 160 supersets removed from queue.
  [FULL ] [1, 55, 28, 1] -> Rank: 1/1 (Params: 1623)
    [Upward Pruned] 125 supersets removed from queue.
  [FULL ] [1, 18, 115, 1] -> Rank: 1/1 (Params: 2203)
    [Upward Pruned] 1091 supersets removed from queue.
  [FULL ] [1, 42, 80, 1] -> Rank: 1/1 (Params: 3482)
    [Upward Pruned] 64 supersets removed from queue.
  [FULL ] [1, 10, 15, 1] -> Rank: 1/1 (Params: 175)
    [Upward Pruned] 4749 supersets removed from queue.
  [FULL ] [1, 9, 55, 1] -> Rank: 1/1 (Params: 559)
    [Upward Pruned] 137 supersets removed from queue.
  [FULL ] [1, 256, 5, 1] -> Rank: 1/1 (Params: 1541)
    [Upward Pruned] 134 supersets removed from queue.
  [FULL ] [1, 5, 35, 1] -> Rank: 1/1 (Params: 215)
    [Upward Pruned] 651 supersets removed from queue.
  [FULL ] [1, 3, 91, 1] -> Rank: 1/1 (Params: 367)
    [Upward Pruned] 419 supersets removed from queue.
  [FULL ] [1, 206, 5, 1] -> Rank: 1/1 (Params: 1241)
    [Upward Pruned] 149 supersets removed from queue.
  [FULL ] [1, 2, 216, 1] -> Rank: 1/1 (Params: 650)
    [Upward Pruned] 84 supersets removed from queue.
  [FULL ] [1, 286, 2, 1] -> Rank: 1/1 (Params: 860)
    [Upward Pruned] 44 supersets removed from queue.
  [FULL ] [1, 2, 15, 1] -> Rank: 1/1 (Params: 47)
    [Upward Pruned] 452 supersets removed from queue.
  [FULL ] [1, 10, 2, 1] -> Rank: 1/1 (Params: 32)
    [Upward Pruned] 2069 supersets removed from queue.
  [FULL ] [1, 3, 5, 1] -> Rank: 1/1 (Params: 23)
    [Upward Pruned] 69 supersets removed from queue.
  [FULL ] [1, 6, 4, 1] -> Rank: 1/1 (Params: 34)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 3, 3, 1] -> Rank: 1/1 (Params: 15)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 9, 2, 1] -> Rank: 1/1 (Params: 29)
  [FULL ] [1, 2, 5, 1] -> Rank: 1/1 (Params: 17)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 2, 3, 1] -> Rank: 1/1 (Params: 11)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 2, 1] -> Rank: 1/1 (Params: 8)
    [Upward Pruned] 6 supersets removed from queue.

Added 50 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_1_r1_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=2 ---
  Target Ambient Dimension: 1
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 162, 1] -> Rank: 1/1 (Params: 324)
    [Upward Pruned] 138 supersets removed from queue.
  [FULL ] [1, 85, 1] -> Rank: 1/1 (Params: 170)
    [Upward Pruned] 76 supersets removed from queue.
  [FULL ] [1, 40, 1] -> Rank: 1/1 (Params: 80)
    [Upward Pruned] 44 supersets removed from queue.
  [FULL ] [1, 32, 1] -> Rank: 1/1 (Params: 64)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 27, 1] -> Rank: 1/1 (Params: 54)
    [Upward Pruned] 4 supersets removed from queue.

  [FULL ] [1, 18, 1] -> Rank: 1/1 (Params: 36)
    [Upward Pruned] 8 supersets removed from queue.
  [FULL ] [1, 15, 1] -> Rank: 1/1 (Params: 30)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 4, 1] -> Rank: 1/1 (Params: 8)
    [Upward Pruned] 10 supersets removed from queue.
  [FULL ] [1, 3, 1] -> Rank: 1/1 (Params: 6)
  [FULL ] [1, 2, 1] -> Rank: 1/1 (Params: 4)

--- RANDOM SEARCH: h=3, exponent=2 ---
  Target Ambient Dimension: 1
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 277, 137, 1] -> Rank: 1/1 (Params: 38363)
    [Upward Pruned] 3935 supersets removed from queue.
  [FULL ] [1, 171, 187, 1] -> Rank: 1/1 (Params: 32335)
    [Upward Pruned] 12083 supersets removed from queue.
  [FULL ] [1, 13, 83, 1] -> Rank: 1/1 (Params: 1175)
    [Upward Pruned] 46763 supersets removed from queue.
  [FULL ] [1, 30, 16, 1] -> Rank: 1/1 (Params: 526)
    [Upward Pruned] 18156 supersets removed from queue.
  [FULL ] [1, 7, 201, 1] -> Rank: 1/1 (Params: 1615)
    [Upward Pruned] 599 supersets removed from queue.
  [FULL ] [1, 42, 9, 1] -> Rank: 1/1 (Params: 429)
    [Upward Pruned] 1812 supersets removed from queue.
  [FULL ] [1, 72, 5, 1] -> Rank: 1/1 (Params: 437)
    [Upward Pruned] 915 supersets removed from queue.
  [FULL ] [1, 241, 4, 1] -> Rank: 1/1 (Params: 1209)
    [Upward Pruned] 59 supersets removed from queue.
  [FULL ] [1, 2, 110, 1] -> Rank: 1/1 (Params: 332)
    [Upward Pruned] 1500 supersets removed from queue.
  [FULL ] [1, 20, 66, 1] -> Rank: 1/1 (Params: 1406)
    [Upward Pruned] 169 supersets removed from queue.
  [FULL ] [1, 29, 6, 1] -> Rank: 1/1 (Params: 209)
    [Upward Pruned] 269 supersets removed from queue.
  [FULL ] [1, 2, 45, 1] -> Rank: 1/1 (Params: 137)
    [Upward Pruned] 1169 supersets removed from queue.
  [FULL ] [1, 263, 3, 1] -> Rank: 1/1 (Params: 1055)
    [Upward Pruned] 37 supersets removed from queue.
  [FULL ] [1, 20, 37, 1] -> Rank: 1/1 (Params: 797)
    [Upward Pruned] 71 supersets removed from queue.
  [FULL ] [1, 94, 3, 1] -> Rank: 1/1 (Params: 379)
    [Upward Pruned] 315 supersets removed from queue.
  [FULL ] [1, 12, 13, 1] -> Rank: 1/1 (Params: 181)
    [Upward Pruned] 471 supersets removed from queue.
  [FULL ] [1, 85, 4, 1] -> Rank: 1/1 (Params: 429)
    [Upward Pruned] 8 supersets removed from queue.
  [FULL ] [1, 43, 5, 1] -> Rank: 1/1 (Params: 263)
    [Upward Pruned] 28 supersets removed from queue.
  [FULL ] [1, 28, 12, 1] -> Rank: 1/1 (Params: 376)
  [FULL ] [1, 11, 30, 1] -> Rank: 1/1 (Params: 371)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 184, 2, 1] -> Rank: 1/1 (Params: 554)
    [Upward Pruned] 116 supersets removed from queue.
  [FULL ] [1, 47, 4, 1] -> Rank: 1/1 (Params: 239)
    [Upward Pruned] 37 supersets removed from queue.
  [FULL ] [1, 16, 2, 1] -> Rank: 1/1 (Params: 50)
    [Upward Pruned] 393 supersets removed from queue.
  [FULL ] [1, 8, 9, 1] -> Rank: 1/1 (Params: 89)
    [Upward Pruned] 144 supersets removed from queue.
  [FULL ] [1, 2, 37, 1] -> Rank: 1/1 (Params: 113)
    [Upward Pruned] 47 supersets removed from queue.
  [FULL ] [1, 6, 32, 1] -> Rank: 1/1 (Params: 230)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 3, 14, 1] -> Rank: 1/1 (Params: 59)
    [Upward Pruned] 104 supersets removed from queue.
  [FULL ] [1, 9, 8, 1] -> Rank: 1/1 (Params: 89)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 9, 7, 1] -> Rank: 1/1 (Params: 79)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 6, 8, 1] -> Rank: 1/1 (Params: 62)
    [Upward Pruned] 12 supersets removed from queue.
  [FULL ] [1, 4, 4, 1] -> Rank: 1/1 (Params: 24)
    [Upward Pruned] 52 supersets removed from queue.
  [FULL ] [1, 2, 22, 1] -> Rank: 1/1 (Params: 68)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 3, 3, 1] -> Rank: 1/1 (Params: 15)
    [Upward Pruned] 22 supersets removed from queue.
  [FULL ] [1, 9, 2, 1] -> Rank: 1/1 (Params: 29)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 2, 5, 1] -> Rank: 1/1 (Params: 17)
    [Upward Pruned] 16 supersets removed from queue.
  [FULL ] [1, 4, 2, 1] -> Rank: 1/1 (Params: 14)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 2, 3, 1] -> Rank: 1/1 (Params: 11)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 2, 1] -> Rank: 1/1 (Params: 8)
    [Upward Pruned] 1 supersets removed from queue.

Added 48 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_1_r2_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=3 ---
  Target Ambient Dimension: 1
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 259, 1] -> Rank: 1/1 (Params: 518)
    [Upward Pruned] 41 supersets removed from queue.
  [FULL ] [1, 45, 1] -> Rank: 1/1 (Params: 90)
    [Upward Pruned] 213 supersets removed from queue.
  [FULL ] [1, 18, 1] -> Rank: 1/1 (Params: 36)
    [Upward Pruned] 26 supersets removed from queue.
  [FULL ] [1, 8, 1] -> Rank: 1/1 (Params: 16)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 7, 1] -> Rank: 1/1 (Params: 14)
  [FULL ] [1, 2, 1] -> Rank: 1/1 (Params: 4)
    [Upward Pruned] 4 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=3 ---
  Target Ambient Dimension: 1
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 29, 188, 1] -> Rank: 1/1 (Params: 5669)
    [Upward Pruned] 30735 supersets removed from queue.
  [FULL ] [1, 90, 157, 1] -> Rank: 1/1 (Params: 14377)
    [Upward Pruned] 6540 supersets removed from queue.
  [FULL ] [1, 278, 44, 1] -> Rank: 1/1 (Params: 12554)
    [Upward Pruned] 2598 supersets removed from queue.
  [FULL ] [1, 161, 44, 1] -> Rank: 1/1 (Params: 7289)
    [Upward Pruned] 13220 supersets removed from queue.
  [FULL ] [1, 6, 127, 1] -> Rank: 1/1 (Params: 895)
    [Upward Pruned] 9852 supersets removed from queue.
  [FULL ] [1, 13, 105, 1] -> Rank: 1/1 (Params: 1483)
    [Upward Pruned] 3255 supersets removed from queue.
  [FULL ] [1, 25, 72, 1] -> Rank: 1/1 (Params: 1897)
    [Upward Pruned] 4487 supersets removed from queue.
  [FULL ] [1, 225, 31, 1] -> Rank: 1/1 (Params: 7231)
    [Upward Pruned] 987 supersets removed from queue.
  [FULL ] [1, 196, 13, 1] -> Rank: 1/1 (Params: 2757)
    [Upward Pruned] 2266 supersets removed from queue.
  [FULL ] [1, 38, 14, 1] -> Rank: 1/1 (Params: 584)
    [Upward Pruned] 8183 supersets removed from queue.
  [FULL ] [1, 37, 7, 1] -> Rank: 1/1 (Params: 303)
    [Upward Pruned] 1800 supersets removed from queue.
  [FULL ] [1, 30, 56, 1] -> Rank: 1/1 (Params: 1766)
    [Upward Pruned] 111 supersets removed from queue.
  [FULL ] [1, 59, 6, 1] -> Rank: 1/1 (Params: 419)
    [Upward Pruned] 241 supersets removed from queue.
  [FULL ] [1, 9, 42, 1] -> Rank: 1/1 (Params: 429)
    [Upward Pruned] 1343 supersets removed from queue.
  [FULL ] [1, 2, 18, 1] -> Rank: 1/1 (Params: 56)
    [Upward Pruned] 2130 supersets removed from queue.
  [FULL ] [1, 281, 5, 1] -> Rank: 1/1 (Params: 1691)
    [Upward Pruned] 19 supersets removed from queue.
  [FULL ] [1, 23, 6, 1] -> Rank: 1/1 (Params: 167)
    [Upward Pruned] 189 supersets removed from queue.
  [FULL ] [1, 115, 5, 1] -> Rank: 1/1 (Params: 695)
    [Upward Pruned] 165 supersets removed from queue.
  [FULL ] [1, 18, 6, 1] -> Rank: 1/1 (Params: 132)
    [Upward Pruned] 59 supersets removed from queue.
  [FULL ] [1, 271, 3, 1] -> Rank: 1/1 (Params: 1087)
    [Upward Pruned] 59 supersets removed from queue.
  [FULL ] [1, 254, 3, 1] -> Rank: 1/1 (Params: 1019)
    [Upward Pruned] 33 supersets removed from queue.
  [FULL ] [1, 25, 4, 1] -> Rank: 1/1 (Params: 129)
    [Upward Pruned] 318 supersets removed from queue.
  [FULL ] [1, 187, 2, 1] -> Rank: 1/1 (Params: 563)
    [Upward Pruned] 180 supersets removed from queue.
  [FULL ] [1, 146, 2, 1] -> Rank: 1/1 (Params: 440)
    [Upward Pruned] 81 supersets removed from queue.
  [FULL ] [1, 5, 8, 1] -> Rank: 1/1 (Params: 53)
    [Upward Pruned] 129 supersets removed from queue.
  [FULL ] [1, 2, 10, 1] -> Rank: 1/1 (Params: 32)
    [Upward Pruned] 23 supersets removed from queue.
  [FULL ] [1, 116, 3, 1] -> Rank: 1/1 (Params: 467)
    [Upward Pruned] 29 supersets removed from queue.
  [FULL ] [1, 61, 3, 1] -> Rank: 1/1 (Params: 247)
    [Upward Pruned] 54 supersets removed from queue.
  [FULL ] [1, 5, 2, 1] -> Rank: 1/1 (Params: 17)
    [Upward Pruned] 262 supersets removed from queue.
  [FULL ] [1, 3, 4, 1] -> Rank: 1/1 (Params: 19)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 2, 9, 1] -> Rank: 1/1 (Params: 29)
  [FULL ] [1, 2, 4, 1] -> Rank: 1/1 (Params: 14)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 3, 2, 1] -> Rank: 1/1 (Params: 11)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 2, 2, 1] -> Rank: 1/1 (Params: 8)
    [Upward Pruned] 1 supersets removed from queue.

Added 40 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_1_r3_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=4 ---
  Target Ambient Dimension: 1
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 60, 1] -> Rank: 1/1 (Params: 120)
    [Upward Pruned] 240 supersets removed from queue.
  [FULL ] [1, 28, 1] -> Rank: 1/1 (Params: 56)
    [Upward Pruned] 31 supersets removed from queue.
  [FULL ] [1, 15, 1] -> Rank: 1/1 (Params: 30)
    [Upward Pruned] 12 supersets removed from queue.
  [FULL ] [1, 7, 1] -> Rank: 1/1 (Params: 14)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 2, 1] -> Rank: 1/1 (Params: 4)
    [Upward Pruned] 4 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=4 ---
  Target Ambient Dimension: 1
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 164, 4, 1] -> Rank: 1/1 (Params: 824)
    [Upward Pruned] 40688 supersets removed from queue.
  [FULL ] [1, 68, 109, 1] -> Rank: 1/1 (Params: 7589)
    [Upward Pruned] 18431 supersets removed from queue.
  [FULL ] [1, 23, 85, 1] -> Rank: 1/1 (Params: 2063)
    [Upward Pruned] 12023 supersets removed from queue.
  [FULL ] [1, 47, 73, 1] -> Rank: 1/1 (Params: 3551)
    [Upward Pruned] 1403 supersets removed from queue.
  [FULL ] [1, 155, 49, 1] -> Rank: 1/1 (Params: 7799)
    [Upward Pruned] 215 supersets removed from queue.
  [FULL ] [1, 11, 275, 1] -> Rank: 1/1 (Params: 3311)
    [Upward Pruned] 311 supersets removed from queue.
  [FULL ] [1, 23, 9, 1] -> Rank: 1/1 (Params: 239)
    [Upward Pruned] 9095 supersets removed from queue.
  [FULL ] [1, 12, 235, 1] -> Rank: 1/1 (Params: 3067)
    [Upward Pruned] 439 supersets removed from queue.
  [FULL ] [1, 16, 72, 1] -> Rank: 1/1 (Params: 1240)
    [Upward Pruned] 1140 supersets removed from queue.
  [FULL ] [1, 5, 78, 1] -> Rank: 1/1 (Params: 473)
    [Upward Pruned] 2162 supersets removed from queue.
  [FULL ] [1, 3, 217, 1] -> Rank: 1/1 (Params: 871)
    [Upward Pruned] 167 supersets removed from queue.
  [FULL ] [1, 141, 8, 1] -> Rank: 1/1 (Params: 1277)
    [Upward Pruned] 22 supersets removed from queue.
  [FULL ] [1, 10, 65, 1] -> Rank: 1/1 (Params: 725)
    [Upward Pruned] 126 supersets removed from queue.
  [FULL ] [1, 7, 39, 1] -> Rank: 1/1 (Params: 319)
    [Upward Pruned] 454 supersets removed from queue.
  [FULL ] [1, 130, 2, 1] -> Rank: 1/1 (Params: 392)
    [Upward Pruned] 488 supersets removed from queue.
  [FULL ] [1, 15, 16, 1] -> Rank: 1/1 (Params: 271)
    [Upward Pruned] 183 supersets removed from queue.
  [FULL ] [1, 114, 8, 1] -> Rank: 1/1 (Params: 1034)
    [Upward Pruned] 15 supersets removed from queue.
  [FULL ] [1, 2, 20, 1] -> Rank: 1/1 (Params: 62)
    [Upward Pruned] 942 supersets removed from queue.
  [FULL ] [1, 30, 7, 1] -> Rank: 1/1 (Params: 247)
    [Upward Pruned] 183 supersets removed from queue.
  [FULL ] [1, 54, 2, 1] -> Rank: 1/1 (Params: 164)
    [Upward Pruned] 379 supersets removed from queue.
  [FULL ] [1, 52, 4, 1] -> Rank: 1/1 (Params: 264)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 19, 12, 1] -> Rank: 1/1 (Params: 259)
    [Upward Pruned] 15 supersets removed from queue.
  [FULL ] [1, 16, 2, 1] -> Rank: 1/1 (Params: 50)
    [Upward Pruned] 244 supersets removed from queue.
  [FULL ] [1, 6, 12, 1] -> Rank: 1/1 (Params: 90)
    [Upward Pruned] 75 supersets removed from queue.
  [FULL ] [1, 4, 19, 1] -> Rank: 1/1 (Params: 99)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 4, 4, 1] -> Rank: 1/1 (Params: 24)
    [Upward Pruned] 109 supersets removed from queue.
  [FULL ] [1, 2, 13, 1] -> Rank: 1/1 (Params: 41)
    [Upward Pruned] 13 supersets removed from queue.
  [FULL ] [1, 13, 2, 1] -> Rank: 1/1 (Params: 41)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 2, 10, 1] -> Rank: 1/1 (Params: 32)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 12, 3, 1] -> Rank: 1/1 (Params: 51)
  [FULL ] [1, 3, 4, 1] -> Rank: 1/1 (Params: 19)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 11, 3, 1] -> Rank: 1/1 (Params: 47)
  [FULL ] [1, 8, 2, 1] -> Rank: 1/1 (Params: 26)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 2, 9, 1] -> Rank: 1/1 (Params: 29)
  [FULL ] [1, 4, 2, 1] -> Rank: 1/1 (Params: 14)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 2, 8, 1] -> Rank: 1/1 (Params: 26)
  [FULL ] [1, 2, 6, 1] -> Rank: 1/1 (Params: 20)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 3, 1] -> Rank: 1/1 (Params: 11)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 2, 2, 1] -> Rank: 1/1 (Params: 8)
    [Upward Pruned] 1 supersets removed from queue.

Added 44 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_1_r4_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=5 ---
  Target Ambient Dimension: 1
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 244, 1] -> Rank: 1/1 (Params: 488)
    [Upward Pruned] 56 supersets removed from queue.
  [FULL ] [1, 41, 1] -> Rank: 1/1 (Params: 82)
    [Upward Pruned] 202 supersets removed from queue.
  [FULL ] [1, 27, 1] -> Rank: 1/1 (Params: 54)
    [Upward Pruned] 13 supersets removed from queue.
  [FULL ] [1, 21, 1] -> Rank: 1/1 (Params: 42)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 19, 1] -> Rank: 1/1 (Params: 38)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 4, 1] -> Rank: 1/1 (Params: 8)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 3, 1] -> Rank: 1/1 (Params: 6)
  [FULL ] [1, 2, 1] -> Rank: 1/1 (Params: 4)

--- RANDOM SEARCH: h=3, exponent=5 ---
  Target Ambient Dimension: 1
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 4, 284, 1] -> Rank: 1/1 (Params: 1424)
    [Upward Pruned] 5048 supersets removed from queue.
  [FULL ] [1, 100, 8, 1] -> Rank: 1/1 (Params: 908)
    [Upward Pruned] 55475 supersets removed from queue.
  [FULL ] [1, 9, 88, 1] -> Rank: 1/1 (Params: 889)
    [Upward Pruned] 17835 supersets removed from queue.
  [FULL ] [1, 87, 41, 1] -> Rank: 1/1 (Params: 3695)
    [Upward Pruned] 610 supersets removed from queue.
  [FULL ] [1, 19, 49, 1] -> Rank: 1/1 (Params: 999)
    [Upward Pruned] 2651 supersets removed from queue.
  [FULL ] [1, 33, 20, 1] -> Rank: 1/1 (Params: 713)
    [Upward Pruned] 1838 supersets removed from queue.
  [FULL ] [1, 6, 159, 1] -> Rank: 1/1 (Params: 1119)
    [Upward Pruned] 374 supersets removed from queue.
  [FULL ] [1, 259, 3, 1] -> Rank: 1/1 (Params: 1039)
    [Upward Pruned] 209 supersets removed from queue.
  [FULL ] [1, 15, 59, 1] -> Rank: 1/1 (Params: 959)
    [Upward Pruned] 115 supersets removed from queue.
  [FULL ] [1, 5, 179, 1] -> Rank: 1/1 (Params: 1079)
    [Upward Pruned] 104 supersets removed from queue.
  [FULL ] [1, 8, 99, 1] -> Rank: 1/1 (Params: 899)
    [Upward Pruned] 59 supersets removed from queue.
  [FULL ] [1, 223, 6, 1] -> Rank: 1/1 (Params: 1567)
    [Upward Pruned] 71 supersets removed from queue.
  [FULL ] [1, 83, 9, 1] -> Rank: 1/1 (Params: 839)
    [Upward Pruned] 186 supersets removed from queue.
  [FULL ] [1, 99, 4, 1] -> Rank: 1/1 (Params: 499)
    [Upward Pruned] 568 supersets removed from queue.
  [FULL ] [1, 4, 63, 1] -> Rank: 1/1 (Params: 319)
    [Upward Pruned] 714 supersets removed from queue.
  [FULL ] [1, 72, 2, 1] -> Rank: 1/1 (Params: 218)
    [Upward Pruned] 671 supersets removed from queue.
  [FULL ] [1, 21, 26, 1] -> Rank: 1/1 (Params: 593)
    [Upward Pruned] 275 supersets removed from queue.
  [FULL ] [1, 14, 19, 1] -> Rank: 1/1 (Params: 299)
    [Upward Pruned] 386 supersets removed from queue.
  [FULL ] [1, 35, 16, 1] -> Rank: 1/1 (Params: 611)
    [Upward Pruned] 110 supersets removed from queue.
  [FULL ] [1, 68, 8, 1] -> Rank: 1/1 (Params: 620)
    [Upward Pruned] 31 supersets removed from queue.
  [FULL ] [1, 62, 9, 1] -> Rank: 1/1 (Params: 629)
    [Upward Pruned] 41 supersets removed from queue.
  [FULL ] [1, 3, 157, 1] -> Rank: 1/1 (Params: 631)
    [Upward Pruned] 143 supersets removed from queue.
  [FULL ] [1, 10, 31, 1] -> Rank: 1/1 (Params: 351)
    [Upward Pruned] 127 supersets removed from queue.
  [FULL ] [1, 13, 25, 1] -> Rank: 1/1 (Params: 363)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 3, 73, 1] -> Rank: 1/1 (Params: 295)
    [Upward Pruned] 83 supersets removed from queue.
  [FULL ] [1, 38, 14, 1] -> Rank: 1/1 (Params: 584)
    [Upward Pruned] 47 supersets removed from queue.
  [FULL ] [1, 62, 8, 1] -> Rank: 1/1 (Params: 566)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 7, 48, 1] -> Rank: 1/1 (Params: 391)
    [Upward Pruned] 44 supersets removed from queue.
  [FULL ] [1, 2, 63, 1] -> Rank: 1/1 (Params: 191)
    [Upward Pruned] 247 supersets removed from queue.
  [FULL ] [1, 50, 4, 1] -> Rank: 1/1 (Params: 254)
    [Upward Pruned] 159 supersets removed from queue.
  [FULL ] [1, 7, 2, 1] -> Rank: 1/1 (Params: 23)
    [Upward Pruned] 834 supersets removed from queue.
  [FULL ] [1, 5, 47, 1] -> Rank: 1/1 (Params: 287)
    [Upward Pruned] 31 supersets removed from queue.
  [FULL ] [1, 2, 43, 1] -> Rank: 1/1 (Params: 131)
    [Upward Pruned] 67 supersets removed from queue.
  [FULL ] [1, 5, 39, 1] -> Rank: 1/1 (Params: 239)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 3, 24, 1] -> Rank: 1/1 (Params: 99)
    [Upward Pruned] 67 supersets removed from queue.
  [FULL ] [1, 4, 17, 1] -> Rank: 1/1 (Params: 89)
    [Upward Pruned] 20 supersets removed from queue.
  [FULL ] [1, 2, 14, 1] -> Rank: 1/1 (Params: 44)
    [Upward Pruned] 47 supersets removed from queue.
  [FULL ] [1, 4, 2, 1] -> Rank: 1/1 (Params: 14)
    [Upward Pruned] 35 supersets removed from queue.
  [FULL ] [1, 3, 5, 1] -> Rank: 1/1 (Params: 23)
    [Upward Pruned] 8 supersets removed from queue.
  [FULL ] [1, 2, 11, 1] -> Rank: 1/1 (Params: 35)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 2, 10, 1] -> Rank: 1/1 (Params: 32)
  [FULL ] [1, 2, 8, 1] -> Rank: 1/1 (Params: 26)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 3, 4, 1] -> Rank: 1/1 (Params: 19)
  [FULL ] [1, 2, 6, 1] -> Rank: 1/1 (Params: 20)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 2, 1] -> Rank: 1/1 (Params: 8)
    [Upward Pruned] 5 supersets removed from queue.

Added 53 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_1_r5_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=6 ---
  Target Ambient Dimension: 1
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 264, 1] -> Rank: 1/1 (Params: 528)
    [Upward Pruned] 36 supersets removed from queue.
  [FULL ] [1, 238, 1] -> Rank: 1/1 (Params: 476)
    [Upward Pruned] 25 supersets removed from queue.
  [FULL ] [1, 28, 1] -> Rank: 1/1 (Params: 56)
    [Upward Pruned] 209 supersets removed from queue.
  [FULL ] [1, 3, 1] -> Rank: 1/1 (Params: 6)
    [Upward Pruned] 24 supersets removed from queue.

  [FULL ] [1, 2, 1] -> Rank: 1/1 (Params: 4)

--- RANDOM SEARCH: h=3, exponent=6 ---
  Target Ambient Dimension: 1
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 296, 219, 1] -> Rank: 1/1 (Params: 65339)
    [Upward Pruned] 409 supersets removed from queue.
  [FULL ] [1, 295, 179, 1] -> Rank: 1/1 (Params: 53279)
    [Upward Pruned] 321 supersets removed from queue.
  [FULL ] [1, 134, 109, 1] -> Rank: 1/1 (Params: 14849)
    [Upward Pruned] 31331 supersets removed from queue.
  [FULL ] [1, 81, 60, 1] -> Rank: 1/1 (Params: 5001)
    [Upward Pruned] 20955 supersets removed from queue.
  [FULL ] [1, 32, 235, 1] -> Rank: 1/1 (Params: 7787)
    [Upward Pruned] 3233 supersets removed from queue.
  [FULL ] [1, 90, 58, 1] -> Rank: 1/1 (Params: 5368)
    [Upward Pruned] 421 supersets removed from queue.
  [FULL ] [1, 40, 192, 1] -> Rank: 1/1 (Params: 7912)
    [Upward Pruned] 1762 supersets removed from queue.
  [FULL ] [1, 23, 31, 1] -> Rank: 1/1 (Params: 767)
    [Upward Pruned] 16620 supersets removed from queue.
  [FULL ] [1, 277, 5, 1] -> Rank: 1/1 (Params: 1667)
    [Upward Pruned] 623 supersets removed from queue.
  [FULL ] [1, 95, 16, 1] -> Rank: 1/1 (Params: 1631)
    [Upward Pruned] 2729 supersets removed from queue.
  [FULL ] [1, 10, 54, 1] -> Rank: 1/1 (Params: 604)
    [Upward Pruned] 3210 supersets removed from queue.
  [FULL ] [1, 17, 35, 1] -> Rank: 1/1 (Params: 647)
    [Upward Pruned] 113 supersets removed from queue.
  [FULL ] [1, 2, 172, 1] -> Rank: 1/1 (Params: 518)
    [Upward Pruned] 1031 supersets removed from queue.
  [FULL ] [1, 59, 14, 1] -> Rank: 1/1 (Params: 899)
    [Upward Pruned] 975 supersets removed from queue.
  [FULL ] [1, 143, 7, 1] -> Rank: 1/1 (Params: 1151)
    [Upward Pruned] 937 supersets removed from queue.
  [FULL ] [1, 8, 125, 1] -> Rank: 1/1 (Params: 1133)
    [Upward Pruned] 93 supersets removed from queue.
  [FULL ] [1, 12, 13, 1] -> Rank: 1/1 (Params: 181)
    [Upward Pruned] 1068 supersets removed from queue.
  [FULL ] [1, 3, 133, 1] -> Rank: 1/1 (Params: 535)
    [Upward Pruned] 194 supersets removed from queue.
  [FULL ] [1, 214, 6, 1] -> Rank: 1/1 (Params: 1504)
    [Upward Pruned] 62 supersets removed from queue.
  [FULL ] [1, 258, 3, 1] -> Rank: 1/1 (Params: 1035)
    [Upward Pruned] 104 supersets removed from queue.
  [FULL ] [1, 43, 8, 1] -> Rank: 1/1 (Params: 395)
    [Upward Pruned] 499 supersets removed from queue.
  [FULL ] [1, 37, 8, 1] -> Rank: 1/1 (Params: 341)
    [Upward Pruned] 29 supersets removed from queue.
  [FULL ] [1, 120, 5, 1] -> Rank: 1/1 (Params: 725)
    [Upward Pruned] 254 supersets removed from queue.
  [FULL ] [1, 4, 7, 1] -> Rank: 1/1 (Params: 39)
    [Upward Pruned] 1066 supersets removed from queue.
  [FULL ] [1, 151, 4, 1] -> Rank: 1/1 (Params: 759)
    [Upward Pruned] 106 supersets removed from queue.
  [FULL ] [1, 207, 2, 1] -> Rank: 1/1 (Params: 623)
    [Upward Pruned] 144 supersets removed from queue.
  [FULL ] [1, 20, 2, 1] -> Rank: 1/1 (Params: 62)
    [Upward Pruned] 704 supersets removed from queue.
  [FULL ] [1, 2, 34, 1] -> Rank: 1/1 (Params: 104)
    [Upward Pruned] 236 supersets removed from queue.
  [FULL ] [1, 4, 5, 1] -> Rank: 1/1 (Params: 29)
    [Upward Pruned] 31 supersets removed from queue.
  [FULL ] [1, 17, 4, 1] -> Rank: 1/1 (Params: 89)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 3, 17, 1] -> Rank: 1/1 (Params: 71)
    [Upward Pruned] 16 supersets removed from queue.
  [FULL ] [1, 13, 2, 1] -> Rank: 1/1 (Params: 41)
    [Upward Pruned] 17 supersets removed from queue.
  [FULL ] [1, 3, 6, 1] -> Rank: 1/1 (Params: 27)
    [Upward Pruned] 10 supersets removed from queue.
  [FULL ] [1, 9, 4, 1] -> Rank: 1/1 (Params: 49)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 4, 2, 1] -> Rank: 1/1 (Params: 14)
    [Upward Pruned] 22 supersets removed from queue.
  [FULL ] [1, 2, 8, 1] -> Rank: 1/1 (Params: 26)
    [Upward Pruned] 25 supersets removed from queue.
  [FULL ] [1, 2, 4, 1] -> Rank: 1/1 (Params: 14)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 3, 3, 1] -> Rank: 1/1 (Params: 15)
  [FULL ] [1, 2, 2, 1] -> Rank: 1/1 (Params: 8)
    [Upward Pruned] 2 supersets removed from queue.

Added 44 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_1_r6_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=7 ---
  Target Ambient Dimension: 1
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 10, 1] -> Rank: 1/1 (Params: 20)
    [Upward Pruned] 290 supersets removed from queue.
  [FULL ] [1, 4, 1] -> Rank: 1/1 (Params: 8)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 3, 1] -> Rank: 1/1 (Params: 6)
  [FULL ] [1, 2, 1] -> Rank: 1/1 (Params: 4)

--- RANDOM SEARCH: h=3, exponent=7 ---
  Target Ambient Dimension: 1
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 98, 189, 1] -> Rank: 1/1 (Params: 18809)
    [Upward Pruned] 22735 supersets removed from queue.
  [FULL ] [1, 225, 158, 1] -> Rank: 1/1 (Params: 35933)
    [Upward Pruned] 2355 supersets removed from queue.
  [FULL ] [1, 9, 191, 1] -> Rank: 1/1 (Params: 1919)
    [Upward Pruned] 9789 supersets removed from queue.
  [FULL ] [1, 115, 82, 1] -> Rank: 1/1 (Params: 9627)
    [Upward Pruned] 17545 supersets removed from queue.
  [FULL ] [1, 60, 115, 1] -> Rank: 1/1 (Params: 7075)
    [Upward Pruned] 4145 supersets removed from queue.
  [FULL ] [1, 169, 27, 1] -> Rank: 1/1 (Params: 4759)
    [Upward Pruned] 7259 supersets removed from queue.
  [FULL ] [1, 42, 25, 1] -> Rank: 1/1 (Params: 1117)
    [Upward Pruned] 11279 supersets removed from queue.
  [FULL ] [1, 2, 27, 1] -> Rank: 1/1 (Params: 83)
    [Upward Pruned] 7329 supersets removed from queue.
  [FULL ] [1, 10, 11, 1] -> Rank: 1/1 (Params: 131)
    [Upward Pruned] 4137 supersets removed from queue.
  [FULL ] [1, 136, 10, 1] -> Rank: 1/1 (Params: 1506)
    [Upward Pruned] 164 supersets removed from queue.
  [FULL ] [1, 44, 2, 1] -> Rank: 1/1 (Params: 134)
    [Upward Pruned] 2147 supersets removed from queue.
  [FULL ] [1, 28, 3, 1] -> Rank: 1/1 (Params: 115)
    [Upward Pruned] 127 supersets removed from queue.
  [FULL ] [1, 39, 2, 1] -> Rank: 1/1 (Params: 119)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 25, 6, 1] -> Rank: 1/1 (Params: 181)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 21, 4, 1] -> Rank: 1/1 (Params: 109)
    [Upward Pruned] 33 supersets removed from queue.
  [FULL ] [1, 2, 23, 1] -> Rank: 1/1 (Params: 71)
    [Upward Pruned] 31 supersets removed from queue.
  [FULL ] [1, 5, 21, 1] -> Rank: 1/1 (Params: 131)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 14, 7, 1] -> Rank: 1/1 (Params: 119)
    [Upward Pruned] 27 supersets removed from queue.
  [FULL ] [1, 3, 19, 1] -> Rank: 1/1 (Params: 79)
    [Upward Pruned] 17 supersets removed from queue.
  [FULL ] [1, 13, 3, 1] -> Rank: 1/1 (Params: 55)
    [Upward Pruned] 42 supersets removed from queue.
  [FULL ] [1, 7, 16, 1] -> Rank: 1/1 (Params: 135)
    [Upward Pruned] 8 supersets removed from queue.
  [FULL ] [1, 2, 20, 1] -> Rank: 1/1 (Params: 62)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 19, 2, 1] -> Rank: 1/1 (Params: 59)
    [Upward Pruned] 19 supersets removed from queue.
  [FULL ] [1, 10, 8, 1] -> Rank: 1/1 (Params: 98)
    [Upward Pruned] 8 supersets removed from queue.
  [FULL ] [1, 2, 11, 1] -> Rank: 1/1 (Params: 35)
    [Upward Pruned] 55 supersets removed from queue.
  [FULL ] [1, 10, 3, 1] -> Rank: 1/1 (Params: 43)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 8, 6, 1] -> Rank: 1/1 (Params: 62)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 12, 2, 1] -> Rank: 1/1 (Params: 38)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 2, 5, 1] -> Rank: 1/1 (Params: 17)
    [Upward Pruned] 37 supersets removed from queue.
  [FULL ] [1, 2, 4, 1] -> Rank: 1/1 (Params: 14)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 9, 3, 1] -> Rank: 1/1 (Params: 39)
  [FULL ] [1, 8, 2, 1] -> Rank: 1/1 (Params: 26)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 3, 3, 1] -> Rank: 1/1 (Params: 15)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 2, 3, 1] -> Rank: 1/1 (Params: 11)
  [FULL ] [1, 5, 2, 1] -> Rank: 1/1 (Params: 17)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 2, 2, 1] -> Rank: 1/1 (Params: 8)
    [Upward Pruned] 2 supersets removed from queue.

Added 40 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_1_r7_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=8 ---
  Target Ambient Dimension: 1
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 115, 1] -> Rank: 1/1 (Params: 230)
    [Upward Pruned] 185 supersets removed from queue.
  [FULL ] [1, 13, 1] -> Rank: 1/1 (Params: 26)
    [Upward Pruned] 101 supersets removed from queue.
  [FULL ] [1, 10, 1] -> Rank: 1/1 (Params: 20)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 9, 1] -> Rank: 1/1 (Params: 18)
  [FULL ] [1, 6, 1] -> Rank: 1/1 (Params: 12)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 4, 1] -> Rank: 1/1 (Params: 8)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 3, 1] -> Rank: 1/1 (Params: 6)
  [FULL ] [1, 2, 1] -> Rank: 1/1 (Params: 4)

--- RANDOM SEARCH: h=3, exponent=8 ---
  Target Ambient Dimension: 1
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 15, 53, 1] -> Rank: 1/1 (Params: 863)
    [Upward Pruned] 70927 supersets removed from queue.
  [FULL ] [1, 202, 6, 1] -> Rank: 1/1 (Params: 1420)
    [Upward Pruned] 4652 supersets removed from queue.
  [FULL ] [1, 3, 42, 1] -> Rank: 1/1 (Params: 171)
    [Upward Pruned] 5164 supersets removed from queue.
  [FULL ] [1, 2, 80, 1] -> Rank: 1/1 (Params: 242)
    [Upward Pruned] 220 supersets removed from queue.
  [FULL ] [1, 235, 5, 1] -> Rank: 1/1 (Params: 1415)
    [Upward Pruned] 65 supersets removed from queue.
  [FULL ] [1, 24, 27, 1] -> Rank: 1/1 (Params: 699)
    [Upward Pruned] 2669 supersets removed from queue.
  [FULL ] [1, 39, 18, 1] -> Rank: 1/1 (Params: 759)
    [Upward Pruned] 1466 supersets removed from queue.
  [FULL ] [1, 189, 10, 1] -> Rank: 1/1 (Params: 2089)
    [Upward Pruned] 103 supersets removed from queue.
  [FULL ] [1, 154, 4, 1] -> Rank: 1/1 (Params: 774)
    [Upward Pruned] 699 supersets removed from queue.
  [FULL ] [1, 52, 16, 1] -> Rank: 1/1 (Params: 900)
    [Upward Pruned] 203 supersets removed from queue.
  [FULL ] [1, 42, 6, 1] -> Rank: 1/1 (Params: 300)
    [Upward Pruned] 1139 supersets removed from queue.
  [FULL ] [1, 6, 40, 1] -> Rank: 1/1 (Params: 286)
    [Upward Pruned] 35 supersets removed from queue.
  [FULL ] [1, 19, 39, 1] -> Rank: 1/1 (Params: 799)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 11, 13, 1] -> Rank: 1/1 (Params: 167)
    [Upward Pruned] 570 supersets removed from queue.
  [FULL ] [1, 64, 2, 1] -> Rank: 1/1 (Params: 194)
    [Upward Pruned] 653 supersets removed from queue.
  [FULL ] [1, 8, 18, 1] -> Rank: 1/1 (Params: 170)
    [Upward Pruned] 65 supersets removed from queue.
  [FULL ] [1, 63, 2, 1] -> Rank: 1/1 (Params: 191)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 34, 5, 1] -> Rank: 1/1 (Params: 209)
    [Upward Pruned] 84 supersets removed from queue.
  [FULL ] [1, 8, 4, 1] -> Rank: 1/1 (Params: 44)
    [Upward Pruned] 277 supersets removed from queue.
  [FULL ] [1, 6, 39, 1] -> Rank: 1/1 (Params: 279)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 30, 1] -> Rank: 1/1 (Params: 92)
    [Upward Pruned] 103 supersets removed from queue.
  [FULL ] [1, 6, 8, 1] -> Rank: 1/1 (Params: 62)
    [Upward Pruned] 43 supersets removed from queue.
  [FULL ] [1, 5, 29, 1] -> Rank: 1/1 (Params: 179)
  [FULL ] [1, 48, 2, 1] -> Rank: 1/1 (Params: 146)
    [Upward Pruned] 29 supersets removed from queue.
  [FULL ] [1, 28, 2, 1] -> Rank: 1/1 (Params: 86)
    [Upward Pruned] 39 supersets removed from queue.
  [FULL ] [1, 4, 22, 1] -> Rank: 1/1 (Params: 114)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 2, 14, 1] -> Rank: 1/1 (Params: 44)
    [Upward Pruned] 47 supersets removed from queue.
  [FULL ] [1, 15, 3, 1] -> Rank: 1/1 (Params: 63)
    [Upward Pruned] 12 supersets removed from queue.
  [FULL ] [1, 6, 7, 1] -> Rank: 1/1 (Params: 55)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 8, 1] -> Rank: 1/1 (Params: 26)
    [Upward Pruned] 23 supersets removed from queue.
  [FULL ] [1, 4, 3, 1] -> Rank: 1/1 (Params: 19)
    [Upward Pruned] 24 supersets removed from queue.
  [FULL ] [1, 9, 2, 1] -> Rank: 1/1 (Params: 29)
    [Upward Pruned] 18 supersets removed from queue.
  [FULL ] [1, 2, 3, 1] -> Rank: 1/1 (Params: 11)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 2, 2, 1] -> Rank: 1/1 (Params: 8)
    [Upward Pruned] 6 supersets removed from queue.

Added 42 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_1_r8_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=9 ---
  Target Ambient Dimension: 1
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 176, 1] -> Rank: 1/1 (Params: 352)
    [Upward Pruned] 124 supersets removed from queue.
  [FULL ] [1, 127, 1] -> Rank: 1/1 (Params: 254)
    [Upward Pruned] 48 supersets removed from queue.
  [FULL ] [1, 120, 1] -> Rank: 1/1 (Params: 240)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 2, 1] -> Rank: 1/1 (Params: 4)
    [Upward Pruned] 117 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=9 ---
  Target Ambient Dimension: 1
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 256, 204, 1] -> Rank: 1/1 (Params: 52684)
    [Upward Pruned] 4364 supersets removed from queue.
  [FULL ] [1, 215, 248, 1] -> Rank: 1/1 (Params: 53783)
    [Upward Pruned] 2172 supersets removed from queue.
  [FULL ] [1, 116, 59, 1] -> Rank: 1/1 (Params: 7019)
    [Upward Pruned] 38231 supersets removed from queue.
  [FULL ] [1, 7, 95, 1] -> Rank: 1/1 (Params: 767)
    [Upward Pruned] 22453 supersets removed from queue.
  [FULL ] [1, 111, 69, 1] -> Rank: 1/1 (Params: 7839)
    [Upward Pruned] 129 supersets removed from queue.
  [FULL ] [1, 52, 49, 1] -> Rank: 1/1 (Params: 2649)
    [Upward Pruned] 4663 supersets removed from queue.
  [FULL ] [1, 168, 34, 1] -> Rank: 1/1 (Params: 5914)
    [Upward Pruned] 1994 supersets removed from queue.
  [FULL ] [1, 203, 26, 1] -> Rank: 1/1 (Params: 5507)
    [Upward Pruned] 783 supersets removed from queue.
  [FULL ] [1, 250, 19, 1] -> Rank: 1/1 (Params: 5019)
    [Upward Pruned] 356 supersets removed from queue.
  [FULL ] [1, 125, 33, 1] -> Rank: 1/1 (Params: 4283)
    [Upward Pruned] 722 supersets removed from queue.
  [FULL ] [1, 114, 5, 1] -> Rank: 1/1 (Params: 689)
    [Upward Pruned] 4368 supersets removed from queue.
  [FULL ] [1, 66, 14, 1] -> Rank: 1/1 (Params: 1004)
    [Upward Pruned] 1679 supersets removed from queue.
  [FULL ] [1, 64, 27, 1] -> Rank: 1/1 (Params: 1819)
    [Upward Pruned] 43 supersets removed from queue.
  [FULL ] [1, 26, 77, 1] -> Rank: 1/1 (Params: 2105)
    [Upward Pruned] 467 supersets removed from queue.
  [FULL ] [1, 191, 3, 1] -> Rank: 1/1 (Params: 767)
    [Upward Pruned] 219 supersets removed from queue.
  [FULL ] [1, 34, 43, 1] -> Rank: 1/1 (Params: 1539)
    [Upward Pruned] 683 supersets removed from queue.
  [FULL ] [1, 40, 9, 1] -> Rank: 1/1 (Params: 409)
    [Upward Pruned] 1091 supersets removed from queue.
  [FULL ] [1, 95, 7, 1] -> Rank: 1/1 (Params: 767)
    [Upward Pruned] 37 supersets removed from queue.
  [FULL ] [1, 11, 49, 1] -> Rank: 1/1 (Params: 599)
    [Upward Pruned] 913 supersets removed from queue.
  [FULL ] [1, 10, 77, 1] -> Rank: 1/1 (Params: 857)
    [Upward Pruned] 17 supersets removed from queue.
  [FULL ] [1, 20, 3, 1] -> Rank: 1/1 (Params: 83)
    [Upward Pruned] 1443 supersets removed from queue.
  [FULL ] [1, 6, 6, 1] -> Rank: 1/1 (Params: 48)
    [Upward Pruned] 1019 supersets removed from queue.
  [FULL ] [1, 4, 32, 1] -> Rank: 1/1 (Params: 164)
    [Upward Pruned] 537 supersets removed from queue.
  [FULL ] [1, 183, 2, 1] -> Rank: 1/1 (Params: 551)
    [Upward Pruned] 117 supersets removed from queue.
  [FULL ] [1, 4, 3, 1] -> Rank: 1/1 (Params: 19)
    [Upward Pruned] 99 supersets removed from queue.
  [FULL ] [1, 2, 187, 1] -> Rank: 1/1 (Params: 563)
    [Upward Pruned] 227 supersets removed from queue.
  [FULL ] [1, 38, 2, 1] -> Rank: 1/1 (Params: 116)
    [Upward Pruned] 144 supersets removed from queue.
  [FULL ] [1, 3, 26, 1] -> Rank: 1/1 (Params: 107)
    [Upward Pruned] 160 supersets removed from queue.
  [FULL ] [1, 2, 100, 1] -> Rank: 1/1 (Params: 302)
    [Upward Pruned] 86 supersets removed from queue.
  [FULL ] [1, 2, 70, 1] -> Rank: 1/1 (Params: 212)
    [Upward Pruned] 29 supersets removed from queue.
  [FULL ] [1, 3, 21, 1] -> Rank: 1/1 (Params: 87)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 2, 23, 1] -> Rank: 1/1 (Params: 71)
    [Upward Pruned] 46 supersets removed from queue.
  [FULL ] [1, 3, 20, 1] -> Rank: 1/1 (Params: 83)
  [FULL ] [1, 3, 3, 1] -> Rank: 1/1 (Params: 15)
    [Upward Pruned] 16 supersets removed from queue.
  [FULL ] [1, 3, 2, 1] -> Rank: 1/1 (Params: 11)
    [Upward Pruned] 34 supersets removed from queue.
  [FULL ] [1, 2, 10, 1] -> Rank: 1/1 (Params: 32)
    [Upward Pruned] 12 supersets removed from queue.
  [FULL ] [1, 2, 5, 1] -> Rank: 1/1 (Params: 17)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 2, 4, 1] -> Rank: 1/1 (Params: 14)
  [FULL ] [1, 2, 3, 1] -> Rank: 1/1 (Params: 11)
  [FULL ] [1, 2, 2, 1] -> Rank: 1/1 (Params: 8)

Added 44 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_1_r9_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=1 ---
  Target Ambient Dimension: 2
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 266, 2] -> Rank: 2/2 (Params: 798)
    [Upward Pruned] 34 supersets removed from queue.
  [FULL ] [1, 103, 2] -> Rank: 2/2 (Params: 309)
    [Upward Pruned] 162 supersets removed from queue.
  [FULL ] [1, 88, 2] -> Rank: 2/2 (Params: 264)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 30, 2] -> Rank: 2/2 (Params: 90)
    [Upward Pruned] 57 supersets removed from queue.
  [FULL ] [1, 12, 2] -> Rank: 2/2 (Params: 36)
    [Upward Pruned] 17 supersets removed from queue.
  [FULL ] [1, 11, 2] -> Rank: 2/2 (Params: 33)
  [FULL ] [1, 10, 2] -> Rank: 2/2 (Params: 30)
  [FULL ] [1, 3, 2] -> Rank: 2/2 (Params: 9)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 2, 2] -> Rank: 2/2 (Params: 6)

--- RANDOM SEARCH: h=3, exponent=1 ---
  Target Ambient Dimension: 2
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 244, 275, 2] -> Rank: 2/2 (Params: 67894)
    [Upward Pruned] 1481 supersets removed from queue.
  [FULL ] [1, 20, 211, 2] -> Rank: 2/2 (Params: 4662)
    [Upward Pruned] 23807 supersets removed from queue.
  [FULL ] [1, 224, 161, 2] -> Rank: 2/2 (Params: 36610)
    [Upward Pruned] 3849 supersets removed from queue.
  [FULL ] [1, 75, 17, 2] -> Rank: 2/2 (Params: 1384)
    [Upward Pruned] 39993 supersets removed from queue.
  [FULL ] [1, 39, 202, 2] -> Rank: 2/2 (Params: 8321)
    [Upward Pruned] 323 supersets removed from queue.
  [FULL ] [1, 56, 176, 2] -> Rank: 2/2 (Params: 10264)
    [Upward Pruned] 493 supersets removed from queue.
  [FULL ] [1, 11, 199, 2] -> Rank: 2/2 (Params: 2598)
    [Upward Pruned] 1196 supersets removed from queue.
  [FULL ] [1, 67, 39, 2] -> Rank: 2/2 (Params: 2758)
    [Upward Pruned] 1095 supersets removed from queue.
  [FULL ] [1, 23, 77, 2] -> Rank: 2/2 (Params: 1948)
    [Upward Pruned] 5114 supersets removed from queue.
  [FULL ] [1, 4, 55, 2] -> Rank: 2/2 (Params: 334)
    [Upward Pruned] 4417 supersets removed from queue.
  [FULL ] [1, 212, 4, 2] -> Rank: 2/2 (Params: 1068)
    [Upward Pruned] 1156 supersets removed from queue.
  [FULL ] [1, 29, 50, 2] -> Rank: 2/2 (Params: 1579)
    [Upward Pruned] 189 supersets removed from queue.
  [FULL ] [1, 152, 12, 2] -> Rank: 2/2 (Params: 2000)
    [Upward Pruned] 299 supersets removed from queue.
  [FULL ] [1, 50, 23, 2] -> Rank: 2/2 (Params: 1246)
    [Upward Pruned] 586 supersets removed from queue.
  [FULL ] [1, 99, 10, 2] -> Rank: 2/2 (Params: 1109)
    [Upward Pruned] 490 supersets removed from queue.
  [FULL ] [1, 98, 13, 2] -> Rank: 2/2 (Params: 1398)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 28, 18, 2] -> Rank: 2/2 (Params: 568)
    [Upward Pruned] 833 supersets removed from queue.
  [FULL ] [1, 189, 4, 2] -> Rank: 2/2 (Params: 953)
    [Upward Pruned] 137 supersets removed from queue.
  [FULL ] [1, 45, 6, 2] -> Rank: 2/2 (Params: 327)
    [Upward Pruned] 979 supersets removed from queue.
  [FULL ] [1, 26, 21, 2] -> Rank: 2/2 (Params: 614)
    [Upward Pruned] 67 supersets removed from queue.
  [FULL ] [1, 6, 46, 2] -> Rank: 2/2 (Params: 374)
    [Upward Pruned] 179 supersets removed from queue.
  [FULL ] [1, 25, 20, 2] -> Rank: 2/2 (Params: 565)
    [Upward Pruned] 27 supersets removed from queue.
  [FULL ] [1, 26, 11, 2] -> Rank: 2/2 (Params: 334)
    [Upward Pruned] 136 supersets removed from queue.
  [FULL ] [1, 83, 3, 2] -> Rank: 2/2 (Params: 338)
    [Upward Pruned] 429 supersets removed from queue.
  [FULL ] [1, 32, 4, 2] -> Rank: 2/2 (Params: 168)
    [Upward Pruned] 166 supersets removed from queue.
  [FULL ] [1, 21, 32, 2] -> Rank: 2/2 (Params: 757)
    [Upward Pruned] 55 supersets removed from queue.
  [FULL ] [1, 6, 6, 2] -> Rank: 2/2 (Params: 54)
    [Upward Pruned] 747 supersets removed from queue.
  [FULL ] [1, 2, 11, 2] -> Rank: 2/2 (Params: 46)
    [Upward Pruned] 667 supersets removed from queue.
  [FULL ] [1, 5, 10, 2] -> Rank: 2/2 (Params: 75)
  [FULL ] [1, 239, 2, 2] -> Rank: 2/2 (Params: 721)
    [Upward Pruned] 61 supersets removed from queue.
  [FULL ] [1, 79, 3, 2] -> Rank: 2/2 (Params: 322)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 168, 2, 2] -> Rank: 2/2 (Params: 508)
    [Upward Pruned] 70 supersets removed from queue.
  [FULL ] [1, 31, 3, 2] -> Rank: 2/2 (Params: 130)
    [Upward Pruned] 49 supersets removed from queue.
  [FULL ] [1, 47, 2, 2] -> Rank: 2/2 (Params: 145)
    [Upward Pruned] 120 supersets removed from queue.
  [FULL ] [1, 24, 2, 2] -> Rank: 2/2 (Params: 76)
    [Upward Pruned] 43 supersets removed from queue.
  [FULL ] [1, 5, 3, 2] -> Rank: 2/2 (Params: 26)
    [Upward Pruned] 60 supersets removed from queue.
  [FULL ] [1, 3, 3, 2] -> Rank: 2/2 (Params: 18)
    [Upward Pruned] 15 supersets removed from queue.
  [FULL ] [1, 2, 7, 2] -> Rank: 2/2 (Params: 30)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 7, 2, 2] -> Rank: 2/2 (Params: 25)
    [Upward Pruned] 16 supersets removed from queue.
  [FULL ] [1, 6, 2, 2] -> Rank: 2/2 (Params: 22)
  [FULL ] [1, 2, 4, 2] -> Rank: 2/2 (Params: 18)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 3, 2, 2] -> Rank: 2/2 (Params: 13)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 2, 2, 2] -> Rank: 2/2 (Params: 10)
    [Upward Pruned] 1 supersets removed from queue.

Added 52 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_2_r1_architectures.csv'.

Loading existing database from '../data/raw/1_2_r2_architectures.csv'...

--- RANDOM SEARCH: h=2, exponent=2 ---
  Target Ambient Dimension: 2
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 289 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.

--- RANDOM SEARCH: h=3, exponent=2 ---
  Target Ambient Dimension: 2
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 89357 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_2_r2_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=3 ---
  Target Ambient Dimension: 2
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 81, 2] -> Rank: 2/2 (Params: 243)
    [Upward Pruned] 219 supersets removed from queue.
  [FULL ] [1, 26, 2] -> Rank: 2/2 (Params: 78)
    [Upward Pruned] 54 supersets removed from queue.
  [FULL ] [1, 15, 2] -> Rank: 2/2 (Params: 45)
    [Upward Pruned] 10 supersets removed from queue.
  [FULL ] [1, 12, 2] -> Rank: 2/2 (Params: 36)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 11, 2] -> Rank: 2/2 (Params: 33)
  [FULL ] [1, 9, 2] -> Rank: 2/2 (Params: 27)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 8, 2] -> Rank: 2/2 (Params: 24)
  [FULL ] [1, 2, 2] -> Rank: 2/2 (Params: 6)
    [Upward Pruned] 5 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=3 ---
  Target Ambient Dimension: 2
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 295, 7, 2] -> Rank: 2/2 (Params: 2374)
    [Upward Pruned] 1763 supersets removed from queue.
  [FULL ] [1, 210, 53, 2] -> Rank: 2/2 (Params: 11446)
    [Upward Pruned] 21079 supersets removed from queue.
  [FULL ] [1, 115, 16, 2] -> Rank: 2/2 (Params: 1987)
    [Upward Pruned] 30219 supersets removed from queue.
  [FULL ] [1, 79, 107, 2] -> Rank: 2/2 (Params: 8746)
    [Upward Pruned] 6983 supersets removed from queue.
  [FULL ] [1, 64, 101, 2] -> Rank: 2/2 (Params: 6730)
    [Upward Pruned] 3215 supersets removed from queue.
  [FULL ] [1, 71, 19, 2] -> Rank: 2/2 (Params: 1458)
    [Upward Pruned] 3607 supersets removed from queue.
  [FULL ] [1, 63, 12, 2] -> Rank: 2/2 (Params: 843)
    [Upward Pruned] 1939 supersets removed from queue.
  [FULL ] [1, 6, 242, 2] -> Rank: 2/2 (Params: 1942)
    [Upward Pruned] 3362 supersets removed from queue.
  [FULL ] [1, 56, 74, 2] -> Rank: 2/2 (Params: 4348)
    [Upward Pruned] 1175 supersets removed from queue.
  [FULL ] [1, 18, 143, 2] -> Rank: 2/2 (Params: 2878)
    [Upward Pruned] 3761 supersets removed from queue.
  [FULL ] [1, 5, 88, 2] -> Rank: 2/2 (Params: 621)
    [Upward Pruned] 4150 supersets removed from queue.
  [FULL ] [1, 12, 43, 2] -> Rank: 2/2 (Params: 614)
    [Upward Pruned] 2196 supersets removed from queue.
  [FULL ] [1, 2, 75, 2] -> Rank: 2/2 (Params: 302)
    [Upward Pruned] 768 supersets removed from queue.
  [FULL ] [1, 35, 27, 2] -> Rank: 2/2 (Params: 1034)
    [Upward Pruned] 447 supersets removed from queue.
  [FULL ] [1, 8, 40, 2] -> Rank: 2/2 (Params: 408)
    [Upward Pruned] 208 supersets removed from queue.
  [FULL ] [1, 33, 18, 2] -> Rank: 2/2 (Params: 663)
    [Upward Pruned] 295 supersets removed from queue.
  [FULL ] [1, 67, 8, 2] -> Rank: 2/2 (Params: 619)
    [Upward Pruned] 911 supersets removed from queue.
  [FULL ] [1, 62, 7, 2] -> Rank: 2/2 (Params: 510)
    [Upward Pruned] 258 supersets removed from queue.
  [FULL ] [1, 296, 2, 2] -> Rank: 2/2 (Params: 892)
    [Upward Pruned] 24 supersets removed from queue.
  [FULL ] [1, 22, 24, 2] -> Rank: 2/2 (Params: 598)
    [Upward Pruned] 175 supersets removed from queue.
  [FULL ] [1, 13, 9, 2] -> Rank: 2/2 (Params: 148)
    [Upward Pruned] 704 supersets removed from queue.
  [FULL ] [1, 83, 6, 2] -> Rank: 2/2 (Params: 593)
    [Upward Pruned] 212 supersets removed from queue.
  [FULL ] [1, 5, 26, 2] -> Rank: 2/2 (Params: 187)
    [Upward Pruned] 216 supersets removed from queue.
  [FULL ] [1, 51, 2, 2] -> Rank: 2/2 (Params: 157)
    [Upward Pruned] 1033 supersets removed from queue.
  [FULL ] [1, 24, 4, 2] -> Rank: 2/2 (Params: 128)
    [Upward Pruned] 134 supersets removed from queue.
  [FULL ] [1, 9, 18, 2] -> Rank: 2/2 (Params: 207)
    [Upward Pruned] 31 supersets removed from queue.
  [FULL ] [1, 4, 20, 2] -> Rank: 2/2 (Params: 124)
    [Upward Pruned] 78 supersets removed from queue.
  [FULL ] [1, 22, 6, 2] -> Rank: 2/2 (Params: 166)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 3, 6, 2] -> Rank: 2/2 (Params: 33)
    [Upward Pruned] 213 supersets removed from queue.
  [FULL ] [1, 16, 5, 2] -> Rank: 2/2 (Params: 106)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 30, 2, 2] -> Rank: 2/2 (Params: 94)
    [Upward Pruned] 41 supersets removed from queue.
  [FULL ] [1, 4, 3, 2] -> Rank: 2/2 (Params: 22)
    [Upward Pruned] 57 supersets removed from queue.
  [FULL ] [1, 12, 2, 2] -> Rank: 2/2 (Params: 40)
    [Upward Pruned] 17 supersets removed from queue.
  [FULL ] [1, 5, 2, 2] -> Rank: 2/2 (Params: 19)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 2, 12, 2] -> Rank: 2/2 (Params: 50)
    [Upward Pruned] 62 supersets removed from queue.
  [FULL ] [1, 2, 4, 2] -> Rank: 2/2 (Params: 18)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 2, 3, 2] -> Rank: 2/2 (Params: 14)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 3, 2, 2] -> Rank: 2/2 (Params: 13)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 2, 2] -> Rank: 2/2 (Params: 10)

Added 47 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_2_r3_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=4 ---
  Target Ambient Dimension: 2
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 228, 2] -> Rank: 2/2 (Params: 684)
    [Upward Pruned] 72 supersets removed from queue.
  [FULL ] [1, 173, 2] -> Rank: 2/2 (Params: 519)
    [Upward Pruned] 54 supersets removed from queue.
  [FULL ] [1, 140, 2] -> Rank: 2/2 (Params: 420)
    [Upward Pruned] 32 supersets removed from queue.

  [FULL ] [1, 33, 2] -> Rank: 2/2 (Params: 99)
    [Upward Pruned] 106 supersets removed from queue.
  [FULL ] [1, 17, 2] -> Rank: 2/2 (Params: 51)
    [Upward Pruned] 15 supersets removed from queue.
  [FULL ] [1, 13, 2] -> Rank: 2/2 (Params: 39)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 3, 2] -> Rank: 2/2 (Params: 9)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 2, 2] -> Rank: 2/2 (Params: 6)

--- RANDOM SEARCH: h=3, exponent=4 ---
  Target Ambient Dimension: 2
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 268, 116, 2] -> Rank: 2/2 (Params: 31588)
    [Upward Pruned] 6104 supersets removed from queue.
  [FULL ] [1, 218, 170, 2] -> Rank: 2/2 (Params: 37618)
    [Upward Pruned] 6549 supersets removed from queue.
  [FULL ] [1, 174, 29, 2] -> Rank: 2/2 (Params: 5278)
    [Upward Pruned] 21888 supersets removed from queue.
  [FULL ] [1, 126, 291, 2] -> Rank: 2/2 (Params: 37374)
    [Upward Pruned] 479 supersets removed from queue.
  [FULL ] [1, 162, 216, 2] -> Rank: 2/2 (Params: 35586)
    [Upward Pruned] 899 supersets removed from queue.
  [FULL ] [1, 105, 233, 2] -> Rank: 2/2 (Params: 25036)
    [Upward Pruned] 3515 supersets removed from queue.
  [FULL ] [1, 80, 279, 2] -> Rank: 2/2 (Params: 22958)
    [Upward Pruned] 549 supersets removed from queue.
  [FULL ] [1, 122, 176, 2] -> Rank: 2/2 (Params: 21946)
    [Upward Pruned] 2759 supersets removed from queue.
  [FULL ] [1, 142, 88, 2] -> Rank: 2/2 (Params: 12814)
    [Upward Pruned] 2815 supersets removed from queue.
  [FULL ] [1, 32, 97, 2] -> Rank: 2/2 (Params: 3330)
    [Upward Pruned] 18233 supersets removed from queue.
  [FULL ] [1, 83, 4, 2] -> Rank: 2/2 (Params: 423)
    [Upward Pruned] 11349 supersets removed from queue.
  [FULL ] [1, 50, 37, 2] -> Rank: 2/2 (Params: 1974)
    [Upward Pruned] 1979 supersets removed from queue.
  [FULL ] [1, 293, 3, 2] -> Rank: 2/2 (Params: 1178)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 4, 108, 2] -> Rank: 2/2 (Params: 652)
    [Upward Pruned] 5403 supersets removed from queue.
  [FULL ] [1, 67, 34, 2] -> Rank: 2/2 (Params: 2413)
    [Upward Pruned] 47 supersets removed from queue.
  [FULL ] [1, 43, 2, 2] -> Rank: 2/2 (Params: 133)
    [Upward Pruned] 2199 supersets removed from queue.
  [FULL ] [1, 28, 16, 2] -> Rank: 2/2 (Params: 508)
    [Upward Pruned] 1258 supersets removed from queue.
  [FULL ] [1, 20, 27, 2] -> Rank: 2/2 (Params: 614)
    [Upward Pruned] 647 supersets removed from queue.
  [FULL ] [1, 12, 66, 2] -> Rank: 2/2 (Params: 936)
    [Upward Pruned] 335 supersets removed from queue.
  [FULL ] [1, 7, 71, 2] -> Rank: 2/2 (Params: 646)
    [Upward Pruned] 184 supersets removed from queue.
  [FULL ] [1, 6, 96, 2] -> Rank: 2/2 (Params: 774)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 2, 7, 2] -> Rank: 2/2 (Params: 30)
    [Upward Pruned] 1965 supersets removed from queue.
  [FULL ] [1, 5, 5, 2] -> Rank: 2/2 (Params: 40)
    [Upward Pruned] 75 supersets removed from queue.
  [FULL ] [1, 40, 3, 2] -> Rank: 2/2 (Params: 166)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 36, 3, 2] -> Rank: 2/2 (Params: 150)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 14, 4, 2] -> Rank: 2/2 (Params: 78)
    [Upward Pruned] 21 supersets removed from queue.
  [FULL ] [1, 14, 2, 2] -> Rank: 2/2 (Params: 46)
    [Upward Pruned] 50 supersets removed from queue.
  [FULL ] [1, 8, 3, 2] -> Rank: 2/2 (Params: 38)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 2, 6, 2] -> Rank: 2/2 (Params: 26)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 3, 2, 2] -> Rank: 2/2 (Params: 13)
    [Upward Pruned] 22 supersets removed from queue.
  [FULL ] [1, 2, 4, 2] -> Rank: 2/2 (Params: 18)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 3, 2] -> Rank: 2/2 (Params: 14)
  [FULL ] [1, 2, 2, 2] -> Rank: 2/2 (Params: 10)

Added 41 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_2_r4_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=5 ---
  Target Ambient Dimension: 2
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 145, 2] -> Rank: 2/2 (Params: 435)
    [Upward Pruned] 155 supersets removed from queue.
  [FULL ] [1, 100, 2] -> Rank: 2/2 (Params: 300)
    [Upward Pruned] 44 supersets removed from queue.

  [FULL ] [1, 49, 2] -> Rank: 2/2 (Params: 147)
    [Upward Pruned] 50 supersets removed from queue.
  [FULL ] [1, 32, 2] -> Rank: 2/2 (Params: 96)
    [Upward Pruned] 16 supersets removed from queue.
  [FULL ] [1, 20, 2] -> Rank: 2/2 (Params: 60)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 5, 2] -> Rank: 2/2 (Params: 15)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 3, 2] -> Rank: 2/2 (Params: 9)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 2] -> Rank: 2/2 (Params: 6)

--- RANDOM SEARCH: h=3, exponent=5 ---
  Target Ambient Dimension: 2
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 257, 250, 2] -> Rank: 2/2 (Params: 65007)
    [Upward Pruned] 2243 supersets removed from queue.
  [FULL ] [1, 11, 2, 2] -> Rank: 2/2 (Params: 37)
    [Upward Pruned] 84465 supersets removed from queue.
  [FULL ] [1, 10, 23, 2] -> Rank: 2/2 (Params: 286)
    [Upward Pruned] 277 supersets removed from queue.
  [FULL ] [1, 6, 89, 2] -> Rank: 2/2 (Params: 718)
    [Upward Pruned] 847 supersets removed from queue.
  [FULL ] [1, 6, 65, 2] -> Rank: 2/2 (Params: 526)
    [Upward Pruned] 95 supersets removed from queue.
  [FULL ] [1, 4, 246, 2] -> Rank: 2/2 (Params: 1480)
    [Upward Pruned] 109 supersets removed from queue.
  [FULL ] [1, 3, 76, 2] -> Rank: 2/2 (Params: 383)
    [Upward Pruned] 564 supersets removed from queue.
  [FULL ] [1, 2, 4, 2] -> Rank: 2/2 (Params: 18)
    [Upward Pruned] 775 supersets removed from queue.
  [FULL ] [1, 10, 2, 2] -> Rank: 2/2 (Params: 34)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 3, 2] -> Rank: 2/2 (Params: 14)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 8, 2, 2] -> Rank: 2/2 (Params: 28)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 4, 2, 2] -> Rank: 2/2 (Params: 16)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 2, 2, 2] -> Rank: 2/2 (Params: 10)
    [Upward Pruned] 1 supersets removed from queue.

Added 21 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_2_r5_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=6 ---
  Target Ambient Dimension: 2
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 263, 2] -> Rank: 2/2 (Params: 789)
    [Upward Pruned] 37 supersets removed from queue.

  [FULL ] [1, 10, 2] -> Rank: 2/2 (Params: 30)
    [Upward Pruned] 252 supersets removed from queue.
  [FULL ] [1, 4, 2] -> Rank: 2/2 (Params: 12)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 2, 2] -> Rank: 2/2 (Params: 6)
    [Upward Pruned] 1 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=6 ---
  Target Ambient Dimension: 2
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 187, 64, 2] -> Rank: 2/2 (Params: 12283)
    [Upward Pruned] 27017 supersets removed from queue.
  [FULL ] [1, 160, 50, 2] -> Rank: 2/2 (Params: 8260)
    [Upward Pruned] 8372 supersets removed from queue.
  [FULL ] [1, 29, 160, 2] -> Rank: 2/2 (Params: 4989)
    [Upward Pruned] 18470 supersets removed from queue.
  [FULL ] [1, 52, 9, 2] -> Rank: 2/2 (Params: 538)
    [Upward Pruned] 22088 supersets removed from queue.
  [FULL ] [1, 42, 78, 2] -> Rank: 2/2 (Params: 3474)
    [Upward Pruned] 819 supersets removed from queue.
  [FULL ] [1, 24, 51, 2] -> Rank: 2/2 (Params: 1350)
    [Upward Pruned] 2936 supersets removed from queue.
  [FULL ] [1, 15, 285, 2] -> Rank: 2/2 (Params: 4860)
    [Upward Pruned] 143 supersets removed from queue.
  [FULL ] [1, 212, 4, 2] -> Rank: 2/2 (Params: 1068)
    [Upward Pruned] 444 supersets removed from queue.
  [FULL ] [1, 18, 10, 2] -> Rank: 2/2 (Params: 218)
    [Upward Pruned] 2797 supersets removed from queue.
  [FULL ] [1, 2, 62, 2] -> Rank: 2/2 (Params: 250)
    [Upward Pruned] 3775 supersets removed from queue.
  [FULL ] [1, 17, 42, 2] -> Rank: 2/2 (Params: 815)
    [Upward Pruned] 19 supersets removed from queue.
  [FULL ] [1, 7, 51, 2] -> Rank: 2/2 (Params: 466)
    [Upward Pruned] 109 supersets removed from queue.
  [FULL ] [1, 2, 8, 2] -> Rank: 2/2 (Params: 34)
    [Upward Pruned] 961 supersets removed from queue.
  [FULL ] [1, 167, 5, 2] -> Rank: 2/2 (Params: 1012)
    [Upward Pruned] 134 supersets removed from queue.
  [FULL ] [1, 118, 4, 2] -> Rank: 2/2 (Params: 598)
    [Upward Pruned] 240 supersets removed from queue.
  [FULL ] [1, 240, 2, 2] -> Rank: 2/2 (Params: 724)
    [Upward Pruned] 121 supersets removed from queue.
  [FULL ] [1, 22, 5, 2] -> Rank: 2/2 (Params: 142)
    [Upward Pruned] 287 supersets removed from queue.
  [FULL ] [1, 72, 4, 2] -> Rank: 2/2 (Params: 368)
    [Upward Pruned] 45 supersets removed from queue.
  [FULL ] [1, 209, 2, 2] -> Rank: 2/2 (Params: 631)
    [Upward Pruned] 61 supersets removed from queue.
  [FULL ] [1, 90, 3, 2] -> Rank: 2/2 (Params: 366)
    [Upward Pruned] 118 supersets removed from queue.
  [FULL ] [1, 9, 3, 2] -> Rank: 2/2 (Params: 42)
    [Upward Pruned] 182 supersets removed from queue.
  [FULL ] [1, 31, 2, 2] -> Rank: 2/2 (Params: 97)
    [Upward Pruned] 177 supersets removed from queue.
  [FULL ] [1, 7, 7, 2] -> Rank: 2/2 (Params: 70)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 8, 2, 2] -> Rank: 2/2 (Params: 28)
    [Upward Pruned] 26 supersets removed from queue.
  [FULL ] [1, 2, 6, 2] -> Rank: 2/2 (Params: 26)
    [Upward Pruned] 10 supersets removed from queue.
  [FULL ] [1, 3, 3, 2] -> Rank: 2/2 (Params: 18)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 2, 4, 2] -> Rank: 2/2 (Params: 18)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 4, 2, 2] -> Rank: 2/2 (Params: 16)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 3, 2, 2] -> Rank: 2/2 (Params: 13)
  [FULL ] [1, 2, 2, 2] -> Rank: 2/2 (Params: 10)
    [Upward Pruned] 1 supersets removed from queue.

Added 34 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_2_r6_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=7 ---
  Target Ambient Dimension: 2
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 187, 2] -> Rank: 2/2 (Params: 561)
    [Upward Pruned] 113 supersets removed from queue.
  [FULL ] [1, 70, 2] -> Rank: 2/2 (Params: 210)
    [Upward Pruned] 116 supersets removed from queue.
  [FULL ] [1, 67, 2] -> Rank: 2/2 (Params: 201)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 8, 2] -> Rank: 2/2 (Params: 24)
    [Upward Pruned] 58 supersets removed from queue.
  [FULL ] [1, 4, 2] -> Rank: 2/2 (Params: 12)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 3, 2] -> Rank: 2/2 (Params: 9)
  [FULL ] [1, 2, 2] -> Rank: 2/2 (Params: 6)

--- RANDOM SEARCH: h=3, exponent=7 ---
  Target Ambient Dimension: 2
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 294, 61, 2] -> Rank: 2/2 (Params: 18350)
    [Upward Pruned] 1679 supersets removed from queue.
  [FULL ] [1, 278, 24, 2] -> Rank: 2/2 (Params: 6998)
    [Upward Pruned] 4690 supersets removed from queue.
  [FULL ] [1, 113, 159, 2] -> Rank: 2/2 (Params: 18398)
    [Upward Pruned] 23429 supersets removed from queue.
  [FULL ] [1, 244, 63, 2] -> Rank: 2/2 (Params: 15742)
    [Upward Pruned] 3263 supersets removed from queue.
  [FULL ] [1, 223, 97, 2] -> Rank: 2/2 (Params: 22048)
    [Upward Pruned] 1301 supersets removed from queue.
  [FULL ] [1, 170, 12, 2] -> Rank: 2/2 (Params: 2234)
    [Upward Pruned] 11585 supersets removed from queue.
  [FULL ] [1, 21, 26, 2] -> Rank: 2/2 (Params: 619)
    [Upward Pruned] 32880 supersets removed from queue.
  [FULL ] [1, 5, 177, 2] -> Rank: 2/2 (Params: 1244)
    [Upward Pruned] 1983 supersets removed from queue.
  [FULL ] [1, 93, 2, 2] -> Rank: 2/2 (Params: 283)
    [Upward Pruned] 3157 supersets removed from queue.
  [FULL ] [1, 60, 17, 2] -> Rank: 2/2 (Params: 1114)
    [Upward Pruned] 296 supersets removed from queue.
  [FULL ] [1, 10, 30, 2] -> Rank: 2/2 (Params: 370)
    [Upward Pruned] 1616 supersets removed from queue.
  [FULL ] [1, 2, 275, 2] -> Rank: 2/2 (Params: 1102)
    [Upward Pruned] 77 supersets removed from queue.
  [FULL ] [1, 54, 12, 2] -> Rank: 2/2 (Params: 726)
    [Upward Pruned] 248 supersets removed from queue.
  [FULL ] [1, 3, 240, 2] -> Rank: 2/2 (Params: 1203)
    [Upward Pruned] 69 supersets removed from queue.
  [FULL ] [1, 37, 13, 2] -> Rank: 2/2 (Params: 544)
    [Upward Pruned] 220 supersets removed from queue.
  [FULL ] [1, 48, 7, 2] -> Rank: 2/2 (Params: 398)
    [Upward Pruned] 230 supersets removed from queue.
  [FULL ] [1, 10, 3, 2] -> Rank: 2/2 (Params: 46)
    [Upward Pruned] 954 supersets removed from queue.
  [FULL ] [1, 2, 162, 2] -> Rank: 2/2 (Params: 650)
    [Upward Pruned] 343 supersets removed from queue.
  [FULL ] [1, 6, 112, 2] -> Rank: 2/2 (Params: 902)
    [Upward Pruned] 199 supersets removed from queue.
  [FULL ] [1, 9, 5, 2] -> Rank: 2/2 (Params: 64)
    [Upward Pruned] 106 supersets removed from queue.
  [FULL ] [1, 5, 52, 2] -> Rank: 2/2 (Params: 369)
    [Upward Pruned] 289 supersets removed from queue.
  [FULL ] [1, 4, 97, 2] -> Rank: 2/2 (Params: 586)
    [Upward Pruned] 64 supersets removed from queue.
  [FULL ] [1, 7, 46, 2] -> Rank: 2/2 (Params: 421)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 8, 32, 2] -> Rank: 2/2 (Params: 328)
    [Upward Pruned] 13 supersets removed from queue.
  [FULL ] [1, 4, 38, 2] -> Rank: 2/2 (Params: 232)
    [Upward Pruned] 94 supersets removed from queue.
  [FULL ] [1, 3, 75, 2] -> Rank: 2/2 (Params: 378)
    [Upward Pruned] 86 supersets removed from queue.
  [FULL ] [1, 3, 63, 2] -> Rank: 2/2 (Params: 318)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 4, 31, 2] -> Rank: 2/2 (Params: 190)
    [Upward Pruned] 28 supersets removed from queue.
  [FULL ] [1, 8, 10, 2] -> Rank: 2/2 (Params: 108)
    [Upward Pruned] 20 supersets removed from queue.
  [FULL ] [1, 36, 2, 2] -> Rank: 2/2 (Params: 112)
    [Upward Pruned] 56 supersets removed from queue.
  [FULL ] [1, 3, 53, 2] -> Rank: 2/2 (Params: 268)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 2, 57, 2] -> Rank: 2/2 (Params: 230)
    [Upward Pruned] 104 supersets removed from queue.
  [FULL ] [1, 5, 3, 2] -> Rank: 2/2 (Params: 26)
    [Upward Pruned] 92 supersets removed from queue.
  [FULL ] [1, 11, 2, 2] -> Rank: 2/2 (Params: 37)
    [Upward Pruned] 24 supersets removed from queue.
  [FULL ] [1, 3, 45, 2] -> Rank: 2/2 (Params: 228)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 4, 19, 2] -> Rank: 2/2 (Params: 118)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 4, 10, 2] -> Rank: 2/2 (Params: 64)
    [Upward Pruned] 8 supersets removed from queue.
  [FULL ] [1, 3, 27, 2] -> Rank: 2/2 (Params: 138)
    [Upward Pruned] 17 supersets removed from queue.
  [FULL ] [1, 3, 10, 2] -> Rank: 2/2 (Params: 53)
    [Upward Pruned] 16 supersets removed from queue.
  [FULL ] [1, 2, 27, 2] -> Rank: 2/2 (Params: 110)
    [Upward Pruned] 29 supersets removed from queue.
  [FULL ] [1, 2, 20, 2] -> Rank: 2/2 (Params: 82)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 9, 2, 2] -> Rank: 2/2 (Params: 31)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 3, 2, 2] -> Rank: 2/2 (Params: 13)
    [Upward Pruned] 19 supersets removed from queue.
  [FULL ] [1, 2, 18, 2] -> Rank: 2/2 (Params: 74)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 17, 2] -> Rank: 2/2 (Params: 70)
  [FULL ] [1, 2, 11, 2] -> Rank: 2/2 (Params: 46)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 2, 6, 2] -> Rank: 2/2 (Params: 26)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 2, 4, 2] -> Rank: 2/2 (Params: 18)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 3, 2] -> Rank: 2/2 (Params: 14)
  [FULL ] [1, 2, 2, 2] -> Rank: 2/2 (Params: 10)

Added 57 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_2_r7_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=8 ---
  Target Ambient Dimension: 2
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 132, 2] -> Rank: 2/2 (Params: 396)
    [Upward Pruned] 168 supersets removed from queue.
  [FULL ] [1, 129, 2] -> Rank: 2/2 (Params: 387)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 87, 2] -> Rank: 2/2 (Params: 261)
    [Upward Pruned] 41 supersets removed from queue.
  [FULL ] [1, 12, 2] -> Rank: 2/2 (Params: 36)
    [Upward Pruned] 74 supersets removed from queue.
  [FULL ] [1, 2, 2] -> Rank: 2/2 (Params: 6)
    [Upward Pruned] 9 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=8 ---
  Target Ambient Dimension: 2
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 137, 257, 2] -> Rank: 2/2 (Params: 35860)
    [Upward Pruned] 7215 supersets removed from queue.
  [FULL ] [1, 57, 197, 2] -> Rank: 2/2 (Params: 11680)
    [Upward Pruned] 18159 supersets removed from queue.
  [FULL ] [1, 150, 169, 2] -> Rank: 2/2 (Params: 25838)
    [Upward Pruned] 4227 supersets removed from queue.
  [FULL ] [1, 68, 134, 2] -> Rank: 2/2 (Params: 9448)
    [Upward Pruned] 10450 supersets removed from queue.
  [FULL ] [1, 13, 157, 2] -> Rank: 2/2 (Params: 2368)
    [Upward Pruned] 6775 supersets removed from queue.
  [FULL ] [1, 219, 60, 2] -> Rank: 2/2 (Params: 13479)
    [Upward Pruned] 6067 supersets removed from queue.
  [FULL ] [1, 10, 204, 2] -> Rank: 2/2 (Params: 2458)
    [Upward Pruned] 290 supersets removed from queue.
  [FULL ] [1, 29, 29, 2] -> Rank: 2/2 (Params: 928)
    [Upward Pruned] 23388 supersets removed from queue.
  [FULL ] [1, 7, 74, 2] -> Rank: 2/2 (Params: 673)
    [Upward Pruned] 2398 supersets removed from queue.
  [FULL ] [1, 4, 65, 2] -> Rank: 2/2 (Params: 394)
    [Upward Pruned] 905 supersets removed from queue.
  [FULL ] [1, 277, 27, 2] -> Rank: 2/2 (Params: 7810)
    [Upward Pruned] 47 supersets removed from queue.
  [FULL ] [1, 132, 7, 2] -> Rank: 2/2 (Params: 1070)
    [Upward Pruned] 3669 supersets removed from queue.
  [FULL ] [1, 83, 27, 2] -> Rank: 2/2 (Params: 2378)
    [Upward Pruned] 97 supersets removed from queue.
  [FULL ] [1, 61, 25, 2] -> Rank: 2/2 (Params: 1636)
    [Upward Pruned] 185 supersets removed from queue.
  [FULL ] [1, 222, 4, 2] -> Rank: 2/2 (Params: 1118)
    [Upward Pruned] 236 supersets removed from queue.
  [FULL ] [1, 6, 15, 2] -> Rank: 2/2 (Params: 126)
    [Upward Pruned] 2307 supersets removed from queue.
  [FULL ] [1, 123, 5, 2] -> Rank: 2/2 (Params: 748)
    [Upward Pruned] 269 supersets removed from queue.
  [FULL ] [1, 3, 158, 2] -> Rank: 2/2 (Params: 793)
    [Upward Pruned] 142 supersets removed from queue.
  [FULL ] [1, 248, 2, 2] -> Rank: 2/2 (Params: 748)
    [Upward Pruned] 105 supersets removed from queue.
  [FULL ] [1, 57, 8, 2] -> Rank: 2/2 (Params: 529)
    [Upward Pruned] 461 supersets removed from queue.
  [FULL ] [1, 2, 286, 2] -> Rank: 2/2 (Params: 1146)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 2, 47, 2] -> Rank: 2/2 (Params: 190)
    [Upward Pruned] 385 supersets removed from queue.
  [FULL ] [1, 9, 3, 2] -> Rank: 2/2 (Params: 42)
    [Upward Pruned] 1129 supersets removed from queue.
  [FULL ] [1, 6, 8, 2] -> Rank: 2/2 (Params: 70)
    [Upward Pruned] 20 supersets removed from queue.
  [FULL ] [1, 7, 5, 2] -> Rank: 2/2 (Params: 52)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 5, 14, 2] -> Rank: 2/2 (Params: 103)
    [Upward Pruned] 32 supersets removed from queue.
  [FULL ] [1, 3, 34, 2] -> Rank: 2/2 (Params: 173)
    [Upward Pruned] 25 supersets removed from queue.
  [FULL ] [1, 49, 2, 2] -> Rank: 2/2 (Params: 151)
    [Upward Pruned] 198 supersets removed from queue.
  [FULL ] [1, 3, 17, 2] -> Rank: 2/2 (Params: 88)
    [Upward Pruned] 33 supersets removed from queue.
  [FULL ] [1, 6, 2, 2] -> Rank: 2/2 (Params: 22)
    [Upward Pruned] 51 supersets removed from queue.
  [FULL ] [1, 4, 8, 2] -> Rank: 2/2 (Params: 52)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 2, 35, 2] -> Rank: 2/2 (Params: 142)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 2, 6, 2] -> Rank: 2/2 (Params: 26)
    [Upward Pruned] 43 supersets removed from queue.
  [FULL ] [1, 2, 4, 2] -> Rank: 2/2 (Params: 18)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 2, 2, 2] -> Rank: 2/2 (Params: 10)
    [Upward Pruned] 7 supersets removed from queue.

Added 40 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_2_r8_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=9 ---
  Target Ambient Dimension: 2
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 35, 2] -> Rank: 2/2 (Params: 105)
    [Upward Pruned] 265 supersets removed from queue.
  [FULL ] [1, 17, 2] -> Rank: 2/2 (Params: 51)
    [Upward Pruned] 17 supersets removed from queue.
  [FULL ] [1, 5, 2] -> Rank: 2/2 (Params: 15)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 4, 2] -> Rank: 2/2 (Params: 12)
  [FULL ] [1, 3, 2] -> Rank: 2/2 (Params: 9)
  [FULL ] [1, 2, 2] -> Rank: 2/2 (Params: 6)

--- RANDOM SEARCH: h=3, exponent=9 ---
  Target Ambient Dimension: 2
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 113, 156, 2] -> Rank: 2/2 (Params: 18053)
    [Upward Pruned] 27259 supersets removed from queue.
  [FULL ] [1, 33, 85, 2] -> Rank: 2/2 (Params: 3008)
    [Upward Pruned] 30627 supersets removed from queue.
  [FULL ] [1, 10, 119, 2] -> Rank: 2/2 (Params: 1438)
    [Upward Pruned] 4185 supersets removed from queue.
  [FULL ] [1, 142, 2, 2] -> Rank: 2/2 (Params: 430)
    [Upward Pruned] 13196 supersets removed from queue.
  [FULL ] [1, 6, 222, 2] -> Rank: 2/2 (Params: 1782)
    [Upward Pruned] 315 supersets removed from queue.
  [FULL ] [1, 79, 60, 2] -> Rank: 2/2 (Params: 4939)
    [Upward Pruned] 1574 supersets removed from queue.
  [FULL ] [1, 136, 19, 2] -> Rank: 2/2 (Params: 2758)
    [Upward Pruned] 245 supersets removed from queue.
  [FULL ] [1, 29, 37, 2] -> Rank: 2/2 (Params: 1176)
    [Upward Pruned] 3846 supersets removed from queue.
  [FULL ] [1, 55, 10, 2] -> Rank: 2/2 (Params: 625)
    [Upward Pruned] 2240 supersets removed from queue.
  [FULL ] [1, 9, 155, 2] -> Rank: 2/2 (Params: 1714)
    [Upward Pruned] 66 supersets removed from queue.
  [FULL ] [1, 12, 37, 2] -> Rank: 2/2 (Params: 530)
    [Upward Pruned] 1393 supersets removed from queue.
  [FULL ] [1, 6, 142, 2] -> Rank: 2/2 (Params: 1142)
    [Upward Pruned] 252 supersets removed from queue.
  [FULL ] [1, 4, 36, 2] -> Rank: 2/2 (Params: 220)
    [Upward Pruned] 1162 supersets removed from queue.
  [FULL ] [1, 42, 16, 2] -> Rank: 2/2 (Params: 746)
    [Upward Pruned] 259 supersets removed from queue.
  [FULL ] [1, 2, 190, 2] -> Rank: 2/2 (Params: 762)
    [Upward Pruned] 221 supersets removed from queue.
  [FULL ] [1, 5, 11, 2] -> Rank: 2/2 (Params: 82)
    [Upward Pruned] 989 supersets removed from queue.
  [FULL ] [1, 3, 48, 2] -> Rank: 2/2 (Params: 243)
    [Upward Pruned] 141 supersets removed from queue.
  [FULL ] [1, 97, 8, 2] -> Rank: 2/2 (Params: 889)
    [Upward Pruned] 89 supersets removed from queue.
  [FULL ] [1, 47, 3, 2] -> Rank: 2/2 (Params: 194)
    [Upward Pruned] 582 supersets removed from queue.
  [FULL ] [1, 26, 5, 2] -> Rank: 2/2 (Params: 166)
    [Upward Pruned] 125 supersets removed from queue.
  [FULL ] [1, 13, 4, 2] -> Rank: 2/2 (Params: 73)
    [Upward Pruned] 111 supersets removed from queue.
  [FULL ] [1, 44, 3, 2] -> Rank: 2/2 (Params: 182)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 3, 6, 2] -> Rank: 2/2 (Params: 33)
    [Upward Pruned] 111 supersets removed from queue.
  [FULL ] [1, 2, 70, 2] -> Rank: 2/2 (Params: 282)
    [Upward Pruned] 119 supersets removed from queue.
  [FULL ] [1, 29, 2, 2] -> Rank: 2/2 (Params: 91)
    [Upward Pruned] 127 supersets removed from queue.
  [FULL ] [1, 2, 19, 2] -> Rank: 2/2 (Params: 78)
    [Upward Pruned] 50 supersets removed from queue.
  [FULL ] [1, 12, 5, 2] -> Rank: 2/2 (Params: 82)
  [FULL ] [1, 4, 3, 2] -> Rank: 2/2 (Params: 22)
    [Upward Pruned] 41 supersets removed from queue.
  [FULL ] [1, 3, 4, 2] -> Rank: 2/2 (Params: 23)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 6, 2] -> Rank: 2/2 (Params: 26)
    [Upward Pruned] 12 supersets removed from queue.
  [FULL ] [1, 22, 2, 2] -> Rank: 2/2 (Params: 70)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 3, 3, 2] -> Rank: 2/2 (Params: 18)
  [FULL ] [1, 18, 2, 2] -> Rank: 2/2 (Params: 58)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 4, 2, 2] -> Rank: 2/2 (Params: 16)
    [Upward Pruned] 13 supersets removed from queue.
  [FULL ] [1, 2, 5, 2] -> Rank: 2/2 (Params: 22)
  [FULL ] [1, 2, 4, 2] -> Rank: 2/2 (Params: 18)
  [FULL ] [1, 3, 2, 2] -> Rank: 2/2 (Params: 13)
  [FULL ] [1, 2, 3, 2] -> Rank: 2/2 (Params: 14)
  [FULL ] [1, 2, 2, 2] -> Rank: 2/2 (Params: 10)

Added 45 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_2_r9_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=1 ---
  Target Ambient Dimension: 3
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 69, 3] -> Rank: 3/3 (Params: 276)
    [Upward Pruned] 231 supersets removed from queue.
  [FULL ] [1, 54, 3] -> Rank: 3/3 (Params: 216)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 32, 3] -> Rank: 3/3 (Params: 128)
    [Upward Pruned] 21 supersets removed from queue.
  [FULL ] [1, 10, 3] -> Rank: 3/3 (Params: 40)
    [Upward Pruned] 21 supersets removed from queue.
  [FULL ] [1, 4, 3] -> Rank: 3/3 (Params: 16)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 2, 3] -> Rank: 3/3 (Params: 8)
    [Upward Pruned] 1 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=1 ---
  Target Ambient Dimension: 3
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 244, 48, 3] -> Rank: 3/3 (Params: 12100)
    [Upward Pruned] 14420 supersets removed from queue.
  [FULL ] [1, 95, 156, 3] -> Rank: 3/3 (Params: 15383)
    [Upward Pruned] 21604 supersets removed from queue.
  [FULL ] [1, 167, 24, 3] -> Rank: 3/3 (Params: 4247)
    [Upward Pruned] 11531 supersets removed from queue.
  [FULL ] [1, 26, 183, 3] -> Rank: 3/3 (Params: 5333)
    [Upward Pruned] 8141 supersets removed from queue.
  [FULL ] [1, 22, 21, 3] -> Rank: 3/3 (Params: 547)
    [Upward Pruned] 22419 supersets removed from queue.
  [FULL ] [1, 4, 99, 3] -> Rank: 3/3 (Params: 697)
    [Upward Pruned] 3635 supersets removed from queue.
  [FULL ] [1, 6, 70, 3] -> Rank: 3/3 (Params: 636)
    [Upward Pruned] 463 supersets removed from queue.
  [FULL ] [1, 152, 20, 3] -> Rank: 3/3 (Params: 3252)
    [Upward Pruned] 148 supersets removed from queue.
  [FULL ] [1, 201, 7, 3] -> Rank: 3/3 (Params: 1629)
    [Upward Pruned] 1299 supersets removed from queue.
  [FULL ] [1, 166, 15, 3] -> Rank: 3/3 (Params: 2701)
    [Upward Pruned] 174 supersets removed from queue.
  [FULL ] [1, 19, 40, 3] -> Rank: 3/3 (Params: 899)
    [Upward Pruned] 89 supersets removed from queue.
  [FULL ] [1, 177, 7, 3] -> Rank: 3/3 (Params: 1437)
    [Upward Pruned] 191 supersets removed from queue.
  [FULL ] [1, 67, 6, 3] -> Rank: 3/3 (Params: 487)
    [Upward Pruned] 1693 supersets removed from queue.
  [FULL ] [1, 18, 68, 3] -> Rank: 3/3 (Params: 1446)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 3, 294, 3] -> Rank: 3/3 (Params: 1767)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 14, 6, 3] -> Rank: 3/3 (Params: 116)
    [Upward Pruned] 1094 supersets removed from queue.
  [FULL ] [1, 260, 4, 3] -> Rank: 3/3 (Params: 1312)
    [Upward Pruned] 81 supersets removed from queue.
  [FULL ] [1, 3, 98, 3] -> Rank: 3/3 (Params: 591)
    [Upward Pruned] 197 supersets removed from queue.
  [FULL ] [1, 12, 15, 3] -> Rank: 3/3 (Params: 237)
    [Upward Pruned] 109 supersets removed from queue.
  [FULL ] [1, 4, 8, 3] -> Rank: 3/3 (Params: 60)
    [Upward Pruned] 565 supersets removed from queue.
  [FULL ] [1, 216, 5, 3] -> Rank: 3/3 (Params: 1311)
    [Upward Pruned] 43 supersets removed from queue.
  [FULL ] [1, 143, 3, 3] -> Rank: 3/3 (Params: 581)
    [Upward Pruned] 347 supersets removed from queue.
  [FULL ] [1, 2, 224, 3] -> Rank: 3/3 (Params: 1122)
    [Upward Pruned] 76 supersets removed from queue.
  [FULL ] [1, 161, 2, 3] -> Rank: 3/3 (Params: 489)
    [Upward Pruned] 139 supersets removed from queue.
  [FULL ] [1, 128, 2, 3] -> Rank: 3/3 (Params: 390)
    [Upward Pruned] 77 supersets removed from queue.
  [FULL ] [1, 96, 4, 3] -> Rank: 3/3 (Params: 492)
    [Upward Pruned] 63 supersets removed from queue.
  [FULL ] [1, 40, 4, 3] -> Rank: 3/3 (Params: 212)
    [Upward Pruned] 111 supersets removed from queue.
  [FULL ] [1, 95, 3, 3] -> Rank: 3/3 (Params: 389)
    [Upward Pruned] 32 supersets removed from queue.
  [FULL ] [1, 74, 3, 3] -> Rank: 3/3 (Params: 305)
    [Upward Pruned] 20 supersets removed from queue.
  [FULL ] [1, 12, 3, 3] -> Rank: 3/3 (Params: 57)
    [Upward Pruned] 121 supersets removed from queue.
  [FULL ] [1, 2, 136, 3] -> Rank: 3/3 (Params: 682)
    [Upward Pruned] 87 supersets removed from queue.
  [FULL ] [1, 2, 53, 3] -> Rank: 3/3 (Params: 267)
    [Upward Pruned] 127 supersets removed from queue.
  [FULL ] [1, 3, 13, 3] -> Rank: 3/3 (Params: 81)
    [Upward Pruned] 39 supersets removed from queue.
  [FULL ] [1, 6, 2, 3] -> Rank: 3/3 (Params: 24)
    [Upward Pruned] 151 supersets removed from queue.
  [FULL ] [1, 5, 5, 3] -> Rank: 3/3 (Params: 45)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 2, 24, 3] -> Rank: 3/3 (Params: 122)
    [Upward Pruned] 28 supersets removed from queue.
  [FULL ] [1, 2, 19, 3] -> Rank: 3/3 (Params: 97)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 2, 4, 3] -> Rank: 3/3 (Params: 22)
    [Upward Pruned] 28 supersets removed from queue.
  [FULL ] [1, 5, 3, 3] -> Rank: 3/3 (Params: 29)
  [FULL ] [1, 4, 3, 3] -> Rank: 3/3 (Params: 25)
  [FULL ] [1, 2, 3, 3] -> Rank: 3/3 (Params: 17)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 3, 2, 3] -> Rank: 3/3 (Params: 15)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 2, 2, 3] -> Rank: 3/3 (Params: 12)

Added 49 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_3_r1_architectures.csv'.

Loading existing database from '../data/raw/1_3_r2_architectures.csv'...

--- RANDOM SEARCH: h=2, exponent=2 ---
  Target Ambient Dimension: 3
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 293 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.

--- RANDOM SEARCH: h=3, exponent=2 ---
  Target Ambient Dimension: 3
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 89343 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_3_r2_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=3 ---
  Target Ambient Dimension: 3
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 268, 3] -> Rank: 3/3 (Params: 1072)
    [Upward Pruned] 32 supersets removed from queue.
  [FULL ] [1, 69, 3] -> Rank: 3/3 (Params: 276)
    [Upward Pruned] 198 supersets removed from queue.
  [FULL ] [1, 46, 3] -> Rank: 3/3 (Params: 184)
    [Upward Pruned] 22 supersets removed from queue.
  [FULL ] [1, 18, 3] -> Rank: 3/3 (Params: 72)
    [Upward Pruned] 27 supersets removed from queue.
  [FULL ] [1, 7, 3] -> Rank: 3/3 (Params: 28)
    [Upward Pruned] 10 supersets removed from queue.
  [FULL ] [1, 6, 3] -> Rank: 3/3 (Params: 24)
  [FULL ] [1, 3, 3] -> Rank: 3/3 (Params: 12)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 2, 3] -> Rank: 3/3 (Params: 8)

--- RANDOM SEARCH: h=3, exponent=3 ---
  Target Ambient Dimension: 3
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 75, 243, 3] -> Rank: 3/3 (Params: 19029)
    [Upward Pruned] 13107 supersets removed from queue.
  [FULL ] [1, 228, 23, 3] -> Rank: 3/3 (Params: 5541)
    [Upward Pruned] 16059 supersets removed from queue.
  [FULL ] [1, 216, 77, 3] -> Rank: 3/3 (Params: 17079)
    [Upward Pruned] 1991 supersets removed from queue.
  [FULL ] [1, 127, 188, 3] -> Rank: 3/3 (Params: 24567)
    [Upward Pruned] 4894 supersets removed from queue.
  [FULL ] [1, 15, 102, 3] -> Rank: 3/3 (Params: 1851)
    [Upward Pruned] 26925 supersets removed from queue.
  [FULL ] [1, 186, 89, 3] -> Rank: 3/3 (Params: 17007)
    [Upward Pruned] 389 supersets removed from queue.
  [FULL ] [1, 178, 90, 3] -> Rank: 3/3 (Params: 16468)
    [Upward Pruned] 95 supersets removed from queue.
  [FULL ] [1, 171, 18, 3] -> Rank: 3/3 (Params: 3303)
    [Upward Pruned] 4366 supersets removed from queue.
  [FULL ] [1, 120, 48, 3] -> Rank: 3/3 (Params: 6024)
    [Upward Pruned] 2753 supersets removed from queue.
  [FULL ] [1, 152, 45, 3] -> Rank: 3/3 (Params: 7127)
    [Upward Pruned] 56 supersets removed from queue.
  [FULL ] [1, 150, 18, 3] -> Rank: 3/3 (Params: 2904)
    [Upward Pruned] 572 supersets removed from queue.
  [FULL ] [1, 13, 34, 3] -> Rank: 3/3 (Params: 557)
    [Upward Pruned] 8093 supersets removed from queue.
  [FULL ] [1, 108, 31, 3] -> Rank: 3/3 (Params: 3549)
    [Upward Pruned] 125 supersets removed from queue.
  [FULL ] [1, 72, 32, 3] -> Rank: 3/3 (Params: 2472)
    [Upward Pruned] 71 supersets removed from queue.
  [FULL ] [1, 21, 33, 3] -> Rank: 3/3 (Params: 813)
    [Upward Pruned] 50 supersets removed from queue.
  [FULL ] [1, 10, 171, 3] -> Rank: 3/3 (Params: 2233)
    [Upward Pruned] 389 supersets removed from queue.
  [FULL ] [1, 36, 11, 3] -> Rank: 3/3 (Params: 465)
    [Upward Pruned] 3444 supersets removed from queue.
  [FULL ] [1, 8, 5, 3] -> Rank: 3/3 (Params: 63)
    [Upward Pruned] 3331 supersets removed from queue.
  [FULL ] [1, 7, 150, 3] -> Rank: 3/3 (Params: 1507)
    [Upward Pruned] 150 supersets removed from queue.
  [FULL ] [1, 2, 156, 3] -> Rank: 3/3 (Params: 782)
    [Upward Pruned] 724 supersets removed from queue.
  [FULL ] [1, 5, 38, 3] -> Rank: 3/3 (Params: 309)
    [Upward Pruned] 347 supersets removed from queue.
  [FULL ] [1, 22, 2, 3] -> Rank: 3/3 (Params: 72)
    [Upward Pruned] 836 supersets removed from queue.
  [FULL ] [1, 2, 122, 3] -> Rank: 3/3 (Params: 612)
    [Upward Pruned] 101 supersets removed from queue.
  [FULL ] [1, 4, 40, 3] -> Rank: 3/3 (Params: 284)
    [Upward Pruned] 81 supersets removed from queue.
  [FULL ] [1, 6, 14, 3] -> Rank: 3/3 (Params: 132)
    [Upward Pruned] 47 supersets removed from queue.
  [FULL ] [1, 6, 7, 3] -> Rank: 3/3 (Params: 69)
    [Upward Pruned] 13 supersets removed from queue.
  [FULL ] [1, 15, 2, 3] -> Rank: 3/3 (Params: 51)
    [Upward Pruned] 20 supersets removed from queue.
  [FULL ] [1, 3, 30, 3] -> Rank: 3/3 (Params: 183)
    [Upward Pruned] 109 supersets removed from queue.
  [FULL ] [1, 5, 26, 3] -> Rank: 3/3 (Params: 213)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 2, 28, 3] -> Rank: 3/3 (Params: 142)
    [Upward Pruned] 97 supersets removed from queue.
  [FULL ] [1, 2, 17, 3] -> Rank: 3/3 (Params: 87)
    [Upward Pruned] 41 supersets removed from queue.
  [FULL ] [1, 7, 6, 3] -> Rank: 3/3 (Params: 67)
  [FULL ] [1, 4, 11, 3] -> Rank: 3/3 (Params: 81)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 11, 3, 3] -> Rank: 3/3 (Params: 53)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 2, 6, 3] -> Rank: 3/3 (Params: 32)
    [Upward Pruned] 32 supersets removed from queue.
  [FULL ] [1, 2, 2, 3] -> Rank: 3/3 (Params: 12)
    [Upward Pruned] 36 supersets removed from queue.

Added 44 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_3_r3_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=4 ---
  Target Ambient Dimension: 3
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 229, 3] -> Rank: 3/3 (Params: 916)
    [Upward Pruned] 71 supersets removed from queue.
  [FULL ] [1, 12, 3] -> Rank: 3/3 (Params: 48)
    [Upward Pruned] 216 supersets removed from queue.
  [FULL ] [1, 8, 3] -> Rank: 3/3 (Params: 32)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 4, 3] -> Rank: 3/3 (Params: 16)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 2, 3] -> Rank: 3/3 (Params: 8)
    [Upward Pruned] 1 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=4 ---
  Target Ambient Dimension: 3
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 23, 79, 3] -> Rank: 3/3 (Params: 2077)
    [Upward Pruned] 61715 supersets removed from queue.
  [FULL ] [1, 36, 64, 3] -> Rank: 3/3 (Params: 2532)
    [Upward Pruned] 3974 supersets removed from queue.
  [FULL ] [1, 15, 100, 3] -> Rank: 3/3 (Params: 1815)
    [Upward Pruned] 1607 supersets removed from queue.
  [FULL ] [1, 85, 37, 3] -> Rank: 3/3 (Params: 3341)
    [Upward Pruned] 5831 supersets removed from queue.
  [FULL ] [1, 4, 247, 3] -> Rank: 3/3 (Params: 1733)
    [Upward Pruned] 593 supersets removed from queue.
  [FULL ] [1, 6, 105, 3] -> Rank: 3/3 (Params: 951)
    [Upward Pruned] 1277 supersets removed from queue.
  [FULL ] [1, 259, 34, 3] -> Rank: 3/3 (Params: 9167)
    [Upward Pruned] 125 supersets removed from queue.
  [FULL ] [1, 59, 33, 3] -> Rank: 3/3 (Params: 2105)
    [Upward Pruned] 1543 supersets removed from queue.
  [FULL ] [1, 42, 17, 3] -> Rank: 3/3 (Params: 807)
    [Upward Pruned] 4670 supersets removed from queue.
  [FULL ] [1, 7, 11, 3] -> Rank: 3/3 (Params: 117)
    [Upward Pruned] 4219 supersets removed from queue.
  [FULL ] [1, 4, 155, 3] -> Rank: 3/3 (Params: 1089)
    [Upward Pruned] 183 supersets removed from queue.
  [FULL ] [1, 97, 8, 3] -> Rank: 3/3 (Params: 897)
    [Upward Pruned] 611 supersets removed from queue.
  [FULL ] [1, 241, 3, 3] -> Rank: 3/3 (Params: 973)
    [Upward Pruned] 299 supersets removed from queue.
  [FULL ] [1, 5, 26, 3] -> Rank: 3/3 (Params: 213)
    [Upward Pruned] 207 supersets removed from queue.
  [FULL ] [1, 120, 7, 3] -> Rank: 3/3 (Params: 981)
    [Upward Pruned] 120 supersets removed from queue.
  [FULL ] [1, 5, 2, 3] -> Rank: 3/3 (Params: 21)
    [Upward Pruned] 1660 supersets removed from queue.
  [FULL ] [1, 2, 161, 3] -> Rank: 3/3 (Params: 807)
    [Upward Pruned] 279 supersets removed from queue.
  [FULL ] [1, 3, 36, 3] -> Rank: 3/3 (Params: 219)
    [Upward Pruned] 243 supersets removed from queue.
  [FULL ] [1, 2, 117, 3] -> Rank: 3/3 (Params: 587)
    [Upward Pruned] 43 supersets removed from queue.
  [FULL ] [1, 4, 9, 3] -> Rank: 3/3 (Params: 67)
    [Upward Pruned] 26 supersets removed from queue.
  [FULL ] [1, 2, 66, 3] -> Rank: 3/3 (Params: 332)
    [Upward Pruned] 50 supersets removed from queue.
  [FULL ] [1, 2, 18, 3] -> Rank: 3/3 (Params: 92)
    [Upward Pruned] 65 supersets removed from queue.
  [FULL ] [1, 2, 2, 3] -> Rank: 3/3 (Params: 12)
    [Upward Pruned] 38 supersets removed from queue.

Added 28 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_3_r4_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=5 ---
  Target Ambient Dimension: 3
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 64, 3] -> Rank: 3/3 (Params: 256)
    [Upward Pruned] 236 supersets removed from queue.
  [FULL ] [1, 46, 3] -> Rank: 3/3 (Params: 184)
    [Upward Pruned] 17 supersets removed from queue.
  [FULL ] [1, 8, 3] -> Rank: 3/3 (Params: 32)
    [Upward Pruned] 37 supersets removed from queue.
  [FULL ] [1, 4, 3] -> Rank: 3/3 (Params: 16)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 2, 3] -> Rank: 3/3 (Params: 8)
    [Upward Pruned] 1 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=5 ---
  Target Ambient Dimension: 3
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 151, 113, 3] -> Rank: 3/3 (Params: 17553)
    [Upward Pruned] 28199 supersets removed from queue.
  [FULL ] [1, 46, 95, 3] -> Rank: 3/3 (Params: 4701)
    [Upward Pruned] 24329 supersets removed from queue.
  [FULL ] [1, 32, 134, 3] -> Rank: 3/3 (Params: 4722)
    [Upward Pruned] 2337 supersets removed from queue.
  [FULL ] [1, 10, 183, 3] -> Rank: 3/3 (Params: 2389)
    [Upward Pruned] 2595 supersets removed from queue.
  [FULL ] [1, 186, 16, 3] -> Rank: 3/3 (Params: 3210)
    [Upward Pruned] 9084 supersets removed from queue.
  [FULL ] [1, 116, 83, 3] -> Rank: 3/3 (Params: 9993)
    [Upward Pruned] 839 supersets removed from queue.
  [FULL ] [1, 35, 22, 3] -> Rank: 3/3 (Params: 871)
    [Upward Pruned] 10611 supersets removed from queue.
  [FULL ] [1, 5, 222, 3] -> Rank: 3/3 (Params: 1781)
    [Upward Pruned] 394 supersets removed from queue.
  [FULL ] [1, 80, 20, 3] -> Rank: 3/3 (Params: 1740)
    [Upward Pruned] 211 supersets removed from queue.
  [FULL ] [1, 31, 46, 3] -> Rank: 3/3 (Params: 1595)
    [Upward Pruned] 400 supersets removed from queue.
  [FULL ] [1, 167, 5, 3] -> Rank: 3/3 (Params: 1017)
    [Upward Pruned] 1549 supersets removed from queue.
  [FULL ] [1, 88, 7, 3] -> Rank: 3/3 (Params: 725)
    [Upward Pruned] 1026 supersets removed from queue.
  [FULL ] [1, 57, 20, 3] -> Rank: 3/3 (Params: 1257)
    [Upward Pruned] 45 supersets removed from queue.
  [FULL ] [1, 20, 24, 3] -> Rank: 3/3 (Params: 572)
    [Upward Pruned] 1836 supersets removed from queue.
  [FULL ] [1, 11, 29, 3] -> Rank: 3/3 (Params: 417)
    [Upward Pruned] 1385 supersets removed from queue.
  [FULL ] [1, 35, 6, 3] -> Rank: 3/3 (Params: 263)
    [Upward Pruned] 864 supersets removed from queue.
  [FULL ] [1, 6, 28, 3] -> Rank: 3/3 (Params: 258)
    [Upward Pruned] 939 supersets removed from queue.
  [FULL ] [1, 186, 3, 3] -> Rank: 3/3 (Params: 753)
    [Upward Pruned] 229 supersets removed from queue.
  [FULL ] [1, 2, 17, 3] -> Rank: 3/3 (Params: 87)
    [Upward Pruned] 1315 supersets removed from queue.
  [FULL ] [1, 40, 5, 3] -> Rank: 3/3 (Params: 255)
    [Upward Pruned] 126 supersets removed from queue.
  [FULL ] [1, 180, 3, 3] -> Rank: 3/3 (Params: 729)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 70, 3, 3] -> Rank: 3/3 (Params: 289)
    [Upward Pruned] 219 supersets removed from queue.
  [FULL ] [1, 11, 13, 3] -> Rank: 3/3 (Params: 193)
    [Upward Pruned] 95 supersets removed from queue.
  [FULL ] [1, 113, 2, 3] -> Rank: 3/3 (Params: 345)
    [Upward Pruned] 187 supersets removed from queue.
  [FULL ] [1, 56, 3, 3] -> Rank: 3/3 (Params: 233)
    [Upward Pruned] 27 supersets removed from queue.
  [FULL ] [1, 16, 10, 3] -> Rank: 3/3 (Params: 206)
    [Upward Pruned] 56 supersets removed from queue.
  [FULL ] [1, 4, 10, 3] -> Rank: 3/3 (Params: 74)
    [Upward Pruned] 63 supersets removed from queue.
  [FULL ] [1, 2, 13, 3] -> Rank: 3/3 (Params: 67)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 79, 2, 3] -> Rank: 3/3 (Params: 243)
    [Upward Pruned] 33 supersets removed from queue.
  [FULL ] [1, 16, 8, 3] -> Rank: 3/3 (Params: 168)
    [Upward Pruned] 37 supersets removed from queue.
  [FULL ] [1, 7, 5, 3] -> Rank: 3/3 (Params: 57)
    [Upward Pruned] 106 supersets removed from queue.
  [FULL ] [1, 50, 3, 3] -> Rank: 3/3 (Params: 209)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 4, 2, 3] -> Rank: 3/3 (Params: 18)
    [Upward Pruned] 181 supersets removed from queue.
  [FULL ] [1, 3, 8, 3] -> Rank: 3/3 (Params: 51)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 2, 5, 3] -> Rank: 3/3 (Params: 27)
    [Upward Pruned] 10 supersets removed from queue.
  [FULL ] [1, 2, 2, 3] -> Rank: 3/3 (Params: 12)
    [Upward Pruned] 5 supersets removed from queue.

Added 41 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_3_r5_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=6 ---
  Target Ambient Dimension: 3
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 283, 3] -> Rank: 3/3 (Params: 1132)
    [Upward Pruned] 17 supersets removed from queue.
  [FULL ] [1, 70, 3] -> Rank: 3/3 (Params: 280)
    [Upward Pruned] 212 supersets removed from queue.
  [FULL ] [1, 27, 3] -> Rank: 3/3 (Params: 108)
    [Upward Pruned] 42 supersets removed from queue.
  [FULL ] [1, 13, 3] -> Rank: 3/3 (Params: 52)
    [Upward Pruned] 13 supersets removed from queue.
  [FULL ] [1, 2, 3] -> Rank: 3/3 (Params: 8)
    [Upward Pruned] 10 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=6 ---
  Target Ambient Dimension: 3
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 182, 76, 3] -> Rank: 3/3 (Params: 14242)
    [Upward Pruned] 26774 supersets removed from queue.
  [FULL ] [1, 30, 198, 3] -> Rank: 3/3 (Params: 6564)
    [Upward Pruned] 15655 supersets removed from queue.
  [FULL ] [1, 34, 139, 3] -> Rank: 3/3 (Params: 5177)
    [Upward Pruned] 8731 supersets removed from queue.
  [FULL ] [1, 62, 18, 3] -> Rank: 3/3 (Params: 1232)
    [Upward Pruned] 21421 supersets removed from queue.
  [FULL ] [1, 29, 102, 3] -> Rank: 3/3 (Params: 3293)
    [Upward Pruned] 1618 supersets removed from queue.
  [FULL ] [1, 24, 27, 3] -> Rank: 3/3 (Params: 753)
    [Upward Pruned] 3844 supersets removed from queue.
  [FULL ] [1, 85, 11, 3] -> Rank: 3/3 (Params: 1053)
    [Upward Pruned] 1511 supersets removed from queue.
  [FULL ] [1, 16, 263, 3] -> Rank: 3/3 (Params: 5013)
    [Upward Pruned] 303 supersets removed from queue.
  [FULL ] [1, 10, 207, 3] -> Rank: 3/3 (Params: 2701)
    [Upward Pruned] 1011 supersets removed from queue.
  [FULL ] [1, 19, 101, 3] -> Rank: 3/3 (Params: 2241)
    [Upward Pruned] 529 supersets removed from queue.
  [FULL ] [1, 5, 160, 3] -> Rank: 3/3 (Params: 1285)
    [Upward Pruned] 1127 supersets removed from queue.
  [FULL ] [1, 103, 5, 3] -> Rank: 3/3 (Params: 633)
    [Upward Pruned] 1187 supersets removed from queue.
  [FULL ] [1, 13, 116, 3] -> Rank: 3/3 (Params: 1869)
    [Upward Pruned] 263 supersets removed from queue.
  [FULL ] [1, 8, 141, 3] -> Rank: 3/3 (Params: 1559)
    [Upward Pruned] 94 supersets removed from queue.
  [FULL ] [1, 18, 34, 3] -> Rank: 3/3 (Params: 732)
    [Upward Pruned] 416 supersets removed from queue.
  [FULL ] [1, 244, 4, 3] -> Rank: 3/3 (Params: 1232)
    [Upward Pruned] 56 supersets removed from queue.
  [FULL ] [1, 75, 13, 3] -> Rank: 3/3 (Params: 1089)
    [Upward Pruned] 49 supersets removed from queue.
  [FULL ] [1, 100, 10, 3] -> Rank: 3/3 (Params: 1130)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 15, 56, 3] -> Rank: 3/3 (Params: 1023)
    [Upward Pruned] 179 supersets removed from queue.
  [FULL ] [1, 44, 12, 3] -> Rank: 3/3 (Params: 608)
    [Upward Pruned] 357 supersets removed from queue.
  [FULL ] [1, 20, 22, 3] -> Rank: 3/3 (Params: 526)
    [Upward Pruned] 147 supersets removed from queue.
  [FULL ] [1, 3, 243, 3] -> Rank: 3/3 (Params: 1461)
    [Upward Pruned] 115 supersets removed from queue.
  [FULL ] [1, 10, 125, 3] -> Rank: 3/3 (Params: 1635)
    [Upward Pruned] 47 supersets removed from queue.
  [FULL ] [1, 11, 4, 3] -> Rank: 3/3 (Params: 67)
    [Upward Pruned] 1705 supersets removed from queue.
  [FULL ] [1, 2, 209, 3] -> Rank: 3/3 (Params: 1047)
    [Upward Pruned] 159 supersets removed from queue.
  [FULL ] [1, 4, 159, 3] -> Rank: 3/3 (Params: 1117)
    [Upward Pruned] 52 supersets removed from queue.
  [FULL ] [1, 4, 125, 3] -> Rank: 3/3 (Params: 879)
    [Upward Pruned] 167 supersets removed from queue.
  [FULL ] [1, 9, 45, 3] -> Rank: 3/3 (Params: 549)
    [Upward Pruned] 159 supersets removed from queue.
  [FULL ] [1, 2, 12, 3] -> Rank: 3/3 (Params: 62)
    [Upward Pruned] 1024 supersets removed from queue.
  [FULL ] [1, 9, 3, 3] -> Rank: 3/3 (Params: 45)
    [Upward Pruned] 307 supersets removed from queue.
  [FULL ] [1, 7, 11, 3] -> Rank: 3/3 (Params: 117)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 9, 3] -> Rank: 3/3 (Params: 47)
    [Upward Pruned] 18 supersets removed from queue.
  [FULL ] [1, 45, 2, 3] -> Rank: 3/3 (Params: 141)
    [Upward Pruned] 255 supersets removed from queue.
  [FULL ] [1, 5, 8, 3] -> Rank: 3/3 (Params: 69)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 7, 3, 3] -> Rank: 3/3 (Params: 37)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 5, 7, 3] -> Rank: 3/3 (Params: 61)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 33, 2, 3] -> Rank: 3/3 (Params: 105)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 2, 5, 3] -> Rank: 3/3 (Params: 27)
    [Upward Pruned] 15 supersets removed from queue.
  [FULL ] [1, 3, 3, 3] -> Rank: 3/3 (Params: 21)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 31, 2, 3] -> Rank: 3/3 (Params: 99)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 7, 2, 3] -> Rank: 3/3 (Params: 27)
    [Upward Pruned] 23 supersets removed from queue.
  [FULL ] [1, 6, 2, 3] -> Rank: 3/3 (Params: 24)
  [FULL ] [1, 3, 2, 3] -> Rank: 3/3 (Params: 15)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 2, 4, 3] -> Rank: 3/3 (Params: 22)
  [FULL ] [1, 2, 3, 3] -> Rank: 3/3 (Params: 17)
  [FULL ] [1, 2, 2, 3] -> Rank: 3/3 (Params: 12)

Added 51 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_3_r6_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=7 ---
  Target Ambient Dimension: 3
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 104, 3] -> Rank: 3/3 (Params: 416)
    [Upward Pruned] 196 supersets removed from queue.
  [FULL ] [1, 31, 3] -> Rank: 3/3 (Params: 124)
    [Upward Pruned] 72 supersets removed from queue.
  [FULL ] [1, 15, 3] -> Rank: 3/3 (Params: 60)
    [Upward Pruned] 15 supersets removed from queue.
  [FULL ] [1, 4, 3] -> Rank: 3/3 (Params: 16)
    [Upward Pruned] 10 supersets removed from queue.
  [FULL ] [1, 3, 3] -> Rank: 3/3 (Params: 12)
  [FULL ] [1, 2, 3] -> Rank: 3/3 (Params: 8)

--- RANDOM SEARCH: h=3, exponent=7 ---
  Target Ambient Dimension: 3
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 31, 106, 3] -> Rank: 3/3 (Params: 3635)
    [Upward Pruned] 52649 supersets removed from queue.
  [FULL ] [1, 81, 51, 3] -> Rank: 3/3 (Params: 4365)
    [Upward Pruned] 12099 supersets removed from queue.
  [FULL ] [1, 57, 22, 3] -> Rank: 3/3 (Params: 1377)
    [Upward Pruned] 8395 supersets removed from queue.
  [FULL ] [1, 28, 107, 3] -> Rank: 3/3 (Params: 3345)
    [Upward Pruned] 581 supersets removed from queue.
  [FULL ] [1, 12, 139, 3] -> Rank: 3/3 (Params: 2097)
    [Upward Pruned] 2591 supersets removed from queue.
  [FULL ] [1, 41, 79, 3] -> Rank: 3/3 (Params: 3517)
    [Upward Pruned] 431 supersets removed from queue.
  [FULL ] [1, 53, 4, 3] -> Rank: 3/3 (Params: 277)
    [Upward Pruned] 4691 supersets removed from queue.
  [FULL ] [1, 32, 46, 3] -> Rank: 3/3 (Params: 1642)
    [Upward Pruned] 935 supersets removed from queue.
  [FULL ] [1, 34, 34, 3] -> Rank: 3/3 (Params: 1292)
    [Upward Pruned] 227 supersets removed from queue.
  [FULL ] [1, 13, 108, 3] -> Rank: 3/3 (Params: 1741)
    [Upward Pruned] 464 supersets removed from queue.
  [FULL ] [1, 27, 42, 3] -> Rank: 3/3 (Params: 1287)
    [Upward Pruned] 332 supersets removed from queue.
  [FULL ] [1, 33, 17, 3] -> Rank: 3/3 (Params: 645)
    [Upward Pruned] 347 supersets removed from queue.
  [FULL ] [1, 2, 208, 3] -> Rank: 3/3 (Params: 1042)
    [Upward Pruned] 929 supersets removed from queue.
  [FULL ] [1, 16, 86, 3] -> Rank: 3/3 (Params: 1650)
    [Upward Pruned] 241 supersets removed from queue.
  [FULL ] [1, 3, 151, 3] -> Rank: 3/3 (Params: 909)
    [Upward Pruned] 512 supersets removed from queue.
  [FULL ] [1, 12, 38, 3] -> Rank: 3/3 (Params: 582)
    [Upward Pruned] 862 supersets removed from queue.
  [FULL ] [1, 2, 137, 3] -> Rank: 3/3 (Params: 687)
    [Upward Pruned] 196 supersets removed from queue.
  [FULL ] [1, 6, 96, 3] -> Rank: 3/3 (Params: 870)
    [Upward Pruned] 245 supersets removed from queue.
  [FULL ] [1, 11, 4, 3] -> Rank: 3/3 (Params: 67)
    [Upward Pruned] 1065 supersets removed from queue.
  [FULL ] [1, 3, 128, 3] -> Rank: 3/3 (Params: 771)
    [Upward Pruned] 26 supersets removed from queue.
  [FULL ] [1, 19, 2, 3] -> Rank: 3/3 (Params: 63)
    [Upward Pruned] 563 supersets removed from queue.
  [FULL ] [1, 3, 92, 3] -> Rank: 3/3 (Params: 555)
    [Upward Pruned] 127 supersets removed from queue.
  [FULL ] [1, 4, 32, 3] -> Rank: 3/3 (Params: 228)
    [Upward Pruned] 419 supersets removed from queue.
  [FULL ] [1, 10, 17, 3] -> Rank: 3/3 (Params: 231)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 8, 14, 3] -> Rank: 3/3 (Params: 162)
    [Upward Pruned] 38 supersets removed from queue.
  [FULL ] [1, 3, 9, 3] -> Rank: 3/3 (Params: 57)
    [Upward Pruned] 189 supersets removed from queue.
  [FULL ] [1, 2, 127, 3] -> Rank: 3/3 (Params: 637)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 2, 50, 3] -> Rank: 3/3 (Params: 252)
    [Upward Pruned] 76 supersets removed from queue.
  [FULL ] [1, 9, 7, 3] -> Rank: 3/3 (Params: 93)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 2, 30, 3] -> Rank: 3/3 (Params: 152)
    [Upward Pruned] 19 supersets removed from queue.
  [FULL ] [1, 4, 3, 3] -> Rank: 3/3 (Params: 25)
    [Upward Pruned] 45 supersets removed from queue.
  [FULL ] [1, 2, 9, 3] -> Rank: 3/3 (Params: 47)
    [Upward Pruned] 20 supersets removed from queue.
  [FULL ] [1, 10, 2, 3] -> Rank: 3/3 (Params: 36)
    [Upward Pruned] 8 supersets removed from queue.
  [FULL ] [1, 3, 8, 3] -> Rank: 3/3 (Params: 51)
  [FULL ] [1, 6, 2, 3] -> Rank: 3/3 (Params: 24)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 2, 5, 3] -> Rank: 3/3 (Params: 27)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 2, 2, 3] -> Rank: 3/3 (Params: 12)
    [Upward Pruned] 7 supersets removed from queue.

Added 43 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_3_r7_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=8 ---
  Target Ambient Dimension: 3
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 32, 3] -> Rank: 3/3 (Params: 128)
    [Upward Pruned] 268 supersets removed from queue.

  [FULL ] [1, 11, 3] -> Rank: 3/3 (Params: 44)
    [Upward Pruned] 20 supersets removed from queue.
  [FULL ] [1, 7, 3] -> Rank: 3/3 (Params: 28)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 6, 3] -> Rank: 3/3 (Params: 24)
  [FULL ] [1, 4, 3] -> Rank: 3/3 (Params: 16)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 3, 3] -> Rank: 3/3 (Params: 12)
  [FULL ] [1, 2, 3] -> Rank: 3/3 (Params: 8)

--- RANDOM SEARCH: h=3, exponent=8 ---
  Target Ambient Dimension: 3
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 147, 190, 3] -> Rank: 3/3 (Params: 28647)
    [Upward Pruned] 17093 supersets removed from queue.
  [FULL ] [1, 242, 71, 3] -> Rank: 3/3 (Params: 17637)
    [Upward Pruned] 7020 supersets removed from queue.
  [FULL ] [1, 144, 248, 3] -> Rank: 3/3 (Params: 36600)
    [Upward Pruned] 158 supersets removed from queue.
  [FULL ] [1, 61, 192, 3] -> Rank: 3/3 (Params: 12349)
    [Upward Pruned] 9214 supersets removed from queue.
  [FULL ] [1, 33, 127, 3] -> Rank: 3/3 (Params: 4605)
    [Upward Pruned] 16446 supersets removed from queue.
  [FULL ] [1, 32, 181, 3] -> Rank: 3/3 (Params: 6367)
    [Upward Pruned] 119 supersets removed from queue.
  [FULL ] [1, 295, 43, 3] -> Rank: 3/3 (Params: 13109)
    [Upward Pruned] 167 supersets removed from queue.
  [FULL ] [1, 113, 20, 3] -> Rank: 3/3 (Params: 2433)
    [Upward Pruned] 16643 supersets removed from queue.
  [FULL ] [1, 26, 123, 3] -> Rank: 3/3 (Params: 3593)
    [Upward Pruned] 1445 supersets removed from queue.
  [FULL ] [1, 20, 228, 3] -> Rank: 3/3 (Params: 5264)
    [Upward Pruned] 437 supersets removed from queue.
  [FULL ] [1, 4, 70, 3] -> Rank: 3/3 (Params: 494)
    [Upward Pruned] 9254 supersets removed from queue.
  [FULL ] [1, 15, 21, 3] -> Rank: 3/3 (Params: 393)
    [Upward Pruned] 4801 supersets removed from queue.
  [FULL ] [1, 224, 16, 3] -> Rank: 3/3 (Params: 3856)
    [Upward Pruned] 307 supersets removed from queue.
  [FULL ] [1, 11, 32, 3] -> Rank: 3/3 (Params: 459)
    [Upward Pruned] 151 supersets removed from queue.
  [FULL ] [1, 13, 18, 3] -> Rank: 3/3 (Params: 301)
    [Upward Pruned] 543 supersets removed from queue.
  [FULL ] [1, 10, 5, 3] -> Rank: 3/3 (Params: 75)
    [Upward Pruned] 3708 supersets removed from queue.
  [FULL ] [1, 8, 15, 3] -> Rank: 3/3 (Params: 173)
    [Upward Pruned] 109 supersets removed from queue.
  [FULL ] [1, 2, 238, 3] -> Rank: 3/3 (Params: 1192)
    [Upward Pruned] 125 supersets removed from queue.
  [FULL ] [1, 3, 45, 3] -> Rank: 3/3 (Params: 273)
    [Upward Pruned] 292 supersets removed from queue.
  [FULL ] [1, 7, 2, 3] -> Rank: 3/3 (Params: 27)
    [Upward Pruned] 941 supersets removed from queue.
  [FULL ] [1, 6, 35, 3] -> Rank: 3/3 (Params: 321)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 2, 113, 3] -> Rank: 3/3 (Params: 567)
    [Upward Pruned] 124 supersets removed from queue.
  [FULL ] [1, 2, 57, 3] -> Rank: 3/3 (Params: 287)
    [Upward Pruned] 55 supersets removed from queue.
  [FULL ] [1, 5, 6, 3] -> Rank: 3/3 (Params: 53)
    [Upward Pruned] 67 supersets removed from queue.
  [FULL ] [1, 4, 23, 3] -> Rank: 3/3 (Params: 165)
    [Upward Pruned] 21 supersets removed from queue.
  [FULL ] [1, 2, 24, 3] -> Rank: 3/3 (Params: 122)
    [Upward Pruned] 53 supersets removed from queue.
  [FULL ] [1, 4, 13, 3] -> Rank: 3/3 (Params: 95)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 5, 4, 3] -> Rank: 3/3 (Params: 37)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 3, 23, 3] -> Rank: 3/3 (Params: 141)
  [FULL ] [1, 2, 21, 3] -> Rank: 3/3 (Params: 107)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 2, 14, 3] -> Rank: 3/3 (Params: 72)
    [Upward Pruned] 13 supersets removed from queue.
  [FULL ] [1, 6, 2, 3] -> Rank: 3/3 (Params: 24)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 3, 3] -> Rank: 3/3 (Params: 17)
    [Upward Pruned] 32 supersets removed from queue.
  [FULL ] [1, 3, 2, 3] -> Rank: 3/3 (Params: 15)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 2, 2, 3] -> Rank: 3/3 (Params: 12)

Added 42 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_3_r8_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=9 ---
  Target Ambient Dimension: 3
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 10, 3] -> Rank: 3/3 (Params: 40)
    [Upward Pruned] 290 supersets removed from queue.
  [FULL ] [1, 7, 3] -> Rank: 3/3 (Params: 28)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 2, 3] -> Rank: 3/3 (Params: 8)
    [Upward Pruned] 4 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=9 ---
  Target Ambient Dimension: 3
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 199, 102, 3] -> Rank: 3/3 (Params: 20803)
    [Upward Pruned] 20297 supersets removed from queue.
  [FULL ] [1, 12, 114, 3] -> Rank: 3/3 (Params: 1722)
    [Upward Pruned] 34968 supersets removed from queue.
  [FULL ] [1, 193, 3, 3] -> Rank: 3/3 (Params: 781)
    [Upward Pruned] 10763 supersets removed from queue.
  [FULL ] [1, 89, 98, 3] -> Rank: 3/3 (Params: 9105)
    [Upward Pruned] 1663 supersets removed from queue.
  [FULL ] [1, 79, 112, 3] -> Rank: 3/3 (Params: 9263)
    [Upward Pruned] 19 supersets removed from queue.
  [FULL ] [1, 6, 121, 3] -> Rank: 3/3 (Params: 1095)
    [Upward Pruned] 1079 supersets removed from queue.
  [FULL ] [1, 19, 110, 3] -> Rank: 3/3 (Params: 2439)
    [Upward Pruned] 259 supersets removed from queue.
  [FULL ] [1, 50, 54, 3] -> Rank: 3/3 (Params: 2912)
    [Upward Pruned] 6759 supersets removed from queue.
  [FULL ] [1, 148, 45, 3] -> Rank: 3/3 (Params: 6943)
    [Upward Pruned] 404 supersets removed from queue.
  [FULL ] [1, 130, 31, 3] -> Rank: 3/3 (Params: 4253)
    [Upward Pruned] 1043 supersets removed from queue.
  [FULL ] [1, 20, 25, 3] -> Rank: 3/3 (Params: 595)
    [Upward Pruned] 5247 supersets removed from queue.
  [FULL ] [1, 96, 19, 3] -> Rank: 3/3 (Params: 1977)
    [Upward Pruned] 581 supersets removed from queue.
  [FULL ] [1, 112, 11, 3] -> Rank: 3/3 (Params: 1377)
    [Upward Pruned] 647 supersets removed from queue.
  [FULL ] [1, 83, 15, 3] -> Rank: 3/3 (Params: 1373)
    [Upward Pruned] 193 supersets removed from queue.
  [FULL ] [1, 85, 11, 3] -> Rank: 3/3 (Params: 1053)
    [Upward Pruned] 107 supersets removed from queue.
  [FULL ] [1, 108, 5, 3] -> Rank: 3/3 (Params: 663)
    [Upward Pruned] 509 supersets removed from queue.
  [FULL ] [1, 18, 73, 3] -> Rank: 3/3 (Params: 1551)
    [Upward Pruned] 77 supersets removed from queue.
  [FULL ] [1, 3, 117, 3] -> Rank: 3/3 (Params: 705)
    [Upward Pruned] 575 supersets removed from queue.
  [FULL ] [1, 2, 130, 3] -> Rank: 3/3 (Params: 652)
    [Upward Pruned] 170 supersets removed from queue.
  [FULL ] [1, 81, 12, 3] -> Rank: 3/3 (Params: 1089)
    [Upward Pruned] 31 supersets removed from queue.
  [FULL ] [1, 8, 33, 3] -> Rank: 3/3 (Params: 371)
    [Upward Pruned] 901 supersets removed from queue.
  [FULL ] [1, 4, 5, 3] -> Rank: 3/3 (Params: 39)
    [Upward Pruned] 2169 supersets removed from queue.
  [FULL ] [1, 158, 4, 3] -> Rank: 3/3 (Params: 802)
    [Upward Pruned] 34 supersets removed from queue.
  [FULL ] [1, 3, 30, 3] -> Rank: 3/3 (Params: 183)
    [Upward Pruned] 86 supersets removed from queue.
  [FULL ] [1, 2, 14, 3] -> Rank: 3/3 (Params: 72)
    [Upward Pruned] 131 supersets removed from queue.
  [FULL ] [1, 88, 3, 3] -> Rank: 3/3 (Params: 361)
    [Upward Pruned] 174 supersets removed from queue.
  [FULL ] [1, 196, 2, 3] -> Rank: 3/3 (Params: 594)
    [Upward Pruned] 104 supersets removed from queue.
  [FULL ] [1, 160, 2, 3] -> Rank: 3/3 (Params: 486)
    [Upward Pruned] 35 supersets removed from queue.
  [FULL ] [1, 64, 3, 3] -> Rank: 3/3 (Params: 265)
    [Upward Pruned] 47 supersets removed from queue.
  [FULL ] [1, 90, 2, 3] -> Rank: 3/3 (Params: 276)
    [Upward Pruned] 69 supersets removed from queue.
  [FULL ] [1, 2, 11, 3] -> Rank: 3/3 (Params: 57)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 46, 2, 3] -> Rank: 3/3 (Params: 144)
    [Upward Pruned] 79 supersets removed from queue.
  [FULL ] [1, 10, 3, 3] -> Rank: 3/3 (Params: 49)
    [Upward Pruned] 71 supersets removed from queue.
  [FULL ] [1, 2, 3, 3] -> Rank: 3/3 (Params: 17)
    [Upward Pruned] 27 supersets removed from queue.
  [FULL ] [1, 40, 2, 3] -> Rank: 3/3 (Params: 126)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 4, 2, 3] -> Rank: 3/3 (Params: 18)
    [Upward Pruned] 35 supersets removed from queue.
  [FULL ] [1, 3, 2, 3] -> Rank: 3/3 (Params: 15)
  [FULL ] [1, 2, 2, 3] -> Rank: 3/3 (Params: 12)

Added 41 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_3_r9_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=1 ---
  Target Ambient Dimension: 4
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 200, 4] -> Rank: 4/4 (Params: 1000)
    [Upward Pruned] 100 supersets removed from queue.
  [FULL ] [1, 70, 4] -> Rank: 4/4 (Params: 350)
    [Upward Pruned] 129 supersets removed from queue.
  [FULL ] [1, 36, 4] -> Rank: 4/4 (Params: 180)
    [Upward Pruned] 33 supersets removed from queue.
  [FULL ] [1, 29, 4] -> Rank: 4/4 (Params: 145)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 6, 4] -> Rank: 4/4 (Params: 30)
    [Upward Pruned] 22 supersets removed from queue.
  [FULL ] [1, 2, 4] -> Rank: 4/4 (Params: 10)
    [Upward Pruned] 3 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=1 ---
  Target Ambient Dimension: 4
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 185, 277, 4] -> Rank: 4/4 (Params: 52538)
    [Upward Pruned] 2783 supersets removed from queue.
  [FULL ] [1, 48, 235, 4] -> Rank: 4/4 (Params: 12268)
    [Upward Pruned] 13913 supersets removed from queue.
  [FULL ] [1, 262, 60, 4] -> Rank: 4/4 (Params: 16222)
    [Upward Pruned] 6824 supersets removed from queue.
  [FULL ] [1, 80, 20, 4] -> Rank: 4/4 (Params: 1760)
    [Upward Pruned] 40689 supersets removed from queue.
  [FULL ] [1, 61, 183, 4] -> Rank: 4/4 (Params: 11956)
    [Upward Pruned] 987 supersets removed from queue.
  [FULL ] [1, 9, 253, 4] -> Rank: 4/4 (Params: 3298)
    [Upward Pruned] 1871 supersets removed from queue.
  [FULL ] [1, 233, 15, 4] -> Rank: 4/4 (Params: 3788)
    [Upward Pruned] 339 supersets removed from queue.
  [FULL ] [1, 59, 108, 4] -> Rank: 4/4 (Params: 6863)
    [Upward Pruned] 1678 supersets removed from queue.
  [FULL ] [1, 9, 103, 4] -> Rank: 4/4 (Params: 1348)
    [Upward Pruned] 7406 supersets removed from queue.
  [FULL ] [1, 87, 16, 4] -> Rank: 4/4 (Params: 1543)
    [Upward Pruned] 583 supersets removed from queue.
  [FULL ] [1, 123, 2, 4] -> Rank: 4/4 (Params: 377)
    [Upward Pruned] 2423 supersets removed from queue.
  [FULL ] [1, 41, 97, 4] -> Rank: 4/4 (Params: 4406)
    [Upward Pruned] 233 supersets removed from queue.
  [FULL ] [1, 52, 86, 4] -> Rank: 4/4 (Params: 4868)
    [Upward Pruned] 307 supersets removed from queue.
  [FULL ] [1, 12, 12, 4] -> Rank: 4/4 (Params: 204)
    [Upward Pruned] 5845 supersets removed from queue.
  [FULL ] [1, 48, 2, 4] -> Rank: 4/4 (Params: 152)
    [Upward Pruned] 749 supersets removed from queue.
  [FULL ] [1, 11, 67, 4] -> Rank: 4/4 (Params: 1016)
    [Upward Pruned] 35 supersets removed from queue.
  [FULL ] [1, 3, 53, 4] -> Rank: 4/4 (Params: 374)
    [Upward Pruned] 1601 supersets removed from queue.
  [FULL ] [1, 3, 47, 4] -> Rank: 4/4 (Params: 332)
    [Upward Pruned] 53 supersets removed from queue.
  [FULL ] [1, 2, 264, 4] -> Rank: 4/4 (Params: 1586)
    [Upward Pruned] 36 supersets removed from queue.
  [FULL ] [1, 32, 5, 4] -> Rank: 4/4 (Params: 212)
    [Upward Pruned] 111 supersets removed from queue.
  [FULL ] [1, 2, 186, 4] -> Rank: 4/4 (Params: 1118)
    [Upward Pruned] 77 supersets removed from queue.
  [FULL ] [1, 2, 134, 4] -> Rank: 4/4 (Params: 806)
    [Upward Pruned] 51 supersets removed from queue.
  [FULL ] [1, 16, 8, 4] -> Rank: 4/4 (Params: 176)
    [Upward Pruned] 63 supersets removed from queue.
  [FULL ] [1, 2, 40, 4] -> Rank: 4/4 (Params: 242)
    [Upward Pruned] 156 supersets removed from queue.
  [FULL ] [1, 4, 8, 4] -> Rank: 4/4 (Params: 68)
    [Upward Pruned] 271 supersets removed from queue.
  [FULL ] [1, 21, 3, 4] -> Rank: 4/4 (Params: 96)
    [Upward Pruned] 86 supersets removed from queue.
  [FULL ] [1, 3, 27, 4] -> Rank: 4/4 (Params: 192)
    [Upward Pruned] 12 supersets removed from queue.
  [FULL ] [1, 11, 5, 4] -> Rank: 4/4 (Params: 86)
    [Upward Pruned] 29 supersets removed from queue.
  [FULL ] [1, 34, 2, 4] -> Rank: 4/4 (Params: 110)
    [Upward Pruned] 13 supersets removed from queue.
  [FULL ] [1, 2, 12, 4] -> Rank: 4/4 (Params: 74)
    [Upward Pruned] 42 supersets removed from queue.
  [FULL ] [1, 9, 6, 4] -> Rank: 4/4 (Params: 87)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 5, 5, 4] -> Rank: 4/4 (Params: 50)
    [Upward Pruned] 13 supersets removed from queue.
  [FULL ] [1, 13, 2, 4] -> Rank: 4/4 (Params: 47)
    [Upward Pruned] 36 supersets removed from queue.
  [FULL ] [1, 5, 3, 4] -> Rank: 4/4 (Params: 32)
    [Upward Pruned] 15 supersets removed from queue.
  [FULL ] [1, 7, 2, 4] -> Rank: 4/4 (Params: 29)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 5, 2, 4] -> Rank: 4/4 (Params: 23)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 4, 4, 4] -> Rank: 4/4 (Params: 36)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 2, 3, 4] -> Rank: 4/4 (Params: 20)
    [Upward Pruned] 18 supersets removed from queue.
  [FULL ] [1, 4, 2, 4] -> Rank: 4/4 (Params: 20)
  [FULL ] [1, 2, 2, 4] -> Rank: 4/4 (Params: 14)
    [Upward Pruned] 1 supersets removed from queue.

Added 46 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_4_r1_architectures.csv'.

Loading existing database from '../data/raw/1_4_r2_architectures.csv'...

--- RANDOM SEARCH: h=2, exponent=2 ---
  Target Ambient Dimension: 4
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 294 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.

--- RANDOM SEARCH: h=3, exponent=2 ---
  Target Ambient Dimension: 4
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 89357 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_4_r2_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=3 ---
  Target Ambient Dimension: 4
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 3, 4] -> Rank: 4/4 (Params: 15)
    [Upward Pruned] 297 supersets removed from queue.
  [FULL ] [1, 2, 4] -> Rank: 4/4 (Params: 10)

--- RANDOM SEARCH: h=3, exponent=3 ---
  Target Ambient Dimension: 4
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 241, 109, 4] -> Rank: 4/4 (Params: 26946)
    [Upward Pruned] 11519 supersets removed from queue.
  [FULL ] [1, 219, 170, 4] -> Rank: 4/4 (Params: 38129)
    [Upward Pruned] 2881 supersets removed from queue.
  [FULL ] [1, 56, 72, 4] -> Rank: 4/4 (Params: 4376)
    [Upward Pruned] 41702 supersets removed from queue.
  [FULL ] [1, 218, 33, 4] -> Rank: 4/4 (Params: 7544)
    [Upward Pruned] 3236 supersets removed from queue.
  [FULL ] [1, 87, 55, 4] -> Rank: 4/4 (Params: 5092)
    [Upward Pruned] 2226 supersets removed from queue.
  [FULL ] [1, 165, 40, 4] -> Rank: 4/4 (Params: 6925)
    [Upward Pruned] 794 supersets removed from queue.
  [FULL ] [1, 54, 249, 4] -> Rank: 4/4 (Params: 14496)
    [Upward Pruned] 103 supersets removed from queue.
  [FULL ] [1, 12, 229, 4] -> Rank: 4/4 (Params: 3676)
    [Upward Pruned] 3063 supersets removed from queue.
  [FULL ] [1, 41, 26, 4] -> Rank: 4/4 (Params: 1211)
    [Upward Pruned] 8055 supersets removed from queue.
  [FULL ] [1, 78, 12, 4] -> Rank: 4/4 (Params: 1062)
    [Upward Pruned] 3121 supersets removed from queue.
  [FULL ] [1, 3, 186, 4] -> Rank: 4/4 (Params: 1305)
    [Upward Pruned] 2281 supersets removed from queue.
  [FULL ] [1, 41, 16, 4] -> Rank: 4/4 (Params: 761)
    [Upward Pruned] 369 supersets removed from queue.
  [FULL ] [1, 25, 163, 4] -> Rank: 4/4 (Params: 4752)
    [Upward Pruned] 367 supersets removed from queue.
  [FULL ] [1, 31, 65, 4] -> Rank: 4/4 (Params: 2306)
    [Upward Pruned] 979 supersets removed from queue.
  [FULL ] [1, 26, 36, 4] -> Rank: 4/4 (Params: 1106)
    [Upward Pruned] 924 supersets removed from queue.
  [FULL ] [1, 17, 127, 4] -> Rank: 4/4 (Params: 2684)
    [Upward Pruned] 507 supersets removed from queue.
  [FULL ] [1, 300, 7, 4] -> Rank: 4/4 (Params: 2428)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 17, 18, 4] -> Rank: 4/4 (Params: 395)
    [Upward Pruned] 1250 supersets removed from queue.
  [FULL ] [1, 9, 36, 4] -> Rank: 4/4 (Params: 477)
    [Upward Pruned] 1199 supersets removed from queue.
  [FULL ] [1, 4, 8, 4] -> Rank: 4/4 (Params: 68)
    [Upward Pruned] 2537 supersets removed from queue.
  [FULL ] [1, 70, 7, 4] -> Rank: 4/4 (Params: 588)
    [Upward Pruned] 229 supersets removed from queue.
  [FULL ] [1, 230, 2, 4] -> Rank: 4/4 (Params: 698)
    [Upward Pruned] 354 supersets removed from queue.
  [FULL ] [1, 34, 5, 4] -> Rank: 4/4 (Params: 224)
    [Upward Pruned] 427 supersets removed from queue.
  [FULL ] [1, 24, 3, 4] -> Rank: 4/4 (Params: 108)
    [Upward Pruned] 441 supersets removed from queue.
  [FULL ] [1, 20, 5, 4] -> Rank: 4/4 (Params: 140)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 153, 2, 4] -> Rank: 4/4 (Params: 467)
    [Upward Pruned] 76 supersets removed from queue.
  [FULL ] [1, 2, 116, 4] -> Rank: 4/4 (Params: 698)
    [Upward Pruned] 254 supersets removed from queue.
  [FULL ] [1, 20, 2, 4] -> Rank: 4/4 (Params: 68)
    [Upward Pruned] 140 supersets removed from queue.
  [FULL ] [1, 14, 5, 4] -> Rank: 4/4 (Params: 104)
    [Upward Pruned] 17 supersets removed from queue.
  [FULL ] [1, 3, 61, 4] -> Rank: 4/4 (Params: 430)
    [Upward Pruned] 54 supersets removed from queue.
  [FULL ] [1, 6, 5, 4] -> Rank: 4/4 (Params: 56)
    [Upward Pruned] 23 supersets removed from queue.
  [FULL ] [1, 2, 11, 4] -> Rank: 4/4 (Params: 68)
    [Upward Pruned] 154 supersets removed from queue.
  [FULL ] [1, 19, 2, 4] -> Rank: 4/4 (Params: 65)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 2, 9, 4] -> Rank: 4/4 (Params: 56)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 15, 3, 4] -> Rank: 4/4 (Params: 72)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 8, 3, 4] -> Rank: 4/4 (Params: 44)
    [Upward Pruned] 13 supersets removed from queue.
  [FULL ] [1, 4, 5, 4] -> Rank: 4/4 (Params: 44)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 18, 2, 4] -> Rank: 4/4 (Params: 62)
  [FULL ] [1, 2, 3, 4] -> Rank: 4/4 (Params: 20)
    [Upward Pruned] 19 supersets removed from queue.
  [FULL ] [1, 10, 2, 4] -> Rank: 4/4 (Params: 38)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 7, 2, 4] -> Rank: 4/4 (Params: 29)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 6, 2, 4] -> Rank: 4/4 (Params: 26)
  [FULL ] [1, 5, 2, 4] -> Rank: 4/4 (Params: 23)
  [FULL ] [1, 4, 2, 4] -> Rank: 4/4 (Params: 20)
  [FULL ] [1, 2, 2, 4] -> Rank: 4/4 (Params: 14)
    [Upward Pruned] 1 supersets removed from queue.

Added 47 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_4_r3_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=4 ---
  Target Ambient Dimension: 4
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 235, 4] -> Rank: 4/4 (Params: 1175)
    [Upward Pruned] 65 supersets removed from queue.
  [FULL ] [1, 219, 4] -> Rank: 4/4 (Params: 1095)
    [Upward Pruned] 15 supersets removed from queue.
  [FULL ] [1, 68, 4] -> Rank: 4/4 (Params: 340)
    [Upward Pruned] 150 supersets removed from queue.
  [FULL ] [1, 64, 4] -> Rank: 4/4 (Params: 320)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 10, 4] -> Rank: 4/4 (Params: 50)
    [Upward Pruned] 53 supersets removed from queue.
  [FULL ] [1, 2, 4] -> Rank: 4/4 (Params: 10)
    [Upward Pruned] 7 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=4 ---
  Target Ambient Dimension: 4
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 237, 138, 4] -> Rank: 4/4 (Params: 33495)
    [Upward Pruned] 10431 supersets removed from queue.
  [FULL ] [1, 245, 41, 4] -> Rank: 4/4 (Params: 10454)
    [Upward Pruned] 5431 supersets removed from queue.
  [FULL ] [1, 70, 298, 4] -> Rank: 4/4 (Params: 22122)
    [Upward Pruned] 500 supersets removed from queue.
  [FULL ] [1, 36, 96, 4] -> Rank: 4/4 (Params: 3876)
    [Upward Pruned] 41039 supersets removed from queue.
  [FULL ] [1, 156, 31, 4] -> Rank: 4/4 (Params: 5116)
    [Upward Pruned] 6344 supersets removed from queue.
  [FULL ] [1, 24, 70, 4] -> Rank: 4/4 (Params: 1984)
    [Upward Pruned] 5891 supersets removed from queue.
  [FULL ] [1, 146, 28, 4] -> Rank: 4/4 (Params: 4346)
    [Upward Pruned] 854 supersets removed from queue.
  [FULL ] [1, 275, 13, 4] -> Rank: 4/4 (Params: 3902)
    [Upward Pruned] 389 supersets removed from queue.
  [FULL ] [1, 94, 43, 4] -> Rank: 4/4 (Params: 4308)
    [Upward Pruned] 1403 supersets removed from queue.
  [FULL ] [1, 28, 52, 4] -> Rank: 4/4 (Params: 1692)
    [Upward Pruned] 1187 supersets removed from queue.
  [FULL ] [1, 186, 14, 4] -> Rank: 4/4 (Params: 2846)
    [Upward Pruned] 1245 supersets removed from queue.
  [FULL ] [1, 11, 10, 4] -> Rank: 4/4 (Params: 161)
    [Upward Pruned] 9664 supersets removed from queue.
  [FULL ] [1, 74, 9, 4] -> Rank: 4/4 (Params: 776)
    [Upward Pruned] 226 supersets removed from queue.
  [FULL ] [1, 6, 180, 4] -> Rank: 4/4 (Params: 1806)
    [Upward Pruned] 604 supersets removed from queue.
  [FULL ] [1, 7, 116, 4] -> Rank: 4/4 (Params: 1283)
    [Upward Pruned] 255 supersets removed from queue.
  [FULL ] [1, 8, 70, 4] -> Rank: 4/4 (Params: 848)
    [Upward Pruned] 137 supersets removed from queue.
  [FULL ] [1, 151, 2, 4] -> Rank: 4/4 (Params: 461)
    [Upward Pruned] 1049 supersets removed from queue.
  [FULL ] [1, 53, 4, 4] -> Rank: 4/4 (Params: 281)
    [Upward Pruned] 510 supersets removed from queue.
  [FULL ] [1, 3, 300, 4] -> Rank: 4/4 (Params: 2103)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 2, 273, 4] -> Rank: 4/4 (Params: 1640)
    [Upward Pruned] 108 supersets removed from queue.
  [FULL ] [1, 4, 173, 4] -> Rank: 4/4 (Params: 1388)
    [Upward Pruned] 206 supersets removed from queue.
  [FULL ] [1, 6, 151, 4] -> Rank: 4/4 (Params: 1516)
    [Upward Pruned] 21 supersets removed from queue.
  [FULL ] [1, 6, 148, 4] -> Rank: 4/4 (Params: 1486)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 3, 44, 4] -> Rank: 4/4 (Params: 311)
    [Upward Pruned] 740 supersets removed from queue.
  [FULL ] [1, 10, 29, 4] -> Rank: 4/4 (Params: 416)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 79, 3, 4] -> Rank: 4/4 (Params: 328)
    [Upward Pruned] 71 supersets removed from queue.
  [FULL ] [1, 24, 5, 4] -> Rank: 4/4 (Params: 164)
    [Upward Pruned] 144 supersets removed from queue.
  [FULL ] [1, 5, 22, 4] -> Rank: 4/4 (Params: 203)
    [Upward Pruned] 116 supersets removed from queue.
  [FULL ] [1, 3, 5, 4] -> Rank: 4/4 (Params: 38)
    [Upward Pruned] 244 supersets removed from queue.
  [FULL ] [1, 2, 88, 4] -> Rank: 4/4 (Params: 530)
    [Upward Pruned] 184 supersets removed from queue.
  [FULL ] [1, 2, 58, 4] -> Rank: 4/4 (Params: 350)
    [Upward Pruned] 29 supersets removed from queue.
  [FULL ] [1, 2, 12, 4] -> Rank: 4/4 (Params: 74)
    [Upward Pruned] 45 supersets removed from queue.
  [FULL ] [1, 126, 2, 4] -> Rank: 4/4 (Params: 386)
    [Upward Pruned] 24 supersets removed from queue.
  [FULL ] [1, 27, 4, 4] -> Rank: 4/4 (Params: 151)
    [Upward Pruned] 25 supersets removed from queue.
  [FULL ] [1, 100, 2, 4] -> Rank: 4/4 (Params: 308)
    [Upward Pruned] 25 supersets removed from queue.
  [FULL ] [1, 77, 2, 4] -> Rank: 4/4 (Params: 239)
    [Upward Pruned] 24 supersets removed from queue.
  [FULL ] [1, 21, 4, 4] -> Rank: 4/4 (Params: 121)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 11, 4, 4] -> Rank: 4/4 (Params: 71)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 33, 2, 4] -> Rank: 4/4 (Params: 107)
    [Upward Pruned] 87 supersets removed from queue.
  [FULL ] [1, 19, 2, 4] -> Rank: 4/4 (Params: 65)
    [Upward Pruned] 27 supersets removed from queue.
  [FULL ] [1, 2, 3, 4] -> Rank: 4/4 (Params: 20)
    [Upward Pruned] 32 supersets removed from queue.
  [FULL ] [1, 18, 2, 4] -> Rank: 4/4 (Params: 62)
  [FULL ] [1, 14, 2, 4] -> Rank: 4/4 (Params: 50)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 5, 2, 4] -> Rank: 4/4 (Params: 23)
    [Upward Pruned] 8 supersets removed from queue.
  [FULL ] [1, 2, 2, 4] -> Rank: 4/4 (Params: 14)
    [Upward Pruned] 2 supersets removed from queue.

Added 51 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_4_r4_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=5 ---
  Target Ambient Dimension: 4
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 166, 4] -> Rank: 4/4 (Params: 830)
    [Upward Pruned] 134 supersets removed from queue.
  [FULL ] [1, 50, 4] -> Rank: 4/4 (Params: 250)
    [Upward Pruned] 115 supersets removed from queue.
  [FULL ] [1, 12, 4] -> Rank: 4/4 (Params: 60)
    [Upward Pruned] 37 supersets removed from queue.
  [FULL ] [1, 7, 4] -> Rank: 4/4 (Params: 35)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 5, 4] -> Rank: 4/4 (Params: 25)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 4, 4] -> Rank: 4/4 (Params: 20)
  [FULL ] [1, 3, 4] -> Rank: 4/4 (Params: 15)
  [FULL ] [1, 2, 4] -> Rank: 4/4 (Params: 10)

--- RANDOM SEARCH: h=3, exponent=5 ---
  Target Ambient Dimension: 4
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 145, 130, 4] -> Rank: 4/4 (Params: 19515)
    [Upward Pruned] 26675 supersets removed from queue.
  [FULL ] [1, 80, 278, 4] -> Rank: 4/4 (Params: 23432)
    [Upward Pruned] 1494 supersets removed from queue.
  [FULL ] [1, 194, 79, 4] -> Rank: 4/4 (Params: 15836)
    [Upward Pruned] 5456 supersets removed from queue.
  [FULL ] [1, 44, 100, 4] -> Rank: 4/4 (Params: 4844)
    [Upward Pruned] 20275 supersets removed from queue.
  [FULL ] [1, 31, 21, 4] -> Rank: 4/4 (Params: 766)
    [Upward Pruned] 21695 supersets removed from queue.
  [FULL ] [1, 18, 174, 4] -> Rank: 4/4 (Params: 3846)
    [Upward Pruned] 1650 supersets removed from queue.
  [FULL ] [1, 12, 174, 4] -> Rank: 4/4 (Params: 2796)
    [Upward Pruned] 761 supersets removed from queue.
  [FULL ] [1, 108, 20, 4] -> Rank: 4/4 (Params: 2348)
    [Upward Pruned] 192 supersets removed from queue.
  [FULL ] [1, 130, 12, 4] -> Rank: 4/4 (Params: 1738)
    [Upward Pruned] 1367 supersets removed from queue.
  [FULL ] [1, 148, 10, 4] -> Rank: 4/4 (Params: 1668)
    [Upward Pruned] 305 supersets removed from queue.
  [FULL ] [1, 4, 6, 4] -> Rank: 4/4 (Params: 52)
    [Upward Pruned] 7734 supersets removed from queue.
  [FULL ] [1, 143, 3, 4] -> Rank: 4/4 (Params: 584)
    [Upward Pruned] 473 supersets removed from queue.
  [FULL ] [1, 2, 99, 4] -> Rank: 4/4 (Params: 596)
    [Upward Pruned] 403 supersets removed from queue.
  [FULL ] [1, 95, 4, 4] -> Rank: 4/4 (Params: 491)
    [Upward Pruned] 95 supersets removed from queue.
  [FULL ] [1, 2, 29, 4] -> Rank: 4/4 (Params: 176)
    [Upward Pruned] 139 supersets removed from queue.
  [FULL ] [1, 247, 2, 4] -> Rank: 4/4 (Params: 749)
    [Upward Pruned] 53 supersets removed from queue.
  [FULL ] [1, 144, 2, 4] -> Rank: 4/4 (Params: 440)
    [Upward Pruned] 102 supersets removed from queue.
  [FULL ] [1, 93, 5, 4] -> Rank: 4/4 (Params: 578)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 21, 3, 4] -> Rank: 4/4 (Params: 96)
    [Upward Pruned] 267 supersets removed from queue.
  [FULL ] [1, 13, 2, 4] -> Rank: 4/4 (Params: 47)
    [Upward Pruned] 154 supersets removed from queue.
  [FULL ] [1, 3, 24, 4] -> Rank: 4/4 (Params: 171)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 3, 12, 4] -> Rank: 4/4 (Params: 87)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 12, 2, 4] -> Rank: 4/4 (Params: 44)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 5, 3, 4] -> Rank: 4/4 (Params: 32)
    [Upward Pruned] 20 supersets removed from queue.
  [FULL ] [1, 2, 22, 4] -> Rank: 4/4 (Params: 134)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 11, 2, 4] -> Rank: 4/4 (Params: 41)
  [FULL ] [1, 3, 7, 4] -> Rank: 4/4 (Params: 52)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 3, 6, 4] -> Rank: 4/4 (Params: 45)
  [FULL ] [1, 2, 14, 4] -> Rank: 4/4 (Params: 86)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 2, 2, 4] -> Rank: 4/4 (Params: 14)
    [Upward Pruned] 25 supersets removed from queue.

Added 38 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_4_r5_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=6 ---
  Target Ambient Dimension: 4
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 189, 4] -> Rank: 4/4 (Params: 945)
    [Upward Pruned] 111 supersets removed from queue.
  [FULL ] [1, 155, 4] -> Rank: 4/4 (Params: 775)
    [Upward Pruned] 33 supersets removed from queue.
  [FULL ] [1, 123, 4] -> Rank: 4/4 (Params: 615)
    [Upward Pruned] 31 supersets removed from queue.
  [FULL ] [1, 38, 4] -> Rank: 4/4 (Params: 190)
    [Upward Pruned] 84 supersets removed from queue.
  [FULL ] [1, 8, 4] -> Rank: 4/4 (Params: 40)
    [Upward Pruned] 29 supersets removed from queue.
  [FULL ] [1, 5, 4] -> Rank: 4/4 (Params: 25)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 3, 4] -> Rank: 4/4 (Params: 15)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 4] -> Rank: 4/4 (Params: 10)

--- RANDOM SEARCH: h=3, exponent=6 ---
  Target Ambient Dimension: 4
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 35, 3, 4] -> Rank: 4/4 (Params: 152)
    [Upward Pruned] 79267 supersets removed from queue.
  [FULL ] [1, 177, 2, 4] -> Rank: 4/4 (Params: 539)
    [Upward Pruned] 123 supersets removed from queue.
  [FULL ] [1, 31, 118, 4] -> Rank: 4/4 (Params: 4161)
    [Upward Pruned] 731 supersets removed from queue.
  [FULL ] [1, 19, 266, 4] -> Rank: 4/4 (Params: 6137)
    [Upward Pruned] 419 supersets removed from queue.
  [FULL ] [1, 20, 176, 4] -> Rank: 4/4 (Params: 4244)
    [Upward Pruned] 989 supersets removed from queue.
  [FULL ] [1, 8, 145, 4] -> Rank: 4/4 (Params: 1748)
    [Upward Pruned] 2177 supersets removed from queue.
  [FULL ] [1, 19, 130, 4] -> Rank: 4/4 (Params: 3009)
    [Upward Pruned] 179 supersets removed from queue.
  [FULL ] [1, 22, 45, 4] -> Rank: 4/4 (Params: 1192)
    [Upward Pruned] 1056 supersets removed from queue.
  [FULL ] [1, 21, 123, 4] -> Rank: 4/4 (Params: 3096)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 7, 89, 4] -> Rank: 4/4 (Params: 986)
    [Upward Pruned] 943 supersets removed from queue.
  [FULL ] [1, 2, 262, 4] -> Rank: 4/4 (Params: 1574)
    [Upward Pruned] 194 supersets removed from queue.
  [FULL ] [1, 3, 50, 4] -> Rank: 4/4 (Params: 353)
    [Upward Pruned] 1432 supersets removed from queue.
  [FULL ] [1, 11, 47, 4] -> Rank: 4/4 (Params: 716)
    [Upward Pruned] 32 supersets removed from queue.
  [FULL ] [1, 23, 21, 4] -> Rank: 4/4 (Params: 590)
    [Upward Pruned] 287 supersets removed from queue.
  [FULL ] [1, 2, 203, 4] -> Rank: 4/4 (Params: 1220)
    [Upward Pruned] 58 supersets removed from queue.
  [FULL ] [1, 91, 2, 4] -> Rank: 4/4 (Params: 281)
    [Upward Pruned] 85 supersets removed from queue.
  [FULL ] [1, 31, 7, 4] -> Rank: 4/4 (Params: 276)
    [Upward Pruned] 55 supersets removed from queue.
  [FULL ] [1, 2, 111, 4] -> Rank: 4/4 (Params: 668)
    [Upward Pruned] 91 supersets removed from queue.
  [FULL ] [1, 3, 36, 4] -> Rank: 4/4 (Params: 255)
    [Upward Pruned] 241 supersets removed from queue.
  [FULL ] [1, 23, 4, 4] -> Rank: 4/4 (Params: 131)
    [Upward Pruned] 147 supersets removed from queue.
  [FULL ] [1, 2, 67, 4] -> Rank: 4/4 (Params: 404)
    [Upward Pruned] 43 supersets removed from queue.
  [FULL ] [1, 20, 3, 4] -> Rank: 4/4 (Params: 92)
    [Upward Pruned] 110 supersets removed from queue.
  [FULL ] [1, 3, 4, 4] -> Rank: 4/4 (Params: 31)
    [Upward Pruned] 543 supersets removed from queue.
  [FULL ] [1, 58, 2, 4] -> Rank: 4/4 (Params: 182)
    [Upward Pruned] 32 supersets removed from queue.
  [FULL ] [1, 2, 39, 4] -> Rank: 4/4 (Params: 236)
    [Upward Pruned] 27 supersets removed from queue.
  [FULL ] [1, 2, 3, 4] -> Rank: 4/4 (Params: 20)
    [Upward Pruned] 52 supersets removed from queue.
  [FULL ] [1, 17, 2, 4] -> Rank: 4/4 (Params: 59)
    [Upward Pruned] 40 supersets removed from queue.
  [FULL ] [1, 3, 2, 4] -> Rank: 4/4 (Params: 17)
    [Upward Pruned] 13 supersets removed from queue.
  [FULL ] [1, 2, 2, 4] -> Rank: 4/4 (Params: 14)

Added 37 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_4_r6_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=7 ---
  Target Ambient Dimension: 4
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 176, 4] -> Rank: 4/4 (Params: 880)
    [Upward Pruned] 124 supersets removed from queue.
  [FULL ] [1, 112, 4] -> Rank: 4/4 (Params: 560)
    [Upward Pruned] 63 supersets removed from queue.
  [FULL ] [1, 52, 4] -> Rank: 4/4 (Params: 260)
    [Upward Pruned] 59 supersets removed from queue.

  [FULL ] [1, 10, 4] -> Rank: 4/4 (Params: 50)
    [Upward Pruned] 41 supersets removed from queue.
  [FULL ] [1, 9, 4] -> Rank: 4/4 (Params: 45)
  [FULL ] [1, 7, 4] -> Rank: 4/4 (Params: 35)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 4, 4] -> Rank: 4/4 (Params: 20)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 2, 4] -> Rank: 4/4 (Params: 10)
    [Upward Pruned] 1 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=7 ---
  Target Ambient Dimension: 4
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 298, 109, 4] -> Rank: 4/4 (Params: 33216)
    [Upward Pruned] 575 supersets removed from queue.
  [FULL ] [1, 89, 230, 4] -> Rank: 4/4 (Params: 21479)
    [Upward Pruned] 14838 supersets removed from queue.
  [FULL ] [1, 89, 16, 4] -> Rank: 4/4 (Params: 1577)
    [Upward Pruned] 45004 supersets removed from queue.
  [FULL ] [1, 54, 6, 4] -> Rank: 4/4 (Params: 402)
    [Upward Pruned] 12444 supersets removed from queue.
  [FULL ] [1, 42, 278, 4] -> Rank: 4/4 (Params: 12830)
    [Upward Pruned] 275 supersets removed from queue.
  [FULL ] [1, 20, 300, 4] -> Rank: 4/4 (Params: 7220)
    [Upward Pruned] 21 supersets removed from queue.
  [FULL ] [1, 45, 170, 4] -> Rank: 4/4 (Params: 8375)
    [Upward Pruned] 971 supersets removed from queue.
  [FULL ] [1, 34, 246, 4] -> Rank: 4/4 (Params: 9382)
    [Upward Pruned] 527 supersets removed from queue.
  [FULL ] [1, 193, 3, 4] -> Rank: 4/4 (Params: 784)
    [Upward Pruned] 323 supersets removed from queue.
  [FULL ] [1, 16, 49, 4] -> Rank: 4/4 (Params: 996)
    [Upward Pruned] 7777 supersets removed from queue.
  [FULL ] [1, 2, 159, 4] -> Rank: 4/4 (Params: 956)
    [Upward Pruned] 1987 supersets removed from queue.
  [FULL ] [1, 11, 150, 4] -> Rank: 4/4 (Params: 2261)
    [Upward Pruned] 44 supersets removed from queue.
  [FULL ] [1, 2, 92, 4] -> Rank: 4/4 (Params: 554)
    [Upward Pruned] 892 supersets removed from queue.
  [FULL ] [1, 127, 3, 4] -> Rank: 4/4 (Params: 520)
    [Upward Pruned] 197 supersets removed from queue.
  [FULL ] [1, 6, 17, 4] -> Rank: 4/4 (Params: 176)
    [Upward Pruned] 1965 supersets removed from queue.
  [FULL ] [1, 25, 7, 4] -> Rank: 4/4 (Params: 228)
    [Upward Pruned] 289 supersets removed from queue.
  [FULL ] [1, 5, 12, 4] -> Rank: 4/4 (Params: 113)
    [Upward Pruned] 174 supersets removed from queue.
  [FULL ] [1, 6, 4, 4] -> Rank: 4/4 (Params: 46)
    [Upward Pruned] 384 supersets removed from queue.
  [FULL ] [1, 133, 2, 4] -> Rank: 4/4 (Params: 407)
    [Upward Pruned] 167 supersets removed from queue.
  [FULL ] [1, 41, 3, 4] -> Rank: 4/4 (Params: 176)
    [Upward Pruned] 85 supersets removed from queue.
  [FULL ] [1, 2, 26, 4] -> Rank: 4/4 (Params: 158)
    [Upward Pruned] 197 supersets removed from queue.
  [FULL ] [1, 31, 3, 4] -> Rank: 4/4 (Params: 136)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 4, 20, 4] -> Rank: 4/4 (Params: 164)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 5, 8, 4] -> Rank: 4/4 (Params: 77)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 57, 2, 4] -> Rank: 4/4 (Params: 179)
    [Upward Pruned] 75 supersets removed from queue.
  [FULL ] [1, 2, 2, 4] -> Rank: 4/4 (Params: 14)
    [Upward Pruned] 147 supersets removed from queue.

Added 34 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_4_r7_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=8 ---
  Target Ambient Dimension: 4
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 141, 4] -> Rank: 4/4 (Params: 705)
    [Upward Pruned] 159 supersets removed from queue.
  [FULL ] [1, 73, 4] -> Rank: 4/4 (Params: 365)
    [Upward Pruned] 67 supersets removed from queue.
  [FULL ] [1, 43, 4] -> Rank: 4/4 (Params: 215)
    [Upward Pruned] 29 supersets removed from queue.
  [FULL ] [1, 30, 4] -> Rank: 4/4 (Params: 150)
    [Upward Pruned] 12 supersets removed from queue.
  [FULL ] [1, 4, 4] -> Rank: 4/4 (Params: 20)
    [Upward Pruned] 25 supersets removed from queue.
  [FULL ] [1, 2, 4] -> Rank: 4/4 (Params: 10)
    [Upward Pruned] 1 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=8 ---
  Target Ambient Dimension: 4
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 11, 58, 4] -> Rank: 4/4 (Params: 881)
    [Upward Pruned] 70469 supersets removed from queue.
  [FULL ] [1, 63, 14, 4] -> Rank: 4/4 (Params: 1001)
    [Upward Pruned] 10471 supersets removed from queue.
  [FULL ] [1, 47, 14, 4] -> Rank: 4/4 (Params: 761)
    [Upward Pruned] 703 supersets removed from queue.
  [FULL ] [1, 29, 25, 4] -> Rank: 4/4 (Params: 854)
    [Upward Pruned] 593 supersets removed from queue.
  [FULL ] [1, 4, 242, 4] -> Rank: 4/4 (Params: 1940)
    [Upward Pruned] 412 supersets removed from queue.
  [FULL ] [1, 178, 2, 4] -> Rank: 4/4 (Params: 542)
    [Upward Pruned] 1475 supersets removed from queue.
  [FULL ] [1, 9, 171, 4] -> Rank: 4/4 (Params: 2232)
    [Upward Pruned] 141 supersets removed from queue.
  [FULL ] [1, 113, 4, 4] -> Rank: 4/4 (Params: 581)
    [Upward Pruned] 649 supersets removed from queue.
  [FULL ] [1, 40, 5, 4] -> Rank: 4/4 (Params: 260)
    [Upward Pruned] 733 supersets removed from queue.
  [FULL ] [1, 3, 227, 4] -> Rank: 4/4 (Params: 1592)
    [Upward Pruned] 148 supersets removed from queue.
  [FULL ] [1, 172, 2, 4] -> Rank: 4/4 (Params: 524)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 27, 37, 4] -> Rank: 4/4 (Params: 1174)
    [Upward Pruned] 41 supersets removed from queue.
  [FULL ] [1, 3, 176, 4] -> Rank: 4/4 (Params: 1235)
    [Upward Pruned] 305 supersets removed from queue.
  [FULL ] [1, 39, 13, 4] -> Rank: 4/4 (Params: 598)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 6, 49, 4] -> Rank: 4/4 (Params: 496)
    [Upward Pruned] 768 supersets removed from queue.
  [FULL ] [1, 26, 8, 4] -> Rank: 4/4 (Params: 266)
    [Upward Pruned] 273 supersets removed from queue.
  [FULL ] [1, 5, 21, 4] -> Rank: 4/4 (Params: 194)
    [Upward Pruned] 714 supersets removed from queue.
  [FULL ] [1, 128, 2, 4] -> Rank: 4/4 (Params: 392)
    [Upward Pruned] 87 supersets removed from queue.
  [FULL ] [1, 2, 22, 4] -> Rank: 4/4 (Params: 134)
    [Upward Pruned] 586 supersets removed from queue.
  [FULL ] [1, 15, 17, 4] -> Rank: 4/4 (Params: 338)
    [Upward Pruned] 43 supersets removed from queue.
  [FULL ] [1, 5, 12, 4] -> Rank: 4/4 (Params: 113)
    [Upward Pruned] 144 supersets removed from queue.
  [FULL ] [1, 15, 5, 4] -> Rank: 4/4 (Params: 110)
    [Upward Pruned] 118 supersets removed from queue.
  [FULL ] [1, 48, 4, 4] -> Rank: 4/4 (Params: 256)
    [Upward Pruned] 64 supersets removed from queue.
  [FULL ] [1, 97, 3, 4] -> Rank: 4/4 (Params: 400)
    [Upward Pruned] 30 supersets removed from queue.
  [FULL ] [1, 74, 2, 4] -> Rank: 4/4 (Params: 230)
    [Upward Pruned] 76 supersets removed from queue.
  [FULL ] [1, 3, 15, 4] -> Rank: 4/4 (Params: 108)
    [Upward Pruned] 13 supersets removed from queue.
  [FULL ] [1, 67, 2, 4] -> Rank: 4/4 (Params: 209)
    [Upward Pruned] 13 supersets removed from queue.
  [FULL ] [1, 2, 12, 4] -> Rank: 4/4 (Params: 74)
    [Upward Pruned] 15 supersets removed from queue.
  [FULL ] [1, 7, 3, 4] -> Rank: 4/4 (Params: 40)
    [Upward Pruned] 156 supersets removed from queue.
  [FULL ] [1, 2, 7, 4] -> Rank: 4/4 (Params: 44)
    [Upward Pruned] 24 supersets removed from queue.
  [FULL ] [1, 13, 2, 4] -> Rank: 4/4 (Params: 47)
    [Upward Pruned] 53 supersets removed from queue.
  [FULL ] [1, 5, 2, 4] -> Rank: 4/4 (Params: 23)
    [Upward Pruned] 15 supersets removed from queue.
  [FULL ] [1, 2, 2, 4] -> Rank: 4/4 (Params: 14)
    [Upward Pruned] 14 supersets removed from queue.

Added 39 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_4_r8_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=9 ---
  Target Ambient Dimension: 4
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 70, 4] -> Rank: 4/4 (Params: 350)
    [Upward Pruned] 230 supersets removed from queue.
  [FULL ] [1, 9, 4] -> Rank: 4/4 (Params: 45)
    [Upward Pruned] 60 supersets removed from queue.
  [FULL ] [1, 5, 4] -> Rank: 4/4 (Params: 25)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 4, 4] -> Rank: 4/4 (Params: 20)
  [FULL ] [1, 2, 4] -> Rank: 4/4 (Params: 10)
    [Upward Pruned] 1 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=9 ---
  Target Ambient Dimension: 4
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 34, 294, 4] -> Rank: 4/4 (Params: 11206)
    [Upward Pruned] 1868 supersets removed from queue.
  [FULL ] [1, 120, 72, 4] -> Rank: 4/4 (Params: 9048)
    [Upward Pruned] 40181 supersets removed from queue.
  [FULL ] [1, 174, 32, 4] -> Rank: 4/4 (Params: 5870)
    [Upward Pruned] 5079 supersets removed from queue.
  [FULL ] [1, 172, 11, 4] -> Rank: 4/4 (Params: 2108)
    [Upward Pruned] 2788 supersets removed from queue.
  [FULL ] [1, 62, 41, 4] -> Rank: 4/4 (Params: 2768)
    [Upward Pruned] 16285 supersets removed from queue.
  [FULL ] [1, 24, 247, 4] -> Rank: 4/4 (Params: 6940)
    [Upward Pruned] 1855 supersets removed from queue.
  [FULL ] [1, 60, 58, 4] -> Rank: 4/4 (Params: 3772)
    [Upward Pruned] 377 supersets removed from queue.
  [FULL ] [1, 25, 125, 4] -> Rank: 4/4 (Params: 3650)
    [Upward Pruned] 4269 supersets removed from queue.
  [FULL ] [1, 9, 78, 4] -> Rank: 4/4 (Params: 1023)
    [Upward Pruned] 5158 supersets removed from queue.
  [FULL ] [1, 216, 3, 4] -> Rank: 4/4 (Params: 876)
    [Upward Pruned] 679 supersets removed from queue.
  [FULL ] [1, 56, 61, 4] -> Rank: 4/4 (Params: 3716)
    [Upward Pruned] 67 supersets removed from queue.
  [FULL ] [1, 7, 129, 4] -> Rank: 4/4 (Params: 1426)
    [Upward Pruned] 343 supersets removed from queue.
  [FULL ] [1, 2, 294, 4] -> Rank: 4/4 (Params: 1766)
    [Upward Pruned] 34 supersets removed from queue.
  [FULL ] [1, 3, 202, 4] -> Rank: 4/4 (Params: 1417)
    [Upward Pruned] 367 supersets removed from queue.
  [FULL ] [1, 37, 68, 4] -> Rank: 4/4 (Params: 2825)
    [Upward Pruned] 189 supersets removed from queue.
  [FULL ] [1, 26, 73, 4] -> Rank: 4/4 (Params: 2216)
    [Upward Pruned] 54 supersets removed from queue.
  [FULL ] [1, 117, 27, 4] -> Rank: 4/4 (Params: 3384)
    [Upward Pruned] 769 supersets removed from queue.
  [FULL ] [1, 90, 10, 4] -> Rank: 4/4 (Params: 1030)
    [Upward Pruned] 1815 supersets removed from queue.
  [FULL ] [1, 69, 32, 4] -> Rank: 4/4 (Params: 2405)
    [Upward Pruned] 188 supersets removed from queue.
  [FULL ] [1, 291, 2, 4] -> Rank: 4/4 (Params: 881)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 38, 56, 4] -> Rank: 4/4 (Params: 2390)
    [Upward Pruned] 239 supersets removed from queue.
  [FULL ] [1, 132, 3, 4] -> Rank: 4/4 (Params: 540)
    [Upward Pruned] 587 supersets removed from queue.
  [FULL ] [1, 56, 20, 4] -> Rank: 4/4 (Params: 1256)
    [Upward Pruned] 614 supersets removed from queue.
  [FULL ] [1, 73, 7, 4] -> Rank: 4/4 (Params: 612)
    [Upward Pruned] 346 supersets removed from queue.
  [FULL ] [1, 16, 59, 4] -> Rank: 4/4 (Params: 1196)
    [Upward Pruned] 352 supersets removed from queue.
  [FULL ] [1, 4, 35, 4] -> Rank: 4/4 (Params: 284)
    [Upward Pruned] 1895 supersets removed from queue.
  [FULL ] [1, 53, 8, 4] -> Rank: 4/4 (Params: 509)
    [Upward Pruned] 284 supersets removed from queue.
  [FULL ] [1, 84, 4, 4] -> Rank: 4/4 (Params: 436)
    [Upward Pruned] 143 supersets removed from queue.
  [FULL ] [1, 3, 21, 4] -> Rank: 4/4 (Params: 150)
    [Upward Pruned] 866 supersets removed from queue.
  [FULL ] [1, 15, 14, 4] -> Rank: 4/4 (Params: 281)
    [Upward Pruned] 265 supersets removed from queue.
  [FULL ] [1, 6, 15, 4] -> Rank: 4/4 (Params: 156)
    [Upward Pruned] 53 supersets removed from queue.
  [FULL ] [1, 39, 10, 4] -> Rank: 4/4 (Params: 469)
    [Upward Pruned] 55 supersets removed from queue.
  [FULL ] [1, 119, 3, 4] -> Rank: 4/4 (Params: 488)
    [Upward Pruned] 12 supersets removed from queue.
  [FULL ] [1, 2, 23, 4] -> Rank: 4/4 (Params: 140)
    [Upward Pruned] 270 supersets removed from queue.
  [FULL ] [1, 41, 4, 4] -> Rank: 4/4 (Params: 221)
    [Upward Pruned] 184 supersets removed from queue.
  [FULL ] [1, 30, 8, 4] -> Rank: 4/4 (Params: 302)
    [Upward Pruned] 57 supersets removed from queue.
  [FULL ] [1, 29, 10, 4] -> Rank: 4/4 (Params: 359)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 151, 2, 4] -> Rank: 4/4 (Params: 461)
    [Upward Pruned] 139 supersets removed from queue.
  [FULL ] [1, 5, 17, 4] -> Rank: 4/4 (Params: 158)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 87, 3, 4] -> Rank: 4/4 (Params: 360)
    [Upward Pruned] 31 supersets removed from queue.
  [FULL ] [1, 39, 2, 4] -> Rank: 4/4 (Params: 125)
    [Upward Pruned] 167 supersets removed from queue.
  [FULL ] [1, 3, 16, 4] -> Rank: 4/4 (Params: 115)
    [Upward Pruned] 10 supersets removed from queue.
  [FULL ] [1, 24, 5, 4] -> Rank: 4/4 (Params: 164)
    [Upward Pruned] 76 supersets removed from queue.
  [FULL ] [1, 12, 10, 4] -> Rank: 4/4 (Params: 172)
    [Upward Pruned] 50 supersets removed from queue.
  [FULL ] [1, 8, 4, 4] -> Rank: 4/4 (Params: 56)
    [Upward Pruned] 130 supersets removed from queue.
  [FULL ] [1, 4, 9, 4] -> Rank: 4/4 (Params: 76)
    [Upward Pruned] 25 supersets removed from queue.
  [FULL ] [1, 4, 3, 4] -> Rank: 4/4 (Params: 28)
    [Upward Pruned] 54 supersets removed from queue.
  [FULL ] [1, 36, 2, 4] -> Rank: 4/4 (Params: 116)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 2, 17, 4] -> Rank: 4/4 (Params: 104)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 17, 2, 4] -> Rank: 4/4 (Params: 59)
    [Upward Pruned] 18 supersets removed from queue.
  [FULL ] [1, 11, 2, 4] -> Rank: 4/4 (Params: 41)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 3, 7, 4] -> Rank: 4/4 (Params: 52)
    [Upward Pruned] 8 supersets removed from queue.
  [FULL ] [1, 3, 5, 4] -> Rank: 4/4 (Params: 38)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 3, 2, 4] -> Rank: 4/4 (Params: 17)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 2, 12, 4] -> Rank: 4/4 (Params: 74)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 2, 2, 4] -> Rank: 4/4 (Params: 14)
    [Upward Pruned] 9 supersets removed from queue.

Added 61 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_4_r9_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=1 ---
  Target Ambient Dimension: 5
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.

  [FULL ] [1, 277, 5] -> Rank: 5/5 (Params: 1662)
    [Upward Pruned] 23 supersets removed from queue.
  [FULL ] [1, 205, 5] -> Rank: 5/5 (Params: 1230)
    [Upward Pruned] 71 supersets removed from queue.
  [FULL ] [1, 127, 5] -> Rank: 5/5 (Params: 762)
    [Upward Pruned] 77 supersets removed from queue.
  [FULL ] [1, 78, 5] -> Rank: 5/5 (Params: 468)
    [Upward Pruned] 48 supersets removed from queue.
  [FULL ] [1, 50, 5] -> Rank: 5/5 (Params: 300)
    [Upward Pruned] 27 supersets removed from queue.
  [FULL ] [1, 26, 5] -> Rank: 5/5 (Params: 156)
    [Upward Pruned] 23 supersets removed from queue.
  [FULL ] [1, 25, 5] -> Rank: 5/5 (Params: 150)
  [FULL ] [1, 8, 5] -> Rank: 5/5 (Params: 48)
    [Upward Pruned] 16 supersets removed from queue.
  [FULL ] [1, 3, 5] -> Rank: 5/5 (Params: 18)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 2, 5] -> Rank: 5/5 (Params: 12)

--- RANDOM SEARCH: h=3, exponent=1 ---
  Target Ambient Dimension: 5
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 93, 221, 5] -> Rank: 5/5 (Params: 21751)
    [Upward Pruned] 16639 supersets removed from queue.
  [FULL ] [1, 206, 30, 5] -> Rank: 5/5 (Params: 6536)
    [Upward Pruned] 18144 supersets removed from queue.
  [FULL ] [1, 89, 245, 5] -> Rank: 5/5 (Params: 23119)
    [Upward Pruned] 223 supersets removed from queue.
  [FULL ] [1, 10, 90, 5] -> Rank: 5/5 (Params: 1360)
    [Upward Pruned] 32091 supersets removed from queue.
  [FULL ] [1, 124, 27, 5] -> Rank: 5/5 (Params: 3607)
    [Upward Pruned] 5450 supersets removed from queue.
  [FULL ] [1, 132, 26, 5] -> Rank: 5/5 (Params: 3694)
    [Upward Pruned] 168 supersets removed from queue.
  [FULL ] [1, 25, 50, 5] -> Rank: 5/5 (Params: 1525)
    [Upward Pruned] 3959 supersets removed from queue.
  [FULL ] [1, 218, 15, 5] -> Rank: 5/5 (Params: 3563)
    [Upward Pruned] 912 supersets removed from queue.
  [FULL ] [1, 5, 283, 5] -> Rank: 5/5 (Params: 2835)
    [Upward Pruned] 89 supersets removed from queue.
  [FULL ] [1, 7, 228, 5] -> Rank: 5/5 (Params: 2743)
    [Upward Pruned] 164 supersets removed from queue.
  [FULL ] [1, 109, 5, 5] -> Rank: 5/5 (Params: 679)
    [Upward Pruned] 3486 supersets removed from queue.
  [FULL ] [1, 3, 31, 5] -> Rank: 5/5 (Params: 251)
    [Upward Pruned] 4115 supersets removed from queue.
  [FULL ] [1, 38, 17, 5] -> Rank: 5/5 (Params: 769)
    [Upward Pruned] 993 supersets removed from queue.
  [FULL ] [1, 47, 15, 5] -> Rank: 5/5 (Params: 827)
    [Upward Pruned] 123 supersets removed from queue.
  [FULL ] [1, 97, 9, 5] -> Rank: 5/5 (Params: 1015)
    [Upward Pruned] 71 supersets removed from queue.
  [FULL ] [1, 15, 9, 5] -> Rank: 5/5 (Params: 195)
    [Upward Pruned] 877 supersets removed from queue.
  [FULL ] [1, 14, 15, 5] -> Rank: 5/5 (Params: 299)
    [Upward Pruned] 15 supersets removed from queue.
  [FULL ] [1, 297, 3, 5] -> Rank: 5/5 (Params: 1203)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 140, 3, 5] -> Rank: 5/5 (Params: 575)
    [Upward Pruned] 313 supersets removed from queue.
  [FULL ] [1, 62, 5, 5] -> Rank: 5/5 (Params: 397)
    [Upward Pruned] 187 supersets removed from queue.
  [FULL ] [1, 56, 8, 5] -> Rank: 5/5 (Params: 544)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 150, 2, 5] -> Rank: 5/5 (Params: 460)
    [Upward Pruned] 150 supersets removed from queue.
  [FULL ] [1, 2, 78, 5] -> Rank: 5/5 (Params: 548)
    [Upward Pruned] 222 supersets removed from queue.
  [FULL ] [1, 14, 14, 5] -> Rank: 5/5 (Params: 280)
  [FULL ] [1, 56, 3, 5] -> Rank: 5/5 (Params: 239)
    [Upward Pruned] 185 supersets removed from queue.
  [FULL ] [1, 104, 2, 5] -> Rank: 5/5 (Params: 322)
    [Upward Pruned] 45 supersets removed from queue.
  [FULL ] [1, 6, 26, 5] -> Rank: 5/5 (Params: 292)
    [Upward Pruned] 39 supersets removed from queue.
  [FULL ] [1, 6, 5, 5] -> Rank: 5/5 (Params: 61)
    [Upward Pruned] 340 supersets removed from queue.
  [FULL ] [1, 88, 2, 5] -> Rank: 5/5 (Params: 274)
    [Upward Pruned] 15 supersets removed from queue.
  [FULL ] [1, 2, 36, 5] -> Rank: 5/5 (Params: 254)
    [Upward Pruned] 41 supersets removed from queue.
  [FULL ] [1, 7, 3, 5] -> Rank: 5/5 (Params: 43)
    [Upward Pruned] 97 supersets removed from queue.
  [FULL ] [1, 2, 15, 5] -> Rank: 5/5 (Params: 107)
    [Upward Pruned] 68 supersets removed from queue.
  [FULL ] [1, 53, 2, 5] -> Rank: 5/5 (Params: 169)
    [Upward Pruned] 34 supersets removed from queue.
  [FULL ] [1, 28, 2, 5] -> Rank: 5/5 (Params: 94)
    [Upward Pruned] 24 supersets removed from queue.
  [FULL ] [1, 19, 2, 5] -> Rank: 5/5 (Params: 67)
    [Upward Pruned] 8 supersets removed from queue.
  [FULL ] [1, 3, 13, 5] -> Rank: 5/5 (Params: 107)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 2, 8, 5] -> Rank: 5/5 (Params: 58)
    [Upward Pruned] 21 supersets removed from queue.
  [FULL ] [1, 3, 5, 5] -> Rank: 5/5 (Params: 43)
    [Upward Pruned] 8 supersets removed from queue.
  [FULL ] [1, 17, 2, 5] -> Rank: 5/5 (Params: 61)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 9, 2, 5] -> Rank: 5/5 (Params: 37)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 6, 2, 5] -> Rank: 5/5 (Params: 28)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 5, 2, 5] -> Rank: 5/5 (Params: 25)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 2, 4, 5] -> Rank: 5/5 (Params: 30)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 3, 2, 5] -> Rank: 5/5 (Params: 19)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 2, 3, 5] -> Rank: 5/5 (Params: 23)
  [FULL ] [1, 2, 2, 5] -> Rank: 5/5 (Params: 16)

Added 56 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_5_r1_architectures.csv'.

Loading existing database from '../data/raw/1_5_r2_architectures.csv'...

--- RANDOM SEARCH: h=2, exponent=2 ---
  Target Ambient Dimension: 5
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 292 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.

--- RANDOM SEARCH: h=3, exponent=2 ---
  Target Ambient Dimension: 5
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 89356 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_5_r2_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=3 ---
  Target Ambient Dimension: 5
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 188, 5] -> Rank: 5/5 (Params: 1128)
    [Upward Pruned] 112 supersets removed from queue.
  [FULL ] [1, 123, 5] -> Rank: 5/5 (Params: 738)
    [Upward Pruned] 64 supersets removed from queue.
  [FULL ] [1, 88, 5] -> Rank: 5/5 (Params: 528)
    [Upward Pruned] 34 supersets removed from queue.
  [FULL ] [1, 48, 5] -> Rank: 5/5 (Params: 288)
    [Upward Pruned] 39 supersets removed from queue.
  [FULL ] [1, 20, 5] -> Rank: 5/5 (Params: 120)
    [Upward Pruned] 27 supersets removed from queue.
  [FULL ] [1, 5, 5] -> Rank: 5/5 (Params: 30)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 2, 5] -> Rank: 5/5 (Params: 12)
    [Upward Pruned] 2 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=3 ---
  Target Ambient Dimension: 5
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 273, 207, 5] -> Rank: 5/5 (Params: 57819)
    [Upward Pruned] 2631 supersets removed from queue.
  [FULL ] [1, 79, 222, 5] -> Rank: 5/5 (Params: 18727)
    [Upward Pruned] 15325 supersets removed from queue.
  [FULL ] [1, 263, 5, 5] -> Rank: 5/5 (Params: 1603)
    [Upward Pruned] 7825 supersets removed from queue.
  [FULL ] [1, 164, 34, 5] -> Rank: 5/5 (Params: 5910)
    [Upward Pruned] 18611 supersets removed from queue.
  [FULL ] [1, 52, 108, 5] -> Rank: 5/5 (Params: 6208)
    [Upward Pruned] 14900 supersets removed from queue.
  [FULL ] [1, 119, 78, 5] -> Rank: 5/5 (Params: 9791)
    [Upward Pruned] 1349 supersets removed from queue.
  [FULL ] [1, 35, 51, 5] -> Rank: 5/5 (Params: 2075)
    [Upward Pruned] 9283 supersets removed from queue.
  [FULL ] [1, 12, 109, 5] -> Rank: 5/5 (Params: 1865)
    [Upward Pruned] 4415 supersets removed from queue.
  [FULL ] [1, 18, 70, 5] -> Rank: 5/5 (Params: 1628)
    [Upward Pruned] 662 supersets removed from queue.
  [FULL ] [1, 202, 21, 5] -> Rank: 5/5 (Params: 4549)
    [Upward Pruned] 792 supersets removed from queue.
  [FULL ] [1, 4, 265, 5] -> Rank: 5/5 (Params: 2389)
    [Upward Pruned] 287 supersets removed from queue.
  [FULL ] [1, 26, 22, 5] -> Rank: 5/5 (Params: 708)
    [Upward Pruned] 4628 supersets removed from queue.
  [FULL ] [1, 157, 9, 5] -> Rank: 5/5 (Params: 1615)
    [Upward Pruned] 1316 supersets removed from queue.
  [FULL ] [1, 8, 176, 5] -> Rank: 5/5 (Params: 2296)
    [Upward Pruned] 355 supersets removed from queue.
  [FULL ] [1, 15, 67, 5] -> Rank: 5/5 (Params: 1355)
    [Upward Pruned] 149 supersets removed from queue.
  [FULL ] [1, 4, 256, 5] -> Rank: 5/5 (Params: 2308)
    [Upward Pruned] 35 supersets removed from queue.
  [FULL ] [1, 133, 16, 5] -> Rank: 5/5 (Params: 2341)
    [Upward Pruned] 143 supersets removed from queue.
  [FULL ] [1, 65, 17, 5] -> Rank: 5/5 (Params: 1255)
    [Upward Pruned] 339 supersets removed from queue.
  [FULL ] [1, 7, 57, 5] -> Rank: 5/5 (Params: 691)
    [Upward Pruned] 940 supersets removed from queue.
  [FULL ] [1, 8, 10, 5] -> Rank: 5/5 (Params: 138)
    [Upward Pruned] 1933 supersets removed from queue.
  [FULL ] [1, 298, 3, 5] -> Rank: 5/5 (Params: 1207)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 139, 8, 5] -> Rank: 5/5 (Params: 1291)
    [Upward Pruned] 141 supersets removed from queue.
  [FULL ] [1, 82, 4, 5] -> Rank: 5/5 (Params: 430)
    [Upward Pruned] 872 supersets removed from queue.
  [FULL ] [1, 3, 230, 5] -> Rank: 5/5 (Params: 1843)
    [Upward Pruned] 148 supersets removed from queue.
  [FULL ] [1, 2, 262, 5] -> Rank: 5/5 (Params: 1836)
    [Upward Pruned] 38 supersets removed from queue.
  [FULL ] [1, 7, 53, 5] -> Rank: 5/5 (Params: 643)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 29, 7, 5] -> Rank: 5/5 (Params: 267)
    [Upward Pruned] 158 supersets removed from queue.
  [FULL ] [1, 4, 122, 5] -> Rank: 5/5 (Params: 1102)
    [Upward Pruned] 323 supersets removed from queue.
  [FULL ] [1, 3, 80, 5] -> Rank: 5/5 (Params: 643)
    [Upward Pruned] 275 supersets removed from queue.
  [FULL ] [1, 6, 19, 5] -> Rank: 5/5 (Params: 215)
    [Upward Pruned] 94 supersets removed from queue.
  [FULL ] [1, 201, 2, 5] -> Rank: 5/5 (Params: 613)
    [Upward Pruned] 196 supersets removed from queue.
  [FULL ] [1, 29, 4, 5] -> Rank: 5/5 (Params: 165)
    [Upward Pruned] 158 supersets removed from queue.
  [FULL ] [1, 132, 3, 5] -> Rank: 5/5 (Params: 543)
    [Upward Pruned] 68 supersets removed from queue.
  [FULL ] [1, 20, 5, 5] -> Rank: 5/5 (Params: 145)
    [Upward Pruned] 44 supersets removed from queue.
  [FULL ] [1, 2, 164, 5] -> Rank: 5/5 (Params: 1150)
    [Upward Pruned] 97 supersets removed from queue.
  [FULL ] [1, 10, 8, 5] -> Rank: 5/5 (Params: 130)
    [Upward Pruned] 19 supersets removed from queue.
  [FULL ] [1, 3, 70, 5] -> Rank: 5/5 (Params: 563)
    [Upward Pruned] 29 supersets removed from queue.
  [FULL ] [1, 4, 5, 5] -> Rank: 5/5 (Params: 49)
    [Upward Pruned] 197 supersets removed from queue.
  [FULL ] [1, 32, 2, 5] -> Rank: 5/5 (Params: 106)
    [Upward Pruned] 268 supersets removed from queue.
  [FULL ] [1, 2, 115, 5] -> Rank: 5/5 (Params: 807)
    [Upward Pruned] 48 supersets removed from queue.
  [FULL ] [1, 2, 110, 5] -> Rank: 5/5 (Params: 772)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 2, 102, 5] -> Rank: 5/5 (Params: 716)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 25, 2, 5] -> Rank: 5/5 (Params: 85)
    [Upward Pruned] 17 supersets removed from queue.
  [FULL ] [1, 11, 3, 5] -> Rank: 5/5 (Params: 59)
    [Upward Pruned] 27 supersets removed from queue.
  [FULL ] [1, 3, 34, 5] -> Rank: 5/5 (Params: 275)
    [Upward Pruned] 35 supersets removed from queue.
  [FULL ] [1, 7, 3, 5] -> Rank: 5/5 (Params: 43)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 2, 95, 5] -> Rank: 5/5 (Params: 667)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 7, 2, 5] -> Rank: 5/5 (Params: 31)
    [Upward Pruned] 17 supersets removed from queue.
  [FULL ] [1, 3, 19, 5] -> Rank: 5/5 (Params: 155)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 3, 17, 5] -> Rank: 5/5 (Params: 139)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 39, 5] -> Rank: 5/5 (Params: 275)
    [Upward Pruned] 55 supersets removed from queue.
  [FULL ] [1, 2, 31, 5] -> Rank: 5/5 (Params: 219)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 2, 13, 5] -> Rank: 5/5 (Params: 93)
    [Upward Pruned] 21 supersets removed from queue.
  [FULL ] [1, 2, 3, 5] -> Rank: 5/5 (Params: 23)
    [Upward Pruned] 25 supersets removed from queue.
  [FULL ] [1, 2, 2, 5] -> Rank: 5/5 (Params: 16)
    [Upward Pruned] 4 supersets removed from queue.

Added 62 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_5_r3_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=4 ---
  Target Ambient Dimension: 5
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 224, 5] -> Rank: 5/5 (Params: 1344)
    [Upward Pruned] 76 supersets removed from queue.
  [FULL ] [1, 12, 5] -> Rank: 5/5 (Params: 72)
    [Upward Pruned] 211 supersets removed from queue.
  [FULL ] [1, 3, 5] -> Rank: 5/5 (Params: 18)
    [Upward Pruned] 8 supersets removed from queue.
  [FULL ] [1, 2, 5] -> Rank: 5/5 (Params: 12)

--- RANDOM SEARCH: h=3, exponent=4 ---
  Target Ambient Dimension: 5
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 85, 91, 5] -> Rank: 5/5 (Params: 8275)
    [Upward Pruned] 45359 supersets removed from queue.
  [FULL ] [1, 17, 2, 5] -> Rank: 5/5 (Params: 61)
    [Upward Pruned] 39555 supersets removed from queue.
  [FULL ] [1, 16, 42, 5] -> Rank: 5/5 (Params: 898)
    [Upward Pruned] 258 supersets removed from queue.
  [FULL ] [1, 14, 27, 5] -> Rank: 5/5 (Params: 527)
    [Upward Pruned] 562 supersets removed from queue.
  [FULL ] [1, 8, 214, 5] -> Rank: 5/5 (Params: 2790)
    [Upward Pruned] 521 supersets removed from queue.
  [FULL ] [1, 7, 175, 5] -> Rank: 5/5 (Params: 2107)
    [Upward Pruned] 359 supersets removed from queue.
  [FULL ] [1, 13, 110, 5] -> Rank: 5/5 (Params: 1993)
    [Upward Pruned] 64 supersets removed from queue.
  [FULL ] [1, 6, 126, 5] -> Rank: 5/5 (Params: 1392)
    [Upward Pruned] 468 supersets removed from queue.
  [FULL ] [1, 5, 197, 5] -> Rank: 5/5 (Params: 1975)
    [Upward Pruned] 103 supersets removed from queue.
  [FULL ] [1, 6, 60, 5] -> Rank: 5/5 (Params: 666)
    [Upward Pruned] 511 supersets removed from queue.
  [FULL ] [1, 4, 169, 5] -> Rank: 5/5 (Params: 1525)
    [Upward Pruned] 159 supersets removed from queue.
  [FULL ] [1, 2, 115, 5] -> Rank: 5/5 (Params: 807)
    [Upward Pruned] 479 supersets removed from queue.
  [FULL ] [1, 10, 34, 5] -> Rank: 5/5 (Params: 520)
    [Upward Pruned] 103 supersets removed from queue.
  [FULL ] [1, 13, 8, 5] -> Rank: 5/5 (Params: 157)
    [Upward Pruned] 82 supersets removed from queue.
  [FULL ] [1, 4, 4, 5] -> Rank: 5/5 (Params: 40)
    [Upward Pruned] 551 supersets removed from queue.
  [FULL ] [1, 3, 68, 5] -> Rank: 5/5 (Params: 547)
    [Upward Pruned] 46 supersets removed from queue.
  [FULL ] [1, 2, 88, 5] -> Rank: 5/5 (Params: 618)
    [Upward Pruned] 26 supersets removed from queue.
  [FULL ] [1, 3, 37, 5] -> Rank: 5/5 (Params: 299)
    [Upward Pruned] 30 supersets removed from queue.
  [FULL ] [1, 2, 35, 5] -> Rank: 5/5 (Params: 247)
    [Upward Pruned] 54 supersets removed from queue.
  [FULL ] [1, 3, 3, 5] -> Rank: 5/5 (Params: 27)
    [Upward Pruned] 44 supersets removed from queue.
  [FULL ] [1, 2, 13, 5] -> Rank: 5/5 (Params: 93)
    [Upward Pruned] 21 supersets removed from queue.
  [FULL ] [1, 2, 4, 5] -> Rank: 5/5 (Params: 30)
    [Upward Pruned] 8 supersets removed from queue.
  [FULL ] [1, 4, 2, 5] -> Rank: 5/5 (Params: 22)
    [Upward Pruned] 12 supersets removed from queue.
  [FULL ] [1, 2, 2, 5] -> Rank: 5/5 (Params: 16)
    [Upward Pruned] 2 supersets removed from queue.

Added 28 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_5_r4_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=5 ---
  Target Ambient Dimension: 5
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 153, 5] -> Rank: 5/5 (Params: 918)
    [Upward Pruned] 147 supersets removed from queue.
  [FULL ] [1, 107, 5] -> Rank: 5/5 (Params: 642)
    [Upward Pruned] 45 supersets removed from queue.
  [FULL ] [1, 74, 5] -> Rank: 5/5 (Params: 444)
    [Upward Pruned] 32 supersets removed from queue.
  [FULL ] [1, 34, 5] -> Rank: 5/5 (Params: 204)
    [Upward Pruned] 39 supersets removed from queue.
  [FULL ] [1, 12, 5] -> Rank: 5/5 (Params: 72)
    [Upward Pruned] 21 supersets removed from queue.
  [FULL ] [1, 7, 5] -> Rank: 5/5 (Params: 42)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 6, 5] -> Rank: 5/5 (Params: 36)

  [FULL ] [1, 4, 5] -> Rank: 5/5 (Params: 24)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 5] -> Rank: 5/5 (Params: 12)
    [Upward Pruned] 1 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=5 ---
  Target Ambient Dimension: 5
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 284, 178, 5] -> Rank: 5/5 (Params: 51726)
    [Upward Pruned] 2090 supersets removed from queue.
  [FULL ] [1, 272, 109, 5] -> Rank: 5/5 (Params: 30465)
    [Upward Pruned] 3476 supersets removed from queue.
  [FULL ] [1, 153, 109, 5] -> Rank: 5/5 (Params: 17375)
    [Upward Pruned] 22847 supersets removed from queue.
  [FULL ] [1, 201, 28, 5] -> Rank: 5/5 (Params: 5969)
    [Upward Pruned] 8099 supersets removed from queue.
  [FULL ] [1, 19, 138, 5] -> Rank: 5/5 (Params: 3331)
    [Upward Pruned] 21841 supersets removed from queue.
  [FULL ] [1, 157, 106, 5] -> Rank: 5/5 (Params: 17329)
    [Upward Pruned] 131 supersets removed from queue.
  [FULL ] [1, 137, 20, 5] -> Rank: 5/5 (Params: 2977)
    [Upward Pruned] 6827 supersets removed from queue.
  [FULL ] [1, 92, 91, 5] -> Rank: 5/5 (Params: 8919)
    [Upward Pruned] 2114 supersets removed from queue.
  [FULL ] [1, 103, 7, 5] -> Rank: 5/5 (Params: 859)
    [Upward Pruned] 4987 supersets removed from queue.
  [FULL ] [1, 11, 123, 5] -> Rank: 5/5 (Params: 1979)
    [Upward Pruned] 2518 supersets removed from queue.
  [FULL ] [1, 86, 68, 5] -> Rank: 5/5 (Params: 6274)
    [Upward Pruned] 582 supersets removed from queue.
  [FULL ] [1, 12, 67, 5] -> Rank: 5/5 (Params: 1151)
    [Upward Pruned] 4160 supersets removed from queue.
  [FULL ] [1, 25, 59, 5] -> Rank: 5/5 (Params: 1795)
    [Upward Pruned] 623 supersets removed from queue.
  [FULL ] [1, 30, 7, 5] -> Rank: 5/5 (Params: 275)
    [Upward Pruned] 3795 supersets removed from queue.
  [FULL ] [1, 19, 41, 5] -> Rank: 5/5 (Params: 1003)
    [Upward Pruned] 245 supersets removed from queue.
  [FULL ] [1, 7, 2, 5] -> Rank: 5/5 (Params: 31)
    [Upward Pruned] 3555 supersets removed from queue.
  [FULL ] [1, 2, 105, 5] -> Rank: 5/5 (Params: 737)
    [Upward Pruned] 979 supersets removed from queue.
  [FULL ] [1, 3, 36, 5] -> Rank: 5/5 (Params: 291)
    [Upward Pruned] 275 supersets removed from queue.
  [FULL ] [1, 3, 13, 5] -> Rank: 5/5 (Params: 107)
    [Upward Pruned] 91 supersets removed from queue.
  [FULL ] [1, 2, 88, 5] -> Rank: 5/5 (Params: 618)
    [Upward Pruned] 16 supersets removed from queue.
  [FULL ] [1, 2, 71, 5] -> Rank: 5/5 (Params: 499)
    [Upward Pruned] 16 supersets removed from queue.
  [FULL ] [1, 3, 11, 5] -> Rank: 5/5 (Params: 91)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 4, 4, 5] -> Rank: 5/5 (Params: 40)
    [Upward Pruned] 20 supersets removed from queue.
  [FULL ] [1, 2, 45, 5] -> Rank: 5/5 (Params: 317)
    [Upward Pruned] 25 supersets removed from queue.
  [FULL ] [1, 2, 9, 5] -> Rank: 5/5 (Params: 65)
    [Upward Pruned] 37 supersets removed from queue.
  [FULL ] [1, 4, 2, 5] -> Rank: 5/5 (Params: 22)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 2, 6, 5] -> Rank: 5/5 (Params: 44)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 3, 3, 5] -> Rank: 5/5 (Params: 27)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 3, 2, 5] -> Rank: 5/5 (Params: 19)
  [FULL ] [1, 2, 5, 5] -> Rank: 5/5 (Params: 37)
  [FULL ] [1, 2, 2, 5] -> Rank: 5/5 (Params: 16)
    [Upward Pruned] 2 supersets removed from queue.

Added 40 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_5_r5_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=6 ---
  Target Ambient Dimension: 5
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 107, 5] -> Rank: 5/5 (Params: 642)
    [Upward Pruned] 193 supersets removed from queue.
  [FULL ] [1, 99, 5] -> Rank: 5/5 (Params: 594)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 93, 5] -> Rank: 5/5 (Params: 558)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 75, 5] -> Rank: 5/5 (Params: 450)
    [Upward Pruned] 17 supersets removed from queue.
  [FULL ] [1, 51, 5] -> Rank: 5/5 (Params: 306)
    [Upward Pruned] 23 supersets removed from queue.
  [FULL ] [1, 44, 5] -> Rank: 5/5 (Params: 264)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 38, 5] -> Rank: 5/5 (Params: 228)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 11, 5] -> Rank: 5/5 (Params: 66)
    [Upward Pruned] 26 supersets removed from queue.
  [FULL ] [1, 4, 5] -> Rank: 5/5 (Params: 24)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 2, 5] -> Rank: 5/5 (Params: 12)
    [Upward Pruned] 1 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=6 ---
  Target Ambient Dimension: 5
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 27, 167, 5] -> Rank: 5/5 (Params: 5371)
    [Upward Pruned] 36715 supersets removed from queue.
  [FULL ] [1, 119, 105, 5] -> Rank: 5/5 (Params: 13139)
    [Upward Pruned] 11283 supersets removed from queue.
  [FULL ] [1, 34, 152, 5] -> Rank: 5/5 (Params: 5962)
    [Upward Pruned] 1274 supersets removed from queue.
  [FULL ] [1, 106, 84, 5] -> Rank: 5/5 (Params: 9430)
    [Upward Pruned] 4705 supersets removed from queue.
  [FULL ] [1, 173, 56, 5] -> Rank: 5/5 (Params: 10141)
    [Upward Pruned] 3583 supersets removed from queue.
  [FULL ] [1, 9, 241, 5] -> Rank: 5/5 (Params: 3383)
    [Upward Pruned] 1079 supersets removed from queue.
  [FULL ] [1, 139, 42, 5] -> Rank: 5/5 (Params: 6187)
    [Upward Pruned] 3219 supersets removed from queue.
  [FULL ] [1, 12, 11, 5] -> Rank: 5/5 (Params: 199)
    [Upward Pruned] 22124 supersets removed from queue.
  [FULL ] [1, 2, 51, 5] -> Rank: 5/5 (Params: 359)
    [Upward Pruned] 2319 supersets removed from queue.
  [FULL ] [1, 241, 7, 5] -> Rank: 5/5 (Params: 1963)
    [Upward Pruned] 239 supersets removed from queue.
  [FULL ] [1, 155, 2, 5] -> Rank: 5/5 (Params: 475)
    [Upward Pruned] 1073 supersets removed from queue.
  [FULL ] [1, 5, 35, 5] -> Rank: 5/5 (Params: 355)
    [Upward Pruned] 111 supersets removed from queue.
  [FULL ] [1, 68, 5, 5] -> Rank: 5/5 (Params: 433)
    [Upward Pruned] 521 supersets removed from queue.
  [FULL ] [1, 61, 6, 5] -> Rank: 5/5 (Params: 457)
    [Upward Pruned] 34 supersets removed from queue.
  [FULL ] [1, 105, 3, 5] -> Rank: 5/5 (Params: 435)
    [Upward Pruned] 99 supersets removed from queue.
  [FULL ] [1, 42, 2, 5] -> Rank: 5/5 (Params: 136)
    [Upward Pruned] 359 supersets removed from queue.
  [FULL ] [1, 8, 13, 5] -> Rank: 5/5 (Params: 177)
    [Upward Pruned] 87 supersets removed from queue.
  [FULL ] [1, 4, 49, 5] -> Rank: 5/5 (Params: 445)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 7, 3, 5] -> Rank: 5/5 (Params: 43)
    [Upward Pruned] 311 supersets removed from queue.
  [FULL ] [1, 3, 4, 5] -> Rank: 5/5 (Params: 35)
    [Upward Pruned] 153 supersets removed from queue.
  [FULL ] [1, 2, 15, 5] -> Rank: 5/5 (Params: 107)
    [Upward Pruned] 35 supersets removed from queue.
  [FULL ] [1, 24, 2, 5] -> Rank: 5/5 (Params: 82)
    [Upward Pruned] 17 supersets removed from queue.
  [FULL ] [1, 2, 13, 5] -> Rank: 5/5 (Params: 93)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 23, 2, 5] -> Rank: 5/5 (Params: 79)
  [FULL ] [1, 7, 2, 5] -> Rank: 5/5 (Params: 31)
    [Upward Pruned] 15 supersets removed from queue.
  [FULL ] [1, 4, 3, 5] -> Rank: 5/5 (Params: 31)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 3, 3, 5] -> Rank: 5/5 (Params: 27)
  [FULL ] [1, 2, 10, 5] -> Rank: 5/5 (Params: 72)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 4, 2, 5] -> Rank: 5/5 (Params: 22)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 3, 2, 5] -> Rank: 5/5 (Params: 19)
  [FULL ] [1, 2, 4, 5] -> Rank: 5/5 (Params: 30)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 2, 3, 5] -> Rank: 5/5 (Params: 23)
  [FULL ] [1, 2, 2, 5] -> Rank: 5/5 (Params: 16)

Added 43 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_5_r6_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=7 ---
  Target Ambient Dimension: 5
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 230, 5] -> Rank: 5/5 (Params: 1380)
    [Upward Pruned] 70 supersets removed from queue.
  [FULL ] [1, 41, 5] -> Rank: 5/5 (Params: 246)
    [Upward Pruned] 188 supersets removed from queue.
  [FULL ] [1, 35, 5] -> Rank: 5/5 (Params: 210)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 10, 5] -> Rank: 5/5 (Params: 60)
    [Upward Pruned] 24 supersets removed from queue.
  [FULL ] [1, 3, 5] -> Rank: 5/5 (Params: 18)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 2, 5] -> Rank: 5/5 (Params: 12)

--- RANDOM SEARCH: h=3, exponent=7 ---
  Target Ambient Dimension: 5
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 165, 135, 5] -> Rank: 5/5 (Params: 23115)
    [Upward Pruned] 22575 supersets removed from queue.
  [FULL ] [1, 263, 34, 5] -> Rank: 5/5 (Params: 9375)
    [Upward Pruned] 3837 supersets removed from queue.
  [FULL ] [1, 107, 19, 5] -> Rank: 5/5 (Params: 2235)
    [Upward Pruned] 28293 supersets removed from queue.
  [FULL ] [1, 76, 13, 5] -> Rank: 5/5 (Params: 1129)
    [Upward Pruned] 10091 supersets removed from queue.
  [FULL ] [1, 11, 263, 5] -> Rank: 5/5 (Params: 4219)
    [Upward Pruned] 2469 supersets removed from queue.
  [FULL ] [1, 55, 240, 5] -> Rank: 5/5 (Params: 14455)
    [Upward Pruned] 482 supersets removed from queue.
  [FULL ] [1, 58, 113, 5] -> Rank: 5/5 (Params: 7177)
    [Upward Pruned] 2285 supersets removed from queue.
  [FULL ] [1, 24, 240, 5] -> Rank: 5/5 (Params: 6984)
    [Upward Pruned] 712 supersets removed from queue.
  [FULL ] [1, 50, 99, 5] -> Rank: 5/5 (Params: 5495)
    [Upward Pruned] 1379 supersets removed from queue.
  [FULL ] [1, 33, 22, 5] -> Rank: 5/5 (Params: 869)
    [Upward Pruned] 5707 supersets removed from queue.
  [FULL ] [1, 4, 18, 5] -> Rank: 5/5 (Params: 166)
    [Upward Pruned] 7335 supersets removed from queue.
  [FULL ] [1, 2, 205, 5] -> Rank: 5/5 (Params: 1437)
    [Upward Pruned] 191 supersets removed from queue.
  [FULL ] [1, 157, 4, 5] -> Rank: 5/5 (Params: 805)
    [Upward Pruned] 1295 supersets removed from queue.
  [FULL ] [1, 156, 12, 5] -> Rank: 5/5 (Params: 2088)
  [FULL ] [1, 28, 14, 5] -> Rank: 5/5 (Params: 490)
    [Upward Pruned] 191 supersets removed from queue.
  [FULL ] [1, 101, 2, 5] -> Rank: 5/5 (Params: 313)
    [Upward Pruned] 902 supersets removed from queue.
  [FULL ] [1, 3, 92, 5] -> Rank: 5/5 (Params: 739)
    [Upward Pruned] 112 supersets removed from queue.
  [FULL ] [1, 44, 7, 5] -> Rank: 5/5 (Params: 387)
    [Upward Pruned] 373 supersets removed from queue.
  [FULL ] [1, 38, 7, 5] -> Rank: 5/5 (Params: 339)
    [Upward Pruned] 41 supersets removed from queue.
  [FULL ] [1, 3, 90, 5] -> Rank: 5/5 (Params: 723)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 108, 5] -> Rank: 5/5 (Params: 758)
    [Upward Pruned] 96 supersets removed from queue.
  [FULL ] [1, 48, 5, 5] -> Rank: 5/5 (Params: 313)
    [Upward Pruned] 105 supersets removed from queue.
  [FULL ] [1, 60, 3, 5] -> Rank: 5/5 (Params: 255)
    [Upward Pruned] 81 supersets removed from queue.
  [FULL ] [1, 2, 103, 5] -> Rank: 5/5 (Params: 723)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 5, 11, 5] -> Rank: 5/5 (Params: 115)
    [Upward Pruned] 190 supersets removed from queue.
  [FULL ] [1, 25, 3, 5] -> Rank: 5/5 (Params: 115)
    [Upward Pruned] 167 supersets removed from queue.
  [FULL ] [1, 18, 8, 5] -> Rank: 5/5 (Params: 202)
    [Upward Pruned] 20 supersets removed from queue.
  [FULL ] [1, 3, 64, 5] -> Rank: 5/5 (Params: 515)
    [Upward Pruned] 25 supersets removed from queue.
  [FULL ] [1, 3, 23, 5] -> Rank: 5/5 (Params: 187)
    [Upward Pruned] 40 supersets removed from queue.
  [FULL ] [1, 2, 3, 5] -> Rank: 5/5 (Params: 23)
    [Upward Pruned] 273 supersets removed from queue.
  [FULL ] [1, 57, 2, 5] -> Rank: 5/5 (Params: 181)
    [Upward Pruned] 43 supersets removed from queue.
  [FULL ] [1, 11, 2, 5] -> Rank: 5/5 (Params: 43)
    [Upward Pruned] 45 supersets removed from queue.
  [FULL ] [1, 9, 2, 5] -> Rank: 5/5 (Params: 37)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 8, 2, 5] -> Rank: 5/5 (Params: 34)
  [FULL ] [1, 6, 2, 5] -> Rank: 5/5 (Params: 28)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 2, 5] -> Rank: 5/5 (Params: 16)
    [Upward Pruned] 3 supersets removed from queue.

Added 42 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_5_r7_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=8 ---
  Target Ambient Dimension: 5
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 192, 5] -> Rank: 5/5 (Params: 1152)
    [Upward Pruned] 108 supersets removed from queue.
  [FULL ] [1, 132, 5] -> Rank: 5/5 (Params: 792)
    [Upward Pruned] 59 supersets removed from queue.
  [FULL ] [1, 37, 5] -> Rank: 5/5 (Params: 222)
    [Upward Pruned] 94 supersets removed from queue.
  [FULL ] [1, 18, 5] -> Rank: 5/5 (Params: 108)
    [Upward Pruned] 18 supersets removed from queue.
  [FULL ] [1, 11, 5] -> Rank: 5/5 (Params: 66)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 10, 5] -> Rank: 5/5 (Params: 60)

  [FULL ] [1, 2, 5] -> Rank: 5/5 (Params: 12)
    [Upward Pruned] 7 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=8 ---
  Target Ambient Dimension: 5
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 101, 72, 5] -> Rank: 5/5 (Params: 7733)
    [Upward Pruned] 45799 supersets removed from queue.
  [FULL ] [1, 72, 84, 5] -> Rank: 5/5 (Params: 6540)
    [Upward Pruned] 6292 supersets removed from queue.
  [FULL ] [1, 22, 42, 5] -> Rank: 5/5 (Params: 1156)
    [Upward Pruned] 20167 supersets removed from queue.
  [FULL ] [1, 73, 17, 5] -> Rank: 5/5 (Params: 1399)
    [Upward Pruned] 5699 supersets removed from queue.
  [FULL ] [1, 57, 3, 5] -> Rank: 5/5 (Params: 243)
    [Upward Pruned] 3815 supersets removed from queue.
  [FULL ] [1, 14, 41, 5] -> Rank: 5/5 (Params: 793)
    [Upward Pruned] 2114 supersets removed from queue.
  [FULL ] [1, 13, 228, 5] -> Rank: 5/5 (Params: 4117)
    [Upward Pruned] 72 supersets removed from queue.
  [FULL ] [1, 48, 9, 5] -> Rank: 5/5 (Params: 525)
    [Upward Pruned] 287 supersets removed from queue.
  [FULL ] [1, 12, 20, 5] -> Rank: 5/5 (Params: 352)
    [Upward Pruned] 1202 supersets removed from queue.
  [FULL ] [1, 11, 135, 5] -> Rank: 5/5 (Params: 2171)
    [Upward Pruned] 165 supersets removed from queue.
  [FULL ] [1, 6, 217, 5] -> Rank: 5/5 (Params: 2393)
    [Upward Pruned] 419 supersets removed from queue.
  [FULL ] [1, 136, 2, 5] -> Rank: 5/5 (Params: 418)
    [Upward Pruned] 164 supersets removed from queue.
  [FULL ] [1, 7, 67, 5] -> Rank: 5/5 (Params: 811)
    [Upward Pruned] 667 supersets removed from queue.
  [FULL ] [1, 8, 42, 5] -> Rank: 5/5 (Params: 554)
    [Upward Pruned] 99 supersets removed from queue.
  [FULL ] [1, 3, 76, 5] -> Rank: 5/5 (Params: 611)
    [Upward Pruned] 815 supersets removed from queue.
  [FULL ] [1, 19, 6, 5] -> Rank: 5/5 (Params: 163)
    [Upward Pruned] 432 supersets removed from queue.
  [FULL ] [1, 4, 6, 5] -> Rank: 5/5 (Params: 58)
    [Upward Pruned] 512 supersets removed from queue.
  [FULL ] [1, 2, 277, 5] -> Rank: 5/5 (Params: 1941)
    [Upward Pruned] 23 supersets removed from queue.
  [FULL ] [1, 2, 229, 5] -> Rank: 5/5 (Params: 1605)
    [Upward Pruned] 47 supersets removed from queue.
  [FULL ] [1, 2, 121, 5] -> Rank: 5/5 (Params: 849)
    [Upward Pruned] 107 supersets removed from queue.
  [FULL ] [1, 6, 3, 5] -> Rank: 5/5 (Params: 39)
    [Upward Pruned] 152 supersets removed from queue.
  [FULL ] [1, 3, 25, 5] -> Rank: 5/5 (Params: 203)
    [Upward Pruned] 50 supersets removed from queue.
  [FULL ] [1, 3, 2, 5] -> Rank: 5/5 (Params: 19)
    [Upward Pruned] 160 supersets removed from queue.
  [FULL ] [1, 2, 45, 5] -> Rank: 5/5 (Params: 317)
    [Upward Pruned] 75 supersets removed from queue.
  [FULL ] [1, 2, 42, 5] -> Rank: 5/5 (Params: 296)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 2, 5, 5] -> Rank: 5/5 (Params: 37)
    [Upward Pruned] 36 supersets removed from queue.
  [FULL ] [1, 2, 3, 5] -> Rank: 5/5 (Params: 23)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 2, 5] -> Rank: 5/5 (Params: 16)

Added 35 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_5_r8_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=9 ---
  Target Ambient Dimension: 5
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 153, 5] -> Rank: 5/5 (Params: 918)
    [Upward Pruned] 147 supersets removed from queue.
  [FULL ] [1, 70, 5] -> Rank: 5/5 (Params: 420)
    [Upward Pruned] 82 supersets removed from queue.
  [FULL ] [1, 36, 5] -> Rank: 5/5 (Params: 216)
    [Upward Pruned] 33 supersets removed from queue.
  [FULL ] [1, 13, 5] -> Rank: 5/5 (Params: 78)
    [Upward Pruned] 22 supersets removed from queue.
  [FULL ] [1, 2, 5] -> Rank: 5/5 (Params: 12)
    [Upward Pruned] 10 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=9 ---
  Target Ambient Dimension: 5
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 150, 146, 5] -> Rank: 5/5 (Params: 22780)
    [Upward Pruned] 23404 supersets removed from queue.
  [FULL ] [1, 125, 181, 5] -> Rank: 5/5 (Params: 23655)
    [Upward Pruned] 2999 supersets removed from queue.
  [FULL ] [1, 6, 298, 5] -> Rank: 5/5 (Params: 3284)
    [Upward Pruned] 356 supersets removed from queue.
  [FULL ] [1, 188, 78, 5] -> Rank: 5/5 (Params: 15242)
    [Upward Pruned] 7683 supersets removed from queue.
  [FULL ] [1, 221, 66, 5] -> Rank: 5/5 (Params: 15137)
    [Upward Pruned] 959 supersets removed from queue.
  [FULL ] [1, 270, 30, 5] -> Rank: 5/5 (Params: 8520)
    [Upward Pruned] 1115 supersets removed from queue.
  [FULL ] [1, 186, 33, 5] -> Rank: 5/5 (Params: 6489)
    [Upward Pruned] 3327 supersets removed from queue.
  [FULL ] [1, 61, 230, 5] -> Rank: 5/5 (Params: 15241)
    [Upward Pruned] 4351 supersets removed from queue.
  [FULL ] [1, 44, 130, 5] -> Rank: 5/5 (Params: 6414)
    [Upward Pruned] 11106 supersets removed from queue.
  [FULL ] [1, 13, 290, 5] -> Rank: 5/5 (Params: 5233)
    [Upward Pruned] 247 supersets removed from queue.
  [FULL ] [1, 257, 22, 5] -> Rank: 5/5 (Params: 6021)
    [Upward Pruned] 390 supersets removed from queue.
  [FULL ] [1, 9, 191, 5] -> Rank: 5/5 (Params: 2683)
    [Upward Pruned] 3496 supersets removed from queue.
  [FULL ] [1, 231, 25, 5] -> Rank: 5/5 (Params: 6131)
    [Upward Pruned] 207 supersets removed from queue.
  [FULL ] [1, 21, 85, 5] -> Rank: 5/5 (Params: 2231)
    [Upward Pruned] 8827 supersets removed from queue.
  [FULL ] [1, 12, 44, 5] -> Rank: 5/5 (Params: 760)
    [Upward Pruned] 8087 supersets removed from queue.
  [FULL ] [1, 180, 23, 5] -> Rank: 5/5 (Params: 4435)
    [Upward Pruned] 627 supersets removed from queue.
  [FULL ] [1, 59, 8, 5] -> Rank: 5/5 (Params: 571)
    [Upward Pruned] 6126 supersets removed from queue.
  [FULL ] [1, 134, 5, 5] -> Rank: 5/5 (Params: 829)
    [Upward Pruned] 500 supersets removed from queue.
  [FULL ] [1, 251, 2, 5] -> Rank: 5/5 (Params: 763)
    [Upward Pruned] 149 supersets removed from queue.
  [FULL ] [1, 11, 102, 5] -> Rank: 5/5 (Params: 1643)
    [Upward Pruned] 88 supersets removed from queue.
  [FULL ] [1, 2, 226, 5] -> Rank: 5/5 (Params: 1584)
    [Upward Pruned] 515 supersets removed from queue.
  [FULL ] [1, 32, 11, 5] -> Rank: 5/5 (Params: 439)
    [Upward Pruned] 890 supersets removed from queue.
  [FULL ] [1, 6, 52, 5] -> Rank: 5/5 (Params: 578)
    [Upward Pruned] 849 supersets removed from queue.
  [FULL ] [1, 174, 2, 5] -> Rank: 5/5 (Params: 532)
    [Upward Pruned] 230 supersets removed from queue.
  [FULL ] [1, 4, 98, 5] -> Rank: 5/5 (Params: 886)
    [Upward Pruned] 255 supersets removed from queue.
  [FULL ] [1, 97, 7, 5] -> Rank: 5/5 (Params: 811)
    [Upward Pruned] 36 supersets removed from queue.
  [FULL ] [1, 114, 2, 5] -> Rank: 5/5 (Params: 352)
    [Upward Pruned] 219 supersets removed from queue.
  [FULL ] [1, 54, 8, 5] -> Rank: 5/5 (Params: 526)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 16, 34, 5] -> Rank: 5/5 (Params: 730)
    [Upward Pruned] 159 supersets removed from queue.
  [FULL ] [1, 4, 7, 5] -> Rank: 5/5 (Params: 67)
    [Upward Pruned] 1162 supersets removed from queue.
  [FULL ] [1, 3, 200, 5] -> Rank: 5/5 (Params: 1603)
    [Upward Pruned] 25 supersets removed from queue.
  [FULL ] [1, 109, 4, 5] -> Rank: 5/5 (Params: 565)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 3, 112, 5] -> Rank: 5/5 (Params: 899)
    [Upward Pruned] 87 supersets removed from queue.
  [FULL ] [1, 44, 3, 5] -> Rank: 5/5 (Params: 191)
    [Upward Pruned] 264 supersets removed from queue.
  [FULL ] [1, 2, 177, 5] -> Rank: 5/5 (Params: 1241)
    [Upward Pruned] 48 supersets removed from queue.
  [FULL ] [1, 20, 6, 5] -> Rank: 5/5 (Params: 170)
    [Upward Pruned] 23 supersets removed from queue.
  [FULL ] [1, 3, 109, 5] -> Rank: 5/5 (Params: 875)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 25, 2, 5] -> Rank: 5/5 (Params: 85)
    [Upward Pruned] 145 supersets removed from queue.
  [FULL ] [1, 3, 26, 5] -> Rank: 5/5 (Params: 211)
    [Upward Pruned] 82 supersets removed from queue.
  [FULL ] [1, 2, 135, 5] -> Rank: 5/5 (Params: 947)
    [Upward Pruned] 41 supersets removed from queue.
  [FULL ] [1, 2, 134, 5] -> Rank: 5/5 (Params: 940)
  [FULL ] [1, 3, 24, 5] -> Rank: 5/5 (Params: 195)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 96, 5] -> Rank: 5/5 (Params: 674)
    [Upward Pruned] 37 supersets removed from queue.
  [FULL ] [1, 2, 41, 5] -> Rank: 5/5 (Params: 289)
    [Upward Pruned] 54 supersets removed from queue.
  [FULL ] [1, 5, 3, 5] -> Rank: 5/5 (Params: 35)
    [Upward Pruned] 74 supersets removed from queue.
  [FULL ] [1, 2, 3, 5] -> Rank: 5/5 (Params: 23)
    [Upward Pruned] 62 supersets removed from queue.
  [FULL ] [1, 22, 2, 5] -> Rank: 5/5 (Params: 76)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 7, 2, 5] -> Rank: 5/5 (Params: 31)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 5, 2, 5] -> Rank: 5/5 (Params: 25)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 3, 2, 5] -> Rank: 5/5 (Params: 19)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 2, 5] -> Rank: 5/5 (Params: 16)

Added 56 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_5_r9_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=1 ---
  Target Ambient Dimension: 6
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 25, 6] -> Rank: 6/6 (Params: 175)
    [Upward Pruned] 275 supersets removed from queue.
  [FULL ] [1, 23, 6] -> Rank: 6/6 (Params: 161)
    [Upward Pruned] 1 supersets removed from queue.

  [FULL ] [1, 17, 6] -> Rank: 6/6 (Params: 119)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 6, 6] -> Rank: 6/6 (Params: 42)
    [Upward Pruned] 10 supersets removed from queue.
  [FULL ] [1, 5, 6] -> Rank: 6/6 (Params: 35)
  [FULL ] [1, 2, 6] -> Rank: 6/6 (Params: 14)
    [Upward Pruned] 2 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=1 ---
  Target Ambient Dimension: 6
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 5, 114, 6] -> Rank: 6/6 (Params: 1259)
    [Upward Pruned] 55351 supersets removed from queue.
  [FULL ] [1, 71, 19, 6] -> Rank: 6/6 (Params: 1534)
    [Upward Pruned] 21849 supersets removed from queue.
  [FULL ] [1, 4, 55, 6] -> Rank: 6/6 (Params: 554)
    [Upward Pruned] 4139 supersets removed from queue.
  [FULL ] [1, 54, 5, 6] -> Rank: 6/6 (Params: 354)
    [Upward Pruned] 4069 supersets removed from queue.
  [FULL ] [1, 25, 20, 6] -> Rank: 6/6 (Params: 645)
    [Upward Pruned] 1014 supersets removed from queue.
  [FULL ] [1, 5, 47, 6] -> Rank: 6/6 (Params: 522)
    [Upward Pruned] 159 supersets removed from queue.
  [FULL ] [1, 17, 4, 6] -> Rank: 6/6 (Params: 109)
    [Upward Pruned] 1054 supersets removed from queue.
  [FULL ] [1, 95, 2, 6] -> Rank: 6/6 (Params: 297)
    [Upward Pruned] 411 supersets removed from queue.
  [FULL ] [1, 3, 69, 6] -> Rank: 6/6 (Params: 624)
    [Upward Pruned] 231 supersets removed from queue.
  [FULL ] [1, 8, 23, 6] -> Rank: 6/6 (Params: 330)
    [Upward Pruned] 215 supersets removed from queue.
  [FULL ] [1, 10, 12, 6] -> Rank: 6/6 (Params: 202)
    [Upward Pruned] 76 supersets removed from queue.
  [FULL ] [1, 2, 151, 6] -> Rank: 6/6 (Params: 1210)
    [Upward Pruned] 149 supersets removed from queue.
  [FULL ] [1, 4, 18, 6] -> Rank: 6/6 (Params: 184)
    [Upward Pruned] 133 supersets removed from queue.
  [FULL ] [1, 2, 21, 6] -> Rank: 6/6 (Params: 170)
    [Upward Pruned] 177 supersets removed from queue.
  [FULL ] [1, 6, 4, 6] -> Rank: 6/6 (Params: 54)
    [Upward Pruned] 111 supersets removed from queue.
  [FULL ] [1, 10, 2, 6] -> Rank: 6/6 (Params: 42)
    [Upward Pruned] 169 supersets removed from queue.
  [FULL ] [1, 5, 2, 6] -> Rank: 6/6 (Params: 27)
    [Upward Pruned] 23 supersets removed from queue.
  [FULL ] [1, 4, 3, 6] -> Rank: 6/6 (Params: 34)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 3, 15, 6] -> Rank: 6/6 (Params: 138)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 3, 2, 6] -> Rank: 6/6 (Params: 21)
    [Upward Pruned] 13 supersets removed from queue.
  [FULL ] [1, 2, 14, 6] -> Rank: 6/6 (Params: 114)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 2, 9, 6] -> Rank: 6/6 (Params: 74)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 2, 6, 6] -> Rank: 6/6 (Params: 50)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 2, 4, 6] -> Rank: 6/6 (Params: 34)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 2, 6] -> Rank: 6/6 (Params: 18)
    [Upward Pruned] 1 supersets removed from queue.

Added 31 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_6_r1_architectures.csv'.

Loading existing database from '../data/raw/1_6_r2_architectures.csv'...

--- RANDOM SEARCH: h=2, exponent=2 ---
  Target Ambient Dimension: 6
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 292 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.

--- RANDOM SEARCH: h=3, exponent=2 ---
  Target Ambient Dimension: 6
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 89367 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_6_r2_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=3 ---
  Target Ambient Dimension: 6
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 95, 6] -> Rank: 6/6 (Params: 665)
    [Upward Pruned] 205 supersets removed from queue.
  [FULL ] [1, 59, 6] -> Rank: 6/6 (Params: 413)
    [Upward Pruned] 35 supersets removed from queue.
  [FULL ] [1, 15, 6] -> Rank: 6/6 (Params: 105)
    [Upward Pruned] 43 supersets removed from queue.
  [FULL ] [1, 7, 6] -> Rank: 6/6 (Params: 49)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 4, 6] -> Rank: 6/6 (Params: 28)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 2, 6] -> Rank: 6/6 (Params: 14)
    [Upward Pruned] 1 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=3 ---
  Target Ambient Dimension: 6
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 263, 159, 6] -> Rank: 6/6 (Params: 43034)
    [Upward Pruned] 5395 supersets removed from queue.
  [FULL ] [1, 221, 198, 6] -> Rank: 6/6 (Params: 45167)
    [Upward Pruned] 4325 supersets removed from queue.
  [FULL ] [1, 195, 218, 6] -> Rank: 6/6 (Params: 44013)
    [Upward Pruned] 2157 supersets removed from queue.
  [FULL ] [1, 128, 82, 6] -> Rank: 6/6 (Params: 11116)
    [Upward Pruned] 26006 supersets removed from queue.
  [FULL ] [1, 137, 15, 6] -> Rank: 6/6 (Params: 2282)
    [Upward Pruned] 10987 supersets removed from queue.
  [FULL ] [1, 56, 273, 6] -> Rank: 6/6 (Params: 16982)
    [Upward Pruned] 2015 supersets removed from queue.
  [FULL ] [1, 41, 192, 6] -> Rank: 6/6 (Params: 9065)
    [Upward Pruned] 7466 supersets removed from queue.
  [FULL ] [1, 271, 3, 6] -> Rank: 6/6 (Params: 1102)
    [Upward Pruned] 359 supersets removed from queue.
  [FULL ] [1, 7, 34, 6] -> Rank: 6/6 (Params: 449)
    [Upward Pruned] 23255 supersets removed from queue.
  [FULL ] [1, 44, 23, 6] -> Rank: 6/6 (Params: 1194)
    [Upward Pruned] 1022 supersets removed from queue.
  [FULL ] [1, 123, 6, 6] -> Rank: 6/6 (Params: 897)
    [Upward Pruned] 1443 supersets removed from queue.
  [FULL ] [1, 4, 145, 6] -> Rank: 6/6 (Params: 1454)
    [Upward Pruned] 467 supersets removed from queue.
  [FULL ] [1, 20, 10, 6] -> Rank: 6/6 (Params: 280)
    [Upward Pruned] 1602 supersets removed from queue.
  [FULL ] [1, 19, 29, 6] -> Rank: 6/6 (Params: 744)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 18, 10, 6] -> Rank: 6/6 (Params: 258)
    [Upward Pruned] 42 supersets removed from queue.
  [FULL ] [1, 181, 4, 6] -> Rank: 6/6 (Params: 929)
    [Upward Pruned] 179 supersets removed from queue.
  [FULL ] [1, 118, 3, 6] -> Rank: 6/6 (Params: 490)
    [Upward Pruned] 298 supersets removed from queue.
  [FULL ] [1, 10, 15, 6] -> Rank: 6/6 (Params: 250)
    [Upward Pruned] 151 supersets removed from queue.
  [FULL ] [1, 100, 6, 6] -> Rank: 6/6 (Params: 736)
    [Upward Pruned] 71 supersets removed from queue.
  [FULL ] [1, 17, 13, 6] -> Rank: 6/6 (Params: 316)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 5, 106, 6] -> Rank: 6/6 (Params: 1171)
    [Upward Pruned] 77 supersets removed from queue.
  [FULL ] [1, 2, 85, 6] -> Rank: 6/6 (Params: 682)
    [Upward Pruned] 533 supersets removed from queue.
  [FULL ] [1, 26, 6, 6] -> Rank: 6/6 (Params: 218)
    [Upward Pruned] 295 supersets removed from queue.
  [FULL ] [1, 9, 26, 6] -> Rank: 6/6 (Params: 399)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 48, 5, 6] -> Rank: 6/6 (Params: 318)
    [Upward Pruned] 69 supersets removed from queue.
  [FULL ] [1, 96, 4, 6] -> Rank: 6/6 (Params: 504)
    [Upward Pruned] 21 supersets removed from queue.
  [FULL ] [1, 112, 2, 6] -> Rank: 6/6 (Params: 348)
    [Upward Pruned] 194 supersets removed from queue.
  [FULL ] [1, 6, 17, 6] -> Rank: 6/6 (Params: 210)
    [Upward Pruned] 110 supersets removed from queue.
  [FULL ] [1, 37, 4, 6] -> Rank: 6/6 (Params: 209)
    [Upward Pruned] 69 supersets removed from queue.
  [FULL ] [1, 45, 2, 6] -> Rank: 6/6 (Params: 147)
    [Upward Pruned] 133 supersets removed from queue.
  [FULL ] [1, 4, 50, 6] -> Rank: 6/6 (Params: 504)
    [Upward Pruned] 69 supersets removed from queue.
  [FULL ] [1, 12, 7, 6] -> Rank: 6/6 (Params: 138)
    [Upward Pruned] 69 supersets removed from queue.
  [FULL ] [1, 22, 6, 6] -> Rank: 6/6 (Params: 190)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 3, 46, 6] -> Rank: 6/6 (Params: 417)
    [Upward Pruned] 46 supersets removed from queue.
  [FULL ] [1, 7, 4, 6] -> Rank: 6/6 (Params: 59)
    [Upward Pruned] 120 supersets removed from queue.
  [FULL ] [1, 2, 61, 6] -> Rank: 6/6 (Params: 490)
    [Upward Pruned] 23 supersets removed from queue.
  [FULL ] [1, 2, 6, 6] -> Rank: 6/6 (Params: 50)
    [Upward Pruned] 185 supersets removed from queue.
  [FULL ] [1, 28, 2, 6] -> Rank: 6/6 (Params: 96)
    [Upward Pruned] 33 supersets removed from queue.
  [FULL ] [1, 5, 4, 6] -> Rank: 6/6 (Params: 49)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 20, 3, 6] -> Rank: 6/6 (Params: 98)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 2, 3, 6] -> Rank: 6/6 (Params: 26)
    [Upward Pruned] 23 supersets removed from queue.
  [FULL ] [1, 2, 2, 6] -> Rank: 6/6 (Params: 18)
    [Upward Pruned] 25 supersets removed from queue.

Added 48 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_6_r3_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=4 ---
  Target Ambient Dimension: 6
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 199, 6] -> Rank: 6/6 (Params: 1393)
    [Upward Pruned] 101 supersets removed from queue.
  [FULL ] [1, 7, 6] -> Rank: 6/6 (Params: 49)
    [Upward Pruned] 191 supersets removed from queue.
  [FULL ] [1, 2, 6] -> Rank: 6/6 (Params: 14)
    [Upward Pruned] 4 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=4 ---
  Target Ambient Dimension: 6
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 162, 97, 6] -> Rank: 6/6 (Params: 16458)
    [Upward Pruned] 28355 supersets removed from queue.
  [FULL ] [1, 104, 299, 6] -> Rank: 6/6 (Params: 32994)
    [Upward Pruned] 115 supersets removed from queue.
  [FULL ] [1, 143, 280, 6] -> Rank: 6/6 (Params: 41863)
    [Upward Pruned] 360 supersets removed from queue.
  [FULL ] [1, 10, 108, 6] -> Rank: 6/6 (Params: 1738)
    [Upward Pruned] 28858 supersets removed from queue.
  [FULL ] [1, 63, 11, 6] -> Rank: 6/6 (Params: 822)
    [Upward Pruned] 21556 supersets removed from queue.
  [FULL ] [1, 9, 281, 6] -> Rank: 6/6 (Params: 4224)
    [Upward Pruned] 19 supersets removed from queue.
  [FULL ] [1, 50, 23, 6] -> Rank: 6/6 (Params: 1338)
    [Upward Pruned] 1104 supersets removed from queue.
  [FULL ] [1, 192, 10, 6] -> Rank: 6/6 (Params: 2172)
    [Upward Pruned] 108 supersets removed from queue.
  [FULL ] [1, 5, 58, 6] -> Rank: 6/6 (Params: 643)
    [Upward Pruned] 3194 supersets removed from queue.
  [FULL ] [1, 38, 54, 6] -> Rank: 6/6 (Params: 2414)
    [Upward Pruned] 47 supersets removed from queue.
  [FULL ] [1, 212, 4, 6] -> Rank: 6/6 (Params: 1084)
    [Upward Pruned] 533 supersets removed from queue.
  [FULL ] [1, 30, 53, 6] -> Rank: 6/6 (Params: 1938)
    [Upward Pruned] 51 supersets removed from queue.
  [FULL ] [1, 62, 14, 6] -> Rank: 6/6 (Params: 1014)
    [Upward Pruned] 8 supersets removed from queue.
  [FULL ] [1, 80, 5, 6] -> Rank: 6/6 (Params: 510)
    [Upward Pruned] 771 supersets removed from queue.
  [FULL ] [1, 48, 40, 6] -> Rank: 6/6 (Params: 2208)
    [Upward Pruned] 25 supersets removed from queue.
  [FULL ] [1, 25, 11, 6] -> Rank: 6/6 (Params: 366)
    [Upward Pruned] 1195 supersets removed from queue.
  [FULL ] [1, 10, 46, 6] -> Rank: 6/6 (Params: 746)
    [Upward Pruned] 179 supersets removed from queue.
  [FULL ] [1, 20, 8, 6] -> Rank: 6/6 (Params: 228)
    [Upward Pruned] 354 supersets removed from queue.
  [FULL ] [1, 2, 90, 6] -> Rank: 6/6 (Params: 722)
    [Upward Pruned] 632 supersets removed from queue.
  [FULL ] [1, 32, 3, 6] -> Rank: 6/6 (Params: 146)
    [Upward Pruned] 592 supersets removed from queue.
  [FULL ] [1, 172, 2, 6] -> Rank: 6/6 (Params: 528)
    [Upward Pruned] 128 supersets removed from queue.
  [FULL ] [1, 10, 12, 6] -> Rank: 6/6 (Params: 202)
    [Upward Pruned] 339 supersets removed from queue.
  [FULL ] [1, 8, 47, 6] -> Rank: 6/6 (Params: 666)
    [Upward Pruned] 21 supersets removed from queue.
  [FULL ] [1, 8, 6, 6] -> Rank: 6/6 (Params: 92)
    [Upward Pruned] 165 supersets removed from queue.
  [FULL ] [1, 60, 2, 6] -> Rank: 6/6 (Params: 192)
    [Upward Pruned] 111 supersets removed from queue.
  [FULL ] [1, 4, 47, 6] -> Rank: 6/6 (Params: 474)
    [Upward Pruned] 75 supersets removed from queue.
  [FULL ] [1, 4, 35, 6] -> Rank: 6/6 (Params: 354)
    [Upward Pruned] 47 supersets removed from queue.
  [FULL ] [1, 50, 2, 6] -> Rank: 6/6 (Params: 162)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 3, 69, 6] -> Rank: 6/6 (Params: 624)
    [Upward Pruned] 20 supersets removed from queue.
  [FULL ] [1, 2, 51, 6] -> Rank: 6/6 (Params: 410)
    [Upward Pruned] 56 supersets removed from queue.
  [FULL ] [1, 5, 12, 6] -> Rank: 6/6 (Params: 137)
    [Upward Pruned] 68 supersets removed from queue.
  [FULL ] [1, 5, 10, 6] -> Rank: 6/6 (Params: 115)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 2, 35, 6] -> Rank: 6/6 (Params: 282)
    [Upward Pruned] 31 supersets removed from queue.
  [FULL ] [1, 33, 2, 6] -> Rank: 6/6 (Params: 111)
    [Upward Pruned] 16 supersets removed from queue.
  [FULL ] [1, 11, 3, 6] -> Rank: 6/6 (Params: 62)
    [Upward Pruned] 62 supersets removed from queue.
  [FULL ] [1, 2, 16, 6] -> Rank: 6/6 (Params: 130)
    [Upward Pruned] 56 supersets removed from queue.
  [FULL ] [1, 2, 7, 6] -> Rank: 6/6 (Params: 58)
    [Upward Pruned] 35 supersets removed from queue.
  [FULL ] [1, 20, 2, 6] -> Rank: 6/6 (Params: 72)
    [Upward Pruned] 12 supersets removed from queue.
  [FULL ] [1, 3, 4, 6] -> Rank: 6/6 (Params: 39)
    [Upward Pruned] 20 supersets removed from queue.
  [FULL ] [1, 5, 2, 6] -> Rank: 6/6 (Params: 27)
    [Upward Pruned] 20 supersets removed from queue.
  [FULL ] [1, 2, 6, 6] -> Rank: 6/6 (Params: 50)
  [FULL ] [1, 2, 4, 6] -> Rank: 6/6 (Params: 34)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 3, 6] -> Rank: 6/6 (Params: 26)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 4, 2, 6] -> Rank: 6/6 (Params: 24)
  [FULL ] [1, 3, 2, 6] -> Rank: 6/6 (Params: 21)
  [FULL ] [1, 2, 2, 6] -> Rank: 6/6 (Params: 18)

Added 49 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_6_r4_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=5 ---
  Target Ambient Dimension: 6
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 272, 6] -> Rank: 6/6 (Params: 1904)
    [Upward Pruned] 28 supersets removed from queue.
  [FULL ] [1, 92, 6] -> Rank: 6/6 (Params: 644)
    [Upward Pruned] 179 supersets removed from queue.
  [FULL ] [1, 69, 6] -> Rank: 6/6 (Params: 483)
    [Upward Pruned] 22 supersets removed from queue.
  [FULL ] [1, 53, 6] -> Rank: 6/6 (Params: 371)
    [Upward Pruned] 15 supersets removed from queue.
  [FULL ] [1, 16, 6] -> Rank: 6/6 (Params: 112)
    [Upward Pruned] 36 supersets removed from queue.
  [FULL ] [1, 12, 6] -> Rank: 6/6 (Params: 84)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 8, 6] -> Rank: 6/6 (Params: 56)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 6, 6] -> Rank: 6/6 (Params: 42)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 5, 6] -> Rank: 6/6 (Params: 35)
  [FULL ] [1, 3, 6] -> Rank: 6/6 (Params: 21)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 6] -> Rank: 6/6 (Params: 14)

--- RANDOM SEARCH: h=3, exponent=5 ---
  Target Ambient Dimension: 6
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 124, 3, 6] -> Rank: 6/6 (Params: 514)
    [Upward Pruned] 52745 supersets removed from queue.
  [FULL ] [1, 43, 287, 6] -> Rank: 6/6 (Params: 14106)
    [Upward Pruned] 1133 supersets removed from queue.
  [FULL ] [1, 33, 148, 6] -> Rank: 6/6 (Params: 5805)
    [Upward Pruned] 12788 supersets removed from queue.
  [FULL ] [1, 101, 46, 6] -> Rank: 6/6 (Params: 5023)
    [Upward Pruned] 2345 supersets removed from queue.
  [FULL ] [1, 16, 254, 6] -> Rank: 6/6 (Params: 5604)
    [Upward Pruned] 798 supersets removed from queue.
  [FULL ] [1, 23, 108, 6] -> Rank: 6/6 (Params: 3155)
    [Upward Pruned] 4179 supersets removed from queue.
  [FULL ] [1, 21, 61, 6] -> Rank: 6/6 (Params: 1668)
    [Upward Pruned] 4051 supersets removed from queue.
  [FULL ] [1, 23, 10, 6] -> Rank: 6/6 (Params: 313)
    [Upward Pruned] 4805 supersets removed from queue.
  [FULL ] [1, 12, 128, 6] -> Rank: 6/6 (Params: 2316)
    [Upward Pruned] 1321 supersets removed from queue.
  [FULL ] [1, 9, 90, 6] -> Rank: 6/6 (Params: 1359)
    [Upward Pruned] 974 supersets removed from queue.
  [FULL ] [1, 6, 228, 6] -> Rank: 6/6 (Params: 2742)
    [Upward Pruned] 218 supersets removed from queue.
  [FULL ] [1, 100, 8, 6] -> Rank: 6/6 (Params: 948)
    [Upward Pruned] 47 supersets removed from queue.
  [FULL ] [1, 4, 284, 6] -> Rank: 6/6 (Params: 2844)
    [Upward Pruned] 33 supersets removed from queue.
  [FULL ] [1, 37, 3, 6] -> Rank: 6/6 (Params: 166)
    [Upward Pruned] 560 supersets removed from queue.
  [FULL ] [1, 4, 175, 6] -> Rank: 6/6 (Params: 1754)
    [Upward Pruned] 376 supersets removed from queue.
  [FULL ] [1, 2, 64, 6] -> Rank: 6/6 (Params: 514)
    [Upward Pruned] 1340 supersets removed from queue.
  [FULL ] [1, 10, 53, 6] -> Rank: 6/6 (Params: 858)
    [Upward Pruned] 136 supersets removed from queue.
  [FULL ] [1, 9, 59, 6] -> Rank: 6/6 (Params: 894)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 145, 2, 6] -> Rank: 6/6 (Params: 447)
    [Upward Pruned] 155 supersets removed from queue.
  [FULL ] [1, 133, 2, 6] -> Rank: 6/6 (Params: 411)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 5, 11, 6] -> Rank: 6/6 (Params: 126)
    [Upward Pruned] 805 supersets removed from queue.
  [FULL ] [1, 32, 9, 6] -> Rank: 6/6 (Params: 374)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 2, 44, 6] -> Rank: 6/6 (Params: 354)
    [Upward Pruned] 59 supersets removed from queue.
  [FULL ] [1, 22, 6, 6] -> Rank: 6/6 (Params: 190)
    [Upward Pruned] 55 supersets removed from queue.
  [FULL ] [1, 4, 21, 6] -> Rank: 6/6 (Params: 214)
    [Upward Pruned] 22 supersets removed from queue.
  [FULL ] [1, 50, 2, 6] -> Rank: 6/6 (Params: 162)
    [Upward Pruned] 82 supersets removed from queue.
  [FULL ] [1, 11, 6, 6] -> Rank: 6/6 (Params: 113)
    [Upward Pruned] 54 supersets removed from queue.
  [FULL ] [1, 4, 3, 6] -> Rank: 6/6 (Params: 34)
    [Upward Pruned] 143 supersets removed from queue.
  [FULL ] [1, 2, 6, 6] -> Rank: 6/6 (Params: 50)
    [Upward Pruned] 75 supersets removed from queue.
  [FULL ] [1, 28, 2, 6] -> Rank: 6/6 (Params: 96)
    [Upward Pruned] 21 supersets removed from queue.
  [FULL ] [1, 17, 2, 6] -> Rank: 6/6 (Params: 63)
    [Upward Pruned] 10 supersets removed from queue.
  [FULL ] [1, 14, 2, 6] -> Rank: 6/6 (Params: 54)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 9, 2, 6] -> Rank: 6/6 (Params: 39)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 3, 5, 6] -> Rank: 6/6 (Params: 48)
  [FULL ] [1, 5, 2, 6] -> Rank: 6/6 (Params: 27)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 3, 4, 6] -> Rank: 6/6 (Params: 39)
  [FULL ] [1, 2, 3, 6] -> Rank: 6/6 (Params: 26)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 2, 2, 6] -> Rank: 6/6 (Params: 18)
    [Upward Pruned] 2 supersets removed from queue.

Added 49 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_6_r5_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=6 ---
  Target Ambient Dimension: 6
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 130, 6] -> Rank: 6/6 (Params: 910)
    [Upward Pruned] 170 supersets removed from queue.
  [FULL ] [1, 63, 6] -> Rank: 6/6 (Params: 441)
    [Upward Pruned] 66 supersets removed from queue.
  [FULL ] [1, 3, 6] -> Rank: 6/6 (Params: 21)
    [Upward Pruned] 59 supersets removed from queue.
  [FULL ] [1, 2, 6] -> Rank: 6/6 (Params: 14)

--- RANDOM SEARCH: h=3, exponent=6 ---
  Target Ambient Dimension: 6
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 84, 14, 6] -> Rank: 6/6 (Params: 1344)
    [Upward Pruned] 62278 supersets removed from queue.
  [FULL ] [1, 10, 18, 6] -> Rank: 6/6 (Params: 298)
    [Upward Pruned] 20941 supersets removed from queue.
  [FULL ] [1, 164, 12, 6] -> Rank: 6/6 (Params: 2204)
    [Upward Pruned] 273 supersets removed from queue.
  [FULL ] [1, 25, 6, 6] -> Rank: 6/6 (Params: 211)
    [Upward Pruned] 2169 supersets removed from queue.
  [FULL ] [1, 2, 47, 6] -> Rank: 6/6 (Params: 378)
    [Upward Pruned] 2031 supersets removed from queue.
  [FULL ] [1, 197, 2, 6] -> Rank: 6/6 (Params: 603)
    [Upward Pruned] 415 supersets removed from queue.
  [FULL ] [1, 2, 15, 6] -> Rank: 6/6 (Params: 122)
    [Upward Pruned] 300 supersets removed from queue.
  [FULL ] [1, 13, 10, 6] -> Rank: 6/6 (Params: 203)
    [Upward Pruned] 59 supersets removed from queue.
  [FULL ] [1, 158, 2, 6] -> Rank: 6/6 (Params: 486)
    [Upward Pruned] 155 supersets removed from queue.
  [FULL ] [1, 22, 7, 6] -> Rank: 6/6 (Params: 218)
    [Upward Pruned] 8 supersets removed from queue.
  [FULL ] [1, 147, 5, 6] -> Rank: 6/6 (Params: 912)
    [Upward Pruned] 10 supersets removed from queue.
  [FULL ] [1, 90, 2, 6] -> Rank: 6/6 (Params: 282)
    [Upward Pruned] 260 supersets removed from queue.
  [FULL ] [1, 64, 3, 6] -> Rank: 6/6 (Params: 274)
    [Upward Pruned] 77 supersets removed from queue.
  [FULL ] [1, 3, 14, 6] -> Rank: 6/6 (Params: 129)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 21, 4, 6] -> Rank: 6/6 (Params: 129)
    [Upward Pruned] 92 supersets removed from queue.
  [FULL ] [1, 6, 7, 6] -> Rank: 6/6 (Params: 90)
    [Upward Pruned] 72 supersets removed from queue.
  [FULL ] [1, 20, 2, 6] -> Rank: 6/6 (Params: 72)
    [Upward Pruned] 116 supersets removed from queue.
  [FULL ] [1, 19, 4, 6] -> Rank: 6/6 (Params: 119)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 6, 2, 6] -> Rank: 6/6 (Params: 30)
    [Upward Pruned] 66 supersets removed from queue.
  [FULL ] [1, 4, 8, 6] -> Rank: 6/6 (Params: 84)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 2, 7, 6] -> Rank: 6/6 (Params: 58)
    [Upward Pruned] 16 supersets removed from queue.
  [FULL ] [1, 3, 2, 6] -> Rank: 6/6 (Params: 21)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 2, 2, 6] -> Rank: 6/6 (Params: 18)
    [Upward Pruned] 4 supersets removed from queue.

Added 27 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_6_r6_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=7 ---
  Target Ambient Dimension: 6
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 84, 6] -> Rank: 6/6 (Params: 588)
    [Upward Pruned] 216 supersets removed from queue.
  [FULL ] [1, 70, 6] -> Rank: 6/6 (Params: 490)
    [Upward Pruned] 13 supersets removed from queue.
  [FULL ] [1, 12, 6] -> Rank: 6/6 (Params: 84)
    [Upward Pruned] 57 supersets removed from queue.
  [FULL ] [1, 3, 6] -> Rank: 6/6 (Params: 21)
    [Upward Pruned] 8 supersets removed from queue.
  [FULL ] [1, 2, 6] -> Rank: 6/6 (Params: 14)

--- RANDOM SEARCH: h=3, exponent=7 ---
  Target Ambient Dimension: 6
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 79, 123, 6] -> Rank: 6/6 (Params: 10534)
    [Upward Pruned] 39515 supersets removed from queue.
  [FULL ] [1, 144, 77, 6] -> Rank: 6/6 (Params: 11694)
    [Upward Pruned] 7221 supersets removed from queue.
  [FULL ] [1, 232, 74, 6] -> Rank: 6/6 (Params: 17844)
    [Upward Pruned] 206 supersets removed from queue.
  [FULL ] [1, 225, 54, 6] -> Rank: 6/6 (Params: 12699)
    [Upward Pruned] 1540 supersets removed from queue.
  [FULL ] [1, 41, 269, 6] -> Rank: 6/6 (Params: 12684)
    [Upward Pruned] 1215 supersets removed from queue.
  [FULL ] [1, 51, 174, 6] -> Rank: 6/6 (Params: 9969)
    [Upward Pruned] 2659 supersets removed from queue.
  [FULL ] [1, 153, 20, 6] -> Rank: 6/6 (Params: 3333)
    [Upward Pruned] 6687 supersets removed from queue.
  [FULL ] [1, 38, 178, 6] -> Rank: 6/6 (Params: 7870)
    [Upward Pruned] 1278 supersets removed from queue.
  [FULL ] [1, 3, 202, 6] -> Rank: 6/6 (Params: 1821)
    [Upward Pruned] 3464 supersets removed from queue.
  [FULL ] [1, 69, 108, 6] -> Rank: 6/6 (Params: 8169)
    [Upward Pruned] 1634 supersets removed from queue.
  [FULL ] [1, 105, 34, 6] -> Rank: 6/6 (Params: 3879)
    [Upward Pruned] 3272 supersets removed from queue.
  [FULL ] [1, 74, 44, 6] -> Rank: 6/6 (Params: 3594)
    [Upward Pruned] 1983 supersets removed from queue.
  [FULL ] [1, 61, 146, 6] -> Rank: 6/6 (Params: 9843)
    [Upward Pruned] 223 supersets removed from queue.
  [FULL ] [1, 24, 12, 6] -> Rank: 6/6 (Params: 384)
    [Upward Pruned] 11221 supersets removed from queue.
  [FULL ] [1, 233, 5, 6] -> Rank: 6/6 (Params: 1428)
    [Upward Pruned] 475 supersets removed from queue.
  [FULL ] [1, 158, 11, 6] -> Rank: 6/6 (Params: 1962)
    [Upward Pruned] 74 supersets removed from queue.
  [FULL ] [1, 4, 39, 6] -> Rank: 6/6 (Params: 394)
    [Upward Pruned] 3259 supersets removed from queue.
  [FULL ] [1, 19, 6, 6] -> Rank: 6/6 (Params: 169)
    [Upward Pruned] 1343 supersets removed from queue.
  [FULL ] [1, 146, 4, 6] -> Rank: 6/6 (Params: 754)
    [Upward Pruned] 241 supersets removed from queue.
  [FULL ] [1, 10, 19, 6] -> Rank: 6/6 (Params: 314)
    [Upward Pruned] 179 supersets removed from queue.
  [FULL ] [1, 2, 293, 6] -> Rank: 6/6 (Params: 2346)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 288, 2, 6] -> Rank: 6/6 (Params: 876)
    [Upward Pruned] 25 supersets removed from queue.
  [FULL ] [1, 65, 5, 6] -> Rank: 6/6 (Params: 420)
    [Upward Pruned] 80 supersets removed from queue.
  [FULL ] [1, 5, 32, 6] -> Rank: 6/6 (Params: 357)
    [Upward Pruned] 34 supersets removed from queue.
  [FULL ] [1, 2, 198, 6] -> Rank: 6/6 (Params: 1586)
    [Upward Pruned] 98 supersets removed from queue.
  [FULL ] [1, 6, 3, 6] -> Rank: 6/6 (Params: 42)
    [Upward Pruned] 701 supersets removed from queue.
  [FULL ] [1, 154, 2, 6] -> Rank: 6/6 (Params: 474)
    [Upward Pruned] 133 supersets removed from queue.
  [FULL ] [1, 2, 105, 6] -> Rank: 6/6 (Params: 842)
    [Upward Pruned] 185 supersets removed from queue.
  [FULL ] [1, 2, 60, 6] -> Rank: 6/6 (Params: 482)
    [Upward Pruned] 89 supersets removed from queue.
  [FULL ] [1, 133, 2, 6] -> Rank: 6/6 (Params: 411)
    [Upward Pruned] 20 supersets removed from queue.
  [FULL ] [1, 5, 26, 6] -> Rank: 6/6 (Params: 291)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 15, 2, 6] -> Rank: 6/6 (Params: 57)
    [Upward Pruned] 117 supersets removed from queue.
  [FULL ] [1, 5, 10, 6] -> Rank: 6/6 (Params: 115)
    [Upward Pruned] 15 supersets removed from queue.
  [FULL ] [1, 3, 13, 6] -> Rank: 6/6 (Params: 120)
    [Upward Pruned] 72 supersets removed from queue.
  [FULL ] [1, 2, 24, 6] -> Rank: 6/6 (Params: 194)
    [Upward Pruned] 35 supersets removed from queue.
  [FULL ] [1, 2, 9, 6] -> Rank: 6/6 (Params: 74)
    [Upward Pruned] 23 supersets removed from queue.
  [FULL ] [1, 5, 4, 6] -> Rank: 6/6 (Params: 49)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 3, 8, 6] -> Rank: 6/6 (Params: 75)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 3, 6, 6] -> Rank: 6/6 (Params: 57)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 2, 2, 6] -> Rank: 6/6 (Params: 18)
    [Upward Pruned] 25 supersets removed from queue.

Added 45 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_6_r7_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=8 ---
  Target Ambient Dimension: 6
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 175, 6] -> Rank: 6/6 (Params: 1225)
    [Upward Pruned] 125 supersets removed from queue.
  [FULL ] [1, 35, 6] -> Rank: 6/6 (Params: 245)
    [Upward Pruned] 139 supersets removed from queue.
  [FULL ] [1, 26, 6] -> Rank: 6/6 (Params: 182)
    [Upward Pruned] 8 supersets removed from queue.
  [FULL ] [1, 23, 6] -> Rank: 6/6 (Params: 161)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 17, 6] -> Rank: 6/6 (Params: 119)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 2, 6] -> Rank: 6/6 (Params: 14)
    [Upward Pruned] 14 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=8 ---
  Target Ambient Dimension: 6
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 265, 204, 6] -> Rank: 6/6 (Params: 55549)
    [Upward Pruned] 3491 supersets removed from queue.
  [FULL ] [1, 196, 165, 6] -> Rank: 6/6 (Params: 33526)
    [Upward Pruned] 10787 supersets removed from queue.
  [FULL ] [1, 120, 169, 6] -> Rank: 6/6 (Params: 21414)
    [Upward Pruned] 10031 supersets removed from queue.
  [FULL ] [1, 72, 152, 6] -> Rank: 6/6 (Params: 11928)
    [Upward Pruned] 9808 supersets removed from queue.
  [FULL ] [1, 277, 7, 6] -> Rank: 6/6 (Params: 2258)
    [Upward Pruned] 3479 supersets removed from queue.
  [FULL ] [1, 116, 44, 6] -> Rank: 6/6 (Params: 5484)
    [Upward Pruned] 17387 supersets removed from queue.
  [FULL ] [1, 83, 109, 6] -> Rank: 6/6 (Params: 9784)
    [Upward Pruned] 1418 supersets removed from queue.
  [FULL ] [1, 253, 19, 6] -> Rank: 6/6 (Params: 5174)
    [Upward Pruned] 599 supersets removed from queue.
  [FULL ] [1, 37, 12, 6] -> Rank: 6/6 (Params: 553)
    [Upward Pruned] 19407 supersets removed from queue.
  [FULL ] [1, 135, 4, 6] -> Rank: 6/6 (Params: 699)
    [Upward Pruned] 1207 supersets removed from queue.
  [FULL ] [1, 111, 8, 6] -> Rank: 6/6 (Params: 1047)
    [Upward Pruned] 95 supersets removed from queue.
  [FULL ] [1, 25, 40, 6] -> Rank: 6/6 (Params: 1265)
    [Upward Pruned] 3131 supersets removed from queue.
  [FULL ] [1, 3, 258, 6] -> Rank: 6/6 (Params: 2325)
    [Upward Pruned] 945 supersets removed from queue.
  [FULL ] [1, 3, 151, 6] -> Rank: 6/6 (Params: 1362)
    [Upward Pruned] 2353 supersets removed from queue.
  [FULL ] [1, 4, 117, 6] -> Rank: 6/6 (Params: 1174)
    [Upward Pruned] 713 supersets removed from queue.
  [FULL ] [1, 240, 2, 6] -> Rank: 6/6 (Params: 732)
    [Upward Pruned] 121 supersets removed from queue.
  [FULL ] [1, 16, 109, 6] -> Rank: 6/6 (Params: 2414)
    [Upward Pruned] 71 supersets removed from queue.
  [FULL ] [1, 12, 8, 6] -> Rank: 6/6 (Params: 156)
    [Upward Pruned] 2024 supersets removed from queue.
  [FULL ] [1, 5, 52, 6] -> Rank: 6/6 (Params: 577)
    [Upward Pruned] 454 supersets removed from queue.
  [FULL ] [1, 116, 3, 6] -> Rank: 6/6 (Params: 482)
    [Upward Pruned] 199 supersets removed from queue.
  [FULL ] [1, 47, 5, 6] -> Rank: 6/6 (Params: 312)
    [Upward Pruned] 206 supersets removed from queue.
  [FULL ] [1, 10, 44, 6] -> Rank: 6/6 (Params: 714)
    [Upward Pruned] 15 supersets removed from queue.
  [FULL ] [1, 3, 134, 6] -> Rank: 6/6 (Params: 1209)
    [Upward Pruned] 16 supersets removed from queue.
  [FULL ] [1, 2, 47, 6] -> Rank: 6/6 (Params: 378)
    [Upward Pruned] 435 supersets removed from queue.
  [FULL ] [1, 25, 5, 6] -> Rank: 6/6 (Params: 180)
    [Upward Pruned] 65 supersets removed from queue.
  [FULL ] [1, 9, 9, 6] -> Rank: 6/6 (Params: 144)
    [Upward Pruned] 107 supersets removed from queue.
  [FULL ] [1, 8, 21, 6] -> Rank: 6/6 (Params: 302)
    [Upward Pruned] 25 supersets removed from queue.
  [FULL ] [1, 3, 29, 6] -> Rank: 6/6 (Params: 264)
    [Upward Pruned] 89 supersets removed from queue.
  [FULL ] [1, 80, 4, 6] -> Rank: 6/6 (Params: 424)
    [Upward Pruned] 35 supersets removed from queue.
  [FULL ] [1, 4, 18, 6] -> Rank: 6/6 (Params: 184)
    [Upward Pruned] 46 supersets removed from queue.
  [FULL ] [1, 17, 3, 6] -> Rank: 6/6 (Params: 86)
    [Upward Pruned] 185 supersets removed from queue.
  [FULL ] [1, 165, 2, 6] -> Rank: 6/6 (Params: 507)
    [Upward Pruned] 74 supersets removed from queue.
  [FULL ] [1, 2, 21, 6] -> Rank: 6/6 (Params: 170)
    [Upward Pruned] 33 supersets removed from queue.
  [FULL ] [1, 157, 2, 6] -> Rank: 6/6 (Params: 483)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 49, 2, 6] -> Rank: 6/6 (Params: 159)
    [Upward Pruned] 107 supersets removed from queue.
  [FULL ] [1, 2, 14, 6] -> Rank: 6/6 (Params: 114)
    [Upward Pruned] 33 supersets removed from queue.
  [FULL ] [1, 3, 9, 6] -> Rank: 6/6 (Params: 84)
    [Upward Pruned] 29 supersets removed from queue.
  [FULL ] [1, 14, 3, 6] -> Rank: 6/6 (Params: 74)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 10, 6, 6] -> Rank: 6/6 (Params: 106)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 29, 2, 6] -> Rank: 6/6 (Params: 99)
    [Upward Pruned] 19 supersets removed from queue.
  [FULL ] [1, 9, 4, 6] -> Rank: 6/6 (Params: 69)
    [Upward Pruned] 12 supersets removed from queue.
  [FULL ] [1, 18, 2, 6] -> Rank: 6/6 (Params: 66)
    [Upward Pruned] 10 supersets removed from queue.
  [FULL ] [1, 6, 3, 6] -> Rank: 6/6 (Params: 42)
    [Upward Pruned] 22 supersets removed from queue.
  [FULL ] [1, 16, 2, 6] -> Rank: 6/6 (Params: 60)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 10, 6] -> Rank: 6/6 (Params: 82)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 4, 7, 6] -> Rank: 6/6 (Params: 74)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 3, 2, 6] -> Rank: 6/6 (Params: 21)
    [Upward Pruned] 26 supersets removed from queue.
  [FULL ] [1, 2, 2, 6] -> Rank: 6/6 (Params: 18)
    [Upward Pruned] 7 supersets removed from queue.

Added 54 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_6_r8_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=9 ---
  Target Ambient Dimension: 6
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 72, 6] -> Rank: 6/6 (Params: 504)
    [Upward Pruned] 228 supersets removed from queue.
  [FULL ] [1, 67, 6] -> Rank: 6/6 (Params: 469)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 27, 6] -> Rank: 6/6 (Params: 189)
    [Upward Pruned] 39 supersets removed from queue.
  [FULL ] [1, 9, 6] -> Rank: 6/6 (Params: 63)
    [Upward Pruned] 17 supersets removed from queue.
  [FULL ] [1, 3, 6] -> Rank: 6/6 (Params: 21)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 2, 6] -> Rank: 6/6 (Params: 14)

--- RANDOM SEARCH: h=3, exponent=9 ---
  Target Ambient Dimension: 6
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 226, 88, 6] -> Rank: 6/6 (Params: 20642)
    [Upward Pruned] 15974 supersets removed from queue.
  [FULL ] [1, 104, 74, 6] -> Rank: 6/6 (Params: 8244)
    [Upward Pruned] 28743 supersets removed from queue.
  [FULL ] [1, 23, 224, 6] -> Rank: 6/6 (Params: 6519)
    [Upward Pruned] 6236 supersets removed from queue.
  [FULL ] [1, 82, 12, 6] -> Rank: 6/6 (Params: 1138)
    [Upward Pruned] 16877 supersets removed from queue.
  [FULL ] [1, 66, 66, 6] -> Rank: 6/6 (Params: 4818)
    [Upward Pruned] 2527 supersets removed from queue.
  [FULL ] [1, 44, 12, 6] -> Rank: 6/6 (Params: 644)
    [Upward Pruned] 5527 supersets removed from queue.
  [FULL ] [1, 22, 109, 6] -> Rank: 6/6 (Params: 3074)
    [Upward Pruned] 2606 supersets removed from queue.
  [FULL ] [1, 19, 115, 6] -> Rank: 6/6 (Params: 2894)
    [Upward Pruned] 557 supersets removed from queue.
  [FULL ] [1, 43, 41, 6] -> Rank: 6/6 (Params: 2052)
    [Upward Pruned] 67 supersets removed from queue.
  [FULL ] [1, 17, 101, 6] -> Rank: 6/6 (Params: 2340)
    [Upward Pruned] 609 supersets removed from queue.
  [FULL ] [1, 11, 234, 6] -> Rank: 6/6 (Params: 3989)
    [Upward Pruned] 401 supersets removed from queue.
  [FULL ] [1, 39, 40, 6] -> Rank: 6/6 (Params: 1839)
    [Upward Pruned] 244 supersets removed from queue.
  [FULL ] [1, 3, 39, 6] -> Rank: 6/6 (Params: 354)
    [Upward Pruned] 4634 supersets removed from queue.
  [FULL ] [1, 220, 2, 6] -> Rank: 6/6 (Params: 672)
    [Upward Pruned] 809 supersets removed from queue.
  [FULL ] [1, 167, 9, 6] -> Rank: 6/6 (Params: 1724)
    [Upward Pruned] 158 supersets removed from queue.
  [FULL ] [1, 8, 37, 6] -> Rank: 6/6 (Params: 526)
    [Upward Pruned] 71 supersets removed from queue.
  [FULL ] [1, 25, 22, 6] -> Rank: 6/6 (Params: 707)
    [Upward Pruned] 284 supersets removed from queue.
  [FULL ] [1, 40, 6, 6] -> Rank: 6/6 (Params: 316)
    [Upward Pruned] 960 supersets removed from queue.
  [FULL ] [1, 15, 19, 6] -> Rank: 6/6 (Params: 414)
    [Upward Pruned] 224 supersets removed from queue.
  [FULL ] [1, 3, 11, 6] -> Rank: 6/6 (Params: 102)
    [Upward Pruned] 521 supersets removed from queue.
  [FULL ] [1, 2, 281, 6] -> Rank: 6/6 (Params: 2250)
    [Upward Pruned] 19 supersets removed from queue.
  [FULL ] [1, 173, 5, 6] -> Rank: 6/6 (Params: 1068)
    [Upward Pruned] 46 supersets removed from queue.
  [FULL ] [1, 97, 3, 6] -> Rank: 6/6 (Params: 406)
    [Upward Pruned] 321 supersets removed from queue.
  [FULL ] [1, 27, 4, 6] -> Rank: 6/6 (Params: 159)
    [Upward Pruned] 204 supersets removed from queue.
  [FULL ] [1, 161, 2, 6] -> Rank: 6/6 (Params: 495)
    [Upward Pruned] 58 supersets removed from queue.
  [FULL ] [1, 2, 219, 6] -> Rank: 6/6 (Params: 1754)
    [Upward Pruned] 61 supersets removed from queue.
  [FULL ] [1, 3, 5, 6] -> Rank: 6/6 (Params: 48)
    [Upward Pruned] 143 supersets removed from queue.
  [FULL ] [1, 40, 3, 6] -> Rank: 6/6 (Params: 178)
    [Upward Pruned] 56 supersets removed from queue.
  [FULL ] [1, 13, 3, 6] -> Rank: 6/6 (Params: 70)
    [Upward Pruned] 40 supersets removed from queue.
  [FULL ] [1, 2, 147, 6] -> Rank: 6/6 (Params: 1178)
    [Upward Pruned] 71 supersets removed from queue.
  [FULL ] [1, 117, 2, 6] -> Rank: 6/6 (Params: 363)
    [Upward Pruned] 43 supersets removed from queue.
  [FULL ] [1, 40, 2, 6] -> Rank: 6/6 (Params: 132)
    [Upward Pruned] 76 supersets removed from queue.
  [FULL ] [1, 2, 136, 6] -> Rank: 6/6 (Params: 1090)
    [Upward Pruned] 10 supersets removed from queue.
  [FULL ] [1, 8, 4, 6] -> Rank: 6/6 (Params: 64)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 2, 73, 6] -> Rank: 6/6 (Params: 586)
    [Upward Pruned] 62 supersets removed from queue.
  [FULL ] [1, 23, 2, 6] -> Rank: 6/6 (Params: 81)
    [Upward Pruned] 16 supersets removed from queue.
  [FULL ] [1, 13, 2, 6] -> Rank: 6/6 (Params: 51)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 2, 25, 6] -> Rank: 6/6 (Params: 202)
    [Upward Pruned] 47 supersets removed from queue.
  [FULL ] [1, 7, 2, 6] -> Rank: 6/6 (Params: 33)
    [Upward Pruned] 12 supersets removed from queue.
  [FULL ] [1, 2, 11, 6] -> Rank: 6/6 (Params: 90)
    [Upward Pruned] 13 supersets removed from queue.
  [FULL ] [1, 5, 2, 6] -> Rank: 6/6 (Params: 27)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 2, 7, 6] -> Rank: 6/6 (Params: 58)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 4, 4, 6] -> Rank: 6/6 (Params: 44)
  [FULL ] [1, 3, 4, 6] -> Rank: 6/6 (Params: 39)
  [FULL ] [1, 4, 3, 6] -> Rank: 6/6 (Params: 34)
  [FULL ] [1, 3, 3, 6] -> Rank: 6/6 (Params: 30)
  [FULL ] [1, 2, 3, 6] -> Rank: 6/6 (Params: 26)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 2, 2, 6] -> Rank: 6/6 (Params: 18)
    [Upward Pruned] 2 supersets removed from queue.

Added 54 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_6_r9_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=1 ---
  Target Ambient Dimension: 7
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 104, 7] -> Rank: 7/7 (Params: 832)
    [Upward Pruned] 196 supersets removed from queue.
  [FULL ] [1, 11, 7] -> Rank: 7/7 (Params: 88)
    [Upward Pruned] 92 supersets removed from queue.
  [FULL ] [1, 10, 7] -> Rank: 7/7 (Params: 80)
  [FULL ] [1, 3, 7] -> Rank: 7/7 (Params: 24)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 2, 7] -> Rank: 7/7 (Params: 16)

--- RANDOM SEARCH: h=3, exponent=1 ---
  Target Ambient Dimension: 7
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 182, 197, 7] -> Rank: 7/7 (Params: 37415)
    [Upward Pruned] 12375 supersets removed from queue.
  [FULL ] [1, 92, 169, 7] -> Rank: 7/7 (Params: 16823)
    [Upward Pruned] 15211 supersets removed from queue.
  [FULL ] [1, 297, 39, 7] -> Rank: 7/7 (Params: 12153)
    [Upward Pruned] 519 supersets removed from queue.
  [FULL ] [1, 23, 262, 7] -> Rank: 7/7 (Params: 7883)
    [Upward Pruned] 2690 supersets removed from queue.
  [FULL ] [1, 163, 37, 7] -> Rank: 7/7 (Params: 6453)
    [Upward Pruned] 17695 supersets removed from queue.
  [FULL ] [1, 100, 76, 7] -> Rank: 7/7 (Params: 8232)
    [Upward Pruned] 5858 supersets removed from queue.
  [FULL ] [1, 46, 247, 7] -> Rank: 7/7 (Params: 13137)
    [Upward Pruned] 689 supersets removed from queue.
  [FULL ] [1, 79, 123, 7] -> Rank: 7/7 (Params: 10657)
    [Upward Pruned] 1979 supersets removed from queue.
  [FULL ] [1, 17, 224, 7] -> Rank: 7/7 (Params: 5393)
    [Upward Pruned] 2094 supersets removed from queue.
  [FULL ] [1, 120, 56, 7] -> Rank: 7/7 (Params: 7232)
    [Upward Pruned] 859 supersets removed from queue.
  [FULL ] [1, 57, 87, 7] -> Rank: 7/7 (Params: 5625)
    [Upward Pruned] 3769 supersets removed from queue.
  [FULL ] [1, 28, 207, 7] -> Rank: 7/7 (Params: 7273)
    [Upward Pruned] 492 supersets removed from queue.
  [FULL ] [1, 105, 13, 7] -> Rank: 7/7 (Params: 1561)
    [Upward Pruned] 6105 supersets removed from queue.
  [FULL ] [1, 5, 70, 7] -> Rank: 7/7 (Params: 845)
    [Upward Pruned] 9199 supersets removed from queue.
  [FULL ] [1, 279, 6, 7] -> Rank: 7/7 (Params: 1995)
    [Upward Pruned] 153 supersets removed from queue.
  [FULL ] [1, 3, 151, 7] -> Rank: 7/7 (Params: 1513)
    [Upward Pruned] 299 supersets removed from queue.
  [FULL ] [1, 37, 37, 7] -> Rank: 7/7 (Params: 1665)
    [Upward Pruned] 2243 supersets removed from queue.
  [FULL ] [1, 97, 20, 7] -> Rank: 7/7 (Params: 2177)
    [Upward Pruned] 135 supersets removed from queue.
  [FULL ] [1, 82, 6, 7] -> Rank: 7/7 (Params: 616)
    [Upward Pruned] 1794 supersets removed from queue.
  [FULL ] [1, 10, 54, 7] -> Rank: 7/7 (Params: 928)
    [Upward Pruned] 431 supersets removed from queue.
  [FULL ] [1, 40, 31, 7] -> Rank: 7/7 (Params: 1497)
    [Upward Pruned] 251 supersets removed from queue.
  [FULL ] [1, 109, 2, 7] -> Rank: 7/7 (Params: 341)
    [Upward Pruned] 767 supersets removed from queue.
  [FULL ] [1, 56, 15, 7] -> Rank: 7/7 (Params: 1001)
    [Upward Pruned] 415 supersets removed from queue.
  [FULL ] [1, 2, 179, 7] -> Rank: 7/7 (Params: 1613)
    [Upward Pruned] 121 supersets removed from queue.
  [FULL ] [1, 3, 36, 7] -> Rank: 7/7 (Params: 363)
    [Upward Pruned] 888 supersets removed from queue.
  [FULL ] [1, 6, 25, 7] -> Rank: 7/7 (Params: 331)
    [Upward Pruned] 469 supersets removed from queue.
  [FULL ] [1, 50, 5, 7] -> Rank: 7/7 (Params: 335)
    [Upward Pruned] 406 supersets removed from queue.
  [FULL ] [1, 93, 2, 7] -> Rank: 7/7 (Params: 293)
    [Upward Pruned] 47 supersets removed from queue.
  [FULL ] [1, 87, 3, 7] -> Rank: 7/7 (Params: 369)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 6, 6, 7] -> Rank: 7/7 (Params: 84)
    [Upward Pruned] 835 supersets removed from queue.
  [FULL ] [1, 68, 4, 7] -> Rank: 7/7 (Params: 368)
    [Upward Pruned] 18 supersets removed from queue.
  [FULL ] [1, 5, 8, 7] -> Rank: 7/7 (Params: 101)
    [Upward Pruned] 27 supersets removed from queue.
  [FULL ] [1, 2, 109, 7] -> Rank: 7/7 (Params: 983)
    [Upward Pruned] 69 supersets removed from queue.
  [FULL ] [1, 19, 2, 7] -> Rank: 7/7 (Params: 71)
    [Upward Pruned] 221 supersets removed from queue.
  [FULL ] [1, 2, 60, 7] -> Rank: 7/7 (Params: 542)
    [Upward Pruned] 48 supersets removed from queue.
  [FULL ] [1, 18, 3, 7] -> Rank: 7/7 (Params: 93)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 11, 2, 7] -> Rank: 7/7 (Params: 47)
    [Upward Pruned] 28 supersets removed from queue.
  [FULL ] [1, 4, 33, 7] -> Rank: 7/7 (Params: 367)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 2, 47, 7] -> Rank: 7/7 (Params: 425)
    [Upward Pruned] 12 supersets removed from queue.
  [FULL ] [1, 3, 35, 7] -> Rank: 7/7 (Params: 353)
  [FULL ] [1, 2, 8, 7] -> Rank: 7/7 (Params: 74)
    [Upward Pruned] 90 supersets removed from queue.
  [FULL ] [1, 3, 6, 7] -> Rank: 7/7 (Params: 63)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 4, 5, 7] -> Rank: 7/7 (Params: 59)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 8, 4, 7] -> Rank: 7/7 (Params: 68)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 6, 3, 7] -> Rank: 7/7 (Params: 45)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 10, 2, 7] -> Rank: 7/7 (Params: 44)
  [FULL ] [1, 5, 2, 7] -> Rank: 7/7 (Params: 29)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 4, 2, 7] -> Rank: 7/7 (Params: 26)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 2, 6, 7] -> Rank: 7/7 (Params: 56)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 4, 7] -> Rank: 7/7 (Params: 38)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 3, 3, 7] -> Rank: 7/7 (Params: 33)
  [FULL ] [1, 2, 3, 7] -> Rank: 7/7 (Params: 29)
  [FULL ] [1, 2, 2, 7] -> Rank: 7/7 (Params: 20)
    [Upward Pruned] 1 supersets removed from queue.

Added 58 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_7_r1_architectures.csv'.

Loading existing database from '../data/raw/1_7_r2_architectures.csv'...

--- RANDOM SEARCH: h=2, exponent=2 ---
  Target Ambient Dimension: 7
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 291 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.

--- RANDOM SEARCH: h=3, exponent=2 ---
  Target Ambient Dimension: 7
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 89357 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_7_r2_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=3 ---
  Target Ambient Dimension: 7
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 102, 7] -> Rank: 7/7 (Params: 816)
    [Upward Pruned] 198 supersets removed from queue.
  [FULL ] [1, 4, 7] -> Rank: 7/7 (Params: 32)
    [Upward Pruned] 97 supersets removed from queue.
  [FULL ] [1, 3, 7] -> Rank: 7/7 (Params: 24)
  [FULL ] [1, 2, 7] -> Rank: 7/7 (Params: 16)

--- RANDOM SEARCH: h=3, exponent=3 ---
  Target Ambient Dimension: 7
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 275, 257, 7] -> Rank: 7/7 (Params: 72749)
    [Upward Pruned] 1143 supersets removed from queue.
  [FULL ] [1, 202, 144, 7] -> Rank: 7/7 (Params: 30298)
    [Upward Pruned] 14398 supersets removed from queue.
  [FULL ] [1, 32, 60, 7] -> Rank: 7/7 (Params: 2372)
    [Upward Pruned] 49285 supersets removed from queue.
  [FULL ] [1, 159, 39, 7] -> Rank: 7/7 (Params: 6633)
    [Upward Pruned] 2981 supersets removed from queue.
  [FULL ] [1, 21, 284, 7] -> Rank: 7/7 (Params: 7973)
    [Upward Pruned] 186 supersets removed from queue.
  [FULL ] [1, 31, 276, 7] -> Rank: 7/7 (Params: 10519)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 26, 186, 7] -> Rank: 7/7 (Params: 6164)
    [Upward Pruned] 579 supersets removed from queue.
  [FULL ] [1, 174, 20, 7] -> Rank: 7/7 (Params: 3794)
    [Upward Pruned] 2412 supersets removed from queue.
  [FULL ] [1, 11, 100, 7] -> Rank: 7/7 (Params: 1811)
    [Upward Pruned] 3445 supersets removed from queue.
  [FULL ] [1, 83, 39, 7] -> Rank: 7/7 (Params: 3593)
    [Upward Pruned] 1595 supersets removed from queue.
  [FULL ] [1, 10, 40, 7] -> Rank: 7/7 (Params: 690)
    [Upward Pruned] 2540 supersets removed from queue.
  [FULL ] [1, 228, 11, 7] -> Rank: 7/7 (Params: 2813)
    [Upward Pruned] 656 supersets removed from queue.
  [FULL ] [1, 152, 22, 7] -> Rank: 7/7 (Params: 3650)
    [Upward Pruned] 373 supersets removed from queue.
  [FULL ] [1, 195, 17, 7] -> Rank: 7/7 (Params: 3629)
    [Upward Pruned] 98 supersets removed from queue.
  [FULL ] [1, 7, 28, 7] -> Rank: 7/7 (Params: 399)
    [Upward Pruned] 2453 supersets removed from queue.
  [FULL ] [1, 198, 4, 7] -> Rank: 7/7 (Params: 1018)
    [Upward Pruned] 900 supersets removed from queue.
  [FULL ] [1, 51, 9, 7] -> Rank: 7/7 (Params: 573)
    [Upward Pruned] 2459 supersets removed from queue.
  [FULL ] [1, 73, 2, 7] -> Rank: 7/7 (Params: 233)
    [Upward Pruned] 1080 supersets removed from queue.
  [FULL ] [1, 6, 98, 7] -> Rank: 7/7 (Params: 1280)
    [Upward Pruned] 202 supersets removed from queue.
  [FULL ] [1, 8, 23, 7] -> Rank: 7/7 (Params: 353)
    [Upward Pruned] 214 supersets removed from queue.
  [FULL ] [1, 18, 14, 7] -> Rank: 7/7 (Params: 368)
    [Upward Pruned] 296 supersets removed from queue.
  [FULL ] [1, 3, 282, 7] -> Rank: 7/7 (Params: 2823)
    [Upward Pruned] 56 supersets removed from queue.
  [FULL ] [1, 4, 156, 7] -> Rank: 7/7 (Params: 1720)
    [Upward Pruned] 251 supersets removed from queue.
  [FULL ] [1, 62, 3, 7] -> Rank: 7/7 (Params: 269)
    [Upward Pruned] 65 supersets removed from queue.
  [FULL ] [1, 3, 212, 7] -> Rank: 7/7 (Params: 2123)
    [Upward Pruned] 69 supersets removed from queue.
  [FULL ] [1, 51, 6, 7] -> Rank: 7/7 (Params: 399)
    [Upward Pruned] 32 supersets removed from queue.
  [FULL ] [1, 2, 14, 7] -> Rank: 7/7 (Params: 128)
    [Upward Pruned] 956 supersets removed from queue.
  [FULL ] [1, 13, 5, 7] -> Rank: 7/7 (Params: 113)
    [Upward Pruned] 352 supersets removed from queue.
  [FULL ] [1, 7, 2, 7] -> Rank: 7/7 (Params: 35)
    [Upward Pruned] 229 supersets removed from queue.
  [FULL ] [1, 2, 10, 7] -> Rank: 7/7 (Params: 92)
    [Upward Pruned] 19 supersets removed from queue.
  [FULL ] [1, 4, 9, 7] -> Rank: 7/7 (Params: 103)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 2, 4, 7] -> Rank: 7/7 (Params: 38)
    [Upward Pruned] 26 supersets removed from queue.
  [FULL ] [1, 2, 3, 7] -> Rank: 7/7 (Params: 29)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 4, 2, 7] -> Rank: 7/7 (Params: 26)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 3, 2, 7] -> Rank: 7/7 (Params: 23)
  [FULL ] [1, 2, 2, 7] -> Rank: 7/7 (Params: 20)

Added 40 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_7_r3_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=4 ---
  Target Ambient Dimension: 7
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 181, 7] -> Rank: 7/7 (Params: 1448)
    [Upward Pruned] 119 supersets removed from queue.

  [FULL ] [1, 39, 7] -> Rank: 7/7 (Params: 312)
    [Upward Pruned] 141 supersets removed from queue.
  [FULL ] [1, 37, 7] -> Rank: 7/7 (Params: 296)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 16, 7] -> Rank: 7/7 (Params: 128)
    [Upward Pruned] 20 supersets removed from queue.
  [FULL ] [1, 9, 7] -> Rank: 7/7 (Params: 72)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 7, 7] -> Rank: 7/7 (Params: 56)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 3, 7] -> Rank: 7/7 (Params: 24)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 2, 7] -> Rank: 7/7 (Params: 16)

--- RANDOM SEARCH: h=3, exponent=4 ---
  Target Ambient Dimension: 7
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 46, 105, 7] -> Rank: 7/7 (Params: 5611)
    [Upward Pruned] 49979 supersets removed from queue.
  [FULL ] [1, 181, 12, 7] -> Rank: 7/7 (Params: 2437)
    [Upward Pruned] 11159 supersets removed from queue.
  [FULL ] [1, 176, 73, 7] -> Rank: 7/7 (Params: 13535)
    [Upward Pruned] 159 supersets removed from queue.
  [FULL ] [1, 117, 52, 7] -> Rank: 7/7 (Params: 6565)
    [Upward Pruned] 3231 supersets removed from queue.
  [FULL ] [1, 42, 15, 7] -> Rank: 7/7 (Params: 777)
    [Upward Pruned] 9901 supersets removed from queue.
  [FULL ] [1, 16, 99, 7] -> Rank: 7/7 (Params: 2293)
    [Upward Pruned] 5251 supersets removed from queue.
  [FULL ] [1, 14, 201, 7] -> Rank: 7/7 (Params: 4235)
    [Upward Pruned] 199 supersets removed from queue.
  [FULL ] [1, 4, 293, 7] -> Rank: 7/7 (Params: 3227)
    [Upward Pruned] 79 supersets removed from queue.
  [FULL ] [1, 6, 186, 7] -> Rank: 7/7 (Params: 2424)
    [Upward Pruned] 885 supersets removed from queue.
  [FULL ] [1, 271, 5, 7] -> Rank: 7/7 (Params: 1661)
    [Upward Pruned] 209 supersets removed from queue.
  [FULL ] [1, 75, 4, 7] -> Rank: 7/7 (Params: 403)
    [Upward Pruned] 1915 supersets removed from queue.
  [FULL ] [1, 14, 52, 7] -> Rank: 7/7 (Params: 1106)
    [Upward Pruned] 1489 supersets removed from queue.
  [FULL ] [1, 23, 48, 7] -> Rank: 7/7 (Params: 1463)
    [Upward Pruned] 75 supersets removed from queue.
  [FULL ] [1, 9, 132, 7] -> Rank: 7/7 (Params: 2121)
    [Upward Pruned] 269 supersets removed from queue.
  [FULL ] [1, 4, 261, 7] -> Rank: 7/7 (Params: 2875)
    [Upward Pruned] 63 supersets removed from queue.
  [FULL ] [1, 158, 3, 7] -> Rank: 7/7 (Params: 653)
    [Upward Pruned] 142 supersets removed from queue.
  [FULL ] [1, 18, 46, 7] -> Rank: 7/7 (Params: 1168)
    [Upward Pruned] 67 supersets removed from queue.
  [FULL ] [1, 38, 11, 7] -> Rank: 7/7 (Params: 533)
    [Upward Pruned] 271 supersets removed from queue.
  [FULL ] [1, 53, 6, 7] -> Rank: 7/7 (Params: 413)
    [Upward Pruned] 109 supersets removed from queue.
  [FULL ] [1, 7, 143, 7] -> Rank: 7/7 (Params: 2009)
    [Upward Pruned] 85 supersets removed from queue.
  [FULL ] [1, 5, 204, 7] -> Rank: 7/7 (Params: 2453)
    [Upward Pruned] 56 supersets removed from queue.
  [FULL ] [1, 2, 296, 7] -> Rank: 7/7 (Params: 2666)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 3, 186, 7] -> Rank: 7/7 (Params: 1863)
    [Upward Pruned] 202 supersets removed from queue.
  [FULL ] [1, 2, 212, 7] -> Rank: 7/7 (Params: 1910)
    [Upward Pruned] 83 supersets removed from queue.
  [FULL ] [1, 36, 14, 7] -> Rank: 7/7 (Params: 638)
    [Upward Pruned] 63 supersets removed from queue.
  [FULL ] [1, 284, 2, 7] -> Rank: 7/7 (Params: 866)
    [Upward Pruned] 16 supersets removed from queue.
  [FULL ] [1, 29, 11, 7] -> Rank: 7/7 (Params: 425)
    [Upward Pruned] 250 supersets removed from queue.
  [FULL ] [1, 13, 25, 7] -> Rank: 7/7 (Params: 513)
    [Upward Pruned] 445 supersets removed from queue.
  [FULL ] [1, 12, 75, 7] -> Rank: 7/7 (Params: 1437)
    [Upward Pruned] 56 supersets removed from queue.
  [FULL ] [1, 2, 193, 7] -> Rank: 7/7 (Params: 1739)
    [Upward Pruned] 18 supersets removed from queue.
  [FULL ] [1, 8, 52, 7] -> Rank: 7/7 (Params: 788)
    [Upward Pruned] 353 supersets removed from queue.
  [FULL ] [1, 4, 96, 7] -> Rank: 7/7 (Params: 1060)
    [Upward Pruned] 316 supersets removed from queue.
  [FULL ] [1, 22, 4, 7] -> Rank: 7/7 (Params: 138)
    [Upward Pruned] 358 supersets removed from queue.
  [FULL ] [1, 11, 8, 7] -> Rank: 7/7 (Params: 155)
    [Upward Pruned] 240 supersets removed from queue.
  [FULL ] [1, 4, 86, 7] -> Rank: 7/7 (Params: 950)
    [Upward Pruned] 39 supersets removed from queue.
  [FULL ] [1, 10, 30, 7] -> Rank: 7/7 (Params: 520)
    [Upward Pruned] 21 supersets removed from queue.
  [FULL ] [1, 4, 18, 7] -> Rank: 7/7 (Params: 202)
    [Upward Pruned] 351 supersets removed from queue.
  [FULL ] [1, 4, 4, 7] -> Rank: 7/7 (Params: 48)
    [Upward Pruned] 141 supersets removed from queue.
  [FULL ] [1, 48, 2, 7] -> Rank: 7/7 (Params: 158)
    [Upward Pruned] 345 supersets removed from queue.
  [FULL ] [1, 9, 2, 7] -> Rank: 7/7 (Params: 41)
    [Upward Pruned] 77 supersets removed from queue.
  [FULL ] [1, 2, 20, 7] -> Rank: 7/7 (Params: 182)
    [Upward Pruned] 338 supersets removed from queue.
  [FULL ] [1, 3, 4, 7] -> Rank: 7/7 (Params: 43)
    [Upward Pruned] 15 supersets removed from queue.
  [FULL ] [1, 2, 19, 7] -> Rank: 7/7 (Params: 173)
  [FULL ] [1, 2, 11, 7] -> Rank: 7/7 (Params: 101)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 3, 2, 7] -> Rank: 7/7 (Params: 23)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 2, 6, 7] -> Rank: 7/7 (Params: 56)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 2, 5, 7] -> Rank: 7/7 (Params: 47)
  [FULL ] [1, 2, 3, 7] -> Rank: 7/7 (Params: 29)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 2, 7] -> Rank: 7/7 (Params: 20)

Added 57 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_7_r4_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=5 ---
  Target Ambient Dimension: 7
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 215, 7] -> Rank: 7/7 (Params: 1720)
    [Upward Pruned] 85 supersets removed from queue.
  [FULL ] [1, 51, 7] -> Rank: 7/7 (Params: 408)
    [Upward Pruned] 163 supersets removed from queue.
  [FULL ] [1, 49, 7] -> Rank: 7/7 (Params: 392)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 32, 7] -> Rank: 7/7 (Params: 256)
    [Upward Pruned] 16 supersets removed from queue.
  [FULL ] [1, 17, 7] -> Rank: 7/7 (Params: 136)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 12, 7] -> Rank: 7/7 (Params: 96)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 4, 7] -> Rank: 7/7 (Params: 32)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 3, 7] -> Rank: 7/7 (Params: 24)
  [FULL ] [1, 2, 7] -> Rank: 7/7 (Params: 16)

--- RANDOM SEARCH: h=3, exponent=5 ---
  Target Ambient Dimension: 7
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 254, 8, 7] -> Rank: 7/7 (Params: 2342)
    [Upward Pruned] 13770 supersets removed from queue.
  [FULL ] [1, 278, 3, 7] -> Rank: 7/7 (Params: 1133)
    [Upward Pruned] 114 supersets removed from queue.
  [FULL ] [1, 103, 119, 7] -> Rank: 7/7 (Params: 13193)
    [Upward Pruned] 27481 supersets removed from queue.
  [FULL ] [1, 185, 33, 7] -> Rank: 7/7 (Params: 6521)
    [Upward Pruned] 5933 supersets removed from queue.
  [FULL ] [1, 101, 197, 7] -> Rank: 7/7 (Params: 21377)
    [Upward Pruned] 207 supersets removed from queue.
  [FULL ] [1, 4, 176, 7] -> Rank: 7/7 (Params: 1940)
    [Upward Pruned] 12166 supersets removed from queue.
  [FULL ] [1, 61, 88, 7] -> Rank: 7/7 (Params: 6045)
    [Upward Pruned] 6237 supersets removed from queue.
  [FULL ] [1, 135, 5, 7] -> Rank: 7/7 (Params: 845)
    [Upward Pruned] 6153 supersets removed from queue.
  [FULL ] [1, 52, 53, 7] -> Rank: 7/7 (Params: 3179)
    [Upward Pruned] 3696 supersets removed from queue.
  [FULL ] [1, 49, 144, 7] -> Rank: 7/7 (Params: 8113)
    [Upward Pruned] 95 supersets removed from queue.
  [FULL ] [1, 28, 119, 7] -> Rank: 7/7 (Params: 4193)
    [Upward Pruned] 1271 supersets removed from queue.
  [FULL ] [1, 11, 129, 7] -> Rank: 7/7 (Params: 2333)
    [Upward Pruned] 798 supersets removed from queue.
  [FULL ] [1, 35, 19, 7] -> Rank: 7/7 (Params: 833)
    [Upward Pruned] 4521 supersets removed from queue.
  [FULL ] [1, 51, 10, 7] -> Rank: 7/7 (Params: 631)
    [Upward Pruned] 755 supersets removed from queue.
  [FULL ] [1, 77, 3, 7] -> Rank: 7/7 (Params: 329)
    [Upward Pruned] 691 supersets removed from queue.
  [FULL ] [1, 50, 8, 7] -> Rank: 7/7 (Params: 506)
    [Upward Pruned] 62 supersets removed from queue.
  [FULL ] [1, 22, 23, 7] -> Rank: 7/7 (Params: 689)
    [Upward Pruned] 1307 supersets removed from queue.
  [FULL ] [1, 2, 287, 7] -> Rank: 7/7 (Params: 2585)
    [Upward Pruned] 27 supersets removed from queue.
  [FULL ] [1, 10, 90, 7] -> Rank: 7/7 (Params: 1540)
    [Upward Pruned] 514 supersets removed from queue.
  [FULL ] [1, 36, 16, 7] -> Rank: 7/7 (Params: 724)
    [Upward Pruned] 41 supersets removed from queue.
  [FULL ] [1, 4, 6, 7] -> Rank: 7/7 (Params: 70)
    [Upward Pruned] 2455 supersets removed from queue.
  [FULL ] [1, 2, 138, 7] -> Rank: 7/7 (Params: 1244)
    [Upward Pruned] 297 supersets removed from queue.
  [FULL ] [1, 71, 4, 7] -> Rank: 7/7 (Params: 383)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 3, 63, 7] -> Rank: 7/7 (Params: 633)
    [Upward Pruned] 74 supersets removed from queue.
  [FULL ] [1, 60, 3, 7] -> Rank: 7/7 (Params: 261)
    [Upward Pruned] 38 supersets removed from queue.
  [FULL ] [1, 165, 2, 7] -> Rank: 7/7 (Params: 509)
    [Upward Pruned] 135 supersets removed from queue.
  [FULL ] [1, 2, 92, 7] -> Rank: 7/7 (Params: 830)
    [Upward Pruned] 45 supersets removed from queue.
  [FULL ] [1, 20, 2, 7] -> Rank: 7/7 (Params: 74)
    [Upward Pruned] 264 supersets removed from queue.
  [FULL ] [1, 2, 62, 7] -> Rank: 7/7 (Params: 560)
    [Upward Pruned] 30 supersets removed from queue.
  [FULL ] [1, 2, 24, 7] -> Rank: 7/7 (Params: 218)
    [Upward Pruned] 75 supersets removed from queue.
  [FULL ] [1, 2, 17, 7] -> Rank: 7/7 (Params: 155)
    [Upward Pruned] 13 supersets removed from queue.
  [FULL ] [1, 14, 5, 7] -> Rank: 7/7 (Params: 119)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 3, 14, 7] -> Rank: 7/7 (Params: 143)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 2, 13, 7] -> Rank: 7/7 (Params: 119)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 3, 9, 7] -> Rank: 7/7 (Params: 93)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 17, 2, 7] -> Rank: 7/7 (Params: 65)
    [Upward Pruned] 8 supersets removed from queue.
  [FULL ] [1, 2, 7, 7] -> Rank: 7/7 (Params: 65)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 5, 3, 7] -> Rank: 7/7 (Params: 41)
    [Upward Pruned] 32 supersets removed from queue.
  [FULL ] [1, 2, 5, 7] -> Rank: 7/7 (Params: 47)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 14, 2, 7] -> Rank: 7/7 (Params: 56)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 3, 3, 7] -> Rank: 7/7 (Params: 33)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 2, 4, 7] -> Rank: 7/7 (Params: 38)
  [FULL ] [1, 13, 2, 7] -> Rank: 7/7 (Params: 53)
  [FULL ] [1, 4, 2, 7] -> Rank: 7/7 (Params: 26)
    [Upward Pruned] 8 supersets removed from queue.
  [FULL ] [1, 2, 3, 7] -> Rank: 7/7 (Params: 29)
  [FULL ] [1, 2, 2, 7] -> Rank: 7/7 (Params: 20)
    [Upward Pruned] 1 supersets removed from queue.

Added 55 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_7_r5_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=6 ---
  Target Ambient Dimension: 7
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 230, 7] -> Rank: 7/7 (Params: 1840)
    [Upward Pruned] 70 supersets removed from queue.
  [FULL ] [1, 187, 7] -> Rank: 7/7 (Params: 1496)
    [Upward Pruned] 42 supersets removed from queue.
  [FULL ] [1, 35, 7] -> Rank: 7/7 (Params: 280)
    [Upward Pruned] 151 supersets removed from queue.
  [FULL ] [1, 10, 7] -> Rank: 7/7 (Params: 80)
    [Upward Pruned] 24 supersets removed from queue.
  [FULL ] [1, 8, 7] -> Rank: 7/7 (Params: 64)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 5, 7] -> Rank: 7/7 (Params: 40)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 2, 7] -> Rank: 7/7 (Params: 16)
    [Upward Pruned] 2 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=6 ---
  Target Ambient Dimension: 7
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 177, 44, 7] -> Rank: 7/7 (Params: 8273)
    [Upward Pruned] 31867 supersets removed from queue.
  [FULL ] [1, 85, 139, 7] -> Rank: 7/7 (Params: 12873)
    [Upward Pruned] 14903 supersets removed from queue.
  [FULL ] [1, 38, 290, 7] -> Rank: 7/7 (Params: 13088)
    [Upward Pruned] 516 supersets removed from queue.
  [FULL ] [1, 88, 8, 7] -> Rank: 7/7 (Params: 848)
    [Upward Pruned] 16122 supersets removed from queue.
  [FULL ] [1, 57, 225, 7] -> Rank: 7/7 (Params: 14457)
    [Upward Pruned] 1819 supersets removed from queue.
  [FULL ] [1, 60, 74, 7] -> Rank: 7/7 (Params: 5018)
    [Upward Pruned] 3969 supersets removed from queue.
  [FULL ] [1, 84, 64, 7] -> Rank: 7/7 (Params: 5908)
    [Upward Pruned] 39 supersets removed from queue.
  [FULL ] [1, 75, 25, 7] -> Rank: 7/7 (Params: 2125)
    [Upward Pruned] 596 supersets removed from queue.
  [FULL ] [1, 24, 292, 7] -> Rank: 7/7 (Params: 9076)
    [Upward Pruned] 125 supersets removed from queue.
  [FULL ] [1, 71, 5, 7] -> Rank: 7/7 (Params: 461)
    [Upward Pruned] 1174 supersets removed from queue.
  [FULL ] [1, 52, 154, 7] -> Rank: 7/7 (Params: 9138)
    [Upward Pruned] 892 supersets removed from queue.
  [FULL ] [1, 67, 37, 7] -> Rank: 7/7 (Params: 2805)
    [Upward Pruned] 147 supersets removed from queue.
  [FULL ] [1, 44, 110, 7] -> Rank: 7/7 (Params: 5654)
    [Upward Pruned] 1791 supersets removed from queue.
  [FULL ] [1, 46, 33, 7] -> Rank: 7/7 (Params: 1795)
    [Upward Pruned] 1380 supersets removed from queue.
  [FULL ] [1, 38, 229, 7] -> Rank: 7/7 (Params: 10343)
    [Upward Pruned] 365 supersets removed from queue.
  [FULL ] [1, 20, 84, 7] -> Rank: 7/7 (Params: 2288)
    [Upward Pruned] 4701 supersets removed from queue.
  [FULL ] [1, 48, 31, 7] -> Rank: 7/7 (Params: 1753)
    [Upward Pruned] 45 supersets removed from queue.
  [FULL ] [1, 13, 172, 7] -> Rank: 7/7 (Params: 3453)
    [Upward Pruned] 902 supersets removed from queue.
  [FULL ] [1, 10, 195, 7] -> Rank: 7/7 (Params: 3325)
    [Upward Pruned] 317 supersets removed from queue.
  [FULL ] [1, 14, 4, 7] -> Rank: 7/7 (Params: 98)
    [Upward Pruned] 3996 supersets removed from queue.
  [FULL ] [1, 11, 155, 7] -> Rank: 7/7 (Params: 2801)
    [Upward Pruned] 96 supersets removed from queue.
  [FULL ] [1, 4, 88, 7] -> Rank: 7/7 (Params: 972)
    [Upward Pruned] 1585 supersets removed from queue.
  [FULL ] [1, 3, 33, 7] -> Rank: 7/7 (Params: 333)
    [Upward Pruned] 817 supersets removed from queue.
  [FULL ] [1, 2, 60, 7] -> Rank: 7/7 (Params: 542)
    [Upward Pruned] 240 supersets removed from queue.
  [FULL ] [1, 3, 4, 7] -> Rank: 7/7 (Params: 43)
    [Upward Pruned] 318 supersets removed from queue.
  [FULL ] [1, 244, 3, 7] -> Rank: 7/7 (Params: 997)
    [Upward Pruned] 56 supersets removed from queue.
  [FULL ] [1, 82, 2, 7] -> Rank: 7/7 (Params: 260)
    [Upward Pruned] 380 supersets removed from queue.
  [FULL ] [1, 81, 3, 7] -> Rank: 7/7 (Params: 345)
  [FULL ] [1, 59, 2, 7] -> Rank: 7/7 (Params: 191)
    [Upward Pruned] 44 supersets removed from queue.
  [FULL ] [1, 42, 3, 7] -> Rank: 7/7 (Params: 189)
    [Upward Pruned] 16 supersets removed from queue.
  [FULL ] [1, 16, 2, 7] -> Rank: 7/7 (Params: 62)
    [Upward Pruned] 68 supersets removed from queue.
  [FULL ] [1, 2, 49, 7] -> Rank: 7/7 (Params: 443)
    [Upward Pruned] 10 supersets removed from queue.
  [FULL ] [1, 2, 36, 7] -> Rank: 7/7 (Params: 326)
    [Upward Pruned] 12 supersets removed from queue.
  [FULL ] [1, 7, 2, 7] -> Rank: 7/7 (Params: 35)
    [Upward Pruned] 17 supersets removed from queue.
  [FULL ] [1, 2, 4, 7] -> Rank: 7/7 (Params: 38)
    [Upward Pruned] 31 supersets removed from queue.
  [FULL ] [1, 2, 3, 7] -> Rank: 7/7 (Params: 29)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 5, 2, 7] -> Rank: 7/7 (Params: 29)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 3, 2, 7] -> Rank: 7/7 (Params: 23)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 2, 7] -> Rank: 7/7 (Params: 20)

Added 46 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_7_r6_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=7 ---
  Target Ambient Dimension: 7
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 14, 7] -> Rank: 7/7 (Params: 112)
    [Upward Pruned] 286 supersets removed from queue.
  [FULL ] [1, 4, 7] -> Rank: 7/7 (Params: 32)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 2, 7] -> Rank: 7/7 (Params: 16)
    [Upward Pruned] 1 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=7 ---
  Target Ambient Dimension: 7
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 59, 112, 7] -> Rank: 7/7 (Params: 7451)
    [Upward Pruned] 45737 supersets removed from queue.
  [FULL ] [1, 12, 109, 7] -> Rank: 7/7 (Params: 2083)
    [Upward Pruned] 9749 supersets removed from queue.
  [FULL ] [1, 283, 37, 7] -> Rank: 7/7 (Params: 11013)
    [Upward Pruned] 1295 supersets removed from queue.
  [FULL ] [1, 120, 91, 7] -> Rank: 7/7 (Params: 11677)
    [Upward Pruned] 2933 supersets removed from queue.
  [FULL ] [1, 66, 73, 7] -> Rank: 7/7 (Params: 5395)
    [Upward Pruned] 4877 supersets removed from queue.
  [FULL ] [1, 177, 41, 7] -> Rank: 7/7 (Params: 7721)
    [Upward Pruned] 3391 supersets removed from queue.
  [FULL ] [1, 235, 3, 7] -> Rank: 7/7 (Params: 961)
    [Upward Pruned] 2435 supersets removed from queue.
  [FULL ] [1, 234, 20, 7] -> Rank: 7/7 (Params: 5054)
    [Upward Pruned] 20 supersets removed from queue.
  [FULL ] [1, 50, 94, 7] -> Rank: 7/7 (Params: 5408)
    [Upward Pruned] 239 supersets removed from queue.
  [FULL ] [1, 145, 12, 7] -> Rank: 7/7 (Params: 1969)
    [Upward Pruned] 3612 supersets removed from queue.
  [FULL ] [1, 131, 9, 7] -> Rank: 7/7 (Params: 1373)
    [Upward Pruned] 1165 supersets removed from queue.
  [FULL ] [1, 3, 197, 7] -> Rank: 7/7 (Params: 1973)
    [Upward Pruned] 935 supersets removed from queue.
  [FULL ] [1, 9, 137, 7] -> Rank: 7/7 (Params: 2201)
    [Upward Pruned] 179 supersets removed from queue.
  [FULL ] [1, 13, 71, 7] -> Rank: 7/7 (Params: 1433)
    [Upward Pruned] 1903 supersets removed from queue.
  [FULL ] [1, 97, 18, 7] -> Rank: 7/7 (Params: 1969)
    [Upward Pruned] 1801 supersets removed from queue.
  [FULL ] [1, 13, 53, 7] -> Rank: 7/7 (Params: 1073)
    [Upward Pruned] 1511 supersets removed from queue.
  [FULL ] [1, 144, 3, 7] -> Rank: 7/7 (Params: 597)
    [Upward Pruned] 545 supersets removed from queue.
  [FULL ] [1, 7, 101, 7] -> Rank: 7/7 (Params: 1421)
    [Upward Pruned] 307 supersets removed from queue.
  [FULL ] [1, 125, 8, 7] -> Rank: 7/7 (Params: 1181)
    [Upward Pruned] 72 supersets removed from queue.
  [FULL ] [1, 73, 34, 7] -> Rank: 7/7 (Params: 2793)
    [Upward Pruned] 455 supersets removed from queue.
  [FULL ] [1, 55, 16, 7] -> Rank: 7/7 (Params: 1047)
    [Upward Pruned] 1153 supersets removed from queue.
  [FULL ] [1, 86, 10, 7] -> Rank: 7/7 (Params: 1016)
    [Upward Pruned] 233 supersets removed from queue.
  [FULL ] [1, 7, 19, 7] -> Rank: 7/7 (Params: 273)
    [Upward Pruned] 1919 supersets removed from queue.
  [FULL ] [1, 2, 266, 7] -> Rank: 7/7 (Params: 2396)
    [Upward Pruned] 34 supersets removed from queue.
  [FULL ] [1, 45, 5, 7] -> Rank: 7/7 (Params: 305)
    [Upward Pruned] 732 supersets removed from queue.
  [FULL ] [1, 50, 3, 7] -> Rank: 7/7 (Params: 221)
    [Upward Pruned] 187 supersets removed from queue.
  [FULL ] [1, 19, 2, 7] -> Rank: 7/7 (Params: 71)
    [Upward Pruned] 707 supersets removed from queue.
  [FULL ] [1, 10, 11, 7] -> Rank: 7/7 (Params: 197)
    [Upward Pruned] 71 supersets removed from queue.
  [FULL ] [1, 2, 22, 7] -> Rank: 7/7 (Params: 200)
    [Upward Pruned] 943 supersets removed from queue.
  [FULL ] [1, 11, 8, 7] -> Rank: 7/7 (Params: 155)
    [Upward Pruned] 23 supersets removed from queue.
  [FULL ] [1, 2, 4, 7] -> Rank: 7/7 (Params: 38)
    [Upward Pruned] 173 supersets removed from queue.
  [FULL ] [1, 15, 2, 7] -> Rank: 7/7 (Params: 59)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 14, 3, 7] -> Rank: 7/7 (Params: 77)
  [FULL ] [1, 6, 2, 7] -> Rank: 7/7 (Params: 32)
    [Upward Pruned] 16 supersets removed from queue.
  [FULL ] [1, 2, 2, 7] -> Rank: 7/7 (Params: 20)
    [Upward Pruned] 7 supersets removed from queue.

Added 38 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_7_r7_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=8 ---
  Target Ambient Dimension: 7
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 150, 7] -> Rank: 7/7 (Params: 1200)
    [Upward Pruned] 150 supersets removed from queue.
  [FULL ] [1, 50, 7] -> Rank: 7/7 (Params: 400)
    [Upward Pruned] 99 supersets removed from queue.
  [FULL ] [1, 20, 7] -> Rank: 7/7 (Params: 160)
    [Upward Pruned] 29 supersets removed from queue.
  [FULL ] [1, 18, 7] -> Rank: 7/7 (Params: 144)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 9, 7] -> Rank: 7/7 (Params: 72)
    [Upward Pruned] 8 supersets removed from queue.
  [FULL ] [1, 4, 7] -> Rank: 7/7 (Params: 32)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 3, 7] -> Rank: 7/7 (Params: 24)
  [FULL ] [1, 2, 7] -> Rank: 7/7 (Params: 16)

--- RANDOM SEARCH: h=3, exponent=8 ---
  Target Ambient Dimension: 7
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 214, 65, 7] -> Rank: 7/7 (Params: 14579)
    [Upward Pruned] 20531 supersets removed from queue.
  [FULL ] [1, 90, 254, 7] -> Rank: 7/7 (Params: 24728)
    [Upward Pruned] 5827 supersets removed from queue.
  [FULL ] [1, 33, 208, 7] -> Rank: 7/7 (Params: 8353)
    [Upward Pruned] 11004 supersets removed from queue.
  [FULL ] [1, 6, 253, 7] -> Rank: 7/7 (Params: 3295)
    [Upward Pruned] 1295 supersets removed from queue.
  [FULL ] [1, 132, 42, 7] -> Rank: 7/7 (Params: 5970)
    [Upward Pruned] 15612 supersets removed from queue.
  [FULL ] [1, 67, 51, 7] -> Rank: 7/7 (Params: 3841)
    [Upward Pruned] 10204 supersets removed from queue.
  [FULL ] [1, 52, 162, 7] -> Rank: 7/7 (Params: 9610)
    [Upward Pruned] 689 supersets removed from queue.
  [FULL ] [1, 26, 186, 7] -> Rank: 7/7 (Params: 6164)
    [Upward Pruned] 886 supersets removed from queue.
  [FULL ] [1, 179, 16, 7] -> Rank: 7/7 (Params: 3155)
    [Upward Pruned] 3171 supersets removed from queue.
  [FULL ] [1, 34, 7, 7] -> Rank: 7/7 (Params: 321)
    [Upward Pruned] 11149 supersets removed from queue.
  [FULL ] [1, 11, 219, 7] -> Rank: 7/7 (Params: 3953)
    [Upward Pruned] 509 supersets removed from queue.
  [FULL ] [1, 10, 71, 7] -> Rank: 7/7 (Params: 1217)
    [Upward Pruned] 3321 supersets removed from queue.
  [FULL ] [1, 2, 188, 7] -> Rank: 7/7 (Params: 1694)
    [Upward Pruned] 711 supersets removed from queue.
  [FULL ] [1, 72, 5, 7] -> Rank: 7/7 (Params: 467)
    [Upward Pruned] 457 supersets removed from queue.
  [FULL ] [1, 11, 31, 7] -> Rank: 7/7 (Params: 569)
    [Upward Pruned] 919 supersets removed from queue.
  [FULL ] [1, 2, 79, 7] -> Rank: 7/7 (Params: 713)
    [Upward Pruned] 871 supersets removed from queue.
  [FULL ] [1, 66, 3, 7] -> Rank: 7/7 (Params: 285)
    [Upward Pruned] 481 supersets removed from queue.
  [FULL ] [1, 4, 65, 7] -> Rank: 7/7 (Params: 719)
    [Upward Pruned] 89 supersets removed from queue.
  [FULL ] [1, 50, 4, 7] -> Rank: 7/7 (Params: 278)
    [Upward Pruned] 47 supersets removed from queue.
  [FULL ] [1, 32, 25, 7] -> Rank: 7/7 (Params: 1007)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 26, 24, 7] -> Rank: 7/7 (Params: 818)
    [Upward Pruned] 43 supersets removed from queue.
  [FULL ] [1, 10, 3, 7] -> Rank: 7/7 (Params: 61)
    [Upward Pruned] 729 supersets removed from queue.
  [FULL ] [1, 7, 16, 7] -> Rank: 7/7 (Params: 231)
    [Upward Pruned] 146 supersets removed from queue.
  [FULL ] [1, 4, 53, 7] -> Rank: 7/7 (Params: 587)
    [Upward Pruned] 35 supersets removed from queue.
  [FULL ] [1, 6, 8, 7] -> Rank: 7/7 (Params: 110)
    [Upward Pruned] 68 supersets removed from queue.
  [FULL ] [1, 2, 41, 7] -> Rank: 7/7 (Params: 371)
    [Upward Pruned] 99 supersets removed from queue.
  [FULL ] [1, 117, 2, 7] -> Rank: 7/7 (Params: 365)
    [Upward Pruned] 183 supersets removed from queue.
  [FULL ] [1, 3, 12, 7] -> Rank: 7/7 (Params: 123)
    [Upward Pruned] 86 supersets removed from queue.
  [FULL ] [1, 36, 2, 7] -> Rank: 7/7 (Params: 122)
    [Upward Pruned] 80 supersets removed from queue.
  [FULL ] [1, 28, 2, 7] -> Rank: 7/7 (Params: 98)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 6, 3, 7] -> Rank: 7/7 (Params: 45)
    [Upward Pruned] 19 supersets removed from queue.
  [FULL ] [1, 2, 33, 7] -> Rank: 7/7 (Params: 299)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 5, 9, 7] -> Rank: 7/7 (Params: 113)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 2, 21, 7] -> Rank: 7/7 (Params: 191)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 2, 16, 7] -> Rank: 7/7 (Params: 146)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 23, 2, 7] -> Rank: 7/7 (Params: 83)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 3, 10, 7] -> Rank: 7/7 (Params: 103)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 21, 2, 7] -> Rank: 7/7 (Params: 77)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 4, 4, 7] -> Rank: 7/7 (Params: 48)
    [Upward Pruned] 10 supersets removed from queue.
  [FULL ] [1, 7, 2, 7] -> Rank: 7/7 (Params: 35)
    [Upward Pruned] 13 supersets removed from queue.
  [FULL ] [1, 3, 9, 7] -> Rank: 7/7 (Params: 93)
  [FULL ] [1, 2, 3, 7] -> Rank: 7/7 (Params: 29)
    [Upward Pruned] 20 supersets removed from queue.
  [FULL ] [1, 3, 2, 7] -> Rank: 7/7 (Params: 23)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 2, 2, 7] -> Rank: 7/7 (Params: 20)

Added 52 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_7_r8_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=9 ---
  Target Ambient Dimension: 7
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 78, 7] -> Rank: 7/7 (Params: 624)
    [Upward Pruned] 222 supersets removed from queue.
  [FULL ] [1, 14, 7] -> Rank: 7/7 (Params: 112)
    [Upward Pruned] 63 supersets removed from queue.

  [FULL ] [1, 6, 7] -> Rank: 7/7 (Params: 48)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 3, 7] -> Rank: 7/7 (Params: 24)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 2, 7] -> Rank: 7/7 (Params: 16)

--- RANDOM SEARCH: h=3, exponent=9 ---
  Target Ambient Dimension: 7
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 272, 88, 7] -> Rank: 7/7 (Params: 24824)
    [Upward Pruned] 6176 supersets removed from queue.
  [FULL ] [1, 49, 49, 7] -> Rank: 7/7 (Params: 2793)
    [Upward Pruned] 57326 supersets removed from queue.
  [FULL ] [1, 132, 30, 7] -> Rank: 7/7 (Params: 4302)
    [Upward Pruned] 3210 supersets removed from queue.
  [FULL ] [1, 15, 44, 7] -> Rank: 7/7 (Params: 983)
    [Upward Pruned] 9152 supersets removed from queue.
  [FULL ] [1, 2, 141, 7] -> Rank: 7/7 (Params: 1271)
    [Upward Pruned] 2079 supersets removed from queue.
  [FULL ] [1, 105, 28, 7] -> Rank: 7/7 (Params: 3241)
    [Upward Pruned] 769 supersets removed from queue.
  [FULL ] [1, 75, 11, 7] -> Rank: 7/7 (Params: 977)
    [Upward Pruned] 4321 supersets removed from queue.
  [FULL ] [1, 57, 10, 7] -> Rank: 7/7 (Params: 697)
    [Upward Pruned] 837 supersets removed from queue.
  [FULL ] [1, 13, 98, 7] -> Rank: 7/7 (Params: 1973)
    [Upward Pruned] 85 supersets removed from queue.
  [FULL ] [1, 52, 25, 7] -> Rank: 7/7 (Params: 1527)
    [Upward Pruned] 94 supersets removed from queue.
  [FULL ] [1, 56, 23, 7] -> Rank: 7/7 (Params: 1505)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 112, 6, 7] -> Rank: 7/7 (Params: 826)
    [Upward Pruned] 755 supersets removed from queue.
  [FULL ] [1, 12, 93, 7] -> Rank: 7/7 (Params: 1779)
    [Upward Pruned] 57 supersets removed from queue.
  [FULL ] [1, 2, 40, 7] -> Rank: 7/7 (Params: 362)
    [Upward Pruned] 1316 supersets removed from queue.
  [FULL ] [1, 20, 16, 7] -> Rank: 7/7 (Params: 452)
    [Upward Pruned] 810 supersets removed from queue.
  [FULL ] [1, 78, 9, 7] -> Rank: 7/7 (Params: 843)
    [Upward Pruned] 33 supersets removed from queue.
  [FULL ] [1, 30, 8, 7] -> Rank: 7/7 (Params: 326)
    [Upward Pruned] 291 supersets removed from queue.
  [FULL ] [1, 18, 19, 7] -> Rank: 7/7 (Params: 493)
    [Upward Pruned] 41 supersets removed from queue.
  [FULL ] [1, 17, 14, 7] -> Rank: 7/7 (Params: 353)
    [Upward Pruned] 55 supersets removed from queue.
  [FULL ] [1, 158, 4, 7] -> Rank: 7/7 (Params: 818)
    [Upward Pruned] 285 supersets removed from queue.
  [FULL ] [1, 46, 4, 7] -> Rank: 7/7 (Params: 258)
    [Upward Pruned] 355 supersets removed from queue.
  [FULL ] [1, 139, 2, 7] -> Rank: 7/7 (Params: 431)
    [Upward Pruned] 323 supersets removed from queue.
  [FULL ] [1, 75, 3, 7] -> Rank: 7/7 (Params: 321)
    [Upward Pruned] 63 supersets removed from queue.
  [FULL ] [1, 26, 3, 7] -> Rank: 7/7 (Params: 125)
    [Upward Pruned] 152 supersets removed from queue.
  [FULL ] [1, 12, 24, 7] -> Rank: 7/7 (Params: 468)
    [Upward Pruned] 79 supersets removed from queue.
  [FULL ] [1, 8, 27, 7] -> Rank: 7/7 (Params: 413)
    [Upward Pruned] 51 supersets removed from queue.
  [FULL ] [1, 33, 2, 7] -> Rank: 7/7 (Params: 113)
    [Upward Pruned] 105 supersets removed from queue.
  [FULL ] [1, 3, 11, 7] -> Rank: 7/7 (Params: 113)
    [Upward Pruned] 300 supersets removed from queue.
  [FULL ] [1, 31, 2, 7] -> Rank: 7/7 (Params: 107)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 11, 10, 7] -> Rank: 7/7 (Params: 191)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 8, 10, 7] -> Rank: 7/7 (Params: 158)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 6, 9, 7] -> Rank: 7/7 (Params: 123)
    [Upward Pruned] 21 supersets removed from queue.
  [FULL ] [1, 25, 5, 7] -> Rank: 7/7 (Params: 185)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 18, 7, 7] -> Rank: 7/7 (Params: 193)
    [Upward Pruned] 13 supersets removed from queue.
  [FULL ] [1, 6, 6, 7] -> Rank: 7/7 (Params: 84)
    [Upward Pruned] 42 supersets removed from queue.
  [FULL ] [1, 2, 36, 7] -> Rank: 7/7 (Params: 326)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 5, 9, 7] -> Rank: 7/7 (Params: 113)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 16, 2, 7] -> Rank: 7/7 (Params: 62)
    [Upward Pruned] 43 supersets removed from queue.
  [FULL ] [1, 6, 5, 7] -> Rank: 7/7 (Params: 71)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 15, 4, 7] -> Rank: 7/7 (Params: 103)
  [FULL ] [1, 14, 3, 7] -> Rank: 7/7 (Params: 77)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 2, 15, 7] -> Rank: 7/7 (Params: 137)
    [Upward Pruned] 20 supersets removed from queue.
  [FULL ] [1, 4, 4, 7] -> Rank: 7/7 (Params: 48)
    [Upward Pruned] 19 supersets removed from queue.
  [FULL ] [1, 3, 7, 7] -> Rank: 7/7 (Params: 73)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 14, 2, 7] -> Rank: 7/7 (Params: 56)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 5, 3, 7] -> Rank: 7/7 (Params: 41)
    [Upward Pruned] 8 supersets removed from queue.
  [FULL ] [1, 13, 2, 7] -> Rank: 7/7 (Params: 53)
  [FULL ] [1, 7, 2, 7] -> Rank: 7/7 (Params: 35)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 2, 3, 7] -> Rank: 7/7 (Params: 29)
    [Upward Pruned] 16 supersets removed from queue.
  [FULL ] [1, 3, 2, 7] -> Rank: 7/7 (Params: 23)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 2, 2, 7] -> Rank: 7/7 (Params: 20)

Added 56 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_7_r9_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=1 ---
  Target Ambient Dimension: 8
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.

  [FULL ] [1, 163, 8] -> Rank: 8/8 (Params: 1467)
    [Upward Pruned] 137 supersets removed from queue.
  [FULL ] [1, 9, 8] -> Rank: 8/8 (Params: 81)
    [Upward Pruned] 153 supersets removed from queue.
  [FULL ] [1, 8, 8] -> Rank: 8/8 (Params: 72)
  [FULL ] [1, 7, 8] -> Rank: 8/8 (Params: 63)
  [FULL ] [1, 6, 8] -> Rank: 8/8 (Params: 54)
  [FULL ] [1, 5, 8] -> Rank: 8/8 (Params: 45)
  [FULL ] [1, 2, 8] -> Rank: 8/8 (Params: 18)
    [Upward Pruned] 2 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=1 ---
  Target Ambient Dimension: 8
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 75, 196, 8] -> Rank: 8/8 (Params: 16343)
    [Upward Pruned] 23729 supersets removed from queue.
  [FULL ] [1, 125, 134, 8] -> Rank: 8/8 (Params: 17947)
    [Upward Pruned] 10911 supersets removed from queue.
  [FULL ] [1, 224, 117, 8] -> Rank: 8/8 (Params: 27368)
    [Upward Pruned] 1308 supersets removed from queue.
  [FULL ] [1, 90, 90, 8] -> Rank: 8/8 (Params: 8910)
    [Upward Pruned] 10144 supersets removed from queue.
  [FULL ] [1, 17, 249, 8] -> Rank: 8/8 (Params: 6242)
    [Upward Pruned] 3015 supersets removed from queue.
  [FULL ] [1, 70, 104, 8] -> Rank: 8/8 (Params: 8182)
    [Upward Pruned] 2104 supersets removed from queue.
  [FULL ] [1, 9, 181, 8] -> Rank: 8/8 (Params: 3086)
    [Upward Pruned] 4563 supersets removed from queue.
  [FULL ] [1, 159, 44, 8] -> Rank: 8/8 (Params: 7507)
    [Upward Pruned] 6531 supersets removed from queue.
  [FULL ] [1, 24, 121, 8] -> Rank: 8/8 (Params: 3896)
    [Upward Pruned] 2759 supersets removed from queue.
  [FULL ] [1, 126, 70, 8] -> Rank: 8/8 (Params: 9506)
    [Upward Pruned] 659 supersets removed from queue.
  [FULL ] [1, 20, 114, 8] -> Rank: 8/8 (Params: 3212)
    [Upward Pruned] 589 supersets removed from queue.
  [FULL ] [1, 31, 2, 8] -> Rank: 8/8 (Params: 109)
    [Upward Pruned] 17783 supersets removed from queue.
  [FULL ] [1, 13, 33, 8] -> Rank: 8/8 (Params: 706)
    [Upward Pruned] 1926 supersets removed from queue.
  [FULL ] [1, 4, 90, 8] -> Rank: 8/8 (Params: 1084)
    [Upward Pruned] 1418 supersets removed from queue.
  [FULL ] [1, 21, 26, 8] -> Rank: 8/8 (Params: 775)
    [Upward Pruned] 69 supersets removed from queue.
  [FULL ] [1, 4, 40, 8] -> Rank: 8/8 (Params: 484)
    [Upward Pruned] 449 supersets removed from queue.
  [FULL ] [1, 13, 29, 8] -> Rank: 8/8 (Params: 622)
    [Upward Pruned] 31 supersets removed from queue.
  [FULL ] [1, 18, 15, 8] -> Rank: 8/8 (Params: 408)
    [Upward Pruned] 151 supersets removed from queue.
  [FULL ] [1, 5, 21, 8] -> Rank: 8/8 (Params: 278)
    [Upward Pruned] 191 supersets removed from queue.
  [FULL ] [1, 2, 113, 8] -> Rank: 8/8 (Params: 1132)
    [Upward Pruned] 375 supersets removed from queue.
  [FULL ] [1, 2, 112, 8] -> Rank: 8/8 (Params: 1122)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 10, 17, 8] -> Rank: 8/8 (Params: 316)
    [Upward Pruned] 31 supersets removed from queue.
  [FULL ] [1, 11, 11, 8] -> Rank: 8/8 (Params: 220)
    [Upward Pruned] 93 supersets removed from queue.
  [FULL ] [1, 2, 69, 8] -> Rank: 8/8 (Params: 692)
    [Upward Pruned] 85 supersets removed from queue.
  [FULL ] [1, 3, 61, 8] -> Rank: 8/8 (Params: 674)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 29, 5, 8] -> Rank: 8/8 (Params: 214)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 2, 6, 8] -> Rank: 8/8 (Params: 62)
    [Upward Pruned] 327 supersets removed from queue.
  [FULL ] [1, 25, 4, 8] -> Rank: 8/8 (Params: 157)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 21, 4, 8] -> Rank: 8/8 (Params: 137)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 6, 5, 8] -> Rank: 8/8 (Params: 76)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 16, 2, 8] -> Rank: 8/8 (Params: 64)
    [Upward Pruned] 34 supersets removed from queue.
  [FULL ] [1, 11, 2, 8] -> Rank: 8/8 (Params: 49)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 9, 3, 8] -> Rank: 8/8 (Params: 60)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 6, 4, 8] -> Rank: 8/8 (Params: 62)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 3, 4, 8] -> Rank: 8/8 (Params: 47)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 2, 2, 8] -> Rank: 8/8 (Params: 22)
    [Upward Pruned] 17 supersets removed from queue.

Added 43 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_8_r1_architectures.csv'.

Loading existing database from '../data/raw/1_8_r2_architectures.csv'...

--- RANDOM SEARCH: h=2, exponent=2 ---
  Target Ambient Dimension: 8
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 292 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.

--- RANDOM SEARCH: h=3, exponent=2 ---
  Target Ambient Dimension: 8
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 89369 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_8_r2_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=3 ---
  Target Ambient Dimension: 8
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 129, 8] -> Rank: 8/8 (Params: 1161)
    [Upward Pruned] 171 supersets removed from queue.
  [FULL ] [1, 101, 8] -> Rank: 8/8 (Params: 909)
    [Upward Pruned] 27 supersets removed from queue.
  [FULL ] [1, 91, 8] -> Rank: 8/8 (Params: 819)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 22, 8] -> Rank: 8/8 (Params: 198)
    [Upward Pruned] 68 supersets removed from queue.
  [FULL ] [1, 6, 8] -> Rank: 8/8 (Params: 54)
    [Upward Pruned] 15 supersets removed from queue.
  [FULL ] [1, 4, 8] -> Rank: 8/8 (Params: 36)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 8] -> Rank: 8/8 (Params: 18)
    [Upward Pruned] 1 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=3 ---
  Target Ambient Dimension: 8
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 27, 41, 8] -> Rank: 8/8 (Params: 1462)
    [Upward Pruned] 71239 supersets removed from queue.
  [FULL ] [1, 223, 37, 8] -> Rank: 8/8 (Params: 8770)
    [Upward Pruned] 311 supersets removed from queue.
  [FULL ] [1, 41, 24, 8] -> Rank: 8/8 (Params: 1217)
    [Upward Pruned] 4107 supersets removed from queue.
  [FULL ] [1, 4, 96, 8] -> Rank: 8/8 (Params: 1156)
    [Upward Pruned] 4714 supersets removed from queue.
  [FULL ] [1, 10, 84, 8] -> Rank: 8/8 (Params: 1522)
    [Upward Pruned] 203 supersets removed from queue.
  [FULL ] [1, 26, 17, 8] -> Rank: 8/8 (Params: 604)
    [Upward Pruned] 2222 supersets removed from queue.
  [FULL ] [1, 18, 51, 8] -> Rank: 8/8 (Params: 1344)
    [Upward Pruned] 263 supersets removed from queue.
  [FULL ] [1, 2, 134, 8] -> Rank: 8/8 (Params: 1342)
    [Upward Pruned] 333 supersets removed from queue.
  [FULL ] [1, 20, 43, 8] -> Rank: 8/8 (Params: 1224)
    [Upward Pruned] 47 supersets removed from queue.
  [FULL ] [1, 291, 14, 8] -> Rank: 8/8 (Params: 4477)
    [Upward Pruned] 29 supersets removed from queue.
  [FULL ] [1, 61, 9, 8] -> Rank: 8/8 (Params: 682)
    [Upward Pruned] 1889 supersets removed from queue.
  [FULL ] [1, 247, 6, 8] -> Rank: 8/8 (Params: 1777)
    [Upward Pruned] 161 supersets removed from queue.
  [FULL ] [1, 156, 6, 8] -> Rank: 8/8 (Params: 1140)
    [Upward Pruned] 272 supersets removed from queue.
  [FULL ] [1, 234, 4, 8] -> Rank: 8/8 (Params: 1202)
    [Upward Pruned] 133 supersets removed from queue.
  [FULL ] [1, 297, 3, 8] -> Rank: 8/8 (Params: 1212)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 203, 3, 8] -> Rank: 8/8 (Params: 836)
    [Upward Pruned] 155 supersets removed from queue.
  [FULL ] [1, 23, 16, 8] -> Rank: 8/8 (Params: 519)
    [Upward Pruned] 115 supersets removed from queue.
  [FULL ] [1, 9, 56, 8] -> Rank: 8/8 (Params: 961)
    [Upward Pruned] 263 supersets removed from queue.
  [FULL ] [1, 6, 83, 8] -> Rank: 8/8 (Params: 1168)
    [Upward Pruned] 38 supersets removed from queue.
  [FULL ] [1, 93, 5, 8] -> Rank: 8/8 (Params: 598)
    [Upward Pruned] 298 supersets removed from queue.
  [FULL ] [1, 8, 53, 8] -> Rank: 8/8 (Params: 856)
    [Upward Pruned] 56 supersets removed from queue.
  [FULL ] [1, 4, 92, 8] -> Rank: 8/8 (Params: 1108)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 4, 35, 8] -> Rank: 8/8 (Params: 424)
    [Upward Pruned] 445 supersets removed from queue.
  [FULL ] [1, 3, 132, 8] -> Rank: 8/8 (Params: 1455)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 126, 3, 8] -> Rank: 8/8 (Params: 528)
    [Upward Pruned] 153 supersets removed from queue.
  [FULL ] [1, 81, 8, 8] -> Rank: 8/8 (Params: 793)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 77, 4, 8] -> Rank: 8/8 (Params: 417)
    [Upward Pruned] 100 supersets removed from queue.
  [FULL ] [1, 74, 6, 8] -> Rank: 8/8 (Params: 566)
    [Upward Pruned] 8 supersets removed from queue.
  [FULL ] [1, 4, 19, 8] -> Rank: 8/8 (Params: 232)
    [Upward Pruned] 303 supersets removed from queue.
  [FULL ] [1, 2, 44, 8] -> Rank: 8/8 (Params: 442)
    [Upward Pruned] 177 supersets removed from queue.
  [FULL ] [1, 174, 2, 8] -> Rank: 8/8 (Params: 538)
    [Upward Pruned] 126 supersets removed from queue.
  [FULL ] [1, 80, 2, 8] -> Rank: 8/8 (Params: 256)
    [Upward Pruned] 139 supersets removed from queue.
  [FULL ] [1, 20, 4, 8] -> Rank: 8/8 (Params: 132)
    [Upward Pruned] 571 supersets removed from queue.
  [FULL ] [1, 3, 4, 8] -> Rank: 8/8 (Params: 47)
    [Upward Pruned] 279 supersets removed from queue.
  [FULL ] [1, 3, 2, 8] -> Rank: 8/8 (Params: 25)
    [Upward Pruned] 153 supersets removed from queue.
  [FULL ] [1, 2, 34, 8] -> Rank: 8/8 (Params: 342)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 2, 28, 8] -> Rank: 8/8 (Params: 282)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 2, 10, 8] -> Rank: 8/8 (Params: 102)
    [Upward Pruned] 17 supersets removed from queue.
  [FULL ] [1, 2, 9, 8] -> Rank: 8/8 (Params: 92)
  [FULL ] [1, 2, 5, 8] -> Rank: 8/8 (Params: 52)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 2, 4, 8] -> Rank: 8/8 (Params: 42)
  [FULL ] [1, 2, 2, 8] -> Rank: 8/8 (Params: 22)
    [Upward Pruned] 1 supersets removed from queue.

Added 49 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_8_r3_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=4 ---
  Target Ambient Dimension: 8
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 258, 8] -> Rank: 8/8 (Params: 2322)
    [Upward Pruned] 42 supersets removed from queue.
  [FULL ] [1, 139, 8] -> Rank: 8/8 (Params: 1251)
    [Upward Pruned] 118 supersets removed from queue.
  [FULL ] [1, 78, 8] -> Rank: 8/8 (Params: 702)
    [Upward Pruned] 60 supersets removed from queue.

  [FULL ] [1, 10, 8] -> Rank: 8/8 (Params: 90)
    [Upward Pruned] 67 supersets removed from queue.
  [FULL ] [1, 8, 8] -> Rank: 8/8 (Params: 72)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 6, 8] -> Rank: 8/8 (Params: 54)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 3, 8] -> Rank: 8/8 (Params: 27)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 2, 8] -> Rank: 8/8 (Params: 18)

--- RANDOM SEARCH: h=3, exponent=4 ---
  Target Ambient Dimension: 8
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 149, 169, 8] -> Rank: 8/8 (Params: 26682)
    [Upward Pruned] 20063 supersets removed from queue.
  [FULL ] [1, 267, 84, 8] -> Rank: 8/8 (Params: 23367)
    [Upward Pruned] 2889 supersets removed from queue.
  [FULL ] [1, 22, 298, 8] -> Rank: 8/8 (Params: 8962)
    [Upward Pruned] 380 supersets removed from queue.
  [FULL ] [1, 110, 194, 8] -> Rank: 8/8 (Params: 23002)
    [Upward Pruned] 4055 supersets removed from queue.
  [FULL ] [1, 233, 6, 8] -> Rank: 8/8 (Params: 1679)
    [Upward Pruned] 8193 supersets removed from queue.
  [FULL ] [1, 142, 192, 8] -> Rank: 8/8 (Params: 28942)
    [Upward Pruned] 13 supersets removed from queue.
  [FULL ] [1, 141, 84, 8] -> Rank: 8/8 (Params: 12657)
    [Upward Pruned] 8005 supersets removed from queue.
  [FULL ] [1, 71, 46, 8] -> Rank: 8/8 (Params: 3705)
    [Upward Pruned] 17911 supersets removed from queue.
  [FULL ] [1, 61, 34, 8] -> Rank: 8/8 (Params: 2407)
    [Upward Pruned] 4583 supersets removed from queue.
  [FULL ] [1, 58, 261, 8] -> Rank: 8/8 (Params: 17284)
    [Upward Pruned] 110 supersets removed from queue.
  [FULL ] [1, 226, 30, 8] -> Rank: 8/8 (Params: 7246)
    [Upward Pruned] 27 supersets removed from queue.
  [FULL ] [1, 28, 250, 8] -> Rank: 8/8 (Params: 9028)
    [Upward Pruned] 1472 supersets removed from queue.
  [FULL ] [1, 31, 72, 8] -> Rank: 8/8 (Params: 2839)
    [Upward Pruned] 5339 supersets removed from queue.
  [FULL ] [1, 101, 18, 8] -> Rank: 8/8 (Params: 2063)
    [Upward Pruned] 2083 supersets removed from queue.
  [FULL ] [1, 14, 200, 8] -> Rank: 8/8 (Params: 4414)
    [Upward Pruned] 1545 supersets removed from queue.
  [FULL ] [1, 12, 255, 8] -> Rank: 8/8 (Params: 5112)
    [Upward Pruned] 91 supersets removed from queue.
  [FULL ] [1, 38, 58, 8] -> Rank: 8/8 (Params: 2706)
    [Upward Pruned] 321 supersets removed from queue.
  [FULL ] [1, 8, 215, 8] -> Rank: 8/8 (Params: 3448)
    [Upward Pruned] 423 supersets removed from queue.
  [FULL ] [1, 4, 169, 8] -> Rank: 8/8 (Params: 2032)
    [Upward Pruned] 1330 supersets removed from queue.
  [FULL ] [1, 227, 2, 8] -> Rank: 8/8 (Params: 697)
    [Upward Pruned] 367 supersets removed from queue.
  [FULL ] [1, 39, 50, 8] -> Rank: 8/8 (Params: 2389)
    [Upward Pruned] 175 supersets removed from queue.
  [FULL ] [1, 21, 76, 8] -> Rank: 8/8 (Params: 2225)
    [Upward Pruned] 929 supersets removed from queue.
  [FULL ] [1, 223, 6, 8] -> Rank: 8/8 (Params: 1609)
    [Upward Pruned] 47 supersets removed from queue.
  [FULL ] [1, 99, 9, 8] -> Rank: 8/8 (Params: 1062)
    [Upward Pruned] 1147 supersets removed from queue.
  [FULL ] [1, 14, 132, 8] -> Rank: 8/8 (Params: 2918)
    [Upward Pruned] 258 supersets removed from queue.
  [FULL ] [1, 2, 42, 8] -> Rank: 8/8 (Params: 422)
    [Upward Pruned] 3159 supersets removed from queue.
  [FULL ] [1, 14, 12, 8] -> Rank: 8/8 (Params: 278)
    [Upward Pruned] 2245 supersets removed from queue.
  [FULL ] [1, 133, 8, 8] -> Rank: 8/8 (Params: 1261)
    [Upward Pruned] 89 supersets removed from queue.
  [FULL ] [1, 145, 5, 8] -> Rank: 8/8 (Params: 910)
    [Upward Pruned] 237 supersets removed from queue.
  [FULL ] [1, 94, 3, 8] -> Rank: 8/8 (Params: 400)
    [Upward Pruned] 472 supersets removed from queue.
  [FULL ] [1, 162, 2, 8] -> Rank: 8/8 (Params: 502)
    [Upward Pruned] 64 supersets removed from queue.
  [FULL ] [1, 47, 8, 8] -> Rank: 8/8 (Params: 487)
    [Upward Pruned] 187 supersets removed from queue.
  [FULL ] [1, 18, 2, 8] -> Rank: 8/8 (Params: 70)
    [Upward Pruned] 639 supersets removed from queue.
  [FULL ] [1, 8, 7, 8] -> Rank: 8/8 (Params: 120)
    [Upward Pruned] 229 supersets removed from queue.
  [FULL ] [1, 2, 27, 8] -> Rank: 8/8 (Params: 272)
    [Upward Pruned] 89 supersets removed from queue.
  [FULL ] [1, 11, 5, 8] -> Rank: 8/8 (Params: 106)
    [Upward Pruned] 13 supersets removed from queue.
  [FULL ] [1, 4, 16, 8] -> Rank: 8/8 (Params: 196)
    [Upward Pruned] 43 supersets removed from queue.
  [FULL ] [1, 2, 25, 8] -> Rank: 8/8 (Params: 252)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 5, 8, 8] -> Rank: 8/8 (Params: 109)
    [Upward Pruned] 23 supersets removed from queue.
  [FULL ] [1, 4, 2, 8] -> Rank: 8/8 (Params: 28)
    [Upward Pruned] 67 supersets removed from queue.
  [FULL ] [1, 3, 19, 8] -> Rank: 8/8 (Params: 212)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 3, 13, 8] -> Rank: 8/8 (Params: 146)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 3, 2, 8] -> Rank: 8/8 (Params: 25)
    [Upward Pruned] 10 supersets removed from queue.
  [FULL ] [1, 2, 10, 8] -> Rank: 8/8 (Params: 102)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 2, 7, 8] -> Rank: 8/8 (Params: 72)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 2, 2, 8] -> Rank: 8/8 (Params: 22)
    [Upward Pruned] 4 supersets removed from queue.

Added 54 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_8_r4_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=5 ---
  Target Ambient Dimension: 8
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 207, 8] -> Rank: 8/8 (Params: 1863)
    [Upward Pruned] 93 supersets removed from queue.
  [FULL ] [1, 202, 8] -> Rank: 8/8 (Params: 1818)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 86, 8] -> Rank: 8/8 (Params: 774)
    [Upward Pruned] 115 supersets removed from queue.
  [FULL ] [1, 29, 8] -> Rank: 8/8 (Params: 261)
    [Upward Pruned] 56 supersets removed from queue.
  [FULL ] [1, 11, 8] -> Rank: 8/8 (Params: 99)
    [Upward Pruned] 17 supersets removed from queue.
  [FULL ] [1, 7, 8] -> Rank: 8/8 (Params: 63)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 3, 8] -> Rank: 8/8 (Params: 27)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 2, 8] -> Rank: 8/8 (Params: 18)

--- RANDOM SEARCH: h=3, exponent=5 ---
  Target Ambient Dimension: 8
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 29, 104, 8] -> Rank: 8/8 (Params: 3877)
    [Upward Pruned] 53583 supersets removed from queue.
  [FULL ] [1, 50, 9, 8] -> Rank: 8/8 (Params: 572)
    [Upward Pruned] 23844 supersets removed from queue.
  [FULL ] [1, 29, 97, 8] -> Rank: 8/8 (Params: 3618)
    [Upward Pruned] 146 supersets removed from queue.
  [FULL ] [1, 26, 24, 8] -> Rank: 8/8 (Params: 842)
    [Upward Pruned] 2363 supersets removed from queue.
  [FULL ] [1, 25, 48, 8] -> Rank: 8/8 (Params: 1609)
    [Upward Pruned] 252 supersets removed from queue.
  [FULL ] [1, 218, 6, 8] -> Rank: 8/8 (Params: 1574)
    [Upward Pruned] 248 supersets removed from queue.
  [FULL ] [1, 23, 148, 8] -> Rank: 8/8 (Params: 4611)
    [Upward Pruned] 305 supersets removed from queue.
  [FULL ] [1, 44, 3, 8] -> Rank: 8/8 (Params: 200)
    [Upward Pruned] 1382 supersets removed from queue.
  [FULL ] [1, 22, 300, 8] -> Rank: 8/8 (Params: 9022)
  [FULL ] [1, 11, 99, 8] -> Rank: 8/8 (Params: 1892)
    [Upward Pruned] 2520 supersets removed from queue.
  [FULL ] [1, 2, 186, 8] -> Rank: 8/8 (Params: 1862)
    [Upward Pruned] 1034 supersets removed from queue.
  [FULL ] [1, 36, 16, 8] -> Rank: 8/8 (Params: 740)
    [Upward Pruned] 63 supersets removed from queue.
  [FULL ] [1, 2, 131, 8] -> Rank: 8/8 (Params: 1312)
    [Upward Pruned] 494 supersets removed from queue.
  [FULL ] [1, 17, 3, 8] -> Rank: 8/8 (Params: 92)
    [Upward Pruned] 1126 supersets removed from queue.
  [FULL ] [1, 34, 2, 8] -> Rank: 8/8 (Params: 118)
    [Upward Pruned] 266 supersets removed from queue.
  [FULL ] [1, 6, 99, 8] -> Rank: 8/8 (Params: 1392)
    [Upward Pruned] 159 supersets removed from queue.
  [FULL ] [1, 3, 116, 8] -> Rank: 8/8 (Params: 1279)
    [Upward Pruned] 44 supersets removed from queue.
  [FULL ] [1, 8, 14, 8] -> Rank: 8/8 (Params: 232)
    [Upward Pruned] 764 supersets removed from queue.
  [FULL ] [1, 2, 49, 8] -> Rank: 8/8 (Params: 492)
    [Upward Pruned] 382 supersets removed from queue.
  [FULL ] [1, 5, 41, 8] -> Rank: 8/8 (Params: 538)
    [Upward Pruned] 23 supersets removed from queue.
  [FULL ] [1, 4, 21, 8] -> Rank: 8/8 (Params: 256)
    [Upward Pruned] 87 supersets removed from queue.
  [FULL ] [1, 13, 11, 8] -> Rank: 8/8 (Params: 244)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 15, 3, 8] -> Rank: 8/8 (Params: 84)
    [Upward Pruned] 15 supersets removed from queue.
  [FULL ] [1, 2, 22, 8] -> Rank: 8/8 (Params: 222)
    [Upward Pruned] 53 supersets removed from queue.
  [FULL ] [1, 7, 16, 8] -> Rank: 8/8 (Params: 247)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 5, 10, 8] -> Rank: 8/8 (Params: 135)
    [Upward Pruned] 49 supersets removed from queue.
  [FULL ] [1, 2, 2, 8] -> Rank: 8/8 (Params: 22)
    [Upward Pruned] 157 supersets removed from queue.

Added 35 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_8_r5_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=6 ---
  Target Ambient Dimension: 8
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 17, 8] -> Rank: 8/8 (Params: 153)
    [Upward Pruned] 283 supersets removed from queue.
  [FULL ] [1, 3, 8] -> Rank: 8/8 (Params: 27)
    [Upward Pruned] 13 supersets removed from queue.
  [FULL ] [1, 2, 8] -> Rank: 8/8 (Params: 18)

--- RANDOM SEARCH: h=3, exponent=6 ---
  Target Ambient Dimension: 8
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 145, 3, 8] -> Rank: 8/8 (Params: 604)
    [Upward Pruned] 46487 supersets removed from queue.
  [FULL ] [1, 7, 3, 8] -> Rank: 8/8 (Params: 52)
    [Upward Pruned] 41123 supersets removed from queue.
  [FULL ] [1, 2, 243, 8] -> Rank: 8/8 (Params: 2432)
    [Upward Pruned] 289 supersets removed from queue.
  [FULL ] [1, 3, 64, 8] -> Rank: 8/8 (Params: 707)
    [Upward Pruned] 715 supersets removed from queue.
  [FULL ] [1, 56, 2, 8] -> Rank: 8/8 (Params: 184)
    [Upward Pruned] 244 supersets removed from queue.
  [FULL ] [1, 2, 139, 8] -> Rank: 8/8 (Params: 1392)
    [Upward Pruned] 103 supersets removed from queue.
  [FULL ] [1, 2, 129, 8] -> Rank: 8/8 (Params: 1292)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 4, 62, 8] -> Rank: 8/8 (Params: 748)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 6, 43, 8] -> Rank: 8/8 (Params: 608)
    [Upward Pruned] 18 supersets removed from queue.
  [FULL ] [1, 4, 55, 8] -> Rank: 8/8 (Params: 664)
    [Upward Pruned] 13 supersets removed from queue.
  [FULL ] [1, 6, 2, 8] -> Rank: 8/8 (Params: 34)
    [Upward Pruned] 89 supersets removed from queue.
  [FULL ] [1, 3, 10, 8] -> Rank: 8/8 (Params: 113)
    [Upward Pruned] 143 supersets removed from queue.
  [FULL ] [1, 2, 15, 8] -> Rank: 8/8 (Params: 152)
    [Upward Pruned] 113 supersets removed from queue.
  [FULL ] [1, 5, 3, 8] -> Rank: 8/8 (Params: 44)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 2, 6, 8] -> Rank: 8/8 (Params: 62)
    [Upward Pruned] 16 supersets removed from queue.
  [FULL ] [1, 4, 5, 8] -> Rank: 8/8 (Params: 64)
  [FULL ] [1, 5, 2, 8] -> Rank: 8/8 (Params: 31)
  [FULL ] [1, 2, 3, 8] -> Rank: 8/8 (Params: 32)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 4, 2, 8] -> Rank: 8/8 (Params: 28)
  [FULL ] [1, 2, 2, 8] -> Rank: 8/8 (Params: 22)
    [Upward Pruned] 1 supersets removed from queue.

Added 23 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_8_r6_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=7 ---
  Target Ambient Dimension: 8
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 90, 8] -> Rank: 8/8 (Params: 810)
    [Upward Pruned] 210 supersets removed from queue.
  [FULL ] [1, 76, 8] -> Rank: 8/8 (Params: 684)
    [Upward Pruned] 13 supersets removed from queue.
  [FULL ] [1, 68, 8] -> Rank: 8/8 (Params: 612)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 39, 8] -> Rank: 8/8 (Params: 351)
    [Upward Pruned] 28 supersets removed from queue.
  [FULL ] [1, 13, 8] -> Rank: 8/8 (Params: 117)
    [Upward Pruned] 25 supersets removed from queue.

  [FULL ] [1, 11, 8] -> Rank: 8/8 (Params: 99)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 4, 8] -> Rank: 8/8 (Params: 36)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 3, 8] -> Rank: 8/8 (Params: 27)
  [FULL ] [1, 2, 8] -> Rank: 8/8 (Params: 18)

--- RANDOM SEARCH: h=3, exponent=7 ---
  Target Ambient Dimension: 8
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 79, 289, 8] -> Rank: 8/8 (Params: 25222)
    [Upward Pruned] 2663 supersets removed from queue.
  [FULL ] [1, 115, 266, 8] -> Rank: 8/8 (Params: 32833)
    [Upward Pruned] 4277 supersets removed from queue.
  [FULL ] [1, 196, 210, 8] -> Rank: 8/8 (Params: 43036)
    [Upward Pruned] 5879 supersets removed from queue.
  [FULL ] [1, 177, 137, 8] -> Rank: 8/8 (Params: 25522)
    [Upward Pruned] 10115 supersets removed from queue.
  [FULL ] [1, 162, 25, 8] -> Rank: 8/8 (Params: 4412)
    [Upward Pruned] 17502 supersets removed from queue.
  [FULL ] [1, 110, 101, 8] -> Rank: 8/8 (Params: 12028)
    [Upward Pruned] 8694 supersets removed from queue.
  [FULL ] [1, 108, 43, 8] -> Rank: 8/8 (Params: 5096)
    [Upward Pruned] 3507 supersets removed from queue.
  [FULL ] [1, 14, 95, 8] -> Rank: 8/8 (Params: 2104)
    [Upward Pruned] 19015 supersets removed from queue.
  [FULL ] [1, 4, 18, 8] -> Rank: 8/8 (Params: 220)
    [Upward Pruned] 12390 supersets removed from queue.
  [FULL ] [1, 158, 15, 8] -> Rank: 8/8 (Params: 2648)
    [Upward Pruned] 428 supersets removed from queue.
  [FULL ] [1, 247, 8, 8] -> Rank: 8/8 (Params: 2287)
    [Upward Pruned] 377 supersets removed from queue.
  [FULL ] [1, 29, 14, 8] -> Rank: 8/8 (Params: 547)
    [Upward Pruned] 604 supersets removed from queue.
  [FULL ] [1, 135, 8, 8] -> Rank: 8/8 (Params: 1279)
    [Upward Pruned] 671 supersets removed from queue.
  [FULL ] [1, 235, 7, 8] -> Rank: 8/8 (Params: 1936)
    [Upward Pruned] 65 supersets removed from queue.
  [FULL ] [1, 3, 61, 8] -> Rank: 8/8 (Params: 674)
    [Upward Pruned] 239 supersets removed from queue.
  [FULL ] [1, 114, 6, 8] -> Rank: 8/8 (Params: 846)
    [Upward Pruned] 433 supersets removed from queue.
  [FULL ] [1, 2, 140, 8] -> Rank: 8/8 (Params: 1402)
    [Upward Pruned] 160 supersets removed from queue.
  [FULL ] [1, 78, 9, 8] -> Rank: 8/8 (Params: 852)
    [Upward Pruned] 179 supersets removed from queue.
  [FULL ] [1, 2, 121, 8] -> Rank: 8/8 (Params: 1212)
    [Upward Pruned] 18 supersets removed from queue.
  [FULL ] [1, 2, 77, 8] -> Rank: 8/8 (Params: 772)
    [Upward Pruned] 43 supersets removed from queue.
  [FULL ] [1, 283, 4, 8] -> Rank: 8/8 (Params: 1447)
    [Upward Pruned] 35 supersets removed from queue.
  [FULL ] [1, 47, 12, 8] -> Rank: 8/8 (Params: 707)
    [Upward Pruned] 61 supersets removed from queue.
  [FULL ] [1, 99, 8, 8] -> Rank: 8/8 (Params: 955)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 249, 5, 8] -> Rank: 8/8 (Params: 1534)
    [Upward Pruned] 33 supersets removed from queue.
  [FULL ] [1, 140, 5, 8] -> Rank: 8/8 (Params: 880)
    [Upward Pruned] 108 supersets removed from queue.
  [FULL ] [1, 188, 2, 8] -> Rank: 8/8 (Params: 580)
    [Upward Pruned] 320 supersets removed from queue.
  [FULL ] [1, 2, 3, 8] -> Rank: 8/8 (Params: 32)
    [Upward Pruned] 1358 supersets removed from queue.
  [FULL ] [1, 168, 2, 8] -> Rank: 8/8 (Params: 520)
    [Upward Pruned] 19 supersets removed from queue.
  [FULL ] [1, 150, 2, 8] -> Rank: 8/8 (Params: 466)
    [Upward Pruned] 17 supersets removed from queue.
  [FULL ] [1, 66, 2, 8] -> Rank: 8/8 (Params: 214)
    [Upward Pruned] 83 supersets removed from queue.
  [FULL ] [1, 49, 2, 8] -> Rank: 8/8 (Params: 163)
    [Upward Pruned] 16 supersets removed from queue.
  [FULL ] [1, 37, 2, 8] -> Rank: 8/8 (Params: 127)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 9, 2, 8] -> Rank: 8/8 (Params: 43)
    [Upward Pruned] 27 supersets removed from queue.
  [FULL ] [1, 5, 2, 8] -> Rank: 8/8 (Params: 31)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 2, 2, 8] -> Rank: 8/8 (Params: 22)
    [Upward Pruned] 2 supersets removed from queue.

Added 44 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_8_r7_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=8 ---
  Target Ambient Dimension: 8
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 51, 8] -> Rank: 8/8 (Params: 459)
    [Upward Pruned] 249 supersets removed from queue.
  [FULL ] [1, 16, 8] -> Rank: 8/8 (Params: 144)
    [Upward Pruned] 34 supersets removed from queue.
  [FULL ] [1, 13, 8] -> Rank: 8/8 (Params: 117)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 4, 8] -> Rank: 8/8 (Params: 36)
    [Upward Pruned] 8 supersets removed from queue.

  [FULL ] [1, 2, 8] -> Rank: 8/8 (Params: 18)
    [Upward Pruned] 1 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=8 ---
  Target Ambient Dimension: 8
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 187, 281, 8] -> Rank: 8/8 (Params: 54982)
    [Upward Pruned] 2279 supersets removed from queue.
  [FULL ] [1, 39, 47, 8] -> Rank: 8/8 (Params: 2248)
    [Upward Pruned] 64267 supersets removed from queue.
  [FULL ] [1, 208, 32, 8] -> Rank: 8/8 (Params: 7120)
    [Upward Pruned] 1394 supersets removed from queue.
  [FULL ] [1, 133, 8, 8] -> Rank: 8/8 (Params: 1261)
    [Upward Pruned] 5156 supersets removed from queue.
  [FULL ] [1, 13, 206, 8] -> Rank: 8/8 (Params: 4339)
    [Upward Pruned] 2469 supersets removed from queue.
  [FULL ] [1, 31, 30, 8] -> Rank: 8/8 (Params: 1201)
    [Upward Pruned] 3005 supersets removed from queue.
  [FULL ] [1, 7, 261, 8] -> Rank: 8/8 (Params: 3922)
    [Upward Pruned] 239 supersets removed from queue.
  [FULL ] [1, 128, 20, 8] -> Rank: 8/8 (Params: 2848)
    [Upward Pruned] 49 supersets removed from queue.
  [FULL ] [1, 27, 91, 8] -> Rank: 8/8 (Params: 3212)
    [Upward Pruned] 459 supersets removed from queue.
  [FULL ] [1, 25, 18, 8] -> Rank: 8/8 (Params: 619)
    [Upward Pruned] 1841 supersets removed from queue.
  [FULL ] [1, 97, 17, 8] -> Rank: 8/8 (Params: 1882)
    [Upward Pruned] 35 supersets removed from queue.
  [FULL ] [1, 11, 91, 8] -> Rank: 8/8 (Params: 1740)
    [Upward Pruned] 1719 supersets removed from queue.
  [FULL ] [1, 199, 3, 8] -> Rank: 8/8 (Params: 820)
    [Upward Pruned] 509 supersets removed from queue.
  [FULL ] [1, 79, 14, 8] -> Rank: 8/8 (Params: 1297)
    [Upward Pruned] 179 supersets removed from queue.
  [FULL ] [1, 7, 190, 8] -> Rank: 8/8 (Params: 2857)
    [Upward Pruned] 283 supersets removed from queue.
  [FULL ] [1, 158, 7, 8] -> Rank: 8/8 (Params: 1320)
    [Upward Pruned] 40 supersets removed from queue.
  [FULL ] [1, 4, 214, 8] -> Rank: 8/8 (Params: 2572)
    [Upward Pruned] 260 supersets removed from queue.
  [FULL ] [1, 24, 50, 8] -> Rank: 8/8 (Params: 1624)
    [Upward Pruned] 40 supersets removed from queue.
  [FULL ] [1, 10, 14, 8] -> Rank: 8/8 (Params: 262)
    [Upward Pruned] 1428 supersets removed from queue.
  [FULL ] [1, 2, 122, 8] -> Rank: 8/8 (Params: 1222)
    [Upward Pruned] 837 supersets removed from queue.
  [FULL ] [1, 120, 2, 8] -> Rank: 8/8 (Params: 376)
    [Upward Pruned] 612 supersets removed from queue.
  [FULL ] [1, 83, 6, 8] -> Rank: 8/8 (Params: 629)
    [Upward Pruned] 295 supersets removed from queue.
  [FULL ] [1, 86, 5, 8] -> Rank: 8/8 (Params: 556)
    [Upward Pruned] 33 supersets removed from queue.
  [FULL ] [1, 8, 26, 8] -> Rank: 8/8 (Params: 424)
    [Upward Pruned] 191 supersets removed from queue.
  [FULL ] [1, 20, 13, 8] -> Rank: 8/8 (Params: 384)
    [Upward Pruned] 62 supersets removed from queue.
  [FULL ] [1, 4, 69, 8] -> Rank: 8/8 (Params: 832)
    [Upward Pruned] 211 supersets removed from queue.
  [FULL ] [1, 50, 2, 8] -> Rank: 8/8 (Params: 166)
    [Upward Pruned] 476 supersets removed from queue.
  [FULL ] [1, 6, 21, 8] -> Rank: 8/8 (Params: 300)
    [Upward Pruned] 105 supersets removed from queue.
  [FULL ] [1, 2, 118, 8] -> Rank: 8/8 (Params: 1182)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 26, 4, 8] -> Rank: 8/8 (Params: 162)
    [Upward Pruned] 215 supersets removed from queue.
  [FULL ] [1, 3, 59, 8] -> Rank: 8/8 (Params: 652)
    [Upward Pruned] 78 supersets removed from queue.
  [FULL ] [1, 18, 13, 8] -> Rank: 8/8 (Params: 356)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 5, 26, 8] -> Rank: 8/8 (Params: 343)
    [Upward Pruned] 32 supersets removed from queue.
  [FULL ] [1, 2, 39, 8] -> Rank: 8/8 (Params: 392)
    [Upward Pruned] 118 supersets removed from queue.
  [FULL ] [1, 15, 2, 8] -> Rank: 8/8 (Params: 61)
    [Upward Pruned] 171 supersets removed from queue.
  [FULL ] [1, 6, 7, 8] -> Rank: 8/8 (Params: 104)
    [Upward Pruned] 90 supersets removed from queue.
  [FULL ] [1, 4, 14, 8] -> Rank: 8/8 (Params: 172)
    [Upward Pruned] 36 supersets removed from queue.
  [FULL ] [1, 2, 12, 8] -> Rank: 8/8 (Params: 122)
    [Upward Pruned] 57 supersets removed from queue.
  [FULL ] [1, 11, 2, 8] -> Rank: 8/8 (Params: 49)
    [Upward Pruned] 19 supersets removed from queue.
  [FULL ] [1, 3, 9, 8] -> Rank: 8/8 (Params: 102)
    [Upward Pruned] 8 supersets removed from queue.
  [FULL ] [1, 7, 4, 8] -> Rank: 8/8 (Params: 67)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 5, 7, 8] -> Rank: 8/8 (Params: 96)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 5, 8] -> Rank: 8/8 (Params: 52)
    [Upward Pruned] 18 supersets removed from queue.
  [FULL ] [1, 3, 2, 8] -> Rank: 8/8 (Params: 25)
    [Upward Pruned] 19 supersets removed from queue.
  [FULL ] [1, 2, 3, 8] -> Rank: 8/8 (Params: 32)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 2, 8] -> Rank: 8/8 (Params: 22)

Added 51 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_8_r8_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=9 ---
  Target Ambient Dimension: 8
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 84, 8] -> Rank: 8/8 (Params: 756)
    [Upward Pruned] 216 supersets removed from queue.
  [FULL ] [1, 79, 8] -> Rank: 8/8 (Params: 711)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 55, 8] -> Rank: 8/8 (Params: 495)
    [Upward Pruned] 23 supersets removed from queue.
  [FULL ] [1, 4, 8] -> Rank: 8/8 (Params: 36)
    [Upward Pruned] 50 supersets removed from queue.
  [FULL ] [1, 2, 8] -> Rank: 8/8 (Params: 18)
    [Upward Pruned] 1 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=9 ---
  Target Ambient Dimension: 8
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 279, 59, 8] -> Rank: 8/8 (Params: 17212)
    [Upward Pruned] 5323 supersets removed from queue.
  [FULL ] [1, 101, 59, 8] -> Rank: 8/8 (Params: 6532)
    [Upward Pruned] 43075 supersets removed from queue.
  [FULL ] [1, 91, 294, 8] -> Rank: 8/8 (Params: 29197)
    [Upward Pruned] 69 supersets removed from queue.
  [FULL ] [1, 32, 29, 8] -> Rank: 8/8 (Params: 1192)
    [Upward Pruned] 24697 supersets removed from queue.
  [FULL ] [1, 232, 26, 8] -> Rank: 8/8 (Params: 6472)
    [Upward Pruned] 206 supersets removed from queue.
  [FULL ] [1, 193, 16, 8] -> Rank: 8/8 (Params: 3409)
    [Upward Pruned] 1196 supersets removed from queue.
  [FULL ] [1, 23, 208, 8] -> Rank: 8/8 (Params: 6471)
    [Upward Pruned] 836 supersets removed from queue.
  [FULL ] [1, 179, 19, 8] -> Rank: 8/8 (Params: 3732)
    [Upward Pruned] 139 supersets removed from queue.
  [FULL ] [1, 17, 131, 8] -> Rank: 8/8 (Params: 3292)
    [Upward Pruned] 1712 supersets removed from queue.
  [FULL ] [1, 288, 12, 8] -> Rank: 8/8 (Params: 3840)
    [Upward Pruned] 51 supersets removed from queue.
  [FULL ] [1, 262, 9, 8] -> Rank: 8/8 (Params: 2692)
    [Upward Pruned] 220 supersets removed from queue.
  [FULL ] [1, 73, 18, 8] -> Rank: 8/8 (Params: 1531)
    [Upward Pruned] 1179 supersets removed from queue.
  [FULL ] [1, 30, 48, 8] -> Rank: 8/8 (Params: 1854)
    [Upward Pruned] 165 supersets removed from queue.
  [FULL ] [1, 101, 9, 8] -> Rank: 8/8 (Params: 1082)
    [Upward Pruned] 1310 supersets removed from queue.
  [FULL ] [1, 221, 4, 8] -> Rank: 8/8 (Params: 1137)
    [Upward Pruned] 399 supersets removed from queue.
  [FULL ] [1, 13, 109, 8] -> Rank: 8/8 (Params: 2302)
    [Upward Pruned] 1053 supersets removed from queue.
  [FULL ] [1, 111, 8, 8] -> Rank: 8/8 (Params: 1063)
    [Upward Pruned] 109 supersets removed from queue.
  [FULL ] [1, 27, 7, 8] -> Rank: 8/8 (Params: 272)
    [Upward Pruned] 1727 supersets removed from queue.
  [FULL ] [1, 2, 51, 8] -> Rank: 8/8 (Params: 512)
    [Upward Pruned] 3561 supersets removed from queue.
  [FULL ] [1, 172, 6, 8] -> Rank: 8/8 (Params: 1252)
    [Upward Pruned] 48 supersets removed from queue.
  [FULL ] [1, 23, 10, 8] -> Rank: 8/8 (Params: 333)
    [Upward Pruned] 163 supersets removed from queue.
  [FULL ] [1, 15, 22, 8] -> Rank: 8/8 (Params: 521)
    [Upward Pruned] 231 supersets removed from queue.
  [FULL ] [1, 277, 2, 8] -> Rank: 8/8 (Params: 847)
    [Upward Pruned] 47 supersets removed from queue.
  [FULL ] [1, 2, 34, 8] -> Rank: 8/8 (Params: 342)
    [Upward Pruned] 220 supersets removed from queue.
  [FULL ] [1, 86, 4, 8] -> Rank: 8/8 (Params: 462)
    [Upward Pruned] 355 supersets removed from queue.
  [FULL ] [1, 3, 6, 8] -> Rank: 8/8 (Params: 69)
    [Upward Pruned] 538 supersets removed from queue.
  [FULL ] [1, 29, 2, 8] -> Rank: 8/8 (Params: 103)
    [Upward Pruned] 609 supersets removed from queue.
  [FULL ] [1, 12, 2, 8] -> Rank: 8/8 (Params: 52)
    [Upward Pruned] 67 supersets removed from queue.
  [FULL ] [1, 5, 3, 8] -> Rank: 8/8 (Params: 44)
    [Upward Pruned] 20 supersets removed from queue.
  [FULL ] [1, 2, 5, 8] -> Rank: 8/8 (Params: 52)
    [Upward Pruned] 30 supersets removed from queue.
  [FULL ] [1, 5, 2, 8] -> Rank: 8/8 (Params: 31)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 3, 2, 8] -> Rank: 8/8 (Params: 25)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 2, 4, 8] -> Rank: 8/8 (Params: 42)
  [FULL ] [1, 2, 3, 8] -> Rank: 8/8 (Params: 32)
  [FULL ] [1, 2, 2, 8] -> Rank: 8/8 (Params: 22)

Added 40 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_8_r9_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=1 ---
  Target Ambient Dimension: 9
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 131, 9] -> Rank: 9/9 (Params: 1310)
    [Upward Pruned] 169 supersets removed from queue.
  [FULL ] [1, 86, 9] -> Rank: 9/9 (Params: 860)
    [Upward Pruned] 44 supersets removed from queue.
  [FULL ] [1, 13, 9] -> Rank: 9/9 (Params: 130)
    [Upward Pruned] 72 supersets removed from queue.
  [FULL ] [1, 7, 9] -> Rank: 9/9 (Params: 70)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 2, 9] -> Rank: 9/9 (Params: 20)
    [Upward Pruned] 4 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=1 ---
  Target Ambient Dimension: 9
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 242, 115, 9] -> Rank: 9/9 (Params: 29107)
    [Upward Pruned] 10973 supersets removed from queue.
  [FULL ] [1, 161, 202, 9] -> Rank: 9/9 (Params: 34501)
    [Upward Pruned] 8018 supersets removed from queue.
  [FULL ] [1, 77, 109, 9] -> Rank: 9/9 (Params: 9451)
    [Upward Pruned] 24014 supersets removed from queue.
  [FULL ] [1, 4, 95, 9] -> Rank: 9/9 (Params: 1239)
    [Upward Pruned] 18173 supersets removed from queue.
  [FULL ] [1, 126, 46, 9] -> Rank: 9/9 (Params: 6336)
    [Upward Pruned] 8574 supersets removed from queue.
  [FULL ] [1, 133, 24, 9] -> Rank: 9/9 (Params: 3541)
    [Upward Pruned] 3695 supersets removed from queue.
  [FULL ] [1, 38, 79, 9] -> Rank: 9/9 (Params: 3751)
    [Upward Pruned] 1407 supersets removed from queue.
  [FULL ] [1, 3, 265, 9] -> Rank: 9/9 (Params: 3183)
    [Upward Pruned] 35 supersets removed from queue.
  [FULL ] [1, 86, 45, 9] -> Rank: 9/9 (Params: 4361)
    [Upward Pruned] 1366 supersets removed from queue.
  [FULL ] [1, 286, 10, 9] -> Rank: 9/9 (Params: 3236)
    [Upward Pruned] 209 supersets removed from queue.
  [FULL ] [1, 142, 4, 9] -> Rank: 9/9 (Params: 746)
    [Upward Pruned] 2969 supersets removed from queue.
  [FULL ] [1, 19, 16, 9] -> Rank: 9/9 (Params: 467)
    [Upward Pruned] 5959 supersets removed from queue.
  [FULL ] [1, 45, 9, 9] -> Rank: 9/9 (Params: 531)
    [Upward Pruned] 678 supersets removed from queue.
  [FULL ] [1, 257, 3, 9] -> Rank: 9/9 (Params: 1055)
    [Upward Pruned] 43 supersets removed from queue.
  [FULL ] [1, 9, 55, 9] -> Rank: 9/9 (Params: 999)
    [Upward Pruned] 399 supersets removed from queue.
  [FULL ] [1, 24, 3, 9] -> Rank: 9/9 (Params: 123)
    [Upward Pruned] 969 supersets removed from queue.
  [FULL ] [1, 281, 2, 9] -> Rank: 9/9 (Params: 861)
    [Upward Pruned] 19 supersets removed from queue.
  [FULL ] [1, 7, 50, 9] -> Rank: 9/9 (Params: 807)
    [Upward Pruned] 139 supersets removed from queue.
  [FULL ] [1, 9, 26, 9] -> Rank: 9/9 (Params: 477)
    [Upward Pruned] 239 supersets removed from queue.
  [FULL ] [1, 2, 94, 9] -> Rank: 9/9 (Params: 1036)
    [Upward Pruned] 380 supersets removed from queue.
  [FULL ] [1, 2, 62, 9] -> Rank: 9/9 (Params: 684)
    [Upward Pruned] 159 supersets removed from queue.
  [FULL ] [1, 9, 11, 9] -> Rank: 9/9 (Params: 207)
    [Upward Pruned] 174 supersets removed from queue.
  [FULL ] [1, 236, 2, 9] -> Rank: 9/9 (Params: 726)
    [Upward Pruned] 44 supersets removed from queue.
  [FULL ] [1, 41, 2, 9] -> Rank: 9/9 (Params: 141)
    [Upward Pruned] 194 supersets removed from queue.
  [FULL ] [1, 7, 4, 9] -> Rank: 9/9 (Params: 71)
    [Upward Pruned] 196 supersets removed from queue.
  [FULL ] [1, 4, 7, 9] -> Rank: 9/9 (Params: 95)
    [Upward Pruned] 164 supersets removed from queue.
  [FULL ] [1, 3, 22, 9] -> Rank: 9/9 (Params: 267)
    [Upward Pruned] 39 supersets removed from queue.
  [FULL ] [1, 6, 3, 9] -> Rank: 9/9 (Params: 51)
    [Upward Pruned] 20 supersets removed from queue.
  [FULL ] [1, 2, 56, 9] -> Rank: 9/9 (Params: 618)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 2, 49, 9] -> Rank: 9/9 (Params: 541)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 2, 2, 9] -> Rank: 9/9 (Params: 24)
    [Upward Pruned] 111 supersets removed from queue.

Added 36 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_9_r1_architectures.csv'.

Loading existing database from '../data/raw/1_9_r2_architectures.csv'...

--- RANDOM SEARCH: h=2, exponent=2 ---
  Target Ambient Dimension: 9
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 294 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.

--- RANDOM SEARCH: h=3, exponent=2 ---
  Target Ambient Dimension: 9
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 89356 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_9_r2_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=3 ---
  Target Ambient Dimension: 9
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 294, 9] -> Rank: 9/9 (Params: 2940)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 9, 9] -> Rank: 9/9 (Params: 90)
    [Upward Pruned] 284 supersets removed from queue.
  [FULL ] [1, 4, 9] -> Rank: 9/9 (Params: 40)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 3, 9] -> Rank: 9/9 (Params: 30)
  [FULL ] [1, 2, 9] -> Rank: 9/9 (Params: 20)

--- RANDOM SEARCH: h=3, exponent=3 ---
  Target Ambient Dimension: 9
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 150, 143, 9] -> Rank: 9/9 (Params: 22887)
    [Upward Pruned] 23857 supersets removed from queue.
  [FULL ] [1, 14, 160, 9] -> Rank: 9/9 (Params: 3694)
    [Upward Pruned] 19175 supersets removed from queue.
  [FULL ] [1, 5, 160, 9] -> Rank: 9/9 (Params: 2245)
    [Upward Pruned] 1268 supersets removed from queue.
  [FULL ] [1, 25, 149, 9] -> Rank: 9/9 (Params: 5091)
    [Upward Pruned] 1374 supersets removed from queue.
  [FULL ] [1, 210, 97, 9] -> Rank: 9/9 (Params: 21453)
    [Upward Pruned] 4185 supersets removed from queue.
  [FULL ] [1, 70, 109, 9] -> Rank: 9/9 (Params: 8681)
    [Upward Pruned] 5239 supersets removed from queue.
  [FULL ] [1, 147, 48, 9] -> Rank: 9/9 (Params: 7635)
    [Upward Pruned] 8301 supersets removed from queue.
  [FULL ] [1, 34, 107, 9] -> Rank: 9/9 (Params: 4635)
    [Upward Pruned] 1665 supersets removed from queue.
  [FULL ] [1, 175, 22, 9] -> Rank: 9/9 (Params: 4223)
    [Upward Pruned] 3275 supersets removed from queue.
  [FULL ] [1, 2, 299, 9] -> Rank: 9/9 (Params: 3291)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 8, 110, 9] -> Rank: 9/9 (Params: 1878)
    [Upward Pruned] 1200 supersets removed from queue.
  [FULL ] [1, 67, 28, 9] -> Rank: 9/9 (Params: 2195)
    [Upward Pruned] 6879 supersets removed from queue.
  [FULL ] [1, 33, 89, 9] -> Rank: 9/9 (Params: 3771)
    [Upward Pruned] 614 supersets removed from queue.
  [FULL ] [1, 108, 24, 9] -> Rank: 9/9 (Params: 2916)
    [Upward Pruned] 267 supersets removed from queue.
  [FULL ] [1, 233, 13, 9] -> Rank: 9/9 (Params: 3379)
    [Upward Pruned] 611 supersets removed from queue.
  [FULL ] [1, 233, 8, 9] -> Rank: 9/9 (Params: 2169)
    [Upward Pruned] 339 supersets removed from queue.
  [FULL ] [1, 82, 14, 9] -> Rank: 9/9 (Params: 1356)
    [Upward Pruned] 1497 supersets removed from queue.
  [FULL ] [1, 12, 3, 9] -> Rank: 9/9 (Params: 75)
    [Upward Pruned] 7546 supersets removed from queue.
  [FULL ] [1, 9, 69, 9] -> Rank: 9/9 (Params: 1251)
    [Upward Pruned] 122 supersets removed from queue.
  [FULL ] [1, 2, 33, 9] -> Rank: 9/9 (Params: 365)
    [Upward Pruned] 1363 supersets removed from queue.
  [FULL ] [1, 50, 2, 9] -> Rank: 9/9 (Params: 168)
    [Upward Pruned] 250 supersets removed from queue.
  [FULL ] [1, 8, 28, 9] -> Rank: 9/9 (Params: 484)
    [Upward Pruned] 19 supersets removed from queue.
  [FULL ] [1, 3, 29, 9] -> Rank: 9/9 (Params: 351)
    [Upward Pruned] 19 supersets removed from queue.
  [FULL ] [1, 4, 22, 9] -> Rank: 9/9 (Params: 290)
    [Upward Pruned] 51 supersets removed from queue.
  [FULL ] [1, 10, 2, 9] -> Rank: 9/9 (Params: 48)
    [Upward Pruned] 77 supersets removed from queue.
  [FULL ] [1, 5, 18, 9] -> Rank: 9/9 (Params: 257)
    [Upward Pruned] 19 supersets removed from queue.
  [FULL ] [1, 3, 14, 9] -> Rank: 9/9 (Params: 171)
    [Upward Pruned] 42 supersets removed from queue.
  [FULL ] [1, 5, 13, 9] -> Rank: 9/9 (Params: 187)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 2, 15, 9] -> Rank: 9/9 (Params: 167)
    [Upward Pruned] 17 supersets removed from queue.
  [FULL ] [1, 5, 11, 9] -> Rank: 9/9 (Params: 159)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 6, 3, 9] -> Rank: 9/9 (Params: 51)
    [Upward Pruned] 31 supersets removed from queue.
  [FULL ] [1, 3, 4, 9] -> Rank: 9/9 (Params: 51)
    [Upward Pruned] 26 supersets removed from queue.
  [FULL ] [1, 3, 2, 9] -> Rank: 9/9 (Params: 27)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 2, 14, 9] -> Rank: 9/9 (Params: 156)
  [FULL ] [1, 2, 7, 9] -> Rank: 9/9 (Params: 79)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 2, 6, 9] -> Rank: 9/9 (Params: 68)
  [FULL ] [1, 2, 4, 9] -> Rank: 9/9 (Params: 46)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 3, 9] -> Rank: 9/9 (Params: 35)
  [FULL ] [1, 2, 2, 9] -> Rank: 9/9 (Params: 24)

Added 44 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_9_r3_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=4 ---
  Target Ambient Dimension: 9
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 215, 9] -> Rank: 9/9 (Params: 2150)
    [Upward Pruned] 85 supersets removed from queue.
  [FULL ] [1, 16, 9] -> Rank: 9/9 (Params: 160)
    [Upward Pruned] 198 supersets removed from queue.

  [FULL ] [1, 6, 9] -> Rank: 9/9 (Params: 60)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 2, 9] -> Rank: 9/9 (Params: 20)
    [Upward Pruned] 3 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=4 ---
  Target Ambient Dimension: 9
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 130, 29, 9] -> Rank: 9/9 (Params: 4161)
    [Upward Pruned] 46511 supersets removed from queue.
  [FULL ] [1, 79, 117, 9] -> Rank: 9/9 (Params: 10375)
    [Upward Pruned] 9383 supersets removed from queue.
  [FULL ] [1, 106, 92, 9] -> Rank: 9/9 (Params: 10686)
    [Upward Pruned] 599 supersets removed from queue.
  [FULL ] [1, 30, 65, 9] -> Rank: 9/9 (Params: 2565)
    [Upward Pruned] 13615 supersets removed from queue.
  [FULL ] [1, 95, 39, 9] -> Rank: 9/9 (Params: 4151)
    [Upward Pruned] 909 supersets removed from queue.
  [FULL ] [1, 3, 209, 9] -> Rank: 9/9 (Params: 2511)
    [Upward Pruned] 2483 supersets removed from queue.
  [FULL ] [1, 107, 5, 9] -> Rank: 9/9 (Params: 687)
    [Upward Pruned] 4885 supersets removed from queue.
  [FULL ] [1, 100, 23, 9] -> Rank: 9/9 (Params: 2607)
    [Upward Pruned] 111 supersets removed from queue.
  [FULL ] [1, 45, 30, 9] -> Rank: 9/9 (Params: 1665)
    [Upward Pruned] 1794 supersets removed from queue.
  [FULL ] [1, 54, 16, 9] -> Rank: 9/9 (Params: 1062)
    [Upward Pruned] 692 supersets removed from queue.
  [FULL ] [1, 11, 92, 9] -> Rank: 9/9 (Params: 1851)
    [Upward Pruned] 2222 supersets removed from queue.
  [FULL ] [1, 17, 2, 9] -> Rank: 9/9 (Params: 69)
    [Upward Pruned] 3690 supersets removed from queue.
  [FULL ] [1, 3, 71, 9] -> Rank: 9/9 (Params: 855)
    [Upward Pruned] 1229 supersets removed from queue.
  [FULL ] [1, 6, 66, 9] -> Rank: 9/9 (Params: 996)
    [Upward Pruned] 54 supersets removed from queue.
  [FULL ] [1, 6, 60, 9] -> Rank: 9/9 (Params: 906)
    [Upward Pruned] 65 supersets removed from queue.
  [FULL ] [1, 2, 276, 9] -> Rank: 9/9 (Params: 3038)
    [Upward Pruned] 24 supersets removed from queue.
  [FULL ] [1, 3, 56, 9] -> Rank: 9/9 (Params: 675)
    [Upward Pruned] 88 supersets removed from queue.
  [FULL ] [1, 6, 3, 9] -> Rank: 9/9 (Params: 51)
    [Upward Pruned] 582 supersets removed from queue.
  [FULL ] [1, 4, 30, 9] -> Rank: 9/9 (Params: 394)
    [Upward Pruned] 51 supersets removed from queue.
  [FULL ] [1, 2, 38, 9] -> Rank: 9/9 (Params: 420)
    [Upward Pruned] 255 supersets removed from queue.
  [FULL ] [1, 4, 12, 9] -> Rank: 9/9 (Params: 160)
    [Upward Pruned] 35 supersets removed from queue.
  [FULL ] [1, 2, 10, 9] -> Rank: 9/9 (Params: 112)
    [Upward Pruned] 59 supersets removed from queue.
  [FULL ] [1, 10, 2, 9] -> Rank: 9/9 (Params: 48)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 4, 2, 9] -> Rank: 9/9 (Params: 30)
    [Upward Pruned] 19 supersets removed from queue.
  [FULL ] [1, 3, 7, 9] -> Rank: 9/9 (Params: 87)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 2, 6, 9] -> Rank: 9/9 (Params: 68)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 2, 3, 9] -> Rank: 9/9 (Params: 35)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 3, 2, 9] -> Rank: 9/9 (Params: 27)
  [FULL ] [1, 2, 2, 9] -> Rank: 9/9 (Params: 24)

Added 33 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_9_r4_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=5 ---
  Target Ambient Dimension: 9
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 186, 9] -> Rank: 9/9 (Params: 1860)
    [Upward Pruned] 114 supersets removed from queue.
  [FULL ] [1, 91, 9] -> Rank: 9/9 (Params: 910)
    [Upward Pruned] 94 supersets removed from queue.

  [FULL ] [1, 76, 9] -> Rank: 9/9 (Params: 760)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 72, 9] -> Rank: 9/9 (Params: 720)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 71, 9] -> Rank: 9/9 (Params: 710)
  [FULL ] [1, 9, 9] -> Rank: 9/9 (Params: 90)
    [Upward Pruned] 61 supersets removed from queue.
  [FULL ] [1, 2, 9] -> Rank: 9/9 (Params: 20)
    [Upward Pruned] 6 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=5 ---
  Target Ambient Dimension: 9
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 153, 155, 9] -> Rank: 9/9 (Params: 25263)
    [Upward Pruned] 21607 supersets removed from queue.
  [FULL ] [1, 270, 20, 9] -> Rank: 9/9 (Params: 5850)
    [Upward Pruned] 4184 supersets removed from queue.
  [FULL ] [1, 215, 124, 9] -> Rank: 9/9 (Params: 27991)
    [Upward Pruned] 1704 supersets removed from queue.
  [FULL ] [1, 190, 138, 9] -> Rank: 9/9 (Params: 27652)
    [Upward Pruned] 424 supersets removed from queue.
  [FULL ] [1, 108, 15, 9] -> Rank: 9/9 (Params: 1863)
    [Upward Pruned] 27274 supersets removed from queue.
  [FULL ] [1, 24, 180, 9] -> Rank: 9/9 (Params: 5964)
    [Upward Pruned] 10163 supersets removed from queue.
  [FULL ] [1, 4, 195, 9] -> Rank: 9/9 (Params: 2539)
    [Upward Pruned] 2119 supersets removed from queue.
  [FULL ] [1, 5, 188, 9] -> Rank: 9/9 (Params: 2637)
    [Upward Pruned] 132 supersets removed from queue.
  [FULL ] [1, 79, 19, 9] -> Rank: 9/9 (Params: 1751)
    [Upward Pruned] 4668 supersets removed from queue.
  [FULL ] [1, 14, 7, 9] -> Rank: 9/9 (Params: 175)
    [Upward Pruned] 13216 supersets removed from queue.
  [FULL ] [1, 12, 154, 9] -> Rank: 9/9 (Params: 3246)
    [Upward Pruned] 67 supersets removed from queue.
  [FULL ] [1, 21, 4, 9] -> Rank: 9/9 (Params: 141)
    [Upward Pruned] 839 supersets removed from queue.
  [FULL ] [1, 11, 45, 9] -> Rank: 9/9 (Params: 911)
    [Upward Pruned] 360 supersets removed from queue.
  [FULL ] [1, 10, 130, 9] -> Rank: 9/9 (Params: 2480)
    [Upward Pruned] 57 supersets removed from queue.
  [FULL ] [1, 3, 246, 9] -> Rank: 9/9 (Params: 2955)
    [Upward Pruned] 54 supersets removed from queue.
  [FULL ] [1, 76, 3, 9] -> Rank: 9/9 (Params: 331)
    [Upward Pruned] 224 supersets removed from queue.
  [FULL ] [1, 5, 86, 9] -> Rank: 9/9 (Params: 1209)
    [Upward Pruned] 553 supersets removed from queue.
  [FULL ] [1, 4, 29, 9] -> Rank: 9/9 (Params: 381)
    [Upward Pruned] 555 supersets removed from queue.
  [FULL ] [1, 248, 2, 9] -> Rank: 9/9 (Params: 762)
    [Upward Pruned] 52 supersets removed from queue.
  [FULL ] [1, 95, 2, 9] -> Rank: 9/9 (Params: 303)
    [Upward Pruned] 152 supersets removed from queue.
  [FULL ] [1, 7, 11, 9] -> Rank: 9/9 (Params: 183)
    [Upward Pruned] 125 supersets removed from queue.
  [FULL ] [1, 6, 11, 9] -> Rank: 9/9 (Params: 171)
    [Upward Pruned] 17 supersets removed from queue.
  [FULL ] [1, 71, 2, 9] -> Rank: 9/9 (Params: 231)
    [Upward Pruned] 28 supersets removed from queue.
  [FULL ] [1, 3, 134, 9] -> Rank: 9/9 (Params: 1611)
    [Upward Pruned] 111 supersets removed from queue.
  [FULL ] [1, 3, 48, 9] -> Rank: 9/9 (Params: 579)
    [Upward Pruned] 85 supersets removed from queue.
  [FULL ] [1, 12, 8, 9] -> Rank: 9/9 (Params: 180)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 2, 183, 9] -> Rank: 9/9 (Params: 2015)
    [Upward Pruned] 117 supersets removed from queue.
  [FULL ] [1, 53, 2, 9] -> Rank: 9/9 (Params: 177)
    [Upward Pruned] 35 supersets removed from queue.
  [FULL ] [1, 2, 45, 9] -> Rank: 9/9 (Params: 497)
    [Upward Pruned] 140 supersets removed from queue.
  [FULL ] [1, 37, 2, 9] -> Rank: 9/9 (Params: 129)
    [Upward Pruned] 31 supersets removed from queue.
  [FULL ] [1, 2, 26, 9] -> Rank: 9/9 (Params: 288)
    [Upward Pruned] 43 supersets removed from queue.
  [FULL ] [1, 7, 6, 9] -> Rank: 9/9 (Params: 103)
    [Upward Pruned] 35 supersets removed from queue.
  [FULL ] [1, 3, 8, 9] -> Rank: 9/9 (Params: 99)
    [Upward Pruned] 56 supersets removed from queue.
  [FULL ] [1, 27, 3, 9] -> Rank: 9/9 (Params: 135)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 4, 6, 9] -> Rank: 9/9 (Params: 82)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 21, 2, 9] -> Rank: 9/9 (Params: 81)
    [Upward Pruned] 21 supersets removed from queue.
  [FULL ] [1, 2, 17, 9] -> Rank: 9/9 (Params: 189)
    [Upward Pruned] 8 supersets removed from queue.
  [FULL ] [1, 2, 10, 9] -> Rank: 9/9 (Params: 112)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [1, 11, 4, 9] -> Rank: 9/9 (Params: 91)
    [Upward Pruned] 19 supersets removed from queue.
  [FULL ] [1, 6, 4, 9] -> Rank: 9/9 (Params: 66)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 3, 6, 9] -> Rank: 9/9 (Params: 75)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 10, 3, 9] -> Rank: 9/9 (Params: 67)
    [Upward Pruned] 10 supersets removed from queue.
  [FULL ] [1, 8, 2, 9] -> Rank: 9/9 (Params: 42)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 2, 6, 9] -> Rank: 9/9 (Params: 68)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 7, 3, 9] -> Rank: 9/9 (Params: 55)
  [FULL ] [1, 2, 3, 9] -> Rank: 9/9 (Params: 35)
    [Upward Pruned] 12 supersets removed from queue.
  [FULL ] [1, 6, 2, 9] -> Rank: 9/9 (Params: 36)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 5, 2, 9] -> Rank: 9/9 (Params: 33)
  [FULL ] [1, 2, 2, 9] -> Rank: 9/9 (Params: 24)
    [Upward Pruned] 2 supersets removed from queue.

Added 56 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_9_r5_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=6 ---
  Target Ambient Dimension: 9
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 108, 9] -> Rank: 9/9 (Params: 1080)
    [Upward Pruned] 192 supersets removed from queue.
  [FULL ] [1, 35, 9] -> Rank: 9/9 (Params: 350)
    [Upward Pruned] 72 supersets removed from queue.
  [FULL ] [1, 7, 9] -> Rank: 9/9 (Params: 70)
    [Upward Pruned] 27 supersets removed from queue.
  [FULL ] [1, 4, 9] -> Rank: 9/9 (Params: 40)
    [Upward Pruned] 2 supersets removed from queue.

  [FULL ] [1, 3, 9] -> Rank: 9/9 (Params: 30)
  [FULL ] [1, 2, 9] -> Rank: 9/9 (Params: 20)

--- RANDOM SEARCH: h=3, exponent=6 ---
  Target Ambient Dimension: 9
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 54, 75, 9] -> Rank: 9/9 (Params: 4779)
    [Upward Pruned] 55821 supersets removed from queue.
  [FULL ] [1, 19, 120, 9] -> Rank: 9/9 (Params: 3379)
    [Upward Pruned] 6334 supersets removed from queue.
  [FULL ] [1, 227, 28, 9] -> Rank: 9/9 (Params: 6835)
    [Upward Pruned] 3477 supersets removed from queue.
  [FULL ] [1, 7, 149, 9] -> Rank: 9/9 (Params: 2391)
    [Upward Pruned] 1823 supersets removed from queue.
  [FULL ] [1, 13, 115, 9] -> Rank: 9/9 (Params: 2543)
    [Upward Pruned] 378 supersets removed from queue.
  [FULL ] [1, 90, 47, 9] -> Rank: 9/9 (Params: 4743)
    [Upward Pruned] 3835 supersets removed from queue.
  [FULL ] [1, 232, 21, 9] -> Rank: 9/9 (Params: 5293)
    [Upward Pruned] 482 supersets removed from queue.
  [FULL ] [1, 217, 22, 9] -> Rank: 9/9 (Params: 5189)
    [Upward Pruned] 279 supersets removed from queue.
  [FULL ] [1, 46, 7, 9] -> Rank: 9/9 (Params: 431)
    [Upward Pruned] 9582 supersets removed from queue.
  [FULL ] [1, 21, 49, 9] -> Rank: 9/9 (Params: 1491)
    [Upward Pruned] 1649 supersets removed from queue.
  [FULL ] [1, 4, 6, 9] -> Rank: 9/9 (Params: 82)
    [Upward Pruned] 3944 supersets removed from queue.
  [FULL ] [1, 25, 3, 9] -> Rank: 9/9 (Params: 127)
    [Upward Pruned] 827 supersets removed from queue.
  [FULL ] [1, 2, 181, 9] -> Rank: 9/9 (Params: 1993)
    [Upward Pruned] 239 supersets removed from queue.
  [FULL ] [1, 96, 2, 9] -> Rank: 9/9 (Params: 306)
    [Upward Pruned] 204 supersets removed from queue.
  [FULL ] [1, 3, 161, 9] -> Rank: 9/9 (Params: 1935)
    [Upward Pruned] 19 supersets removed from queue.
  [FULL ] [1, 3, 159, 9] -> Rank: 9/9 (Params: 1911)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 3, 60, 9] -> Rank: 9/9 (Params: 723)
    [Upward Pruned] 98 supersets removed from queue.
  [FULL ] [1, 2, 43, 9] -> Rank: 9/9 (Params: 475)
    [Upward Pruned] 154 supersets removed from queue.
  [FULL ] [1, 2, 17, 9] -> Rank: 9/9 (Params: 189)
    [Upward Pruned] 51 supersets removed from queue.
  [FULL ] [1, 60, 2, 9] -> Rank: 9/9 (Params: 198)
    [Upward Pruned] 35 supersets removed from queue.
  [FULL ] [1, 19, 4, 9] -> Rank: 9/9 (Params: 131)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 13, 2, 9] -> Rank: 9/9 (Params: 57)
    [Upward Pruned] 70 supersets removed from queue.
  [FULL ] [1, 12, 3, 9] -> Rank: 9/9 (Params: 75)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 3, 7, 9] -> Rank: 9/9 (Params: 87)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 2, 8, 9] -> Rank: 9/9 (Params: 90)
    [Upward Pruned] 8 supersets removed from queue.
  [FULL ] [1, 6, 2, 9] -> Rank: 9/9 (Params: 36)
    [Upward Pruned] 24 supersets removed from queue.
  [FULL ] [1, 2, 2, 9] -> Rank: 9/9 (Params: 24)
    [Upward Pruned] 18 supersets removed from queue.

Added 33 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_9_r6_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=7 ---
  Target Ambient Dimension: 9
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 280, 9] -> Rank: 9/9 (Params: 2800)
    [Upward Pruned] 20 supersets removed from queue.

  [FULL ] [1, 191, 9] -> Rank: 9/9 (Params: 1910)
    [Upward Pruned] 88 supersets removed from queue.
  [FULL ] [1, 115, 9] -> Rank: 9/9 (Params: 1150)
    [Upward Pruned] 75 supersets removed from queue.
  [FULL ] [1, 75, 9] -> Rank: 9/9 (Params: 750)
    [Upward Pruned] 39 supersets removed from queue.
  [FULL ] [1, 59, 9] -> Rank: 9/9 (Params: 590)
    [Upward Pruned] 15 supersets removed from queue.
  [FULL ] [1, 2, 9] -> Rank: 9/9 (Params: 20)
    [Upward Pruned] 56 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=7 ---
  Target Ambient Dimension: 9
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 235, 282, 9] -> Rank: 9/9 (Params: 69043)
    [Upward Pruned] 1253 supersets removed from queue.
  [FULL ] [1, 240, 42, 9] -> Rank: 9/9 (Params: 10698)
    [Upward Pruned] 14639 supersets removed from queue.
  [FULL ] [1, 71, 237, 9] -> Rank: 9/9 (Params: 19031)
    [Upward Pruned] 10720 supersets removed from queue.
  [FULL ] [1, 175, 190, 9] -> Rank: 9/9 (Params: 35135)
    [Upward Pruned] 3054 supersets removed from queue.
  [FULL ] [1, 204, 130, 9] -> Rank: 9/9 (Params: 27894)
    [Upward Pruned] 2159 supersets removed from queue.
  [FULL ] [1, 90, 221, 9] -> Rank: 9/9 (Params: 21969)
    [Upward Pruned] 1359 supersets removed from queue.
  [FULL ] [1, 131, 37, 9] -> Rank: 9/9 (Params: 5311)
    [Upward Pruned] 16185 supersets removed from queue.
  [FULL ] [1, 49, 69, 9] -> Rank: 9/9 (Params: 4051)
    [Upward Pruned] 14527 supersets removed from queue.
  [FULL ] [1, 40, 295, 9] -> Rank: 9/9 (Params: 14495)
    [Upward Pruned] 53 supersets removed from queue.
  [FULL ] [1, 8, 193, 9] -> Rank: 9/9 (Params: 3289)
    [Upward Pruned] 4373 supersets removed from queue.
  [FULL ] [1, 58, 34, 9] -> Rank: 9/9 (Params: 2336)
    [Upward Pruned] 3064 supersets removed from queue.
  [FULL ] [1, 7, 189, 9] -> Rank: 9/9 (Params: 3031)
    [Upward Pruned] 275 supersets removed from queue.
  [FULL ] [1, 12, 148, 9] -> Rank: 9/9 (Params: 3120)
    [Upward Pruned] 1516 supersets removed from queue.
  [FULL ] [1, 14, 60, 9] -> Rank: 9/9 (Params: 1394)
    [Upward Pruned] 3160 supersets removed from queue.
  [FULL ] [1, 296, 16, 9] -> Rank: 9/9 (Params: 5176)
    [Upward Pruned] 89 supersets removed from queue.
  [FULL ] [1, 201, 22, 9] -> Rank: 9/9 (Params: 4821)
    [Upward Pruned] 1139 supersets removed from queue.
  [FULL ] [1, 163, 10, 9] -> Rank: 9/9 (Params: 1883)
    [Upward Pruned] 2081 supersets removed from queue.
  [FULL ] [1, 13, 71, 9] -> Rank: 9/9 (Params: 1575)
    [Upward Pruned] 76 supersets removed from queue.
  [FULL ] [1, 6, 166, 9] -> Rank: 9/9 (Params: 2496)
    [Upward Pruned] 249 supersets removed from queue.
  [FULL ] [1, 286, 3, 9] -> Rank: 9/9 (Params: 1171)
    [Upward Pruned] 104 supersets removed from queue.
  [FULL ] [1, 117, 29, 9] -> Rank: 9/9 (Params: 3771)
    [Upward Pruned] 229 supersets removed from queue.
  [FULL ] [1, 35, 31, 9] -> Rank: 9/9 (Params: 1399)
    [Upward Pruned] 843 supersets removed from queue.
  [FULL ] [1, 141, 25, 9] -> Rank: 9/9 (Params: 3891)
    [Upward Pruned] 87 supersets removed from queue.
  [FULL ] [1, 138, 19, 9] -> Rank: 9/9 (Params: 2931)
    [Upward Pruned] 161 supersets removed from queue.
  [FULL ] [1, 174, 4, 9] -> Rank: 9/9 (Params: 906)
    [Upward Pruned] 671 supersets removed from queue.
  [FULL ] [1, 3, 173, 9] -> Rank: 9/9 (Params: 2079)
    [Upward Pruned] 383 supersets removed from queue.
  [FULL ] [1, 128, 7, 9] -> Rank: 9/9 (Params: 1087)
    [Upward Pruned] 552 supersets removed from queue.
  [FULL ] [1, 24, 51, 9] -> Rank: 9/9 (Params: 1707)
    [Upward Pruned] 98 supersets removed from queue.
  [FULL ] [1, 124, 2, 9] -> Rank: 9/9 (Params: 390)
    [Upward Pruned] 576 supersets removed from queue.
  [FULL ] [1, 71, 8, 9] -> Rank: 9/9 (Params: 711)
    [Upward Pruned] 1204 supersets removed from queue.
  [FULL ] [1, 2, 297, 9] -> Rank: 9/9 (Params: 3269)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 12, 99, 9] -> Rank: 9/9 (Params: 2091)
    [Upward Pruned] 48 supersets removed from queue.
  [FULL ] [1, 27, 26, 9] -> Rank: 9/9 (Params: 963)
    [Upward Pruned] 379 supersets removed from queue.
  [FULL ] [1, 21, 19, 9] -> Rank: 9/9 (Params: 591)
    [Upward Pruned] 526 supersets removed from queue.
  [FULL ] [1, 16, 28, 9] -> Rank: 9/9 (Params: 716)
    [Upward Pruned] 159 supersets removed from queue.
  [FULL ] [1, 70, 17, 9] -> Rank: 9/9 (Params: 1413)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 10, 116, 9] -> Rank: 9/9 (Params: 2214)
    [Upward Pruned] 99 supersets removed from queue.
  [FULL ] [1, 6, 108, 9] -> Rank: 9/9 (Params: 1626)
    [Upward Pruned] 247 supersets removed from queue.
  [FULL ] [1, 13, 55, 9] -> Rank: 9/9 (Params: 1223)
    [Upward Pruned] 25 supersets removed from queue.
  [FULL ] [1, 30, 12, 9] -> Rank: 9/9 (Params: 498)
    [Upward Pruned] 284 supersets removed from queue.
  [FULL ] [1, 105, 6, 9] -> Rank: 9/9 (Params: 789)
    [Upward Pruned] 37 supersets removed from queue.
  [FULL ] [1, 21, 11, 9] -> Rank: 9/9 (Params: 351)
    [Upward Pruned] 112 supersets removed from queue.
  [FULL ] [1, 6, 61, 9] -> Rank: 9/9 (Params: 921)
    [Upward Pruned] 319 supersets removed from queue.
  [FULL ] [1, 47, 5, 9] -> Rank: 9/9 (Params: 327)
    [Upward Pruned] 264 supersets removed from queue.
  [FULL ] [1, 2, 256, 9] -> Rank: 9/9 (Params: 2818)
    [Upward Pruned] 40 supersets removed from queue.
  [FULL ] [1, 20, 9, 9] -> Rank: 9/9 (Params: 281)
    [Upward Pruned] 70 supersets removed from queue.
  [FULL ] [1, 10, 2, 9] -> Rank: 9/9 (Params: 48)
    [Upward Pruned] 859 supersets removed from queue.
  [FULL ] [1, 2, 204, 9] -> Rank: 9/9 (Params: 2246)
    [Upward Pruned] 51 supersets removed from queue.
  [FULL ] [1, 5, 71, 9] -> Rank: 9/9 (Params: 999)
    [Upward Pruned] 101 supersets removed from queue.
  [FULL ] [1, 3, 159, 9] -> Rank: 9/9 (Params: 1911)
    [Upward Pruned] 27 supersets removed from queue.
  [FULL ] [1, 3, 33, 9] -> Rank: 9/9 (Params: 399)
    [Upward Pruned] 401 supersets removed from queue.
  [FULL ] [1, 2, 65, 9] -> Rank: 9/9 (Params: 717)
    [Upward Pruned] 138 supersets removed from queue.
  [FULL ] [1, 7, 13, 9] -> Rank: 9/9 (Params: 215)
    [Upward Pruned] 59 supersets removed from queue.
  [FULL ] [1, 8, 12, 9] -> Rank: 9/9 (Params: 212)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 7, 3, 9] -> Rank: 9/9 (Params: 55)
    [Upward Pruned] 27 supersets removed from queue.
  [FULL ] [1, 3, 2, 9] -> Rank: 9/9 (Params: 27)
    [Upward Pruned] 126 supersets removed from queue.
  [FULL ] [1, 2, 40, 9] -> Rank: 9/9 (Params: 442)
    [Upward Pruned] 24 supersets removed from queue.
  [FULL ] [1, 2, 36, 9] -> Rank: 9/9 (Params: 398)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 2, 21, 9] -> Rank: 9/9 (Params: 233)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [1, 2, 8, 9] -> Rank: 9/9 (Params: 90)
    [Upward Pruned] 12 supersets removed from queue.
  [FULL ] [1, 2, 4, 9] -> Rank: 9/9 (Params: 46)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 2, 2, 9] -> Rank: 9/9 (Params: 24)
    [Upward Pruned] 1 supersets removed from queue.

Added 68 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_9_r7_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=8 ---
  Target Ambient Dimension: 9
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 262, 9] -> Rank: 9/9 (Params: 2620)
    [Upward Pruned] 38 supersets removed from queue.
  [FULL ] [1, 242, 9] -> Rank: 9/9 (Params: 2420)
    [Upward Pruned] 19 supersets removed from queue.
  [FULL ] [1, 85, 9] -> Rank: 9/9 (Params: 850)
    [Upward Pruned] 156 supersets removed from queue.
  [FULL ] [1, 53, 9] -> Rank: 9/9 (Params: 530)
    [Upward Pruned] 31 supersets removed from queue.
  [FULL ] [1, 14, 9] -> Rank: 9/9 (Params: 140)
    [Upward Pruned] 38 supersets removed from queue.
  [FULL ] [1, 11, 9] -> Rank: 9/9 (Params: 110)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 9, 9] -> Rank: 9/9 (Params: 90)
    [Upward Pruned] 1 supersets removed from queue.

  [FULL ] [1, 2, 9] -> Rank: 9/9 (Params: 20)
    [Upward Pruned] 6 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=8 ---
  Target Ambient Dimension: 9
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 261, 229, 9] -> Rank: 9/9 (Params: 62091)
    [Upward Pruned] 2879 supersets removed from queue.
  [FULL ] [1, 6, 276, 9] -> Rank: 9/9 (Params: 4146)
    [Upward Pruned] 6374 supersets removed from queue.
  [FULL ] [1, 266, 64, 9] -> Rank: 9/9 (Params: 17866)
    [Upward Pruned] 5774 supersets removed from queue.
  [FULL ] [1, 239, 252, 9] -> Rank: 9/9 (Params: 62735)
    [Upward Pruned] 527 supersets removed from queue.
  [FULL ] [1, 207, 114, 9] -> Rank: 9/9 (Params: 24831)
    [Upward Pruned] 8794 supersets removed from queue.
  [FULL ] [1, 65, 209, 9] -> Rank: 9/9 (Params: 15531)
    [Upward Pruned] 9513 supersets removed from queue.
  [FULL ] [1, 103, 206, 9] -> Rank: 9/9 (Params: 23175)
    [Upward Pruned] 311 supersets removed from queue.
  [FULL ] [1, 55, 149, 9] -> Rank: 9/9 (Params: 9591)
    [Upward Pruned] 9477 supersets removed from queue.
  [FULL ] [1, 116, 94, 9] -> Rank: 9/9 (Params: 11866)
    [Upward Pruned] 6184 supersets removed from queue.
  [FULL ] [1, 194, 60, 9] -> Rank: 9/9 (Params: 12374)
    [Upward Pruned] 2587 supersets removed from queue.
  [FULL ] [1, 25, 151, 9] -> Rank: 9/9 (Params: 5159)
    [Upward Pruned] 3749 supersets removed from queue.
  [FULL ] [1, 19, 89, 9] -> Rank: 9/9 (Params: 2511)
    [Upward Pruned] 7031 supersets removed from queue.
  [FULL ] [1, 43, 77, 9] -> Rank: 9/9 (Params: 4047)
    [Upward Pruned] 1811 supersets removed from queue.
  [FULL ] [1, 27, 63, 9] -> Rank: 9/9 (Params: 2295)
    [Upward Pruned] 2529 supersets removed from queue.
  [FULL ] [1, 194, 6, 9] -> Rank: 9/9 (Params: 1412)
    [Upward Pruned] 5777 supersets removed from queue.
  [FULL ] [1, 2, 237, 9] -> Rank: 9/9 (Params: 2609)
    [Upward Pruned] 762 supersets removed from queue.
  [FULL ] [1, 131, 21, 9] -> Rank: 9/9 (Params: 3071)
    [Upward Pruned] 2645 supersets removed from queue.
  [FULL ] [1, 60, 51, 9] -> Rank: 9/9 (Params: 3579)
    [Upward Pruned] 851 supersets removed from queue.
  [FULL ] [1, 15, 116, 9] -> Rank: 9/9 (Params: 2799)
    [Upward Pruned] 483 supersets removed from queue.
  [FULL ] [1, 23, 57, 9] -> Rank: 9/9 (Params: 1847)
    [Upward Pruned] 325 supersets removed from queue.
  [FULL ] [1, 41, 42, 9] -> Rank: 9/9 (Params: 2141)
    [Upward Pruned] 923 supersets removed from queue.
  [FULL ] [1, 18, 88, 9] -> Rank: 9/9 (Params: 2394)
    [Upward Pruned] 31 supersets removed from queue.
  [FULL ] [1, 51, 35, 9] -> Rank: 9/9 (Params: 2151)
    [Upward Pruned] 559 supersets removed from queue.
  [FULL ] [1, 117, 2, 9] -> Rank: 9/9 (Params: 369)
    [Upward Pruned] 2086 supersets removed from queue.
  [FULL ] [1, 15, 105, 9] -> Rank: 9/9 (Params: 2535)
    [Upward Pruned] 32 supersets removed from queue.
  [FULL ] [1, 10, 207, 9] -> Rank: 9/9 (Params: 3943)
    [Upward Pruned] 149 supersets removed from queue.
  [FULL ] [1, 14, 17, 9] -> Rank: 9/9 (Params: 405)
    [Upward Pruned] 2966 supersets removed from queue.
  [FULL ] [1, 2, 161, 9] -> Rank: 9/9 (Params: 1773)
    [Upward Pruned] 791 supersets removed from queue.
  [FULL ] [1, 6, 111, 9] -> Rank: 9/9 (Params: 1671)
    [Upward Pruned] 399 supersets removed from queue.
  [FULL ] [1, 72, 10, 9] -> Rank: 9/9 (Params: 882)
    [Upward Pruned] 314 supersets removed from queue.
  [FULL ] [1, 20, 14, 9] -> Rank: 9/9 (Params: 426)
    [Upward Pruned] 155 supersets removed from queue.
  [FULL ] [1, 11, 85, 9] -> Rank: 9/9 (Params: 1711)
    [Upward Pruned] 77 supersets removed from queue.
  [FULL ] [1, 7, 92, 9] -> Rank: 9/9 (Params: 1479)
    [Upward Pruned] 75 supersets removed from queue.
  [FULL ] [1, 5, 27, 9] -> Rank: 9/9 (Params: 383)
    [Upward Pruned] 651 supersets removed from queue.
  [FULL ] [1, 14, 9, 9] -> Rank: 9/9 (Params: 221)
    [Upward Pruned] 352 supersets removed from queue.
  [FULL ] [1, 44, 7, 9] -> Rank: 9/9 (Params: 415)
    [Upward Pruned] 145 supersets removed from queue.
  [FULL ] [1, 86, 3, 9] -> Rank: 9/9 (Params: 371)
    [Upward Pruned] 123 supersets removed from queue.
  [FULL ] [1, 2, 143, 9] -> Rank: 9/9 (Params: 1575)
    [Upward Pruned] 53 supersets removed from queue.
  [FULL ] [1, 3, 52, 9] -> Rank: 9/9 (Params: 627)
    [Upward Pruned] 181 supersets removed from queue.
  [FULL ] [1, 44, 3, 9] -> Rank: 9/9 (Params: 203)
    [Upward Pruned] 167 supersets removed from queue.
  [FULL ] [1, 8, 25, 9] -> Rank: 9/9 (Params: 433)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [1, 13, 22, 9] -> Rank: 9/9 (Params: 497)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 38, 6, 9] -> Rank: 9/9 (Params: 320)
    [Upward Pruned] 17 supersets removed from queue.
  [FULL ] [1, 12, 24, 9] -> Rank: 9/9 (Params: 516)
  [FULL ] [1, 2, 47, 9] -> Rank: 9/9 (Params: 519)
    [Upward Pruned] 105 supersets removed from queue.
  [FULL ] [1, 29, 2, 9] -> Rank: 9/9 (Params: 105)
    [Upward Pruned] 159 supersets removed from queue.
  [FULL ] [1, 11, 23, 9] -> Rank: 9/9 (Params: 471)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [1, 2, 30, 9] -> Rank: 9/9 (Params: 332)
    [Upward Pruned] 50 supersets removed from queue.
  [FULL ] [1, 7, 17, 9] -> Rank: 9/9 (Params: 279)
    [Upward Pruned] 50 supersets removed from queue.
  [FULL ] [1, 28, 3, 9] -> Rank: 9/9 (Params: 139)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 12, 15, 9] -> Rank: 9/9 (Params: 327)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 3, 14, 9] -> Rank: 9/9 (Params: 171)
    [Upward Pruned] 74 supersets removed from queue.
  [FULL ] [1, 26, 6, 9] -> Rank: 9/9 (Params: 236)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 20, 5, 9] -> Rank: 9/9 (Params: 165)
    [Upward Pruned] 25 supersets removed from queue.
  [FULL ] [1, 4, 13, 9] -> Rank: 9/9 (Params: 173)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [1, 21, 2, 9] -> Rank: 9/9 (Params: 81)
    [Upward Pruned] 21 supersets removed from queue.
  [FULL ] [1, 12, 12, 9] -> Rank: 9/9 (Params: 264)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 18, 7, 9] -> Rank: 9/9 (Params: 207)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 9, 9, 9] -> Rank: 9/9 (Params: 171)
    [Upward Pruned] 17 supersets removed from queue.
  [FULL ] [1, 15, 7, 9] -> Rank: 9/9 (Params: 183)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 14, 3, 9] -> Rank: 9/9 (Params: 83)
    [Upward Pruned] 27 supersets removed from queue.
  [FULL ] [1, 10, 2, 9] -> Rank: 9/9 (Params: 48)
    [Upward Pruned] 34 supersets removed from queue.
  [FULL ] [1, 7, 2, 9] -> Rank: 9/9 (Params: 39)
    [Upward Pruned] 28 supersets removed from queue.
  [FULL ] [1, 5, 11, 9] -> Rank: 9/9 (Params: 159)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 4, 7, 9] -> Rank: 9/9 (Params: 95)
    [Upward Pruned] 13 supersets removed from queue.
  [FULL ] [1, 2, 6, 9] -> Rank: 9/9 (Params: 68)
    [Upward Pruned] 34 supersets removed from queue.
  [FULL ] [1, 5, 3, 9] -> Rank: 9/9 (Params: 47)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [1, 2, 2, 9] -> Rank: 9/9 (Params: 24)
    [Upward Pruned] 13 supersets removed from queue.

Added 76 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_9_r8_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=9 ---
  Target Ambient Dimension: 9
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [1, 4, 9] -> Rank: 9/9 (Params: 40)
    [Upward Pruned] 296 supersets removed from queue.
  [FULL ] [1, 2, 9] -> Rank: 9/9 (Params: 20)
    [Upward Pruned] 1 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=9 ---
  Target Ambient Dimension: 9
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [1, 55, 39, 9] -> Rank: 9/9 (Params: 2551)
    [Upward Pruned] 64451 supersets removed from queue.
  [FULL ] [1, 72, 14, 9] -> Rank: 9/9 (Params: 1206)
    [Upward Pruned] 5724 supersets removed from queue.
  [FULL ] [1, 118, 4, 9] -> Rank: 9/9 (Params: 626)
    [Upward Pruned] 1829 supersets removed from queue.
  [FULL ] [1, 21, 141, 9] -> Rank: 9/9 (Params: 4251)
    [Upward Pruned] 5439 supersets removed from queue.
  [FULL ] [1, 6, 262, 9] -> Rank: 9/9 (Params: 3936)
    [Upward Pruned] 584 supersets removed from queue.
  [FULL ] [1, 49, 97, 9] -> Rank: 9/9 (Params: 5675)
    [Upward Pruned] 263 supersets removed from queue.
  [FULL ] [1, 3, 145, 9] -> Rank: 9/9 (Params: 1743)
    [Upward Pruned] 2222 supersets removed from queue.
  [FULL ] [1, 37, 46, 9] -> Rank: 9/9 (Params: 2153)
    [Upward Pruned] 1445 supersets removed from queue.
  [FULL ] [1, 2, 10, 9] -> Rank: 9/9 (Params: 112)
    [Upward Pruned] 6141 supersets removed from queue.
  [FULL ] [1, 126, 3, 9] -> Rank: 9/9 (Params: 531)
    [Upward Pruned] 174 supersets removed from queue.
  [FULL ] [1, 113, 6, 9] -> Rank: 9/9 (Params: 845)
    [Upward Pruned] 19 supersets removed from queue.
  [FULL ] [1, 2, 6, 9] -> Rank: 9/9 (Params: 68)
    [Upward Pruned] 443 supersets removed from queue.
  [FULL ] [1, 48, 4, 9] -> Rank: 9/9 (Params: 276)
    [Upward Pruned] 139 supersets removed from queue.
  [FULL ] [1, 121, 2, 9] -> Rank: 9/9 (Params: 381)
    [Upward Pruned] 184 supersets removed from queue.
  [FULL ] [1, 51, 2, 9] -> Rank: 9/9 (Params: 171)
    [Upward Pruned] 139 supersets removed from queue.
  [FULL ] [1, 8, 2, 9] -> Rank: 9/9 (Params: 42)
    [Upward Pruned] 165 supersets removed from queue.
  [FULL ] [1, 4, 5, 9] -> Rank: 9/9 (Params: 69)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [1, 3, 5, 9] -> Rank: 9/9 (Params: 63)
  [FULL ] [1, 4, 3, 9] -> Rank: 9/9 (Params: 43)
    [Upward Pruned] 7 supersets removed from queue.
  [FULL ] [1, 6, 2, 9] -> Rank: 9/9 (Params: 36)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 4, 2, 9] -> Rank: 9/9 (Params: 30)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [1, 2, 3, 9] -> Rank: 9/9 (Params: 35)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [1, 3, 2, 9] -> Rank: 9/9 (Params: 27)
  [FULL ] [1, 2, 2, 9] -> Rank: 9/9 (Params: 24)

Added 26 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/1_9_r9_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=1 ---
  Target Ambient Dimension: 2
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.

  [FULL ] [2, 95, 1] -> Rank: 2/2 (Params: 285)
    [Upward Pruned] 205 supersets removed from queue.
  [FULL ] [2, 49, 1] -> Rank: 2/2 (Params: 147)
    [Upward Pruned] 45 supersets removed from queue.
  [FULL ] [2, 36, 1] -> Rank: 2/2 (Params: 108)
    [Upward Pruned] 12 supersets removed from queue.
  [FULL ] [2, 21, 1] -> Rank: 2/2 (Params: 63)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [2, 14, 1] -> Rank: 2/2 (Params: 42)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [2, 4, 1] -> Rank: 2/2 (Params: 12)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [2, 3, 1] -> Rank: 2/2 (Params: 9)
  [FULL ] [2, 2, 1] -> Rank: 2/2 (Params: 6)

--- RANDOM SEARCH: h=3, exponent=1 ---
  Target Ambient Dimension: 2
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [2, 46, 279, 1] -> Rank: 2/2 (Params: 13205)
    [Upward Pruned] 5609 supersets removed from queue.
  [FULL ] [2, 67, 134, 1] -> Rank: 2/2 (Params: 9246)
    [Upward Pruned] 33929 supersets removed from queue.
  [FULL ] [2, 44, 140, 1] -> Rank: 2/2 (Params: 6388)
    [Upward Pruned] 3240 supersets removed from queue.
  [FULL ] [2, 50, 21, 1] -> Rank: 2/2 (Params: 1171)
    [Upward Pruned] 28464 supersets removed from queue.
  [FULL ] [2, 181, 7, 1] -> Rank: 2/2 (Params: 1636)
    [Upward Pruned] 1679 supersets removed from queue.
  [FULL ] [2, 15, 136, 1] -> Rank: 2/2 (Params: 2206)
    [Upward Pruned] 4808 supersets removed from queue.
  [FULL ] [2, 29, 100, 1] -> Rank: 2/2 (Params: 3058)
    [Upward Pruned] 755 supersets removed from queue.
  [FULL ] [2, 6, 185, 1] -> Rank: 2/2 (Params: 1307)
    [Upward Pruned] 1043 supersets removed from queue.
  [FULL ] [2, 8, 106, 1] -> Rank: 2/2 (Params: 970)
    [Upward Pruned] 972 supersets removed from queue.
  [FULL ] [2, 11, 36, 1] -> Rank: 2/2 (Params: 454)
    [Upward Pruned] 2603 supersets removed from queue.
  [FULL ] [2, 169, 6, 1] -> Rank: 2/2 (Params: 1358)
    [Upward Pruned] 299 supersets removed from queue.
  [FULL ] [2, 260, 4, 1] -> Rank: 2/2 (Params: 1564)
    [Upward Pruned] 81 supersets removed from queue.
  [FULL ] [2, 177, 3, 1] -> Rank: 2/2 (Params: 888)
    [Upward Pruned] 289 supersets removed from queue.
  [FULL ] [2, 126, 18, 1] -> Rank: 2/2 (Params: 2538)
    [Upward Pruned] 128 supersets removed from queue.
  [FULL ] [2, 54, 9, 1] -> Rank: 2/2 (Params: 603)
    [Upward Pruned] 1250 supersets removed from queue.
  [FULL ] [2, 6, 167, 1] -> Rank: 2/2 (Params: 1181)
    [Upward Pruned] 35 supersets removed from queue.
  [FULL ] [2, 7, 49, 1] -> Rank: 2/2 (Params: 406)
    [Upward Pruned] 288 supersets removed from queue.
  [FULL ] [2, 14, 2, 1] -> Rank: 2/2 (Params: 58)
    [Upward Pruned] 2260 supersets removed from queue.
  [FULL ] [2, 6, 134, 1] -> Rank: 2/2 (Params: 950)
    [Upward Pruned] 32 supersets removed from queue.
  [FULL ] [2, 5, 207, 1] -> Rank: 2/2 (Params: 1252)
    [Upward Pruned] 93 supersets removed from queue.
  [FULL ] [2, 3, 171, 1] -> Rank: 2/2 (Params: 690)
    [Upward Pruned] 295 supersets removed from queue.
  [FULL ] [2, 6, 55, 1] -> Rank: 2/2 (Params: 397)
    [Upward Pruned] 78 supersets removed from queue.
  [FULL ] [2, 7, 17, 1] -> Rank: 2/2 (Params: 150)
    [Upward Pruned] 184 supersets removed from queue.
  [FULL ] [2, 3, 15, 1] -> Rank: 2/2 (Params: 66)
    [Upward Pruned] 521 supersets removed from queue.
  [FULL ] [2, 2, 106, 1] -> Rank: 2/2 (Params: 322)
    [Upward Pruned] 194 supersets removed from queue.
  [FULL ] [2, 9, 4, 1] -> Rank: 2/2 (Params: 58)
    [Upward Pruned] 54 supersets removed from queue.
  [FULL ] [2, 2, 5, 1] -> Rank: 2/2 (Params: 19)
    [Upward Pruned] 160 supersets removed from queue.
  [FULL ] [2, 10, 3, 1] -> Rank: 2/2 (Params: 53)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [2, 6, 3, 1] -> Rank: 2/2 (Params: 33)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [2, 11, 2, 1] -> Rank: 2/2 (Params: 46)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [2, 3, 3, 1] -> Rank: 2/2 (Params: 18)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [2, 7, 2, 1] -> Rank: 2/2 (Params: 30)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [2, 2, 3, 1] -> Rank: 2/2 (Params: 13)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [2, 6, 2, 1] -> Rank: 2/2 (Params: 26)
  [FULL ] [2, 5, 2, 1] -> Rank: 2/2 (Params: 22)
  [FULL ] [2, 3, 2, 1] -> Rank: 2/2 (Params: 14)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [2, 2, 2, 1] -> Rank: 2/2 (Params: 10)

Added 45 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/2_1_r1_architectures.csv'.

Loading existing database from '../data/raw/2_1_r2_architectures.csv'...

--- RANDOM SEARCH: h=2, exponent=2 ---
  Target Ambient Dimension: 3
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 296 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.

--- RANDOM SEARCH: h=3, exponent=2 ---
  Target Ambient Dimension: 5
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 89397 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/2_1_r2_architectures.csv'.

Loading existing database from '../data/raw/2_1_r3_architectures.csv'...

--- RANDOM SEARCH: h=2, exponent=3 ---
  Target Ambient Dimension: 4
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 298 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.

--- RANDOM SEARCH: h=3, exponent=3 ---
  Target Ambient Dimension: 10
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 88803 impossible/redundant architectures.
  Starting sequential evaluation on 597 viable candidates.
  [SHORT] [2, 177, 2, 1] -> Rank: 8/10 (Params: 710)
    [Downward Pruned] 175 subsets removed from queue.
  [SHORT] [2, 2, 138, 1] -> Rank: 6/10 (Params: 418)
    [Downward Pruned] 135 subsets removed from queue.
  [SHORT] [2, 2, 147, 1] -> Rank: 6/10 (Params: 445)
    [Downward Pruned] 8 subsets removed from queue.
  [SHORT] [2, 2, 278, 1] -> Rank: 6/10 (Params: 838)
    [Downward Pruned] 130 subsets removed from queue.
  [SHORT] [2, 223, 2, 1] -> Rank: 8/10 (Params: 894)
    [Downward Pruned] 45 subsets removed from queue.
  [SHORT] [2, 287, 2, 1] -> Rank: 8/10 (Params: 1150)
    [Downward Pruned] 63 subsets removed from queue.
  [SHORT] [2, 2, 296, 1] -> Rank: 6/10 (Params: 892)
    [Downward Pruned] 17 subsets removed from queue.
  [SHORT] [2, 298, 2, 1] -> Rank: 8/10 (Params: 1194)
    [Downward Pruned] 10 subsets removed from queue.
  [SHORT] [2, 299, 2, 1] -> Rank: 8/10 (Params: 1198)
  [SHORT] [2, 2, 297, 1] -> Rank: 6/10 (Params: 895)
  [SHORT] [2, 2, 298, 1] -> Rank: 6/10 (Params: 898)
  [SHORT] [2, 300, 2, 1] -> Rank: 8/10 (Params: 1202)
  [SHORT] [2, 2, 300, 1] -> Rank: 6/10 (Params: 904)
    [Downward Pruned] 1 subsets removed from queue.

Added 13 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/2_1_r3_architectures.csv'.

Loading existing database from '../data/raw/2_1_r4_architectures.csv'...

--- RANDOM SEARCH: h=2, exponent=4 ---
  Target Ambient Dimension: 5
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 294 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.

--- RANDOM SEARCH: h=3, exponent=4 ---
  Target Ambient Dimension: 17
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 88564 impossible/redundant architectures.
  Starting sequential evaluation on 810 viable candidates.
  [SHORT] [2, 212, 3, 1] -> Rank: 15/17 (Params: 1063)
    [Downward Pruned] 363 subsets removed from queue.
  [SHORT] [2, 292, 3, 1] -> Rank: 15/17 (Params: 1463)
    [Downward Pruned] 159 subsets removed from queue.
  [SHORT] [2, 2, 116, 1] -> Rank: 7/17 (Params: 352)
    [Downward Pruned] 85 subsets removed from queue.
  [SHORT] [2, 2, 256, 1] -> Rank: 7/17 (Params: 772)
    [Downward Pruned] 139 subsets removed from queue.
  [SHORT] [2, 2, 276, 1] -> Rank: 7/17 (Params: 832)
    [Downward Pruned] 19 subsets removed from queue.
  [SHORT] [2, 297, 3, 1] -> Rank: 15/17 (Params: 1488)
    [Downward Pruned] 9 subsets removed from queue.
  [SHORT] [2, 2, 283, 1] -> Rank: 7/17 (Params: 853)
    [Downward Pruned] 6 subsets removed from queue.
  [SHORT] [2, 2, 284, 1] -> Rank: 7/17 (Params: 856)
  [SHORT] [2, 2, 297, 1] -> Rank: 7/17 (Params: 895)
    [Downward Pruned] 12 subsets removed from queue.
  [SHORT] [2, 299, 2, 1] -> Rank: 10/17 (Params: 1198)
    [Downward Pruned] 1 subsets removed from queue.
  [SHORT] [2, 2, 299, 1] -> Rank: 7/17 (Params: 901)
    [Downward Pruned] 1 subsets removed from queue.
  [SHORT] [2, 299, 3, 1] -> Rank: 15/17 (Params: 1498)
    [Downward Pruned] 1 subsets removed from queue.
  [SHORT] [2, 300, 2, 1] -> Rank: 10/17 (Params: 1202)
  [SHORT] [2, 2, 300, 1] -> Rank: 7/17 (Params: 904)
  [SHORT] [2, 300, 3, 1] -> Rank: 15/17 (Params: 1503)

Added 15 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/2_1_r4_architectures.csv'.

Loading existing database from '../data/raw/2_1_r5_architectures.csv'...

--- RANDOM SEARCH: h=2, exponent=5 ---
  Target Ambient Dimension: 6
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 296 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.

--- RANDOM SEARCH: h=3, exponent=5 ---
  Target Ambient Dimension: 26
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 88063 impossible/redundant architectures.
  Starting sequential evaluation on 1300 viable candidates.
  [SHORT] [2, 81, 3, 1] -> Rank: 18/26 (Params: 408)
    [Downward Pruned] 81 subsets removed from queue.
  [SHORT] [2, 220, 3, 1] -> Rank: 18/26 (Params: 1103)
    [Downward Pruned] 277 subsets removed from queue.
  [SHORT] [2, 95, 4, 1] -> Rank: 24/26 (Params: 574)
    [Downward Pruned] 54 subsets removed from queue.
  [SHORT] [2, 2, 207, 1] -> Rank: 8/26 (Params: 625)
    [Downward Pruned] 166 subsets removed from queue.
  [SHORT] [2, 245, 3, 1] -> Rank: 18/26 (Params: 1228)
    [Downward Pruned] 49 subsets removed from queue.
  [SHORT] [2, 194, 4, 1] -> Rank: 24/26 (Params: 1168)
    [Downward Pruned] 98 subsets removed from queue.
  [SHORT] [2, 208, 4, 1] -> Rank: 24/26 (Params: 1252)
    [Downward Pruned] 13 subsets removed from queue.
  [SHORT] [2, 3, 67, 1] -> Rank: 23/26 (Params: 274)
    [Downward Pruned] 26 subsets removed from queue.
  [SHORT] [2, 263, 3, 1] -> Rank: 18/26 (Params: 1318)
    [Downward Pruned] 35 subsets removed from queue.
  [SHORT] [2, 3, 86, 1] -> Rank: 23/26 (Params: 350)
    [Downward Pruned] 18 subsets removed from queue.
  [SHORT] [2, 2, 297, 1] -> Rank: 8/26 (Params: 895)
    [Downward Pruned] 89 subsets removed from queue.
  [SHORT] [2, 3, 212, 1] -> Rank: 23/26 (Params: 854)
    [Downward Pruned] 125 subsets removed from queue.
  [SHORT] [2, 261, 4, 1] -> Rank: 24/26 (Params: 1570)
    [Downward Pruned] 52 subsets removed from queue.
  [SHORT] [2, 3, 245, 1] -> Rank: 23/26 (Params: 986)
    [Downward Pruned] 32 subsets removed from queue.
  [SHORT] [2, 282, 4, 1] -> Rank: 24/26 (Params: 1696)
    [Downward Pruned] 58 subsets removed from queue.
  [SHORT] [2, 3, 294, 1] -> Rank: 23/26 (Params: 1182)
    [Downward Pruned] 48 subsets removed from queue.
  [SHORT] [2, 294, 4, 1] -> Rank: 24/26 (Params: 1768)
    [Downward Pruned] 35 subsets removed from queue.
  [SHORT] [2, 3, 297, 1] -> Rank: 23/26 (Params: 1194)
    [Downward Pruned] 2 subsets removed from queue.
  [SHORT] [2, 296, 3, 1] -> Rank: 18/26 (Params: 1483)
    [Downward Pruned] 3 subsets removed from queue.
  [SHORT] [2, 2, 299, 1] -> Rank: 8/26 (Params: 901)
    [Downward Pruned] 1 subsets removed from queue.
  [SHORT] [2, 297, 2, 1] -> Rank: 12/26 (Params: 1190)
  [SHORT] [2, 3, 298, 1] -> Rank: 23/26 (Params: 1198)
  [SHORT] [2, 296, 4, 1] -> Rank: 24/26 (Params: 1780)
    [Downward Pruned] 1 subsets removed from queue.
  [SHORT] [2, 3, 300, 1] -> Rank: 23/26 (Params: 1206)
    [Downward Pruned] 2 subsets removed from queue.
  [SHORT] [2, 300, 4, 1] -> Rank: 24/26 (Params: 1804)
    [Downward Pruned] 10 subsets removed from queue.

Added 25 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/2_1_r5_architectures.csv'.

Loading existing database from '../data/raw/2_1_r6_architectures.csv'...

--- RANDOM SEARCH: h=2, exponent=6 ---
  Target Ambient Dimension: 7
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 293 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.

--- RANDOM SEARCH: h=3, exponent=6 ---
  Target Ambient Dimension: 37
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 87855 impossible/redundant architectures.
  Starting sequential evaluation on 1500 viable candidates.
  [SHORT] [2, 2, 164, 1] -> Rank: 9/37 (Params: 496)
    [Downward Pruned] 113 subsets removed from queue.
  [SHORT] [2, 245, 4, 1] -> Rank: 28/37 (Params: 1474)
    [Downward Pruned] 584 subsets removed from queue.
  [SHORT] [2, 3, 53, 1] -> Rank: 30/37 (Params: 218)
    [Downward Pruned] 2 subsets removed from queue.
  [SHORT] [2, 74, 5, 1] -> Rank: 35/37 (Params: 523)
    [Downward Pruned] 23 subsets removed from queue.
  [SHORT] [2, 213, 5, 1] -> Rank: 35/37 (Params: 1496)
    [Downward Pruned] 138 subsets removed from queue.
  [SHORT] [2, 3, 123, 1] -> Rank: 30/37 (Params: 498)
    [Downward Pruned] 69 subsets removed from queue.
  [SHORT] [2, 3, 205, 1] -> Rank: 30/37 (Params: 826)
    [Downward Pruned] 122 subsets removed from queue.
  [SHORT] [2, 273, 4, 1] -> Rank: 28/37 (Params: 1642)
    [Downward Pruned] 83 subsets removed from queue.
  [SHORT] [2, 3, 230, 1] -> Rank: 30/37 (Params: 926)
    [Downward Pruned] 49 subsets removed from queue.
  [SHORT] [2, 296, 2, 1] -> Rank: 14/37 (Params: 1186)
    [Downward Pruned] 22 subsets removed from queue.
  [SHORT] [2, 231, 5, 1] -> Rank: 35/37 (Params: 1622)
    [Downward Pruned] 17 subsets removed from queue.
  [SHORT] [2, 2, 233, 1] -> Rank: 9/37 (Params: 703)
    [Downward Pruned] 2 subsets removed from queue.
  [SHORT] [2, 234, 5, 1] -> Rank: 35/37 (Params: 1643)
    [Downward Pruned] 2 subsets removed from queue.
  [SHORT] [2, 249, 5, 1] -> Rank: 35/37 (Params: 1748)
    [Downward Pruned] 14 subsets removed from queue.
  [SHORT] [2, 3, 286, 1] -> Rank: 30/37 (Params: 1150)
    [Downward Pruned] 108 subsets removed from queue.
  [SHORT] [2, 276, 3, 1] -> Rank: 21/37 (Params: 1383)
    [Downward Pruned] 2 subsets removed from queue.
  [SHORT] [2, 290, 3, 1] -> Rank: 21/37 (Params: 1453)
    [Downward Pruned] 13 subsets removed from queue.
  [SHORT] [2, 292, 5, 1] -> Rank: 35/37 (Params: 2049)
    [Downward Pruned] 63 subsets removed from queue.
  [SHORT] [2, 3, 292, 1] -> Rank: 30/37 (Params: 1174)
    [Downward Pruned] 11 subsets removed from queue.
  [SHORT] [2, 295, 5, 1] -> Rank: 35/37 (Params: 2070)
    [Downward Pruned] 8 subsets removed from queue.
  [SHORT] [2, 300, 2, 1] -> Rank: 14/37 (Params: 1202)
    [Downward Pruned] 3 subsets removed from queue.
  [SHORT] [2, 3, 294, 1] -> Rank: 30/37 (Params: 1182)
    [Downward Pruned] 3 subsets removed from queue.
  [SHORT] [2, 297, 3, 1] -> Rank: 21/37 (Params: 1488)
    [Downward Pruned] 1 subsets removed from queue.
  [SHORT] [2, 3, 295, 1] -> Rank: 30/37 (Params: 1186)
    [Downward Pruned] 1 subsets removed from queue.
  [SHORT] [2, 300, 5, 1] -> Rank: 35/37 (Params: 2105)
    [Downward Pruned] 12 subsets removed from queue.
  [SHORT] [2, 2, 296, 1] -> Rank: 9/37 (Params: 892)
  [SHORT] [2, 2, 300, 1] -> Rank: 9/37 (Params: 904)
    [Downward Pruned] 3 subsets removed from queue.
  [SHORT] [2, 3, 297, 1] -> Rank: 30/37 (Params: 1194)
    [Downward Pruned] 1 subsets removed from queue.
  [SHORT] [2, 3, 299, 1] -> Rank: 30/37 (Params: 1202)
    [Downward Pruned] 1 subsets removed from queue.
  [SHORT] [2, 3, 300, 1] -> Rank: 30/37 (Params: 1206)

Added 30 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/2_1_r6_architectures.csv'.

Loading existing database from '../data/raw/2_1_r7_architectures.csv'...

--- RANDOM SEARCH: h=2, exponent=7 ---
  Target Ambient Dimension: 8
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 1 impossible/redundant architectures.
  Starting sequential evaluation on 298 viable candidates.
  [FULL ] [2, 28, 1] -> Rank: 8/8 (Params: 84)
    [Upward Pruned] 272 supersets removed from queue.
  [FULL ] [2, 21, 1] -> Rank: 8/8 (Params: 63)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [2, 16, 1] -> Rank: 8/8 (Params: 48)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [2, 4, 1] -> Rank: 8/8 (Params: 12)
    [Upward Pruned] 11 supersets removed from queue.
  [SHORT] [2, 3, 1] -> Rank: 6/8 (Params: 9)

--- RANDOM SEARCH: h=3, exponent=7 ---
  Target Ambient Dimension: 50
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 48 impossible/redundant architectures.
  Starting sequential evaluation on 89353 viable candidates.
  [FULL ] [2, 119, 140, 1] -> Rank: 50/50 (Params: 17038)
    [Upward Pruned] 29301 supersets removed from queue.
  [FULL ] [2, 18, 251, 1] -> Rank: 50/50 (Params: 4805)
    [Upward Pruned] 5049 supersets removed from queue.
  [FULL ] [2, 173, 25, 1] -> Rank: 50/50 (Params: 4696)
    [Upward Pruned] 14719 supersets removed from queue.
  [FULL ] [2, 88, 46, 1] -> Rank: 50/50 (Params: 4270)
    [Upward Pruned] 11430 supersets removed from queue.
  [FULL ] [2, 22, 200, 1] -> Rank: 50/50 (Params: 4644)
    [Upward Pruned] 3365 supersets removed from queue.
  [FULL ] [2, 6, 198, 1] -> Rank: 50/50 (Params: 1398)
    [Upward Pruned] 1579 supersets removed from queue.
  [FULL ] [2, 65, 73, 1] -> Rank: 50/50 (Params: 4948)
    [Upward Pruned] 2874 supersets removed from queue.
  [FULL ] [2, 127, 8, 1] -> Rank: 50/50 (Params: 1278)
    [Upward Pruned] 3923 supersets removed from queue.
  [SHORT] [2, 259, 3, 1] -> Rank: 24/50 (Params: 1298)
    [Downward Pruned] 497 subsets removed from queue.
  [FULL ] [2, 147, 7, 1] -> Rank: 50/50 (Params: 1330)
    [Upward Pruned] 153 supersets removed from queue.
  [FULL ] [2, 81, 52, 1] -> Rank: 50/50 (Params: 4426)
    [Upward Pruned] 146 supersets removed from queue.
  [FULL ] [2, 106, 27, 1] -> Rank: 50/50 (Params: 3101)
    [Upward Pruned] 398 supersets removed from queue.
  [FULL ] [2, 100, 28, 1] -> Rank: 50/50 (Params: 3028)
    [Upward Pruned] 107 supersets removed from queue.
  [FULL ] [2, 50, 15, 1] -> Rank: 50/50 (Params: 865)
    [Upward Pruned] 4633 supersets removed from queue.
  [SHORT] [2, 41, 5, 1] -> Rank: 40/50 (Params: 292)
    [Downward Pruned] 68 subsets removed from queue.
  [FULL ] [2, 34, 175, 1] -> Rank: 50/50 (Params: 6193)
    [Upward Pruned] 367 supersets removed from queue.
  [FULL ] [2, 40, 87, 1] -> Rank: 50/50 (Params: 3647)
    [Upward Pruned] 879 supersets removed from queue.
  [FULL ] [2, 45, 65, 1] -> Rank: 50/50 (Params: 3080)
    [Upward Pruned] 109 supersets removed from queue.
  [FULL ] [2, 67, 12, 1] -> Rank: 50/50 (Params: 950)
    [Upward Pruned] 179 supersets removed from queue.
  [FULL ] [2, 45, 20, 1] -> Rank: 50/50 (Params: 1010)
    [Upward Pruned] 224 supersets removed from queue.
  [FULL ] [2, 31, 143, 1] -> Rank: 50/50 (Params: 4638)
    [Upward Pruned] 356 supersets removed from queue.
  [FULL ] [2, 58, 11, 1] -> Rank: 50/50 (Params: 765)
    [Upward Pruned] 95 supersets removed from queue.
  [SHORT] [2, 242, 4, 1] -> Rank: 32/50 (Params: 1456)
    [Downward Pruned] 200 subsets removed from queue.
  [FULL ] [2, 4, 186, 1] -> Rank: 50/50 (Params: 938)
    [Upward Pruned] 529 supersets removed from queue.
  [FULL ] [2, 16, 102, 1] -> Rank: 50/50 (Params: 1766)
    [Upward Pruned] 1628 supersets removed from queue.
  [FULL ] [2, 14, 62, 1] -> Rank: 50/50 (Params: 958)
    [Upward Pruned] 1332 supersets removed from queue.
  [FULL ] [2, 44, 8, 1] -> Rank: 50/50 (Params: 448)
    [Upward Pruned] 376 supersets removed from queue.
  [FULL ] [2, 10, 93, 1] -> Rank: 50/50 (Params: 1043)
    [Upward Pruned] 371 supersets removed from queue.
  [FULL ] [2, 15, 16, 1] -> Rank: 50/50 (Params: 286)
    [Upward Pruned] 1333 supersets removed from queue.
  [FULL ] [2, 8, 29, 1] -> Rank: 50/50 (Params: 277)
    [Upward Pruned] 602 supersets removed from queue.
  [SHORT] [2, 90, 5, 1] -> Rank: 40/50 (Params: 635)
    [Downward Pruned] 48 subsets removed from queue.
  [SHORT] [2, 2, 160, 1] -> Rank: 10/50 (Params: 484)
    [Downward Pruned] 144 subsets removed from queue.
  [SHORT] [2, 164, 6, 1] -> Rank: 48/50 (Params: 1318)
    [Downward Pruned] 232 subsets removed from queue.
  [FULL ] [2, 4, 39, 1] -> Rank: 50/50 (Params: 203)
    [Upward Pruned] 587 supersets removed from queue.
  [SHORT] [2, 3, 261, 1] -> Rank: 38/50 (Params: 1050)
    [Downward Pruned] 351 subsets removed from queue.
  [SHORT] [2, 233, 6, 1] -> Rank: 48/50 (Params: 1870)
    [Downward Pruned] 137 subsets removed from queue.
  [FULL ] [2, 39, 8, 1] -> Rank: 50/50 (Params: 398)
    [Upward Pruned] 39 supersets removed from queue.
  [FULL ] [2, 86, 7, 1] -> Rank: 50/50 (Params: 781)
    [Upward Pruned] 60 supersets removed from queue.
  [SHORT] [2, 264, 3, 1] -> Rank: 24/50 (Params: 1323)
    [Downward Pruned] 9 subsets removed from queue.
  [SHORT] [2, 3, 263, 1] -> Rank: 38/50 (Params: 1058)
    [Downward Pruned] 3 subsets removed from queue.
  [SHORT] [2, 2, 276, 1] -> Rank: 10/50 (Params: 832)
    [Downward Pruned] 12 subsets removed from queue.
  [FULL ] [2, 13, 28, 1] -> Rank: 50/50 (Params: 418)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [2, 6, 10, 1] -> Rank: 50/50 (Params: 82)
    [Upward Pruned] 332 supersets removed from queue.
  [FULL ] [2, 20, 9, 1] -> Rank: 50/50 (Params: 229)
    [Upward Pruned] 18 supersets removed from queue.
  [FULL ] [2, 26, 8, 1] -> Rank: 50/50 (Params: 268)
    [Upward Pruned] 12 supersets removed from queue.
  [SHORT] [2, 300, 3, 1] -> Rank: 24/50 (Params: 1503)
    [Downward Pruned] 71 subsets removed from queue.
  [FULL ] [2, 15, 7, 1] -> Rank: 50/50 (Params: 142)
    [Upward Pruned] 86 supersets removed from queue.
  [FULL ] [2, 4, 14, 1] -> Rank: 50/50 (Params: 78)
    [Upward Pruned] 49 supersets removed from queue.
  [SHORT] [2, 263, 5, 1] -> Rank: 40/50 (Params: 1846)
    [Downward Pruned] 50 subsets removed from queue.
  [SHORT] [2, 267, 6, 1] -> Rank: 48/50 (Params: 2142)
    [Downward Pruned] 41 subsets removed from queue.
  [SHORT] [2, 3, 271, 1] -> Rank: 38/50 (Params: 1090)
    [Downward Pruned] 7 subsets removed from queue.
  [SHORT] [2, 299, 4, 1] -> Rank: 32/50 (Params: 1798)
    [Downward Pruned] 31 subsets removed from queue.
  [SHORT] [2, 2, 297, 1] -> Rank: 10/50 (Params: 895)
    [Downward Pruned] 20 subsets removed from queue.
  [SHORT] [2, 272, 5, 1] -> Rank: 40/50 (Params: 1909)
    [Downward Pruned] 4 subsets removed from queue.
  [SHORT] [2, 3, 287, 1] -> Rank: 38/50 (Params: 1154)
    [Downward Pruned] 15 subsets removed from queue.
  [SHORT] [2, 293, 5, 1] -> Rank: 40/50 (Params: 2056)
    [Downward Pruned] 20 subsets removed from queue.
  [SHORT] [2, 3, 288, 1] -> Rank: 38/50 (Params: 1158)
  [SHORT] [2, 288, 6, 1] -> Rank: 48/50 (Params: 2310)
    [Downward Pruned] 20 subsets removed from queue.
  [SHORT] [2, 3, 299, 1] -> Rank: 38/50 (Params: 1202)
    [Downward Pruned] 12 subsets removed from queue.
  [FULL ] [2, 8, 8, 1] -> Rank: 50/50 (Params: 88)
    [Upward Pruned] 13 supersets removed from queue.
  [SHORT] [2, 300, 5, 1] -> Rank: 40/50 (Params: 2105)
    [Downward Pruned] 7 subsets removed from queue.
  [SHORT] [2, 293, 6, 1] -> Rank: 48/50 (Params: 2350)
    [Downward Pruned] 4 subsets removed from queue.
  [SHORT] [2, 296, 6, 1] -> Rank: 48/50 (Params: 2374)
    [Downward Pruned] 2 subsets removed from queue.
  [SHORT] [2, 6, 7, 1] -> Rank: 48/50 (Params: 61)
    [Downward Pruned] 1 subsets removed from queue.
  [FULL ] [2, 5, 11, 1] -> Rank: 50/50 (Params: 76)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [2, 12, 7, 1] -> Rank: 50/50 (Params: 115)
    [Upward Pruned] 2 supersets removed from queue.
  [SHORT] [2, 297, 6, 1] -> Rank: 48/50 (Params: 2382)
  [FULL ] [2, 9, 7, 1] -> Rank: 50/50 (Params: 88)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [2, 6, 9, 1] -> Rank: 50/50 (Params: 75)
    [Upward Pruned] 1 supersets removed from queue.
  [SHORT] [2, 5, 8, 1] -> Rank: 45/50 (Params: 58)
  [SHORT] [2, 4, 10, 1] -> Rank: 44/50 (Params: 58)
    [Downward Pruned] 1 subsets removed from queue.
  [FULL ] [2, 6, 8, 1] -> Rank: 50/50 (Params: 68)
    [Upward Pruned] 1 supersets removed from queue.
  [SHORT] [2, 300, 6, 1] -> Rank: 48/50 (Params: 2406)
    [Downward Pruned] 2 subsets removed from queue.
  [SHORT] [2, 2, 300, 1] -> Rank: 10/50 (Params: 904)
  [SHORT] [2, 3, 300, 1] -> Rank: 38/50 (Params: 1206)
  [SHORT] [2, 4, 11, 1] -> Rank: 48/50 (Params: 63)
  [FULL ] [2, 5, 10, 1] -> Rank: 50/50 (Params: 70)
  [FULL ] [2, 4, 12, 1] -> Rank: 50/50 (Params: 68)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [2, 7, 7, 1] -> Rank: 50/50 (Params: 70)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [2, 5, 9, 1] -> Rank: 50/50 (Params: 64)

Added 85 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/2_1_r7_architectures.csv'.

Loading existing database from '../data/raw/2_1_r8_architectures.csv'...

--- RANDOM SEARCH: h=2, exponent=8 ---
  Target Ambient Dimension: 9
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 1 impossible/redundant architectures.
  Starting sequential evaluation on 298 viable candidates.
  [FULL ] [2, 209, 1] -> Rank: 9/9 (Params: 627)
    [Upward Pruned] 91 supersets removed from queue.
  [FULL ] [2, 39, 1] -> Rank: 9/9 (Params: 117)
    [Upward Pruned] 169 supersets removed from queue.
  [FULL ] [2, 38, 1] -> Rank: 9/9 (Params: 114)
  [FULL ] [2, 22, 1] -> Rank: 9/9 (Params: 66)
    [Upward Pruned] 15 supersets removed from queue.
  [SHORT] [2, 4, 1] -> Rank: 8/9 (Params: 12)
    [Downward Pruned] 1 subsets removed from queue.
  [FULL ] [2, 20, 1] -> Rank: 9/9 (Params: 60)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [2, 9, 1] -> Rank: 9/9 (Params: 27)
    [Upward Pruned] 10 supersets removed from queue.
  [FULL ] [2, 8, 1] -> Rank: 9/9 (Params: 24)
  [FULL ] [2, 6, 1] -> Rank: 9/9 (Params: 18)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [2, 5, 1] -> Rank: 9/9 (Params: 15)

--- RANDOM SEARCH: h=3, exponent=8 ---
  Target Ambient Dimension: 65
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 87176 impossible/redundant architectures.
  Starting sequential evaluation on 2184 viable candidates.
  [SHORT] [2, 3, 176, 1] -> Rank: 47/65 (Params: 710)
    [Downward Pruned] 297 subsets removed from queue.
  [SHORT] [2, 3, 198, 1] -> Rank: 47/65 (Params: 798)
    [Downward Pruned] 43 subsets removed from queue.
  [SHORT] [2, 220, 4, 1] -> Rank: 36/65 (Params: 1324)
    [Downward Pruned] 578 subsets removed from queue.
  [SHORT] [2, 2, 264, 1] -> Rank: 11/65 (Params: 796)
    [Downward Pruned] 65 subsets removed from queue.
  [SHORT] [2, 159, 6, 1] -> Rank: 54/65 (Params: 1278)
    [Downward Pruned] 263 subsets removed from queue.
  [SHORT] [2, 197, 5, 1] -> Rank: 45/65 (Params: 1384)
    [Downward Pruned] 37 subsets removed from queue.
  [SHORT] [2, 251, 5, 1] -> Rank: 45/65 (Params: 1762)
    [Downward Pruned] 146 subsets removed from queue.
  [SHORT] [2, 121, 7, 1] -> Rank: 63/65 (Params: 1096)
    [Downward Pruned] 93 subsets removed from queue.
  [SHORT] [2, 2, 282, 1] -> Rank: 11/65 (Params: 850)
    [Downward Pruned] 17 subsets removed from queue.
  [SHORT] [2, 249, 6, 1] -> Rank: 54/65 (Params: 1998)
    [Downward Pruned] 89 subsets removed from queue.
  [SHORT] [2, 255, 4, 1] -> Rank: 36/65 (Params: 1534)
    [Downward Pruned] 11 subsets removed from queue.
  [SHORT] [2, 185, 7, 1] -> Rank: 63/65 (Params: 1672)
    [Downward Pruned] 63 subsets removed from queue.
  [SHORT] [2, 258, 6, 1] -> Rank: 54/65 (Params: 2070)
    [Downward Pruned] 24 subsets removed from queue.
  [SHORT] [2, 2, 300, 1] -> Rank: 11/65 (Params: 904)
    [Downward Pruned] 17 subsets removed from queue.
  [SHORT] [2, 268, 5, 1] -> Rank: 45/65 (Params: 1881)
    [Downward Pruned] 39 subsets removed from queue.
  [SHORT] [2, 254, 7, 1] -> Rank: 63/65 (Params: 2293)
    [Downward Pruned] 68 subsets removed from queue.
  [SHORT] [2, 3, 250, 1] -> Rank: 47/65 (Params: 1006)
    [Downward Pruned] 51 subsets removed from queue.
  [SHORT] [2, 284, 6, 1] -> Rank: 54/65 (Params: 2278)
    [Downward Pruned] 89 subsets removed from queue.
  [SHORT] [2, 286, 5, 1] -> Rank: 45/65 (Params: 2007)
    [Downward Pruned] 7 subsets removed from queue.
  [SHORT] [2, 266, 7, 1] -> Rank: 63/65 (Params: 2401)
    [Downward Pruned] 11 subsets removed from queue.
  [SHORT] [2, 3, 265, 1] -> Rank: 47/65 (Params: 1066)
    [Downward Pruned] 14 subsets removed from queue.
  [SHORT] [2, 296, 6, 1] -> Rank: 54/65 (Params: 2374)
    [Downward Pruned] 51 subsets removed from queue.
  [SHORT] [2, 297, 5, 1] -> Rank: 45/65 (Params: 2084)
    [Downward Pruned] 3 subsets removed from queue.
  [SHORT] [2, 3, 284, 1] -> Rank: 47/65 (Params: 1142)
    [Downward Pruned] 18 subsets removed from queue.
  [SHORT] [2, 3, 295, 1] -> Rank: 47/65 (Params: 1186)
    [Downward Pruned] 10 subsets removed from queue.
  [SHORT] [2, 290, 7, 1] -> Rank: 63/65 (Params: 2617)
    [Downward Pruned] 23 subsets removed from queue.
  [SHORT] [2, 3, 300, 1] -> Rank: 47/65 (Params: 1206)
    [Downward Pruned] 4 subsets removed from queue.
  [SHORT] [2, 298, 7, 1] -> Rank: 63/65 (Params: 2689)
    [Downward Pruned] 13 subsets removed from queue.
  [SHORT] [2, 300, 2, 1] -> Rank: 18/65 (Params: 1202)
    [Downward Pruned] 1 subsets removed from queue.
  [SHORT] [2, 300, 4, 1] -> Rank: 36/65 (Params: 1804)
    [Downward Pruned] 3 subsets removed from queue.
  [SHORT] [2, 299, 5, 1] -> Rank: 45/65 (Params: 2098)
  [SHORT] [2, 300, 6, 1] -> Rank: 54/65 (Params: 2406)
    [Downward Pruned] 2 subsets removed from queue.
  [SHORT] [2, 299, 7, 1] -> Rank: 63/65 (Params: 2698)
  [SHORT] [2, 300, 7, 1] -> Rank: 63/65 (Params: 2707)

Added 44 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/2_1_r8_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=9 ---
  Target Ambient Dimension: 10
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 2 impossible/redundant architectures.
  Starting sequential evaluation on 297 viable candidates.
  [FULL ] [2, 94, 1] -> Rank: 10/10 (Params: 282)
    [Upward Pruned] 206 supersets removed from queue.
  [FULL ] [2, 85, 1] -> Rank: 10/10 (Params: 255)
    [Upward Pruned] 8 supersets removed from queue.
  [FULL ] [2, 77, 1] -> Rank: 10/10 (Params: 231)
    [Upward Pruned] 7 supersets removed from queue.

  [FULL ] [2, 6, 1] -> Rank: 10/10 (Params: 18)
    [Upward Pruned] 70 supersets removed from queue.
  [FULL ] [2, 5, 1] -> Rank: 10/10 (Params: 15)
  [SHORT] [2, 4, 1] -> Rank: 8/10 (Params: 12)

--- RANDOM SEARCH: h=3, exponent=9 ---
  Target Ambient Dimension: 82
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 110 impossible/redundant architectures.
  Starting sequential evaluation on 89291 viable candidates.
  [FULL ] [2, 62, 123, 1] -> Rank: 82/82 (Params: 7873)
    [Upward Pruned] 42541 supersets removed from queue.
  [FULL ] [2, 23, 185, 1] -> Rank: 82/82 (Params: 4486)
    [Upward Pruned] 4523 supersets removed from queue.
  [FULL ] [2, 282, 91, 1] -> Rank: 82/82 (Params: 26317)
    [Upward Pruned] 607 supersets removed from queue.
  [FULL ] [2, 20, 253, 1] -> Rank: 82/82 (Params: 5353)
    [Upward Pruned] 143 supersets removed from queue.
  [FULL ] [2, 44, 115, 1] -> Rank: 82/82 (Params: 5263)
    [Upward Pruned] 3019 supersets removed from queue.
  [FULL ] [2, 77, 55, 1] -> Rank: 82/82 (Params: 4444)
    [Upward Pruned] 12983 supersets removed from queue.
  [FULL ] [2, 9, 200, 1] -> Rank: 82/82 (Params: 2018)
    [Upward Pruned] 1269 supersets removed from queue.
  [FULL ] [2, 156, 27, 1] -> Rank: 82/82 (Params: 4551)
    [Upward Pruned] 4059 supersets removed from queue.
  [FULL ] [2, 29, 55, 1] -> Rank: 82/82 (Params: 1708)
    [Upward Pruned] 3929 supersets removed from queue.
  [FULL ] [2, 71, 42, 1] -> Rank: 82/82 (Params: 3166)
    [Upward Pruned] 1104 supersets removed from queue.
  [FULL ] [2, 146, 34, 1] -> Rank: 82/82 (Params: 5290)
    [Upward Pruned] 79 supersets removed from queue.
  [FULL ] [2, 55, 36, 1] -> Rank: 82/82 (Params: 2126)
    [Upward Pruned] 753 supersets removed from queue.
  [FULL ] [2, 280, 16, 1] -> Rank: 82/82 (Params: 5056)
    [Upward Pruned] 230 supersets removed from queue.
  [FULL ] [2, 192, 16, 1] -> Rank: 82/82 (Params: 3472)
    [Upward Pruned] 967 supersets removed from queue.
  [SHORT] [2, 3, 172, 1] -> Rank: 57/82 (Params: 694)
    [Downward Pruned] 300 subsets removed from queue.
  [FULL ] [2, 18, 150, 1] -> Rank: 82/82 (Params: 2886)
    [Upward Pruned] 459 supersets removed from queue.
  [SHORT] [2, 237, 4, 1] -> Rank: 40/82 (Params: 1426)
    [Downward Pruned] 664 subsets removed from queue.
  [FULL ] [2, 130, 31, 1] -> Rank: 82/82 (Params: 4321)
    [Upward Pruned] 109 supersets removed from queue.
  [FULL ] [2, 10, 186, 1] -> Rank: 82/82 (Params: 2066)
    [Upward Pruned] 111 supersets removed from queue.
  [FULL ] [2, 15, 31, 1] -> Rank: 82/82 (Params: 526)
    [Upward Pruned] 2772 supersets removed from queue.
  [FULL ] [2, 113, 20, 1] -> Rank: 82/82 (Params: 2506)
    [Upward Pruned] 724 supersets removed from queue.
  [SHORT] [2, 84, 7, 1] -> Rank: 70/82 (Params: 763)
    [Downward Pruned] 224 subsets removed from queue.
  [FULL ] [2, 4, 252, 1] -> Rank: 82/82 (Params: 1268)
    [Upward Pruned] 244 supersets removed from queue.
  [FULL ] [2, 6, 248, 1] -> Rank: 82/82 (Params: 1748)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [2, 9, 32, 1] -> Rank: 82/82 (Params: 338)
    [Upward Pruned] 937 supersets removed from queue.
  [FULL ] [2, 43, 18, 1] -> Rank: 82/82 (Params: 878)
    [Upward Pruned] 1067 supersets removed from queue.
  [FULL ] [2, 151, 12, 1] -> Rank: 82/82 (Params: 2126)
    [Upward Pruned] 681 supersets removed from queue.
  [FULL ] [2, 22, 20, 1] -> Rank: 82/82 (Params: 504)
    [Upward Pruned] 230 supersets removed from queue.
  [SHORT] [2, 270, 6, 1] -> Rank: 60/82 (Params: 2166)
    [Downward Pruned] 470 subsets removed from queue.
  [FULL ] [2, 9, 14, 1] -> Rank: 82/82 (Params: 158)
    [Upward Pruned] 784 supersets removed from queue.
  [FULL ] [2, 73, 12, 1] -> Rank: 82/82 (Params: 1034)
    [Upward Pruned] 155 supersets removed from queue.
  [FULL ] [2, 155, 10, 1] -> Rank: 82/82 (Params: 1870)
    [Upward Pruned] 291 supersets removed from queue.
  [FULL ] [2, 8, 229, 1] -> Rank: 82/82 (Params: 2077)
    [Upward Pruned] 18 supersets removed from queue.
  [SHORT] [2, 136, 7, 1] -> Rank: 70/82 (Params: 1231)
    [Downward Pruned] 51 subsets removed from queue.
  [FULL ] [2, 7, 224, 1] -> Rank: 82/82 (Params: 1806)
    [Upward Pruned] 28 supersets removed from queue.
  [FULL ] [2, 7, 25, 1] -> Rank: 82/82 (Params: 214)
    [Upward Pruned] 397 supersets removed from queue.
  [FULL ] [2, 4, 218, 1] -> Rank: 82/82 (Params: 1098)
    [Upward Pruned] 97 supersets removed from queue.
  [SHORT] [2, 295, 3, 1] -> Rank: 30/82 (Params: 1478)
    [Downward Pruned] 49 subsets removed from queue.
  [FULL ] [2, 49, 11, 1] -> Rank: 82/82 (Params: 648)
    [Upward Pruned] 153 supersets removed from queue.
  [SHORT] [2, 201, 7, 1] -> Rank: 70/82 (Params: 1816)
    [Downward Pruned] 64 subsets removed from queue.
  [SHORT] [2, 3, 285, 1] -> Rank: 57/82 (Params: 1146)
    [Downward Pruned] 225 subsets removed from queue.
  [FULL ] [2, 110, 10, 1] -> Rank: 82/82 (Params: 1330)
    [Upward Pruned] 44 supersets removed from queue.
  [SHORT] [2, 3, 292, 1] -> Rank: 57/82 (Params: 1174)
    [Downward Pruned] 13 subsets removed from queue.
  [FULL ] [2, 16, 10, 1] -> Rank: 82/82 (Params: 202)
    [Upward Pruned] 192 supersets removed from queue.
  [FULL ] [2, 282, 9, 1] -> Rank: 82/82 (Params: 3111)
    [Upward Pruned] 18 supersets removed from queue.
  [FULL ] [2, 5, 211, 1] -> Rank: 82/82 (Params: 1276)
    [Upward Pruned] 13 supersets removed from queue.
  [FULL ] [2, 45, 9, 1] -> Rank: 82/82 (Params: 504)
    [Upward Pruned] 236 supersets removed from queue.
  [SHORT] [2, 276, 7, 1] -> Rank: 70/82 (Params: 2491)
    [Downward Pruned] 92 subsets removed from queue.
  [FULL ] [2, 4, 201, 1] -> Rank: 82/82 (Params: 1013)
    [Upward Pruned] 36 supersets removed from queue.
  [SHORT] [2, 2, 293, 1] -> Rank: 12/82 (Params: 883)
  [FULL ] [2, 7, 19, 1] -> Rank: 82/82 (Params: 166)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [2, 5, 93, 1] -> Rank: 82/82 (Params: 568)
    [Upward Pruned] 215 supersets removed from queue.
  [FULL ] [2, 4, 96, 1] -> Rank: 82/82 (Params: 488)
    [Upward Pruned] 104 supersets removed from queue.
  [SHORT] [2, 292, 5, 1] -> Rank: 50/82 (Params: 2049)
    [Downward Pruned] 31 subsets removed from queue.
  [SHORT] [2, 179, 8, 1] -> Rank: 80/82 (Params: 1798)
    [Downward Pruned] 171 subsets removed from queue.
  [FULL ] [2, 22, 9, 1] -> Rank: 82/82 (Params: 251)
    [Upward Pruned] 22 supersets removed from queue.
  [SHORT] [2, 182, 8, 1] -> Rank: 80/82 (Params: 1828)
    [Downward Pruned] 2 subsets removed from queue.
  [SHORT] [2, 248, 8, 1] -> Rank: 80/82 (Params: 2488)
    [Downward Pruned] 65 subsets removed from queue.
  [FULL ] [2, 4, 42, 1] -> Rank: 82/82 (Params: 218)
    [Upward Pruned] 155 supersets removed from queue.
  [FULL ] [2, 6, 28, 1] -> Rank: 82/82 (Params: 208)
    [Upward Pruned] 13 supersets removed from queue.
  [SHORT] [2, 295, 4, 1] -> Rank: 40/82 (Params: 1774)
    [Downward Pruned] 2 subsets removed from queue.
  [SHORT] [2, 290, 7, 1] -> Rank: 70/82 (Params: 2617)
    [Downward Pruned] 27 subsets removed from queue.
  [FULL ] [2, 4, 31, 1] -> Rank: 82/82 (Params: 163)
    [Upward Pruned] 21 supersets removed from queue.
  [FULL ] [2, 7, 15, 1] -> Rank: 82/82 (Params: 134)
    [Upward Pruned] 7 supersets removed from queue.
  [SHORT] [2, 294, 6, 1] -> Rank: 60/82 (Params: 2358)
    [Downward Pruned] 5 subsets removed from queue.
  [SHORT] [2, 266, 8, 1] -> Rank: 80/82 (Params: 2668)
    [Downward Pruned] 17 subsets removed from queue.
  [SHORT] [2, 3, 297, 1] -> Rank: 57/82 (Params: 1194)
    [Downward Pruned] 8 subsets removed from queue.
  [FULL ] [2, 7, 11, 1] -> Rank: 82/82 (Params: 102)
    [Upward Pruned] 28 supersets removed from queue.
  [FULL ] [2, 6, 16, 1] -> Rank: 82/82 (Params: 124)
    [Upward Pruned] 11 supersets removed from queue.
  [SHORT] [2, 294, 8, 1] -> Rank: 80/82 (Params: 2948)
    [Downward Pruned] 31 subsets removed from queue.
  [FULL ] [2, 5, 25, 1] -> Rank: 82/82 (Params: 160)
    [Upward Pruned] 5 supersets removed from queue.
  [SHORT] [2, 299, 8, 1] -> Rank: 80/82 (Params: 2998)
    [Downward Pruned] 31 subsets removed from queue.
  [SHORT] [2, 300, 4, 1] -> Rank: 40/82 (Params: 1804)
    [Downward Pruned] 2 subsets removed from queue.
  [FULL ] [2, 6, 14, 1] -> Rank: 82/82 (Params: 110)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [2, 15, 10, 1] -> Rank: 82/82 (Params: 190)
  [FULL ] [2, 5, 17, 1] -> Rank: 82/82 (Params: 112)
    [Upward Pruned] 7 supersets removed from queue.
  [SHORT] [2, 7, 10, 1] -> Rank: 77/82 (Params: 94)
    [Downward Pruned] 2 subsets removed from queue.
  [FULL ] [2, 8, 10, 1] -> Rank: 82/82 (Params: 106)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [2, 14, 9, 1] -> Rank: 82/82 (Params: 163)
    [Upward Pruned] 7 supersets removed from queue.
  [SHORT] [2, 300, 5, 1] -> Rank: 50/82 (Params: 2105)
  [SHORT] [2, 4, 19, 1] -> Rank: 80/82 (Params: 103)
    [Downward Pruned] 4 subsets removed from queue.
  [FULL ] [2, 4, 24, 1] -> Rank: 82/82 (Params: 128)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [2, 4, 21, 1] -> Rank: 82/82 (Params: 113)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [2, 6, 13, 1] -> Rank: 82/82 (Params: 103)
  [SHORT] [2, 3, 299, 1] -> Rank: 57/82 (Params: 1202)
    [Downward Pruned] 3 subsets removed from queue.
  [SHORT] [2, 6, 11, 1] -> Rank: 72/82 (Params: 89)
  [SHORT] [2, 5, 12, 1] -> Rank: 65/82 (Params: 82)
  [SHORT] [2, 5, 14, 1] -> Rank: 75/82 (Params: 94)
    [Downward Pruned] 1 subsets removed from queue.
  [SHORT] [2, 8, 9, 1] -> Rank: 80/82 (Params: 97)
  [FULL ] [2, 5, 16, 1] -> Rank: 82/82 (Params: 106)
  [SHORT] [2, 300, 7, 1] -> Rank: 70/82 (Params: 2707)
    [Downward Pruned] 1 subsets removed from queue.
  [FULL ] [2, 9, 9, 1] -> Rank: 82/82 (Params: 108)
    [Upward Pruned] 4 supersets removed from queue.
  [SHORT] [2, 6, 12, 1] -> Rank: 78/82 (Params: 96)
  [SHORT] [2, 5, 15, 1] -> Rank: 80/82 (Params: 100)
  [FULL ] [2, 4, 20, 1] -> Rank: 82/82 (Params: 108)
  [SHORT] [2, 2, 300, 1] -> Rank: 12/82 (Params: 904)
  [SHORT] [2, 300, 8, 1] -> Rank: 80/82 (Params: 3008)
  [SHORT] [2, 3, 300, 1] -> Rank: 57/82 (Params: 1206)

Added 104 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/2_1_r9_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=1 ---
  Target Ambient Dimension: 4
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 299 viable candidates.
  [FULL ] [2, 184, 2] -> Rank: 4/4 (Params: 736)
    [Upward Pruned] 116 supersets removed from queue.
  [FULL ] [2, 175, 2] -> Rank: 4/4 (Params: 700)
    [Upward Pruned] 8 supersets removed from queue.
  [FULL ] [2, 125, 2] -> Rank: 4/4 (Params: 500)
    [Upward Pruned] 49 supersets removed from queue.
  [FULL ] [2, 43, 2] -> Rank: 4/4 (Params: 172)
    [Upward Pruned] 81 supersets removed from queue.
  [FULL ] [2, 20, 2] -> Rank: 4/4 (Params: 80)
    [Upward Pruned] 22 supersets removed from queue.
  [FULL ] [2, 6, 2] -> Rank: 4/4 (Params: 24)
    [Upward Pruned] 13 supersets removed from queue.
  [FULL ] [2, 4, 2] -> Rank: 4/4 (Params: 16)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [2, 2, 2] -> Rank: 4/4 (Params: 8)
    [Upward Pruned] 1 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=1 ---
  Target Ambient Dimension: 4
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 0 impossible/redundant architectures.
  Starting sequential evaluation on 89401 viable candidates.
  [FULL ] [2, 38, 140, 2] -> Rank: 4/4 (Params: 5676)
    [Upward Pruned] 42342 supersets removed from queue.
  [FULL ] [2, 42, 41, 2] -> Rank: 4/4 (Params: 1888)
    [Upward Pruned] 25640 supersets removed from queue.
  [FULL ] [2, 27, 111, 2] -> Rank: 4/4 (Params: 3273)
    [Upward Pruned] 2205 supersets removed from queue.
  [FULL ] [2, 244, 38, 2] -> Rank: 4/4 (Params: 9836)
    [Upward Pruned] 170 supersets removed from queue.
  [FULL ] [2, 207, 29, 2] -> Rank: 4/4 (Params: 6475)
    [Upward Pruned] 956 supersets removed from queue.
  [FULL ] [2, 12, 105, 2] -> Rank: 4/4 (Params: 1494)
    [Upward Pruned] 3029 supersets removed from queue.
  [FULL ] [2, 171, 7, 2] -> Rank: 4/4 (Params: 1553)
    [Upward Pruned] 3291 supersets removed from queue.
  [FULL ] [2, 6, 242, 2] -> Rank: 4/4 (Params: 1948)
    [Upward Pruned] 353 supersets removed from queue.
  [FULL ] [2, 16, 24, 2] -> Rank: 4/4 (Params: 464)
    [Upward Pruned] 4298 supersets removed from queue.
  [FULL ] [2, 7, 164, 2] -> Rank: 4/4 (Params: 1490)
    [Upward Pruned] 389 supersets removed from queue.
  [FULL ] [2, 149, 10, 2] -> Rank: 4/4 (Params: 1808)
    [Upward Pruned] 307 supersets removed from queue.
  [FULL ] [2, 109, 16, 2] -> Rank: 4/4 (Params: 1994)
    [Upward Pruned] 319 supersets removed from queue.
  [FULL ] [2, 124, 8, 2] -> Rank: 4/4 (Params: 1256)
    [Upward Pruned] 243 supersets removed from queue.
  [FULL ] [2, 14, 5, 2] -> Rank: 4/4 (Params: 108)
    [Upward Pruned] 2532 supersets removed from queue.
  [FULL ] [2, 3, 174, 2] -> Rank: 4/4 (Params: 876)
    [Upward Pruned] 448 supersets removed from queue.
  [FULL ] [2, 80, 3, 2] -> Rank: 4/4 (Params: 406)
    [Upward Pruned] 441 supersets removed from queue.
  [FULL ] [2, 6, 24, 2] -> Rank: 4/4 (Params: 204)
    [Upward Pruned] 1011 supersets removed from queue.
  [FULL ] [2, 4, 68, 2] -> Rank: 4/4 (Params: 416)
    [Upward Pruned] 211 supersets removed from queue.
  [FULL ] [2, 2, 32, 2] -> Rank: 4/4 (Params: 132)
    [Upward Pruned] 482 supersets removed from queue.
  [FULL ] [2, 201, 2, 2] -> Rank: 4/4 (Params: 808)
    [Upward Pruned] 99 supersets removed from queue.
  [FULL ] [2, 5, 13, 2] -> Rank: 4/4 (Params: 101)
    [Upward Pruned] 106 supersets removed from queue.
  [FULL ] [2, 123, 2, 2] -> Rank: 4/4 (Params: 496)
    [Upward Pruned] 77 supersets removed from queue.
  [FULL ] [2, 56, 3, 2] -> Rank: 4/4 (Params: 286)
    [Upward Pruned] 47 supersets removed from queue.
  [FULL ] [2, 111, 2, 2] -> Rank: 4/4 (Params: 448)
    [Upward Pruned] 11 supersets removed from queue.
  [FULL ] [2, 42, 2, 2] -> Rank: 4/4 (Params: 172)
    [Upward Pruned] 96 supersets removed from queue.
  [FULL ] [2, 39, 4, 2] -> Rank: 4/4 (Params: 242)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [2, 2, 8, 2] -> Rank: 4/4 (Params: 36)
    [Upward Pruned] 116 supersets removed from queue.
  [FULL ] [2, 24, 3, 2] -> Rank: 4/4 (Params: 126)
    [Upward Pruned] 32 supersets removed from queue.
  [FULL ] [2, 24, 2, 2] -> Rank: 4/4 (Params: 100)
    [Upward Pruned] 17 supersets removed from queue.
  [FULL ] [2, 8, 5, 2] -> Rank: 4/4 (Params: 66)
    [Upward Pruned] 17 supersets removed from queue.
  [FULL ] [2, 15, 3, 2] -> Rank: 4/4 (Params: 81)
    [Upward Pruned] 17 supersets removed from queue.
  [FULL ] [2, 22, 2, 2] -> Rank: 4/4 (Params: 92)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [2, 7, 6, 2] -> Rank: 4/4 (Params: 68)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [2, 2, 6, 2] -> Rank: 4/4 (Params: 28)
    [Upward Pruned] 9 supersets removed from queue.
  [FULL ] [2, 5, 2, 2] -> Rank: 4/4 (Params: 24)
    [Upward Pruned] 39 supersets removed from queue.
  [FULL ] [2, 4, 4, 2] -> Rank: 4/4 (Params: 32)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [2, 2, 5, 2] -> Rank: 4/4 (Params: 24)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [2, 2, 3, 2] -> Rank: 4/4 (Params: 16)
    [Upward Pruned] 4 supersets removed from queue.
  [FULL ] [2, 3, 2, 2] -> Rank: 4/4 (Params: 16)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [2, 2, 2, 2] -> Rank: 4/4 (Params: 12)

Added 48 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/2_2_r1_architectures.csv'.

Loading existing database from '../data/raw/2_2_r2_architectures.csv'...

--- RANDOM SEARCH: h=2, exponent=2 ---
  Target Ambient Dimension: 6
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 297 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.

--- RANDOM SEARCH: h=3, exponent=2 ---
  Target Ambient Dimension: 10
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 88858 impossible/redundant architectures.
  Starting sequential evaluation on 500 viable candidates.
  [SHORT] [2, 2, 294, 2] -> Rank: 8/10 (Params: 1180)
    [Downward Pruned] 243 subsets removed from queue.
  [SHORT] [2, 292, 2, 2] -> Rank: 8/10 (Params: 1172)
    [Downward Pruned] 241 subsets removed from queue.
  [SHORT] [2, 295, 2, 2] -> Rank: 8/10 (Params: 1184)
    [Downward Pruned] 2 subsets removed from queue.
  [SHORT] [2, 2, 295, 2] -> Rank: 8/10 (Params: 1184)
  [SHORT] [2, 2, 298, 2] -> Rank: 8/10 (Params: 1196)
    [Downward Pruned] 2 subsets removed from queue.
  [SHORT] [2, 296, 2, 2] -> Rank: 8/10 (Params: 1188)
  [SHORT] [2, 2, 300, 2] -> Rank: 8/10 (Params: 1204)
    [Downward Pruned] 1 subsets removed from queue.
  [SHORT] [2, 299, 2, 2] -> Rank: 8/10 (Params: 1200)
    [Downward Pruned] 2 subsets removed from queue.
  [SHORT] [2, 300, 2, 2] -> Rank: 8/10 (Params: 1204)

Added 9 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/2_2_r2_architectures.csv'.

Loading existing database from '../data/raw/2_2_r3_architectures.csv'...

--- RANDOM SEARCH: h=2, exponent=3 ---
  Target Ambient Dimension: 8
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 292 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.

--- RANDOM SEARCH: h=3, exponent=3 ---
  Target Ambient Dimension: 20
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 89354 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/2_2_r3_architectures.csv'.

Loading existing database from '../data/raw/2_2_r4_architectures.csv'...

--- RANDOM SEARCH: h=2, exponent=4 ---
  Target Ambient Dimension: 10
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 293 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.

--- RANDOM SEARCH: h=3, exponent=4 ---
  Target Ambient Dimension: 34
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 89350 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/2_2_r4_architectures.csv'.

Loading existing database from '../data/raw/2_2_r5_architectures.csv'...

--- RANDOM SEARCH: h=2, exponent=5 ---
  Target Ambient Dimension: 12
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 289 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.

--- RANDOM SEARCH: h=3, exponent=5 ---
  Target Ambient Dimension: 52
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 89326 impossible/redundant architectures.
  Starting sequential evaluation on 0 viable candidates.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/2_2_r5_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=6 ---
  Target Ambient Dimension: 14
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 2 impossible/redundant architectures.
  Starting sequential evaluation on 297 viable candidates.
  [FULL ] [2, 124, 2] -> Rank: 14/14 (Params: 496)
    [Upward Pruned] 176 supersets removed from queue.
  [FULL ] [2, 46, 2] -> Rank: 14/14 (Params: 184)
    [Upward Pruned] 77 supersets removed from queue.
  [FULL ] [2, 8, 2] -> Rank: 14/14 (Params: 32)
    [Upward Pruned] 37 supersets removed from queue.
  [SHORT] [2, 4, 2] -> Rank: 12/14 (Params: 16)
  [FULL ] [2, 7, 2] -> Rank: 14/14 (Params: 28)
  [FULL ] [2, 5, 2] -> Rank: 14/14 (Params: 20)
    [Upward Pruned] 1 supersets removed from queue.

--- RANDOM SEARCH: h=3, exponent=6 ---
  Target Ambient Dimension: 74
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 77 impossible/redundant architectures.
  Starting sequential evaluation on 89324 viable candidates.
  [FULL ] [2, 261, 296, 2] -> Rank: 74/74 (Params: 78370)
    [Upward Pruned] 199 supersets removed from queue.
  [FULL ] [2, 170, 104, 2] -> Rank: 74/74 (Params: 18228)
    [Upward Pruned] 25606 supersets removed from queue.
  [FULL ] [2, 137, 161, 2] -> Rank: 74/74 (Params: 22653)
    [Upward Pruned] 4619 supersets removed from queue.
  [FULL ] [2, 194, 16, 2] -> Rank: 74/74 (Params: 3524)
    [Upward Pruned] 9415 supersets removed from queue.
  [FULL ] [2, 64, 19, 2] -> Rank: 74/74 (Params: 1382)
    [Upward Pruned] 27311 supersets removed from queue.
  [FULL ] [2, 45, 186, 2] -> Rank: 74/74 (Params: 8832)
    [Upward Pruned] 2184 supersets removed from queue.
  [FULL ] [2, 17, 162, 2] -> Rank: 74/74 (Params: 3112)
    [Upward Pruned] 4347 supersets removed from queue.
  [FULL ] [2, 32, 119, 2] -> Rank: 74/74 (Params: 4110)
    [Upward Pruned] 1375 supersets removed from queue.
  [SHORT] [2, 2, 72, 2] -> Rank: 16/74 (Params: 292)
    [Downward Pruned] 54 subsets removed from queue.
  [FULL ] [2, 46, 22, 2] -> Rank: 74/74 (Params: 1148)
    [Upward Pruned] 1745 supersets removed from queue.
  [FULL ] [2, 29, 15, 2] -> Rank: 74/74 (Params: 523)
    [Upward Pruned] 2649 supersets removed from queue.
  [FULL ] [2, 7, 284, 2] -> Rank: 74/74 (Params: 2570)
    [Upward Pruned] 169 supersets removed from queue.
  [FULL ] [2, 15, 241, 2] -> Rank: 74/74 (Params: 4127)
    [Upward Pruned] 85 supersets removed from queue.
  [SHORT] [2, 235, 2, 2] -> Rank: 16/74 (Params: 944)
    [Downward Pruned] 217 subsets removed from queue.
  [FULL ] [2, 205, 12, 2] -> Rank: 74/74 (Params: 2894)
    [Upward Pruned] 287 supersets removed from queue.
  [SHORT] [2, 253, 6, 2] -> Rank: 48/74 (Params: 2036)
    [Downward Pruned] 990 subsets removed from queue.
  [FULL ] [2, 128, 13, 2] -> Rank: 74/74 (Params: 1946)
    [Upward Pruned] 153 supersets removed from queue.
  [FULL ] [2, 19, 107, 2] -> Rank: 74/74 (Params: 2285)
    [Upward Pruned] 549 supersets removed from queue.
  [SHORT] [2, 63, 7, 2] -> Rank: 56/74 (Params: 581)
    [Downward Pruned] 56 subsets removed from queue.
  [FULL ] [2, 4, 290, 2] -> Rank: 74/74 (Params: 1748)
    [Upward Pruned] 32 supersets removed from queue.
  [FULL ] [2, 10, 212, 2] -> Rank: 74/74 (Params: 2564)
    [Upward Pruned] 417 supersets removed from queue.
  [FULL ] [2, 7, 226, 2] -> Rank: 74/74 (Params: 2048)
    [Upward Pruned] 173 supersets removed from queue.
  [SHORT] [2, 3, 34, 2] -> Rank: 57/74 (Params: 176)
    [Downward Pruned] 20 subsets removed from queue.
  [FULL ] [2, 13, 164, 2] -> Rank: 74/74 (Params: 2486)
    [Upward Pruned] 191 supersets removed from queue.
  [FULL ] [2, 9, 64, 2] -> Rank: 74/74 (Params: 722)
    [Upward Pruned] 1631 supersets removed from queue.
  [SHORT] [2, 297, 2, 2] -> Rank: 16/74 (Params: 1192)
    [Downward Pruned] 43 subsets removed from queue.
  [SHORT] [2, 3, 86, 2] -> Rank: 57/74 (Params: 436)
    [Downward Pruned] 65 subsets removed from queue.
  [SHORT] [2, 2, 239, 2] -> Rank: 16/74 (Params: 960)
    [Downward Pruned] 152 subsets removed from queue.
  [SHORT] [2, 3, 226, 2] -> Rank: 57/74 (Params: 1136)
    [Downward Pruned] 139 subsets removed from queue.
  [SHORT] [2, 262, 7, 2] -> Rank: 56/74 (Params: 2372)
    [Downward Pruned] 234 subsets removed from queue.
  [SHORT] [2, 151, 8, 2] -> Rank: 64/74 (Params: 1526)
    [Downward Pruned] 145 subsets removed from queue.
  [FULL ] [2, 7, 18, 2] -> Rank: 74/74 (Params: 176)
    [Upward Pruned] 1335 supersets removed from queue.
  [FULL ] [2, 298, 10, 2] -> Rank: 74/74 (Params: 3596)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [2, 21, 10, 2] -> Rank: 74/74 (Params: 272)
    [Upward Pruned] 975 supersets removed from queue.
  [SHORT] [2, 74, 9, 2] -> Rank: 72/74 (Params: 832)
    [Downward Pruned] 68 subsets removed from queue.
  [FULL ] [2, 17, 16, 2] -> Rank: 74/74 (Params: 338)
    [Upward Pruned] 7 supersets removed from queue.
  [SHORT] [2, 281, 4, 2] -> Rank: 32/74 (Params: 1694)
    [Downward Pruned] 37 subsets removed from queue.
  [SHORT] [2, 224, 8, 2] -> Rank: 64/74 (Params: 2256)
    [Downward Pruned] 72 subsets removed from queue.
  [SHORT] [2, 282, 3, 2] -> Rank: 24/74 (Params: 1416)
  [FULL ] [2, 6, 56, 2] -> Rank: 74/74 (Params: 460)
    [Upward Pruned] 233 supersets removed from queue.
  [FULL ] [2, 4, 107, 2] -> Rank: 74/74 (Params: 650)
    [Upward Pruned] 365 supersets removed from queue.
  [FULL ] [2, 6, 40, 2] -> Rank: 74/74 (Params: 332)
    [Upward Pruned] 15 supersets removed from queue.
  [SHORT] [2, 2, 298, 2] -> Rank: 16/74 (Params: 1196)
    [Downward Pruned] 58 subsets removed from queue.
  [FULL ] [2, 5, 52, 2] -> Rank: 74/74 (Params: 374)
    [Upward Pruned] 54 supersets removed from queue.
  [SHORT] [2, 264, 8, 2] -> Rank: 64/74 (Params: 2656)
    [Downward Pruned] 45 subsets removed from queue.
  [FULL ] [2, 4, 33, 2] -> Rank: 74/74 (Params: 206)
    [Upward Pruned] 99 supersets removed from queue.
  [SHORT] [2, 155, 9, 2] -> Rank: 72/74 (Params: 1723)
    [Downward Pruned] 80 subsets removed from queue.
  [SHORT] [2, 289, 8, 2] -> Rank: 64/74 (Params: 2906)
    [Downward Pruned] 114 subsets removed from queue.
  [SHORT] [2, 197, 9, 2] -> Rank: 72/74 (Params: 2185)
    [Downward Pruned] 41 subsets removed from queue.
  [SHORT] [2, 3, 228, 2] -> Rank: 57/74 (Params: 1146)
    [Downward Pruned] 1 subsets removed from queue.
  [FULL ] [2, 18, 14, 2] -> Rank: 74/74 (Params: 316)
    [Upward Pruned] 5 supersets removed from queue.
  [SHORT] [2, 3, 269, 2] -> Rank: 57/74 (Params: 1351)
    [Downward Pruned] 40 subsets removed from queue.
  [SHORT] [2, 216, 9, 2] -> Rank: 72/74 (Params: 2394)
    [Downward Pruned] 18 subsets removed from queue.
  [SHORT] [2, 295, 9, 2] -> Rank: 72/74 (Params: 3263)
    [Downward Pruned] 114 subsets removed from queue.
  [FULL ] [2, 14, 17, 2] -> Rank: 74/74 (Params: 300)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [2, 13, 15, 2] -> Rank: 74/74 (Params: 251)
    [Upward Pruned] 9 supersets removed from queue.
  [SHORT] [2, 299, 7, 2] -> Rank: 56/74 (Params: 2705)
    [Downward Pruned] 21 subsets removed from queue.
  [FULL ] [2, 17, 14, 2] -> Rank: 74/74 (Params: 300)
  [FULL ] [2, 8, 14, 2] -> Rank: 74/74 (Params: 156)
    [Upward Pruned] 23 supersets removed from queue.
  [FULL ] [2, 5, 31, 2] -> Rank: 74/74 (Params: 227)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [2, 4, 28, 2] -> Rank: 74/74 (Params: 176)
    [Upward Pruned] 10 supersets removed from queue.
  [FULL ] [2, 10, 11, 2] -> Rank: 74/74 (Params: 152)
    [Upward Pruned] 32 supersets removed from queue.
  [SHORT] [2, 3, 273, 2] -> Rank: 57/74 (Params: 1371)
    [Downward Pruned] 3 subsets removed from queue.
  [SHORT] [2, 3, 280, 2] -> Rank: 57/74 (Params: 1406)
    [Downward Pruned] 6 subsets removed from queue.
  [FULL ] [2, 9, 11, 2] -> Rank: 74/74 (Params: 139)
    [Upward Pruned] 2 supersets removed from queue.
  [SHORT] [2, 3, 287, 2] -> Rank: 57/74 (Params: 1441)
    [Downward Pruned] 6 subsets removed from queue.
  [SHORT] [2, 300, 2, 2] -> Rank: 16/74 (Params: 1204)
  [FULL ] [2, 5, 12, 2] -> Rank: 74/74 (Params: 94)
    [Upward Pruned] 39 supersets removed from queue.
  [SHORT] [2, 3, 300, 2] -> Rank: 57/74 (Params: 1506)
    [Downward Pruned] 14 subsets removed from queue.
  [FULL ] [2, 6, 11, 2] -> Rank: 74/74 (Params: 100)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [2, 4, 20, 2] -> Rank: 74/74 (Params: 128)
    [Upward Pruned] 7 supersets removed from queue.
  [SHORT] [2, 297, 8, 2] -> Rank: 64/74 (Params: 2986)
    [Downward Pruned] 1 subsets removed from queue.
  [SHORT] [2, 4, 12, 2] -> Rank: 64/74 (Params: 80)
    [Downward Pruned] 1 subsets removed from queue.
  [FULL ] [2, 4, 19, 2] -> Rank: 74/74 (Params: 122)
  [SHORT] [2, 5, 11, 2] -> Rank: 71/74 (Params: 87)
    [Downward Pruned] 1 subsets removed from queue.
  [FULL ] [2, 6, 10, 2] -> Rank: 74/74 (Params: 92)
    [Upward Pruned] 14 supersets removed from queue.
  [SHORT] [2, 298, 9, 2] -> Rank: 72/74 (Params: 3296)
    [Downward Pruned] 3 subsets removed from queue.
  [SHORT] [2, 300, 5, 2] -> Rank: 40/74 (Params: 2110)
    [Downward Pruned] 2 subsets removed from queue.
  [SHORT] [2, 300, 6, 2] -> Rank: 48/74 (Params: 2412)
  [SHORT] [2, 4, 13, 2] -> Rank: 69/74 (Params: 86)
  [FULL ] [2, 4, 18, 2] -> Rank: 74/74 (Params: 116)
  [SHORT] [2, 299, 8, 2] -> Rank: 64/74 (Params: 3006)
  [SHORT] [2, 299, 9, 2] -> Rank: 72/74 (Params: 3307)
  [SHORT] [2, 300, 8, 2] -> Rank: 64/74 (Params: 3016)
    [Downward Pruned] 1 subsets removed from queue.
  [FULL ] [2, 4, 14, 2] -> Rank: 74/74 (Params: 92)
    [Upward Pruned] 3 supersets removed from queue.
  [SHORT] [2, 300, 9, 2] -> Rank: 72/74 (Params: 3318)

Added 92 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/2_2_r6_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=7 ---
  Target Ambient Dimension: 16
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 2 impossible/redundant architectures.
  Starting sequential evaluation on 297 viable candidates.
  [FULL ] [2, 96, 2] -> Rank: 16/16 (Params: 384)
    [Upward Pruned] 204 supersets removed from queue.
  [FULL ] [2, 43, 2] -> Rank: 16/16 (Params: 172)
    [Upward Pruned] 52 supersets removed from queue.

  [FULL ] [2, 22, 2] -> Rank: 16/16 (Params: 88)
    [Upward Pruned] 20 supersets removed from queue.
  [FULL ] [2, 7, 2] -> Rank: 16/16 (Params: 28)
    [Upward Pruned] 14 supersets removed from queue.
  [FULL ] [2, 6, 2] -> Rank: 16/16 (Params: 24)
  [SHORT] [2, 4, 2] -> Rank: 12/16 (Params: 16)
  [SHORT] [2, 5, 2] -> Rank: 15/16 (Params: 20)

--- RANDOM SEARCH: h=3, exponent=7 ---
  Target Ambient Dimension: 100
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 127 impossible/redundant architectures.
  Starting sequential evaluation on 89274 viable candidates.
  [FULL ] [2, 281, 157, 2] -> Rank: 100/100 (Params: 44993)
    [Upward Pruned] 2879 supersets removed from queue.
  [FULL ] [2, 244, 68, 2] -> Rank: 100/100 (Params: 17216)
    [Upward Pruned] 10400 supersets removed from queue.
  [FULL ] [2, 47, 161, 2] -> Rank: 100/100 (Params: 7983)
    [Upward Pruned] 27579 supersets removed from queue.
  [FULL ] [2, 102, 106, 2] -> Rank: 100/100 (Params: 11228)
    [Upward Pruned] 7809 supersets removed from queue.
  [FULL ] [2, 27, 256, 2] -> Rank: 100/100 (Params: 7478)
    [Upward Pruned] 899 supersets removed from queue.
  [FULL ] [2, 102, 12, 2] -> Rank: 100/100 (Params: 1452)
    [Upward Pruned] 16539 supersets removed from queue.
  [FULL ] [2, 39, 224, 2] -> Rank: 100/100 (Params: 9262)
    [Upward Pruned] 255 supersets removed from queue.
  [FULL ] [2, 27, 85, 2] -> Rank: 100/100 (Params: 2519)
    [Upward Pruned] 7343 supersets removed from queue.
  [FULL ] [2, 72, 35, 2] -> Rank: 100/100 (Params: 2734)
    [Upward Pruned] 1499 supersets removed from queue.
  [SHORT] [2, 235, 2, 2] -> Rank: 18/100 (Params: 944)
    [Downward Pruned] 211 subsets removed from queue.
  [FULL ] [2, 23, 265, 2] -> Rank: 100/100 (Params: 6671)
    [Upward Pruned] 143 supersets removed from queue.
  [SHORT] [2, 97, 3, 2] -> Rank: 27/100 (Params: 491)
    [Downward Pruned] 78 subsets removed from queue.
  [FULL ] [2, 47, 12, 2] -> Rank: 100/100 (Params: 682)
    [Upward Pruned] 2514 supersets removed from queue.
  [FULL ] [2, 10, 80, 2] -> Rank: 100/100 (Params: 980)
    [Upward Pruned] 3712 supersets removed from queue.
  [SHORT] [2, 3, 29, 2] -> Rank: 73/100 (Params: 151)
    [Downward Pruned] 16 subsets removed from queue.
  [FULL ] [2, 34, 62, 2] -> Rank: 100/100 (Params: 2300)
    [Upward Pruned] 233 supersets removed from queue.
  [FULL ] [2, 22, 70, 2] -> Rank: 100/100 (Params: 1724)
    [Upward Pruned] 119 supersets removed from queue.
  [FULL ] [2, 17, 50, 2] -> Rank: 100/100 (Params: 984)
    [Upward Pruned] 545 supersets removed from queue.
  [FULL ] [2, 46, 28, 2] -> Rank: 100/100 (Params: 1436)
    [Upward Pruned] 21 supersets removed from queue.
  [SHORT] [2, 164, 7, 2] -> Rank: 63/100 (Params: 1490)
    [Downward Pruned] 676 subsets removed from queue.
  [FULL ] [2, 37, 34, 2] -> Rank: 100/100 (Params: 1400)
    [Upward Pruned] 143 supersets removed from queue.
  [SHORT] [2, 294, 7, 2] -> Rank: 63/100 (Params: 2660)
    [Downward Pruned] 708 subsets removed from queue.
  [FULL ] [2, 9, 67, 2] -> Rank: 100/100 (Params: 755)
    [Upward Pruned] 324 supersets removed from queue.
  [SHORT] [2, 3, 289, 2] -> Rank: 73/100 (Params: 1451)
    [Downward Pruned] 519 subsets removed from queue.
  [FULL ] [2, 4, 155, 2] -> Rank: 100/100 (Params: 938)
    [Upward Pruned] 729 supersets removed from queue.
  [FULL ] [2, 6, 45, 2] -> Rank: 100/100 (Params: 372)
    [Upward Pruned] 605 supersets removed from queue.
  [FULL ] [2, 9, 34, 2] -> Rank: 100/100 (Params: 392)
    [Upward Pruned] 307 supersets removed from queue.
  [FULL ] [2, 30, 12, 2] -> Rank: 100/100 (Params: 444)
    [Upward Pruned] 367 supersets removed from queue.
  [SHORT] [2, 114, 9, 2] -> Rank: 81/100 (Params: 1272)
    [Downward Pruned] 212 subsets removed from queue.
  [SHORT] [2, 276, 11, 2] -> Rank: 99/100 (Params: 3610)
    [Downward Pruned] 864 subsets removed from queue.
  [FULL ] [2, 4, 154, 2] -> Rank: 100/100 (Params: 932)
    [Upward Pruned] 1 supersets removed from queue.
  [SHORT] [2, 298, 10, 2] -> Rank: 90/100 (Params: 3596)
    [Downward Pruned] 89 subsets removed from queue.
  [FULL ] [2, 27, 33, 2] -> Rank: 100/100 (Params: 1011)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [2, 29, 27, 2] -> Rank: 100/100 (Params: 895)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [2, 22, 29, 2] -> Rank: 100/100 (Params: 740)
    [Upward Pruned] 32 supersets removed from queue.
  [FULL ] [2, 22, 28, 2] -> Rank: 100/100 (Params: 716)
    [Upward Pruned] 6 supersets removed from queue.
  [FULL ] [2, 4, 59, 2] -> Rank: 100/100 (Params: 362)
    [Upward Pruned] 189 supersets removed from queue.
  [FULL ] [2, 4, 27, 2] -> Rank: 100/100 (Params: 170)
    [Upward Pruned] 215 supersets removed from queue.
  [FULL ] [2, 22, 17, 2] -> Rank: 100/100 (Params: 452)
    [Upward Pruned] 79 supersets removed from queue.
  [FULL ] [2, 17, 16, 2] -> Rank: 100/100 (Params: 338)
    [Upward Pruned] 62 supersets removed from queue.
  [FULL ] [2, 11, 18, 2] -> Rank: 100/100 (Params: 256)
    [Upward Pruned] 53 supersets removed from queue.
  [FULL ] [2, 6, 22, 2] -> Rank: 100/100 (Params: 188)
    [Upward Pruned] 24 supersets removed from queue.
  [FULL ] [2, 24, 15, 2] -> Rank: 100/100 (Params: 438)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [2, 4, 22, 2] -> Rank: 100/100 (Params: 140)
    [Upward Pruned] 9 supersets removed from queue.
  [SHORT] [2, 2, 291, 2] -> Rank: 18/100 (Params: 1168)
    [Downward Pruned] 1 subsets removed from queue.
  [FULL ] [2, 10, 21, 2] -> Rank: 100/100 (Params: 272)
  [FULL ] [2, 24, 14, 2] -> Rank: 100/100 (Params: 412)
    [Upward Pruned] 5 supersets removed from queue.
  [FULL ] [2, 6, 21, 2] -> Rank: 100/100 (Params: 180)
    [Upward Pruned] 3 supersets removed from queue.
  [SHORT] [2, 277, 11, 2] -> Rank: 99/100 (Params: 3623)
  [FULL ] [2, 7, 16, 2] -> Rank: 100/100 (Params: 158)
    [Upward Pruned] 31 supersets removed from queue.
  [SHORT] [2, 290, 11, 2] -> Rank: 99/100 (Params: 3792)
    [Downward Pruned] 12 subsets removed from queue.
  [SHORT] [2, 299, 2, 2] -> Rank: 18/100 (Params: 1200)
  [FULL ] [2, 20, 13, 2] -> Rank: 100/100 (Params: 326)
    [Upward Pruned] 17 supersets removed from queue.
  [FULL ] [2, 18, 14, 2] -> Rank: 100/100 (Params: 316)
    [Upward Pruned] 3 supersets removed from queue.
  [SHORT] [2, 3, 291, 2] -> Rank: 73/100 (Params: 1461)
    [Downward Pruned] 1 subsets removed from queue.
  [FULL ] [2, 16, 15, 2] -> Rank: 100/100 (Params: 302)
    [Upward Pruned] 1 supersets removed from queue.
  [SHORT] [2, 298, 11, 2] -> Rank: 99/100 (Params: 3896)
    [Downward Pruned] 7 subsets removed from queue.
  [FULL ] [2, 21, 12, 2] -> Rank: 100/100 (Params: 318)
    [Upward Pruned] 8 supersets removed from queue.
  [SHORT] [2, 299, 9, 2] -> Rank: 81/100 (Params: 3307)
    [Downward Pruned] 6 subsets removed from queue.
  [SHORT] [2, 2, 298, 2] -> Rank: 18/100 (Params: 1196)
    [Downward Pruned] 6 subsets removed from queue.
  [FULL ] [2, 5, 21, 2] -> Rank: 100/100 (Params: 157)
  [SHORT] [2, 299, 11, 2] -> Rank: 99/100 (Params: 3909)
    [Downward Pruned] 1 subsets removed from queue.
  [SHORT] [2, 300, 8, 2] -> Rank: 72/100 (Params: 3016)
    [Downward Pruned] 6 subsets removed from queue.
  [FULL ] [2, 7, 13, 2] -> Rank: 100/100 (Params: 131)
    [Upward Pruned] 32 supersets removed from queue.
  [SHORT] [2, 4, 17, 2] -> Rank: 89/100 (Params: 110)
    [Downward Pruned] 1 subsets removed from queue.
  [SHORT] [2, 300, 11, 2] -> Rank: 99/100 (Params: 3922)
    [Downward Pruned] 2 subsets removed from queue.
  [SHORT] [2, 5, 13, 2] -> Rank: 83/100 (Params: 101)
  [FULL ] [2, 8, 12, 2] -> Rank: 100/100 (Params: 136)
    [Upward Pruned] 12 supersets removed from queue.
  [FULL ] [2, 6, 18, 2] -> Rank: 100/100 (Params: 156)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [2, 4, 21, 2] -> Rank: 100/100 (Params: 134)
  [SHORT] [2, 6, 12, 2] -> Rank: 90/100 (Params: 108)
  [SHORT] [2, 2, 299, 2] -> Rank: 18/100 (Params: 1200)
  [FULL ] [2, 5, 17, 2] -> Rank: 100/100 (Params: 129)
    [Upward Pruned] 4 supersets removed from queue.
  [SHORT] [2, 3, 296, 2] -> Rank: 73/100 (Params: 1486)
    [Downward Pruned] 4 subsets removed from queue.
  [FULL ] [2, 4, 20, 2] -> Rank: 100/100 (Params: 128)
  [SHORT] [2, 4, 18, 2] -> Rank: 94/100 (Params: 116)
  [SHORT] [2, 3, 297, 2] -> Rank: 73/100 (Params: 1491)
  [FULL ] [2, 6, 14, 2] -> Rank: 100/100 (Params: 124)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [2, 5, 16, 2] -> Rank: 100/100 (Params: 122)
  [SHORT] [2, 5, 15, 2] -> Rank: 95/100 (Params: 115)
    [Downward Pruned] 1 subsets removed from queue.
  [SHORT] [2, 3, 299, 2] -> Rank: 73/100 (Params: 1501)
    [Downward Pruned] 1 subsets removed from queue.
  [SHORT] [2, 2, 300, 2] -> Rank: 18/100 (Params: 1204)
  [SHORT] [2, 3, 300, 2] -> Rank: 73/100 (Params: 1506)
  [SHORT] [2, 6, 13, 2] -> Rank: 97/100 (Params: 116)
  [FULL ] [2, 7, 12, 2] -> Rank: 100/100 (Params: 122)
  [SHORT] [2, 4, 19, 2] -> Rank: 99/100 (Params: 122)

Added 93 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/2_2_r7_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=8 ---
  Target Ambient Dimension: 18
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 3 impossible/redundant architectures.
  Starting sequential evaluation on 296 viable candidates.
  [FULL ] [2, 25, 2] -> Rank: 18/18 (Params: 100)
    [Upward Pruned] 275 supersets removed from queue.
  [FULL ] [2, 7, 2] -> Rank: 18/18 (Params: 28)
    [Upward Pruned] 17 supersets removed from queue.
  [FULL ] [2, 6, 2] -> Rank: 18/18 (Params: 24)
  [SHORT] [2, 5, 2] -> Rank: 15/18 (Params: 20)

--- RANDOM SEARCH: h=3, exponent=8 ---
  Target Ambient Dimension: 130
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 198 impossible/redundant architectures.
  Starting sequential evaluation on 89203 viable candidates.
  [FULL ] [2, 94, 133, 2] -> Rank: 130/130 (Params: 12956)
    [Upward Pruned] 34775 supersets removed from queue.
  [FULL ] [2, 199, 61, 2] -> Rank: 130/130 (Params: 12659)
    [Upward Pruned] 7343 supersets removed from queue.
  [FULL ] [2, 279, 25, 2] -> Rank: 130/130 (Params: 7583)
    [Upward Pruned] 791 supersets removed from queue.
  [FULL ] [2, 209, 51, 2] -> Rank: 130/130 (Params: 11179)
    [Upward Pruned] 699 supersets removed from queue.
  [SHORT] [2, 143, 11, 2] -> Rank: 110/130 (Params: 1881)
    [Downward Pruned] 1273 subsets removed from queue.
  [FULL ] [2, 149, 37, 2] -> Rank: 130/130 (Params: 5885)
    [Upward Pruned] 6019 supersets removed from queue.
  [FULL ] [2, 37, 227, 2] -> Rank: 130/130 (Params: 8927)
    [Upward Pruned] 4217 supersets removed from queue.
  [FULL ] [2, 125, 131, 2] -> Rank: 130/130 (Params: 16887)
    [Upward Pruned] 47 supersets removed from queue.
  [FULL ] [2, 19, 239, 2] -> Rank: 130/130 (Params: 5057)
    [Upward Pruned] 1115 supersets removed from queue.
  [FULL ] [2, 121, 94, 2] -> Rank: 130/130 (Params: 11804)
    [Upward Pruned] 1043 supersets removed from queue.
  [FULL ] [2, 100, 52, 2] -> Rank: 130/130 (Params: 5504)
    [Upward Pruned] 2876 supersets removed from queue.
  [FULL ] [2, 75, 201, 2] -> Rank: 130/130 (Params: 15627)
    [Upward Pruned] 493 supersets removed from queue.
  [FULL ] [2, 72, 71, 2] -> Rank: 130/130 (Params: 5398)
    [Upward Pruned] 3309 supersets removed from queue.
  [FULL ] [2, 10, 265, 2] -> Rank: 130/130 (Params: 3200)
    [Upward Pruned] 323 supersets removed from queue.
  [FULL ] [2, 188, 22, 2] -> Rank: 130/130 (Params: 4556)
    [Upward Pruned] 1430 supersets removed from queue.
  [FULL ] [2, 62, 34, 2] -> Rank: 130/130 (Params: 2300)
    [Upward Pruned] 3964 supersets removed from queue.
  [FULL ] [2, 32, 221, 2] -> Rank: 130/130 (Params: 7578)
    [Upward Pruned] 239 supersets removed from queue.
  [FULL ] [2, 193, 19, 2] -> Rank: 130/130 (Params: 4091)
    [Upward Pruned] 323 supersets removed from queue.
  [SHORT] [2, 204, 10, 2] -> Rank: 100/130 (Params: 2468)
    [Downward Pruned] 548 subsets removed from queue.
  [FULL ] [2, 20, 97, 2] -> Rank: 130/130 (Params: 2174)
    [Upward Pruned] 5423 supersets removed from queue.
  [SHORT] [2, 116, 12, 2] -> Rank: 120/130 (Params: 1648)
    [Downward Pruned] 108 subsets removed from queue.
  [SHORT] [2, 235, 12, 2] -> Rank: 120/130 (Params: 3314)
    [Downward Pruned] 489 subsets removed from queue.
  [FULL ] [2, 119, 28, 2] -> Rank: 130/130 (Params: 3626)
    [Upward Pruned] 413 supersets removed from queue.
  [FULL ] [2, 8, 277, 2] -> Rank: 130/130 (Params: 2786)
    [Upward Pruned] 47 supersets removed from queue.
  [FULL ] [2, 12, 232, 2] -> Rank: 130/130 (Params: 3272)
    [Upward Pruned] 237 supersets removed from queue.
  [FULL ] [2, 11, 65, 2] -> Rank: 130/130 (Params: 867)
    [Upward Pruned] 2879 supersets removed from queue.
  [FULL ] [2, 42, 35, 2] -> Rank: 130/130 (Params: 1624)
    [Upward Pruned] 599 supersets removed from queue.
  [FULL ] [2, 168, 14, 2] -> Rank: 130/130 (Params: 2716)
    [Upward Pruned] 859 supersets removed from queue.
  [FULL ] [2, 190, 13, 2] -> Rank: 130/130 (Params: 2876)
    [Upward Pruned] 110 supersets removed from queue.
  [FULL ] [2, 118, 27, 2] -> Rank: 130/130 (Params: 3476)
    [Upward Pruned] 55 supersets removed from queue.
  [FULL ] [2, 67, 16, 2] -> Rank: 130/130 (Params: 1238)
    [Upward Pruned] 1467 supersets removed from queue.
  [FULL ] [2, 5, 95, 2] -> Rank: 130/130 (Params: 675)
    [Upward Pruned] 1151 supersets removed from queue.
  [FULL ] [2, 55, 17, 2] -> Rank: 130/130 (Params: 1079)
    [Upward Pruned] 210 supersets removed from queue.
  [SHORT] [2, 251, 4, 2] -> Rank: 40/130 (Params: 1514)
    [Downward Pruned] 47 subsets removed from queue.
  [SHORT] [2, 285, 3, 2] -> Rank: 30/130 (Params: 1431)
    [Downward Pruned] 67 subsets removed from queue.
  [SHORT] [2, 238, 10, 2] -> Rank: 100/130 (Params: 2876)
    [Downward Pruned] 17 subsets removed from queue.
  [SHORT] [2, 277, 7, 2] -> Rank: 70/130 (Params: 2507)
    [Downward Pruned] 142 subsets removed from queue.
  [FULL ] [2, 4, 279, 2] -> Rank: 130/130 (Params: 1682)
    [Upward Pruned] 21 supersets removed from queue.
  [SHORT] [2, 289, 10, 2] -> Rank: 100/130 (Params: 3488)
    [Downward Pruned] 208 subsets removed from queue.
  [FULL ] [2, 4, 54, 2] -> Rank: 130/130 (Params: 332)
    [Upward Pruned] 811 supersets removed from queue.
  [FULL ] [2, 34, 16, 2] -> Rank: 130/130 (Params: 644)
    [Upward Pruned] 562 supersets removed from queue.
  [FULL ] [2, 9, 42, 2] -> Rank: 130/130 (Params: 480)
    [Upward Pruned] 299 supersets removed from queue.
  [SHORT] [2, 2, 97, 2] -> Rank: 20/130 (Params: 392)
    [Downward Pruned] 65 subsets removed from queue.
  [FULL ] [2, 65, 13, 2] -> Rank: 130/130 (Params: 1001)
    [Upward Pruned] 330 supersets removed from queue.
  [SHORT] [2, 3, 84, 2] -> Rank: 91/130 (Params: 426)
    [Downward Pruned] 59 subsets removed from queue.
  [SHORT] [2, 2, 248, 2] -> Rank: 20/130 (Params: 996)
    [Downward Pruned] 150 subsets removed from queue.
  [SHORT] [2, 293, 9, 2] -> Rank: 90/130 (Params: 3241)
    [Downward Pruned] 31 subsets removed from queue.
  [FULL ] [2, 18, 16, 2] -> Rank: 130/130 (Params: 356)
    [Upward Pruned] 415 supersets removed from queue.
  [FULL ] [2, 4, 28, 2] -> Rank: 130/130 (Params: 176)
    [Upward Pruned] 255 supersets removed from queue.
  [SHORT] [2, 3, 186, 2] -> Rank: 91/130 (Params: 936)
    [Downward Pruned] 101 subsets removed from queue.
  [SHORT] [2, 281, 12, 2] -> Rank: 120/130 (Params: 3958)
    [Downward Pruned] 91 subsets removed from queue.
  [FULL ] [2, 18, 14, 2] -> Rank: 130/130 (Params: 316)
    [Upward Pruned] 93 supersets removed from queue.
  [SHORT] [2, 300, 10, 2] -> Rank: 100/130 (Params: 3620)
    [Downward Pruned] 66 subsets removed from queue.
  [SHORT] [2, 3, 285, 2] -> Rank: 91/130 (Params: 1431)
    [Downward Pruned] 135 subsets removed from queue.
  [FULL ] [2, 11, 15, 2] -> Rank: 130/130 (Params: 217)
    [Upward Pruned] 90 supersets removed from queue.
  [FULL ] [2, 14, 14, 2] -> Rank: 130/130 (Params: 252)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [2, 9, 15, 2] -> Rank: 130/130 (Params: 183)
    [Upward Pruned] 25 supersets removed from queue.
  [FULL ] [2, 54, 13, 2] -> Rank: 130/130 (Params: 836)
    [Upward Pruned] 10 supersets removed from queue.
  [FULL ] [2, 5, 27, 2] -> Rank: 130/130 (Params: 199)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [2, 6, 19, 2] -> Rank: 130/130 (Params: 164)
    [Upward Pruned] 23 supersets removed from queue.
  [FULL ] [2, 32, 13, 2] -> Rank: 130/130 (Params: 506)
    [Upward Pruned] 21 supersets removed from queue.

[Interrupt] User halted the loop early. Saving progress and continuing execution...

Added 65 new architectures to the database.
Re-evaluating minimal filling properties (grouped by depth h and exponent)...
Database successfully saved to '../data/raw/2_2_r8_architectures.csv'.

No existing database found. Starting fresh...

--- RANDOM SEARCH: h=2, exponent=9 ---
  Target Ambient Dimension: 20
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 3 impossible/redundant architectures.
  Starting sequential evaluation on 296 viable candidates.
  [FULL ] [2, 13, 2] -> Rank: 20/20 (Params: 52)
    [Upward Pruned] 287 supersets removed from queue.
  [FULL ] [2, 12, 2] -> Rank: 20/20 (Params: 48)
  [FULL ] [2, 8, 2] -> Rank: 20/20 (Params: 32)
    [Upward Pruned] 3 supersets removed from queue.
  [FULL ] [2, 7, 2] -> Rank: 20/20 (Params: 28)
  [SHORT] [2, 5, 2] -> Rank: 15/20 (Params: 20)
  [SHORT] [2, 6, 2] -> Rank: 18/20 (Params: 24)

--- RANDOM SEARCH: h=3, exponent=9 ---
  Target Ambient Dimension: 164
  Generating candidate pool...
  Using global bounds: min_width=2, max_width=300

  Pruned 277 impossible/redundant architectures.
  Starting sequential evaluation on 89124 viable candidates.
  [FULL ] [2, 189, 98, 2] -> Rank: 164/164 (Params: 19096)
    [Upward Pruned] 22735 supersets removed from queue.
  [FULL ] [2, 141, 79, 2] -> Rank: 164/164 (Params: 11579)
    [Upward Pruned] 12783 supersets removed from queue.
  [FULL ] [2, 93, 111, 2] -> Rank: 164/164 (Params: 10731)
    [Upward Pruned] 9119 supersets removed from queue.
  [FULL ] [2, 49, 44, 2] -> Rank: 164/164 (Params: 2342)
    [Upward Pruned] 20123 supersets removed from queue.
  [FULL ] [2, 35, 221, 2] -> Rank: 164/164 (Params: 8247)
    [Upward Pruned] 1119 supersets removed from queue.
  [FULL ] [2, 66, 43, 2] -> Rank: 164/164 (Params: 3056)
    [Upward Pruned] 234 supersets removed from queue.
  [FULL ] [2, 175, 17, 2] -> Rank: 164/164 (Params: 3359)
    [Upward Pruned] 3275 supersets removed from queue.
  [FULL ] [2, 20, 191, 2] -> Rank: 164/164 (Params: 4242)
    [Upward Pruned] 2069 supersets removed from queue.
  [FULL ] [2, 154, 23, 2] -> Rank: 164/164 (Params: 3896)
    [Upward Pruned] 419 supersets removed from queue.
  [SHORT] [2, 274, 14, 2] -> Rank: 154/164 (Params: 4412)
    [Downward Pruned] 3337 subsets removed from queue.
  [FULL ] [2, 18, 184, 2] -> Rank: 164/164 (Params: 3716)
    [Upward Pruned] 436 supersets removed from queue.
  [SHORT] [2, 2, 115, 2] -> Rank: 22/164 (Params: 464)
    [Downward Pruned] 75 subsets removed from queue.
  [FULL ] [2, 14, 225, 2] -> Rank: 164/164 (Params: 3628)
    [Upward Pruned] 303 supersets removed from queue.
  [FULL ] [2, 13, 143, 2] -> Rank: 164/164 (Params: 2171)
    [Upward Pruned] 1756 supersets removed from queue.
  [FULL ] [2, 12, 299, 2] -> Rank: 164/164 (Params: 4210)
    [Upward Pruned] 1 supersets removed from queue.
  [FULL ] [2, 45, 33, 2] -> Rank: 164/164 (Params: 1641)
    [Upward Pruned] 1506 supersets removed from queue.
  [FULL ] [2, 4, 273, 2] -> Rank: 164/164 (Params: 1646)
    [Upward Pruned] 249 supersets removed from queue.
  [FULL ] [2, 82, 20, 2] -> Rank: 164/164 (Params: 1844)
    [Upward Pruned] 998 supersets removed from queue.
  [FULL ] [2, 53, 28, 2] -> Rank: 164/164 (Params: 1646)
    [Upward Pruned] 144 supersets removed from queue.
  [FULL ] [2, 11, 42, 2] -> Rank: 164/164 (Params: 568)
    [Upward Pruned] 3693 supersets removed from queue.
  [FULL ] [2, 9, 163, 2] -> Rank: 164/164 (Params: 1811)
    [Upward Pruned] 219 supersets removed from queue.
  [FULL ] [2, 45, 27, 2] -> Rank: 164/164 (Params: 1359)
    [Upward Pruned] 76 supersets removed from queue.
  [FULL ] [2, 5, 214, 2] -> Rank: 164/164 (Params: 1508)
    [Upward Pruned] 235 supersets removed from queue.
  [FULL ] [2, 9, 132, 2] -> Rank: 164/164 (Params: 1470)
    [Upward Pruned] 61 supersets removed from queue.
  [SHORT] [2, 3, 179, 2] -> Rank: 111/164 (Params: 901)
    [Downward Pruned] 211 subsets removed from queue.
  [FULL ] [2, 109, 18, 2] -> Rank: 164/164 (Params: 2216)
    [Upward Pruned] 131 supersets removed from queue.
  [FULL ] [2, 10, 57, 2] -> Rank: 164/164 (Params: 704)
    [Upward Pruned] 74 supersets removed from queue.
  [FULL ] [2, 298, 16, 2] -> Rank: 164/164 (Params: 5396)
    [Upward Pruned] 2 supersets removed from queue.
  [FULL ] [2, 32, 41, 2] -> Rank: 164/164 (Params: 1458)
    [Upward Pruned] 12 supersets removed from queue.
  [SHORT] [2, 3, 200, 2] -> Rank: 111/164 (Params: 1006)
    [Downward Pruned] 41 subsets removed from queue.
  [FULL ] [2, 6, 151, 2] -> Rank: 164/164 (Params: 1220)
    [Upward Pruned] 188 supersets removed from queue.
  [FULL ] [2, 5, 175, 2] -> Rank: 164/164 (Params: 1235)
    [Upward Pruned] 38 supersets removed from queue.
  [SHORT] [2, 276, 7, 2] -> Rank: 77/164 (Params: 2498)
    [Downward Pruned] 11 subsets removed from queue.
  [FULL ] [2, 275, 15, 2] -> Rank: 164/164 (Params: 4705)
    [Upward Pruned] 48 supersets removed from queue.
  [SHORT] [2, 285, 3, 2] -> Rank: 33/164 (Params: 1431)
    [Downward Pruned] 17 subsets removed from queue.
  [FULL ] [2, 5, 32, 2] -> Rank: 164/164 (Params: 234)
    [Upward Pruned] 951 supersets removed from queue.
  [FULL ] [2, 42, 26, 2] -> Rank: 164/164 (Params: 1228)
    [Upward Pruned] 54 supersets removed from queue.
  [FULL ] [2, 4, 114, 2] -> Rank: 164/164 (Params: 692)
    [Upward Pruned] 158 supersets removed from queue.
  [SHORT] [2, 299, 3, 2] -> Rank: 33/164 (Params: 1501)
    [Downward Pruned] 27 subsets removed from queue.
  [FULL ] [2, 19, 30, 2] -> Rank: 164/164 (Params: 668)
    [Upward Pruned] 45 supersets removed from queue.
  [SHORT] [2, 3, 232, 2] -> Rank: 111/164 (Params: 1166)
    [Downward Pruned] 63 subsets removed from queue.
  [FULL ] [2, 59, 25, 2] -> Rank: 164/164 (Params: 1643)
    [Upward Pruned] 22 supersets removed from queue.
  [SHORT] [2, 285, 4, 2] -> Rank: 44/164 (Params: 1718)
    [Downward Pruned] 8 subsets removed from queue.
  [FULL ] [2, 149, 15, 2] -> Rank: 164/164 (Params: 2563)
    [Upward Pruned] 277 supersets removed from queue.
  [FULL ] [2, 67, 24, 2] -> Rank: 164/164 (Params: 1790)
    [Upward Pruned] 14 supersets removed from queue.
  [SHORT] [2, 289, 8, 2] -> Rank: 88/164 (Params: 2906)
    [Downward Pruned] 57 subsets removed from queue.
  [FULL ] [2, 52, 21, 2] -> Rank: 164/164 (Params: 1238)
    [Upward Pruned] 111 supersets removed from queue.
  [SHORT] [2, 297, 12, 2] -> Rank: 132/164 (Params: 4182)
    [Downward Pruned] 131 subsets removed from queue.

In [180]:
# Display the minimal architectures found so far
print("\n=== CURRENT MINIMAL FILLING ARCHITECTURES IN DATABASE ===")
if not df_results.empty:
    minimal_archs = df_results[df_results['is_minimal'] == True]
    
    if not minimal_archs.empty:
        # Sort by parameters for easier reading
        minimal_archs = minimal_archs.sort_values(by="num_parameters")
        print(minimal_archs[["architecture", "num_parameters", "dimension_computed"]].to_string(index=False))
    else:
        print("No minimal full architectures found matching the criteria.")
else:
    print("Database is empty.")

=== CURRENT MINIMAL FILLING ARCHITECTURES IN DATABASE ===
 architecture  num_parameters  dimension_computed
    [2, 4, 2]              16                  12
 [2, 5, 8, 2]              66                  52
[2, 4, 10, 2]              68                  52

# Examining the Data Frame

In [181]:
# %load is_unimodal.py

import ast

def is_unimodal(data):
    # 1. Parse the string into a list safely
    if isinstance(data, str):
        try:
            # ast.literal_eval safely evaluates strings containing Python literals
            data = ast.literal_eval(data)
        except (ValueError, SyntaxError):
            raise ValueError(f"Could not parse the string: '{data}'. Ensure it is formatted like '[1, 2, 3]'.")
            
    # 2. Validate the data type
    if not isinstance(data, list):
        raise TypeError("Input must be a list or a string representation of a list.")
        
    # 3. Core unimodal logic
    n = len(data)
    if n <= 2:
        return True
        
    i = 0
    
    # Phase 1: Walk up the non-decreasing slope
    while i + 1 < n and data[i] <= data[i + 1]:
        i += 1
        
    # Phase 2: Walk down the non-increasing slope
    while i + 1 < n and data[i] >= data[i + 1]:
        i += 1
        
    # Phase 3: Check if we reached the end
    return i == n - 1

In [182]:
USER_DEPTH = 5
d0=3
dL=1
r=3

df = pd.read_csv(f'../data/raw/{d0}_{dL}_r{r}_architectures.csv')
df['is_unimodal'] = df['architecture'].apply(is_unimodal)
print("--"*15 + "DISCOVERED FILLING ARCHITECTURES" + "--"*15)
display(df[(df['h']==USER_DEPTH) & (df['is_full_dimension'] == True)])
print(len(df[(df['h']==USER_DEPTH) & (df['is_full_dimension'] == True)]))

df = pd.read_csv(f'../data/raw/{d0}_{dL}_r{r}_architectures.csv')
df['is_unimodal'] = df['architecture'].apply(is_unimodal)
print("--"*15 + "DISCOVERED POTENTIAL MINIMAL FILLING ARCHITECTURES" + "--"*15)
display(df[(df['h']==USER_DEPTH) & (df['is_minimal'] == True)])
print(len(df[(df['h']==USER_DEPTH) & (df['is_minimal'] == True)]))

df = pd.read_csv(f'../data/raw/{d0}_{dL}_r{r}_architectures.csv')
df['is_unimodal'] = df['architecture'].apply(is_unimodal)
print("--"*15 + "DISCOVERED POTENTIAL NONUNIMODAL MINIMAL FILLING ARCHITECTURES" + "--"*15)
display(df[(df['h']==USER_DEPTH) & (df['is_minimal'] == True) & (df['is_unimodal']==False)])
print(len(df[(df['h']==USER_DEPTH) & (df['is_minimal'] == True) & (df['is_unimodal']==False)]))

------------------------------DISCOVERED FILLING ARCHITECTURES------------------------------

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,is_unimodal
635,5,3,"[3, 21, 14, 55, 47, 1]",3759,3403,3403,True,False,False
637,5,3,"[3, 20, 47, 46, 50, 1]",5512,3403,3403,True,False,False
640,5,3,"[3, 11, 44, 55, 48, 1]",5625,3403,3403,True,False,True
641,5,3,"[3, 42, 41, 53, 30, 1]",5641,3403,3403,True,False,False
642,5,3,"[3, 21, 49, 55, 42, 1]",6139,3403,3403,True,False,True
...,...,...,...,...,...,...,...,...,...
12247,5,3,"[3, 6, 48, 53, 13, 1]",3552,3403,3403,True,True,True
12250,5,3,"[3, 8, 45, 33, 51, 1]",3603,3403,3403,True,True,False
12251,5,3,"[3, 8, 33, 47, 36, 1]",3567,3403,3403,True,True,True
12255,5,3,"[3, 6, 35, 46, 37, 1]",3577,3403,3403,True,True,True
12258,5,3,"[3, 9, 33, 45, 38, 1]",3557,3403,3403,True,True,True

5508
------------------------------DISCOVERED POTENTIAL MINIMAL FILLING ARCHITECTURES------------------------------

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,is_unimodal
1345,5,3,"[3, 8, 37, 42, 39, 1]",3551,3403,3403,True,True,True
1442,5,3,"[3, 9, 37, 51, 25, 1]",3547,3403,3403,True,True,True
1625,5,3,"[3, 7, 43, 35, 48, 1]",3555,3403,3403,True,True,False
1784,5,3,"[3, 9, 38, 50, 25, 1]",3544,3403,3403,True,True,True
1962,5,3,"[3, 8, 36, 41, 42, 1]",3552,3403,3403,True,True,True
...,...,...,...,...,...,...,...,...,...
12247,5,3,"[3, 6, 48, 53, 13, 1]",3552,3403,3403,True,True,True
12250,5,3,"[3, 8, 45, 33, 51, 1]",3603,3403,3403,True,True,False
12251,5,3,"[3, 8, 33, 47, 36, 1]",3567,3403,3403,True,True,True
12255,5,3,"[3, 6, 35, 46, 37, 1]",3577,3403,3403,True,True,True
12258,5,3,"[3, 9, 33, 45, 38, 1]",3557,3403,3403,True,True,True

1630
------------------------------DISCOVERED POTENTIAL NONUNIMODAL MINIMAL FILLING ARCHITECTURES------------------------------

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,is_unimodal
1625,5,3,"[3, 7, 43, 35, 48, 1]",3555,3403,3403,True,True,False
2575,5,3,"[3, 7, 45, 37, 42, 1]",3597,3403,3403,True,True,False
2963,5,3,"[3, 6, 47, 35, 45, 1]",3565,3403,3403,True,True,False
3027,5,3,"[3, 6, 46, 35, 47, 1]",3596,3403,3403,True,True,False
3097,5,3,"[3, 15, 42, 36, 44, 1]",3815,3403,3403,True,True,False
...,...,...,...,...,...,...,...,...,...
12198,5,3,"[3, 13, 9, 54, 54, 1]",3612,3403,3403,True,True,False
12215,5,3,"[3, 8, 39, 37, 47, 1]",3565,3403,3403,True,True,False
12231,5,3,"[3, 10, 44, 36, 41, 1]",3571,3403,3403,True,True,False
12239,5,3,"[3, 13, 37, 34, 55, 1]",3703,3403,3403,True,True,False
12250,5,3,"[3, 8, 45, 33, 51, 1]",3603,3403,3403,True,True,False

195