# Sequential CSV Dimension Fill — GPU Only, Windows-Safe Checkpoints

This notebook fills dimensions using **only** `dim_backprop_gpu_only.py` and its CuPy/CUDA finite-field Jacobian-rank computation.

The search is driven by the MFAs already recorded in each CSV:

1. Read rows whose `is_minimal` value is true.
2. Group those minimal filling architectures by depth `h` and exponent.
3. Build the finite rectangular search box whose coordinatewise upper corner is the coordinatewise maximum of those MFAs.
4. Process candidates from small to large.
5. For each candidate:
   - if it is a **strict coordinatewise predecessor of at least one recorded MFA**, compute its dimension unless a valid row already exists;
   - otherwise skip it without calling the dimension oracle.
6. Save new results through retrying, resumable checkpoints.

On Windows, Excel, OneDrive, antivirus software, or another Python process may temporarily lock the destination CSV. If replacement remains blocked after several retries, the notebook writes the complete current data to `NAME.locked_checkpoint.csv` and continues instead of losing the GPU run. A later run automatically resumes from that checkpoint when it is newer than the primary CSV.

## Configuration

Place this notebook, `dim_backprop_gpu_only.py`, and the `Data/` directory in the same project folder. The module loader also recognizes common alternate filenames, including the uploaded filename with `(2)` appended.

In [67]:
from pathlib import Path

# -----------------------------------------------------------------------------
# Paths
# -----------------------------------------------------------------------------
DATA_DIR = Path("Data")
FALLBACK_DATA_DIRS = [Path("data/raw"), Path("../data/raw")]

# None means every *_architectures.csv file in DATA_DIR.
# Example: CSV_FILES = [Path("Data/2_2_architectures.csv")]
CSV_FILES = None

# Set an explicit module path only when automatic discovery is undesirable.
GPU_MODULE_PATH = None
GPU_MODULE_FILENAMES = [
    "dim_backprop_gpu_only.py",
    "dim_back_prop_gpu_only.py",
    "dim_backprop_gpu_only(2).py",
]

# -----------------------------------------------------------------------------
# Search filters
# -----------------------------------------------------------------------------
# None means use every (h, exponent) group represented by an is_minimal=True row.
H_VALUES = None
EXPONENTS = None
DEFAULT_EXPONENT = 2

# Hidden widths begin at 1. A candidate must be strictly coordinatewise below
# at least one marked MFA before it is eligible for a dimension computation.
MIN_HIDDEN_WIDTH = 1

# The rectangular list can be inspected before running. Set a finite guard if desired.
MAX_SEARCH_BOX_SIZE = None

# -----------------------------------------------------------------------------
# GPU dimension oracle
# -----------------------------------------------------------------------------
PRIMES = (10_000_019, 19_511_957)
SEED = 20260630
RANK_WORKSPACE_BYTES = 512 * 1024**2
DIMENSION_VERBOSE = False

# -----------------------------------------------------------------------------
# Execution controls
# -----------------------------------------------------------------------------
RUN_FILL = True
MAX_NEW_EVALUATIONS_PER_FILE = None

# 1 preserves the old crash-safe behavior. Increasing this reduces CSV write overhead.
SAVE_EVERY_N_NEW_ROWS = 100
PROGRESS_EVERY = 100

# Windows may temporarily deny os.replace() when the target CSV is open in
# Excel, synchronized by OneDrive, scanned by antivirus, or used elsewhere.
SAVE_REPLACE_RETRIES = 8
SAVE_RETRY_DELAY_SECONDS = 1.0
SAVE_LOCKED_CHECKPOINT_SUFFIX = ".locked_checkpoint"
CONTINUE_WITH_LOCKED_CHECKPOINT = True

# A full-dimensional strict predecessor contradicts the recorded MFA flag.
# The row is saved first, then the notebook stops when this is True.
STOP_ON_MFA_CONTRADICTION = True

## Load the GPU-only dimension module

In [68]:
import ast
import importlib.util
import itertools
import math
import os
import sys
import time
import uuid
from collections import defaultdict
from typing import Iterable, Iterator, Sequence

import pandas as pd


def discover_gpu_module_path() -> Path:
    if GPU_MODULE_PATH is not None:
        path = Path(GPU_MODULE_PATH).expanduser().resolve()
        if not path.exists():
            raise FileNotFoundError(f"GPU_MODULE_PATH does not exist: {path}")
        return path

    roots = [Path.cwd(), Path.cwd().parent, Path("/mnt/data")]
    checked = []
    for root in roots:
        for filename in GPU_MODULE_FILENAMES:
            candidate = (root / filename).resolve()
            checked.append(candidate)
            if candidate.exists():
                return candidate

    checked_text = "\n".join(f"  - {path}" for path in checked)
    raise FileNotFoundError(
        "Could not find the GPU-only dimension module. Checked:\n" + checked_text
    )


def load_gpu_dimension_module(path: Path):
    module_name = "_mfa_dim_backprop_gpu_only"
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Could not create an import specification for {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


GPU_MODULE_FILE = discover_gpu_module_path()
gpu_dimension_module = load_gpu_dimension_module(GPU_MODULE_FILE)
compute_dimension = gpu_dimension_module.compute_dimension
gpu_information = gpu_dimension_module.gpu_information

print("GPU dimension module:", GPU_MODULE_FILE)
print("GPU information:", gpu_information())

GPU dimension module: C:\Users\daoke\Documents\GitHub\MFA_PNNs\notebooks\dim_backprop_gpu_only.py
GPU information: {'device_id': 0, 'name': 'NVIDIA GeForce RTX 4070 SUPER', 'device_count': 1, 'cupy_version': '14.1.1', 'cuda_runtime_version': 12090, 'driver_version': 12060}

## CSV and architecture helpers

In [69]:
def choose_data_dir() -> Path:
    if DATA_DIR.exists():
        return DATA_DIR
    for candidate in FALLBACK_DATA_DIRS:
        if candidate.exists():
            print(f"DATA_DIR={DATA_DIR!s} was not found. Using {candidate!s}.")
            return candidate
    return DATA_DIR


def find_csv_files(data_dir: Path) -> list[Path]:
    if CSV_FILES is not None:
        return [Path(path) for path in CSV_FILES]
    return sorted(data_dir.glob("*_architectures.csv"))



def locked_checkpoint_path(path: Path) -> Path:
    """Return the stable fallback path used when Windows locks the main CSV."""
    path = Path(path)
    return path.with_name(f"{path.stem}{SAVE_LOCKED_CHECKPOINT_SUFFIX}{path.suffix}")


def preferred_csv_source(path: Path) -> Path:
    """Prefer a newer locked-file checkpoint so interrupted runs resume safely."""
    path = Path(path)
    checkpoint = locked_checkpoint_path(path)

    if checkpoint.exists() and (
        not path.exists() or checkpoint.stat().st_mtime_ns > path.stat().st_mtime_ns
    ):
        print(
            f"Resuming from newer checkpoint {checkpoint.name!r} because "
            f"{path.name!r} was previously locked."
        )
        return checkpoint

    return path


def read_architecture_csv(path: Path) -> pd.DataFrame:
    source = preferred_csv_source(path)
    if source.exists():
        try:
            df = pd.read_csv(source)
        except Exception:
            # Compatibility with older processed files containing a preamble line.
            df = pd.read_csv(source, skiprows=1)
    else:
        df = pd.DataFrame()

    required_columns = [
        "h",
        "exponent",
        "architecture",
        "num_parameters",
        "dimension_computed",
        "ambient_dimension",
        "is_full_dimension",
        "is_minimal",
    ]
    audit_columns = [
        "expected_dimension",
        "defect_expected",
        "defect_ambient",
        "backend",
        "primes",
        "elapsed_seconds",
        "status",
        "covered_by_mfa",
    ]
    for column in required_columns + audit_columns:
        if column not in df.columns:
            df[column] = pd.Series(dtype="object")
    return df

def parse_architecture(value) -> tuple[int, ...]:
    if isinstance(value, (tuple, list)):
        architecture = tuple(int(x) for x in value)
    else:
        if pd.isna(value):
            raise ValueError("missing architecture")
        architecture = tuple(int(x) for x in ast.literal_eval(str(value)))
    if len(architecture) < 2 or any(width <= 0 for width in architecture):
        raise ValueError(f"invalid architecture: {architecture}")
    return architecture


def architecture_string(architecture: Sequence[int]) -> str:
    return str([int(width) for width in architecture])


def truthy(value) -> bool:
    if isinstance(value, bool):
        return value
    if pd.isna(value):
        return False
    return str(value).strip().lower() in {"true", "1", "yes", "y", "t"}


def infer_d0_dL_from_filename(path: Path) -> tuple[int, int]:
    parts = path.stem.split("_")
    if len(parts) >= 3 and parts[-1] == "architectures":
        return int(parts[0]), int(parts[1])
    raise ValueError(
        f"Could not infer d0 and dL from {path.name!r}; expected a name such as "
        "2_1_architectures.csv."
    )


def parameter_count(architecture: Sequence[int]) -> int:
    return sum(
        int(input_width) * int(output_width)
        for input_width, output_width in zip(architecture[:-1], architecture[1:])
    )


def hidden_leq(left: Sequence[int], right: Sequence[int]) -> bool:
    return len(left) == len(right) and all(int(a) <= int(b) for a, b in zip(left, right))


def full_architecture(d0: int, hidden: Sequence[int], dL: int) -> tuple[int, ...]:
    return (int(d0), *(int(width) for width in hidden), int(dL))


def stable_seed(
    base_seed: int,
    hidden: Sequence[int],
    h: int,
    d0: int,
    dL: int,
    exponent: int,
) -> int:
    value = (
        int(base_seed)
        + 99_991 * int(h)
        + 101 * int(d0)
        + 103 * int(dL)
        + 107 * int(exponent)
    )
    for index, width in enumerate(hidden):
        value += (index + 1) * 1_000_003 * int(width)
    return value % (2**31 - 1)


def valid_dimension_row(row) -> bool:
    try:
        parse_architecture(row["architecture"])
        dimension = row.get("dimension_computed")
        ambient = row.get("ambient_dimension")
        if pd.isna(dimension) or pd.isna(ambient):
            return False
        int(dimension)
        int(ambient)
        return True
    except Exception:
        return False


def architecture_exponent_key(
    architecture: Sequence[int] | str,
    exponent: int,
) -> tuple[str, int]:
    if isinstance(architecture, str):
        architecture_key = architecture_string(parse_architecture(architecture))
    else:
        architecture_key = architecture_string(architecture)
    return architecture_key, int(exponent)


def existing_rows_by_key(df: pd.DataFrame) -> dict[tuple[str, int], int]:
    index_by_key: dict[tuple[str, int], int] = {}
    for index, row in df.iterrows():
        try:
            exponent_value = row.get("exponent")
            exponent = DEFAULT_EXPONENT if pd.isna(exponent_value) else int(exponent_value)
            key = architecture_exponent_key(
                parse_architecture(row["architecture"]),
                exponent,
            )
            index_by_key[key] = index
        except Exception:
            continue
    return index_by_key



def save_csv(df: pd.DataFrame, path: Path) -> Path:
    """Save atomically when possible and survive Windows destination locks.

    Returns the path that actually received the complete CSV. Normally this is
    ``path``. If Windows keeps the destination locked, it is the stable
    ``*.locked_checkpoint.csv`` fallback instead.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    checkpoint = locked_checkpoint_path(path)
    temporary = path.with_name(
        f".{path.name}.{os.getpid()}.{uuid.uuid4().hex}.tmp"
    )

    try:
        # Write a complete independent file before touching the existing CSV.
        df.to_csv(temporary, index=False)

        last_permission_error = None
        retries = max(1, int(SAVE_REPLACE_RETRIES))
        for attempt in range(1, retries + 1):
            try:
                os.replace(temporary, path)

                # A successful primary save supersedes any stale fallback.
                if checkpoint.exists():
                    try:
                        checkpoint.unlink()
                    except OSError:
                        pass
                return path

            except PermissionError as exc:
                last_permission_error = exc
                if attempt < retries:
                    print(
                        f"CSV is locked: {path}. Retrying save "
                        f"({attempt}/{retries}) ...",
                        flush=True,
                    )
                    time.sleep(max(0.0, float(SAVE_RETRY_DELAY_SECONDS)))

        if not CONTINUE_WITH_LOCKED_CHECKPOINT:
            raise last_permission_error

        # Keep one predictable latest checkpoint. If that checkpoint is itself
        # open, use a unique recovery name rather than losing the in-memory rows.
        try:
            os.replace(temporary, checkpoint)
            recovery_path = checkpoint
        except PermissionError:
            timestamp = time.strftime("%Y%m%d_%H%M%S")
            recovery_path = path.with_name(
                f"{path.stem}.locked_checkpoint_{timestamp}_{uuid.uuid4().hex[:8]}"
                f"{path.suffix}"
            )
            os.replace(temporary, recovery_path)

        print(
            "WARNING: Windows would not allow replacement of the primary CSV. "
            f"The complete current data was saved to:\n  {recovery_path}\n"
            "Close the primary CSV in Excel or any other program. A later "
            "checkpoint will automatically restore normal saving when the lock "
            "is released.",
            flush=True,
        )
        return recovery_path

    finally:
        # Remove only a leftover temporary file; never remove a recovery file.
        if temporary.exists():
            try:
                temporary.unlink()
            except OSError:
                pass

## Read the recorded MFAs and build the candidate list

Only rows already marked `is_minimal=True` define the search. The notebook does not discover or update the MFA list while it runs.

In [70]:
def selected(value: int, allowed: Sequence[int] | None) -> bool:
    return allowed is None or int(value) in {int(x) for x in allowed}


def recorded_mfa_groups(
    df: pd.DataFrame,
    d0: int,
    dL: int,
) -> dict[tuple[int, int], list[tuple[int, ...]]]:
    """Return {(h, exponent): [hidden MFA tuples]} from is_minimal=True rows."""
    groups: dict[tuple[int, int], list[tuple[int, ...]]] = defaultdict(list)

    for index, row in df.iterrows():
        if not truthy(row.get("is_minimal")):
            continue

        architecture = parse_architecture(row["architecture"])
        if architecture[0] != d0 or architecture[-1] != dL:
            raise ValueError(
                f"Row {index} is marked minimal but has endpoints {architecture[0], architecture[-1]}, "
                f"whereas {d0, dL} were inferred from the filename."
            )

        h = len(architecture) - 1
        if not pd.isna(row.get("h")) and int(row["h"]) != h:
            raise ValueError(
                f"Row {index} has h={row['h']} but architecture {architecture} has h={h}."
            )

        exponent_value = row.get("exponent")
        exponent = DEFAULT_EXPONENT if pd.isna(exponent_value) else int(exponent_value)
        if not selected(h, H_VALUES) or not selected(exponent, EXPONENTS):
            continue

        if not truthy(row.get("is_full_dimension")):
            print(
                f"Warning: row {index} is marked is_minimal=True but is_full_dimension is not true. "
                "It will still be used because is_minimal is the requested source of truth."
            )

        groups[(h, exponent)].append(tuple(architecture[1:-1]))

    cleaned: dict[tuple[int, int], list[tuple[int, ...]]] = {}
    for key, hidden_values in groups.items():
        unique = sorted(set(hidden_values))

        # Recorded MFAs should form an antichain. Equality was removed above.
        for i, left in enumerate(unique):
            for j, right in enumerate(unique):
                if i != j and hidden_leq(left, right):
                    raise ValueError(
                        f"The is_minimal rows for group {key} are not an antichain: "
                        f"{left} <= {right}. Fix the CSV flags before running."
                    )
        cleaned[key] = unique

    return dict(sorted(cleaned.items()))


def coordinatewise_mfa_maxima(mfas: Sequence[Sequence[int]]) -> tuple[int, ...]:
    if not mfas:
        raise ValueError("at least one MFA is required")
    hidden_length = len(mfas[0])
    if any(len(mfa) != hidden_length for mfa in mfas):
        raise ValueError("all MFAs in a group must have the same number of hidden layers")
    return tuple(max(int(mfa[i]) for mfa in mfas) for i in range(hidden_length))


def is_strict_predecessor_of_some_mfa(
    hidden: Sequence[int],
    mfas: Sequence[Sequence[int]],
) -> bool:
    hidden_tuple = tuple(int(width) for width in hidden)
    return any(
        hidden_tuple != tuple(int(width) for width in mfa)
        and hidden_leq(hidden_tuple, mfa)
        for mfa in mfas
    )


def covering_mfas(
    hidden: Sequence[int],
    mfas: Sequence[Sequence[int]],
) -> list[tuple[int, ...]]:
    hidden_tuple = tuple(int(width) for width in hidden)
    return [
        tuple(int(width) for width in mfa)
        for mfa in mfas
        if hidden_tuple != tuple(int(width) for width in mfa)
        and hidden_leq(hidden_tuple, mfa)
    ]


def candidate_priority(hidden: tuple[int, ...], d0: int, dL: int) -> tuple:
    architecture = full_architecture(d0, hidden, dL)
    return (parameter_count(architecture), sum(hidden), max(hidden), hidden)


def enumerate_search_box(
    mfas: Sequence[Sequence[int]],
    d0: int,
    dL: int,
) -> tuple[list[tuple[int, ...]], tuple[int, ...]]:
    """Materialize and sort the MFA-determined rectangular search box."""
    maxima = coordinatewise_mfa_maxima(mfas)
    if any(maximum < MIN_HIDDEN_WIDTH for maximum in maxima):
        raise ValueError(f"MFA maxima {maxima} lie below MIN_HIDDEN_WIDTH={MIN_HIDDEN_WIDTH}")

    box_size = math.prod(maximum - MIN_HIDDEN_WIDTH + 1 for maximum in maxima)
    if MAX_SEARCH_BOX_SIZE is not None and box_size > int(MAX_SEARCH_BOX_SIZE):
        raise RuntimeError(
            f"The MFA-determined search box contains {box_size:,} candidates, exceeding "
            f"MAX_SEARCH_BOX_SIZE={int(MAX_SEARCH_BOX_SIZE):,}."
        )

    ranges = [range(MIN_HIDDEN_WIDTH, maximum + 1) for maximum in maxima]
    candidates = [tuple(values) for values in itertools.product(*ranges)]
    candidates.sort(key=lambda hidden: candidate_priority(hidden, d0, dL))
    return candidates, maxima

## GPU evaluation and CSV updates

In [71]:
def record_for_architecture(
    architecture: Sequence[int],
    exponent: int,
    seed: int,
    covering: Sequence[Sequence[int]],
) -> dict:
    start = time.perf_counter()
    result = compute_dimension(
        architecture,
        exponent,
        primes=PRIMES,
        seed=seed,
        rank_workspace_bytes=RANK_WORKSPACE_BYTES,
        verbose=DIMENSION_VERBOSE,
    )
    elapsed = time.perf_counter() - start

    sizes, returned_exponent, ambient, expected, dimension, expected_defect = result
    if tuple(int(width) for width in sizes) != tuple(int(width) for width in architecture):
        raise RuntimeError(f"Dimension module returned unexpected architecture {sizes}")
    if int(returned_exponent) != int(exponent):
        raise RuntimeError(f"Dimension module returned unexpected exponent {returned_exponent}")

    is_full = int(dimension) == int(ambient)
    return {
        "h": len(architecture) - 1,
        "exponent": int(exponent),
        "architecture": architecture_string(architecture),
        "num_parameters": parameter_count(architecture),
        "dimension_computed": int(dimension),
        "ambient_dimension": int(ambient),
        "is_full_dimension": bool(is_full),
        # The notebook never promotes new rows into the recorded MFA list.
        "is_minimal": False,
        "expected_dimension": int(expected),
        "defect_expected": int(expected_defect),
        "defect_ambient": int(ambient) - int(dimension),
        "backend": "dim_backprop_gpu_only/CuPy-CUDA",
        "primes": str(tuple(int(prime) for prime in PRIMES)),
        "elapsed_seconds": elapsed,
        "status": "filling_below_recorded_mfa" if is_full else "nonfilling",
        "covered_by_mfa": str([list(map(int, mfa)) for mfa in covering]),
    }


def append_or_update_row(
    df: pd.DataFrame,
    record: dict,
    index_by_key: dict[tuple[str, int], int],
) -> tuple[pd.DataFrame, dict[tuple[str, int], int]]:
    row_key = architecture_exponent_key(record["architecture"], record["exponent"])

    for column in record:
        if column not in df.columns:
            df[column] = pd.Series(dtype="object")

    if row_key in index_by_key:
        index = index_by_key[row_key]
        for column, value in record.items():
            df.at[index, column] = value
    else:
        index = len(df)
        df.loc[index, list(record.keys())] = list(record.values())
        index_by_key[row_key] = index

    return df, index_by_key


def fill_one_csv_file(
    path: Path,
    *,
    max_new_evaluations: int | None = None,
) -> dict:
    print("=" * 100)
    print(f"Processing {path}")
    print("=" * 100)

    df = read_architecture_csv(path)
    d0, dL = infer_d0_dL_from_filename(path)
    groups = recorded_mfa_groups(df, d0, dL)
    index_by_key = existing_rows_by_key(df)

    if not groups:
        print("No selected is_minimal=True rows were found. Nothing to evaluate.")
        return {
            "path": str(path),
            "new_evaluations": 0,
            "existing_rows": 0,
            "skipped_not_below_mfa": 0,
            "groups": [],
        }

    total_new = 0
    total_existing = 0
    total_skipped_not_below = 0
    total_marked_mfas = 0
    group_summaries = []
    unsaved_new = 0

    for (h, exponent), mfas in groups.items():
        candidates, maxima = enumerate_search_box(mfas, d0, dL)
        print(f"\nGroup h={h}, exponent={exponent}")
        print("Recorded MFA hidden tuples:", mfas)
        print("Coordinatewise search-box maximum:", maxima)
        print(f"Enumerated candidates: {len(candidates):,}")

        group_new = 0
        group_existing = 0
        group_skipped = 0
        group_marked_mfas = 0
        group_eligible = 0
        group_start = time.perf_counter()
        mfa_set = set(mfas)

        for position, hidden in enumerate(candidates, start=1):
            if max_new_evaluations is not None and total_new >= int(max_new_evaluations):
                print(
                    f"Stopping {path.name} after "
                    f"max_new_evaluations={int(max_new_evaluations)}."
                )
                break

            architecture = full_architecture(d0, hidden, dL)
            row_key = architecture_exponent_key(architecture, exponent)

            # The recorded MFA rows themselves are boundary data, not targets.
            if hidden in mfa_set:
                group_marked_mfas += 1
                total_marked_mfas += 1
                continue

            # Requested fast gate: evaluate only when the candidate is below an MFA.
            covering = covering_mfas(hidden, mfas)
            if not covering:
                group_skipped += 1
                total_skipped_not_below += 1
                continue

            group_eligible += 1

            if row_key in index_by_key:
                row = df.loc[index_by_key[row_key]]
                if valid_dimension_row(row):
                    group_existing += 1
                    total_existing += 1
                    continue

            seed = stable_seed(SEED, hidden, h, d0, dL, exponent)
            print(
                f"[{position:,}/{len(candidates):,}] Evaluating {architecture} "
                f"below {len(covering)} MFA(s) ...",
                flush=True,
            )
            record = record_for_architecture(architecture, exponent, seed, covering)
            print(
                f"  {record['status'].upper()} | "
                f"dim={record['dimension_computed']}/{record['ambient_dimension']} | "
                f"params={record['num_parameters']} | "
                f"elapsed={record['elapsed_seconds']:.2f}s"
            )

            df, index_by_key = append_or_update_row(
                df,
                record,
                index_by_key,
            )
            group_new += 1
            total_new += 1
            unsaved_new += 1

            should_checkpoint = (
                SAVE_EVERY_N_NEW_ROWS is not None
                and int(SAVE_EVERY_N_NEW_ROWS) > 0
                and unsaved_new >= int(SAVE_EVERY_N_NEW_ROWS)
            )
            if should_checkpoint:
                save_csv(df, path)
                unsaved_new = 0

            if record["is_full_dimension"]:
                # Save before stopping: the contradiction is useful diagnostic data.
                save_csv(df, path)
                unsaved_new = 0
                message = (
                    f"Architecture {architecture} is a strict predecessor of recorded MFA(s) "
                    f"{covering}, but the GPU computation found full ambient dimension. "
                    "The CSV's is_minimal flags are inconsistent with this result."
                )
                if STOP_ON_MFA_CONTRADICTION:
                    raise RuntimeError(message)
                print("WARNING:", message)

            if PROGRESS_EVERY and group_new % int(PROGRESS_EVERY) == 0:
                elapsed = time.perf_counter() - group_start
                print(
                    f"Progress h={h}, exponent={exponent}: new={group_new}, "
                    f"existing={group_existing}, skipped={group_skipped}, "
                    f"elapsed={elapsed:.1f}s"
                )

        if unsaved_new:
            save_csv(df, path)
            unsaved_new = 0

        elapsed = time.perf_counter() - group_start
        summary = {
            "h": h,
            "exponent": exponent,
            "mfas": list(mfas),
            "search_box_maxima": maxima,
            "enumerated": len(candidates),
            "eligible_below_mfa": group_eligible,
            "new_evaluations": group_new,
            "existing_rows": group_existing,
            "marked_mfas_skipped": group_marked_mfas,
            "not_below_any_mfa_skipped": group_skipped,
            "elapsed_seconds": elapsed,
        }
        group_summaries.append(summary)
        print(
            f"Finished h={h}, exponent={exponent}: eligible={group_eligible}, "
            f"new={group_new}, existing={group_existing}, "
            f"MFA rows={group_marked_mfas}, not-below skips={group_skipped}, "
            f"elapsed={elapsed:.1f}s"
        )

        if max_new_evaluations is not None and total_new >= int(max_new_evaluations):
            break

    save_csv(df, path)
    return {
        "path": str(path),
        "d0": d0,
        "dL": dL,
        "new_evaluations": total_new,
        "existing_rows": total_existing,
        "marked_mfas_skipped": total_marked_mfas,
        "skipped_not_below_mfa": total_skipped_not_below,
        "groups": group_summaries,
    }

## Inspect the planned files and MFA-derived search sizes

In [72]:
data_dir = choose_data_dir()
csv_paths = find_csv_files(data_dir)

print("Data directory:", data_dir.resolve())
print("CSV files:")
for path in csv_paths:
    print(" -", path)

if not csv_paths:
    raise FileNotFoundError(
        f"No *_architectures.csv files found in {data_dir!s}. "
        "Set DATA_DIR or CSV_FILES in the configuration cell."
    )

plan_rows = []
for path in csv_paths:
    df = read_architecture_csv(path)
    d0, dL = infer_d0_dL_from_filename(path)
    groups = recorded_mfa_groups(df, d0, dL)
    for (h, exponent), mfas in groups.items():
        maxima = coordinatewise_mfa_maxima(mfas)
        box_size = math.prod(maximum - MIN_HIDDEN_WIDTH + 1 for maximum in maxima)
        plan_rows.append({
            "file": str(path),
            "h": h,
            "exponent": exponent,
            "number_of_mfas": len(mfas),
            "mfas": mfas,
            "box_maxima": maxima,
            "box_size": box_size,
        })

plan_df = pd.DataFrame(plan_rows)
display(plan_df)

DATA_DIR=Data was not found. Using ..\data\raw.
Data directory: C:\Users\daoke\Documents\GitHub\MFA_PNNs\data\raw
CSV files:
 - ..\data\raw\2_1_r12_architectures.csv
 - ..\data\raw\2_1_r2_architectures.csv
 - ..\data\raw\2_1_r3_architectures.csv
 - ..\data\raw\2_1_r4_architectures.csv
 - ..\data\raw\2_1_r5_architectures.csv
 - ..\data\raw\2_1_r6_architectures.csv
 - ..\data\raw\2_1_r7_architectures.csv
 - ..\data\raw\2_1_r8_architectures.csv
 - ..\data\raw\2_2_r2_architectures.csv
 - ..\data\raw\2_2_r3_architectures.csv
 - ..\data\raw\2_3_r2_architectures.csv
 - ..\data\raw\3_1_r2_architectures.csv
 - ..\data\raw\3_1_r3_architectures.csv
 - ..\data\raw\3_2_r3_architectures.csv
 - ..\data\raw\3_3_r3_architectures.csv
 - ..\data\raw\3_3_r6_architectures.csv
 - ..\data\raw\3_4_r3_architectures.csv
 - ..\data\raw\4_1_r2_architectures.csv
 - ..\data\raw\4_1_r3_architectures.csv
 - ..\data\raw\5_1_r2_architectures.csv
 - ..\data\raw\5_1_r3_architectures.csv
 - ..\data\raw\6_1_r3_architectures.csv
 - ..\data\raw\7_1_r3_architectures.csv
 - ..\data\raw\8_1_r2_architectures.csv
 - ..\data\raw\8_1_r3_architectures.csv

,file,h,exponent,number_of_mfas,mfas,box_maxima,box_size
0,..\data\raw\2_1_r12_architectures.csv,3,12,7,"[(6, 24), (7, 20), (8, 18), (9, 16), (10, 14),...","(12, 24)",288
1,..\data\raw\2_1_r2_architectures.csv,2,2,1,"[(2,)]","(2,)",2
2,..\data\raw\2_1_r2_architectures.csv,3,2,1,"[(2, 2)]","(2, 2)",4
3,..\data\raw\2_1_r2_architectures.csv,4,2,1,"[(3, 3, 2)]","(3, 3, 2)",18
4,..\data\raw\2_1_r2_architectures.csv,5,2,1,"[(3, 3, 3, 2)]","(3, 3, 3, 2)",54
...,...,...,...,...,...,...,...
82,..\data\raw\7_1_r3_architectures.csv,3,3,39,"[(33, 146), (34, 144), (35, 137), (37, 130), (...","(76, 146)",11096
83,..\data\raw\8_1_r2_architectures.csv,2,2,1,"[(8,)]","(8,)",8
84,..\data\raw\8_1_r2_architectures.csv,3,2,3,"[(20, 15), (21, 12), (22, 11)]","(22, 15)",330
85,..\data\raw\8_1_r2_architectures.csv,4,2,1,"[(136, 111, 139)]","(136, 111, 139)",2098344
86,..\data\raw\8_1_r3_architectures.csv,2,3,1,"[(15,)]","(15,)",15

## Run the sequential fill

The notebook checkpoints to the same CSV. Rerunning it skips every architecture whose row already contains a valid computed and ambient dimension.

### Select Particular CSV_Files

In [73]:
# csv_paths=csv_paths[15:]
csv_paths

[WindowsPath('../data/raw/2_1_r12_architectures.csv'),
 WindowsPath('../data/raw/2_1_r2_architectures.csv'),
 WindowsPath('../data/raw/2_1_r3_architectures.csv'),
 WindowsPath('../data/raw/2_1_r4_architectures.csv'),
 WindowsPath('../data/raw/2_1_r5_architectures.csv'),
 WindowsPath('../data/raw/2_1_r6_architectures.csv'),
 WindowsPath('../data/raw/2_1_r7_architectures.csv'),
 WindowsPath('../data/raw/2_1_r8_architectures.csv'),
 WindowsPath('../data/raw/2_2_r2_architectures.csv'),
 WindowsPath('../data/raw/2_2_r3_architectures.csv'),
 WindowsPath('../data/raw/2_3_r2_architectures.csv'),
 WindowsPath('../data/raw/3_1_r2_architectures.csv'),
 WindowsPath('../data/raw/3_1_r3_architectures.csv'),
 WindowsPath('../data/raw/3_2_r3_architectures.csv'),
 WindowsPath('../data/raw/3_3_r3_architectures.csv'),
 WindowsPath('../data/raw/3_3_r6_architectures.csv'),
 WindowsPath('../data/raw/3_4_r3_architectures.csv'),
 WindowsPath('../data/raw/4_1_r2_architectures.csv'),
 WindowsPath('../data/raw/4_1_r3_architectures.csv'),
 WindowsPath('../data/raw/5_1_r2_architectures.csv'),
 WindowsPath('../data/raw/5_1_r3_architectures.csv'),
 WindowsPath('../data/raw/6_1_r3_architectures.csv'),
 WindowsPath('../data/raw/7_1_r3_architectures.csv'),
 WindowsPath('../data/raw/8_1_r2_architectures.csv'),
 WindowsPath('../data/raw/8_1_r3_architectures.csv')]

In [74]:
all_summaries = []

if RUN_FILL:
    for csv_path in csv_paths:
        summary = fill_one_csv_file(
            csv_path,
            max_new_evaluations=MAX_NEW_EVALUATIONS_PER_FILE,
        )
        all_summaries.append(summary)
    print("\nAll requested CSV files are complete for the selected MFA predecessor boxes.")
else:
    print("RUN_FILL is False. Review plan_df, then set RUN_FILL=True to begin.")

all_summaries

====================================================================================================
Processing ..\data\raw\2_1_r12_architectures.csv
====================================================================================================

Group h=3, exponent=12
Recorded MFA hidden tuples: [(6, 24), (7, 20), (8, 18), (9, 16), (10, 14), (11, 13), (12, 12)]
Coordinatewise search-box maximum: (12, 24)
Enumerated candidates: 288
Finished h=3, exponent=12: eligible=230, new=0, existing=230, MFA rows=7, not-below skips=51, elapsed=0.0s
====================================================================================================
Processing ..\data\raw\2_1_r2_architectures.csv
====================================================================================================

Group h=2, exponent=2
Recorded MFA hidden tuples: [(2,)]
Coordinatewise search-box maximum: (2,)
Enumerated candidates: 2
Finished h=2, exponent=2: eligible=1, new=0, existing=1, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=3, exponent=2
Recorded MFA hidden tuples: [(2, 2)]
Coordinatewise search-box maximum: (2, 2)
Enumerated candidates: 4
Finished h=3, exponent=2: eligible=3, new=0, existing=3, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=4, exponent=2
Recorded MFA hidden tuples: [(3, 3, 2)]
Coordinatewise search-box maximum: (3, 3, 2)
Enumerated candidates: 18
Finished h=4, exponent=2: eligible=17, new=0, existing=17, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=5, exponent=2
Recorded MFA hidden tuples: [(3, 3, 3, 2)]
Coordinatewise search-box maximum: (3, 3, 3, 2)
Enumerated candidates: 54
Finished h=5, exponent=2: eligible=53, new=0, existing=53, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=6, exponent=2
Recorded MFA hidden tuples: [(3, 3, 4, 4, 2)]
Coordinatewise search-box maximum: (3, 3, 4, 4, 2)
Enumerated candidates: 288
Finished h=6, exponent=2: eligible=287, new=0, existing=287, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=7, exponent=2
Recorded MFA hidden tuples: [(3, 3, 4, 5, 6, 3), (3, 3, 4, 6, 5, 2), (3, 3, 5, 5, 5, 4), (3, 3, 5, 6, 4, 4), (3, 3, 5, 7, 4, 2), (3, 3, 6, 6, 4, 3), (3, 4, 4, 5, 5, 4), (3, 4, 5, 4, 6, 4), (3, 4, 5, 5, 4, 4), (3, 4, 5, 5, 5, 2), (3, 4, 5, 6, 4, 2), (3, 4, 6, 5, 4, 3), (3, 5, 5, 5, 4, 3)]
Coordinatewise search-box maximum: (3, 5, 6, 7, 6, 4)
Enumerated candidates: 15,120

KeyboardInterrupt:

## Post-run summary

In [75]:
for path in csv_paths:
    df = read_architecture_csv(path)
    print("=" * 100)
    print(path)
    print("rows:", len(df))
    print("is_full_dimension counts:")
    print(df["is_full_dimension"].value_counts(dropna=False))
    print("status counts:")
    print(df["status"].value_counts(dropna=False).head(20))

    marked = df[df["is_minimal"].map(truthy)]
    print("Recorded MFAs:")
    display(
        marked[
            [
                "h",
                "exponent",
                "architecture",
                "dimension_computed",
                "ambient_dimension",
                "num_parameters",
            ]
        ]
    )

====================================================================================================
..\data\raw\2_1_r12_architectures.csv
rows: 257
is_full_dimension counts:
is_full_dimension
False    237
True      20
Name: count, dtype: int64
status counts:
status
nonfilling    218
NaN            39
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
8,3.0,12.0,"[2, 10, 14, 1]",145.0,145.0,174.0
20,3.0,12.0,"[2, 6, 24, 1]",145.0,145.0,180.0
31,3.0,12.0,"[2, 11, 13, 1]",145.0,145.0,178.0
33,3.0,12.0,"[2, 8, 18, 1]",145.0,145.0,178.0
34,3.0,12.0,"[2, 12, 12, 1]",145.0,145.0,180.0
36,3.0,12.0,"[2, 9, 16, 1]",145.0,145.0,178.0
38,3.0,12.0,"[2, 7, 20, 1]",145.0,145.0,174.0

====================================================================================================
..\data\raw\2_1_r2_architectures.csv
rows: 40914
is_full_dimension counts:
is_full_dimension
False    39522
True      1392
Name: count, dtype: int64
status counts:
status
nonfilling    30859
NaN           10055
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2.0,2.0,"[2, 2, 1]",3.0,3.0,6.0
9,3.0,2.0,"[2, 2, 2, 1]",5.0,5.0,10.0
53,4.0,2.0,"[2, 3, 3, 2, 1]",9.0,9.0,23.0
275,5.0,2.0,"[2, 3, 3, 3, 2, 1]",17.0,17.0,32.0
1169,6.0,2.0,"[2, 3, 3, 4, 4, 2, 1]",33.0,33.0,53.0
...,...,...,...,...,...,...
5209,8.0,2.0,"[2, 3, 4, 5, 5, 5, 9, 6, 1]",129.0,129.0,193.0
5354,8.0,2.0,"[2, 3, 3, 6, 6, 6, 7, 7, 1]",129.0,129.0,203.0
5355,8.0,2.0,"[2, 3, 4, 6, 6, 5, 7, 7, 1]",129.0,129.0,199.0
5641,8.0,2.0,"[2, 3, 3, 6, 6, 5, 8, 8, 1]",129.0,129.0,211.0
5646,8.0,2.0,"[2, 3, 4, 4, 7, 5, 8, 8, 1]",129.0,129.0,209.0

====================================================================================================
..\data\raw\2_1_r3_architectures.csv
rows: 229
is_full_dimension counts:
is_full_dimension
True     169
False     60
Name: count, dtype: int64
status counts:
status
NaN    229
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
0,3,3,"[2, 3, 3, 1]",10,10,18
1,2,3,"[2, 2, 1]",4,4,6
2,4,3,"[2, 3, 5, 3, 1]",28,28,39
3,4,3,"[2, 4, 4, 4, 1]",28,28,44
4,4,3,"[2, 3, 4, 5, 1]",28,28,43
...,...,...,...,...,...,...
213,6,3,"[2, 3, 7, 12, 9, 7, 1]",244,244,289
216,6,3,"[2, 3, 8, 12, 9, 6, 1]",244,244,294
221,6,3,"[2, 4, 7, 12, 9, 6, 1]",244,244,288
224,6,3,"[2, 4, 8, 12, 9, 5, 1]",244,244,294
225,6,3,"[2, 4, 9, 12, 10, 3, 1]",244,244,305

====================================================================================================
..\data\raw\2_1_r4_architectures.csv
rows: 3293
is_full_dimension counts:
is_full_dimension
False    2145
True     1148
Name: count, dtype: int64
status counts:
status
NaN    3293
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,4,"[2, 3, 1]",5,5,9
24,3,4,"[2, 3, 5, 1]",17,17,26
25,3,4,"[2, 4, 4, 1]",17,17,28
37,4,4,"[2, 3, 8, 6, 1]",65,65,84
82,4,4,"[2, 4, 9, 4, 1]",65,65,84
...,...,...,...,...,...,...
3264,5,4,"[2, 3, 6, 25, 5, 1]",257,257,304
3276,5,4,"[2, 4, 9, 7, 25, 1]",257,257,307
3280,5,4,"[2, 4, 6, 24, 5, 1]",257,257,301
3289,5,4,"[2, 3, 10, 7, 25, 1]",257,257,306
3291,5,4,"[2, 3, 5, 25, 6, 1]",257,257,302

====================================================================================================
..\data\raw\2_1_r5_architectures.csv
rows: 9044
is_full_dimension counts:
is_full_dimension
False    8514
True      530
Name: count, dtype: int64
status counts:
status
nonfilling    7926
NaN           1118
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2.0,5.0,"[2, 3, 1]",6.0,6.0,9.0
20,3.0,5.0,"[2, 4, 6, 1]",26.0,26.0,38.0
24,3.0,5.0,"[2, 5, 5, 1]",26.0,26.0,40.0
130,4.0,5.0,"[2, 4, 12, 8, 1]",126.0,126.0,160.0
131,4.0,5.0,"[2, 4, 6, 18, 1]",126.0,126.0,158.0
...,...,...,...,...,...,...
1108,5.0,5.0,"[2, 16, 18, 22, 12, 1]",626.0,626.0,992.0
1110,5.0,5.0,"[2, 33, 16, 19, 17, 1]",626.0,626.0,1238.0
1113,5.0,5.0,"[2, 11, 12, 17, 35, 1]",626.0,626.0,988.0
1114,5.0,5.0,"[2, 30, 13, 16, 25, 1]",626.0,626.0,1083.0
1116,5.0,5.0,"[2, 28, 29, 22, 5, 1]",626.0,626.0,1621.0

====================================================================================================
..\data\raw\2_1_r6_architectures.csv
rows: 842
is_full_dimension counts:
is_full_dimension
False    591
True     251
Name: count, dtype: int64
status counts:
status
NaN    842
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
51,4,6,"[2, 4, 12, 15, 1]",217,217,251
79,4,6,"[2, 5, 11, 16, 1]",217,217,257
125,4,6,"[2, 5, 12, 14, 1]",217,217,252
127,4,6,"[2, 5, 8, 23, 1]",217,217,257
134,4,6,"[2, 5, 15, 11, 1]",217,217,261
...,...,...,...,...,...,...
830,5,6,"[2, 11, 8, 49, 21, 1]",1297,1297,1552
831,5,6,"[2, 43, 15, 37, 32, 1]",1297,1297,2502
834,5,6,"[2, 15, 42, 26, 39, 1]",1297,1297,2805
840,5,6,"[2, 48, 20, 46, 12, 1]",1297,1297,2540
841,5,6,"[2, 37, 12, 28, 43, 1]",1297,1297,2101

====================================================================================================
..\data\raw\2_1_r7_architectures.csv
rows: 986
is_full_dimension counts:
is_full_dimension
False    688
True     298
Name: count, dtype: int64
status counts:
status
NaN    986
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
81,4,7,"[2, 6, 14, 20, 1]",344,344,396
117,4,7,"[2, 5, 12, 25, 1]",344,344,395
141,4,7,"[2, 6, 26, 8, 1]",344,344,384
142,4,7,"[2, 6, 19, 13, 1]",344,344,386
149,4,7,"[2, 7, 26, 7, 1]",344,344,385
...,...,...,...,...,...,...
777,4,7,"[2, 7, 7, 43, 1]",344,344,407
826,4,7,"[2, 5, 6, 53, 1]",344,344,411
922,4,7,"[2, 4, 6, 54, 1]",344,344,410
944,4,7,"[2, 6, 6, 52, 1]",344,344,412
952,4,7,"[2, 7, 6, 51, 1]",344,344,413

====================================================================================================
..\data\raw\2_1_r8_architectures.csv
rows: 41
is_full_dimension counts:
is_full_dimension
False    21
True     20
Name: count, dtype: int64
status counts:
status
NaN    41
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
26,3,8,"[2, 6, 10, 1]",65,65,82
35,3,8,"[2, 5, 12, 1]",65,65,82
37,3,8,"[2, 4, 16, 1]",65,65,88
38,3,8,"[2, 8, 8, 1]",65,65,88
39,3,8,"[2, 7, 9, 1]",65,65,86

====================================================================================================
..\data\raw\2_2_r2_architectures.csv
rows: 20931
is_full_dimension counts:
is_full_dimension
False    19064
True      1867
Name: count, dtype: int64
status counts:
status
nonfilling    13430
NaN            7501
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2.0,2.0,"[2, 2, 2]",6.0,6.0,8.0
13,3.0,2.0,"[2, 3, 3, 2]",10.0,10.0,21.0
59,4.0,2.0,"[2, 3, 3, 3, 2]",18.0,18.0,30.0
225,5.0,2.0,"[2, 3, 3, 4, 4, 2]",34.0,34.0,51.0
1086,6.0,2.0,"[2, 3, 3, 4, 6, 5, 2]",66.0,66.0,91.0
1088,6.0,2.0,"[2, 3, 3, 5, 7, 4, 2]",66.0,66.0,101.0
1100,6.0,2.0,"[2, 3, 4, 5, 5, 5, 2]",66.0,66.0,98.0
1104,6.0,2.0,"[2, 3, 4, 5, 6, 4, 2]",66.0,66.0,100.0
3707,7.0,2.0,"[2, 3, 3, 5, 7, 8, 5, 2]",130.0,130.0,171.0
4067,7.0,2.0,"[2, 3, 3, 4, 6, 8, 7, 2]",130.0,130.0,169.0
4289,7.0,2.0,"[2, 3, 4, 6, 6, 7, 6, 2]",130.0,130.0,174.0
4291,7.0,2.0,"[2, 3, 4, 5, 7, 8, 4, 2]",130.0,130.0,169.0
4494,7.0,2.0,"[2, 3, 4, 5, 9, 6, 5, 2]",130.0,130.0,177.0
4536,7.0,2.0,"[2, 3, 3, 6, 6, 8, 6, 2]",130.0,130.0,177.0
4574,7.0,2.0,"[2, 3, 4, 4, 7, 9, 4, 2]",130.0,130.0,169.0
4626,7.0,2.0,"[2, 3, 3, 4, 5, 8, 8, 2]",130.0,130.0,167.0
4660,7.0,2.0,"[2, 3, 5, 5, 7, 7, 5, 2]",130.0,130.0,175.0
4735,7.0,2.0,"[2, 3, 3, 4, 6, 9, 6, 2]",130.0,130.0,171.0
4741,7.0,2.0,"[2, 3, 4, 7, 7, 7, 4, 2]",130.0,130.0,180.0
4743,7.0,2.0,"[2, 3, 3, 5, 6, 9, 5, 2]",130.0,130.0,169.0
4758,7.0,2.0,"[2, 3, 3, 4, 6, 10, 5, 2]",130.0,130.0,171.0
4761,7.0,2.0,"[2, 3, 4, 5, 8, 7, 4, 2]",130.0,130.0,170.0
4762,7.0,2.0,"[2, 3, 4, 5, 6, 7, 7, 2]",130.0,130.0,173.0
4767,7.0,2.0,"[2, 3, 4, 5, 7, 7, 6, 2]",130.0,130.0,176.0
4772,7.0,2.0,"[2, 3, 4, 6, 8, 6, 5, 2]",130.0,130.0,178.0
4785,7.0,2.0,"[2, 3, 3, 4, 5, 9, 7, 2]",130.0,130.0,169.0
4790,7.0,2.0,"[2, 3, 3, 4, 7, 9, 5, 2]",130.0,130.0,173.0
4798,7.0,2.0,"[2, 3, 3, 5, 8, 8, 4, 2]",130.0,130.0,174.0
4801,7.0,2.0,"[2, 3, 3, 4, 8, 8, 5, 2]",130.0,130.0,173.0
4803,7.0,2.0,"[2, 3, 4, 6, 7, 6, 6, 2]",130.0,130.0,174.0
4805,7.0,2.0,"[2, 3, 4, 4, 7, 8, 5, 2]",130.0,130.0,168.0
4810,7.0,2.0,"[2, 3, 3, 4, 7, 7, 7, 2]",130.0,130.0,167.0
4815,7.0,2.0,"[2, 3, 3, 4, 8, 9, 4, 2]",130.0,130.0,175.0
4817,7.0,2.0,"[2, 3, 3, 5, 8, 7, 5, 2]",130.0,130.0,171.0
4818,7.0,2.0,"[2, 3, 4, 5, 5, 9, 6, 2]",130.0,130.0,174.0
4821,7.0,2.0,"[2, 3, 3, 5, 7, 9, 4, 2]",130.0,130.0,172.0
4829,7.0,2.0,"[2, 3, 4, 6, 6, 9, 4, 2]",130.0,130.0,176.0
4834,7.0,2.0,"[2, 3, 4, 5, 6, 10, 4, 2]",130.0,130.0,176.0
4836,7.0,2.0,"[2, 3, 4, 5, 8, 6, 6, 2]",130.0,130.0,174.0
4841,7.0,2.0,"[2, 3, 4, 5, 6, 8, 6, 2]",130.0,130.0,176.0
4844,7.0,2.0,"[2, 3, 3, 6, 7, 7, 6, 2]",130.0,130.0,178.0
4849,7.0,2.0,"[2, 3, 3, 4, 7, 10, 4, 2]",130.0,130.0,173.0
4852,7.0,2.0,"[2, 3, 4, 6, 7, 7, 5, 2]",130.0,130.0,178.0
4855,7.0,2.0,"[2, 3, 4, 5, 5, 8, 7, 2]",130.0,130.0,173.0
4860,7.0,2.0,"[2, 3, 3, 4, 7, 8, 6, 2]",130.0,130.0,171.0
4865,7.0,2.0,"[2, 3, 4, 6, 6, 8, 5, 2]",130.0,130.0,176.0
5499,8.0,2.0,"[2, 3, 4, 6, 10, 10, 8, 4, 2]",258.0,258.0,322.0
5528,8.0,2.0,"[2, 3, 5, 5, 10, 10, 8, 4, 2]",258.0,258.0,316.0
5539,8.0,2.0,"[2, 3, 4, 8, 9, 10, 8, 4, 2]",258.0,258.0,332.0
5805,9.0,2.0,"[2, 3, 4, 5, 18, 12, 13, 12, 4, 2]",514.0,514.0,712.0
5811,9.0,2.0,"[2, 3, 4, 5, 18, 13, 12, 11, 4, 2]",514.0,514.0,702.0
5847,9.0,2.0,"[2, 3, 4, 5, 18, 13, 13, 10, 4, 2]",514.0,514.0,709.0
6160,9.0,2.0,"[2, 3, 6, 9, 10, 15, 11, 12, 4, 2]",514.0,514.0,671.0
6172,9.0,2.0,"[2, 4, 5, 7, 10, 15, 11, 12, 4, 2]",514.0,514.0,636.0
6236,9.0,2.0,"[2, 3, 4, 4, 10, 17, 11, 12, 4, 2]",514.0,514.0,619.0

====================================================================================================
..\data\raw\2_2_r3_architectures.csv
rows: 8702
is_full_dimension counts:
is_full_dimension
False    4840
True     3862
Name: count, dtype: int64
status counts:
status
NaN    8702
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2,3,"[2, 3, 2]",8,8,12
23,3,3,"[2, 3, 5, 2]",20,20,31
25,3,3,"[2, 4, 4, 2]",20,20,32
128,4,3,"[2, 3, 5, 8, 2]",56,56,77
131,4,3,"[2, 4, 5, 7, 2]",56,56,77
...,...,...,...,...,...,...
7423,7,3,"[2, 3, 7, 5, 48, 112, 10, 2]",1460,1460,6818
7424,7,3,"[2, 3, 9, 18, 29, 117, 6, 2]",1460,1460,4824
7425,7,3,"[2, 3, 7, 6, 16, 68, 13, 2]",1460,1460,2163
7426,7,3,"[2, 4, 6, 17, 26, 60, 8, 2]",1460,1460,2632
7427,7,3,"[2, 4, 10, 6, 37, 55, 10, 2]",1460,1460,2935

====================================================================================================
..\data\raw\2_3_r2_architectures.csv
rows: 1055
is_full_dimension counts:
is_full_dimension
False    696
True     359
Name: count, dtype: int64
status counts:
status
NaN    1055
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2,2,"[2, 3, 3]",9,9,15
31,3,2,"[2, 3, 3, 3]",15,15,24
215,4,2,"[2, 3, 4, 4, 3]",27,27,46
1035,5,2,"[2, 3, 4, 5, 5, 3]",51,51,78

====================================================================================================
..\data\raw\3_1_r2_architectures.csv
rows: 64625
is_full_dimension counts:
is_full_dimension
False    62705
True      1920
Name: count, dtype: int64
status counts:
status
nonfilling    56707
NaN            7918
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
19,3.0,2.0,"[3, 4, 3, 1]",15.0,15.0,27.0
69,4.0,2.0,"[3, 5, 6, 4, 1]",45.0,45.0,73.0
178,2.0,2.0,"[3, 3, 1]",6.0,6.0,12.0
482,5.0,2.0,"[3, 6, 9, 9, 6, 1]",153.0,153.0,213.0
500,5.0,2.0,"[3, 5, 9, 10, 4, 1]",153.0,153.0,194.0
...,...,...,...,...,...,...
6550,7.0,2.0,"[3, 10, 9, 23, 38, 25, 8, 1]",2145.0,2145.0,2359.0
6555,7.0,2.0,"[3, 5, 13, 30, 26, 29, 12, 1]",2145.0,2145.0,2364.0
6596,7.0,2.0,"[3, 5, 11, 19, 39, 28, 6, 1]",2145.0,2145.0,2286.0
6598,7.0,2.0,"[3, 5, 13, 19, 39, 28, 5, 1]",2145.0,2145.0,2305.0
6625,7.0,2.0,"[3, 5, 14, 19, 36, 30, 7, 1]",2145.0,2145.0,2332.0

====================================================================================================
..\data\raw\3_1_r3_architectures.csv
rows: 12259
is_full_dimension counts:
is_full_dimension
False    6447
True     5812
Name: count, dtype: int64
status counts:
status
NaN    12259
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,3,"[3, 4, 1]",10,10,16
40,3,3,"[3, 6, 8, 1]",55,55,74
41,3,3,"[3, 7, 6, 1]",55,55,69
189,4,3,"[3, 8, 22, 11, 1]",406,406,453
202,4,3,"[3, 8, 12, 26, 1]",406,406,458
...,...,...,...,...,...,...
12247,5,3,"[3, 6, 48, 53, 13, 1]",3403,3403,3552
12250,5,3,"[3, 8, 45, 33, 51, 1]",3403,3403,3603
12251,5,3,"[3, 8, 33, 47, 36, 1]",3403,3403,3567
12255,5,3,"[3, 6, 35, 46, 37, 1]",3403,3403,3577
12258,5,3,"[3, 9, 33, 45, 38, 1]",3403,3403,3557

====================================================================================================
..\data\raw\3_2_r3_architectures.csv
rows: 885
is_full_dimension counts:
is_full_dimension
False    444
True     441
Name: count, dtype: int64
status counts:
status
NaN    885
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2,3,"[3, 6, 2]",20,20,30
43,3,3,"[3, 7, 12, 2]",110,110,129
52,3,3,"[3, 10, 10, 2]",110,110,150
62,3,3,"[3, 6, 14, 2]",110,110,130
64,3,3,"[3, 8, 11, 2]",110,110,134
...,...,...,...,...,...,...
870,4,3,"[3, 6, 24, 28, 2]",812,812,890
872,4,3,"[3, 8, 19, 34, 2]",812,812,890
875,4,3,"[3, 10, 25, 23, 2]",812,812,901
879,4,3,"[3, 9, 28, 20, 2]",812,812,879
880,4,3,"[3, 8, 36, 15, 2]",812,812,882

====================================================================================================
..\data\raw\3_3_r3_architectures.csv
rows: 599
is_full_dimension counts:
is_full_dimension
False    335
True     264
Name: count, dtype: int64
status counts:
status
NaN    599
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,3,"[3, 6, 3]",30,30,36
56,3,3,"[3, 8, 15, 3]",165,165,189
58,3,3,"[3, 6, 20, 3]",165,165,198
59,3,3,"[3, 10, 14, 3]",165,165,212
60,3,3,"[3, 7, 17, 3]",165,165,191
...,...,...,...,...,...,...
592,4,3,"[3, 18, 27, 34, 3]",1218,1218,1560
594,4,3,"[3, 10, 18, 53, 3]",1218,1218,1323
595,4,3,"[3, 6, 40, 26, 3]",1218,1218,1376
596,4,3,"[3, 16, 30, 30, 3]",1218,1218,1518
598,4,3,"[3, 10, 37, 24, 3]",1218,1218,1360

====================================================================================================
..\data\raw\3_3_r6_architectures.csv
rows: 2191
is_full_dimension counts:
is_full_dimension
False    2118
True       73
Name: count, dtype: int64
status counts:
status
nonfilling    2014
NaN            177
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
74,2.0,6.0,"[3, 17, 3]",84.0,84.0,102.0
76,3.0,6.0,"[3, 28, 71, 3]",2109.0,2109.0,2285.0
77,3.0,6.0,"[3, 27, 72, 3]",2109.0,2109.0,2241.0
80,3.0,6.0,"[3, 24, 80, 3]",2109.0,2109.0,2232.0
84,3.0,6.0,"[3, 26, 74, 3]",2109.0,2109.0,2224.0
87,3.0,6.0,"[3, 25, 77, 3]",2109.0,2109.0,2231.0
104,3.0,6.0,"[3, 17, 110, 3]",2109.0,2109.0,2251.0
105,3.0,6.0,"[3, 22, 87, 3]",2109.0,2109.0,2241.0
106,3.0,6.0,"[3, 21, 90, 3]",2109.0,2109.0,2223.0
113,3.0,6.0,"[3, 20, 95, 3]",2109.0,2109.0,2245.0
126,3.0,6.0,"[3, 16, 116, 3]",2109.0,2109.0,2252.0
128,3.0,6.0,"[3, 23, 83, 3]",2109.0,2109.0,2227.0
130,3.0,6.0,"[3, 19, 99, 3]",2109.0,2109.0,2235.0
131,3.0,6.0,"[3, 18, 104, 3]",2109.0,2109.0,2238.0
156,3.0,6.0,"[3, 14, 131, 3]",2109.0,2109.0,2269.0
166,3.0,6.0,"[3, 15, 123, 3]",2109.0,2109.0,2259.0
171,3.0,6.0,"[3, 13, 139, 3]",2109.0,2109.0,2263.0
176,3.0,6.0,"[3, 12, 149, 3]",2109.0,2109.0,2271.0

====================================================================================================
..\data\raw\3_4_r3_architectures.csv
rows: 1115
is_full_dimension counts:
is_full_dimension
False    612
True     503
Name: count, dtype: int64
status counts:
status
NaN    1115
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
7,2,3,"[3, 7, 4]",40,40,49
45,3,3,"[3, 9, 18, 4]",220,220,261
52,3,3,"[3, 8, 19, 4]",220,220,252
53,3,3,"[3, 10, 17, 4]",220,220,268
62,3,3,"[3, 6, 24, 4]",220,220,258
...,...,...,...,...,...,...
1099,4,3,"[3, 10, 35, 35, 4]",1624,1624,1745
1100,4,3,"[3, 6, 41, 32, 4]",1624,1624,1704
1102,4,3,"[3, 8, 18, 71, 4]",1624,1624,1730
1103,4,3,"[3, 8, 25, 52, 4]",1624,1624,1732
1109,4,3,"[3, 9, 24, 53, 4]",1624,1624,1727

====================================================================================================
..\data\raw\4_1_r2_architectures.csv
rows: 5835
is_full_dimension counts:
is_full_dimension
False    3104
True     2731
Name: count, dtype: int64
status counts:
status
NaN    5835
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,2,"[4, 4, 1]",10,10,20
45,3,2,"[4, 6, 5, 1]",35,35,59
317,4,2,"[4, 8, 14, 5, 1]",165,165,219
334,4,2,"[4, 10, 11, 11, 1]",165,165,282
345,4,2,"[4, 8, 13, 6, 1]",165,165,220
...,...,...,...,...,...,...
5828,5,2,"[4, 8, 19, 31, 10, 1]",969,969,1093
5830,5,2,"[4, 7, 14, 34, 16, 1]",969,969,1162
5832,5,2,"[4, 9, 20, 25, 25, 1]",969,969,1366
5833,5,2,"[4, 9, 14, 30, 27, 1]",969,969,1419
5834,5,2,"[4, 8, 22, 26, 13, 1]",969,969,1131

====================================================================================================
..\data\raw\4_1_r3_architectures.csv
rows: 99
is_full_dimension counts:
is_full_dimension
True     51
False    48
Name: count, dtype: int64
status counts:
status
NaN    99
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2,3,"[4, 5, 1]",20,20,25
45,3,3,"[4, 13, 14, 1]",220,220,248
46,3,3,"[4, 11, 17, 1]",220,220,248
47,3,3,"[4, 10, 19, 1]",220,220,249
49,3,3,"[4, 12, 16, 1]",220,220,256
56,3,3,"[4, 15, 12, 1]",220,220,252
58,3,3,"[4, 14, 13, 1]",220,220,251
60,3,3,"[4, 16, 11, 1]",220,220,251
67,4,3,"[4, 29, 73, 41, 1]",4060,4060,5267
70,4,3,"[4, 8, 57, 69, 1]",4060,4060,4490
71,4,3,"[4, 24, 54, 66, 1]",4060,4060,5022
80,4,3,"[4, 46, 61, 49, 1]",4060,4060,6028
91,4,3,"[4, 25, 56, 59, 1]",4060,4060,4863
95,4,3,"[4, 14, 66, 48, 1]",4060,4060,4196
97,4,3,"[4, 15, 56, 60, 1]",4060,4060,4320
98,4,3,"[4, 53, 56, 54, 1]",4060,4060,6258

====================================================================================================
..\data\raw\5_1_r2_architectures.csv
rows: 892
is_full_dimension counts:
is_full_dimension
False    596
True     296
Name: count, dtype: int64
status counts:
status
NaN    892
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2,2,"[5, 5, 1]",15,15,30
35,3,2,"[5, 9, 6, 1]",70,70,105
214,4,2,"[5, 12, 22, 14, 1]",495,495,646
263,4,2,"[5, 14, 24, 9, 1]",495,495,631
316,4,2,"[5, 9, 25, 14, 1]",495,495,634
...,...,...,...,...,...,...
870,5,2,"[5, 16, 55, 53, 33, 1]",4845,4845,5657
871,5,2,"[5, 43, 51, 55, 39, 1]",4845,4845,7397
877,5,2,"[5, 32, 55, 55, 27, 1]",4845,4845,6457
883,5,2,"[5, 15, 54, 53, 52, 1]",4845,4845,6555
891,5,2,"[5, 40, 55, 52, 38, 1]",4845,4845,7274

====================================================================================================
..\data\raw\5_1_r3_architectures.csv
rows: 84
is_full_dimension counts:
is_full_dimension
True     42
False    42
Name: count, dtype: int64
status counts:
status
NaN    84
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,3,"[5, 8, 1]",35,35,48
24,3,3,"[5, 19, 36, 1]",715,715,815
25,3,3,"[5, 27, 23, 1]",715,715,779
35,3,3,"[5, 24, 26, 1]",715,715,770
50,3,3,"[5, 28, 22, 1]",715,715,778
51,3,3,"[5, 18, 38, 1]",715,715,812
66,3,3,"[5, 20, 32, 1]",715,715,772
67,3,3,"[5, 17, 39, 1]",715,715,787
71,3,3,"[5, 15, 44, 1]",715,715,779
74,3,3,"[5, 26, 25, 1]",715,715,805
78,3,3,"[5, 23, 28, 1]",715,715,787
81,3,3,"[5, 22, 29, 1]",715,715,777
82,3,3,"[5, 16, 41, 1]",715,715,777
83,3,3,"[5, 29, 21, 1]",715,715,775

====================================================================================================
..\data\raw\6_1_r3_architectures.csv
rows: 177
is_full_dimension counts:
is_full_dimension
True     94
False    83
Name: count, dtype: int64
status counts:
status
NaN    177
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
7,2,3,"[6, 10, 1]",56,56,70
24,3,3,"[6, 38, 48, 1]",2002,2002,2100
43,3,3,"[6, 23, 83, 1]",2002,2002,2130
70,3,3,"[6, 46, 39, 1]",2002,2002,2109
76,3,3,"[6, 45, 40, 1]",2002,2002,2110
79,3,3,"[6, 32, 58, 1]",2002,2002,2106
91,3,3,"[6, 25, 76, 1]",2002,2002,2126
105,3,3,"[6, 34, 54, 1]",2002,2002,2094
109,3,3,"[6, 37, 50, 1]",2002,2002,2122
120,3,3,"[6, 36, 51, 1]",2002,2002,2103
124,3,3,"[6, 49, 36, 1]",2002,2002,2094
127,3,3,"[6, 29, 65, 1]",2002,2002,2124
130,3,3,"[6, 24, 79, 1]",2002,2002,2119
132,3,3,"[6, 22, 86, 1]",2002,2002,2110
134,3,3,"[6, 28, 67, 1]",2002,2002,2111
135,3,3,"[6, 35, 53, 1]",2002,2002,2118
137,3,3,"[6, 26, 72, 1]",2002,2002,2100
143,3,3,"[6, 41, 44, 1]",2002,2002,2094
147,3,3,"[6, 33, 56, 1]",2002,2002,2102
153,3,3,"[6, 48, 37, 1]",2002,2002,2101
154,3,3,"[6, 27, 70, 1]",2002,2002,2122
156,3,3,"[6, 42, 43, 1]",2002,2002,2101
159,3,3,"[6, 40, 46, 1]",2002,2002,2126
163,3,3,"[6, 30, 62, 1]",2002,2002,2102
164,3,3,"[6, 47, 38, 1]",2002,2002,2106
169,3,3,"[6, 43, 42, 1]",2002,2002,2106
170,3,3,"[6, 39, 47, 1]",2002,2002,2114
171,3,3,"[6, 31, 60, 1]",2002,2002,2106
176,3,3,"[6, 44, 41, 1]",2002,2002,2109

====================================================================================================
..\data\raw\7_1_r3_architectures.csv
rows: 183
is_full_dimension counts:
is_full_dimension
True     104
False     79
Name: count, dtype: int64
status counts:
status
NaN    183
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
0,2,3,"[7, 12, 1]",84,84,96
25,3,3,"[7, 34, 144, 1]",5005,5005,5278
38,3,3,"[7, 45, 110, 1]",5005,5005,5375
42,3,3,"[7, 43, 115, 1]",5005,5005,5361
57,3,3,"[7, 38, 127, 1]",5005,5005,5219
66,3,3,"[7, 37, 130, 1]",5005,5005,5199
68,3,3,"[7, 51, 93, 1]",5005,5005,5193
70,3,3,"[7, 52, 91, 1]",5005,5005,5187
74,3,3,"[7, 39, 124, 1]",5005,5005,5233
78,3,3,"[7, 40, 122, 1]",5005,5005,5282
92,3,3,"[7, 58, 81, 1]",5005,5005,5185
99,3,3,"[7, 62, 75, 1]",5005,5005,5159
104,3,3,"[7, 33, 146, 1]",5005,5005,5195
106,3,3,"[7, 64, 73, 1]",5005,5005,5193
114,3,3,"[7, 35, 137, 1]",5005,5005,5177
118,3,3,"[7, 46, 107, 1]",5005,5005,5351
121,3,3,"[7, 61, 77, 1]",5005,5005,5201
122,3,3,"[7, 50, 95, 1]",5005,5005,5195
123,3,3,"[7, 76, 60, 1]",5005,5005,5152
125,3,3,"[7, 71, 65, 1]",5005,5005,5177
132,3,3,"[7, 73, 63, 1]",5005,5005,5173
134,3,3,"[7, 54, 87, 1]",5005,5005,5163
139,3,3,"[7, 66, 70, 1]",5005,5005,5152
144,3,3,"[7, 65, 71, 1]",5005,5005,5141
146,3,3,"[7, 68, 68, 1]",5005,5005,5168
147,3,3,"[7, 55, 85, 1]",5005,5005,5145
151,3,3,"[7, 56, 84, 1]",5005,5005,5180
153,3,3,"[7, 75, 61, 1]",5005,5005,5161
154,3,3,"[7, 74, 62, 1]",5005,5005,5168
158,3,3,"[7, 53, 89, 1]",5005,5005,5177
159,3,3,"[7, 59, 79, 1]",5005,5005,5153
162,3,3,"[7, 49, 97, 1]",5005,5005,5193
164,3,3,"[7, 70, 66, 1]",5005,5005,5176
166,3,3,"[7, 48, 99, 1]",5005,5005,5187
167,3,3,"[7, 67, 69, 1]",5005,5005,5161
169,3,3,"[7, 69, 67, 1]",5005,5005,5173
176,3,3,"[7, 60, 78, 1]",5005,5005,5178
177,3,3,"[7, 63, 74, 1]",5005,5005,5177
180,3,3,"[7, 57, 82, 1]",5005,5005,5155
182,3,3,"[7, 72, 64, 1]",5005,5005,5176

====================================================================================================
..\data\raw\8_1_r2_architectures.csv
rows: 94
is_full_dimension counts:
is_full_dimension
False    55
True     39
Name: count, dtype: int64
status counts:
status
NaN    94
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2,2,"[8, 8, 1]",36,36,72
69,3,2,"[8, 22, 11, 1]",330,330,429
74,3,2,"[8, 21, 12, 1]",330,330,432
87,3,2,"[8, 20, 15, 1]",330,330,475
93,4,2,"[8, 136, 111, 139, 1]",6435,6435,31752

====================================================================================================
..\data\raw\8_1_r3_architectures.csv
rows: 6
is_full_dimension counts:
is_full_dimension
True     5
False    1
Name: count, dtype: int64
status counts:
status
NaN    6
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,3,"[8, 15, 1]",120,120,135

## Post-Run entries with Codimension = 1

In [76]:
for path in csv_paths:
    df = read_architecture_csv(path)
    df = df[df['dimension_computed'] == df['ambient_dimension']-1]
    display(df)

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,expected_dimension,defect_expected,defect_ambient,backend,primes,elapsed_seconds,status,covered_by_mfa
23,3.0,12.0,"[2, 9, 15, 1]",168.0,144.0,145.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,3.0,12.0,"[2, 8, 17, 1]",169.0,144.0,145.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,3.0,12.0,"[2, 6, 23, 1]",173.0,144.0,145.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,expected_dimension,defect_expected,defect_ambient,backend,primes,elapsed_seconds,status,covered_by_mfa
1,2.0,2.0,"[2, 1, 1]",3.0,2.0,3.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3735,7.0,2.0,"[2, 4, 3, 4, 5, 5, 10, 1]",137.0,64.0,65.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3798,7.0,2.0,"[2, 9, 3, 4, 5, 5, 6, 1]",138.0,64.0,65.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3835,7.0,2.0,"[2, 10, 3, 4, 5, 5, 8, 1]",155.0,64.0,65.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4002,7.0,2.0,"[2, 8, 3, 4, 5, 5, 11, 1]",163.0,64.0,65.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10050,8.0,2.0,"[2, 9, 3, 5, 7, 6, 7, 3, 1]",203.0,128.0,129.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10051,8.0,2.0,"[2, 9, 3, 9, 7, 7, 5, 9, 1]",273.0,128.0,129.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10053,8.0,2.0,"[2, 9, 9, 9, 6, 7, 5, 9, 1]",365.0,128.0,129.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10054,8.0,2.0,"[2, 9, 3, 5, 6, 8, 6, 2, 1]",200.0,128.0,129.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20448,7.0,2.0,"[2, 3, 3, 5, 6, 4, 3, 1]",99.0,64.0,65.0,False,False,65.0,1.0,1.0,dim_backprop_gpu_only/CuPy-CUDA,"(10000019, 100153)",0.110316,nonfilling,"[[3, 3, 5, 6, 4, 4], [3, 3, 6, 6, 4, 3]]"

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,expected_dimension,defect_expected,defect_ambient,backend,primes,elapsed_seconds,status,covered_by_mfa
7,5,3,"[2, 3, 7, 6, 5, 1]",104,81,82,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,5,3,"[2, 3, 8, 6, 5, 1]",113,81,82,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,5,3,"[2, 3, 9, 6, 5, 1]",122,81,82,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,5,3,"[2, 3, 10, 6, 5, 1]",131,81,82,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,6,3,"[2, 3, 8, 14, 8, 4, 1]",290,243,244,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145,6,3,"[2, 3, 7, 15, 8, 4, 1]",288,243,244,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160,6,3,"[2, 3, 6, 16, 8, 4, 1]",284,243,244,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
195,6,3,"[2, 4, 8, 11, 10, 5, 1]",293,243,244,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
219,6,3,"[2, 3, 9, 12, 9, 5, 1]",299,243,244,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,expected_dimension,defect_expected,defect_ambient,backend,primes,elapsed_seconds,status,covered_by_mfa
3,2,4,"[2, 2, 1]",6,4,5,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,4,4,"[2, 21, 8, 4, 1]",246,64,65,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,4,4,"[2, 23, 8, 4, 1]",266,64,65,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
142,4,4,"[2, 4, 6, 7, 1]",81,64,65,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
173,4,4,"[2, 24, 8, 4, 1]",276,64,65,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3249,5,4,"[2, 24, 10, 8, 18, 1]",530,256,257,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3250,5,4,"[2, 25, 9, 10, 14, 1]",519,256,257,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3263,5,4,"[2, 25, 10, 8, 18, 1]",542,256,257,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3283,5,4,"[2, 25, 12, 13, 5, 1]",576,256,257,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3285,5,4,"[2, 25, 4, 20, 9, 1]",419,256,257,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,expected_dimension,defect_expected,defect_ambient,backend,primes,elapsed_seconds,status,covered_by_mfa
191,4.0,5.0,"[2, 30, 5, 20, 1]",330.0,125.0,126.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
232,4.0,5.0,"[2, 38, 5, 20, 1]",386.0,125.0,126.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259,4.0,5.0,"[2, 5, 12, 6, 1]",148.0,125.0,126.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276,4.0,5.0,"[2, 39, 5, 20, 1]",393.0,125.0,126.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
299,4.0,5.0,"[2, 4, 11, 8, 1]",148.0,125.0,126.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
306,4.0,5.0,"[2, 5, 10, 8, 1]",148.0,125.0,126.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
310,4.0,5.0,"[2, 5, 8, 11, 1]",149.0,125.0,126.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,4.0,5.0,"[2, 5, 6, 16, 1]",152.0,125.0,126.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
331,4.0,5.0,"[2, 40, 5, 20, 1]",400.0,125.0,126.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
992,5.0,5.0,"[2, 26, 5, 15, 36, 1]",833.0,625.0,626.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2311,4.0,5.0,"[2, 5, 5, 20, 1]",155.0,125.0,126.0,False,False,125.0,0.0,1.0,dim_backprop_gpu_only/CuPy-CUDA,"(10000019, 19511957)",1.226279,nonfilling,"[[5, 5, 21]]"

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,expected_dimension,defect_expected,defect_ambient,backend,primes,elapsed_seconds,status,covered_by_mfa
73,4,6,"[2, 16, 12, 12, 1]",380,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,4,6,"[2, 16, 18, 6, 1]",434,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146,4,6,"[2, 6, 7, 25, 1]",254,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168,4,6,"[2, 8, 9, 18, 1]",268,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
172,4,6,"[2, 13, 9, 18, 1]",323,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,4,6,"[2, 8, 8, 21, 1]",269,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
214,4,6,"[2, 25, 8, 21, 1]",439,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
252,4,6,"[2, 24, 12, 12, 1]",492,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
256,4,6,"[2, 25, 18, 6, 1]",614,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261,4,6,"[2, 15, 9, 18, 1]",345,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,4,6,"[2, 19, 9, 18, 1]",389,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
283,4,6,"[2, 6, 14, 10, 1]",246,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
295,4,6,"[2, 6, 10, 16, 1]",248,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,4,6,"[2, 23, 9, 18, 1]",433,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,4,6,"[2, 25, 12, 12, 1]",506,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
322,4,6,"[2, 24, 9, 18, 1]",444,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
334,4,6,"[2, 25, 9, 18, 1]",455,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
344,4,6,"[2, 6, 15, 9, 1]",246,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
395,4,6,"[2, 34, 8, 21, 1]",529,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
409,4,6,"[2, 19, 6, 30, 1]",362,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
432,4,6,"[2, 29, 6, 30, 1]",442,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
468,4,6,"[2, 40, 6, 30, 1]",530,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
476,4,6,"[2, 38, 18, 6, 1]",874,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
504,4,6,"[2, 37, 12, 12, 1]",674,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
519,4,6,"[2, 35, 9, 18, 1]",565,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
546,4,6,"[2, 39, 9, 18, 1]",609,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
559,4,6,"[2, 40, 12, 12, 1]",716,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
567,4,6,"[2, 39, 18, 6, 1]",894,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
576,4,6,"[2, 40, 18, 6, 1]",914,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
578,4,6,"[2, 40, 9, 18, 1]",620,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
591,4,6,"[2, 36, 8, 21, 1]",549,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
598,4,6,"[2, 38, 8, 21, 1]",569,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
602,4,6,"[2, 40, 8, 21, 1]",589,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
611,2,6,"[2, 3, 1]",9,6,7,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
636,3,6,"[2, 4, 8, 1]",48,36,37,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
732,4,6,"[2, 45, 6, 30, 1]",570,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
767,4,6,"[2, 44, 12, 12, 1]",772,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
768,4,6,"[2, 46, 6, 30, 1]",578,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
774,4,6,"[2, 44, 8, 21, 1]",629,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
790,4,6,"[2, 50, 6, 30, 1]",610,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
791,4,6,"[2, 50, 18, 6, 1]",1114,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
794,4,6,"[2, 45, 8, 21, 1]",639,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
796,4,6,"[2, 46, 8, 21, 1]",649,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
799,4,6,"[2, 48, 12, 12, 1]",828,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
808,4,6,"[2, 48, 8, 21, 1]",669,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
809,4,6,"[2, 44, 9, 18, 1]",664,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
815,4,6,"[2, 49, 9, 18, 1]",719,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
816,4,6,"[2, 50, 9, 18, 1]",730,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
822,4,6,"[2, 50, 12, 12, 1]",856,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
823,4,6,"[2, 49, 8, 21, 1]",679,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
824,4,6,"[2, 50, 8, 21, 1]",689,216,217,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,expected_dimension,defect_expected,defect_ambient,backend,primes,elapsed_seconds,status,covered_by_mfa
237,4,7,"[2, 7, 16, 15, 1]",381,343,344,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
344,4,7,"[2, 7, 14, 18, 1]",382,343,344,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
359,4,7,"[2, 5, 13, 22, 1]",383,343,344,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
368,4,7,"[2, 7, 24, 8, 1]",382,343,344,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
393,4,7,"[2, 5, 26, 9, 1]",383,343,344,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
397,4,7,"[2, 7, 21, 10, 1]",381,343,344,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
415,4,7,"[2, 7, 12, 22, 1]",384,343,344,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
596,4,7,"[2, 41, 7, 42, 1]",705,343,344,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
622,4,7,"[2, 45, 7, 42, 1]",741,343,344,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
634,4,7,"[2, 7, 8, 36, 1]",394,343,344,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
712,4,7,"[2, 46, 7, 42, 1]",750,343,344,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
764,4,7,"[2, 48, 7, 42, 1]",768,343,344,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
896,4,7,"[2, 50, 7, 42, 1]",786,343,344,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
965,4,7,"[2, 53, 7, 42, 1]",813,343,344,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
980,4,7,"[2, 54, 7, 42, 1]",822,343,344,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,expected_dimension,defect_expected,defect_ambient,backend,primes,elapsed_seconds,status,covered_by_mfa
28,3,8,"[2, 4, 15, 1]",83,64,65,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,expected_dimension,defect_expected,defect_ambient,backend,primes,elapsed_seconds,status,covered_by_mfa
2345,7.0,2.0,"[2, 11, 11, 5, 6, 9, 4, 2]",326.0,129.0,130.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2500,7.0,2.0,"[2, 11, 9, 5, 6, 8, 5, 2]",294.0,129.0,130.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2584,7.0,2.0,"[2, 3, 9, 5, 8, 6, 5, 2]",206.0,129.0,130.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2729,7.0,2.0,"[2, 4, 3, 6, 12, 7, 4, 2]",230.0,129.0,130.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2891,7.0,2.0,"[2, 6, 11, 4, 6, 9, 5, 2]",255.0,129.0,130.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4843,7.0,2.0,"[2, 12, 9, 5, 6, 9, 4, 2]",305.0,129.0,130.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4851,7.0,2.0,"[2, 12, 12, 4, 6, 9, 5, 2]",349.0,129.0,130.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4861,7.0,2.0,"[2, 12, 11, 5, 6, 9, 4, 2]",339.0,129.0,130.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4862,7.0,2.0,"[2, 12, 4, 5, 7, 7, 5, 2]",221.0,129.0,130.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5529,8.0,2.0,"[2, 4, 4, 5, 10, 10, 8, 4, 2]",314.0,257.0,258.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,expected_dimension,defect_expected,defect_ambient,backend,primes,elapsed_seconds,status,covered_by_mfa
30,3,3,"[2, 3, 4, 2]",26,19,20,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,4,3,"[2, 24, 25, 5, 2]",783,55,56,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,4,3,"[2, 18, 29, 5, 2]",713,55,56,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,4,3,"[2, 26, 15, 5, 2]",527,55,56,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,4,3,"[2, 28, 15, 5, 2]",561,55,56,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8682,5,3,"[2, 3, 54, 6, 55, 2]",932,163,164,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8688,5,3,"[2, 54, 6, 9, 10, 2]",596,163,164,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8691,5,3,"[2, 3, 55, 6, 55, 2]",941,163,164,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8695,5,3,"[2, 55, 4, 13, 8, 2]",502,163,164,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8699,5,3,"[2, 55, 6, 9, 10, 2]",604,163,164,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,expected_dimension,defect_expected,defect_ambient,backend,primes,elapsed_seconds,status,covered_by_mfa
4,2,2,"[2, 2, 3]",10,8,9,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,expected_dimension,defect_expected,defect_ambient,backend,primes,elapsed_seconds,status,covered_by_mfa
177,2.0,2.0,"[3, 2, 1]",8.0,5.0,6.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
501,5.0,2.0,"[3, 13, 9, 9, 5, 1]",287.0,152.0,153.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
518,5.0,2.0,"[3, 5, 6, 12, 7, 1]",208.0,152.0,153.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
527,5.0,2.0,"[3, 13, 7, 11, 6, 1]",279.0,152.0,153.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
549,5.0,2.0,"[3, 14, 7, 11, 6, 1]",289.0,152.0,153.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
593,5.0,2.0,"[3, 5, 8, 10, 6, 1]",201.0,152.0,153.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
594,5.0,2.0,"[3, 15, 7, 11, 6, 1]",299.0,152.0,153.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
603,5.0,2.0,"[3, 5, 9, 9, 6, 1]",201.0,152.0,153.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
610,5.0,2.0,"[3, 14, 9, 9, 5, 1]",299.0,152.0,153.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
620,5.0,2.0,"[3, 15, 9, 9, 5, 1]",311.0,152.0,153.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
622,5.0,2.0,"[3, 5, 8, 11, 4, 1]",191.0,152.0,153.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
942,6.0,2.0,"[3, 5, 8, 19, 18, 4, 1]",625.0,560.0,561.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1676,6.0,2.0,"[3, 5, 20, 16, 18, 4, 1]",799.0,560.0,561.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1821,6.0,2.0,"[3, 6, 16, 16, 18, 4, 1]",734.0,560.0,561.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1869,6.0,2.0,"[3, 6, 18, 16, 18, 4, 1]",778.0,560.0,561.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1890,6.0,2.0,"[3, 6, 20, 16, 18, 4, 1]",822.0,560.0,561.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1928,6.0,2.0,"[3, 5, 23, 16, 18, 4, 1]",862.0,560.0,561.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1946,6.0,2.0,"[3, 6, 21, 16, 18, 4, 1]",844.0,560.0,561.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1955,6.0,2.0,"[3, 6, 22, 16, 18, 4, 1]",866.0,560.0,561.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1966,6.0,2.0,"[3, 6, 14, 15, 19, 5, 1]",697.0,560.0,561.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1971,6.0,2.0,"[3, 6, 23, 16, 18, 4, 1]",888.0,560.0,561.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1974,6.0,2.0,"[3, 5, 25, 16, 18, 4, 1]",904.0,560.0,561.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1977,6.0,2.0,"[3, 6, 24, 16, 18, 4, 1]",910.0,560.0,561.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982,6.0,2.0,"[3, 6, 25, 16, 18, 4, 1]",932.0,560.0,561.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1986,6.0,2.0,"[3, 5, 13, 21, 12, 4, 1]",657.0,560.0,561.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2040,6.0,2.0,"[3, 5, 13, 15, 20, 4, 1]",659.0,560.0,561.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2054,6.0,2.0,"[3, 5, 7, 16, 23, 4, 1]",626.0,560.0,561.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2099,6.0,2.0,"[3, 6, 12, 13, 23, 5, 1]",665.0,560.0,561.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2129,6.0,2.0,"[3, 5, 10, 13, 24, 5, 1]",632.0,560.0,561.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2134,6.0,2.0,"[3, 5, 9, 13, 25, 5, 1]",632.0,560.0,561.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2142,6.0,2.0,"[3, 6, 11, 21, 13, 4, 1]",644.0,560.0,561.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2174,6.0,2.0,"[3, 6, 13, 21, 12, 4, 1]",673.0,560.0,561.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2178,6.0,2.0,"[3, 6, 8, 14, 24, 5, 1]",639.0,560.0,561.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2201,6.0,2.0,"[3, 6, 13, 15, 20, 4, 1]",675.0,560.0,561.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2248,6.0,2.0,"[3, 5, 8, 22, 15, 4, 1]",625.0,560.0,561.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2266,6.0,2.0,"[3, 5, 11, 20, 14, 4, 1]",630.0,560.0,561.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2274,6.0,2.0,"[3, 6, 11, 20, 14, 4, 1]",644.0,560.0,561.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2283,6.0,2.0,"[3, 6, 6, 16, 23, 5, 1]",638.0,560.0,561.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3560,7.0,2.0,"[3, 7, 9, 36, 34, 17, 6, 1]",2318.0,2144.0,2145.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3664,7.0,2.0,"[3, 7, 11, 40, 34, 17, 6, 1]",2584.0,2144.0,2145.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4313,7.0,2.0,"[3, 10, 22, 29, 29, 26, 9, 1]",2726.0,2144.0,2145.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4347,7.0,2.0,"[3, 11, 15, 29, 29, 26, 9, 1]",2471.0,2144.0,2145.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5302,7.0,2.0,"[3, 5, 14, 29, 26, 30, 11, 1]",2366.0,2144.0,2145.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5314,7.0,2.0,"[3, 7, 14, 29, 26, 30, 11, 1]",2400.0,2144.0,2145.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5357,7.0,2.0,"[3, 8, 14, 29, 26, 30, 11, 1]",2417.0,2144.0,2145.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5365,7.0,2.0,"[3, 10, 14, 29, 26, 30, 11, 1]",2451.0,2144.0,2145.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5644,7.0,2.0,"[3, 8, 13, 18, 39, 28, 7, 1]",2359.0,2144.0,2145.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5683,7.0,2.0,"[3, 11, 14, 18, 38, 30, 5, 1]",2418.0,2144.0,2145.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6483,7.0,2.0,"[3, 11, 9, 23, 38, 25, 7, 1]",2345.0,2144.0,2145.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6521,7.0,2.0,"[3, 12, 9, 23, 38, 25, 7, 1]",2357.0,2144.0,2145.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7136,5.0,2.0,"[3, 30, 7, 11, 6, 1]",449.0,152.0,153.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7222,5.0,2.0,"[3, 29, 9, 9, 5, 1]",479.0,152.0,153.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7265,5.0,2.0,"[3, 30, 9, 9, 5, 1]",491.0,152.0,153.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13114,5.0,2.0,"[3, 6, 9, 9, 5, 1]",203.0,152.0,153.0,False,False,153.0,1.0,1.0,dim_backprop_gpu_only/CuPy-CUDA,"(10000019, 19511957)",0.261039,nonfilling,"[[6, 9, 9, 6]]"

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,expected_dimension,defect_expected,defect_ambient,backend,primes,elapsed_seconds,status,covered_by_mfa
0,2,3,"[3, 3, 1]",12,9,10,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,3,3,"[3, 6, 7, 1]",67,54,55,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140,4,3,"[3, 53, 15, 18, 1]",1242,405,406,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278,4,3,"[3, 7, 23, 11, 1]",446,405,406,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
481,4,3,"[3, 7, 17, 17, 1]",446,405,406,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12034,5,3,"[3, 55, 33, 45, 37, 1]",5167,3402,3403,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12069,5,3,"[3, 54, 24, 54, 36, 1]",4734,3402,3403,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12093,5,3,"[3, 50, 18, 54, 43, 1]",4387,3402,3403,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12102,5,3,"[3, 48, 42, 54, 15, 1]",5253,3402,3403,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12174,5,3,"[3, 6, 38, 50, 27, 1]",3523,3402,3403,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,expected_dimension,defect_expected,defect_ambient,backend,primes,elapsed_seconds,status,covered_by_mfa
2,2,3,"[3, 5, 2]",25,19,20,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,3,3,"[3, 9, 10, 2]",137,109,110,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,4,3,"[3, 36, 19, 32, 2]",1464,811,812,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
389,4,3,"[3, 39, 19, 32, 2]",1530,811,812,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
418,4,3,"[3, 49, 19, 32, 2]",1750,811,812,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
514,4,3,"[3, 53, 19, 32, 2]",1838,811,812,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
615,4,3,"[3, 9, 29, 19, 2]",877,811,812,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
749,4,3,"[3, 54, 19, 32, 2]",1860,811,812,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
799,4,3,"[3, 9, 14, 46, 2]",889,811,812,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
843,4,3,"[3, 9, 17, 37, 2]",883,811,812,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
844,4,3,"[3, 9, 26, 22, 2]",877,811,812,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
874,4,3,"[3, 55, 19, 32, 2]",1882,811,812,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,expected_dimension,defect_expected,defect_ambient,backend,primes,elapsed_seconds,status,covered_by_mfa
45,3,3,"[3, 6, 19, 3]",189,164,165,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
288,4,3,"[3, 6, 43, 22, 3]",1288,1217,1218,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
378,4,3,"[3, 9, 22, 43, 3]",1300,1217,1218,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,expected_dimension,defect_expected,defect_ambient,backend,primes,elapsed_seconds,status,covered_by_mfa
46,3.0,6.0,"[3, 22, 86, 3]",2216.0,2108.0,2109.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129,3.0,6.0,"[3, 20, 94, 3]",2222.0,2108.0,2109.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175,3.0,6.0,"[3, 14, 130, 3]",2252.0,2108.0,2109.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,expected_dimension,defect_expected,defect_ambient,backend,primes,elapsed_seconds,status,covered_by_mfa
58,3,3,"[3, 6, 23, 4]",248,219,220,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
306,4,3,"[3, 44, 22, 57, 4]",2582,1623,1624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
334,4,3,"[3, 35, 30, 41, 4]",2549,1623,1624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
394,4,3,"[3, 51, 22, 57, 4]",2757,1623,1624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
396,4,3,"[3, 36, 30, 41, 4]",2582,1623,1624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
442,4,3,"[3, 8, 19, 67, 4]",1717,1623,1624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446,4,3,"[3, 60, 22, 57, 4]",2982,1623,1624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
504,4,3,"[3, 26, 27, 46, 4]",2206,1623,1624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
589,4,3,"[3, 11, 19, 66, 4]",1760,1623,1624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
597,4,3,"[3, 67, 30, 41, 4]",3605,1623,1624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
616,4,3,"[3, 53, 19, 66, 4]",2684,1623,1624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
645,4,3,"[3, 70, 30, 41, 4]",3704,1623,1624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
652,4,3,"[3, 63, 27, 46, 4]",3316,1623,1624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
660,4,3,"[3, 73, 27, 46, 4]",3616,1623,1624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
749,4,3,"[3, 75, 27, 46, 4]",3676,1623,1624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
779,4,3,"[3, 64, 22, 57, 4]",3082,1623,1624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
787,4,3,"[3, 59, 19, 66, 4]",2816,1623,1624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
806,4,3,"[3, 74, 30, 41, 4]",3836,1623,1624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
815,4,3,"[3, 9, 39, 31, 4]",1711,1623,1624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
824,4,3,"[3, 9, 18, 70, 4]",1729,1623,1624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
833,4,3,"[3, 9, 36, 34, 4]",1711,1623,1624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
846,4,3,"[3, 71, 22, 57, 4]",3257,1623,1624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
877,4,3,"[3, 8, 41, 30, 4]",1702,1623,1624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
879,4,3,"[3, 74, 19, 66, 4]",3146,1623,1624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
883,4,3,"[3, 75, 30, 41, 4]",3869,1623,1624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
890,4,3,"[3, 8, 34, 37, 4]",1702,1623,1624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
914,4,3,"[3, 74, 22, 57, 4]",3332,1623,1624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,4,3,"[3, 75, 19, 66, 4]",3168,1623,1624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1090,4,3,"[3, 75, 22, 57, 4]",3357,1623,1624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1094,4,3,"[3, 9, 23, 55, 4]",1719,1623,1624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,expected_dimension,defect_expected,defect_ambient,backend,primes,elapsed_seconds,status,covered_by_mfa
4,2,2,"[4, 3, 1]",15,9,10,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,3,2,"[4, 20, 4, 1]",164,34,35,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,3,2,"[4, 44, 4, 1]",356,34,35,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,3,2,"[4, 49, 4, 1]",396,34,35,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,3,2,"[4, 52, 4, 1]",420,34,35,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5671,5,2,"[4, 8, 24, 23, 17, 1]",1184,968,969,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5712,5,2,"[4, 8, 14, 30, 29, 1]",1463,968,969,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5769,5,2,"[4, 55, 15, 33, 14, 1]",2016,968,969,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5776,5,2,"[4, 8, 14, 31, 22, 1]",1282,968,969,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5813,5,2,"[4, 55, 23, 23, 17, 1]",2422,968,969,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Empty DataFrame
Columns: [h, exponent, architecture, num_parameters, dimension_computed, ambient_dimension, is_full_dimension, is_minimal, expected_dimension, defect_expected, defect_ambient, backend, primes, elapsed_seconds, status, covered_by_mfa]
Index: []

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,expected_dimension,defect_expected,defect_ambient,backend,primes,elapsed_seconds,status,covered_by_mfa
7,2,2,"[5, 4, 1]",24,14,15,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
439,4,2,"[5, 13, 24, 9, 1]",602,494,495,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
450,4,2,"[5, 13, 21, 16, 1]",690,494,495,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,expected_dimension,defect_expected,defect_ambient,backend,primes,elapsed_seconds,status,covered_by_mfa
4,2,3,"[5, 7, 1]",42,34,35,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,3,3,"[5, 21, 30, 1]",765,714,715,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,expected_dimension,defect_expected,defect_ambient,backend,primes,elapsed_seconds,status,covered_by_mfa
129,3,3,"[6, 29, 64, 1]",2094,2001,2002,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168,3,3,"[6, 23, 82, 1]",2106,2001,2002,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,expected_dimension,defect_expected,defect_ambient,backend,primes,elapsed_seconds,status,covered_by_mfa
93,3,3,"[7, 36, 133, 1]",5173,5004,5005,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,expected_dimension,defect_expected,defect_ambient,backend,primes,elapsed_seconds,status,covered_by_mfa
8,2,2,"[8, 7, 1]",63,35,36,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,3,2,"[8, 20, 14, 1]",454,329,330,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Empty DataFrame
Columns: [h, exponent, architecture, num_parameters, dimension_computed, ambient_dimension, is_full_dimension, is_minimal, expected_dimension, defect_expected, defect_ambient, backend, primes, elapsed_seconds, status, covered_by_mfa]
Index: []