# CSV Processing for Readability

This notebook processes the csv files produced from the random search so that it includes interesting relevant properties such as unimodality and defectivity.

**Warning:** One should be cautious to check if an architecture is truly minimal. The column "is_minimal" is in reference to the search *thus far*. It is possible for it to actually not be minimal and filling because the search has not uncovered a subarchitecture that is filling yet. One should manually check minimality by computing the dimension of the subarchitectures.

In [2]:
import pandas as pd
import math
import ast
import os
from pathlib import Path
from is_unimodal import is_unimodal

## Helper Functions

In [3]:
# lists of architectures to consider (d0,dh,exponent)

ARCHS = [(d0, dh, r) for d0 in range(1, 10) for dh in range(1, 10) for r in range(1, 10)]

In [4]:
def expdim(d: list[int], r) -> int | float:
    """
    Calculates the expected dimension of the architecture
    """

    if type(d)==str:
        d = ast.literal_eval(d)
    
    h = len(d) - 1
    d_0 = d[0]
    d_h = d[h]

    # Term 1: d_h + sum_{i=1}^{h} (d_{i-1}-1)*d_i
    sum_term = sum((d[i-1]-1)*d[i] for i in range(1,h+1))
    sum_term += d_h

    # Term 2: d_h * Binomial(r**{h-1} + d_0 - 1, d_0 - 1)
    n = r**(h-1) + d_0 - 1
    k = d_0 - 1
    
    ambient_term = d_h * math.comb(n, k)

    return min(sum_term, ambient_term)

## Processing

In [5]:
missing = []

for entry in ARCHS:
    d0, dh, r = entry

    input_file = f'../data/raw/{d0}_{dh}_r{r}_architectures.csv'

    if not os.path.exists(input_file):
        missing.append(input_file)
        continue

    df = pd.read_csv(input_file)

    output_file = f'../data/processed/{d0}_{dh}_r{r}_cleaned_architectures.csv'

    df['is_unimodal'] = df['architecture'].apply(is_unimodal)
    df['expected_dimension'] = df['architecture'].apply(lambda x: expdim(x, r))
    df['defect'] = df['expected_dimension'] - df['dimension_computed']
    df = df.sort_values(by=['h', 'is_minimal', 'is_unimodal'], ascending=[True, False, True])

    # print(f"For d_0={d0} and d_h={dh}: the following are counterexamples to the minimal unimodal conjecture.")
    # display(df[(df['is_minimal'] == True) & (df['is_full_dimension'] == True) & (df['is_unimodal'] == False)])

    df.to_csv(output_file, index=False, header=f"Architectures with d_0={d0} and d_h={dh}")

print(f"\nSkipped {len(missing)} missing files.")

C:\Users\daoke\AppData\Local\Temp\ipykernel_18652\2588195640.py:12: DtypeWarning: Columns (0: is_unimodal) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_file)
C:\Users\daoke\AppData\Local\Temp\ipykernel_18652\2588195640.py:12: DtypeWarning: Columns (0: shrunk_hidden_layers) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_file)

Skipped 298 missing files.

In [6]:
for entry in ARCHS:
    d0, dh, r = entry

    input_file = f'../data/raw/{d0}_{dh}_r{r}_architectures.csv'

    if not os.path.exists(input_file):
        missing.append(input_file)
        continue


    df = pd.read_csv(input_file)

    output_file = f'../data/processed/{d0}_{dh}_r{r}_cleaned_architectures.csv'

    df['is_unimodal'] = df['architecture'].apply(is_unimodal)
    df['expected_dimension'] = df['architecture'].apply(lambda x: expdim(x, r))
    df['defect'] = df['expected_dimension'] - df['dimension_computed'] 
    df = df.sort_values(by=['h','is_minimal','is_unimodal'], ascending=[True,False,True])

C:\Users\daoke\AppData\Local\Temp\ipykernel_18652\2036750230.py:11: DtypeWarning: Columns (0: is_unimodal) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_file)
C:\Users\daoke\AppData\Local\Temp\ipykernel_18652\2036750230.py:11: DtypeWarning: Columns (0: shrunk_hidden_layers) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_file)

# CSV Of Counterexamples

Below, we extra the list of counterexamples to the minimal unimodal conjecture and save it to a separate .csv file.

In [7]:
import pandas as pd

ce = pd.DataFrame()

for entry in ARCHS:
    d0, dh, r = entry

    input_file = f'../data/raw/{d0}_{dh}_r{r}_architectures.csv'

    if not os.path.exists(input_file):
        missing.append(input_file)
        continue

    df = pd.read_csv(input_file)

    df['is_unimodal'] = df['architecture'].apply(is_unimodal)
    df['expected_dimension'] = df['architecture'].apply(lambda x: expdim(x, r))
    df['defect'] = df['expected_dimension'] - df['dimension_computed'] 
    
    df['d0'] = d0
    df['dh'] = dh
    df['r'] = r

    df = df.sort_values(by=['h','is_minimal','is_unimodal'], ascending=[True,False,True])

    # Filter for counterexamples (fixed the missing closing brackets)
    counterexamples = df[(df['is_minimal'] == True) & 
                         (df['is_full_dimension'] == True) & 
                         (df['is_unimodal'] == False)]
    
    # Save/append to the master CE dataframe
    if not counterexamples.empty:
        ce = pd.concat([ce, counterexamples], ignore_index=True)

ce.to_csv('../data/processed/counterexamples.csv', index=False)
display(ce)

C:\Users\daoke\AppData\Local\Temp\ipykernel_18652\1534662582.py:14: DtypeWarning: Columns (0: shrunk_hidden_layers) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_file)

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,expected_dimension,defect_expected,...,primes,elapsed_seconds,status,covered_by_mfa,is_unimodal,shrunk_hidden_layers,defect,d0,dh,r
0,7.0,2.0,"[2, 3, 4, 5, 4, 6, 4, 1]",110.0,65.0,65.0,True,True,65,NaN,...,NaN,NaN,NaN,NaN,False,NaN,0.0,2,1,2
1,8.0,2.0,"[2, 3, 3, 5, 7, 6, 7, 4, 1]",181.0,129.0,129.0,True,True,129,NaN,...,NaN,NaN,NaN,NaN,False,NaN,0.0,2,1,2
2,8.0,2.0,"[2, 3, 3, 6, 7, 6, 7, 3, 1]",183.0,129.0,129.0,True,True,129,NaN,...,NaN,NaN,NaN,NaN,False,NaN,0.0,2,1,2
3,8.0,2.0,"[2, 3, 4, 5, 7, 6, 7, 3, 1]",181.0,129.0,129.0,True,True,129,NaN,...,NaN,NaN,NaN,NaN,False,NaN,0.0,2,1,2
4,8.0,2.0,"[2, 3, 3, 4, 7, 6, 8, 4, 1]",181.0,129.0,129.0,True,True,129,NaN,...,NaN,NaN,NaN,NaN,False,NaN,0.0,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
803,5.0,3.0,"[3, 8, 45, 33, 51, 1]",3603.0,3403.0,3403.0,True,True,3403,NaN,...,NaN,NaN,NaN,NaN,False,NaN,0.0,3,1,3
804,5.0,2.0,"[5, 55, 53, 54, 35, 1]",7977.0,4845.0,4845.0,True,True,4845,NaN,...,NaN,NaN,NaN,NaN,False,NaN,0.0,5,1,2
805,5.0,2.0,"[5, 54, 55, 51, 52, 1]",8749.0,4845.0,4845.0,True,True,4845,NaN,...,NaN,NaN,NaN,NaN,False,NaN,0.0,5,1,2
806,5.0,2.0,"[5, 25, 55, 51, 53, 1]",7061.0,4845.0,4845.0,True,True,4845,NaN,...,NaN,NaN,NaN,NaN,False,NaN,0.0,5,1,2
807,4.0,2.0,"[8, 136, 111, 139, 1]",31752.0,6435.0,6435.0,True,True,6435,NaN,...,NaN,NaN,NaN,NaN,False,NaN,0.0,8,1,2

# CSV of Hypersurfaces

In [8]:
import pandas as pd

ce = pd.DataFrame()

for entry in ARCHS:
    d0, dh, r = entry

    input_file = f'../data/raw/{d0}_{dh}_r{r}_architectures.csv'

    if not os.path.exists(input_file):
        missing.append(input_file)
        continue

    df = pd.read_csv(input_file)

    df['is_unimodal'] = df['architecture'].apply(is_unimodal)
    df['expected_dimension'] = df['architecture'].apply(lambda x: expdim(x, r))
    df['defect'] = df['expected_dimension'] - df['dimension_computed'] 
    
    df['d0'] = d0
    df['dh'] = dh
    df['r'] = r

    # Filter for hypersurfaces (fixed the missing closing brackets)
    hypersurfaces = df[(df['dimension_computed'] == df['ambient_dimension']-1)]
    
    # Save/append to the master CE dataframe
    if not hypersurfaces.empty:
        ce = pd.concat([ce, hypersurfaces], ignore_index=True)


ce = ce.sort_values(by=['h','dimension_computed','num_parameters'], ascending=[True,True,True])
ce.to_csv('../data/processed/codimension_one.csv', index=False)
display(ce)

C:\Users\daoke\AppData\Local\Temp\ipykernel_18652\3150087935.py:14: DtypeWarning: Columns (0: is_unimodal) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_file)
C:\Users\daoke\AppData\Local\Temp\ipykernel_18652\3150087935.py:14: DtypeWarning: Columns (0: shrunk_hidden_layers) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_file)

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,expected_dimension,defect_expected,...,primes,elapsed_seconds,status,covered_by_mfa,is_unimodal,shrunk_hidden_layers,defect,d0,dh,r
0,2.0,2.0,"[2, 1, 1]",3.0,2.0,3.0,False,False,2,NaN,...,NaN,NaN,NaN,NaN,True,NaN,0.0,2,1,2
941,2.0,1.0,"[2, 1, 2]",4.0,3.0,4.0,False,False,3,NaN,...,NaN,NaN,NaN,NaN,False,NaN,0.0,2,2,1
606,2.0,4.0,"[2, 2, 1]",6.0,4.0,5.0,False,False,4,NaN,...,NaN,NaN,NaN,NaN,True,NaN,0.0,2,1,4
1166,2.0,2.0,"[3, 2, 1]",8.0,5.0,6.0,False,False,6,NaN,...,NaN,NaN,NaN,NaN,True,NaN,1.0,3,1,2
900,2.0,6.0,"[2, 3, 1]",9.0,6.0,7.0,False,False,6,NaN,...,NaN,NaN,NaN,NaN,True,NaN,0.0,2,1,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
484,8.0,2.0,"[2, 9, 9, 9, 6, 7, 5, 9, 1]",365.0,128.0,129.0,False,False,129,NaN,...,NaN,NaN,NaN,NaN,False,NaN,1.0,2,1,2
510,8.0,2.0,"[2, 4, 3, 30, 15, 7, 4, 2, 1]",703.0,128.0,129.0,False,False,129,NaN,...,NaN,NaN,NaN,NaN,False,NaN,1.0,2,1,2
511,8.0,2.0,"[2, 4, 3, 32, 16, 7, 4, 2, 1]",778.0,128.0,129.0,False,False,129,NaN,...,NaN,NaN,NaN,NaN,False,NaN,1.0,2,1,2
1035,8.0,2.0,"[2, 3, 4, 5, 10, 10, 8, 4, 2]",308.0,257.0,258.0,False,False,258,1.0,...,"(10000019, 19511957)",0.655151,maximal_subarchitecture_of_recorded_mfa,"[[2, 3, 4, 6, 10, 10, 8, 4, 2], [2, 3, 5, 5, 1...",True,"[2, 3]",1.0,2,2,2
1030,8.0,2.0,"[2, 4, 4, 5, 10, 10, 8, 4, 2]",314.0,257.0,258.0,False,False,258,NaN,...,NaN,NaN,NaN,NaN,True,NaN,1.0,2,2,2