# CSV Processing for Readability

This notebook processes the csv files produced from the random search so that it includes interesting relevant properties such as unimodality and defectivity.

**Warning:** One should be cautious to check if an architecture is truly minimal. The column "is_minimal" is in reference to the search *thus far*. It is possible for it to actually not be minimal and filling because the search has not uncovered a subarchitecture that is filling yet. One should manually check minimality by computing the dimension of the subarchitectures.

In [1]:
import pandas as pd
import math
import ast
import os

## Helper Functions

In [2]:
ARCHS = [(2,1,2), (2,1,3), (2,1,4), (2,1,5), (2,1,6), (2,1,7), (2,1,8), 
         (2,1,12),
         (2,2,2),
         (2,3,2),
         (3,1,2),
         (3,3,6)]

In [3]:
# %load ../is_unimodal.py

def is_unimodal(data):
    # data should be string formatted as '[1, 2, 3]'
    data = ast.literal_eval(data)
    n = len(data)
    
    if n <= 2:
        return True
    
    i = 0
    
    # walk up the non-decreasing slope
    while i + 1 < n and data[i] <= data[i + 1]:
        i += 1

    # walk down the non-increasing slope
    while i + 1 < n and data[i] >= data[i + 1]:
        i += 1
        
    # check if we reached the end
    return i == n - 1

In [4]:
def expdim(d: list[int], r) -> int | float:
    """
    Calculates the expected dimension of the architecture
    """

    if type(d)==str:
        d = ast.literal_eval(d)
    
    h = len(d) - 1
    d_0 = d[0]
    d_h = d[h]

    # Term 1: d_h + sum_{i=1}^{h} (d_{i-1}-1)*d_i
    sum_term = sum((d[i-1]-1)*d[i] for i in range(1,h+1))
    sum_term += d_h

    # Term 2: d_h * Binomial(r**{h-1} + d_0 - 1, d_0 - 1)
    n = r**(h-1) + d_0 - 1
    k = d_0 - 1
    
    ambient_term = d_h * math.comb(n, k)

    return min(sum_term, ambient_term)

## Processing

In [5]:
for entry in ARCHS:
    d0 = entry[0]
    dh = entry[1]
    r = entry[2]

    df = pd.read_csv(f'../data/raw/{d0}_{dh}_r{r}_architectures.csv')

    output_file = f'../data/processed/{d0}_{dh}_r{r}_cleaned_architectures.csv'

    df['is_unimodal'] = df['architecture'].apply(is_unimodal)
    df['expected_dimension'] = df['architecture'].apply(lambda x: expdim(x, r))
    df['defect'] = df['expected_dimension'] - df['dimension_computed'] 
    df = df.sort_values(by=['h','is_minimal','is_unimodal'], ascending=[True,False,True])

    print(f"For d_0={d0} and d_h={dh}: the following are counterexamples to the minimal unimodal conjecture.")
    display(df[(df['is_minimal']==True) & (df['is_full_dimension']==True) & (df['is_unimodal']==False)])

    df.to_csv(output_file, index=False, header=f"Architectures with d_0={d0} and d_h={dh}")

For d_0=2 and d_h=1: the following are counterexamples to the minimal unimodal conjecture.

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,is_unimodal,expected_dimension,defect
4729,7,2,"[2, 3, 4, 5, 4, 6, 4, 1]",110,65,65,True,True,False,65,0
4910,8,2,"[2, 3, 3, 5, 7, 6, 7, 4, 1]",181,129,129,True,True,False,129,0
4911,8,2,"[2, 3, 3, 6, 7, 6, 7, 3, 1]",183,129,129,True,True,False,129,0
4915,8,2,"[2, 3, 4, 5, 7, 6, 7, 3, 1]",181,129,129,True,True,False,129,0
4926,8,2,"[2, 3, 3, 4, 7, 6, 8, 4, 1]",181,129,129,True,True,False,129,0
4930,8,2,"[2, 3, 3, 5, 7, 6, 8, 3, 1]",182,129,129,True,True,False,129,0
4937,8,2,"[2, 3, 4, 4, 7, 6, 8, 3, 1]",179,129,129,True,True,False,129,0
4942,8,2,"[2, 3, 4, 6, 5, 8, 6, 3, 1]",181,129,129,True,True,False,129,0
4975,8,2,"[2, 3, 4, 5, 4, 7, 9, 3, 1]",179,129,129,True,True,False,129,0
5000,8,2,"[2, 3, 3, 4, 7, 6, 7, 6, 1]",187,129,129,True,True,False,129,0
5001,8,2,"[2, 3, 4, 4, 7, 6, 7, 5, 1]",186,129,129,True,True,False,129,0
5002,8,2,"[2, 3, 4, 5, 7, 5, 7, 5, 1]",183,129,129,True,True,False,129,0
5003,8,2,"[2, 3, 4, 6, 7, 5, 7, 4, 1]",186,129,129,True,True,False,129,0
5012,8,2,"[2, 3, 3, 5, 7, 5, 8, 5, 1]",185,129,129,True,True,False,129,0
5021,8,2,"[2, 3, 4, 5, 4, 7, 8, 5, 1]",187,129,129,True,True,False,129,0
5022,8,2,"[2, 3, 4, 5, 4, 8, 8, 4, 1]",190,129,129,True,True,False,129,0
5023,8,2,"[2, 3, 4, 5, 6, 5, 8, 5, 1]",183,129,129,True,True,False,129,0
5024,8,2,"[2, 3, 4, 5, 7, 5, 8, 4, 1]",184,129,129,True,True,False,129,0
5025,8,2,"[2, 3, 4, 5, 8, 5, 7, 4, 1]",185,129,129,True,True,False,129,0
5071,8,2,"[2, 3, 4, 5, 4, 6, 9, 5, 1]",186,129,129,True,True,False,129,0
5179,8,2,"[2, 3, 3, 4, 7, 5, 9, 6, 1]",195,129,129,True,True,False,129,0
5182,8,2,"[2, 3, 3, 5, 6, 5, 9, 6, 1]",195,129,129,True,True,False,129,0
5355,8,2,"[2, 3, 4, 6, 6, 5, 7, 7, 1]",199,129,129,True,True,False,129,0
5641,8,2,"[2, 3, 3, 6, 6, 5, 8, 8, 1]",211,129,129,True,True,False,129,0
5646,8,2,"[2, 3, 4, 4, 7, 5, 8, 8, 1]",209,129,129,True,True,False,129,0

For d_0=2 and d_h=1: the following are counterexamples to the minimal unimodal conjecture.

Empty DataFrame
Columns: [h, exponent, architecture, num_parameters, dimension_computed, ambient_dimension, is_full_dimension, is_minimal, is_unimodal, expected_dimension, defect]
Index: []

For d_0=2 and d_h=1: the following are counterexamples to the minimal unimodal conjecture.

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,is_unimodal,expected_dimension,defect
631,5,4,"[2, 4, 9, 8, 21, 1]",305,257,257,True,True,False,257,0
750,5,4,"[2, 5, 10, 7, 22, 1]",306,257,257,True,True,False,257,0
893,5,4,"[2, 4, 11, 10, 12, 1]",294,257,257,True,True,False,257,0
1103,5,4,"[2, 3, 10, 8, 21, 1]",305,257,257,True,True,False,257,0
1358,5,4,"[2, 4, 12, 8, 17, 1]",305,257,257,True,True,False,257,0
1427,5,4,"[2, 5, 11, 9, 14, 1]",304,257,257,True,True,False,257,0
1520,5,4,"[2, 3, 11, 8, 19, 1]",298,257,257,True,True,False,257,0
1700,5,4,"[2, 4, 11, 7, 22, 1]",305,257,257,True,True,False,257,0
1757,5,4,"[2, 4, 10, 7, 23, 1]",302,257,257,True,True,False,257,0
1794,5,4,"[2, 3, 10, 9, 17, 1]",296,257,257,True,True,False,257,0
1799,5,4,"[2, 5, 11, 8, 17, 1]",306,257,257,True,True,False,257,0
1804,5,4,"[2, 4, 10, 9, 16, 1]",298,257,257,True,True,False,257,0
1846,5,4,"[2, 4, 13, 9, 13, 1]",307,257,257,True,True,False,257,0
1860,5,4,"[2, 5, 12, 9, 13, 1]",308,257,257,True,True,False,257,0
1868,5,4,"[2, 4, 11, 8, 18, 1]",302,257,257,True,True,False,257,0
1918,5,4,"[2, 3, 12, 10, 13, 1]",305,257,257,True,True,False,257,0
1953,5,4,"[2, 3, 11, 9, 16, 1]",298,257,257,True,True,False,257,0
1971,5,4,"[2, 4, 10, 8, 19, 1]",299,257,257,True,True,False,257,0
1988,5,4,"[2, 5, 11, 7, 21, 1]",310,257,257,True,True,False,257,0
2019,5,4,"[2, 3, 9, 8, 22, 1]",303,257,257,True,True,False,257,0
2022,5,4,"[2, 4, 12, 9, 14, 1]",304,257,257,True,True,False,257,0
2042,5,4,"[2, 5, 9, 8, 20, 1]",307,257,257,True,True,False,257,0
2120,5,4,"[2, 4, 11, 9, 15, 1]",301,257,257,True,True,False,257,0
2130,5,4,"[2, 3, 11, 10, 14, 1]",303,257,257,True,True,False,257,0
2131,5,4,"[2, 4, 12, 7, 21, 1]",308,257,257,True,True,False,257,0
2135,5,4,"[2, 4, 12, 10, 11, 1]",297,257,257,True,True,False,257,0
3113,5,4,"[2, 9, 5, 8, 26, 1]",337,257,257,True,True,False,257,0
3126,5,4,"[2, 7, 6, 7, 30, 1]",338,257,257,True,True,False,257,0
3128,5,4,"[2, 20, 6, 7, 29, 1]",434,257,257,True,True,False,257,0
3147,5,4,"[2, 6, 5, 30, 4, 1]",316,257,257,True,True,False,257,0
3180,5,4,"[2, 8, 5, 7, 30, 1]",331,257,257,True,True,False,257,0
3208,5,4,"[2, 5, 9, 7, 24, 1]",310,257,257,True,True,False,257,0
3224,5,4,"[2, 8, 7, 7, 27, 1]",337,257,257,True,True,False,257,0
3230,5,4,"[2, 3, 8, 7, 29, 1]",318,257,257,True,True,False,257,0
3231,5,4,"[2, 7, 8, 7, 26, 1]",334,257,257,True,True,False,257,0
3235,5,4,"[2, 3, 11, 7, 24, 1]",308,257,257,True,True,False,257,0
3276,5,4,"[2, 4, 9, 7, 25, 1]",307,257,257,True,True,False,257,0
3289,5,4,"[2, 3, 10, 7, 25, 1]",306,257,257,True,True,False,257,0

For d_0=2 and d_h=1: the following are counterexamples to the minimal unimodal conjecture.

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,is_unimodal,expected_dimension,defect
396,5,5,"[2, 36, 4, 32, 19, 1]",971,626,626,True,True,False,626,0
421,5,5,"[2, 36, 28, 12, 28, 1]",1780,626,626,True,True,False,626,0
461,5,5,"[2, 8, 5, 29, 26, 1]",981,626,626,True,True,False,626,0
462,5,5,"[2, 23, 13, 13, 34, 1]",990,626,626,True,True,False,626,0
465,5,5,"[2, 8, 6, 31, 15, 1]",730,626,626,True,True,False,626,0
...,...,...,...,...,...,...,...,...,...,...,...
1097,5,5,"[2, 37, 13, 27, 9, 1]",1158,626,626,True,True,False,626,0
1099,5,5,"[2, 34, 10, 32, 11, 1]",1091,626,626,True,True,False,626,0
1103,5,5,"[2, 30, 20, 14, 25, 1]",1315,626,626,True,True,False,626,0
1110,5,5,"[2, 33, 16, 19, 17, 1]",1238,626,626,True,True,False,626,0
1114,5,5,"[2, 30, 13, 16, 25, 1]",1083,626,626,True,True,False,626,0

For d_0=2 and d_h=1: the following are counterexamples to the minimal unimodal conjecture.

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,is_unimodal,expected_dimension,defect
594,4,6,"[2, 6, 5, 38, 1]",270,217,217,True,True,False,217,0
827,5,6,"[2, 36, 20, 47, 36, 1]",3460,1297,1297,True,True,False,1297,0
830,5,6,"[2, 11, 8, 49, 21, 1]",1552,1297,1297,True,True,False,1297,0
831,5,6,"[2, 43, 15, 37, 32, 1]",2502,1297,1297,True,True,False,1297,0
834,5,6,"[2, 15, 42, 26, 39, 1]",2805,1297,1297,True,True,False,1297,0
840,5,6,"[2, 48, 20, 46, 12, 1]",2540,1297,1297,True,True,False,1297,0
841,5,6,"[2, 37, 12, 28, 43, 1]",2101,1297,1297,True,True,False,1297,0

For d_0=2 and d_h=1: the following are counterexamples to the minimal unimodal conjecture.

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,is_unimodal,expected_dimension,defect
952,4,7,"[2, 7, 6, 51, 1]",413,344,344,True,True,False,344,0

For d_0=2 and d_h=1: the following are counterexamples to the minimal unimodal conjecture.

Empty DataFrame
Columns: [h, exponent, architecture, num_parameters, dimension_computed, ambient_dimension, is_full_dimension, is_minimal, is_unimodal, expected_dimension, defect]
Index: []

For d_0=2 and d_h=1: the following are counterexamples to the minimal unimodal conjecture.

Empty DataFrame
Columns: [h, exponent, architecture, num_parameters, dimension_computed, ambient_dimension, is_full_dimension, is_minimal, is_unimodal, expected_dimension, defect]
Index: []

For d_0=2 and d_h=2: the following are counterexamples to the minimal unimodal conjecture.

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,is_unimodal,expected_dimension,defect
5805,9,2,"[2, 3, 4, 5, 18, 12, 13, 12, 4, 2]",712,514,514,True,True,False,514,0
6160,9,2,"[2, 3, 6, 9, 10, 15, 11, 12, 4, 2]",671,514,514,True,True,False,514,0
6172,9,2,"[2, 4, 5, 7, 10, 15, 11, 12, 4, 2]",636,514,514,True,True,False,514,0
6236,9,2,"[2, 3, 4, 4, 10, 17, 11, 12, 4, 2]",619,514,514,True,True,False,514,0

For d_0=2 and d_h=3: the following are counterexamples to the minimal unimodal conjecture.

Empty DataFrame
Columns: [h, exponent, architecture, num_parameters, dimension_computed, ambient_dimension, is_full_dimension, is_minimal, is_unimodal, expected_dimension, defect]
Index: []

For d_0=3 and d_h=1: the following are counterexamples to the minimal unimodal conjecture.

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,is_unimodal,expected_dimension,defect
4841,7,2,"[3, 12, 10, 26, 38, 23, 9, 1]",2494,2145,2145,True,True,False,2145,0
5093,7,2,"[3, 5, 20, 28, 27, 30, 10, 1]",2551,2145,2145,True,True,False,2145,0
5100,7,2,"[3, 5, 20, 28, 27, 29, 12, 1]",2574,2145,2145,True,True,False,2145,0
5152,7,2,"[3, 5, 20, 30, 26, 30, 10, 1]",2585,2145,2145,True,True,False,2145,0
5164,7,2,"[3, 5, 14, 29, 28, 30, 6, 1]",2329,2145,2145,True,True,False,2145,0
5167,7,2,"[3, 5, 12, 30, 28, 30, 6, 1]",2301,2145,2145,True,True,False,2145,0
5178,7,2,"[3, 5, 13, 29, 28, 30, 7, 1]",2326,2145,2145,True,True,False,2145,0
5179,7,2,"[3, 5, 14, 30, 28, 29, 6, 1]",2337,2145,2145,True,True,False,2145,0
5184,7,2,"[3, 5, 14, 30, 27, 29, 8, 1]",2338,2145,2145,True,True,False,2145,0
5186,7,2,"[3, 5, 12, 30, 28, 29, 8, 1]",2327,2145,2145,True,True,False,2145,0
5193,7,2,"[3, 5, 13, 30, 28, 30, 5, 1]",2305,2145,2145,True,True,False,2145,0
5197,7,2,"[3, 5, 15, 30, 28, 30, 4, 1]",2344,2145,2145,True,True,False,2145,0
5209,7,2,"[3, 5, 15, 29, 28, 29, 7, 1]",2359,2145,2145,True,True,False,2145,0
5211,7,2,"[3, 5, 13, 30, 28, 29, 7, 1]",2332,2145,2145,True,True,False,2145,0
5215,7,2,"[3, 5, 15, 29, 27, 30, 8, 1]",2366,2145,2145,True,True,False,2145,0
5218,7,2,"[3, 5, 13, 30, 27, 30, 8, 1]",2338,2145,2145,True,True,False,2145,0
5222,7,2,"[3, 5, 15, 30, 28, 29, 5, 1]",2342,2145,2145,True,True,False,2145,0
5224,7,2,"[3, 5, 13, 29, 28, 29, 8, 1]",2321,2145,2145,True,True,False,2145,0
5226,7,2,"[3, 5, 12, 29, 28, 30, 8, 1]",2323,2145,2145,True,True,False,2145,0
5228,7,2,"[3, 5, 10, 30, 28, 30, 8, 1]",2293,2145,2145,True,True,False,2145,0
5231,7,2,"[3, 5, 14, 30, 27, 30, 7, 1]",2342,2145,2145,True,True,False,2145,0
5235,7,2,"[3, 5, 11, 30, 28, 30, 7, 1]",2297,2145,2145,True,True,False,2145,0
5342,7,2,"[3, 5, 13, 29, 26, 30, 12, 1]",2363,2145,2145,True,True,False,2145,0
5369,7,2,"[3, 5, 15, 29, 26, 30, 11, 1]",2400,2145,2145,True,True,False,2145,0
5539,7,2,"[3, 10, 21, 19, 38, 28, 7, 1]",2628,2145,2145,True,True,False,2145,0
5588,7,2,"[3, 9, 21, 18, 39, 28, 7, 1]",2591,2145,2145,True,True,False,2145,0
5661,7,2,"[3, 7, 21, 19, 37, 29, 7, 1]",2553,2145,2145,True,True,False,2145,0
5662,7,2,"[3, 8, 18, 17, 38, 30, 7, 1]",2477,2145,2145,True,True,False,2145,0
5668,7,2,"[3, 8, 21, 18, 39, 30, 4, 1]",2566,2145,2145,True,True,False,2145,0
5693,7,2,"[3, 8, 20, 18, 39, 29, 5, 1]",2527,2145,2145,True,True,False,2145,0
5695,7,2,"[3, 5, 21, 19, 37, 30, 6, 1]",2518,2145,2145,True,True,False,2145,0
5731,7,2,"[3, 7, 23, 21, 38, 25, 9, 1]",2647,2145,2145,True,True,False,2145,0
6457,7,2,"[3, 10, 8, 23, 38, 25, 9, 1]",2352,2145,2145,True,True,False,2145,0
6550,7,2,"[3, 10, 9, 23, 38, 25, 8, 1]",2359,2145,2145,True,True,False,2145,0
6555,7,2,"[3, 5, 13, 30, 26, 29, 12, 1]",2364,2145,2145,True,True,False,2145,0

For d_0=3 and d_h=3: the following are counterexamples to the minimal unimodal conjecture.

Empty DataFrame
Columns: [h, exponent, architecture, num_parameters, dimension_computed, ambient_dimension, is_full_dimension, is_minimal, is_unimodal, expected_dimension, defect]
Index: []

In [6]:
for entry in ARCHS:
    d0 = entry[0]
    dh = entry[1]
    r = entry[2]

    df = pd.read_csv(f'../data/raw/{d0}_{dh}_r{r}_architectures.csv')

    output_file = f'../data/processed/{d0}_{dh}_r{r}_cleaned_architectures.csv'

    df['is_unimodal'] = df['architecture'].apply(is_unimodal)
    df['expected_dimension'] = df['architecture'].apply(lambda x: expdim(x, r))
    df['defect'] = df['expected_dimension'] - df['dimension_computed'] 
    df = df.sort_values(by=['h','is_minimal','is_unimodal'], ascending=[True,False,True])

# CSV Of Counterexamples

Below, we extra the list of counterexamples to the minimal unimodal conjecture and save it to a separate .csv file.

In [7]:
import pandas as pd

ce = pd.DataFrame()

for entry in ARCHS:

    d0, dh, r = entry

    df = pd.read_csv(f'../data/raw/{d0}_{dh}_r{r}_architectures.csv')

    df['is_unimodal'] = df['architecture'].apply(is_unimodal)
    df['expected_dimension'] = df['architecture'].apply(lambda x: expdim(x, r))
    df['defect'] = df['expected_dimension'] - df['dimension_computed'] 
    
    df['d0'] = d0
    df['dh'] = dh
    df['r'] = r

    df = df.sort_values(by=['h','is_minimal','is_unimodal'], ascending=[True,False,True])

    # Filter for counterexamples (fixed the missing closing brackets)
    counterexamples = df[(df['is_minimal'] == True) & 
                         (df['is_full_dimension'] == True) & 
                         (df['is_unimodal'] == False)]
    
    # Save/append to the master CE dataframe
    if not counterexamples.empty:
        ce = pd.concat([ce, counterexamples], ignore_index=True)

ce.to_csv('../data/processed/counterexamples.csv', index=False)
display(ce)

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,is_unimodal,expected_dimension,defect,d0,dh,r
0,7,2,"[2, 3, 4, 5, 4, 6, 4, 1]",110,65,65,True,True,False,65,0,2,1,2
1,8,2,"[2, 3, 3, 5, 7, 6, 7, 4, 1]",181,129,129,True,True,False,129,0,2,1,2
2,8,2,"[2, 3, 3, 6, 7, 6, 7, 3, 1]",183,129,129,True,True,False,129,0,2,1,2
3,8,2,"[2, 3, 4, 5, 7, 6, 7, 3, 1]",181,129,129,True,True,False,129,0,2,1,2
4,8,2,"[2, 3, 3, 4, 7, 6, 8, 4, 1]",181,129,129,True,True,False,129,0,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221,7,2,"[3, 5, 21, 19, 37, 30, 6, 1]",2518,2145,2145,True,True,False,2145,0,3,1,2
222,7,2,"[3, 7, 23, 21, 38, 25, 9, 1]",2647,2145,2145,True,True,False,2145,0,3,1,2
223,7,2,"[3, 10, 8, 23, 38, 25, 9, 1]",2352,2145,2145,True,True,False,2145,0,3,1,2
224,7,2,"[3, 10, 9, 23, 38, 25, 8, 1]",2359,2145,2145,True,True,False,2145,0,3,1,2
225,7,2,"[3, 5, 13, 30, 26, 29, 12, 1]",2364,2145,2145,True,True,False,2145,0,3,1,2