# Sequential CSV Dimension Fill — GPU Only, Windows-Safe Checkpoints

This notebook fills dimensions using **only** `dim_backprop_gpu_only.py` and its CuPy/CUDA finite-field Jacobian-rank computation.

The search is driven by the MFAs already recorded in each CSV:

1. Read rows whose `is_minimal` value is true.

2. Group those minimal filling architectures by depth `h` and exponent.

3. Build the finite rectangular search box whose coordinatewise upper corner is the coordinatewise maximum of those MFAs.

4. Process candidates from small to large.

5. For each candidate:

   - if it is a **strict coordinatewise predecessor of at least one recorded MFA**, compute its dimension unless a valid row already exists;

   - otherwise skip it without calling the dimension oracle.

6. Save new results through retrying, resumable checkpoints.

On Windows, Excel, OneDrive, antivirus software, or another Python process may temporarily lock the destination CSV. If replacement remains blocked after several retries, the notebook writes the complete current data to `NAME.locked_checkpoint.csv` and continues instead of losing the GPU run. A later run automatically resumes from that checkpoint when it is newer than the primary CSV.

## Configuration

Place this notebook, `dim_backprop_gpu_only.py`, and the `Data/` directory in the same project folder. The module loader also recognizes common alternate filenames, including the uploaded filename with `(2)` appended.


Note: This is kind of ugly. Can probably rewrite this.

In [249]:
from pathlib import Path

# Paths
DATA_DIR = Path("Data")
FALLBACK_DATA_DIRS = [Path("data/raw"), Path("../data/raw")]

# None means every *_architectures.csv file in DATA_DIR.
# Example: CSV_FILES = [Path("Data/2_2_architectures.csv")]
CSV_FILES = None

# Set an explicit module path only when automatic discovery is undesirable.
GPU_MODULE_PATH = None
GPU_MODULE_FILENAMES = ["dim_backprop_gpu_only.py"]

# Search filters
# None means use every (h, exponent) group represented by an is_minimal=True row.
H_VALUES = None
EXPONENTS = None
DEFAULT_EXPONENT = 2

# Hidden widths begin at 1. A candidate must be strictly coordinatewise below at least one marked MFA before it is eligible for a dimension computation.
MIN_HIDDEN_WIDTH = 1

# The rectangular list can be inspected before running. Set a finite guard if desired.
MAX_SEARCH_BOX_SIZE = None

# GPU dimension oracle
PRIMES = (10_000_019, 19_511_957) # prefer to pick larger primes and multiple primes
SEED = 20260630
RANK_WORKSPACE_BYTES = 512 * 1024**2
DIMENSION_VERBOSE = False

# Execution controls
RUN_FILL = True
MAX_NEW_EVALUATIONS_PER_FILE = None # Change this to limit number of evaluations needed to be performed.

# 1 preserves the old crash-safe behavior. Increasing this reduces CSV write overhead.
SAVE_EVERY_N_NEW_ROWS = 1_000 
PROGRESS_EVERY = 1_000

# Windows may temporarily deny os.replace() when the target CSV is open in
# Excel, synchronized by OneDrive, scanned by antivirus, or used elsewhere.
SAVE_REPLACE_RETRIES = 8
SAVE_RETRY_DELAY_SECONDS = 1.0
SAVE_LOCKED_CHECKPOINT_SUFFIX = ".locked_checkpoint"
CONTINUE_WITH_LOCKED_CHECKPOINT = True

# A full-dimensional strict predecessor contradicts the recorded MFA flag.
# The row is saved first, then the notebook stops when this is True.
STOP_ON_MFA_CONTRADICTION = True

## Load the GPU-only dimension module

In [250]:
import ast
import importlib.util
import itertools
import math
import os
import sys
import time
import uuid
from collections import defaultdict
from typing import Iterable, Iterator, Sequence
import pandas as pd

In [251]:
def discover_gpu_module_path() -> Path:
    if GPU_MODULE_PATH is not None:
        path = Path(GPU_MODULE_PATH).expanduser().resolve()
        if not path.exists():
            raise FileNotFoundError(f"GPU_MODULE_PATH does not exist: {path}")
        return path

    roots = [Path.cwd(), Path.cwd().parent, Path("/mnt/data")]
    checked = []
    for root in roots:
        for filename in GPU_MODULE_FILENAMES:
            candidate = (root / filename).resolve()
            checked.append(candidate)
            if candidate.exists():
                return candidate

    checked_text = "\n".join(f"  - {path}" for path in checked)
    raise FileNotFoundError(
        "Could not find the GPU-only dimension module. Checked:\n" + checked_text
    )

In [252]:
def load_gpu_dimension_module(path: Path):
    module_name = "_mfa_dim_backprop_gpu_only"
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Could not create an import specification for {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module

In [253]:
GPU_MODULE_FILE = discover_gpu_module_path()
gpu_dimension_module = load_gpu_dimension_module(GPU_MODULE_FILE)
compute_dimension = gpu_dimension_module.compute_dimension
gpu_information = gpu_dimension_module.gpu_information

print("GPU dimension module:", GPU_MODULE_FILE)
print("GPU information:", gpu_information())

GPU dimension module: C:\Users\daoke\Documents\GitHub\MFA_PNNs\notebooks\dim_backprop_gpu_only.py
GPU information: {'device_id': 0, 'name': 'NVIDIA GeForce RTX 4070 SUPER', 'device_count': 1, 'cupy_version': '14.1.1', 'cuda_runtime_version': 12090, 'driver_version': 12060}

## CSV and architecture helpers

In [254]:
def choose_data_dir() -> Path:
    if DATA_DIR.exists():
        return DATA_DIR
    for candidate in FALLBACK_DATA_DIRS:
        if candidate.exists():
            print(f"DATA_DIR={DATA_DIR!s} was not found. Using {candidate!s}.")
            return candidate
    return DATA_DIR


def find_csv_files(data_dir: Path) -> list[Path]:
    if CSV_FILES is not None:
        return [Path(path) for path in CSV_FILES]
    return sorted(data_dir.glob("*_architectures.csv"))



def locked_checkpoint_path(path: Path) -> Path:
    """Return the stable fallback path used when Windows locks the main CSV."""
    path = Path(path)
    return path.with_name(f"{path.stem}{SAVE_LOCKED_CHECKPOINT_SUFFIX}{path.suffix}")


def preferred_csv_source(path: Path) -> Path:
    """Prefer a newer locked-file checkpoint so interrupted runs resume safely."""
    path = Path(path)
    checkpoint = locked_checkpoint_path(path)

    if checkpoint.exists() and (
        not path.exists() or checkpoint.stat().st_mtime_ns > path.stat().st_mtime_ns
    ):
        print(
            f"Resuming from newer checkpoint {checkpoint.name!r} because "
            f"{path.name!r} was previously locked."
        )
        return checkpoint

    return path

In [255]:
def read_architecture_csv(path: Path) -> pd.DataFrame:
    source = preferred_csv_source(path)
    if source.exists():
        try:
            df = pd.read_csv(source)
        except Exception:
            # Compatibility with older processed files containing a preamble line.
            df = pd.read_csv(source, skiprows=1)
    else:
        df = pd.DataFrame()

    required_columns = [
        "h",
        "exponent",
        "architecture",
        "num_parameters",
        "dimension_computed",
        "ambient_dimension",
        "is_full_dimension",
        "is_minimal",
    ]
    audit_columns = [
        "expected_dimension",
        "defect_expected",
        "defect_ambient",
        "backend",
        "primes",
        "elapsed_seconds",
        "status",
        "covered_by_mfa",
    ]
    for column in required_columns + audit_columns:
        if column not in df.columns:
            df[column] = pd.Series(dtype="object")
    return df

def parse_architecture(value) -> tuple[int, ...]:
    if isinstance(value, (tuple, list)):
        architecture = tuple(int(x) for x in value)
    else:
        if pd.isna(value):
            raise ValueError("missing architecture")
        architecture = tuple(int(x) for x in ast.literal_eval(str(value)))
    if len(architecture) < 2 or any(width <= 0 for width in architecture):
        raise ValueError(f"invalid architecture: {architecture}")
    return architecture


def architecture_string(architecture: Sequence[int]) -> str:
    return str([int(width) for width in architecture])


def truthy(value) -> bool:
    if isinstance(value, bool):
        return value
    if pd.isna(value):
        return False
    return str(value).strip().lower() in {"true", "1", "yes", "y", "t"}


def infer_d0_dL_from_filename(path: Path) -> tuple[int, int]:
    parts = path.stem.split("_")
    if len(parts) >= 3 and parts[-1] == "architectures":
        return int(parts[0]), int(parts[1])
    raise ValueError(
        f"Could not infer d0 and dL from {path.name!r}; expected a name such as "
        "2_1_architectures.csv."
    )


def parameter_count(architecture: Sequence[int]) -> int:
    return sum(
        int(input_width) * int(output_width)
        for input_width, output_width in zip(architecture[:-1], architecture[1:])
    )


def hidden_leq(left: Sequence[int], right: Sequence[int]) -> bool:
    return len(left) == len(right) and all(int(a) <= int(b) for a, b in zip(left, right))


def full_architecture(d0: int, hidden: Sequence[int], dL: int) -> tuple[int, ...]:
    return (int(d0), *(int(width) for width in hidden), int(dL))


def stable_seed(
    base_seed: int,
    hidden: Sequence[int],
    h: int,
    d0: int,
    dL: int,
    exponent: int,
) -> int:
    value = (
        int(base_seed)
        + 99_991 * int(h)
        + 101 * int(d0)
        + 103 * int(dL)
        + 107 * int(exponent)
    )
    for index, width in enumerate(hidden):
        value += (index + 1) * 1_000_003 * int(width)
    return value % (2**31 - 1)


def valid_dimension_row(row) -> bool:
    try:
        parse_architecture(row["architecture"])
        dimension = row.get("dimension_computed")
        ambient = row.get("ambient_dimension")
        if pd.isna(dimension) or pd.isna(ambient):
            return False
        int(dimension)
        int(ambient)
        return True
    except Exception:
        return False


def architecture_exponent_key(
    architecture: Sequence[int] | str,
    exponent: int,
) -> tuple[str, int]:
    if isinstance(architecture, str):
        architecture_key = architecture_string(parse_architecture(architecture))
    else:
        architecture_key = architecture_string(architecture)
    return architecture_key, int(exponent)


def existing_rows_by_key(df: pd.DataFrame) -> dict[tuple[str, int], int]:
    index_by_key: dict[tuple[str, int], int] = {}
    for index, row in df.iterrows():
        try:
            exponent_value = row.get("exponent")
            exponent = DEFAULT_EXPONENT if pd.isna(exponent_value) else int(exponent_value)
            key = architecture_exponent_key(
                parse_architecture(row["architecture"]),
                exponent,
            )
            index_by_key[key] = index
        except Exception:
            continue
    return index_by_key



def save_csv(df: pd.DataFrame, path: Path) -> Path:
    """Save atomically when possible and survive Windows destination locks.

    Returns the path that actually received the complete CSV. Normally this is
    ``path``. If Windows keeps the destination locked, it is the stable
    ``*.locked_checkpoint.csv`` fallback instead.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    checkpoint = locked_checkpoint_path(path)
    temporary = path.with_name(
        f".{path.name}.{os.getpid()}.{uuid.uuid4().hex}.tmp"
    )

    try:
        # Write a complete independent file before touching the existing CSV.
        df.to_csv(temporary, index=False)

        last_permission_error = None
        retries = max(1, int(SAVE_REPLACE_RETRIES))
        for attempt in range(1, retries + 1):
            try:
                os.replace(temporary, path)

                # A successful primary save supersedes any stale fallback.
                if checkpoint.exists():
                    try:
                        checkpoint.unlink()
                    except OSError:
                        pass
                return path

            except PermissionError as exc:
                last_permission_error = exc
                if attempt < retries:
                    print(
                        f"CSV is locked: {path}. Retrying save "
                        f"({attempt}/{retries}) ...",
                        flush=True,
                    )
                    time.sleep(max(0.0, float(SAVE_RETRY_DELAY_SECONDS)))

        if not CONTINUE_WITH_LOCKED_CHECKPOINT:
            raise last_permission_error

        # Keep one predictable latest checkpoint. If that checkpoint is itself
        # open, use a unique recovery name rather than losing the in-memory rows.
        try:
            os.replace(temporary, checkpoint)
            recovery_path = checkpoint
        except PermissionError:
            timestamp = time.strftime("%Y%m%d_%H%M%S")
            recovery_path = path.with_name(
                f"{path.stem}.locked_checkpoint_{timestamp}_{uuid.uuid4().hex[:8]}"
                f"{path.suffix}"
            )
            os.replace(temporary, recovery_path)

        print(
            "WARNING: Windows would not allow replacement of the primary CSV. "
            f"The complete current data was saved to:\n  {recovery_path}\n"
            "Close the primary CSV in Excel or any other program. A later "
            "checkpoint will automatically restore normal saving when the lock "
            "is released.",
            flush=True,
        )
        return recovery_path

    finally:
        # Remove only a leftover temporary file; never remove a recovery file.
        if temporary.exists():
            try:
                temporary.unlink()
            except OSError:
                pass

## Read the recorded MFAs and build the candidate list

Only rows already marked `is_minimal=True` define the search. The notebook does not discover or update the MFA list while it runs.

In [256]:
def selected(value: int, allowed: Sequence[int] | None) -> bool:
    return allowed is None or int(value) in {int(x) for x in allowed}


def recorded_mfa_groups(
    df: pd.DataFrame,
    d0: int,
    dL: int,
) -> dict[tuple[int, int], list[tuple[int, ...]]]:
    """Return {(h, exponent): [hidden MFA tuples]} from is_minimal=True rows."""
    groups: dict[tuple[int, int], list[tuple[int, ...]]] = defaultdict(list)

    for index, row in df.iterrows():
        if not truthy(row.get("is_minimal")):
            continue

        architecture = parse_architecture(row["architecture"])
        if architecture[0] != d0 or architecture[-1] != dL:
            raise ValueError(
                f"Row {index} is marked minimal but has endpoints {architecture[0], architecture[-1]}, "
                f"whereas {d0, dL} were inferred from the filename."
            )

        h = len(architecture) - 1
        if not pd.isna(row.get("h")) and int(row["h"]) != h:
            raise ValueError(
                f"Row {index} has h={row['h']} but architecture {architecture} has h={h}."
            )

        exponent_value = row.get("exponent")
        exponent = DEFAULT_EXPONENT if pd.isna(exponent_value) else int(exponent_value)
        if not selected(h, H_VALUES) or not selected(exponent, EXPONENTS):
            continue

        if not truthy(row.get("is_full_dimension")):
            print(
                f"Warning: row {index} is marked is_minimal=True but is_full_dimension is not true. "
                "It will still be used because is_minimal is the requested source of truth."
            )

        groups[(h, exponent)].append(tuple(architecture[1:-1]))

    cleaned: dict[tuple[int, int], list[tuple[int, ...]]] = {}
    for key, hidden_values in groups.items():
        unique = sorted(set(hidden_values))

        # Recorded MFAs should form an antichain. Equality was removed above.
        for i, left in enumerate(unique):
            for j, right in enumerate(unique):
                if i != j and hidden_leq(left, right):
                    raise ValueError(
                        f"The is_minimal rows for group {key} are not an antichain: "
                        f"{left} <= {right}. Fix the CSV flags before running."
                    )
        cleaned[key] = unique

    return dict(sorted(cleaned.items()))


def coordinatewise_mfa_maxima(mfas: Sequence[Sequence[int]]) -> tuple[int, ...]:
    if not mfas:
        raise ValueError("at least one MFA is required")
    hidden_length = len(mfas[0])
    if any(len(mfa) != hidden_length for mfa in mfas):
        raise ValueError("all MFAs in a group must have the same number of hidden layers")
    return tuple(max(int(mfa[i]) for mfa in mfas) for i in range(hidden_length))


def is_strict_predecessor_of_some_mfa(
    hidden: Sequence[int],
    mfas: Sequence[Sequence[int]],
) -> bool:
    hidden_tuple = tuple(int(width) for width in hidden)
    return any(
        hidden_tuple != tuple(int(width) for width in mfa)
        and hidden_leq(hidden_tuple, mfa)
        for mfa in mfas
    )


def covering_mfas(
    hidden: Sequence[int],
    mfas: Sequence[Sequence[int]],
) -> list[tuple[int, ...]]:
    hidden_tuple = tuple(int(width) for width in hidden)
    return [
        tuple(int(width) for width in mfa)
        for mfa in mfas
        if hidden_tuple != tuple(int(width) for width in mfa)
        and hidden_leq(hidden_tuple, mfa)
    ]


def candidate_priority(hidden: tuple[int, ...], d0: int, dL: int) -> tuple:
    architecture = full_architecture(d0, hidden, dL)
    return (parameter_count(architecture), sum(hidden), max(hidden), hidden)


def enumerate_search_box(
    mfas: Sequence[Sequence[int]],
    d0: int,
    dL: int,
) -> tuple[list[tuple[int, ...]], tuple[int, ...]]:
    """Materialize and sort the MFA-determined rectangular search box."""
    maxima = coordinatewise_mfa_maxima(mfas)
    if any(maximum < MIN_HIDDEN_WIDTH for maximum in maxima):
        raise ValueError(f"MFA maxima {maxima} lie below MIN_HIDDEN_WIDTH={MIN_HIDDEN_WIDTH}")

    box_size = math.prod(maximum - MIN_HIDDEN_WIDTH + 1 for maximum in maxima)
    if MAX_SEARCH_BOX_SIZE is not None and box_size > int(MAX_SEARCH_BOX_SIZE):
        raise RuntimeError(
            f"The MFA-determined search box contains {box_size:,} candidates, exceeding "
            f"MAX_SEARCH_BOX_SIZE={int(MAX_SEARCH_BOX_SIZE):,}."
        )

    ranges = [range(MIN_HIDDEN_WIDTH, maximum + 1) for maximum in maxima]
    candidates = [tuple(values) for values in itertools.product(*ranges)]
    candidates.sort(key=lambda hidden: candidate_priority(hidden, d0, dL))
    return candidates, maxima

## GPU evaluation and CSV updates

In [257]:
def record_for_architecture(
    architecture: Sequence[int],
    exponent: int,
    seed: int,
    covering: Sequence[Sequence[int]],
) -> dict:
    start = time.perf_counter()
    result = compute_dimension(
        architecture,
        exponent,
        primes=PRIMES,
        seed=seed,
        rank_workspace_bytes=RANK_WORKSPACE_BYTES,
        verbose=DIMENSION_VERBOSE,
    )
    elapsed = time.perf_counter() - start

    sizes, returned_exponent, ambient, expected, dimension, expected_defect = result
    if tuple(int(width) for width in sizes) != tuple(int(width) for width in architecture):
        raise RuntimeError(f"Dimension module returned unexpected architecture {sizes}")
    if int(returned_exponent) != int(exponent):
        raise RuntimeError(f"Dimension module returned unexpected exponent {returned_exponent}")

    is_full = int(dimension) == int(ambient)
    return {
        "h": len(architecture) - 1,
        "exponent": int(exponent),
        "architecture": architecture_string(architecture),
        "num_parameters": parameter_count(architecture),
        "dimension_computed": int(dimension),
        "ambient_dimension": int(ambient),
        "is_full_dimension": bool(is_full),
        # The notebook never promotes new rows into the recorded MFA list.
        "is_minimal": False,
        "expected_dimension": int(expected),
        "defect_expected": int(expected_defect),
        "defect_ambient": int(ambient) - int(dimension),
        "backend": "dim_backprop_gpu_only/CuPy-CUDA",
        "primes": str(tuple(int(prime) for prime in PRIMES)),
        "elapsed_seconds": elapsed,
        "status": "filling_below_recorded_mfa" if is_full else "nonfilling",
        "covered_by_mfa": str([list(map(int, mfa)) for mfa in covering]),
    }


def append_or_update_row(
    df: pd.DataFrame,
    record: dict,
    index_by_key: dict[tuple[str, int], int],
) -> tuple[pd.DataFrame, dict[tuple[str, int], int]]:
    row_key = architecture_exponent_key(record["architecture"], record["exponent"])

    for column in record:
        if column not in df.columns:
            df[column] = pd.Series(dtype="object")

    if row_key in index_by_key:
        index = index_by_key[row_key]
        for column, value in record.items():
            df.at[index, column] = value
    else:
        index = len(df)
        df.loc[index, list(record.keys())] = list(record.values())
        index_by_key[row_key] = index

    return df, index_by_key


def fill_one_csv_file(
    path: Path,
    *,
    max_new_evaluations: int | None = None, reverse = False
) -> dict:
    print("=" * 100)
    print(f"Processing {path}")
    print("=" * 100)

    df = read_architecture_csv(path)
    d0, dL = infer_d0_dL_from_filename(path)
    groups = recorded_mfa_groups(df, d0, dL)
    index_by_key = existing_rows_by_key(df)

    if not groups:
        print("No selected is_minimal=True rows were found. Nothing to evaluate.")
        return {
            "path": str(path),
            "new_evaluations": 0,
            "existing_rows": 0,
            "skipped_not_below_mfa": 0,
            "groups": [],
        }

    total_new = 0
    total_existing = 0
    total_skipped_not_below = 0
    total_marked_mfas = 0
    group_summaries = []
    unsaved_new = 0

    for (h, exponent), mfas in groups.items():
        candidates, maxima = enumerate_search_box(mfas, d0, dL)
        print(f"\nGroup h={h}, exponent={exponent}")
        print("Recorded MFA hidden tuples:", mfas)
        print("Coordinatewise search-box maximum:", maxima)
        print(f"Enumerated candidates: {len(candidates):,}")

        group_new = 0
        group_existing = 0
        group_skipped = 0
        group_marked_mfas = 0
        group_eligible = 0
        group_start = time.perf_counter()
        mfa_set = set(mfas)

        if reverse == True:
            candidates = list(reversed(candidates))
            
        for position, hidden in enumerate(candidates, start=1):
            if max_new_evaluations is not None and total_new >= int(max_new_evaluations):
                print(
                    f"Stopping {path.name} after "
                    f"max_new_evaluations={int(max_new_evaluations)}."
                )
                break

            architecture = full_architecture(d0, hidden, dL)
            row_key = architecture_exponent_key(architecture, exponent)

            # The recorded MFA rows themselves are boundary data, not targets.
            if hidden in mfa_set:
                group_marked_mfas += 1
                total_marked_mfas += 1
                continue

            # Requested fast gate: evaluate only when the candidate is below an MFA.
            covering = covering_mfas(hidden, mfas)
            if not covering:
                group_skipped += 1
                total_skipped_not_below += 1
                continue

            group_eligible += 1

            if row_key in index_by_key:
                row = df.loc[index_by_key[row_key]]
                if valid_dimension_row(row):
                    group_existing += 1
                    total_existing += 1
                    continue

            seed = stable_seed(SEED, hidden, h, d0, dL, exponent)
            print(
                f"[{position:,}/{len(candidates):,}] Evaluating {architecture} "
                f"below {len(covering)} MFA(s) ...",
                flush=True,
            )
            record = record_for_architecture(architecture, exponent, seed, covering)
            print(
                f"  {record['status'].upper()} | "
                f"dim={record['dimension_computed']}/{record['ambient_dimension']} | "
                f"params={record['num_parameters']} | "
                f"elapsed={record['elapsed_seconds']:.2f}s"
            )

            df, index_by_key = append_or_update_row(
                df,
                record,
                index_by_key,
            )
            group_new += 1
            total_new += 1
            unsaved_new += 1

            should_checkpoint = (
                SAVE_EVERY_N_NEW_ROWS is not None
                and int(SAVE_EVERY_N_NEW_ROWS) > 0
                and unsaved_new >= int(SAVE_EVERY_N_NEW_ROWS)
            )
            if should_checkpoint:
                save_csv(df, path)
                unsaved_new = 0

            if record["is_full_dimension"]:
                # Save before stopping: the contradiction is useful diagnostic data.
                save_csv(df, path)
                unsaved_new = 0
                message = (
                    f"Architecture {architecture} is a strict predecessor of recorded MFA(s) "
                    f"{covering}, but the GPU computation found full ambient dimension. "
                    "The CSV's is_minimal flags are inconsistent with this result."
                )
                if STOP_ON_MFA_CONTRADICTION:
                    raise RuntimeError(message)
                print("WARNING:", message)

            if PROGRESS_EVERY and group_new % int(PROGRESS_EVERY) == 0:
                elapsed = time.perf_counter() - group_start
                print(
                    f"Progress h={h}, exponent={exponent}: new={group_new}, "
                    f"existing={group_existing}, skipped={group_skipped}, "
                    f"elapsed={elapsed:.1f}s"
                )

        if unsaved_new:
            save_csv(df, path)
            unsaved_new = 0

        elapsed = time.perf_counter() - group_start
        summary = {
            "h": h,
            "exponent": exponent,
            "mfas": list(mfas),
            "search_box_maxima": maxima,
            "enumerated": len(candidates),
            "eligible_below_mfa": group_eligible,
            "new_evaluations": group_new,
            "existing_rows": group_existing,
            "marked_mfas_skipped": group_marked_mfas,
            "not_below_any_mfa_skipped": group_skipped,
            "elapsed_seconds": elapsed,
        }
        group_summaries.append(summary)
        print(
            f"Finished h={h}, exponent={exponent}: eligible={group_eligible}, "
            f"new={group_new}, existing={group_existing}, "
            f"MFA rows={group_marked_mfas}, not-below skips={group_skipped}, "
            f"elapsed={elapsed:.1f}s"
        )

        if max_new_evaluations is not None and total_new >= int(max_new_evaluations):
            break

    save_csv(df, path)
    return {
        "path": str(path),
        "d0": d0,
        "dL": dL,
        "new_evaluations": total_new,
        "existing_rows": total_existing,
        "marked_mfas_skipped": total_marked_mfas,
        "skipped_not_below_mfa": total_skipped_not_below,
        "groups": group_summaries,
    }

## Inspect the planned files and MFA-derived search sizes

In [258]:
data_dir = choose_data_dir()
csv_paths = find_csv_files(data_dir)

print("Data directory:", data_dir.resolve())
print("CSV files:")
for path in csv_paths:
    print(" -", path)

if not csv_paths:
    raise FileNotFoundError(
        f"No *_architectures.csv files found in {data_dir!s}. "
        "Set DATA_DIR or CSV_FILES in the configuration cell."
    )

plan_rows = []
for path in csv_paths:
    df = read_architecture_csv(path)
    d0, dL = infer_d0_dL_from_filename(path)
    groups = recorded_mfa_groups(df, d0, dL)
    for (h, exponent), mfas in groups.items():
        maxima = coordinatewise_mfa_maxima(mfas)
        box_size = math.prod(maximum - MIN_HIDDEN_WIDTH + 1 for maximum in maxima)
        plan_rows.append({
            "file": str(path),
            "h": h,
            "exponent": exponent,
            "number_of_mfas": len(mfas),
            "mfas": mfas,
            "box_maxima": maxima,
            "box_size": box_size,
        })

plan_df = pd.DataFrame(plan_rows)
display(plan_df)

DATA_DIR=Data was not found. Using ..\data\raw.
Data directory: C:\Users\daoke\Documents\GitHub\MFA_PNNs\data\raw
CSV files:
 - ..\data\raw\1_1_r1_architectures.csv
 - ..\data\raw\1_1_r2_architectures.csv
 - ..\data\raw\1_1_r3_architectures.csv
 - ..\data\raw\1_1_r4_architectures.csv
 - ..\data\raw\1_1_r5_architectures.csv
 - ..\data\raw\1_1_r6_architectures.csv
 - ..\data\raw\1_1_r7_architectures.csv
 - ..\data\raw\1_1_r8_architectures.csv
 - ..\data\raw\1_1_r9_architectures.csv
 - ..\data\raw\1_2_r1_architectures.csv
 - ..\data\raw\1_2_r2_architectures.csv
 - ..\data\raw\1_2_r3_architectures.csv
 - ..\data\raw\1_2_r4_architectures.csv
 - ..\data\raw\1_2_r5_architectures.csv
 - ..\data\raw\1_2_r6_architectures.csv
 - ..\data\raw\1_2_r7_architectures.csv
 - ..\data\raw\1_2_r8_architectures.csv
 - ..\data\raw\1_2_r9_architectures.csv
 - ..\data\raw\1_3_r1_architectures.csv
 - ..\data\raw\1_3_r2_architectures.csv
 - ..\data\raw\1_3_r3_architectures.csv
 - ..\data\raw\1_3_r4_architectures.csv
 - ..\data\raw\1_3_r5_architectures.csv
 - ..\data\raw\1_3_r6_architectures.csv
 - ..\data\raw\1_3_r7_architectures.csv
 - ..\data\raw\1_3_r8_architectures.csv
 - ..\data\raw\1_3_r9_architectures.csv
 - ..\data\raw\1_4_r1_architectures.csv
 - ..\data\raw\1_4_r2_architectures.csv
 - ..\data\raw\1_4_r3_architectures.csv
 - ..\data\raw\1_4_r4_architectures.csv
 - ..\data\raw\1_4_r5_architectures.csv
 - ..\data\raw\1_4_r6_architectures.csv
 - ..\data\raw\1_4_r7_architectures.csv
 - ..\data\raw\1_4_r8_architectures.csv
 - ..\data\raw\1_4_r9_architectures.csv
 - ..\data\raw\1_5_r1_architectures.csv
 - ..\data\raw\1_5_r2_architectures.csv
 - ..\data\raw\1_5_r3_architectures.csv
 - ..\data\raw\1_5_r4_architectures.csv
 - ..\data\raw\1_5_r5_architectures.csv
 - ..\data\raw\1_5_r6_architectures.csv
 - ..\data\raw\1_5_r7_architectures.csv
 - ..\data\raw\1_5_r8_architectures.csv
 - ..\data\raw\1_5_r9_architectures.csv
 - ..\data\raw\1_6_r1_architectures.csv
 - ..\data\raw\1_6_r2_architectures.csv
 - ..\data\raw\1_6_r3_architectures.csv
 - ..\data\raw\1_6_r4_architectures.csv
 - ..\data\raw\1_6_r5_architectures.csv
 - ..\data\raw\1_6_r6_architectures.csv
 - ..\data\raw\1_6_r7_architectures.csv
 - ..\data\raw\1_6_r8_architectures.csv
 - ..\data\raw\1_6_r9_architectures.csv
 - ..\data\raw\1_7_r1_architectures.csv
 - ..\data\raw\1_7_r2_architectures.csv
 - ..\data\raw\1_7_r3_architectures.csv
 - ..\data\raw\1_7_r4_architectures.csv
 - ..\data\raw\1_7_r5_architectures.csv
 - ..\data\raw\1_7_r6_architectures.csv
 - ..\data\raw\1_7_r7_architectures.csv
 - ..\data\raw\1_7_r8_architectures.csv
 - ..\data\raw\1_7_r9_architectures.csv
 - ..\data\raw\1_8_r1_architectures.csv
 - ..\data\raw\1_8_r2_architectures.csv
 - ..\data\raw\1_8_r3_architectures.csv
 - ..\data\raw\1_8_r4_architectures.csv
 - ..\data\raw\1_8_r5_architectures.csv
 - ..\data\raw\1_8_r6_architectures.csv
 - ..\data\raw\1_8_r7_architectures.csv
 - ..\data\raw\1_8_r8_architectures.csv
 - ..\data\raw\1_8_r9_architectures.csv
 - ..\data\raw\1_9_r1_architectures.csv
 - ..\data\raw\1_9_r2_architectures.csv
 - ..\data\raw\1_9_r3_architectures.csv
 - ..\data\raw\1_9_r4_architectures.csv
 - ..\data\raw\1_9_r5_architectures.csv
 - ..\data\raw\1_9_r6_architectures.csv
 - ..\data\raw\1_9_r7_architectures.csv
 - ..\data\raw\1_9_r8_architectures.csv
 - ..\data\raw\1_9_r9_architectures.csv
 - ..\data\raw\2_1_r12_architectures.csv
 - ..\data\raw\2_1_r1_architectures.csv
 - ..\data\raw\2_1_r2_architectures.csv
 - ..\data\raw\2_1_r3_architectures.csv
 - ..\data\raw\2_1_r4_architectures.csv
 - ..\data\raw\2_1_r5_architectures.csv
 - ..\data\raw\2_1_r6_architectures.csv
 - ..\data\raw\2_1_r7_architectures.csv
 - ..\data\raw\2_1_r8_architectures.csv
 - ..\data\raw\2_1_r9_architectures.csv
 - ..\data\raw\2_2_r1_architectures.csv
 - ..\data\raw\2_2_r2_architectures.csv
 - ..\data\raw\2_2_r3_architectures.csv
 - ..\data\raw\2_2_r4_architectures.csv
 - ..\data\raw\2_2_r5_architectures.csv
 - ..\data\raw\2_2_r6_architectures.csv
 - ..\data\raw\2_2_r7_architectures.csv
 - ..\data\raw\2_2_r8_architectures.csv
 - ..\data\raw\2_2_r9_architectures.csv
 - ..\data\raw\2_3_r1_architectures.csv
 - ..\data\raw\2_3_r2_architectures.csv
 - ..\data\raw\2_3_r3_architectures.csv
 - ..\data\raw\2_3_r4_architectures.csv
 - ..\data\raw\2_3_r5_architectures.csv
 - ..\data\raw\2_3_r6_architectures.csv
 - ..\data\raw\2_3_r7_architectures.csv
 - ..\data\raw\2_3_r8_architectures.csv
 - ..\data\raw\2_3_r9_architectures.csv
 - ..\data\raw\2_4_r1_architectures.csv
 - ..\data\raw\2_4_r2_architectures.csv
 - ..\data\raw\2_4_r3_architectures.csv
 - ..\data\raw\2_4_r4_architectures.csv
 - ..\data\raw\2_4_r5_architectures.csv
 - ..\data\raw\2_4_r6_architectures.csv
 - ..\data\raw\2_4_r7_architectures.csv
 - ..\data\raw\2_4_r8_architectures.csv
 - ..\data\raw\2_4_r9_architectures.csv
 - ..\data\raw\2_5_r1_architectures.csv
 - ..\data\raw\2_5_r2_architectures.csv
 - ..\data\raw\2_5_r3_architectures.csv
 - ..\data\raw\2_5_r4_architectures.csv
 - ..\data\raw\2_5_r5_architectures.csv
 - ..\data\raw\2_5_r6_architectures.csv
 - ..\data\raw\2_5_r7_architectures.csv
 - ..\data\raw\2_5_r8_architectures.csv
 - ..\data\raw\2_5_r9_architectures.csv
 - ..\data\raw\2_6_r1_architectures.csv
 - ..\data\raw\2_6_r2_architectures.csv
 - ..\data\raw\2_6_r3_architectures.csv
 - ..\data\raw\2_6_r4_architectures.csv
 - ..\data\raw\2_6_r5_architectures.csv
 - ..\data\raw\2_6_r6_architectures.csv
 - ..\data\raw\2_6_r7_architectures.csv
 - ..\data\raw\2_6_r8_architectures.csv
 - ..\data\raw\2_6_r9_architectures.csv
 - ..\data\raw\2_7_r1_architectures.csv
 - ..\data\raw\2_7_r2_architectures.csv
 - ..\data\raw\2_7_r3_architectures.csv
 - ..\data\raw\2_7_r4_architectures.csv
 - ..\data\raw\2_7_r5_architectures.csv
 - ..\data\raw\2_7_r6_architectures.csv
 - ..\data\raw\2_7_r7_architectures.csv
 - ..\data\raw\2_7_r8_architectures.csv
 - ..\data\raw\2_7_r9_architectures.csv
 - ..\data\raw\2_8_r1_architectures.csv
 - ..\data\raw\2_8_r2_architectures.csv
 - ..\data\raw\2_8_r3_architectures.csv
 - ..\data\raw\2_8_r4_architectures.csv
 - ..\data\raw\2_8_r5_architectures.csv
 - ..\data\raw\2_8_r6_architectures.csv
 - ..\data\raw\2_8_r7_architectures.csv
 - ..\data\raw\2_8_r8_architectures.csv
 - ..\data\raw\2_8_r9_architectures.csv
 - ..\data\raw\2_9_r1_architectures.csv
 - ..\data\raw\2_9_r2_architectures.csv
 - ..\data\raw\2_9_r3_architectures.csv
 - ..\data\raw\2_9_r4_architectures.csv
 - ..\data\raw\2_9_r5_architectures.csv
 - ..\data\raw\2_9_r6_architectures.csv
 - ..\data\raw\2_9_r7_architectures.csv
 - ..\data\raw\2_9_r8_architectures.csv
 - ..\data\raw\2_9_r9_architectures.csv
 - ..\data\raw\3_1_r1_architectures.csv
 - ..\data\raw\3_1_r2_architectures.csv
 - ..\data\raw\3_1_r3_architectures.csv
 - ..\data\raw\3_1_r4_architectures.csv
 - ..\data\raw\3_1_r5_architectures.csv
 - ..\data\raw\3_1_r6_architectures.csv
 - ..\data\raw\3_1_r7_architectures.csv
 - ..\data\raw\3_1_r8_architectures.csv
 - ..\data\raw\3_1_r9_architectures.csv
 - ..\data\raw\3_2_r1_architectures.csv
 - ..\data\raw\3_2_r2_architectures.csv
 - ..\data\raw\3_2_r3_architectures.csv
 - ..\data\raw\3_2_r4_architectures.csv
 - ..\data\raw\3_2_r5_architectures.csv
 - ..\data\raw\3_2_r6_architectures.csv
 - ..\data\raw\3_2_r7_architectures.csv
 - ..\data\raw\3_2_r8_architectures.csv
 - ..\data\raw\3_2_r9_architectures.csv
 - ..\data\raw\3_3_r1_architectures.csv
 - ..\data\raw\3_3_r2_architectures.csv
 - ..\data\raw\3_3_r3_architectures.csv
 - ..\data\raw\3_3_r4_architectures.csv
 - ..\data\raw\3_3_r5_architectures.csv
 - ..\data\raw\3_3_r6_architectures.csv
 - ..\data\raw\3_3_r7_architectures.csv
 - ..\data\raw\3_3_r8_architectures.csv
 - ..\data\raw\3_3_r9_architectures.csv
 - ..\data\raw\3_4_r1_architectures.csv
 - ..\data\raw\3_4_r2_architectures.csv
 - ..\data\raw\3_4_r3_architectures.csv
 - ..\data\raw\3_4_r4_architectures.csv
 - ..\data\raw\3_4_r5_architectures.csv
 - ..\data\raw\3_4_r6_architectures.csv
 - ..\data\raw\3_4_r7_architectures.csv
 - ..\data\raw\3_4_r8_architectures.csv
 - ..\data\raw\3_4_r9_architectures.csv
 - ..\data\raw\3_5_r1_architectures.csv
 - ..\data\raw\3_5_r2_architectures.csv
 - ..\data\raw\3_5_r3_architectures.csv
 - ..\data\raw\3_5_r4_architectures.csv
 - ..\data\raw\3_5_r5_architectures.csv
 - ..\data\raw\3_5_r6_architectures.csv
 - ..\data\raw\3_5_r7_architectures.csv
 - ..\data\raw\3_5_r8_architectures.csv
 - ..\data\raw\3_5_r9_architectures.csv
 - ..\data\raw\3_6_r1_architectures.csv
 - ..\data\raw\3_6_r2_architectures.csv
 - ..\data\raw\3_6_r3_architectures.csv
 - ..\data\raw\3_6_r4_architectures.csv
 - ..\data\raw\3_6_r5_architectures.csv
 - ..\data\raw\3_6_r6_architectures.csv
 - ..\data\raw\3_6_r7_architectures.csv
 - ..\data\raw\3_6_r8_architectures.csv
 - ..\data\raw\3_6_r9_architectures.csv
 - ..\data\raw\3_7_r1_architectures.csv
 - ..\data\raw\3_7_r2_architectures.csv
 - ..\data\raw\3_7_r3_architectures.csv
 - ..\data\raw\3_7_r4_architectures.csv
 - ..\data\raw\3_7_r5_architectures.csv
 - ..\data\raw\3_7_r6_architectures.csv
 - ..\data\raw\3_7_r7_architectures.csv
 - ..\data\raw\3_7_r8_architectures.csv
 - ..\data\raw\3_7_r9_architectures.csv
 - ..\data\raw\3_8_r1_architectures.csv
 - ..\data\raw\3_8_r2_architectures.csv
 - ..\data\raw\3_8_r3_architectures.csv
 - ..\data\raw\3_8_r4_architectures.csv
 - ..\data\raw\3_8_r5_architectures.csv
 - ..\data\raw\3_8_r6_architectures.csv
 - ..\data\raw\3_8_r7_architectures.csv
 - ..\data\raw\3_8_r8_architectures.csv
 - ..\data\raw\3_8_r9_architectures.csv
 - ..\data\raw\3_9_r1_architectures.csv
 - ..\data\raw\3_9_r2_architectures.csv
 - ..\data\raw\3_9_r3_architectures.csv
 - ..\data\raw\3_9_r4_architectures.csv
 - ..\data\raw\3_9_r5_architectures.csv
 - ..\data\raw\3_9_r6_architectures.csv
 - ..\data\raw\3_9_r7_architectures.csv
 - ..\data\raw\3_9_r8_architectures.csv
 - ..\data\raw\3_9_r9_architectures.csv
 - ..\data\raw\4_1_r1_architectures.csv
 - ..\data\raw\4_1_r2_architectures.csv
 - ..\data\raw\4_1_r3_architectures.csv
 - ..\data\raw\4_1_r4_architectures.csv
 - ..\data\raw\4_1_r5_architectures.csv
 - ..\data\raw\4_1_r6_architectures.csv
 - ..\data\raw\4_1_r7_architectures.csv
 - ..\data\raw\4_1_r8_architectures.csv
 - ..\data\raw\4_1_r9_architectures.csv
 - ..\data\raw\4_2_r1_architectures.csv
 - ..\data\raw\4_2_r2_architectures.csv
 - ..\data\raw\4_2_r3_architectures.csv
 - ..\data\raw\4_2_r4_architectures.csv
 - ..\data\raw\4_2_r5_architectures.csv
 - ..\data\raw\4_2_r6_architectures.csv
 - ..\data\raw\4_2_r7_architectures.csv
 - ..\data\raw\4_2_r8_architectures.csv
 - ..\data\raw\4_2_r9_architectures.csv
 - ..\data\raw\4_3_r1_architectures.csv
 - ..\data\raw\4_3_r2_architectures.csv
 - ..\data\raw\4_3_r3_architectures.csv
 - ..\data\raw\4_3_r4_architectures.csv
 - ..\data\raw\4_3_r5_architectures.csv
 - ..\data\raw\4_3_r6_architectures.csv
 - ..\data\raw\4_3_r7_architectures.csv
 - ..\data\raw\4_3_r8_architectures.csv
 - ..\data\raw\4_3_r9_architectures.csv
 - ..\data\raw\4_4_r1_architectures.csv
 - ..\data\raw\4_4_r2_architectures.csv
 - ..\data\raw\4_4_r3_architectures.csv
 - ..\data\raw\4_4_r4_architectures.csv
 - ..\data\raw\4_4_r5_architectures.csv
 - ..\data\raw\4_4_r6_architectures.csv
 - ..\data\raw\4_4_r7_architectures.csv
 - ..\data\raw\4_4_r8_architectures.csv
 - ..\data\raw\4_4_r9_architectures.csv
 - ..\data\raw\4_5_r1_architectures.csv
 - ..\data\raw\4_5_r2_architectures.csv
 - ..\data\raw\4_5_r3_architectures.csv
 - ..\data\raw\4_5_r4_architectures.csv
 - ..\data\raw\4_5_r5_architectures.csv
 - ..\data\raw\4_5_r6_architectures.csv
 - ..\data\raw\4_5_r7_architectures.csv
 - ..\data\raw\4_5_r8_architectures.csv
 - ..\data\raw\4_5_r9_architectures.csv
 - ..\data\raw\4_6_r1_architectures.csv
 - ..\data\raw\4_6_r2_architectures.csv
 - ..\data\raw\4_6_r3_architectures.csv
 - ..\data\raw\4_6_r4_architectures.csv
 - ..\data\raw\4_6_r5_architectures.csv
 - ..\data\raw\4_6_r6_architectures.csv
 - ..\data\raw\4_6_r7_architectures.csv
 - ..\data\raw\4_6_r8_architectures.csv
 - ..\data\raw\4_6_r9_architectures.csv
 - ..\data\raw\4_7_r1_architectures.csv
 - ..\data\raw\4_7_r2_architectures.csv
 - ..\data\raw\4_7_r3_architectures.csv
 - ..\data\raw\4_7_r4_architectures.csv
 - ..\data\raw\4_7_r5_architectures.csv
 - ..\data\raw\4_7_r6_architectures.csv
 - ..\data\raw\4_7_r7_architectures.csv
 - ..\data\raw\4_7_r8_architectures.csv
 - ..\data\raw\4_7_r9_architectures.csv
 - ..\data\raw\4_8_r1_architectures.csv
 - ..\data\raw\4_8_r2_architectures.csv
 - ..\data\raw\4_8_r3_architectures.csv
 - ..\data\raw\4_8_r4_architectures.csv
 - ..\data\raw\4_8_r5_architectures.csv
 - ..\data\raw\4_8_r6_architectures.csv
 - ..\data\raw\4_8_r7_architectures.csv
 - ..\data\raw\4_8_r8_architectures.csv
 - ..\data\raw\4_8_r9_architectures.csv
 - ..\data\raw\4_9_r1_architectures.csv
 - ..\data\raw\4_9_r2_architectures.csv
 - ..\data\raw\4_9_r3_architectures.csv
 - ..\data\raw\4_9_r4_architectures.csv
 - ..\data\raw\4_9_r5_architectures.csv
 - ..\data\raw\4_9_r6_architectures.csv
 - ..\data\raw\4_9_r7_architectures.csv
 - ..\data\raw\4_9_r8_architectures.csv
 - ..\data\raw\4_9_r9_architectures.csv
 - ..\data\raw\5_1_r1_architectures.csv
 - ..\data\raw\5_1_r2_architectures.csv
 - ..\data\raw\5_1_r3_architectures.csv
 - ..\data\raw\5_1_r4_architectures.csv
 - ..\data\raw\5_1_r5_architectures.csv
 - ..\data\raw\5_1_r6_architectures.csv
 - ..\data\raw\5_1_r7_architectures.csv
 - ..\data\raw\5_1_r8_architectures.csv
 - ..\data\raw\5_1_r9_architectures.csv
 - ..\data\raw\5_2_r1_architectures.csv
 - ..\data\raw\5_2_r2_architectures.csv
 - ..\data\raw\5_2_r3_architectures.csv
 - ..\data\raw\5_2_r4_architectures.csv
 - ..\data\raw\5_2_r5_architectures.csv
 - ..\data\raw\5_2_r6_architectures.csv
 - ..\data\raw\5_2_r7_architectures.csv
 - ..\data\raw\5_2_r8_architectures.csv
 - ..\data\raw\5_2_r9_architectures.csv
 - ..\data\raw\5_3_r1_architectures.csv
 - ..\data\raw\5_3_r2_architectures.csv
 - ..\data\raw\5_3_r3_architectures.csv
 - ..\data\raw\5_3_r4_architectures.csv
 - ..\data\raw\5_3_r5_architectures.csv
 - ..\data\raw\5_3_r6_architectures.csv
 - ..\data\raw\5_3_r7_architectures.csv
 - ..\data\raw\5_3_r8_architectures.csv
 - ..\data\raw\5_3_r9_architectures.csv
 - ..\data\raw\5_4_r1_architectures.csv
 - ..\data\raw\5_4_r2_architectures.csv
 - ..\data\raw\5_4_r3_architectures.csv
 - ..\data\raw\5_4_r4_architectures.csv
 - ..\data\raw\5_4_r5_architectures.csv
 - ..\data\raw\5_4_r6_architectures.csv
 - ..\data\raw\5_4_r7_architectures.csv
 - ..\data\raw\5_4_r8_architectures.csv
 - ..\data\raw\5_4_r9_architectures.csv
 - ..\data\raw\5_5_r1_architectures.csv
 - ..\data\raw\5_5_r2_architectures.csv
 - ..\data\raw\5_5_r3_architectures.csv
 - ..\data\raw\5_5_r4_architectures.csv
 - ..\data\raw\5_5_r5_architectures.csv
 - ..\data\raw\5_5_r6_architectures.csv
 - ..\data\raw\5_5_r7_architectures.csv
 - ..\data\raw\5_5_r8_architectures.csv
 - ..\data\raw\5_5_r9_architectures.csv
 - ..\data\raw\5_6_r1_architectures.csv
 - ..\data\raw\5_6_r2_architectures.csv
 - ..\data\raw\5_6_r3_architectures.csv
 - ..\data\raw\5_6_r4_architectures.csv
 - ..\data\raw\5_6_r5_architectures.csv
 - ..\data\raw\5_6_r6_architectures.csv
 - ..\data\raw\5_6_r7_architectures.csv
 - ..\data\raw\5_6_r8_architectures.csv
 - ..\data\raw\5_6_r9_architectures.csv
 - ..\data\raw\5_7_r1_architectures.csv
 - ..\data\raw\5_7_r2_architectures.csv
 - ..\data\raw\5_7_r3_architectures.csv
 - ..\data\raw\5_7_r4_architectures.csv
 - ..\data\raw\5_7_r5_architectures.csv
 - ..\data\raw\5_7_r6_architectures.csv
 - ..\data\raw\5_7_r7_architectures.csv
 - ..\data\raw\5_7_r8_architectures.csv
 - ..\data\raw\5_7_r9_architectures.csv
 - ..\data\raw\5_8_r1_architectures.csv
 - ..\data\raw\5_8_r2_architectures.csv
 - ..\data\raw\5_8_r3_architectures.csv
 - ..\data\raw\5_8_r4_architectures.csv
 - ..\data\raw\5_8_r5_architectures.csv
 - ..\data\raw\5_8_r6_architectures.csv
 - ..\data\raw\5_8_r7_architectures.csv
 - ..\data\raw\5_8_r8_architectures.csv
 - ..\data\raw\5_8_r9_architectures.csv
 - ..\data\raw\5_9_r9_architectures.csv
 - ..\data\raw\6_1_r1_architectures.csv
 - ..\data\raw\6_1_r2_architectures.csv
 - ..\data\raw\6_1_r3_architectures.csv
 - ..\data\raw\6_8_r9_architectures.csv
 - ..\data\raw\6_9_r9_architectures.csv
 - ..\data\raw\7_1_r1_architectures.csv
 - ..\data\raw\7_1_r2_architectures.csv
 - ..\data\raw\7_1_r3_architectures.csv
 - ..\data\raw\7_1_r4_architectures.csv
 - ..\data\raw\7_1_r5_architectures.csv
 - ..\data\raw\7_1_r6_architectures.csv
 - ..\data\raw\7_1_r7_architectures.csv
 - ..\data\raw\7_1_r8_architectures.csv
 - ..\data\raw\7_1_r9_architectures.csv
 - ..\data\raw\7_2_r1_architectures.csv
 - ..\data\raw\7_2_r2_architectures.csv
 - ..\data\raw\7_2_r3_architectures.csv
 - ..\data\raw\7_2_r4_architectures.csv
 - ..\data\raw\7_2_r5_architectures.csv
 - ..\data\raw\7_2_r6_architectures.csv
 - ..\data\raw\7_2_r7_architectures.csv
 - ..\data\raw\8_1_r1_architectures.csv
 - ..\data\raw\8_1_r2_architectures.csv
 - ..\data\raw\8_1_r3_architectures.csv
 - ..\data\raw\8_1_r4_architectures.csv
 - ..\data\raw\8_1_r5_architectures.csv
 - ..\data\raw\8_1_r6_architectures.csv
 - ..\data\raw\8_1_r7_architectures.csv
 - ..\data\raw\8_1_r8_architectures.csv
 - ..\data\raw\9_1_r1_architectures.csv
 - ..\data\raw\9_1_r2_architectures.csv
 - ..\data\raw\9_1_r3_architectures.csv
 - ..\data\raw\9_1_r4_architectures.csv
 - ..\data\raw\9_1_r5_architectures.csv

,file,h,exponent,number_of_mfas,mfas,box_maxima,box_size
0,..\data\raw\1_1_r1_architectures.csv,2,1,1,"[(1,)]","(1,)",1
1,..\data\raw\1_1_r1_architectures.csv,3,1,1,"[(1, 1)]","(1, 1)",1
2,..\data\raw\1_1_r1_architectures.csv,4,1,1,"[(1, 1, 1)]","(1, 1, 1)",1
3,..\data\raw\1_1_r1_architectures.csv,5,1,1,"[(1, 1, 1, 1)]","(1, 1, 1, 1)",1
4,..\data\raw\1_1_r1_architectures.csv,6,1,1,"[(1, 1, 1, 1, 1)]","(1, 1, 1, 1, 1)",1
...,...,...,...,...,...,...,...
746,..\data\raw\9_1_r2_architectures.csv,2,2,1,"[(9,)]","(9,)",9
747,..\data\raw\9_1_r2_architectures.csv,3,2,4,"[(25, 18), (26, 16), (27, 14), (28, 13)]","(28, 18)",504
748,..\data\raw\9_1_r3_architectures.csv,2,3,1,"[(19,)]","(19,)",19
749,..\data\raw\9_1_r4_architectures.csv,2,4,1,"[(55,)]","(55,)",55
750,..\data\raw\9_1_r5_architectures.csv,2,5,1,"[(143,)]","(143,)",143

## Run the sequential fill

The notebook checkpoints to the same CSV. Rerunning it skips every architecture whose row already contains a valid computed and ambient dimension.

### Select Particular CSV_Files

In [259]:
# csv_paths=csv_paths[100:]
csv_paths

[WindowsPath('../data/raw/1_1_r1_architectures.csv'),
 WindowsPath('../data/raw/1_1_r2_architectures.csv'),
 WindowsPath('../data/raw/1_1_r3_architectures.csv'),
 WindowsPath('../data/raw/1_1_r4_architectures.csv'),
 WindowsPath('../data/raw/1_1_r5_architectures.csv'),
 WindowsPath('../data/raw/1_1_r6_architectures.csv'),
 WindowsPath('../data/raw/1_1_r7_architectures.csv'),
 WindowsPath('../data/raw/1_1_r8_architectures.csv'),
 WindowsPath('../data/raw/1_1_r9_architectures.csv'),
 WindowsPath('../data/raw/1_2_r1_architectures.csv'),
 WindowsPath('../data/raw/1_2_r2_architectures.csv'),
 WindowsPath('../data/raw/1_2_r3_architectures.csv'),
 WindowsPath('../data/raw/1_2_r4_architectures.csv'),
 WindowsPath('../data/raw/1_2_r5_architectures.csv'),
 WindowsPath('../data/raw/1_2_r6_architectures.csv'),
 WindowsPath('../data/raw/1_2_r7_architectures.csv'),
 WindowsPath('../data/raw/1_2_r8_architectures.csv'),
 WindowsPath('../data/raw/1_2_r9_architectures.csv'),
 WindowsPath('../data/raw/1_3_r1_architectures.csv'),
 WindowsPath('../data/raw/1_3_r2_architectures.csv'),
 WindowsPath('../data/raw/1_3_r3_architectures.csv'),
 WindowsPath('../data/raw/1_3_r4_architectures.csv'),
 WindowsPath('../data/raw/1_3_r5_architectures.csv'),
 WindowsPath('../data/raw/1_3_r6_architectures.csv'),
 WindowsPath('../data/raw/1_3_r7_architectures.csv'),
 WindowsPath('../data/raw/1_3_r8_architectures.csv'),
 WindowsPath('../data/raw/1_3_r9_architectures.csv'),
 WindowsPath('../data/raw/1_4_r1_architectures.csv'),
 WindowsPath('../data/raw/1_4_r2_architectures.csv'),
 WindowsPath('../data/raw/1_4_r3_architectures.csv'),
 WindowsPath('../data/raw/1_4_r4_architectures.csv'),
 WindowsPath('../data/raw/1_4_r5_architectures.csv'),
 WindowsPath('../data/raw/1_4_r6_architectures.csv'),
 WindowsPath('../data/raw/1_4_r7_architectures.csv'),
 WindowsPath('../data/raw/1_4_r8_architectures.csv'),
 WindowsPath('../data/raw/1_4_r9_architectures.csv'),
 WindowsPath('../data/raw/1_5_r1_architectures.csv'),
 WindowsPath('../data/raw/1_5_r2_architectures.csv'),
 WindowsPath('../data/raw/1_5_r3_architectures.csv'),
 WindowsPath('../data/raw/1_5_r4_architectures.csv'),
 WindowsPath('../data/raw/1_5_r5_architectures.csv'),
 WindowsPath('../data/raw/1_5_r6_architectures.csv'),
 WindowsPath('../data/raw/1_5_r7_architectures.csv'),
 WindowsPath('../data/raw/1_5_r8_architectures.csv'),
 WindowsPath('../data/raw/1_5_r9_architectures.csv'),
 WindowsPath('../data/raw/1_6_r1_architectures.csv'),
 WindowsPath('../data/raw/1_6_r2_architectures.csv'),
 WindowsPath('../data/raw/1_6_r3_architectures.csv'),
 WindowsPath('../data/raw/1_6_r4_architectures.csv'),
 WindowsPath('../data/raw/1_6_r5_architectures.csv'),
 WindowsPath('../data/raw/1_6_r6_architectures.csv'),
 WindowsPath('../data/raw/1_6_r7_architectures.csv'),
 WindowsPath('../data/raw/1_6_r8_architectures.csv'),
 WindowsPath('../data/raw/1_6_r9_architectures.csv'),
 WindowsPath('../data/raw/1_7_r1_architectures.csv'),
 WindowsPath('../data/raw/1_7_r2_architectures.csv'),
 WindowsPath('../data/raw/1_7_r3_architectures.csv'),
 WindowsPath('../data/raw/1_7_r4_architectures.csv'),
 WindowsPath('../data/raw/1_7_r5_architectures.csv'),
 WindowsPath('../data/raw/1_7_r6_architectures.csv'),
 WindowsPath('../data/raw/1_7_r7_architectures.csv'),
 WindowsPath('../data/raw/1_7_r8_architectures.csv'),
 WindowsPath('../data/raw/1_7_r9_architectures.csv'),
 WindowsPath('../data/raw/1_8_r1_architectures.csv'),
 WindowsPath('../data/raw/1_8_r2_architectures.csv'),
 WindowsPath('../data/raw/1_8_r3_architectures.csv'),
 WindowsPath('../data/raw/1_8_r4_architectures.csv'),
 WindowsPath('../data/raw/1_8_r5_architectures.csv'),
 WindowsPath('../data/raw/1_8_r6_architectures.csv'),
 WindowsPath('../data/raw/1_8_r7_architectures.csv'),
 WindowsPath('../data/raw/1_8_r8_architectures.csv'),
 WindowsPath('../data/raw/1_8_r9_architectures.csv'),
 WindowsPath('../data/raw/1_9_r1_architectures.csv'),
 WindowsPath('../data/raw/1_9_r2_architectures.csv'),
 WindowsPath('../data/raw/1_9_r3_architectures.csv'),
 WindowsPath('../data/raw/1_9_r4_architectures.csv'),
 WindowsPath('../data/raw/1_9_r5_architectures.csv'),
 WindowsPath('../data/raw/1_9_r6_architectures.csv'),
 WindowsPath('../data/raw/1_9_r7_architectures.csv'),
 WindowsPath('../data/raw/1_9_r8_architectures.csv'),
 WindowsPath('../data/raw/1_9_r9_architectures.csv'),
 WindowsPath('../data/raw/2_1_r12_architectures.csv'),
 WindowsPath('../data/raw/2_1_r1_architectures.csv'),
 WindowsPath('../data/raw/2_1_r2_architectures.csv'),
 WindowsPath('../data/raw/2_1_r3_architectures.csv'),
 WindowsPath('../data/raw/2_1_r4_architectures.csv'),
 WindowsPath('../data/raw/2_1_r5_architectures.csv'),
 WindowsPath('../data/raw/2_1_r6_architectures.csv'),
 WindowsPath('../data/raw/2_1_r7_architectures.csv'),
 WindowsPath('../data/raw/2_1_r8_architectures.csv'),
 WindowsPath('../data/raw/2_1_r9_architectures.csv'),
 WindowsPath('../data/raw/2_2_r1_architectures.csv'),
 WindowsPath('../data/raw/2_2_r2_architectures.csv'),
 WindowsPath('../data/raw/2_2_r3_architectures.csv'),
 WindowsPath('../data/raw/2_2_r4_architectures.csv'),
 WindowsPath('../data/raw/2_2_r5_architectures.csv'),
 WindowsPath('../data/raw/2_2_r6_architectures.csv'),
 WindowsPath('../data/raw/2_2_r7_architectures.csv'),
 WindowsPath('../data/raw/2_2_r8_architectures.csv'),
 WindowsPath('../data/raw/2_2_r9_architectures.csv'),
 WindowsPath('../data/raw/2_3_r1_architectures.csv'),
 WindowsPath('../data/raw/2_3_r2_architectures.csv'),
 WindowsPath('../data/raw/2_3_r3_architectures.csv'),
 WindowsPath('../data/raw/2_3_r4_architectures.csv'),
 WindowsPath('../data/raw/2_3_r5_architectures.csv'),
 WindowsPath('../data/raw/2_3_r6_architectures.csv'),
 WindowsPath('../data/raw/2_3_r7_architectures.csv'),
 WindowsPath('../data/raw/2_3_r8_architectures.csv'),
 WindowsPath('../data/raw/2_3_r9_architectures.csv'),
 WindowsPath('../data/raw/2_4_r1_architectures.csv'),
 WindowsPath('../data/raw/2_4_r2_architectures.csv'),
 WindowsPath('../data/raw/2_4_r3_architectures.csv'),
 WindowsPath('../data/raw/2_4_r4_architectures.csv'),
 WindowsPath('../data/raw/2_4_r5_architectures.csv'),
 WindowsPath('../data/raw/2_4_r6_architectures.csv'),
 WindowsPath('../data/raw/2_4_r7_architectures.csv'),
 WindowsPath('../data/raw/2_4_r8_architectures.csv'),
 WindowsPath('../data/raw/2_4_r9_architectures.csv'),
 WindowsPath('../data/raw/2_5_r1_architectures.csv'),
 WindowsPath('../data/raw/2_5_r2_architectures.csv'),
 WindowsPath('../data/raw/2_5_r3_architectures.csv'),
 WindowsPath('../data/raw/2_5_r4_architectures.csv'),
 WindowsPath('../data/raw/2_5_r5_architectures.csv'),
 WindowsPath('../data/raw/2_5_r6_architectures.csv'),
 WindowsPath('../data/raw/2_5_r7_architectures.csv'),
 WindowsPath('../data/raw/2_5_r8_architectures.csv'),
 WindowsPath('../data/raw/2_5_r9_architectures.csv'),
 WindowsPath('../data/raw/2_6_r1_architectures.csv'),
 WindowsPath('../data/raw/2_6_r2_architectures.csv'),
 WindowsPath('../data/raw/2_6_r3_architectures.csv'),
 WindowsPath('../data/raw/2_6_r4_architectures.csv'),
 WindowsPath('../data/raw/2_6_r5_architectures.csv'),
 WindowsPath('../data/raw/2_6_r6_architectures.csv'),
 WindowsPath('../data/raw/2_6_r7_architectures.csv'),
 WindowsPath('../data/raw/2_6_r8_architectures.csv'),
 WindowsPath('../data/raw/2_6_r9_architectures.csv'),
 WindowsPath('../data/raw/2_7_r1_architectures.csv'),
 WindowsPath('../data/raw/2_7_r2_architectures.csv'),
 WindowsPath('../data/raw/2_7_r3_architectures.csv'),
 WindowsPath('../data/raw/2_7_r4_architectures.csv'),
 WindowsPath('../data/raw/2_7_r5_architectures.csv'),
 WindowsPath('../data/raw/2_7_r6_architectures.csv'),
 WindowsPath('../data/raw/2_7_r7_architectures.csv'),
 WindowsPath('../data/raw/2_7_r8_architectures.csv'),
 WindowsPath('../data/raw/2_7_r9_architectures.csv'),
 WindowsPath('../data/raw/2_8_r1_architectures.csv'),
 WindowsPath('../data/raw/2_8_r2_architectures.csv'),
 WindowsPath('../data/raw/2_8_r3_architectures.csv'),
 WindowsPath('../data/raw/2_8_r4_architectures.csv'),
 WindowsPath('../data/raw/2_8_r5_architectures.csv'),
 WindowsPath('../data/raw/2_8_r6_architectures.csv'),
 WindowsPath('../data/raw/2_8_r7_architectures.csv'),
 WindowsPath('../data/raw/2_8_r8_architectures.csv'),
 WindowsPath('../data/raw/2_8_r9_architectures.csv'),
 WindowsPath('../data/raw/2_9_r1_architectures.csv'),
 WindowsPath('../data/raw/2_9_r2_architectures.csv'),
 WindowsPath('../data/raw/2_9_r3_architectures.csv'),
 WindowsPath('../data/raw/2_9_r4_architectures.csv'),
 WindowsPath('../data/raw/2_9_r5_architectures.csv'),
 WindowsPath('../data/raw/2_9_r6_architectures.csv'),
 WindowsPath('../data/raw/2_9_r7_architectures.csv'),
 WindowsPath('../data/raw/2_9_r8_architectures.csv'),
 WindowsPath('../data/raw/2_9_r9_architectures.csv'),
 WindowsPath('../data/raw/3_1_r1_architectures.csv'),
 WindowsPath('../data/raw/3_1_r2_architectures.csv'),
 WindowsPath('../data/raw/3_1_r3_architectures.csv'),
 WindowsPath('../data/raw/3_1_r4_architectures.csv'),
 WindowsPath('../data/raw/3_1_r5_architectures.csv'),
 WindowsPath('../data/raw/3_1_r6_architectures.csv'),
 WindowsPath('../data/raw/3_1_r7_architectures.csv'),
 WindowsPath('../data/raw/3_1_r8_architectures.csv'),
 WindowsPath('../data/raw/3_1_r9_architectures.csv'),
 WindowsPath('../data/raw/3_2_r1_architectures.csv'),
 WindowsPath('../data/raw/3_2_r2_architectures.csv'),
 WindowsPath('../data/raw/3_2_r3_architectures.csv'),
 WindowsPath('../data/raw/3_2_r4_architectures.csv'),
 WindowsPath('../data/raw/3_2_r5_architectures.csv'),
 WindowsPath('../data/raw/3_2_r6_architectures.csv'),
 WindowsPath('../data/raw/3_2_r7_architectures.csv'),
 WindowsPath('../data/raw/3_2_r8_architectures.csv'),
 WindowsPath('../data/raw/3_2_r9_architectures.csv'),
 WindowsPath('../data/raw/3_3_r1_architectures.csv'),
 WindowsPath('../data/raw/3_3_r2_architectures.csv'),
 WindowsPath('../data/raw/3_3_r3_architectures.csv'),
 WindowsPath('../data/raw/3_3_r4_architectures.csv'),
 WindowsPath('../data/raw/3_3_r5_architectures.csv'),
 WindowsPath('../data/raw/3_3_r6_architectures.csv'),
 WindowsPath('../data/raw/3_3_r7_architectures.csv'),
 WindowsPath('../data/raw/3_3_r8_architectures.csv'),
 WindowsPath('../data/raw/3_3_r9_architectures.csv'),
 WindowsPath('../data/raw/3_4_r1_architectures.csv'),
 WindowsPath('../data/raw/3_4_r2_architectures.csv'),
 WindowsPath('../data/raw/3_4_r3_architectures.csv'),
 WindowsPath('../data/raw/3_4_r4_architectures.csv'),
 WindowsPath('../data/raw/3_4_r5_architectures.csv'),
 WindowsPath('../data/raw/3_4_r6_architectures.csv'),
 WindowsPath('../data/raw/3_4_r7_architectures.csv'),
 WindowsPath('../data/raw/3_4_r8_architectures.csv'),
 WindowsPath('../data/raw/3_4_r9_architectures.csv'),
 WindowsPath('../data/raw/3_5_r1_architectures.csv'),
 WindowsPath('../data/raw/3_5_r2_architectures.csv'),
 WindowsPath('../data/raw/3_5_r3_architectures.csv'),
 WindowsPath('../data/raw/3_5_r4_architectures.csv'),
 WindowsPath('../data/raw/3_5_r5_architectures.csv'),
 WindowsPath('../data/raw/3_5_r6_architectures.csv'),
 WindowsPath('../data/raw/3_5_r7_architectures.csv'),
 WindowsPath('../data/raw/3_5_r8_architectures.csv'),
 WindowsPath('../data/raw/3_5_r9_architectures.csv'),
 WindowsPath('../data/raw/3_6_r1_architectures.csv'),
 WindowsPath('../data/raw/3_6_r2_architectures.csv'),
 WindowsPath('../data/raw/3_6_r3_architectures.csv'),
 WindowsPath('../data/raw/3_6_r4_architectures.csv'),
 WindowsPath('../data/raw/3_6_r5_architectures.csv'),
 WindowsPath('../data/raw/3_6_r6_architectures.csv'),
 WindowsPath('../data/raw/3_6_r7_architectures.csv'),
 WindowsPath('../data/raw/3_6_r8_architectures.csv'),
 WindowsPath('../data/raw/3_6_r9_architectures.csv'),
 WindowsPath('../data/raw/3_7_r1_architectures.csv'),
 WindowsPath('../data/raw/3_7_r2_architectures.csv'),
 WindowsPath('../data/raw/3_7_r3_architectures.csv'),
 WindowsPath('../data/raw/3_7_r4_architectures.csv'),
 WindowsPath('../data/raw/3_7_r5_architectures.csv'),
 WindowsPath('../data/raw/3_7_r6_architectures.csv'),
 WindowsPath('../data/raw/3_7_r7_architectures.csv'),
 WindowsPath('../data/raw/3_7_r8_architectures.csv'),
 WindowsPath('../data/raw/3_7_r9_architectures.csv'),
 WindowsPath('../data/raw/3_8_r1_architectures.csv'),
 WindowsPath('../data/raw/3_8_r2_architectures.csv'),
 WindowsPath('../data/raw/3_8_r3_architectures.csv'),
 WindowsPath('../data/raw/3_8_r4_architectures.csv'),
 WindowsPath('../data/raw/3_8_r5_architectures.csv'),
 WindowsPath('../data/raw/3_8_r6_architectures.csv'),
 WindowsPath('../data/raw/3_8_r7_architectures.csv'),
 WindowsPath('../data/raw/3_8_r8_architectures.csv'),
 WindowsPath('../data/raw/3_8_r9_architectures.csv'),
 WindowsPath('../data/raw/3_9_r1_architectures.csv'),
 WindowsPath('../data/raw/3_9_r2_architectures.csv'),
 WindowsPath('../data/raw/3_9_r3_architectures.csv'),
 WindowsPath('../data/raw/3_9_r4_architectures.csv'),
 WindowsPath('../data/raw/3_9_r5_architectures.csv'),
 WindowsPath('../data/raw/3_9_r6_architectures.csv'),
 WindowsPath('../data/raw/3_9_r7_architectures.csv'),
 WindowsPath('../data/raw/3_9_r8_architectures.csv'),
 WindowsPath('../data/raw/3_9_r9_architectures.csv'),
 WindowsPath('../data/raw/4_1_r1_architectures.csv'),
 WindowsPath('../data/raw/4_1_r2_architectures.csv'),
 WindowsPath('../data/raw/4_1_r3_architectures.csv'),
 WindowsPath('../data/raw/4_1_r4_architectures.csv'),
 WindowsPath('../data/raw/4_1_r5_architectures.csv'),
 WindowsPath('../data/raw/4_1_r6_architectures.csv'),
 WindowsPath('../data/raw/4_1_r7_architectures.csv'),
 WindowsPath('../data/raw/4_1_r8_architectures.csv'),
 WindowsPath('../data/raw/4_1_r9_architectures.csv'),
 WindowsPath('../data/raw/4_2_r1_architectures.csv'),
 WindowsPath('../data/raw/4_2_r2_architectures.csv'),
 WindowsPath('../data/raw/4_2_r3_architectures.csv'),
 WindowsPath('../data/raw/4_2_r4_architectures.csv'),
 WindowsPath('../data/raw/4_2_r5_architectures.csv'),
 WindowsPath('../data/raw/4_2_r6_architectures.csv'),
 WindowsPath('../data/raw/4_2_r7_architectures.csv'),
 WindowsPath('../data/raw/4_2_r8_architectures.csv'),
 WindowsPath('../data/raw/4_2_r9_architectures.csv'),
 WindowsPath('../data/raw/4_3_r1_architectures.csv'),
 WindowsPath('../data/raw/4_3_r2_architectures.csv'),
 WindowsPath('../data/raw/4_3_r3_architectures.csv'),
 WindowsPath('../data/raw/4_3_r4_architectures.csv'),
 WindowsPath('../data/raw/4_3_r5_architectures.csv'),
 WindowsPath('../data/raw/4_3_r6_architectures.csv'),
 WindowsPath('../data/raw/4_3_r7_architectures.csv'),
 WindowsPath('../data/raw/4_3_r8_architectures.csv'),
 WindowsPath('../data/raw/4_3_r9_architectures.csv'),
 WindowsPath('../data/raw/4_4_r1_architectures.csv'),
 WindowsPath('../data/raw/4_4_r2_architectures.csv'),
 WindowsPath('../data/raw/4_4_r3_architectures.csv'),
 WindowsPath('../data/raw/4_4_r4_architectures.csv'),
 WindowsPath('../data/raw/4_4_r5_architectures.csv'),
 WindowsPath('../data/raw/4_4_r6_architectures.csv'),
 WindowsPath('../data/raw/4_4_r7_architectures.csv'),
 WindowsPath('../data/raw/4_4_r8_architectures.csv'),
 WindowsPath('../data/raw/4_4_r9_architectures.csv'),
 WindowsPath('../data/raw/4_5_r1_architectures.csv'),
 WindowsPath('../data/raw/4_5_r2_architectures.csv'),
 WindowsPath('../data/raw/4_5_r3_architectures.csv'),
 WindowsPath('../data/raw/4_5_r4_architectures.csv'),
 WindowsPath('../data/raw/4_5_r5_architectures.csv'),
 WindowsPath('../data/raw/4_5_r6_architectures.csv'),
 WindowsPath('../data/raw/4_5_r7_architectures.csv'),
 WindowsPath('../data/raw/4_5_r8_architectures.csv'),
 WindowsPath('../data/raw/4_5_r9_architectures.csv'),
 WindowsPath('../data/raw/4_6_r1_architectures.csv'),
 WindowsPath('../data/raw/4_6_r2_architectures.csv'),
 WindowsPath('../data/raw/4_6_r3_architectures.csv'),
 WindowsPath('../data/raw/4_6_r4_architectures.csv'),
 WindowsPath('../data/raw/4_6_r5_architectures.csv'),
 WindowsPath('../data/raw/4_6_r6_architectures.csv'),
 WindowsPath('../data/raw/4_6_r7_architectures.csv'),
 WindowsPath('../data/raw/4_6_r8_architectures.csv'),
 WindowsPath('../data/raw/4_6_r9_architectures.csv'),
 WindowsPath('../data/raw/4_7_r1_architectures.csv'),
 WindowsPath('../data/raw/4_7_r2_architectures.csv'),
 WindowsPath('../data/raw/4_7_r3_architectures.csv'),
 WindowsPath('../data/raw/4_7_r4_architectures.csv'),
 WindowsPath('../data/raw/4_7_r5_architectures.csv'),
 WindowsPath('../data/raw/4_7_r6_architectures.csv'),
 WindowsPath('../data/raw/4_7_r7_architectures.csv'),
 WindowsPath('../data/raw/4_7_r8_architectures.csv'),
 WindowsPath('../data/raw/4_7_r9_architectures.csv'),
 WindowsPath('../data/raw/4_8_r1_architectures.csv'),
 WindowsPath('../data/raw/4_8_r2_architectures.csv'),
 WindowsPath('../data/raw/4_8_r3_architectures.csv'),
 WindowsPath('../data/raw/4_8_r4_architectures.csv'),
 WindowsPath('../data/raw/4_8_r5_architectures.csv'),
 WindowsPath('../data/raw/4_8_r6_architectures.csv'),
 WindowsPath('../data/raw/4_8_r7_architectures.csv'),
 WindowsPath('../data/raw/4_8_r8_architectures.csv'),
 WindowsPath('../data/raw/4_8_r9_architectures.csv'),
 WindowsPath('../data/raw/4_9_r1_architectures.csv'),
 WindowsPath('../data/raw/4_9_r2_architectures.csv'),
 WindowsPath('../data/raw/4_9_r3_architectures.csv'),
 WindowsPath('../data/raw/4_9_r4_architectures.csv'),
 WindowsPath('../data/raw/4_9_r5_architectures.csv'),
 WindowsPath('../data/raw/4_9_r6_architectures.csv'),
 WindowsPath('../data/raw/4_9_r7_architectures.csv'),
 WindowsPath('../data/raw/4_9_r8_architectures.csv'),
 WindowsPath('../data/raw/4_9_r9_architectures.csv'),
 WindowsPath('../data/raw/5_1_r1_architectures.csv'),
 WindowsPath('../data/raw/5_1_r2_architectures.csv'),
 WindowsPath('../data/raw/5_1_r3_architectures.csv'),
 WindowsPath('../data/raw/5_1_r4_architectures.csv'),
 WindowsPath('../data/raw/5_1_r5_architectures.csv'),
 WindowsPath('../data/raw/5_1_r6_architectures.csv'),
 WindowsPath('../data/raw/5_1_r7_architectures.csv'),
 WindowsPath('../data/raw/5_1_r8_architectures.csv'),
 WindowsPath('../data/raw/5_1_r9_architectures.csv'),
 WindowsPath('../data/raw/5_2_r1_architectures.csv'),
 WindowsPath('../data/raw/5_2_r2_architectures.csv'),
 WindowsPath('../data/raw/5_2_r3_architectures.csv'),
 WindowsPath('../data/raw/5_2_r4_architectures.csv'),
 WindowsPath('../data/raw/5_2_r5_architectures.csv'),
 WindowsPath('../data/raw/5_2_r6_architectures.csv'),
 WindowsPath('../data/raw/5_2_r7_architectures.csv'),
 WindowsPath('../data/raw/5_2_r8_architectures.csv'),
 WindowsPath('../data/raw/5_2_r9_architectures.csv'),
 WindowsPath('../data/raw/5_3_r1_architectures.csv'),
 WindowsPath('../data/raw/5_3_r2_architectures.csv'),
 WindowsPath('../data/raw/5_3_r3_architectures.csv'),
 WindowsPath('../data/raw/5_3_r4_architectures.csv'),
 WindowsPath('../data/raw/5_3_r5_architectures.csv'),
 WindowsPath('../data/raw/5_3_r6_architectures.csv'),
 WindowsPath('../data/raw/5_3_r7_architectures.csv'),
 WindowsPath('../data/raw/5_3_r8_architectures.csv'),
 WindowsPath('../data/raw/5_3_r9_architectures.csv'),
 WindowsPath('../data/raw/5_4_r1_architectures.csv'),
 WindowsPath('../data/raw/5_4_r2_architectures.csv'),
 WindowsPath('../data/raw/5_4_r3_architectures.csv'),
 WindowsPath('../data/raw/5_4_r4_architectures.csv'),
 WindowsPath('../data/raw/5_4_r5_architectures.csv'),
 WindowsPath('../data/raw/5_4_r6_architectures.csv'),
 WindowsPath('../data/raw/5_4_r7_architectures.csv'),
 WindowsPath('../data/raw/5_4_r8_architectures.csv'),
 WindowsPath('../data/raw/5_4_r9_architectures.csv'),
 WindowsPath('../data/raw/5_5_r1_architectures.csv'),
 WindowsPath('../data/raw/5_5_r2_architectures.csv'),
 WindowsPath('../data/raw/5_5_r3_architectures.csv'),
 WindowsPath('../data/raw/5_5_r4_architectures.csv'),
 WindowsPath('../data/raw/5_5_r5_architectures.csv'),
 WindowsPath('../data/raw/5_5_r6_architectures.csv'),
 WindowsPath('../data/raw/5_5_r7_architectures.csv'),
 WindowsPath('../data/raw/5_5_r8_architectures.csv'),
 WindowsPath('../data/raw/5_5_r9_architectures.csv'),

In [260]:
all_summaries = []

if RUN_FILL:
    for csv_path in csv_paths:
        summary = fill_one_csv_file(csv_path, max_new_evaluations=MAX_NEW_EVALUATIONS_PER_FILE, reverse=True)
        all_summaries.append(summary)
    print("\nAll requested CSV files are complete for the selected MFA predecessor boxes.")
else:
    print("RUN_FILL is False. Review plan_df, then set RUN_FILL=True to begin.")

all_summaries

====================================================================================================
Processing ..\data\raw\1_1_r1_architectures.csv
====================================================================================================

Group h=2, exponent=1
Recorded MFA hidden tuples: [(1,)]
Coordinatewise search-box maximum: (1,)
Enumerated candidates: 1
Finished h=2, exponent=1: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=3, exponent=1
Recorded MFA hidden tuples: [(1, 1)]
Coordinatewise search-box maximum: (1, 1)
Enumerated candidates: 1
Finished h=3, exponent=1: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=4, exponent=1
Recorded MFA hidden tuples: [(1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1)
Enumerated candidates: 1
Finished h=4, exponent=1: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=5, exponent=1
Recorded MFA hidden tuples: [(1, 1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1, 1)
Enumerated candidates: 1
Finished h=5, exponent=1: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=6, exponent=1
Recorded MFA hidden tuples: [(1, 1, 1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1, 1, 1)
Enumerated candidates: 1
Finished h=6, exponent=1: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s
====================================================================================================
Processing ..\data\raw\1_1_r2_architectures.csv
====================================================================================================

Group h=2, exponent=2
Recorded MFA hidden tuples: [(1,)]
Coordinatewise search-box maximum: (1,)
Enumerated candidates: 1
Finished h=2, exponent=2: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=3, exponent=2
Recorded MFA hidden tuples: [(1, 1)]
Coordinatewise search-box maximum: (1, 1)
Enumerated candidates: 1
Finished h=3, exponent=2: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=4, exponent=2
Recorded MFA hidden tuples: [(1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1)
Enumerated candidates: 1
Finished h=4, exponent=2: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=5, exponent=2
Recorded MFA hidden tuples: [(1, 1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1, 1)
Enumerated candidates: 1
Finished h=5, exponent=2: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=6, exponent=2
Recorded MFA hidden tuples: [(1, 1, 1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1, 1, 1)
Enumerated candidates: 1
Finished h=6, exponent=2: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=7, exponent=2
Recorded MFA hidden tuples: [(1, 1, 1, 1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1, 1, 1, 1)
Enumerated candidates: 1
Finished h=7, exponent=2: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=8, exponent=2
Recorded MFA hidden tuples: [(1, 1, 1, 1, 1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1, 1, 1, 1, 1)
Enumerated candidates: 1
Finished h=8, exponent=2: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=9, exponent=2
Recorded MFA hidden tuples: [(1, 1, 1, 1, 1, 1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1, 1, 1, 1, 1, 1)
Enumerated candidates: 1
Finished h=9, exponent=2: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s
====================================================================================================
Processing ..\data\raw\1_1_r3_architectures.csv
====================================================================================================

Group h=2, exponent=3
Recorded MFA hidden tuples: [(1,)]
Coordinatewise search-box maximum: (1,)
Enumerated candidates: 1
Finished h=2, exponent=3: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=3, exponent=3
Recorded MFA hidden tuples: [(1, 1)]
Coordinatewise search-box maximum: (1, 1)
Enumerated candidates: 1
Finished h=3, exponent=3: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=4, exponent=3
Recorded MFA hidden tuples: [(1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1)
Enumerated candidates: 1
Finished h=4, exponent=3: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=5, exponent=3
Recorded MFA hidden tuples: [(1, 1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1, 1)
Enumerated candidates: 1
Finished h=5, exponent=3: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=6, exponent=3
Recorded MFA hidden tuples: [(1, 1, 1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1, 1, 1)
Enumerated candidates: 1
Finished h=6, exponent=3: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s
====================================================================================================
Processing ..\data\raw\1_1_r4_architectures.csv
====================================================================================================

Group h=2, exponent=4
Recorded MFA hidden tuples: [(1,)]
Coordinatewise search-box maximum: (1,)
Enumerated candidates: 1
Finished h=2, exponent=4: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=3, exponent=4
Recorded MFA hidden tuples: [(1, 1)]
Coordinatewise search-box maximum: (1, 1)
Enumerated candidates: 1
Finished h=3, exponent=4: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=4, exponent=4
Recorded MFA hidden tuples: [(1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1)
Enumerated candidates: 1
Finished h=4, exponent=4: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=5, exponent=4
Recorded MFA hidden tuples: [(1, 1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1, 1)
Enumerated candidates: 1
Finished h=5, exponent=4: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=6, exponent=4
Recorded MFA hidden tuples: [(1, 1, 1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1, 1, 1)
Enumerated candidates: 1
Finished h=6, exponent=4: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s
====================================================================================================
Processing ..\data\raw\1_1_r5_architectures.csv
====================================================================================================

Group h=2, exponent=5
Recorded MFA hidden tuples: [(1,)]
Coordinatewise search-box maximum: (1,)
Enumerated candidates: 1
Finished h=2, exponent=5: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=3, exponent=5
Recorded MFA hidden tuples: [(1, 1)]
Coordinatewise search-box maximum: (1, 1)
Enumerated candidates: 1
Finished h=3, exponent=5: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=4, exponent=5
Recorded MFA hidden tuples: [(1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1)
Enumerated candidates: 1
Finished h=4, exponent=5: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=5, exponent=5
Recorded MFA hidden tuples: [(1, 1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1, 1)
Enumerated candidates: 1
Finished h=5, exponent=5: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=6, exponent=5
Recorded MFA hidden tuples: [(1, 1, 1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1, 1, 1)
Enumerated candidates: 1
Finished h=6, exponent=5: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s
====================================================================================================
Processing ..\data\raw\1_1_r6_architectures.csv
====================================================================================================

Group h=2, exponent=6
Recorded MFA hidden tuples: [(1,)]
Coordinatewise search-box maximum: (1,)
Enumerated candidates: 1
Finished h=2, exponent=6: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=3, exponent=6
Recorded MFA hidden tuples: [(1, 1)]
Coordinatewise search-box maximum: (1, 1)
Enumerated candidates: 1
Finished h=3, exponent=6: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s
====================================================================================================
Processing ..\data\raw\1_1_r7_architectures.csv
====================================================================================================

Group h=2, exponent=7
Recorded MFA hidden tuples: [(1,)]
Coordinatewise search-box maximum: (1,)
Enumerated candidates: 1
Finished h=2, exponent=7: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=3, exponent=7
Recorded MFA hidden tuples: [(1, 1)]
Coordinatewise search-box maximum: (1, 1)
Enumerated candidates: 1
Finished h=3, exponent=7: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s
====================================================================================================
Processing ..\data\raw\1_1_r8_architectures.csv
====================================================================================================

Group h=2, exponent=8
Recorded MFA hidden tuples: [(1,)]
Coordinatewise search-box maximum: (1,)
Enumerated candidates: 1
Finished h=2, exponent=8: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=3, exponent=8
Recorded MFA hidden tuples: [(1, 1)]
Coordinatewise search-box maximum: (1, 1)
Enumerated candidates: 1
Finished h=3, exponent=8: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s
====================================================================================================
Processing ..\data\raw\1_1_r9_architectures.csv
====================================================================================================

Group h=2, exponent=9
Recorded MFA hidden tuples: [(1,)]
Coordinatewise search-box maximum: (1,)
Enumerated candidates: 1
Finished h=2, exponent=9: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=3, exponent=9
Recorded MFA hidden tuples: [(1, 1)]
Coordinatewise search-box maximum: (1, 1)
Enumerated candidates: 1
Finished h=3, exponent=9: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s
====================================================================================================
Processing ..\data\raw\1_2_r1_architectures.csv
====================================================================================================

Group h=2, exponent=1
Recorded MFA hidden tuples: [(1,)]
Coordinatewise search-box maximum: (1,)
Enumerated candidates: 1
Finished h=2, exponent=1: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=3, exponent=1
Recorded MFA hidden tuples: [(1, 1)]
Coordinatewise search-box maximum: (1, 1)
Enumerated candidates: 1
Finished h=3, exponent=1: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=4, exponent=1
Recorded MFA hidden tuples: [(1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1)
Enumerated candidates: 1
Finished h=4, exponent=1: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=5, exponent=1
Recorded MFA hidden tuples: [(1, 1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1, 1)
Enumerated candidates: 1
Finished h=5, exponent=1: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=6, exponent=1
Recorded MFA hidden tuples: [(1, 1, 1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1, 1, 1)
Enumerated candidates: 1
Finished h=6, exponent=1: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s
====================================================================================================
Processing ..\data\raw\1_2_r2_architectures.csv
====================================================================================================

Group h=2, exponent=2
Recorded MFA hidden tuples: [(1,)]
Coordinatewise search-box maximum: (1,)
Enumerated candidates: 1
Finished h=2, exponent=2: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=3, exponent=2
Recorded MFA hidden tuples: [(1, 1)]
Coordinatewise search-box maximum: (1, 1)
Enumerated candidates: 1
Finished h=3, exponent=2: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=4, exponent=2
Recorded MFA hidden tuples: [(1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1)
Enumerated candidates: 1
Finished h=4, exponent=2: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=5, exponent=2
Recorded MFA hidden tuples: [(1, 1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1, 1)
Enumerated candidates: 1
Finished h=5, exponent=2: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=6, exponent=2
Recorded MFA hidden tuples: [(1, 1, 1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1, 1, 1)
Enumerated candidates: 1
Finished h=6, exponent=2: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=7, exponent=2
Recorded MFA hidden tuples: [(1, 1, 1, 1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1, 1, 1, 1)
Enumerated candidates: 1
Finished h=7, exponent=2: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=8, exponent=2
Recorded MFA hidden tuples: [(1, 1, 1, 1, 1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1, 1, 1, 1, 1)
Enumerated candidates: 1
Finished h=8, exponent=2: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=9, exponent=2
Recorded MFA hidden tuples: [(1, 1, 1, 1, 1, 1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1, 1, 1, 1, 1, 1)
Enumerated candidates: 1
Finished h=9, exponent=2: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s
====================================================================================================
Processing ..\data\raw\1_2_r3_architectures.csv
====================================================================================================

Group h=2, exponent=3
Recorded MFA hidden tuples: [(1,)]
Coordinatewise search-box maximum: (1,)
Enumerated candidates: 1
Finished h=2, exponent=3: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=3, exponent=3
Recorded MFA hidden tuples: [(1, 1)]
Coordinatewise search-box maximum: (1, 1)
Enumerated candidates: 1
Finished h=3, exponent=3: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=4, exponent=3
Recorded MFA hidden tuples: [(1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1)
Enumerated candidates: 1
Finished h=4, exponent=3: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=5, exponent=3
Recorded MFA hidden tuples: [(1, 1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1, 1)
Enumerated candidates: 1
Finished h=5, exponent=3: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=6, exponent=3
Recorded MFA hidden tuples: [(1, 1, 1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1, 1, 1)
Enumerated candidates: 1
Finished h=6, exponent=3: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s
====================================================================================================
Processing ..\data\raw\1_2_r4_architectures.csv
====================================================================================================

Group h=2, exponent=4
Recorded MFA hidden tuples: [(1,)]
Coordinatewise search-box maximum: (1,)
Enumerated candidates: 1
Finished h=2, exponent=4: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=3, exponent=4
Recorded MFA hidden tuples: [(1, 1)]
Coordinatewise search-box maximum: (1, 1)
Enumerated candidates: 1
Finished h=3, exponent=4: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=4, exponent=4
Recorded MFA hidden tuples: [(1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1)
Enumerated candidates: 1
Finished h=4, exponent=4: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=5, exponent=4
Recorded MFA hidden tuples: [(1, 1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1, 1)
Enumerated candidates: 1
Finished h=5, exponent=4: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=6, exponent=4
Recorded MFA hidden tuples: [(1, 1, 1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1, 1, 1)
Enumerated candidates: 1
Finished h=6, exponent=4: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s
====================================================================================================
Processing ..\data\raw\1_2_r5_architectures.csv
====================================================================================================

Group h=2, exponent=5
Recorded MFA hidden tuples: [(1,)]
Coordinatewise search-box maximum: (1,)
Enumerated candidates: 1
Finished h=2, exponent=5: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=3, exponent=5
Recorded MFA hidden tuples: [(1, 1)]
Coordinatewise search-box maximum: (1, 1)
Enumerated candidates: 1
Finished h=3, exponent=5: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=4, exponent=5
Recorded MFA hidden tuples: [(1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1)
Enumerated candidates: 1
Finished h=4, exponent=5: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=5, exponent=5
Recorded MFA hidden tuples: [(1, 1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1, 1)
Enumerated candidates: 1
Finished h=5, exponent=5: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=6, exponent=5
Recorded MFA hidden tuples: [(1, 1, 1, 1, 1)]
Coordinatewise search-box maximum: (1, 1, 1, 1, 1)
Enumerated candidates: 1
Finished h=6, exponent=5: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s
====================================================================================================
Processing ..\data\raw\1_2_r6_architectures.csv
====================================================================================================

Group h=2, exponent=6
Recorded MFA hidden tuples: [(1,)]
Coordinatewise search-box maximum: (1,)
Enumerated candidates: 1
Finished h=2, exponent=6: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=3, exponent=6
Recorded MFA hidden tuples: [(1, 1)]
Coordinatewise search-box maximum: (1, 1)
Enumerated candidates: 1
Finished h=3, exponent=6: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s
====================================================================================================
Processing ..\data\raw\1_2_r7_architectures.csv
====================================================================================================

Group h=2, exponent=7
Recorded MFA hidden tuples: [(1,)]
Coordinatewise search-box maximum: (1,)
Enumerated candidates: 1
Finished h=2, exponent=7: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

Group h=3, exponent=7
Recorded MFA hidden tuples: [(1, 1)]
Coordinatewise search-box maximum: (1, 1)
Enumerated candidates: 1
Finished h=3, exponent=7: eligible=0, new=0, existing=0, MFA rows=1, not-below skips=0, elapsed=0.0s

KeyboardInterrupt:

## Post-run summary

In [261]:
for path in csv_paths:
    df = read_architecture_csv(path)
    print("=" * 100)
    print(path)
    print("rows:", len(df))
    print("is_full_dimension counts:")
    print(df["is_full_dimension"].value_counts(dropna=False))
    print("status counts:")
    print(df["status"].value_counts(dropna=False).head(20))
    marked = df[df["is_minimal"].map(truthy)]
    print("Recorded MFAs:")
    display(marked[["h", "exponent", "architecture", "dimension_computed", "ambient_dimension", "num_parameters",]])

====================================================================================================
..\data\raw\1_1_r1_architectures.csv
rows: 62
is_full_dimension counts:
is_full_dimension
True    62
Name: count, dtype: int64
status counts:
status
NaN                           61
filling_below_recorded_mfa     1
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
50,2.0,1.0,"[1, 1, 1]",1.0,1.0,2.0
58,3.0,1.0,"[1, 1, 1, 1]",1.0,1.0,3.0
59,4.0,1.0,"[1, 1, 1, 1, 1]",1.0,1.0,4.0
60,5.0,1.0,"[1, 1, 1, 1, 1, 1]",1.0,1.0,5.0
61,6.0,1.0,"[1, 1, 1, 1, 1, 1, 1]",1.0,1.0,6.0

====================================================================================================
..\data\raw\1_1_r2_architectures.csv
rows: 72
is_full_dimension counts:
is_full_dimension
True    72
Name: count, dtype: int64
status counts:
status
NaN    72
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
48,2,2,"[1, 1, 1]",1,1,2
65,3,2,"[1, 1, 1, 1]",1,1,3
66,4,2,"[1, 1, 1, 1, 1]",1,1,4
67,5,2,"[1, 1, 1, 1, 1, 1]",1,1,5
68,6,2,"[1, 1, 1, 1, 1, 1, 1]",1,1,6
69,7,2,"[1, 1, 1, 1, 1, 1, 1, 1]",1,1,7
70,8,2,"[1, 1, 1, 1, 1, 1, 1, 1, 1]",1,1,8
71,9,2,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",1,1,9

====================================================================================================
..\data\raw\1_1_r3_architectures.csv
rows: 52
is_full_dimension counts:
is_full_dimension
True    52
Name: count, dtype: int64
status counts:
status
NaN    52
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
40,2,3,"[1, 1, 1]",1,1,2
48,3,3,"[1, 1, 1, 1]",1,1,3
49,4,3,"[1, 1, 1, 1, 1]",1,1,4
50,5,3,"[1, 1, 1, 1, 1, 1]",1,1,5
51,6,3,"[1, 1, 1, 1, 1, 1, 1]",1,1,6

====================================================================================================
..\data\raw\1_1_r4_architectures.csv
rows: 58
is_full_dimension counts:
is_full_dimension
True    58
Name: count, dtype: int64
status counts:
status
NaN    58
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
44,2,4,"[1, 1, 1]",1,1,2
54,3,4,"[1, 1, 1, 1]",1,1,3
55,4,4,"[1, 1, 1, 1, 1]",1,1,4
56,5,4,"[1, 1, 1, 1, 1, 1]",1,1,5
57,6,4,"[1, 1, 1, 1, 1, 1, 1]",1,1,6

====================================================================================================
..\data\raw\1_1_r5_architectures.csv
rows: 69
is_full_dimension counts:
is_full_dimension
True    69
Name: count, dtype: int64
status counts:
status
NaN    69
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
53,2,5,"[1, 1, 1]",1,1,2
65,3,5,"[1, 1, 1, 1]",1,1,3
66,4,5,"[1, 1, 1, 1, 1]",1,1,4
67,5,5,"[1, 1, 1, 1, 1, 1]",1,1,5
68,6,5,"[1, 1, 1, 1, 1, 1, 1]",1,1,6

====================================================================================================
..\data\raw\1_1_r6_architectures.csv
rows: 59
is_full_dimension counts:
is_full_dimension
True    59
Name: count, dtype: int64
status counts:
status
NaN    59
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
44,2,6,"[1, 1, 1]",1,1,2
58,3,6,"[1, 1, 1, 1]",1,1,3

====================================================================================================
..\data\raw\1_1_r7_architectures.csv
rows: 55
is_full_dimension counts:
is_full_dimension
True    55
Name: count, dtype: int64
status counts:
status
NaN    55
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
40,2,7,"[1, 1, 1]",1,1,2
54,3,7,"[1, 1, 1, 1]",1,1,3

====================================================================================================
..\data\raw\1_1_r8_architectures.csv
rows: 58
is_full_dimension counts:
is_full_dimension
True    58
Name: count, dtype: int64
status counts:
status
NaN    58
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
42,2,8,"[1, 1, 1]",1,1,2
57,3,8,"[1, 1, 1, 1]",1,1,3

====================================================================================================
..\data\raw\1_1_r9_architectures.csv
rows: 56
is_full_dimension counts:
is_full_dimension
True    56
Name: count, dtype: int64
status counts:
status
NaN    56
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
44,2,9,"[1, 1, 1]",1,1,2
55,3,9,"[1, 1, 1, 1]",1,1,3

====================================================================================================
..\data\raw\1_2_r1_architectures.csv
rows: 68
is_full_dimension counts:
is_full_dimension
True    68
Name: count, dtype: int64
status counts:
status
NaN    68
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
52,2,1,"[1, 1, 2]",2,2,3
64,3,1,"[1, 1, 1, 2]",2,2,4
65,4,1,"[1, 1, 1, 1, 2]",2,2,5
66,5,1,"[1, 1, 1, 1, 1, 2]",2,2,6
67,6,1,"[1, 1, 1, 1, 1, 1, 2]",2,2,7

====================================================================================================
..\data\raw\1_2_r2_architectures.csv
rows: 72
is_full_dimension counts:
is_full_dimension
True    72
Name: count, dtype: int64
status counts:
status
NaN    72
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
54,2,2,"[1, 1, 2]",2,2,3
65,3,2,"[1, 1, 1, 2]",2,2,4
66,4,2,"[1, 1, 1, 1, 2]",2,2,5
67,5,2,"[1, 1, 1, 1, 1, 2]",2,2,6
68,6,2,"[1, 1, 1, 1, 1, 1, 2]",2,2,7
69,7,2,"[1, 1, 1, 1, 1, 1, 1, 2]",2,2,8
70,8,2,"[1, 1, 1, 1, 1, 1, 1, 1, 2]",2,2,9
71,9,2,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 2]",2,2,10

====================================================================================================
..\data\raw\1_2_r3_architectures.csv
rows: 65
is_full_dimension counts:
is_full_dimension
True    65
Name: count, dtype: int64
status counts:
status
NaN    65
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
47,2,3,"[1, 1, 2]",2,2,3
61,3,3,"[1, 1, 1, 2]",2,2,4
62,4,3,"[1, 1, 1, 1, 2]",2,2,5
63,5,3,"[1, 1, 1, 1, 1, 2]",2,2,6
64,6,3,"[1, 1, 1, 1, 1, 1, 2]",2,2,7

====================================================================================================
..\data\raw\1_2_r4_architectures.csv
rows: 54
is_full_dimension counts:
is_full_dimension
True    54
Name: count, dtype: int64
status counts:
status
NaN    54
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
41,2,4,"[1, 1, 2]",2,2,3
50,3,4,"[1, 1, 1, 2]",2,2,4
51,4,4,"[1, 1, 1, 1, 2]",2,2,5
52,5,4,"[1, 1, 1, 1, 1, 2]",2,2,6
53,6,4,"[1, 1, 1, 1, 1, 1, 2]",2,2,7

====================================================================================================
..\data\raw\1_2_r5_architectures.csv
rows: 34
is_full_dimension counts:
is_full_dimension
True    34
Name: count, dtype: int64
status counts:
status
NaN    34
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
21,2,5,"[1, 1, 2]",2,2,3
30,3,5,"[1, 1, 1, 2]",2,2,4
31,4,5,"[1, 1, 1, 1, 2]",2,2,5
32,5,5,"[1, 1, 1, 1, 1, 2]",2,2,6
33,6,5,"[1, 1, 1, 1, 1, 1, 2]",2,2,7

====================================================================================================
..\data\raw\1_2_r6_architectures.csv
rows: 49
is_full_dimension counts:
is_full_dimension
True    49
Name: count, dtype: int64
status counts:
status
NaN    49
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
34,2,6,"[1, 1, 2]",2,2,3
48,3,6,"[1, 1, 1, 2]",2,2,4

====================================================================================================
..\data\raw\1_2_r7_architectures.csv
rows: 74
is_full_dimension counts:
is_full_dimension
True    74
Name: count, dtype: int64
status counts:
status
NaN                           73
filling_below_recorded_mfa     1
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
57,2.0,7.0,"[1, 1, 2]",2.0,2.0,3.0
73,3.0,7.0,"[1, 1, 1, 2]",2.0,2.0,4.0

====================================================================================================
..\data\raw\1_2_r8_architectures.csv
rows: 55
is_full_dimension counts:
is_full_dimension
True    55
Name: count, dtype: int64
status counts:
status
NaN    55
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
40,2,8,"[1, 1, 2]",2,2,3
54,3,8,"[1, 1, 1, 2]",2,2,4

====================================================================================================
..\data\raw\1_2_r9_architectures.csv
rows: 55
is_full_dimension counts:
is_full_dimension
True    55
Name: count, dtype: int64
status counts:
status
NaN    55
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
45,2,9,"[1, 1, 2]",2,2,3
54,3,9,"[1, 1, 1, 2]",2,2,4

====================================================================================================
..\data\raw\1_3_r1_architectures.csv
rows: 66
is_full_dimension counts:
is_full_dimension
True    66
Name: count, dtype: int64
status counts:
status
NaN    66
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
49,2,1,"[1, 1, 3]",3,3,4
62,3,1,"[1, 1, 1, 3]",3,3,5
63,4,1,"[1, 1, 1, 1, 3]",3,3,6
64,5,1,"[1, 1, 1, 1, 1, 3]",3,3,7
65,6,1,"[1, 1, 1, 1, 1, 1, 3]",3,3,8

====================================================================================================
..\data\raw\1_3_r2_architectures.csv
rows: 72
is_full_dimension counts:
is_full_dimension
True    72
Name: count, dtype: int64
status counts:
status
NaN    72
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
64,2,2,"[1, 1, 3]",3,3,4
65,3,2,"[1, 1, 1, 3]",3,3,5
66,4,2,"[1, 1, 1, 1, 3]",3,3,6
67,5,2,"[1, 1, 1, 1, 1, 3]",3,3,7
68,6,2,"[1, 1, 1, 1, 1, 1, 3]",3,3,8
69,7,2,"[1, 1, 1, 1, 1, 1, 1, 3]",3,3,9
70,8,2,"[1, 1, 1, 1, 1, 1, 1, 1, 3]",3,3,10
71,9,2,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 3]",3,3,11

====================================================================================================
..\data\raw\1_3_r3_architectures.csv
rows: 62
is_full_dimension counts:
is_full_dimension
True    62
Name: count, dtype: int64
status counts:
status
NaN    62
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
44,2,3,"[1, 1, 3]",3,3,4
58,3,3,"[1, 1, 1, 3]",3,3,5
59,4,3,"[1, 1, 1, 1, 3]",3,3,6
60,5,3,"[1, 1, 1, 1, 1, 3]",3,3,7
61,6,3,"[1, 1, 1, 1, 1, 1, 3]",3,3,8

====================================================================================================
..\data\raw\1_3_r4_architectures.csv
rows: 40
is_full_dimension counts:
is_full_dimension
True    40
Name: count, dtype: int64
status counts:
status
NaN    40
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
28,2,4,"[1, 1, 3]",3,3,4
36,3,4,"[1, 1, 1, 3]",3,3,5
37,4,4,"[1, 1, 1, 1, 3]",3,3,6
38,5,4,"[1, 1, 1, 1, 1, 3]",3,3,7
39,6,4,"[1, 1, 1, 1, 1, 1, 3]",3,3,8

====================================================================================================
..\data\raw\1_3_r5_architectures.csv
rows: 61
is_full_dimension counts:
is_full_dimension
True    61
Name: count, dtype: int64
status counts:
status
NaN    61
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
41,2,5,"[1, 1, 3]",3,3,4
57,3,5,"[1, 1, 1, 3]",3,3,5
58,4,5,"[1, 1, 1, 1, 3]",3,3,6
59,5,5,"[1, 1, 1, 1, 1, 3]",3,3,7
60,6,5,"[1, 1, 1, 1, 1, 1, 3]",3,3,8

====================================================================================================
..\data\raw\1_3_r6_architectures.csv
rows: 64
is_full_dimension counts:
is_full_dimension
True    64
Name: count, dtype: int64
status counts:
status
NaN    64
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
51,2,6,"[1, 1, 3]",3,3,4
63,3,6,"[1, 1, 1, 3]",3,3,5

====================================================================================================
..\data\raw\1_3_r7_architectures.csv
rows: 55
is_full_dimension counts:
is_full_dimension
True    55
Name: count, dtype: int64
status counts:
status
NaN    55
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
43,2,7,"[1, 1, 3]",3,3,4
54,3,7,"[1, 1, 1, 3]",3,3,5

====================================================================================================
..\data\raw\1_3_r8_architectures.csv
rows: 55
is_full_dimension counts:
is_full_dimension
True    55
Name: count, dtype: int64
status counts:
status
NaN                           54
filling_below_recorded_mfa     1
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
42,2.0,8.0,"[1, 1, 3]",3.0,3.0,4.0
54,3.0,8.0,"[1, 1, 1, 3]",3.0,3.0,5.0

====================================================================================================
..\data\raw\1_3_r9_architectures.csv
rows: 58
is_full_dimension counts:
is_full_dimension
True    58
Name: count, dtype: int64
status counts:
status
NaN    58
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
41,2,9,"[1, 1, 3]",3,3,4
57,3,9,"[1, 1, 1, 3]",3,3,5

====================================================================================================
..\data\raw\1_4_r1_architectures.csv
rows: 60
is_full_dimension counts:
is_full_dimension
True    60
Name: count, dtype: int64
status counts:
status
NaN    60
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
46,2,1,"[1, 1, 4]",4,4,5
56,3,1,"[1, 1, 1, 4]",4,4,6
57,4,1,"[1, 1, 1, 1, 4]",4,4,7
58,5,1,"[1, 1, 1, 1, 1, 4]",4,4,8
59,6,1,"[1, 1, 1, 1, 1, 1, 4]",4,4,9

====================================================================================================
..\data\raw\1_4_r2_architectures.csv
rows: 66
is_full_dimension counts:
is_full_dimension
True    66
Name: count, dtype: int64
status counts:
status
NaN    66
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
49,2,2,"[1, 1, 4]",4,4,5
59,3,2,"[1, 1, 1, 4]",4,4,6
60,4,2,"[1, 1, 1, 1, 4]",4,4,7
61,5,2,"[1, 1, 1, 1, 1, 4]",4,4,8
62,6,2,"[1, 1, 1, 1, 1, 1, 4]",4,4,9
63,7,2,"[1, 1, 1, 1, 1, 1, 1, 4]",4,4,10
64,8,2,"[1, 1, 1, 1, 1, 1, 1, 1, 4]",4,4,11
65,9,2,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 4]",4,4,12

====================================================================================================
..\data\raw\1_4_r3_architectures.csv
rows: 61
is_full_dimension counts:
is_full_dimension
True    61
Name: count, dtype: int64
status counts:
status
NaN    61
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
47,2,3,"[1, 1, 4]",4,4,5
57,3,3,"[1, 1, 1, 4]",4,4,6
58,4,3,"[1, 1, 1, 1, 4]",4,4,7
59,5,3,"[1, 1, 1, 1, 1, 4]",4,4,8
60,6,3,"[1, 1, 1, 1, 1, 1, 4]",4,4,9

====================================================================================================
..\data\raw\1_4_r4_architectures.csv
rows: 64
is_full_dimension counts:
is_full_dimension
True    64
Name: count, dtype: int64
status counts:
status
NaN    64
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
51,2,4,"[1, 1, 4]",4,4,5
60,3,4,"[1, 1, 1, 4]",4,4,6
61,4,4,"[1, 1, 1, 1, 4]",4,4,7
62,5,4,"[1, 1, 1, 1, 1, 4]",4,4,8
63,6,4,"[1, 1, 1, 1, 1, 1, 4]",4,4,9

====================================================================================================
..\data\raw\1_4_r5_architectures.csv
rows: 53
is_full_dimension counts:
is_full_dimension
True    53
Name: count, dtype: int64
status counts:
status
NaN    53
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
38,2,5,"[1, 1, 4]",4,4,5
49,3,5,"[1, 1, 1, 4]",4,4,6
50,4,5,"[1, 1, 1, 1, 4]",4,4,7
51,5,5,"[1, 1, 1, 1, 1, 4]",4,4,8
52,6,5,"[1, 1, 1, 1, 1, 1, 4]",4,4,9

====================================================================================================
..\data\raw\1_4_r6_architectures.csv
rows: 42
is_full_dimension counts:
is_full_dimension
True    42
Name: count, dtype: int64
status counts:
status
NaN    42
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
37,2,6,"[1, 1, 4]",4,4,5
41,3,6,"[1, 1, 1, 4]",4,4,6

====================================================================================================
..\data\raw\1_4_r7_architectures.csv
rows: 49
is_full_dimension counts:
is_full_dimension
True    49
Name: count, dtype: int64
status counts:
status
NaN    49
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
34,2,7,"[1, 1, 4]",4,4,5
48,3,7,"[1, 1, 1, 4]",4,4,6

====================================================================================================
..\data\raw\1_4_r8_architectures.csv
rows: 54
is_full_dimension counts:
is_full_dimension
True    54
Name: count, dtype: int64
status counts:
status
NaN    54
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
39,2,8,"[1, 1, 4]",4,4,5
53,3,8,"[1, 1, 1, 4]",4,4,6

====================================================================================================
..\data\raw\1_4_r9_architectures.csv
rows: 79
is_full_dimension counts:
is_full_dimension
True    79
Name: count, dtype: int64
status counts:
status
NaN    79
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
61,2,9,"[1, 1, 4]",4,4,5
78,3,9,"[1, 1, 1, 4]",4,4,6

====================================================================================================
..\data\raw\1_5_r1_architectures.csv
rows: 74
is_full_dimension counts:
is_full_dimension
True    74
Name: count, dtype: int64
status counts:
status
NaN    74
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
56,2,1,"[1, 1, 5]",5,5,6
70,3,1,"[1, 1, 1, 5]",5,5,7
71,4,1,"[1, 1, 1, 1, 5]",5,5,8
72,5,1,"[1, 1, 1, 1, 1, 5]",5,5,9
73,6,1,"[1, 1, 1, 1, 1, 1, 5]",5,5,10

====================================================================================================
..\data\raw\1_5_r2_architectures.csv
rows: 66
is_full_dimension counts:
is_full_dimension
True    66
Name: count, dtype: int64
status counts:
status
NaN    66
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
52,2,2,"[1, 1, 5]",5,5,6
59,3,2,"[1, 1, 1, 5]",5,5,7
60,4,2,"[1, 1, 1, 1, 5]",5,5,8
61,5,2,"[1, 1, 1, 1, 1, 5]",5,5,9
62,6,2,"[1, 1, 1, 1, 1, 1, 5]",5,5,10
63,7,2,"[1, 1, 1, 1, 1, 1, 1, 5]",5,5,11
64,8,2,"[1, 1, 1, 1, 1, 1, 1, 1, 5]",5,5,12
65,9,2,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 5]",5,5,13

====================================================================================================
..\data\raw\1_5_r3_architectures.csv
rows: 86
is_full_dimension counts:
is_full_dimension
True    86
Name: count, dtype: int64
status counts:
status
NaN    86
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
62,2,3,"[1, 1, 5]",5,5,6
82,3,3,"[1, 1, 1, 5]",5,5,7
83,4,3,"[1, 1, 1, 1, 5]",5,5,8
84,5,3,"[1, 1, 1, 1, 1, 5]",5,5,9
85,6,3,"[1, 1, 1, 1, 1, 1, 5]",5,5,10

====================================================================================================
..\data\raw\1_5_r4_architectures.csv
rows: 46
is_full_dimension counts:
is_full_dimension
True    46
Name: count, dtype: int64
status counts:
status
NaN    46
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
28,2,4,"[1, 1, 5]",5,5,6
42,3,4,"[1, 1, 1, 5]",5,5,7
43,4,4,"[1, 1, 1, 1, 5]",5,5,8
44,5,4,"[1, 1, 1, 1, 1, 5]",5,5,9
45,6,4,"[1, 1, 1, 1, 1, 1, 5]",5,5,10

====================================================================================================
..\data\raw\1_5_r5_architectures.csv
rows: 52
is_full_dimension counts:
is_full_dimension
True    52
Name: count, dtype: int64
status counts:
status
NaN    52
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
40,2,5,"[1, 1, 5]",5,5,6
48,3,5,"[1, 1, 1, 5]",5,5,7
49,4,5,"[1, 1, 1, 1, 5]",5,5,8
50,5,5,"[1, 1, 1, 1, 1, 5]",5,5,9
51,6,5,"[1, 1, 1, 1, 1, 1, 5]",5,5,10

====================================================================================================
..\data\raw\1_5_r6_architectures.csv
rows: 54
is_full_dimension counts:
is_full_dimension
True    54
Name: count, dtype: int64
status counts:
status
NaN    54
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
43,2,6,"[1, 1, 5]",5,5,6
53,3,6,"[1, 1, 1, 5]",5,5,7

====================================================================================================
..\data\raw\1_5_r7_architectures.csv
rows: 55
is_full_dimension counts:
is_full_dimension
True    55
Name: count, dtype: int64
status counts:
status
NaN    55
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
42,2,7,"[1, 1, 5]",5,5,6
54,3,7,"[1, 1, 1, 5]",5,5,7

====================================================================================================
..\data\raw\1_5_r8_architectures.csv
rows: 46
is_full_dimension counts:
is_full_dimension
True    46
Name: count, dtype: int64
status counts:
status
NaN    46
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
35,2,8,"[1, 1, 5]",5,5,6
45,3,8,"[1, 1, 1, 5]",5,5,7

====================================================================================================
..\data\raw\1_5_r9_architectures.csv
rows: 74
is_full_dimension counts:
is_full_dimension
True    74
Name: count, dtype: int64
status counts:
status
NaN    74
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
56,2,9,"[1, 1, 5]",5,5,6
73,3,9,"[1, 1, 1, 5]",5,5,7

====================================================================================================
..\data\raw\1_6_r1_architectures.csv
rows: 43
is_full_dimension counts:
is_full_dimension
True    43
Name: count, dtype: int64
status counts:
status
NaN    43
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
31,2,1,"[1, 1, 6]",6,6,7
42,3,1,"[1, 1, 1, 6]",6,6,8

====================================================================================================
..\data\raw\1_6_r2_architectures.csv
rows: 50
is_full_dimension counts:
is_full_dimension
True    50
Name: count, dtype: int64
status counts:
status
NaN    50
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
41,2,2,"[1, 1, 6]",6,6,7
49,3,2,"[1, 1, 1, 6]",6,6,8

====================================================================================================
..\data\raw\1_6_r3_architectures.csv
rows: 64
is_full_dimension counts:
is_full_dimension
True    64
Name: count, dtype: int64
status counts:
status
NaN    64
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
48,2,3,"[1, 1, 6]",6,6,7
63,3,3,"[1, 1, 1, 6]",6,6,8

====================================================================================================
..\data\raw\1_6_r4_architectures.csv
rows: 64
is_full_dimension counts:
is_full_dimension
True    64
Name: count, dtype: int64
status counts:
status
NaN    64
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
49,2,4,"[1, 1, 6]",6,6,7
63,3,4,"[1, 1, 1, 6]",6,6,8

====================================================================================================
..\data\raw\1_6_r5_architectures.csv
rows: 65
is_full_dimension counts:
is_full_dimension
True    65
Name: count, dtype: int64
status counts:
status
NaN    65
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
49,2,5,"[1, 1, 6]",6,6,7
64,3,5,"[1, 1, 1, 6]",6,6,8

====================================================================================================
..\data\raw\1_6_r6_architectures.csv
rows: 39
is_full_dimension counts:
is_full_dimension
True    39
Name: count, dtype: int64
status counts:
status
NaN                           38
filling_below_recorded_mfa     1
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
27,2.0,6.0,"[1, 1, 6]",6.0,6.0,7.0
38,3.0,6.0,"[1, 1, 1, 6]",6.0,6.0,8.0

====================================================================================================
..\data\raw\1_6_r7_architectures.csv
rows: 57
is_full_dimension counts:
is_full_dimension
True    57
Name: count, dtype: int64
status counts:
status
NaN    57
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
45,2,7,"[1, 1, 6]",6,6,7
56,3,7,"[1, 1, 1, 6]",6,6,8

====================================================================================================
..\data\raw\1_6_r8_architectures.csv
rows: 60
is_full_dimension counts:
is_full_dimension
True    60
Name: count, dtype: int64
status counts:
status
NaN    60
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
54,2,8,"[1, 1, 6]",6,6,7
59,3,8,"[1, 1, 1, 6]",6,6,8

====================================================================================================
..\data\raw\1_6_r9_architectures.csv
rows: 71
is_full_dimension counts:
is_full_dimension
True    71
Name: count, dtype: int64
status counts:
status
NaN    71
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
54,2,9,"[1, 1, 6]",6,6,7
70,3,9,"[1, 1, 1, 6]",6,6,8

====================================================================================================
..\data\raw\1_7_r1_architectures.csv
rows: 78
is_full_dimension counts:
is_full_dimension
True    78
Name: count, dtype: int64
status counts:
status
NaN    78
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
58,2,1,"[1, 1, 7]",7,7,8
77,3,1,"[1, 1, 1, 7]",7,7,9

====================================================================================================
..\data\raw\1_7_r2_architectures.csv
rows: 61
is_full_dimension counts:
is_full_dimension
True    61
Name: count, dtype: int64
status counts:
status
NaN    61
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
52,2,2,"[1, 1, 7]",7,7,8
60,3,2,"[1, 1, 1, 7]",7,7,9

====================================================================================================
..\data\raw\1_7_r3_architectures.csv
rows: 55
is_full_dimension counts:
is_full_dimension
True    55
Name: count, dtype: int64
status counts:
status
NaN    55
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
40,2,3,"[1, 1, 7]",7,7,8
54,3,3,"[1, 1, 1, 7]",7,7,9

====================================================================================================
..\data\raw\1_7_r4_architectures.csv
rows: 62
is_full_dimension counts:
is_full_dimension
True    62
Name: count, dtype: int64
status counts:
status
NaN    62
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
57,2,4,"[1, 1, 7]",7,7,8
61,3,4,"[1, 1, 1, 7]",7,7,9

====================================================================================================
..\data\raw\1_7_r5_architectures.csv
rows: 67
is_full_dimension counts:
is_full_dimension
True    67
Name: count, dtype: int64
status counts:
status
NaN    67
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
55,2,5,"[1, 1, 7]",7,7,8
66,3,5,"[1, 1, 1, 7]",7,7,9

====================================================================================================
..\data\raw\1_7_r6_architectures.csv
rows: 57
is_full_dimension counts:
is_full_dimension
True    57
Name: count, dtype: int64
status counts:
status
NaN    57
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
46,2,6,"[1, 1, 7]",7,7,8
56,3,6,"[1, 1, 1, 7]",7,7,9

====================================================================================================
..\data\raw\1_7_r7_architectures.csv
rows: 52
is_full_dimension counts:
is_full_dimension
True    52
Name: count, dtype: int64
status counts:
status
NaN    52
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
38,2,7,"[1, 1, 7]",7,7,8
51,3,7,"[1, 1, 1, 7]",7,7,9

====================================================================================================
..\data\raw\1_7_r8_architectures.csv
rows: 62
is_full_dimension counts:
is_full_dimension
True    62
Name: count, dtype: int64
status counts:
status
NaN    62
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
52,2,8,"[1, 1, 7]",7,7,8
61,3,8,"[1, 1, 1, 7]",7,7,9

====================================================================================================
..\data\raw\1_7_r9_architectures.csv
rows: 71
is_full_dimension counts:
is_full_dimension
True    71
Name: count, dtype: int64
status counts:
status
NaN    71
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
56,2,9,"[1, 1, 7]",7,7,8
70,3,9,"[1, 1, 1, 7]",7,7,9

====================================================================================================
..\data\raw\1_8_r1_architectures.csv
rows: 54
is_full_dimension counts:
is_full_dimension
True    54
Name: count, dtype: int64
status counts:
status
NaN    54
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
43,2,1,"[1, 1, 8]",8,8,9
53,3,1,"[1, 1, 1, 8]",8,8,10

====================================================================================================
..\data\raw\1_8_r2_architectures.csv
rows: 46
is_full_dimension counts:
is_full_dimension
True    46
Name: count, dtype: int64
status counts:
status
NaN    46
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
39,2,2,"[1, 1, 8]",8,8,9
45,3,2,"[1, 1, 1, 8]",8,8,10

====================================================================================================
..\data\raw\1_8_r3_architectures.csv
rows: 59
is_full_dimension counts:
is_full_dimension
True    59
Name: count, dtype: int64
status counts:
status
NaN    59
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
49,2,3,"[1, 1, 8]",8,8,9
58,3,3,"[1, 1, 1, 8]",8,8,10

====================================================================================================
..\data\raw\1_8_r4_architectures.csv
rows: 65
is_full_dimension counts:
is_full_dimension
True    65
Name: count, dtype: int64
status counts:
status
NaN    65
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
54,2,4,"[1, 1, 8]",8,8,9
64,3,4,"[1, 1, 1, 8]",8,8,10

====================================================================================================
..\data\raw\1_8_r5_architectures.csv
rows: 49
is_full_dimension counts:
is_full_dimension
True    49
Name: count, dtype: int64
status counts:
status
NaN    49
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
35,2,5,"[1, 1, 8]",8,8,9
48,3,5,"[1, 1, 1, 8]",8,8,10

====================================================================================================
..\data\raw\1_8_r6_architectures.csv
rows: 37
is_full_dimension counts:
is_full_dimension
True    37
Name: count, dtype: int64
status counts:
status
NaN    37
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
23,2,6,"[1, 1, 8]",8,8,9
36,3,6,"[1, 1, 1, 8]",8,8,10

====================================================================================================
..\data\raw\1_8_r7_architectures.csv
rows: 59
is_full_dimension counts:
is_full_dimension
True    59
Name: count, dtype: int64
status counts:
status
NaN    59
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
44,2,7,"[1, 1, 8]",8,8,9
58,3,7,"[1, 1, 1, 8]",8,8,10

====================================================================================================
..\data\raw\1_8_r8_architectures.csv
rows: 59
is_full_dimension counts:
is_full_dimension
True    59
Name: count, dtype: int64
status counts:
status
NaN    59
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
51,2,8,"[1, 1, 8]",8,8,9
58,3,8,"[1, 1, 1, 8]",8,8,10

====================================================================================================
..\data\raw\1_8_r9_architectures.csv
rows: 55
is_full_dimension counts:
is_full_dimension
True    55
Name: count, dtype: int64
status counts:
status
NaN    55
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
40,2,9,"[1, 1, 8]",8,8,9
54,3,9,"[1, 1, 1, 8]",8,8,10

====================================================================================================
..\data\raw\1_9_r1_architectures.csv
rows: 46
is_full_dimension counts:
is_full_dimension
True    46
Name: count, dtype: int64
status counts:
status
NaN    46
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
36,2,1,"[1, 1, 9]",9,9,10
45,3,1,"[1, 1, 1, 9]",9,9,11

====================================================================================================
..\data\raw\1_9_r2_architectures.csv
rows: 62
is_full_dimension counts:
is_full_dimension
True    62
Name: count, dtype: int64
status counts:
status
NaN    62
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
50,2,2,"[1, 1, 9]",9,9,10
61,3,2,"[1, 1, 1, 9]",9,9,11

====================================================================================================
..\data\raw\1_9_r3_architectures.csv
rows: 53
is_full_dimension counts:
is_full_dimension
True    53
Name: count, dtype: int64
status counts:
status
NaN    53
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
44,2,3,"[1, 1, 9]",9,9,10
52,3,3,"[1, 1, 1, 9]",9,9,11

====================================================================================================
..\data\raw\1_9_r4_architectures.csv
rows: 47
is_full_dimension counts:
is_full_dimension
True    47
Name: count, dtype: int64
status counts:
status
NaN    47
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
33,2,4,"[1, 1, 9]",9,9,10
46,3,4,"[1, 1, 1, 9]",9,9,11

====================================================================================================
..\data\raw\1_9_r5_architectures.csv
rows: 69
is_full_dimension counts:
is_full_dimension
True    69
Name: count, dtype: int64
status counts:
status
NaN    69
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
56,2,5,"[1, 1, 9]",9,9,10
68,3,5,"[1, 1, 1, 9]",9,9,11

====================================================================================================
..\data\raw\1_9_r6_architectures.csv
rows: 48
is_full_dimension counts:
is_full_dimension
True    48
Name: count, dtype: int64
status counts:
status
NaN    48
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
33,2,6,"[1, 1, 9]",9,9,10
47,3,6,"[1, 1, 1, 9]",9,9,11

====================================================================================================
..\data\raw\1_9_r7_architectures.csv
rows: 76
is_full_dimension counts:
is_full_dimension
True    76
Name: count, dtype: int64
status counts:
status
NaN    76
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
68,2,7,"[1, 1, 9]",9,9,10
75,3,7,"[1, 1, 1, 9]",9,9,11

====================================================================================================
..\data\raw\1_9_r8_architectures.csv
rows: 89
is_full_dimension counts:
is_full_dimension
True    89
Name: count, dtype: int64
status counts:
status
NaN    89
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
76,2,8,"[1, 1, 9]",9,9,10
88,3,8,"[1, 1, 1, 9]",9,9,11

====================================================================================================
..\data\raw\1_9_r9_architectures.csv
rows: 41
is_full_dimension counts:
is_full_dimension
True    41
Name: count, dtype: int64
status counts:
status
NaN    41
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
26,2,9,"[1, 1, 9]",9,9,10
40,3,9,"[1, 1, 1, 9]",9,9,11

====================================================================================================
..\data\raw\2_1_r12_architectures.csv
rows: 257
is_full_dimension counts:
is_full_dimension
False    237
True      20
Name: count, dtype: int64
status counts:
status
nonfilling    218
NaN            39
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
8,3.0,12.0,"[2, 10, 14, 1]",145.0,145.0,174.0
20,3.0,12.0,"[2, 6, 24, 1]",145.0,145.0,180.0
31,3.0,12.0,"[2, 11, 13, 1]",145.0,145.0,178.0
33,3.0,12.0,"[2, 8, 18, 1]",145.0,145.0,178.0
34,3.0,12.0,"[2, 12, 12, 1]",145.0,145.0,180.0
36,3.0,12.0,"[2, 9, 16, 1]",145.0,145.0,178.0
38,3.0,12.0,"[2, 7, 20, 1]",145.0,145.0,174.0

====================================================================================================
..\data\raw\2_1_r1_architectures.csv
rows: 55
is_full_dimension counts:
is_full_dimension
True    55
Name: count, dtype: int64
status counts:
status
NaN    55
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
45,2,1,"[2, 1, 1]",2,2,3
51,3,1,"[2, 1, 1, 1]",2,2,4
52,4,1,"[2, 1, 1, 1, 1]",2,2,5
53,5,1,"[2, 1, 1, 1, 1, 1]",2,2,6
54,6,1,"[2, 1, 1, 1, 1, 1, 1]",2,2,7

====================================================================================================
..\data\raw\2_1_r2_architectures.csv
rows: 24107
is_full_dimension counts:
is_full_dimension
False    22715
True      1392
Name: count, dtype: int64
status counts:
status
nonfilling    14052
NaN           10055
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2.0,2.0,"[2, 2, 1]",3.0,3.0,6.0
9,3.0,2.0,"[2, 2, 2, 1]",5.0,5.0,10.0
53,4.0,2.0,"[2, 3, 3, 2, 1]",9.0,9.0,23.0
275,5.0,2.0,"[2, 3, 3, 3, 2, 1]",17.0,17.0,32.0
1169,6.0,2.0,"[2, 3, 3, 4, 4, 2, 1]",33.0,33.0,53.0
...,...,...,...,...,...,...
5209,8.0,2.0,"[2, 3, 4, 5, 5, 5, 9, 6, 1]",129.0,129.0,193.0
5354,8.0,2.0,"[2, 3, 3, 6, 6, 6, 7, 7, 1]",129.0,129.0,203.0
5355,8.0,2.0,"[2, 3, 4, 6, 6, 5, 7, 7, 1]",129.0,129.0,199.0
5641,8.0,2.0,"[2, 3, 3, 6, 6, 5, 8, 8, 1]",129.0,129.0,211.0
5646,8.0,2.0,"[2, 3, 4, 4, 7, 5, 8, 8, 1]",129.0,129.0,209.0

====================================================================================================
..\data\raw\2_1_r3_architectures.csv
rows: 2377
is_full_dimension counts:
is_full_dimension
False    2138
True      239
Name: count, dtype: int64
status counts:
status
NaN           1277
nonfilling    1100
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
0,3.0,3.0,"[2, 3, 3, 1]",10.0,10.0,18.0
1,2.0,3.0,"[2, 2, 1]",4.0,4.0,6.0
2,4.0,3.0,"[2, 3, 5, 3, 1]",28.0,28.0,39.0
3,4.0,3.0,"[2, 4, 4, 4, 1]",28.0,28.0,44.0
4,4.0,3.0,"[2, 3, 4, 5, 1]",28.0,28.0,43.0
...,...,...,...,...,...,...
2260,6.0,3.0,"[2, 4, 5, 18, 8, 4, 1]",244.0,244.0,298.0
2308,6.0,3.0,"[2, 4, 10, 13, 8, 4, 1]",244.0,244.0,318.0
2315,6.0,3.0,"[2, 4, 6, 16, 8, 4, 1]",244.0,244.0,292.0
2324,6.0,3.0,"[2, 4, 9, 13, 9, 3, 1]",244.0,244.0,308.0
2358,6.0,3.0,"[2, 4, 8, 14, 8, 4, 1]",244.0,244.0,300.0

====================================================================================================
..\data\raw\2_1_r4_architectures.csv
rows: 4200
is_full_dimension counts:
is_full_dimension
False    3015
True     1185
Name: count, dtype: int64
status counts:
status
NaN                           3831
nonfilling                     368
filling_below_recorded_mfa       1
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2.0,4.0,"[2, 3, 1]",5.0,5.0,9.0
24,3.0,4.0,"[2, 3, 5, 1]",17.0,17.0,26.0
25,3.0,4.0,"[2, 4, 4, 1]",17.0,17.0,28.0
37,4.0,4.0,"[2, 3, 8, 6, 1]",65.0,65.0,84.0
82,4.0,4.0,"[2, 4, 9, 4, 1]",65.0,65.0,84.0
...,...,...,...,...,...,...
4173,6.0,4.0,"[2, 11, 29, 39, 17, 4, 1]",1025.0,1025.0,2207.0
4178,6.0,4.0,"[2, 16, 98, 43, 16, 4, 1]",1025.0,1025.0,6570.0
4183,6.0,4.0,"[2, 5, 190, 38, 16, 4, 1]",1025.0,1025.0,8856.0
4189,6.0,4.0,"[2, 4, 34, 48, 17, 5, 1]",1025.0,1025.0,2682.0
4195,6.0,4.0,"[2, 13, 160, 40, 15, 5, 1]",1025.0,1025.0,9186.0

====================================================================================================
..\data\raw\2_1_r5_architectures.csv
rows: 9590
is_full_dimension counts:
is_full_dimension
False    8926
True      664
Name: count, dtype: int64
status counts:
status
nonfilling                    7927
NaN                           1662
filling_below_recorded_mfa       1
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2.0,5.0,"[2, 3, 1]",6.0,6.0,9.0
20,3.0,5.0,"[2, 4, 6, 1]",26.0,26.0,38.0
24,3.0,5.0,"[2, 5, 5, 1]",26.0,26.0,40.0
130,4.0,5.0,"[2, 4, 12, 8, 1]",126.0,126.0,160.0
131,4.0,5.0,"[2, 4, 6, 18, 1]",126.0,126.0,158.0
...,...,...,...,...,...,...
9578,5.0,5.0,"[2, 5, 19, 24, 5, 1]",626.0,626.0,686.0
9579,5.0,5.0,"[2, 5, 21, 22, 5, 1]",626.0,626.0,692.0
9580,5.0,5.0,"[2, 6, 16, 26, 6, 1]",626.0,626.0,686.0
9584,5.0,5.0,"[2, 6, 21, 21, 5, 1]",626.0,626.0,689.0
9586,5.0,5.0,"[2, 5, 20, 22, 6, 1]",626.0,626.0,688.0

====================================================================================================
..\data\raw\2_1_r6_architectures.csv
rows: 872
is_full_dimension counts:
is_full_dimension
False    621
True     251
Name: count, dtype: int64
status counts:
status
NaN    872
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
51,4,6,"[2, 4, 12, 15, 1]",217,217,251
79,4,6,"[2, 5, 11, 16, 1]",217,217,257
125,4,6,"[2, 5, 12, 14, 1]",217,217,252
127,4,6,"[2, 5, 8, 23, 1]",217,217,257
134,4,6,"[2, 5, 15, 11, 1]",217,217,261
...,...,...,...,...,...,...
830,5,6,"[2, 11, 8, 49, 21, 1]",1297,1297,1552
831,5,6,"[2, 43, 15, 37, 32, 1]",1297,1297,2502
834,5,6,"[2, 15, 42, 26, 39, 1]",1297,1297,2805
840,5,6,"[2, 48, 20, 46, 12, 1]",1297,1297,2540
841,5,6,"[2, 37, 12, 28, 43, 1]",1297,1297,2101

====================================================================================================
..\data\raw\2_1_r7_architectures.csv
rows: 1071
is_full_dimension counts:
is_full_dimension
False    723
True     348
Name: count, dtype: int64
status counts:
status
NaN    1071
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
81,4,7,"[2, 6, 14, 20, 1]",344,344,396
117,4,7,"[2, 5, 12, 25, 1]",344,344,395
141,4,7,"[2, 6, 26, 8, 1]",344,344,384
142,4,7,"[2, 6, 19, 13, 1]",344,344,386
149,4,7,"[2, 7, 26, 7, 1]",344,344,385
...,...,...,...,...,...,...
989,2,7,"[2, 4, 1]",8,8,12
1062,3,7,"[2, 6, 8, 1]",50,50,68
1068,3,7,"[2, 4, 12, 1]",50,50,68
1069,3,7,"[2, 7, 7, 1]",50,50,70
1070,3,7,"[2, 5, 9, 1]",50,50,64

====================================================================================================
..\data\raw\2_1_r8_architectures.csv
rows: 85
is_full_dimension counts:
is_full_dimension
False    56
True     29
Name: count, dtype: int64
status counts:
status
NaN    85
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
26,3,8,"[2, 6, 10, 1]",65,65,82
35,3,8,"[2, 5, 12, 1]",65,65,82
37,3,8,"[2, 4, 16, 1]",65,65,88
38,3,8,"[2, 8, 8, 1]",65,65,88
39,3,8,"[2, 7, 9, 1]",65,65,86
50,2,8,"[2, 5, 1]",9,9,15

====================================================================================================
..\data\raw\2_1_r9_architectures.csv
rows: 104
is_full_dimension counts:
is_full_dimension
True     66
False    38
Name: count, dtype: int64
status counts:
status
NaN    104
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,9,"[2, 5, 1]",10,10,15
73,3,9,"[2, 7, 11, 1]",82,82,102
83,3,9,"[2, 8, 10, 1]",82,82,106
89,3,9,"[2, 6, 13, 1]",82,82,103
95,3,9,"[2, 5, 16, 1]",82,82,106
97,3,9,"[2, 9, 9, 1]",82,82,108
100,3,9,"[2, 4, 20, 1]",82,82,108

====================================================================================================
..\data\raw\2_2_r1_architectures.csv
rows: 60
is_full_dimension counts:
is_full_dimension
True     48
False    12
Name: count, dtype: int64
status counts:
status
NaN    60
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
7,2,1,"[2, 2, 2]",4,4,8
47,3,1,"[2, 2, 2, 2]",4,4,12

====================================================================================================
..\data\raw\2_2_r2_architectures.csv
rows: 20958
is_full_dimension counts:
is_full_dimension
False    19091
True      1867
Name: count, dtype: int64
status counts:
status
nonfilling    13430
NaN            7528
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2.0,2.0,"[2, 2, 2]",6.0,6.0,8.0
13,3.0,2.0,"[2, 3, 3, 2]",10.0,10.0,21.0
59,4.0,2.0,"[2, 3, 3, 3, 2]",18.0,18.0,30.0
225,5.0,2.0,"[2, 3, 3, 4, 4, 2]",34.0,34.0,51.0
1086,6.0,2.0,"[2, 3, 3, 4, 6, 5, 2]",66.0,66.0,91.0
1088,6.0,2.0,"[2, 3, 3, 5, 7, 4, 2]",66.0,66.0,101.0
1100,6.0,2.0,"[2, 3, 4, 5, 5, 5, 2]",66.0,66.0,98.0
1104,6.0,2.0,"[2, 3, 4, 5, 6, 4, 2]",66.0,66.0,100.0
3707,7.0,2.0,"[2, 3, 3, 5, 7, 8, 5, 2]",130.0,130.0,171.0
4067,7.0,2.0,"[2, 3, 3, 4, 6, 8, 7, 2]",130.0,130.0,169.0
4289,7.0,2.0,"[2, 3, 4, 6, 6, 7, 6, 2]",130.0,130.0,174.0
4291,7.0,2.0,"[2, 3, 4, 5, 7, 8, 4, 2]",130.0,130.0,169.0
4494,7.0,2.0,"[2, 3, 4, 5, 9, 6, 5, 2]",130.0,130.0,177.0
4536,7.0,2.0,"[2, 3, 3, 6, 6, 8, 6, 2]",130.0,130.0,177.0
4574,7.0,2.0,"[2, 3, 4, 4, 7, 9, 4, 2]",130.0,130.0,169.0
4626,7.0,2.0,"[2, 3, 3, 4, 5, 8, 8, 2]",130.0,130.0,167.0
4660,7.0,2.0,"[2, 3, 5, 5, 7, 7, 5, 2]",130.0,130.0,175.0
4735,7.0,2.0,"[2, 3, 3, 4, 6, 9, 6, 2]",130.0,130.0,171.0
4741,7.0,2.0,"[2, 3, 4, 7, 7, 7, 4, 2]",130.0,130.0,180.0
4743,7.0,2.0,"[2, 3, 3, 5, 6, 9, 5, 2]",130.0,130.0,169.0
4758,7.0,2.0,"[2, 3, 3, 4, 6, 10, 5, 2]",130.0,130.0,171.0
4761,7.0,2.0,"[2, 3, 4, 5, 8, 7, 4, 2]",130.0,130.0,170.0
4762,7.0,2.0,"[2, 3, 4, 5, 6, 7, 7, 2]",130.0,130.0,173.0
4767,7.0,2.0,"[2, 3, 4, 5, 7, 7, 6, 2]",130.0,130.0,176.0
4772,7.0,2.0,"[2, 3, 4, 6, 8, 6, 5, 2]",130.0,130.0,178.0
4785,7.0,2.0,"[2, 3, 3, 4, 5, 9, 7, 2]",130.0,130.0,169.0
4790,7.0,2.0,"[2, 3, 3, 4, 7, 9, 5, 2]",130.0,130.0,173.0
4798,7.0,2.0,"[2, 3, 3, 5, 8, 8, 4, 2]",130.0,130.0,174.0
4801,7.0,2.0,"[2, 3, 3, 4, 8, 8, 5, 2]",130.0,130.0,173.0
4803,7.0,2.0,"[2, 3, 4, 6, 7, 6, 6, 2]",130.0,130.0,174.0
4805,7.0,2.0,"[2, 3, 4, 4, 7, 8, 5, 2]",130.0,130.0,168.0
4810,7.0,2.0,"[2, 3, 3, 4, 7, 7, 7, 2]",130.0,130.0,167.0
4815,7.0,2.0,"[2, 3, 3, 4, 8, 9, 4, 2]",130.0,130.0,175.0
4817,7.0,2.0,"[2, 3, 3, 5, 8, 7, 5, 2]",130.0,130.0,171.0
4818,7.0,2.0,"[2, 3, 4, 5, 5, 9, 6, 2]",130.0,130.0,174.0
4821,7.0,2.0,"[2, 3, 3, 5, 7, 9, 4, 2]",130.0,130.0,172.0
4829,7.0,2.0,"[2, 3, 4, 6, 6, 9, 4, 2]",130.0,130.0,176.0
4834,7.0,2.0,"[2, 3, 4, 5, 6, 10, 4, 2]",130.0,130.0,176.0
4836,7.0,2.0,"[2, 3, 4, 5, 8, 6, 6, 2]",130.0,130.0,174.0
4841,7.0,2.0,"[2, 3, 4, 5, 6, 8, 6, 2]",130.0,130.0,176.0
4844,7.0,2.0,"[2, 3, 3, 6, 7, 7, 6, 2]",130.0,130.0,178.0
4849,7.0,2.0,"[2, 3, 3, 4, 7, 10, 4, 2]",130.0,130.0,173.0
4852,7.0,2.0,"[2, 3, 4, 6, 7, 7, 5, 2]",130.0,130.0,178.0
4855,7.0,2.0,"[2, 3, 4, 5, 5, 8, 7, 2]",130.0,130.0,173.0
4860,7.0,2.0,"[2, 3, 3, 4, 7, 8, 6, 2]",130.0,130.0,171.0
4865,7.0,2.0,"[2, 3, 4, 6, 6, 8, 5, 2]",130.0,130.0,176.0
5499,8.0,2.0,"[2, 3, 4, 6, 10, 10, 8, 4, 2]",258.0,258.0,322.0
5528,8.0,2.0,"[2, 3, 5, 5, 10, 10, 8, 4, 2]",258.0,258.0,316.0
5539,8.0,2.0,"[2, 3, 4, 8, 9, 10, 8, 4, 2]",258.0,258.0,332.0
5805,9.0,2.0,"[2, 3, 4, 5, 18, 12, 13, 12, 4, 2]",514.0,514.0,712.0
5811,9.0,2.0,"[2, 3, 4, 5, 18, 13, 12, 11, 4, 2]",514.0,514.0,702.0
5847,9.0,2.0,"[2, 3, 4, 5, 18, 13, 13, 10, 4, 2]",514.0,514.0,709.0
6160,9.0,2.0,"[2, 3, 6, 9, 10, 15, 11, 12, 4, 2]",514.0,514.0,671.0
6172,9.0,2.0,"[2, 4, 5, 7, 10, 15, 11, 12, 4, 2]",514.0,514.0,636.0
6236,9.0,2.0,"[2, 3, 4, 4, 10, 17, 11, 12, 4, 2]",514.0,514.0,619.0

====================================================================================================
..\data\raw\2_2_r3_architectures.csv
rows: 2323
is_full_dimension counts:
is_full_dimension
False    1329
True      994
Name: count, dtype: int64
status counts:
status
NaN    2323
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2,3,"[2, 3, 2]",8,8,12
23,3,3,"[2, 3, 5, 2]",20,20,31
25,3,3,"[2, 4, 4, 2]",20,20,32
128,4,3,"[2, 3, 5, 8, 2]",56,56,77
131,4,3,"[2, 4, 5, 7, 2]",56,56,77
...,...,...,...,...,...,...
2313,6,3,"[2, 10, 5, 9, 20, 18, 2]",488,488,691
2316,6,3,"[2, 13, 16, 12, 17, 13, 2]",488,488,877
2318,6,3,"[2, 13, 9, 11, 15, 18, 2]",488,488,713
2321,6,3,"[2, 20, 5, 9, 20, 15, 2]",488,488,695
2322,6,3,"[2, 6, 18, 17, 12, 16, 2]",488,488,854

====================================================================================================
..\data\raw\2_2_r4_architectures.csv
rows: 57
is_full_dimension counts:
is_full_dimension
True     38
False    19
Name: count, dtype: int64
status counts:
status
NaN    57
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,4,"[2, 4, 2]",10,10,16
50,3,4,"[2, 4, 6, 2]",34,34,44

====================================================================================================
..\data\raw\2_2_r5_architectures.csv
rows: 85
is_full_dimension counts:
is_full_dimension
True     46
False    39
Name: count, dtype: int64
status counts:
status
NaN    85
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
8,2,5,"[2, 4, 2]",12,12,16
72,3,5,"[2, 5, 8, 2]",52,52,66
82,3,5,"[2, 4, 10, 2]",52,52,68

====================================================================================================
..\data\raw\2_2_r6_architectures.csv
rows: 92
is_full_dimension counts:
is_full_dimension
True     50
False    42
Name: count, dtype: int64
status counts:
status
NaN    92
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2,6,"[2, 5, 2]",14,14,20
73,3,6,"[2, 5, 12, 2]",74,74,94
81,3,6,"[2, 6, 10, 2]",74,74,92
90,3,6,"[2, 4, 14, 2]",74,74,92

====================================================================================================
..\data\raw\2_2_r7_architectures.csv
rows: 93
is_full_dimension counts:
is_full_dimension
True     58
False    35
Name: count, dtype: int64
status counts:
status
NaN    93
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,7,"[2, 6, 2]",16,16,24
81,3,7,"[2, 4, 20, 2]",100,100,128
84,3,7,"[2, 6, 14, 2]",100,100,124
85,3,7,"[2, 5, 16, 2]",100,100,122
91,3,7,"[2, 7, 12, 2]",100,100,122

====================================================================================================
..\data\raw\2_2_r8_architectures.csv
rows: 103
is_full_dimension counts:
is_full_dimension
True     60
False    43
Name: count, dtype: int64
status counts:
status
NaN    103
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,8,"[2, 6, 2]",18,18,24
69,3,8,"[2, 7, 16, 2]",130,130,158
78,3,8,"[2, 4, 26, 2]",130,130,164
87,3,8,"[2, 8, 14, 2]",130,130,156
95,3,8,"[2, 5, 21, 2]",130,130,157
100,3,8,"[2, 6, 18, 2]",130,130,156
101,3,8,"[2, 9, 13, 2]",130,130,161

====================================================================================================
..\data\raw\2_2_r9_architectures.csv
rows: 125
is_full_dimension counts:
is_full_dimension
True     84
False    41
Name: count, dtype: int64
status counts:
status
NaN    125
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2,9,"[2, 7, 2]",20,20,28
107,3,9,"[2, 4, 32, 2]",164,164,200
110,3,9,"[2, 8, 18, 2]",164,164,196
115,3,9,"[2, 10, 15, 2]",164,164,200
119,3,9,"[2, 7, 20, 2]",164,164,194
120,3,9,"[2, 5, 27, 2]",164,164,199
121,3,9,"[2, 9, 16, 2]",164,164,194
124,3,9,"[2, 6, 23, 2]",164,164,196

====================================================================================================
..\data\raw\2_3_r1_architectures.csv
rows: 50
is_full_dimension counts:
is_full_dimension
True     36
False    14
Name: count, dtype: int64
status counts:
status
NaN           46
nonfilling     4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2.0,1.0,"[2, 2, 3]",6.0,6.0,10.0
45,3.0,1.0,"[2, 2, 2, 3]",6.0,6.0,14.0

====================================================================================================
..\data\raw\2_3_r2_architectures.csv
rows: 1426
is_full_dimension counts:
is_full_dimension
False    1067
True      359
Name: count, dtype: int64
status counts:
status
NaN           1071
nonfilling     355
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2.0,2.0,"[2, 3, 3]",9.0,9.0,15.0
31,3.0,2.0,"[2, 3, 3, 3]",15.0,15.0,24.0
215,4.0,2.0,"[2, 3, 4, 4, 3]",27.0,27.0,46.0
1035,5.0,2.0,"[2, 3, 4, 5, 5, 3]",51.0,51.0,78.0

====================================================================================================
..\data\raw\2_3_r3_architectures.csv
rows: 93
is_full_dimension counts:
is_full_dimension
False    50
True     43
Name: count, dtype: int64
status counts:
status
NaN           71
nonfilling    22
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
8,2.0,3.0,"[2, 3, 3]",12.0,12.0,15.0
63,3.0,3.0,"[2, 4, 5, 3]",30.0,30.0,43.0
68,3.0,3.0,"[2, 3, 6, 3]",30.0,30.0,42.0

====================================================================================================
..\data\raw\2_3_r4_architectures.csv
rows: 113
is_full_dimension counts:
is_full_dimension
False    58
True     55
Name: count, dtype: int64
status counts:
status
NaN           80
nonfilling    33
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2.0,4.0,"[2, 4, 3]",15.0,15.0,20.0
78,3.0,4.0,"[2, 4, 8, 3]",51.0,51.0,64.0

====================================================================================================
..\data\raw\2_3_r5_architectures.csv
rows: 191
is_full_dimension counts:
is_full_dimension
False    140
True      51
Name: count, dtype: int64
status counts:
status
NaN           120
nonfilling     71
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2.0,5.0,"[2, 5, 3]",18.0,18.0,25.0
75,3.0,5.0,"[2, 4, 13, 3]",78.0,78.0,99.0
88,3.0,5.0,"[2, 6, 10, 3]",78.0,78.0,102.0
89,3.0,5.0,"[2, 5, 11, 3]",78.0,78.0,98.0

====================================================================================================
..\data\raw\2_3_r6_architectures.csv
rows: 210
is_full_dimension counts:
is_full_dimension
False    149
True      61
Name: count, dtype: int64
status counts:
status
nonfilling    110
NaN           100
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2.0,6.0,"[2, 6, 3]",21.0,21.0,30.0
95,3.0,6.0,"[2, 4, 18, 3]",111.0,111.0,134.0
96,3.0,6.0,"[2, 7, 13, 3]",111.0,111.0,144.0
98,3.0,6.0,"[2, 5, 16, 3]",111.0,111.0,138.0
99,3.0,6.0,"[2, 6, 14, 3]",111.0,111.0,138.0

====================================================================================================
..\data\raw\2_3_r7_architectures.csv
rows: 258
is_full_dimension counts:
is_full_dimension
False    206
True      52
Name: count, dtype: int64
status counts:
status
nonfilling    162
NaN            96
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2.0,7.0,"[2, 6, 3]",24.0,24.0,30.0
70,3.0,7.0,"[2, 8, 15, 3]",150.0,150.0,181.0
91,3.0,7.0,"[2, 6, 18, 3]",150.0,150.0,174.0
92,3.0,7.0,"[2, 7, 16, 3]",150.0,150.0,174.0
94,3.0,7.0,"[2, 5, 21, 3]",150.0,150.0,178.0
95,3.0,7.0,"[2, 4, 25, 3]",150.0,150.0,183.0

====================================================================================================
..\data\raw\2_3_r8_architectures.csv
rows: 332
is_full_dimension counts:
is_full_dimension
False    268
True      64
Name: count, dtype: int64
status counts:
status
nonfilling    229
NaN           103
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2.0,8.0,"[2, 7, 3]",27.0,27.0,35.0
87,3.0,8.0,"[2, 4, 32, 3]",195.0,195.0,232.0
93,3.0,8.0,"[2, 6, 24, 3]",195.0,195.0,228.0
94,3.0,8.0,"[2, 5, 28, 3]",195.0,195.0,234.0
96,3.0,8.0,"[2, 8, 19, 3]",195.0,195.0,225.0
98,3.0,8.0,"[2, 9, 18, 3]",195.0,195.0,234.0
101,3.0,8.0,"[2, 7, 21, 3]",195.0,195.0,224.0

====================================================================================================
..\data\raw\2_3_r9_architectures.csv
rows: 425
is_full_dimension counts:
is_full_dimension
False    365
True      60
Name: count, dtype: int64
status counts:
status
nonfilling    309
NaN           116
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
9,2.0,9.0,"[2, 8, 3]",30.0,30.0,40.0
78,3.0,9.0,"[2, 7, 27, 3]",246.0,246.0,284.0
79,3.0,9.0,"[2, 10, 21, 3]",246.0,246.0,293.0
94,3.0,9.0,"[2, 8, 24, 3]",246.0,246.0,280.0
105,3.0,9.0,"[2, 5, 35, 3]",246.0,246.0,290.0
112,3.0,9.0,"[2, 4, 41, 3]",246.0,246.0,295.0
114,3.0,9.0,"[2, 6, 30, 3]",246.0,246.0,282.0
115,3.0,9.0,"[2, 9, 22, 3]",246.0,246.0,282.0

====================================================================================================
..\data\raw\2_4_r1_architectures.csv
rows: 69
is_full_dimension counts:
is_full_dimension
True     52
False    17
Name: count, dtype: int64
status counts:
status
NaN           65
nonfilling     4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2.0,1.0,"[2, 2, 4]",8.0,8.0,12.0
63,3.0,1.0,"[2, 2, 2, 4]",8.0,8.0,16.0

====================================================================================================
..\data\raw\2_4_r2_architectures.csv
rows: 74
is_full_dimension counts:
is_full_dimension
True     41
False    33
Name: count, dtype: int64
status counts:
status
NaN           62
nonfilling    12
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2.0,2.0,"[2, 3, 4]",12.0,12.0,18.0
56,3.0,2.0,"[2, 3, 4, 4]",20.0,20.0,34.0

====================================================================================================
..\data\raw\2_4_r3_architectures.csv
rows: 100
is_full_dimension counts:
is_full_dimension
False    57
True     43
Name: count, dtype: int64
status counts:
status
NaN           75
nonfilling    25
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
8,2.0,3.0,"[2, 4, 4]",16.0,16.0,24.0
71,3.0,3.0,"[2, 4, 6, 4]",40.0,40.0,56.0

====================================================================================================
..\data\raw\2_4_r4_architectures.csv
rows: 120
is_full_dimension counts:
is_full_dimension
False    72
True     48
Name: count, dtype: int64
status counts:
status
NaN           71
nonfilling    49
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2.0,4.0,"[2, 4, 4]",20.0,20.0,24.0
69,3.0,4.0,"[2, 4, 10, 4]",68.0,68.0,88.0
70,3.0,4.0,"[2, 5, 9, 4]",68.0,68.0,91.0

====================================================================================================
..\data\raw\2_4_r5_architectures.csv
rows: 165
is_full_dimension counts:
is_full_dimension
False    129
True      36
Name: count, dtype: int64
status counts:
status
nonfilling    83
NaN           82
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2.0,5.0,"[2, 5, 4]",24.0,24.0,30.0
62,3.0,5.0,"[2, 5, 13, 4]",104.0,104.0,127.0
78,3.0,5.0,"[2, 6, 12, 4]",104.0,104.0,132.0
80,3.0,5.0,"[2, 4, 15, 4]",104.0,104.0,128.0

====================================================================================================
..\data\raw\2_4_r6_architectures.csv
rows: 210
is_full_dimension counts:
is_full_dimension
False    168
True      42
Name: count, dtype: int64
status counts:
status
nonfilling    129
NaN            81
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2.0,6.0,"[2, 6, 4]",28.0,28.0,36.0
69,3.0,6.0,"[2, 4, 21, 4]",148.0,148.0,176.0
74,3.0,6.0,"[2, 6, 16, 4]",148.0,148.0,172.0
77,3.0,6.0,"[2, 5, 18, 4]",148.0,148.0,172.0
80,3.0,6.0,"[2, 7, 15, 4]",148.0,148.0,179.0

====================================================================================================
..\data\raw\2_4_r7_architectures.csv
rows: 273
is_full_dimension counts:
is_full_dimension
False    239
True      34
Name: count, dtype: int64
status counts:
status
nonfilling    193
NaN            80
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2.0,7.0,"[2, 7, 4]",32.0,32.0,42.0
72,3.0,7.0,"[2, 8, 19, 4]",200.0,200.0,244.0
73,3.0,7.0,"[2, 5, 25, 4]",200.0,200.0,235.0
74,3.0,7.0,"[2, 4, 28, 4]",200.0,200.0,232.0
75,3.0,7.0,"[2, 7, 20, 4]",200.0,200.0,234.0
77,3.0,7.0,"[2, 6, 22, 4]",200.0,200.0,232.0

====================================================================================================
..\data\raw\2_4_r8_architectures.csv
rows: 369
is_full_dimension counts:
is_full_dimension
False    320
True      49
Name: count, dtype: int64
status counts:
status
nonfilling    269
NaN           100
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2.0,8.0,"[2, 8, 4]",36.0,36.0,48.0
61,3.0,8.0,"[2, 6, 29, 4]",260.0,260.0,302.0
68,3.0,8.0,"[2, 4, 37, 4]",260.0,260.0,304.0
70,3.0,8.0,"[2, 7, 26, 4]",260.0,260.0,300.0
81,3.0,8.0,"[2, 5, 32, 4]",260.0,260.0,298.0
92,3.0,8.0,"[2, 8, 23, 4]",260.0,260.0,292.0
98,3.0,8.0,"[2, 9, 22, 4]",260.0,260.0,304.0

====================================================================================================
..\data\raw\2_4_r9_architectures.csv
rows: 468
is_full_dimension counts:
is_full_dimension
False    405
True      63
Name: count, dtype: int64
status counts:
status
nonfilling    367
NaN           101
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2.0,9.0,"[2, 8, 4]",40.0,40.0,48.0
59,3.0,9.0,"[2, 6, 36, 4]",328.0,328.0,372.0
69,3.0,9.0,"[2, 5, 41, 4]",328.0,328.0,379.0
77,3.0,9.0,"[2, 7, 33, 4]",328.0,328.0,377.0
90,3.0,9.0,"[2, 10, 26, 4]",328.0,328.0,384.0
92,3.0,9.0,"[2, 4, 47, 4]",328.0,328.0,384.0
94,3.0,9.0,"[2, 8, 30, 4]",328.0,328.0,376.0
98,3.0,9.0,"[2, 9, 27, 4]",328.0,328.0,369.0

====================================================================================================
..\data\raw\2_5_r1_architectures.csv
rows: 64
is_full_dimension counts:
is_full_dimension
True     47
False    17
Name: count, dtype: int64
status counts:
status
NaN           60
nonfilling     4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2.0,1.0,"[2, 2, 5]",10.0,10.0,14.0
56,3.0,1.0,"[2, 2, 2, 5]",10.0,10.0,18.0

====================================================================================================
..\data\raw\2_5_r2_architectures.csv
rows: 77
is_full_dimension counts:
is_full_dimension
True     42
False    35
Name: count, dtype: int64
status counts:
status
NaN           61
nonfilling    16
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2.0,2.0,"[2, 3, 5]",15.0,15.0,21.0
59,3.0,2.0,"[2, 3, 5, 5]",25.0,25.0,46.0

====================================================================================================
..\data\raw\2_5_r3_architectures.csv
rows: 90
is_full_dimension counts:
is_full_dimension
False    52
True     38
Name: count, dtype: int64
status counts:
status
NaN           61
nonfilling    29
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
8,2.0,3.0,"[2, 4, 5]",20.0,20.0,28.0
60,3.0,3.0,"[2, 4, 7, 5]",50.0,50.0,71.0

====================================================================================================
..\data\raw\2_5_r4_architectures.csv
rows: 109
is_full_dimension counts:
is_full_dimension
False    73
True     36
Name: count, dtype: int64
status counts:
status
NaN           55
nonfilling    54
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
9,2.0,4.0,"[2, 5, 5]",25.0,25.0,35.0
52,3.0,4.0,"[2, 4, 11, 5]",85.0,85.0,107.0
53,3.0,4.0,"[2, 5, 10, 5]",85.0,85.0,110.0

====================================================================================================
..\data\raw\2_5_r5_architectures.csv
rows: 183
is_full_dimension counts:
is_full_dimension
False    134
True      49
Name: count, dtype: int64
status counts:
status
NaN           94
nonfilling    89
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2.0,5.0,"[2, 5, 5]",30.0,30.0,35.0
80,3.0,5.0,"[2, 5, 14, 5]",130.0,130.0,150.0
83,3.0,5.0,"[2, 4, 16, 5]",130.0,130.0,152.0
91,3.0,5.0,"[2, 6, 13, 5]",130.0,130.0,155.0

====================================================================================================
..\data\raw\2_5_r6_architectures.csv
rows: 213
is_full_dimension counts:
is_full_dimension
False    170
True      43
Name: count, dtype: int64
status counts:
status
nonfilling    142
NaN            71
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
7,2.0,6.0,"[2, 6, 5]",35.0,35.0,42.0
58,3.0,6.0,"[2, 4, 23, 5]",185.0,185.0,215.0
65,3.0,6.0,"[2, 7, 17, 5]",185.0,185.0,218.0
67,3.0,6.0,"[2, 6, 18, 5]",185.0,185.0,210.0
68,3.0,6.0,"[2, 5, 20, 5]",185.0,185.0,210.0

====================================================================================================
..\data\raw\2_5_r7_architectures.csv
rows: 316
is_full_dimension counts:
is_full_dimension
False    252
True      64
Name: count, dtype: int64
status counts:
status
nonfilling    214
NaN           102
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
9,2.0,7.0,"[2, 7, 5]",40.0,40.0,49.0
74,3.0,7.0,"[2, 7, 23, 5]",250.0,250.0,290.0
82,3.0,7.0,"[2, 5, 28, 5]",250.0,250.0,290.0
95,3.0,7.0,"[2, 6, 25, 5]",250.0,250.0,287.0
100,3.0,7.0,"[2, 4, 31, 5]",250.0,250.0,287.0
101,3.0,7.0,"[2, 8, 21, 5]",250.0,250.0,289.0

====================================================================================================
..\data\raw\2_5_r8_architectures.csv
rows: 404
is_full_dimension counts:
is_full_dimension
False    361
True      43
Name: count, dtype: int64
status counts:
status
nonfilling    302
NaN           102
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
8,2.0,8.0,"[2, 8, 5]",45.0,45.0,56.0
54,3.0,8.0,"[2, 9, 25, 5]",325.0,325.0,368.0
71,3.0,8.0,"[2, 4, 41, 5]",325.0,325.0,377.0
87,3.0,8.0,"[2, 8, 27, 5]",325.0,325.0,367.0
91,3.0,8.0,"[2, 6, 32, 5]",325.0,325.0,364.0
98,3.0,8.0,"[2, 5, 36, 5]",325.0,325.0,370.0
101,3.0,8.0,"[2, 7, 29, 5]",325.0,325.0,362.0

====================================================================================================
..\data\raw\2_5_r9_architectures.csv
rows: 530
is_full_dimension counts:
is_full_dimension
False    460
True      70
Name: count, dtype: int64
status counts:
status
nonfilling    411
NaN           119
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2.0,9.0,"[2, 9, 5]",50.0,50.0,63.0
71,3.0,9.0,"[2, 6, 41, 5]",410.0,410.0,463.0
93,3.0,9.0,"[2, 8, 34, 5]",410.0,410.0,458.0
103,3.0,9.0,"[2, 10, 30, 5]",410.0,410.0,470.0
110,3.0,9.0,"[2, 9, 31, 5]",410.0,410.0,452.0
111,3.0,9.0,"[2, 7, 37, 5]",410.0,410.0,458.0
116,3.0,9.0,"[2, 5, 45, 5]",410.0,410.0,460.0
118,3.0,9.0,"[2, 4, 51, 5]",410.0,410.0,467.0

====================================================================================================
..\data\raw\2_6_r1_architectures.csv
rows: 53
is_full_dimension counts:
is_full_dimension
True     37
False    16
Name: count, dtype: int64
status counts:
status
NaN           49
nonfilling     4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2.0,1.0,"[2, 2, 6]",12.0,12.0,16.0
46,3.0,1.0,"[2, 2, 2, 6]",12.0,12.0,20.0

====================================================================================================
..\data\raw\2_6_r2_architectures.csv
rows: 74
is_full_dimension counts:
is_full_dimension
True     40
False    34
Name: count, dtype: int64
status counts:
status
NaN           58
nonfilling    16
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2.0,2.0,"[2, 3, 6]",18.0,18.0,24.0
55,3.0,2.0,"[2, 3, 5, 6]",30.0,30.0,51.0

====================================================================================================
..\data\raw\2_6_r3_architectures.csv
rows: 89
is_full_dimension counts:
is_full_dimension
False    60
True     29
Name: count, dtype: int64
status counts:
status
NaN           60
nonfilling    29
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
9,2.0,3.0,"[2, 4, 6]",24.0,24.0,32.0
57,3.0,3.0,"[2, 4, 7, 6]",60.0,60.0,78.0

====================================================================================================
..\data\raw\2_6_r4_architectures.csv
rows: 120
is_full_dimension counts:
is_full_dimension
False    79
True     41
Name: count, dtype: int64
status counts:
status
NaN           74
nonfilling    46
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2.0,4.0,"[2, 5, 6]",30.0,30.0,40.0
72,3.0,4.0,"[2, 4, 11, 6]",102.0,102.0,118.0

====================================================================================================
..\data\raw\2_6_r5_architectures.csv
rows: 179
is_full_dimension counts:
is_full_dimension
False    116
True      63
Name: count, dtype: int64
status counts:
status
nonfilling    98
NaN           81
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2.0,5.0,"[2, 6, 6]",36.0,36.0,48.0
67,3.0,5.0,"[2, 5, 16, 6]",156.0,156.0,186.0
76,3.0,5.0,"[2, 6, 15, 6]",156.0,156.0,192.0
80,3.0,5.0,"[2, 4, 17, 6]",156.0,156.0,178.0

====================================================================================================
..\data\raw\2_6_r6_architectures.csv
rows: 230
is_full_dimension counts:
is_full_dimension
False    188
True      42
Name: count, dtype: int64
status counts:
status
nonfilling    158
NaN            72
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2.0,6.0,"[2, 6, 6]",42.0,42.0,48.0
52,3.0,6.0,"[2, 6, 20, 6]",222.0,222.0,252.0
65,3.0,6.0,"[2, 5, 22, 6]",222.0,222.0,252.0
67,3.0,6.0,"[2, 4, 25, 6]",222.0,222.0,258.0
70,3.0,6.0,"[2, 7, 19, 6]",222.0,222.0,261.0

====================================================================================================
..\data\raw\2_6_r7_architectures.csv
rows: 324
is_full_dimension counts:
is_full_dimension
False    273
True      51
Name: count, dtype: int64
status counts:
status
nonfilling    230
NaN            94
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2.0,7.0,"[2, 7, 6]",48.0,48.0,56.0
75,3.0,7.0,"[2, 4, 33, 6]",300.0,300.0,338.0
76,3.0,7.0,"[2, 5, 30, 6]",300.0,300.0,340.0
85,3.0,7.0,"[2, 7, 25, 6]",300.0,300.0,339.0
86,3.0,7.0,"[2, 6, 27, 6]",300.0,300.0,336.0
93,3.0,7.0,"[2, 8, 24, 6]",300.0,300.0,352.0

====================================================================================================
..\data\raw\2_6_r8_architectures.csv
rows: 429
is_full_dimension counts:
is_full_dimension
False    362
True      67
Name: count, dtype: int64
status counts:
status
nonfilling    328
NaN           101
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
9,2.0,8.0,"[2, 8, 6]",54.0,54.0,64.0
67,3.0,8.0,"[2, 4, 43, 6]",390.0,390.0,438.0
73,3.0,8.0,"[2, 5, 39, 6]",390.0,390.0,439.0
87,3.0,8.0,"[2, 7, 32, 6]",390.0,390.0,430.0
88,3.0,8.0,"[2, 9, 28, 6]",390.0,390.0,438.0
94,3.0,8.0,"[2, 6, 35, 6]",390.0,390.0,432.0
100,3.0,8.0,"[2, 8, 30, 6]",390.0,390.0,436.0

====================================================================================================
..\data\raw\2_6_r9_architectures.csv
rows: 553
is_full_dimension counts:
is_full_dimension
False    497
True      56
Name: count, dtype: int64
status counts:
status
nonfilling    447
NaN           106
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2.0,9.0,"[2, 9, 6]",60.0,60.0,72.0
77,3.0,9.0,"[2, 6, 45, 6]",492.0,492.0,552.0
83,3.0,9.0,"[2, 8, 38, 6]",492.0,492.0,548.0
93,3.0,9.0,"[2, 5, 49, 6]",492.0,492.0,549.0
100,3.0,9.0,"[2, 7, 41, 6]",492.0,492.0,547.0
101,3.0,9.0,"[2, 9, 35, 6]",492.0,492.0,543.0
102,3.0,9.0,"[2, 4, 55, 6]",492.0,492.0,558.0
105,3.0,9.0,"[2, 10, 33, 6]",492.0,492.0,548.0

====================================================================================================
..\data\raw\2_7_r1_architectures.csv
rows: 52
is_full_dimension counts:
is_full_dimension
True     38
False    14
Name: count, dtype: int64
status counts:
status
NaN           48
nonfilling     4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2.0,1.0,"[2, 2, 7]",14.0,14.0,18.0
47,3.0,1.0,"[2, 2, 2, 7]",14.0,14.0,22.0

====================================================================================================
..\data\raw\2_7_r2_architectures.csv
rows: 70
is_full_dimension counts:
is_full_dimension
False    40
True     30
Name: count, dtype: int64
status counts:
status
NaN           54
nonfilling    16
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2.0,2.0,"[2, 3, 7]",21.0,21.0,27.0
50,3.0,2.0,"[2, 3, 5, 7]",35.0,35.0,56.0

====================================================================================================
..\data\raw\2_7_r3_architectures.csv
rows: 91
is_full_dimension counts:
is_full_dimension
False    50
True     41
Name: count, dtype: int64
status counts:
status
NaN           61
nonfilling    30
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2.0,3.0,"[2, 4, 7]",28.0,28.0,36.0
60,3.0,3.0,"[2, 4, 7, 7]",70.0,70.0,85.0

====================================================================================================
..\data\raw\2_7_r4_architectures.csv
rows: 142
is_full_dimension counts:
is_full_dimension
False    86
True     56
Name: count, dtype: int64
status counts:
status
NaN           83
nonfilling    59
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2.0,4.0,"[2, 5, 7]",35.0,35.0,45.0
79,3.0,4.0,"[2, 5, 11, 7]",119.0,119.0,142.0
80,3.0,4.0,"[2, 4, 12, 7]",119.0,119.0,140.0

====================================================================================================
..\data\raw\2_7_r5_architectures.csv
rows: 197
is_full_dimension counts:
is_full_dimension
False    143
True      54
Name: count, dtype: int64
status counts:
status
nonfilling    103
NaN            94
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2.0,5.0,"[2, 6, 7]",42.0,42.0,54.0
87,3.0,5.0,"[2, 4, 18, 7]",182.0,182.0,206.0
92,3.0,5.0,"[2, 6, 16, 7]",182.0,182.0,220.0
93,3.0,5.0,"[2, 5, 17, 7]",182.0,182.0,214.0

====================================================================================================
..\data\raw\2_7_r6_architectures.csv
rows: 270
is_full_dimension counts:
is_full_dimension
False    207
True      63
Name: count, dtype: int64
status counts:
status
nonfilling    166
NaN           104
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2.0,6.0,"[2, 7, 7]",49.0,49.0,63.0
81,3.0,6.0,"[2, 4, 26, 7]",259.0,259.0,294.0
100,3.0,6.0,"[2, 5, 24, 7]",259.0,259.0,298.0
101,3.0,6.0,"[2, 6, 22, 7]",259.0,259.0,298.0
103,3.0,6.0,"[2, 7, 20, 7]",259.0,259.0,294.0

====================================================================================================
..\data\raw\2_7_r7_architectures.csv
rows: 355
is_full_dimension counts:
is_full_dimension
False    303
True      52
Name: count, dtype: int64
status counts:
status
nonfilling    245
NaN           110
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
7,2.0,7.0,"[2, 7, 7]",56.0,56.0,63.0
93,3.0,7.0,"[2, 7, 27, 7]",350.0,350.0,392.0
96,3.0,7.0,"[2, 6, 29, 7]",350.0,350.0,389.0
99,3.0,7.0,"[2, 4, 35, 7]",350.0,350.0,393.0
107,3.0,7.0,"[2, 5, 32, 7]",350.0,350.0,394.0
109,3.0,7.0,"[2, 8, 25, 7]",350.0,350.0,391.0

====================================================================================================
..\data\raw\2_7_r8_architectures.csv
rows: 459
is_full_dimension counts:
is_full_dimension
False    416
True      43
Name: count, dtype: int64
status counts:
status
nonfilling    352
NaN           107
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
7,2.0,8.0,"[2, 8, 7]",63.0,63.0,72.0
52,3.0,8.0,"[2, 4, 46, 7]",455.0,455.0,514.0
67,3.0,8.0,"[2, 7, 35, 7]",455.0,455.0,504.0
88,3.0,8.0,"[2, 6, 38, 7]",455.0,455.0,506.0
93,3.0,8.0,"[2, 8, 32, 7]",455.0,455.0,496.0
105,3.0,8.0,"[2, 5, 41, 7]",455.0,455.0,502.0
106,3.0,8.0,"[2, 9, 31, 7]",455.0,455.0,514.0

====================================================================================================
..\data\raw\2_7_r9_architectures.csv
rows: 563
is_full_dimension counts:
is_full_dimension
False    515
True      48
Name: count, dtype: int64
status counts:
status
nonfilling    474
NaN            89
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2.0,9.0,"[2, 9, 7]",70.0,70.0,81.0
35,3.0,9.0,"[2, 7, 44, 7]",574.0,574.0,630.0
53,3.0,9.0,"[2, 5, 52, 7]",574.0,574.0,634.0
54,3.0,9.0,"[2, 4, 57, 7]",574.0,574.0,635.0
77,3.0,9.0,"[2, 10, 36, 7]",574.0,574.0,632.0
80,3.0,9.0,"[2, 8, 41, 7]",574.0,574.0,631.0
87,3.0,9.0,"[2, 6, 48, 7]",574.0,574.0,636.0
88,3.0,9.0,"[2, 9, 38, 7]",574.0,574.0,626.0

====================================================================================================
..\data\raw\2_8_r1_architectures.csv
rows: 57
is_full_dimension counts:
is_full_dimension
True     44
False    13
Name: count, dtype: int64
status counts:
status
NaN           53
nonfilling     4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2.0,1.0,"[2, 2, 8]",16.0,16.0,20.0
47,3.0,1.0,"[2, 2, 2, 8]",16.0,16.0,24.0

====================================================================================================
..\data\raw\2_8_r2_architectures.csv
rows: 84
is_full_dimension counts:
is_full_dimension
True     47
False    37
Name: count, dtype: int64
status counts:
status
NaN           68
nonfilling    16
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2.0,2.0,"[2, 3, 8]",24.0,24.0,30.0
67,3.0,2.0,"[2, 3, 5, 8]",40.0,40.0,61.0

====================================================================================================
..\data\raw\2_8_r3_architectures.csv
rows: 97
is_full_dimension counts:
is_full_dimension
False    56
True     41
Name: count, dtype: int64
status counts:
status
NaN           63
nonfilling    34
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2.0,3.0,"[2, 4, 8]",32.0,32.0,40.0
58,3.0,3.0,"[2, 4, 8, 8]",80.0,80.0,104.0

====================================================================================================
..\data\raw\2_8_r4_architectures.csv
rows: 132
is_full_dimension counts:
is_full_dimension
False    79
True     53
Name: count, dtype: int64
status counts:
status
NaN           82
nonfilling    50
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2.0,4.0,"[2, 5, 8]",40.0,40.0,50.0
81,3.0,4.0,"[2, 4, 12, 8]",136.0,136.0,152.0

====================================================================================================
..\data\raw\2_8_r5_architectures.csv
rows: 177
is_full_dimension counts:
is_full_dimension
False    137
True      40
Name: count, dtype: int64
status counts:
status
nonfilling    107
NaN            70
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2.0,5.0,"[2, 6, 8]",48.0,48.0,60.0
55,3.0,5.0,"[2, 6, 16, 8]",208.0,208.0,236.0
65,3.0,5.0,"[2, 5, 17, 8]",208.0,208.0,231.0
67,3.0,5.0,"[2, 4, 19, 8]",208.0,208.0,236.0

====================================================================================================
..\data\raw\2_8_r6_architectures.csv
rows: 269
is_full_dimension counts:
is_full_dimension
False    216
True      53
Name: count, dtype: int64
status counts:
status
nonfilling    174
NaN            95
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
9,2.0,6.0,"[2, 7, 8]",56.0,56.0,70.0
73,3.0,6.0,"[2, 4, 27, 8]",296.0,296.0,332.0
83,3.0,6.0,"[2, 5, 25, 8]",296.0,296.0,335.0
87,3.0,6.0,"[2, 7, 22, 8]",296.0,296.0,344.0
93,3.0,6.0,"[2, 6, 23, 8]",296.0,296.0,334.0

====================================================================================================
..\data\raw\2_8_r7_architectures.csv
rows: 366
is_full_dimension counts:
is_full_dimension
False    302
True      64
Name: count, dtype: int64
status counts:
status
nonfilling    258
NaN           108
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
7,2.0,7.0,"[2, 8, 8]",64.0,64.0,80.0
102,3.0,7.0,"[2, 4, 36, 8]",400.0,400.0,440.0
104,3.0,7.0,"[2, 8, 27, 8]",400.0,400.0,448.0
105,3.0,7.0,"[2, 6, 31, 8]",400.0,400.0,446.0
106,3.0,7.0,"[2, 7, 29, 8]",400.0,400.0,449.0
107,3.0,7.0,"[2, 5, 33, 8]",400.0,400.0,439.0

====================================================================================================
..\data\raw\2_8_r8_architectures.csv
rows: 486
is_full_dimension counts:
is_full_dimension
False    420
True      66
Name: count, dtype: int64
status counts:
status
nonfilling    369
NaN           117
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2.0,8.0,"[2, 8, 8]",72.0,72.0,80.0
60,3.0,8.0,"[2, 8, 35, 8]",520.0,520.0,576.0
77,3.0,8.0,"[2, 6, 40, 8]",520.0,520.0,572.0
79,3.0,8.0,"[2, 5, 43, 8]",520.0,520.0,569.0
102,3.0,8.0,"[2, 7, 37, 8]",520.0,520.0,569.0
113,3.0,8.0,"[2, 9, 33, 8]",520.0,520.0,579.0
114,3.0,8.0,"[2, 4, 47, 8]",520.0,520.0,572.0

====================================================================================================
..\data\raw\2_8_r9_architectures.csv
rows: 611
is_full_dimension counts:
is_full_dimension
False    551
True      60
Name: count, dtype: int64
status counts:
status
nonfilling    503
NaN           108
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
8,2.0,9.0,"[2, 9, 8]",80.0,80.0,90.0
82,3.0,9.0,"[2, 6, 50, 8]",656.0,656.0,712.0
85,3.0,9.0,"[2, 5, 55, 8]",656.0,656.0,725.0
89,3.0,9.0,"[2, 4, 60, 8]",656.0,656.0,728.0
91,3.0,9.0,"[2, 8, 44, 8]",656.0,656.0,720.0
99,3.0,9.0,"[2, 9, 41, 8]",656.0,656.0,715.0
104,3.0,9.0,"[2, 10, 39, 8]",656.0,656.0,722.0
106,3.0,9.0,"[2, 7, 47, 8]",656.0,656.0,719.0

====================================================================================================
..\data\raw\2_9_r1_architectures.csv
rows: 51
is_full_dimension counts:
is_full_dimension
True     33
False    18
Name: count, dtype: int64
status counts:
status
NaN           47
nonfilling     4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2.0,1.0,"[2, 2, 9]",18.0,18.0,22.0
46,3.0,1.0,"[2, 2, 2, 9]",18.0,18.0,26.0

====================================================================================================
..\data\raw\2_9_r2_architectures.csv
rows: 77
is_full_dimension counts:
is_full_dimension
False    39
True     38
Name: count, dtype: int64
status counts:
status
NaN           61
nonfilling    16
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2.0,2.0,"[2, 3, 9]",27.0,27.0,33.0
58,3.0,2.0,"[2, 3, 5, 9]",45.0,45.0,66.0

====================================================================================================
..\data\raw\2_9_r3_architectures.csv
rows: 123
is_full_dimension counts:
is_full_dimension
False    63
True     60
Name: count, dtype: int64
status counts:
status
NaN           85
nonfilling    38
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2.0,3.0,"[2, 4, 9]",36.0,36.0,44.0
84,3.0,3.0,"[2, 4, 9, 9]",90.0,90.0,125.0

====================================================================================================
..\data\raw\2_9_r4_architectures.csv
rows: 139
is_full_dimension counts:
is_full_dimension
False    103
True      36
Name: count, dtype: int64
status counts:
status
NaN           74
nonfilling    65
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2.0,4.0,"[2, 5, 9]",45.0,45.0,55.0
68,3.0,4.0,"[2, 4, 13, 9]",153.0,153.0,177.0
73,3.0,4.0,"[2, 5, 12, 9]",153.0,153.0,178.0

====================================================================================================
..\data\raw\2_9_r5_architectures.csv
rows: 199
is_full_dimension counts:
is_full_dimension
False    140
True      59
Name: count, dtype: int64
status counts:
status
nonfilling    114
NaN            85
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2.0,5.0,"[2, 6, 9]",54.0,54.0,66.0
78,3.0,5.0,"[2, 4, 20, 9]",234.0,234.0,268.0
82,3.0,5.0,"[2, 6, 17, 9]",234.0,234.0,267.0
83,3.0,5.0,"[2, 5, 18, 9]",234.0,234.0,262.0

====================================================================================================
..\data\raw\2_9_r6_architectures.csv
rows: 283
is_full_dimension counts:
is_full_dimension
False    228
True      55
Name: count, dtype: int64
status counts:
status
nonfilling    180
NaN           103
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2.0,6.0,"[2, 7, 9]",63.0,63.0,77.0
93,3.0,6.0,"[2, 6, 24, 9]",333.0,333.0,372.0
96,3.0,6.0,"[2, 4, 28, 9]",333.0,333.0,372.0
97,3.0,6.0,"[2, 5, 26, 9]",333.0,333.0,374.0
100,3.0,6.0,"[2, 7, 23, 9]",333.0,333.0,382.0

====================================================================================================
..\data\raw\2_9_r7_architectures.csv
rows: 378
is_full_dimension counts:
is_full_dimension
False    312
True      66
Name: count, dtype: int64
status counts:
status
nonfilling    272
NaN           106
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
8,2.0,7.0,"[2, 8, 9]",72.0,72.0,88.0
89,3.0,7.0,"[2, 5, 35, 9]",450.0,450.0,500.0
94,3.0,7.0,"[2, 6, 32, 9]",450.0,450.0,492.0
99,3.0,7.0,"[2, 4, 38, 9]",450.0,450.0,502.0
102,3.0,7.0,"[2, 8, 29, 9]",450.0,450.0,509.0
104,3.0,7.0,"[2, 7, 30, 9]",450.0,450.0,494.0

====================================================================================================
..\data\raw\2_9_r8_architectures.csv
rows: 467
is_full_dimension counts:
is_full_dimension
False    438
True      29
Name: count, dtype: int64
status counts:
status
nonfilling    385
NaN            82
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2.0,8.0,"[2, 9, 9]",81.0,81.0,99.0
39,3.0,8.0,"[2, 7, 39, 9]",585.0,585.0,638.0
71,3.0,8.0,"[2, 4, 49, 9]",585.0,585.0,645.0
72,3.0,8.0,"[2, 5, 45, 9]",585.0,585.0,640.0
79,3.0,8.0,"[2, 8, 37, 9]",585.0,585.0,645.0
80,3.0,8.0,"[2, 6, 42, 9]",585.0,585.0,642.0
81,3.0,8.0,"[2, 9, 35, 9]",585.0,585.0,648.0

====================================================================================================
..\data\raw\2_9_r9_architectures.csv
rows: 631
is_full_dimension counts:
is_full_dimension
False    564
True      67
Name: count, dtype: int64
status counts:
status
nonfilling    527
NaN           104
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2.0,9.0,"[2, 9, 9]",90.0,90.0,99.0
71,3.0,9.0,"[2, 6, 53, 9]",738.0,738.0,807.0
84,3.0,9.0,"[2, 8, 46, 9]",738.0,738.0,798.0
90,3.0,9.0,"[2, 10, 41, 9]",738.0,738.0,799.0
96,3.0,9.0,"[2, 4, 62, 9]",738.0,738.0,814.0
98,3.0,9.0,"[2, 5, 57, 9]",738.0,738.0,808.0
100,3.0,9.0,"[2, 7, 49, 9]",738.0,738.0,798.0
103,3.0,9.0,"[2, 9, 43, 9]",738.0,738.0,792.0

====================================================================================================
..\data\raw\3_1_r1_architectures.csv
rows: 43
is_full_dimension counts:
is_full_dimension
True    43
Name: count, dtype: int64
status counts:
status
NaN    43
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,1,"[3, 1, 1]",3,3,4
42,3,1,"[3, 1, 1, 1]",3,3,5

====================================================================================================
..\data\raw\3_1_r2_architectures.csv
rows: 64713
is_full_dimension counts:
is_full_dimension
False    62792
True      1921
Name: count, dtype: int64
status counts:
status
nonfilling                    56771
NaN                            7941
filling_below_recorded_mfa        1
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
19,3.0,2.0,"[3, 4, 3, 1]",15.0,15.0,27.0
69,4.0,2.0,"[3, 5, 6, 4, 1]",45.0,45.0,73.0
178,2.0,2.0,"[3, 3, 1]",6.0,6.0,12.0
482,5.0,2.0,"[3, 6, 9, 9, 6, 1]",153.0,153.0,213.0
500,5.0,2.0,"[3, 5, 9, 10, 4, 1]",153.0,153.0,194.0
...,...,...,...,...,...,...
6555,7.0,2.0,"[3, 5, 13, 30, 26, 29, 12, 1]",2145.0,2145.0,2364.0
6596,7.0,2.0,"[3, 5, 11, 19, 39, 28, 6, 1]",2145.0,2145.0,2286.0
6598,7.0,2.0,"[3, 5, 13, 19, 39, 28, 5, 1]",2145.0,2145.0,2305.0
6625,7.0,2.0,"[3, 5, 14, 19, 36, 30, 7, 1]",2145.0,2145.0,2332.0
64712,6.0,2.0,"[3, 5, 8, 13, 27, 5, 1]",561.0,561.0,650.0

====================================================================================================
..\data\raw\3_1_r3_architectures.csv
rows: 12282
is_full_dimension counts:
is_full_dimension
False    6470
True     5812
Name: count, dtype: int64
status counts:
status
NaN    12282
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,3,"[3, 4, 1]",10,10,16
40,3,3,"[3, 6, 8, 1]",55,55,74
41,3,3,"[3, 7, 6, 1]",55,55,69
189,4,3,"[3, 8, 22, 11, 1]",406,406,453
202,4,3,"[3, 8, 12, 26, 1]",406,406,458
...,...,...,...,...,...,...
12247,5,3,"[3, 6, 48, 53, 13, 1]",3403,3403,3552
12250,5,3,"[3, 8, 45, 33, 51, 1]",3403,3403,3603
12251,5,3,"[3, 8, 33, 47, 36, 1]",3403,3403,3567
12255,5,3,"[3, 6, 35, 46, 37, 1]",3403,3403,3577
12258,5,3,"[3, 9, 33, 45, 38, 1]",3403,3403,3557

====================================================================================================
..\data\raw\3_1_r4_architectures.csv
rows: 99
is_full_dimension counts:
is_full_dimension
True     64
False    35
Name: count, dtype: int64
status counts:
status
NaN    99
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
10,2,4,"[3, 6, 1]",15,15,24
73,3,4,"[3, 7, 20, 1]",153,153,181
85,3,4,"[3, 11, 12, 1]",153,153,177
87,3,4,"[3, 9, 15, 1]",153,153,177
93,3,4,"[3, 10, 14, 1]",153,153,184
96,3,4,"[3, 8, 18, 1]",153,153,186
98,3,4,"[3, 12, 11, 1]",153,153,179

====================================================================================================
..\data\raw\3_1_r5_architectures.csv
rows: 139
is_full_dimension counts:
is_full_dimension
False    70
True     69
Name: count, dtype: int64
status counts:
status
NaN    139
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2,5,"[3, 7, 1]",21,21,28
84,3,5,"[3, 8, 42, 1]",351,351,402
97,3,5,"[3, 16, 20, 1]",351,351,388
99,3,5,"[3, 11, 30, 1]",351,351,393
106,3,5,"[3, 14, 24, 1]",351,351,402
109,3,5,"[3, 15, 22, 1]",351,351,397
114,3,5,"[3, 13, 25, 1]",351,351,389
116,3,5,"[3, 9, 37, 1]",351,351,397
118,3,5,"[3, 7, 49, 1]",351,351,413
122,3,5,"[3, 19, 17, 1]",351,351,397
125,3,5,"[3, 10, 34, 1]",351,351,404
128,3,5,"[3, 18, 18, 1]",351,351,396
136,3,5,"[3, 17, 19, 1]",351,351,393
138,3,5,"[3, 12, 28, 1]",351,351,400

====================================================================================================
..\data\raw\3_1_r6_architectures.csv
rows: 155
is_full_dimension counts:
is_full_dimension
True     90
False    65
Name: count, dtype: int64
status counts:
status
NaN    155
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
9,2,6,"[3, 10, 1]",28,28,40
70,3,6,"[3, 21, 32, 1]",703,703,767
75,3,6,"[3, 23, 29, 1]",703,703,765
80,3,6,"[3, 16, 42, 1]",703,703,762
83,3,6,"[3, 9, 77, 1]",703,703,797
103,3,6,"[3, 15, 45, 1]",703,703,765
105,3,6,"[3, 13, 53, 1]",703,703,781
108,3,6,"[3, 18, 38, 1]",703,703,776
109,3,6,"[3, 12, 57, 1]",703,703,777
116,3,6,"[3, 11, 62, 1]",703,703,777
118,3,6,"[3, 20, 34, 1]",703,703,774
122,3,6,"[3, 7, 99, 1]",703,703,813
132,3,6,"[3, 10, 69, 1]",703,703,789
138,3,6,"[3, 19, 35, 1]",703,703,757
139,3,6,"[3, 8, 86, 1]",703,703,798
140,3,6,"[3, 14, 49, 1]",703,703,777
141,3,6,"[3, 24, 28, 1]",703,703,772
144,3,6,"[3, 22, 30, 1]",703,703,756
147,3,6,"[3, 26, 26, 1]",703,703,780
148,3,6,"[3, 25, 27, 1]",703,703,777
154,3,6,"[3, 17, 40, 1]",703,703,771

====================================================================================================
..\data\raw\3_1_r7_architectures.csv
rows: 239
is_full_dimension counts:
is_full_dimension
False    123
True     116
Name: count, dtype: int64
status counts:
status
NaN    239
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2,7,"[3, 12, 1]",36,36,48
62,3,7,"[3, 14, 90, 1]",1275,1275,1392
96,3,7,"[3, 20, 62, 1]",1275,1275,1362
109,3,7,"[3, 25, 49, 1]",1275,1275,1349
118,3,7,"[3, 9, 140, 1]",1275,1275,1427
126,3,7,"[3, 8, 158, 1]",1275,1275,1446
161,3,7,"[3, 10, 126, 1]",1275,1275,1416
165,3,7,"[3, 16, 78, 1]",1275,1275,1374
169,3,7,"[3, 29, 42, 1]",1275,1275,1347
173,3,7,"[3, 30, 41, 1]",1275,1275,1361
174,3,7,"[3, 34, 36, 1]",1275,1275,1362
175,3,7,"[3, 13, 97, 1]",1275,1275,1397
177,3,7,"[3, 23, 54, 1]",1275,1275,1365
180,3,7,"[3, 7, 181, 1]",1275,1275,1469
181,3,7,"[3, 21, 59, 1]",1275,1275,1361
182,3,7,"[3, 28, 44, 1]",1275,1275,1360
184,3,7,"[3, 15, 83, 1]",1275,1275,1373
185,3,7,"[3, 22, 56, 1]",1275,1275,1354
187,3,7,"[3, 26, 48, 1]",1275,1275,1374
192,3,7,"[3, 31, 40, 1]",1275,1275,1373
194,3,7,"[3, 12, 105, 1]",1275,1275,1401
200,3,7,"[3, 24, 52, 1]",1275,1275,1372
202,3,7,"[3, 11, 114, 1]",1275,1275,1401
204,3,7,"[3, 17, 73, 1]",1275,1275,1365
208,3,7,"[3, 33, 37, 1]",1275,1275,1357
211,3,7,"[3, 19, 66, 1]",1275,1275,1377
216,3,7,"[3, 18, 69, 1]",1275,1275,1365
220,3,7,"[3, 27, 46, 1]",1275,1275,1369
224,3,7,"[3, 32, 38, 1]",1275,1275,1350

====================================================================================================
..\data\raw\3_1_r8_architectures.csv
rows: 263
is_full_dimension counts:
is_full_dimension
True     148
False    115
Name: count, dtype: int64
status counts:
status
NaN    263
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
8,2,8,"[3, 15, 1]",45,45,60
94,3,8,"[3, 23, 92, 1]",2145,2145,2277
105,3,8,"[3, 10, 213, 1]",2145,2145,2373
111,3,8,"[3, 15, 141, 1]",2145,2145,2301
131,3,8,"[3, 14, 152, 1]",2145,2145,2322
133,3,8,"[3, 36, 58, 1]",2145,2145,2254
139,3,8,"[3, 38, 55, 1]",2145,2145,2259
141,3,8,"[3, 25, 84, 1]",2145,2145,2259
146,3,8,"[3, 26, 81, 1]",2145,2145,2265
148,3,8,"[3, 11, 193, 1]",2145,2145,2349
149,3,8,"[3, 34, 62, 1]",2145,2145,2272
160,3,8,"[3, 37, 56, 1]",2145,2145,2239
165,3,8,"[3, 13, 163, 1]",2145,2145,2321
176,3,8,"[3, 24, 88, 1]",2145,2145,2272
180,3,8,"[3, 19, 111, 1]",2145,2145,2277
184,3,8,"[3, 32, 66, 1]",2145,2145,2274
186,3,8,"[3, 31, 68, 1]",2145,2145,2269
195,3,8,"[3, 39, 53, 1]",2145,2145,2237
196,3,8,"[3, 22, 96, 1]",2145,2145,2274
205,3,8,"[3, 40, 52, 1]",2145,2145,2252
206,3,8,"[3, 33, 63, 1]",2145,2145,2241
210,3,8,"[3, 41, 51, 1]",2145,2145,2265
213,3,8,"[3, 18, 118, 1]",2145,2145,2296
217,3,8,"[3, 8, 267, 1]",2145,2145,2427
221,3,8,"[3, 12, 177, 1]",2145,2145,2337
223,3,8,"[3, 42, 50, 1]",2145,2145,2276
228,3,8,"[3, 21, 101, 1]",2145,2145,2285
230,3,8,"[3, 27, 78, 1]",2145,2145,2265
232,3,8,"[3, 28, 75, 1]",2145,2145,2259
238,3,8,"[3, 29, 72, 1]",2145,2145,2247
239,3,8,"[3, 9, 237, 1]",2145,2145,2397
240,3,8,"[3, 16, 133, 1]",2145,2145,2309
242,3,8,"[3, 30, 70, 1]",2145,2145,2260
244,3,8,"[3, 20, 106, 1]",2145,2145,2286
245,3,8,"[3, 17, 125, 1]",2145,2145,2301
246,3,8,"[3, 35, 60, 1]",2145,2145,2265
247,3,8,"[3, 43, 48, 1]",2145,2145,2241

====================================================================================================
..\data\raw\3_1_r9_architectures.csv
rows: 45
is_full_dimension counts:
is_full_dimension
True     32
False    13
Name: count, dtype: int64
status counts:
status
NaN    45
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
10,2,9,"[3, 19, 1]",55,55,76
16,3,9,"[3, 15, 250, 1]",3403,3403,4045
19,3,9,"[3, 27, 143, 1]",3403,3403,4085
28,3,9,"[3, 56, 69, 1]",3403,3403,4101
29,3,9,"[3, 32, 120, 1]",3403,3403,4056
34,3,9,"[3, 61, 63, 1]",3403,3403,4089
38,3,9,"[3, 45, 83, 1]",3403,3403,3953
39,3,9,"[3, 22, 189, 1]",3403,3403,4413
40,3,9,"[3, 14, 297, 1]",3403,3403,4497
41,3,9,"[3, 18, 201, 1]",3403,3403,3873
42,3,9,"[3, 41, 111, 1]",3403,3403,4785
43,3,9,"[3, 24, 147, 1]",3403,3403,3747

====================================================================================================
..\data\raw\3_2_r1_architectures.csv
rows: 59
is_full_dimension counts:
is_full_dimension
True     49
False    10
Name: count, dtype: int64
status counts:
status
NaN    59
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
8,2,1,"[3, 2, 2]",6,6,10
58,3,1,"[3, 2, 2, 2]",6,6,14

====================================================================================================
..\data\raw\3_2_r2_architectures.csv
rows: 63
is_full_dimension counts:
is_full_dimension
True     35
False    28
Name: count, dtype: int64
status counts:
status
NaN    63
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2,2,"[3, 3, 2]",12,12,15
60,3,2,"[3, 5, 5, 2]",30,30,50

====================================================================================================
..\data\raw\3_2_r3_architectures.csv
rows: 919
is_full_dimension counts:
is_full_dimension
False    478
True     441
Name: count, dtype: int64
status counts:
status
NaN    919
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2,3,"[3, 6, 2]",20,20,30
43,3,3,"[3, 7, 12, 2]",110,110,129
52,3,3,"[3, 10, 10, 2]",110,110,150
62,3,3,"[3, 6, 14, 2]",110,110,130
64,3,3,"[3, 8, 11, 2]",110,110,134
...,...,...,...,...,...,...
870,4,3,"[3, 6, 24, 28, 2]",812,812,890
872,4,3,"[3, 8, 19, 34, 2]",812,812,890
875,4,3,"[3, 10, 25, 23, 2]",812,812,901
879,4,3,"[3, 9, 28, 20, 2]",812,812,879
880,4,3,"[3, 8, 36, 15, 2]",812,812,882

====================================================================================================
..\data\raw\3_2_r4_architectures.csv
rows: 101
is_full_dimension counts:
is_full_dimension
False    98
True      3
Name: count, dtype: int64
status counts:
status
NaN    101
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,4,"[3, 8, 2]",30,30,40

====================================================================================================
..\data\raw\3_2_r5_architectures.csv
rows: 20
is_full_dimension counts:
is_full_dimension
False    17
True      3
Name: count, dtype: int64
status counts:
status
NaN    20
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,5,"[3, 11, 2]",42,42,55

====================================================================================================
..\data\raw\3_2_r6_architectures.csv
rows: 9
is_full_dimension counts:
is_full_dimension
False    7
True     2
Name: count, dtype: int64
status counts:
status
NaN    9
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2,6,"[3, 14, 2]",56,56,70

====================================================================================================
..\data\raw\3_2_r7_architectures.csv
rows: 7
is_full_dimension counts:
is_full_dimension
True     5
False    2
Name: count, dtype: int64
status counts:
status
NaN    7
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2,7,"[3, 18, 2]",72,72,90

====================================================================================================
..\data\raw\3_2_r8_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
False    2
True     1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
0,2,8,"[3, 23, 2]",90,90,115

====================================================================================================
..\data\raw\3_2_r9_architectures.csv
rows: 6
is_full_dimension counts:
is_full_dimension
True     3
False    3
Name: count, dtype: int64
status counts:
status
NaN    6
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2,9,"[3, 28, 2]",110,110,140

====================================================================================================
..\data\raw\3_3_r1_architectures.csv
rows: 2
is_full_dimension counts:
is_full_dimension
True     1
False    1
Name: count, dtype: int64
status counts:
status
NaN    2
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
0,2,1,"[3, 3, 3]",9,9,18

====================================================================================================
..\data\raw\3_3_r2_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True     2
False    1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,2,"[3, 4, 3]",18,18,24

====================================================================================================
..\data\raw\3_3_r3_architectures.csv
rows: 599
is_full_dimension counts:
is_full_dimension
False    335
True     264
Name: count, dtype: int64
status counts:
status
NaN    599
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,3,"[3, 6, 3]",30,30,36
56,3,3,"[3, 8, 15, 3]",165,165,189
58,3,3,"[3, 6, 20, 3]",165,165,198
59,3,3,"[3, 10, 14, 3]",165,165,212
60,3,3,"[3, 7, 17, 3]",165,165,191
...,...,...,...,...,...,...
592,4,3,"[3, 18, 27, 34, 3]",1218,1218,1560
594,4,3,"[3, 10, 18, 53, 3]",1218,1218,1323
595,4,3,"[3, 6, 40, 26, 3]",1218,1218,1376
596,4,3,"[3, 16, 30, 30, 3]",1218,1218,1518
598,4,3,"[3, 10, 37, 24, 3]",1218,1218,1360

====================================================================================================
..\data\raw\3_3_r4_architectures.csv
rows: 5
is_full_dimension counts:
is_full_dimension
True     4
False    1
Name: count, dtype: int64
status counts:
status
NaN    5
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,4,"[3, 9, 3]",45,45,54

====================================================================================================
..\data\raw\3_3_r5_architectures.csv
rows: 4
is_full_dimension counts:
is_full_dimension
True     3
False    1
Name: count, dtype: int64
status counts:
status
NaN    4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,5,"[3, 13, 3]",63,63,78

====================================================================================================
..\data\raw\3_3_r6_architectures.csv
rows: 2191
is_full_dimension counts:
is_full_dimension
False    2118
True       73
Name: count, dtype: int64
status counts:
status
nonfilling    2014
NaN            177
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
74,2.0,6.0,"[3, 17, 3]",84.0,84.0,102.0
76,3.0,6.0,"[3, 28, 71, 3]",2109.0,2109.0,2285.0
77,3.0,6.0,"[3, 27, 72, 3]",2109.0,2109.0,2241.0
80,3.0,6.0,"[3, 24, 80, 3]",2109.0,2109.0,2232.0
84,3.0,6.0,"[3, 26, 74, 3]",2109.0,2109.0,2224.0
87,3.0,6.0,"[3, 25, 77, 3]",2109.0,2109.0,2231.0
104,3.0,6.0,"[3, 17, 110, 3]",2109.0,2109.0,2251.0
105,3.0,6.0,"[3, 22, 87, 3]",2109.0,2109.0,2241.0
106,3.0,6.0,"[3, 21, 90, 3]",2109.0,2109.0,2223.0
113,3.0,6.0,"[3, 20, 95, 3]",2109.0,2109.0,2245.0
126,3.0,6.0,"[3, 16, 116, 3]",2109.0,2109.0,2252.0
128,3.0,6.0,"[3, 23, 83, 3]",2109.0,2109.0,2227.0
130,3.0,6.0,"[3, 19, 99, 3]",2109.0,2109.0,2235.0
131,3.0,6.0,"[3, 18, 104, 3]",2109.0,2109.0,2238.0
156,3.0,6.0,"[3, 14, 131, 3]",2109.0,2109.0,2269.0
166,3.0,6.0,"[3, 15, 123, 3]",2109.0,2109.0,2259.0
171,3.0,6.0,"[3, 13, 139, 3]",2109.0,2109.0,2263.0
176,3.0,6.0,"[3, 12, 149, 3]",2109.0,2109.0,2271.0

====================================================================================================
..\data\raw\3_3_r7_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True     2
False    1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,7,"[3, 22, 3]",108,108,132

====================================================================================================
..\data\raw\3_3_r8_architectures.csv
rows: 5
is_full_dimension counts:
is_full_dimension
False    3
True     2
Name: count, dtype: int64
status counts:
status
NaN    5
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,8,"[3, 27, 3]",135,135,162

====================================================================================================
..\data\raw\3_3_r9_architectures.csv
rows: 6
is_full_dimension counts:
is_full_dimension
True     3
False    3
Name: count, dtype: int64
status counts:
status
NaN    6
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,9,"[3, 33, 3]",165,165,198

====================================================================================================
..\data\raw\3_4_r1_architectures.csv
rows: 2
is_full_dimension counts:
is_full_dimension
False    1
True     1
Name: count, dtype: int64
status counts:
status
NaN    2
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2,1,"[3, 3, 4]",12,12,21

====================================================================================================
..\data\raw\3_4_r2_architectures.csv
rows: 2
is_full_dimension counts:
is_full_dimension
True    2
Name: count, dtype: int64
status counts:
status
NaN    2
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2,2,"[3, 4, 4]",24,24,28

====================================================================================================
..\data\raw\3_4_r3_architectures.csv
rows: 1115
is_full_dimension counts:
is_full_dimension
False    612
True     503
Name: count, dtype: int64
status counts:
status
NaN    1115
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
7,2,3,"[3, 7, 4]",40,40,49
45,3,3,"[3, 9, 18, 4]",220,220,261
52,3,3,"[3, 8, 19, 4]",220,220,252
53,3,3,"[3, 10, 17, 4]",220,220,268
62,3,3,"[3, 6, 24, 4]",220,220,258
...,...,...,...,...,...,...
1099,4,3,"[3, 10, 35, 35, 4]",1624,1624,1745
1100,4,3,"[3, 6, 41, 32, 4]",1624,1624,1704
1102,4,3,"[3, 8, 18, 71, 4]",1624,1624,1730
1103,4,3,"[3, 8, 25, 52, 4]",1624,1624,1732
1109,4,3,"[3, 9, 24, 53, 4]",1624,1624,1727

====================================================================================================
..\data\raw\3_4_r4_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True     2
False    1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,4,"[3, 10, 4]",60,60,70

====================================================================================================
..\data\raw\3_4_r5_architectures.csv
rows: 8
is_full_dimension counts:
is_full_dimension
True     6
False    2
Name: count, dtype: int64
status counts:
status
NaN    8
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2,5,"[3, 14, 4]",84,84,98

====================================================================================================
..\data\raw\3_4_r6_architectures.csv
rows: 4
is_full_dimension counts:
is_full_dimension
True     3
False    1
Name: count, dtype: int64
status counts:
status
NaN    4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,6,"[3, 19, 4]",112,112,133

====================================================================================================
..\data\raw\3_4_r7_architectures.csv
rows: 5
is_full_dimension counts:
is_full_dimension
True     3
False    2
Name: count, dtype: int64
status counts:
status
NaN    5
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,7,"[3, 24, 4]",144,144,168

====================================================================================================
..\data\raw\3_4_r8_architectures.csv
rows: 5
is_full_dimension counts:
is_full_dimension
True     4
False    1
Name: count, dtype: int64
status counts:
status
NaN    5
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,8,"[3, 30, 4]",180,180,210

====================================================================================================
..\data\raw\3_4_r9_architectures.csv
rows: 7
is_full_dimension counts:
is_full_dimension
True     4
False    3
Name: count, dtype: int64
status counts:
status
NaN    7
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2,9,"[3, 37, 4]",220,220,259

====================================================================================================
..\data\raw\3_5_r1_architectures.csv
rows: 2
is_full_dimension counts:
is_full_dimension
True     1
False    1
Name: count, dtype: int64
status counts:
status
NaN    2
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
0,2,1,"[3, 3, 5]",15,15,24

====================================================================================================
..\data\raw\3_5_r2_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True     2
False    1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,2,"[3, 5, 5]",30,30,40

====================================================================================================
..\data\raw\3_5_r3_architectures.csv
rows: 2
is_full_dimension counts:
is_full_dimension
True     1
False    1
Name: count, dtype: int64
status counts:
status
NaN    2
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
0,2,3,"[3, 8, 5]",50,50,64

====================================================================================================
..\data\raw\3_5_r4_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True     2
False    1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2,4,"[3, 11, 5]",75,75,88

====================================================================================================
..\data\raw\3_5_r5_architectures.csv
rows: 6
is_full_dimension counts:
is_full_dimension
True     5
False    1
Name: count, dtype: int64
status counts:
status
NaN    6
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2,5,"[3, 15, 5]",105,105,120

====================================================================================================
..\data\raw\3_5_r6_architectures.csv
rows: 5
is_full_dimension counts:
is_full_dimension
True     3
False    2
Name: count, dtype: int64
status counts:
status
NaN    5
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,6,"[3, 20, 5]",140,140,160

====================================================================================================
..\data\raw\3_5_r7_architectures.csv
rows: 4
is_full_dimension counts:
is_full_dimension
True     3
False    1
Name: count, dtype: int64
status counts:
status
NaN    4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,7,"[3, 26, 5]",180,180,208

====================================================================================================
..\data\raw\3_5_r8_architectures.csv
rows: 6
is_full_dimension counts:
is_full_dimension
True     4
False    2
Name: count, dtype: int64
status counts:
status
NaN    6
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,8,"[3, 33, 5]",225,225,264

====================================================================================================
..\data\raw\3_5_r9_architectures.csv
rows: 4
is_full_dimension counts:
is_full_dimension
True     3
False    1
Name: count, dtype: int64
status counts:
status
NaN    4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,9,"[3, 40, 5]",275,275,320

====================================================================================================
..\data\raw\3_6_r1_architectures.csv
rows: 2
is_full_dimension counts:
is_full_dimension
True     1
False    1
Name: count, dtype: int64
status counts:
status
NaN    2
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
0,2,1,"[3, 3, 6]",18,18,27

====================================================================================================
..\data\raw\3_6_r2_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
False    2
True     1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
0,2,2,"[3, 6, 6]",36,36,54

====================================================================================================
..\data\raw\3_6_r3_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True     2
False    1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2,3,"[3, 8, 6]",60,60,72

====================================================================================================
..\data\raw\3_6_r4_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True     2
False    1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,4,"[3, 12, 6]",90,90,108

====================================================================================================
..\data\raw\3_6_r5_architectures.csv
rows: 4
is_full_dimension counts:
is_full_dimension
True     3
False    1
Name: count, dtype: int64
status counts:
status
NaN    4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,5,"[3, 16, 6]",126,126,144

====================================================================================================
..\data\raw\3_6_r6_architectures.csv
rows: 4
is_full_dimension counts:
is_full_dimension
True     3
False    1
Name: count, dtype: int64
status counts:
status
NaN    4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,6,"[3, 21, 6]",168,168,189

====================================================================================================
..\data\raw\3_6_r7_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True     2
False    1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2,7,"[3, 27, 6]",216,216,243

====================================================================================================
..\data\raw\3_6_r8_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True     2
False    1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2,8,"[3, 34, 6]",270,270,306

====================================================================================================
..\data\raw\3_6_r9_architectures.csv
rows: 4
is_full_dimension counts:
is_full_dimension
True     2
False    2
Name: count, dtype: int64
status counts:
status
NaN    4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2,9,"[3, 42, 6]",330,330,378

====================================================================================================
..\data\raw\3_7_r1_architectures.csv
rows: 1
is_full_dimension counts:
is_full_dimension
True    1
Name: count, dtype: int64
status counts:
status
NaN    1
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
0,2,1,"[3, 3, 7]",21,21,30

====================================================================================================
..\data\raw\3_7_r2_architectures.csv
rows: 2
is_full_dimension counts:
is_full_dimension
False    1
True     1
Name: count, dtype: int64
status counts:
status
NaN    2
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2,2,"[3, 6, 7]",42,42,60

====================================================================================================
..\data\raw\3_7_r3_architectures.csv
rows: 4
is_full_dimension counts:
is_full_dimension
True     3
False    1
Name: count, dtype: int64
status counts:
status
NaN    4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,3,"[3, 8, 7]",70,70,80

====================================================================================================
..\data\raw\3_7_r4_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True     2
False    1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2,4,"[3, 12, 7]",105,105,120

====================================================================================================
..\data\raw\3_7_r5_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True     2
False    1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,5,"[3, 17, 7]",147,147,170

====================================================================================================
..\data\raw\3_7_r6_architectures.csv
rows: 4
is_full_dimension counts:
is_full_dimension
True     2
False    2
Name: count, dtype: int64
status counts:
status
NaN    4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,6,"[3, 22, 7]",196,196,220

====================================================================================================
..\data\raw\3_7_r7_architectures.csv
rows: 5
is_full_dimension counts:
is_full_dimension
True     4
False    1
Name: count, dtype: int64
status counts:
status
NaN    5
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,7,"[3, 28, 7]",252,252,280

====================================================================================================
..\data\raw\3_7_r8_architectures.csv
rows: 5
is_full_dimension counts:
is_full_dimension
True     3
False    2
Name: count, dtype: int64
status counts:
status
NaN    5
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,8,"[3, 35, 7]",315,315,350

====================================================================================================
..\data\raw\3_7_r9_architectures.csv
rows: 6
is_full_dimension counts:
is_full_dimension
True     4
False    2
Name: count, dtype: int64
status counts:
status
NaN    6
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2,9,"[3, 43, 7]",385,385,430

====================================================================================================
..\data\raw\3_8_r1_architectures.csv
rows: 1
is_full_dimension counts:
is_full_dimension
True    1
Name: count, dtype: int64
status counts:
status
NaN    1
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
0,2,1,"[3, 3, 8]",24,24,33

====================================================================================================
..\data\raw\3_8_r2_architectures.csv
rows: 2
is_full_dimension counts:
is_full_dimension
True     1
False    1
Name: count, dtype: int64
status counts:
status
NaN    2
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
0,2,2,"[3, 6, 8]",48,48,66

====================================================================================================
..\data\raw\3_8_r3_architectures.csv
rows: 1
is_full_dimension counts:
is_full_dimension
True    1
Name: count, dtype: int64
status counts:
status
NaN    1
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
0,2,3,"[3, 8, 8]",80,80,88

====================================================================================================
..\data\raw\3_8_r4_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True     2
False    1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,4,"[3, 12, 8]",120,120,132

====================================================================================================
..\data\raw\3_8_r5_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True     2
False    1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2,5,"[3, 17, 8]",168,168,187

====================================================================================================
..\data\raw\3_8_r6_architectures.csv
rows: 4
is_full_dimension counts:
is_full_dimension
True     3
False    1
Name: count, dtype: int64
status counts:
status
NaN    4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,6,"[3, 23, 8]",224,224,253

====================================================================================================
..\data\raw\3_8_r7_architectures.csv
rows: 4
is_full_dimension counts:
is_full_dimension
False    2
True     2
Name: count, dtype: int64
status counts:
status
NaN    4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,7,"[3, 29, 8]",288,288,319

====================================================================================================
..\data\raw\3_8_r8_architectures.csv
rows: 4
is_full_dimension counts:
is_full_dimension
False    3
True     1
Name: count, dtype: int64
status counts:
status
NaN    4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
0,2,8,"[3, 36, 8]",360,360,396

====================================================================================================
..\data\raw\3_8_r9_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
False    2
True     1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
0,2,9,"[3, 44, 8]",440,440,484

====================================================================================================
..\data\raw\3_9_r1_architectures.csv
rows: 1
is_full_dimension counts:
is_full_dimension
True    1
Name: count, dtype: int64
status counts:
status
NaN    1
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
0,2,1,"[3, 3, 9]",27,27,36

====================================================================================================
..\data\raw\3_9_r2_architectures.csv
rows: 2
is_full_dimension counts:
is_full_dimension
True     1
False    1
Name: count, dtype: int64
status counts:
status
NaN    2
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
0,2,2,"[3, 6, 9]",54,54,72

====================================================================================================
..\data\raw\3_9_r3_architectures.csv
rows: 2
is_full_dimension counts:
is_full_dimension
True     1
False    1
Name: count, dtype: int64
status counts:
status
NaN    2
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
0,2,3,"[3, 9, 9]",90,90,108

====================================================================================================
..\data\raw\3_9_r4_architectures.csv
rows: 2
is_full_dimension counts:
is_full_dimension
False    1
True     1
Name: count, dtype: int64
status counts:
status
NaN    2
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2,4,"[3, 13, 9]",135,135,156

====================================================================================================
..\data\raw\3_9_r5_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True     2
False    1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,5,"[3, 18, 9]",189,189,216

====================================================================================================
..\data\raw\3_9_r6_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True     2
False    1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,6,"[3, 23, 9]",252,252,276

====================================================================================================
..\data\raw\3_9_r7_architectures.csv
rows: 4
is_full_dimension counts:
is_full_dimension
True     2
False    2
Name: count, dtype: int64
status counts:
status
NaN    4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,7,"[3, 30, 9]",324,324,360

====================================================================================================
..\data\raw\3_9_r8_architectures.csv
rows: 4
is_full_dimension counts:
is_full_dimension
True     2
False    2
Name: count, dtype: int64
status counts:
status
NaN    4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2,8,"[3, 37, 9]",405,405,444

====================================================================================================
..\data\raw\3_9_r9_architectures.csv
rows: 5
is_full_dimension counts:
is_full_dimension
False    3
True     2
Name: count, dtype: int64
status counts:
status
NaN    5
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2,9,"[3, 45, 9]",495,495,540

====================================================================================================
..\data\raw\4_1_r1_architectures.csv
rows: 2
is_full_dimension counts:
is_full_dimension
True    2
Name: count, dtype: int64
status counts:
status
NaN    2
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
0,2,1,"[4, 1, 1]",4,4,5
1,3,1,"[4, 1, 1, 1]",4,4,6

====================================================================================================
..\data\raw\4_1_r2_architectures.csv
rows: 5835
is_full_dimension counts:
is_full_dimension
False    3104
True     2731
Name: count, dtype: int64
status counts:
status
NaN    5835
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,2,"[4, 4, 1]",10,10,20
45,3,2,"[4, 6, 5, 1]",35,35,59
317,4,2,"[4, 8, 14, 5, 1]",165,165,219
334,4,2,"[4, 10, 11, 11, 1]",165,165,282
345,4,2,"[4, 8, 13, 6, 1]",165,165,220
...,...,...,...,...,...,...
5828,5,2,"[4, 8, 19, 31, 10, 1]",969,969,1093
5830,5,2,"[4, 7, 14, 34, 16, 1]",969,969,1162
5832,5,2,"[4, 9, 20, 25, 25, 1]",969,969,1366
5833,5,2,"[4, 9, 14, 30, 27, 1]",969,969,1419
5834,5,2,"[4, 8, 22, 26, 13, 1]",969,969,1131

====================================================================================================
..\data\raw\4_1_r3_architectures.csv
rows: 107
is_full_dimension counts:
is_full_dimension
False    56
True     51
Name: count, dtype: int64
status counts:
status
NaN    107
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2,3,"[4, 5, 1]",20,20,25
45,3,3,"[4, 13, 14, 1]",220,220,248
46,3,3,"[4, 11, 17, 1]",220,220,248
47,3,3,"[4, 10, 19, 1]",220,220,249
49,3,3,"[4, 12, 16, 1]",220,220,256
56,3,3,"[4, 15, 12, 1]",220,220,252
58,3,3,"[4, 14, 13, 1]",220,220,251
60,3,3,"[4, 16, 11, 1]",220,220,251
67,4,3,"[4, 29, 73, 41, 1]",4060,4060,5267
70,4,3,"[4, 8, 57, 69, 1]",4060,4060,4490
71,4,3,"[4, 24, 54, 66, 1]",4060,4060,5022
80,4,3,"[4, 46, 61, 49, 1]",4060,4060,6028
91,4,3,"[4, 25, 56, 59, 1]",4060,4060,4863
95,4,3,"[4, 14, 66, 48, 1]",4060,4060,4196
97,4,3,"[4, 15, 56, 60, 1]",4060,4060,4320
98,4,3,"[4, 53, 56, 54, 1]",4060,4060,6258

====================================================================================================
..\data\raw\4_1_r4_architectures.csv
rows: 61
is_full_dimension counts:
is_full_dimension
True     32
False    29
Name: count, dtype: int64
status counts:
status
NaN    61
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,4,"[4, 10, 1]",35,35,50
21,3,4,"[4, 29, 31, 1]",969,969,1046
41,3,4,"[4, 27, 33, 1]",969,969,1032
43,3,4,"[4, 31, 29, 1]",969,969,1052
50,3,4,"[4, 26, 35, 1]",969,969,1049
53,3,4,"[4, 28, 32, 1]",969,969,1040
58,3,4,"[4, 30, 30, 1]",969,969,1050
59,3,4,"[4, 32, 28, 1]",969,969,1052

====================================================================================================
..\data\raw\4_1_r5_architectures.csv
rows: 48
is_full_dimension counts:
is_full_dimension
False    44
True      4
Name: count, dtype: int64
status counts:
status
NaN    48
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,5,"[4, 14, 1]",56,56,70

====================================================================================================
..\data\raw\4_1_r6_architectures.csv
rows: 8
is_full_dimension counts:
is_full_dimension
True     4
False    4
Name: count, dtype: int64
status counts:
status
NaN    8
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2,6,"[4, 21, 1]",84,84,105

====================================================================================================
..\data\raw\4_1_r7_architectures.csv
rows: 5
is_full_dimension counts:
is_full_dimension
True     3
False    2
Name: count, dtype: int64
status counts:
status
NaN    5
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,7,"[4, 30, 1]",120,120,150

====================================================================================================
..\data\raw\4_1_r8_architectures.csv
rows: 8
is_full_dimension counts:
is_full_dimension
True     4
False    4
Name: count, dtype: int64
status counts:
status
NaN    8
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2,8,"[4, 42, 1]",165,165,210

====================================================================================================
..\data\raw\4_1_r9_architectures.csv
rows: 9
is_full_dimension counts:
is_full_dimension
True     6
False    3
Name: count, dtype: int64
status counts:
status
NaN    9
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
8,2,9,"[4, 55, 1]",220,220,275

====================================================================================================
..\data\raw\4_2_r1_architectures.csv
rows: 1
is_full_dimension counts:
is_full_dimension
True    1
Name: count, dtype: int64
status counts:
status
NaN    1
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
0,2,1,"[4, 2, 2]",8,8,12

====================================================================================================
..\data\raw\4_2_r2_architectures.csv
rows: 1
is_full_dimension counts:
is_full_dimension
True    1
Name: count, dtype: int64
status counts:
status
NaN    1
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
0,2,2,"[4, 4, 2]",20,20,24

====================================================================================================
..\data\raw\4_2_r3_architectures.csv
rows: 5
is_full_dimension counts:
is_full_dimension
True     4
False    1
Name: count, dtype: int64
status counts:
status
NaN    5
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,3,"[4, 8, 2]",40,40,48

====================================================================================================
..\data\raw\4_2_r4_architectures.csv
rows: 5
is_full_dimension counts:
is_full_dimension
True     4
False    1
Name: count, dtype: int64
status counts:
status
NaN    5
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,4,"[4, 14, 2]",70,70,84

====================================================================================================
..\data\raw\4_2_r5_architectures.csv
rows: 11
is_full_dimension counts:
is_full_dimension
True     8
False    3
Name: count, dtype: int64
status counts:
status
NaN    11
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
9,2,5,"[4, 23, 2]",112,112,138

====================================================================================================
..\data\raw\4_2_r6_architectures.csv
rows: 5
is_full_dimension counts:
is_full_dimension
True     3
False    2
Name: count, dtype: int64
status counts:
status
NaN    5
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,6,"[4, 34, 2]",168,168,204

====================================================================================================
..\data\raw\4_2_r7_architectures.csv
rows: 10
is_full_dimension counts:
is_full_dimension
True     6
False    4
Name: count, dtype: int64
status counts:
status
NaN    10
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
8,2,7,"[4, 48, 2]",240,240,288

====================================================================================================
..\data\raw\4_2_r8_architectures.csv
rows: 10
is_full_dimension counts:
is_full_dimension
True     8
False    2
Name: count, dtype: int64
status counts:
status
NaN    10
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
8,2,8,"[4, 66, 2]",330,330,396

====================================================================================================
..\data\raw\4_2_r9_architectures.csv
rows: 9
is_full_dimension counts:
is_full_dimension
False    6
True     3
Name: count, dtype: int64
status counts:
status
NaN    9
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
8,2,9,"[4, 88, 2]",440,440,528

====================================================================================================
..\data\raw\4_3_r1_architectures.csv
rows: 2
is_full_dimension counts:
is_full_dimension
False    1
True     1
Name: count, dtype: int64
status counts:
status
NaN    2
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2,1,"[4, 3, 3]",12,12,21

====================================================================================================
..\data\raw\4_3_r2_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True     2
False    1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,2,"[4, 6, 3]",30,30,42

====================================================================================================
..\data\raw\4_3_r3_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True     2
False    1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2,3,"[4, 10, 3]",60,60,70

====================================================================================================
..\data\raw\4_3_r4_architectures.csv
rows: 7
is_full_dimension counts:
is_full_dimension
True     5
False    2
Name: count, dtype: int64
status counts:
status
NaN    7
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2,4,"[4, 18, 3]",105,105,126

====================================================================================================
..\data\raw\4_3_r5_architectures.csv
rows: 7
is_full_dimension counts:
is_full_dimension
True     5
False    2
Name: count, dtype: int64
status counts:
status
NaN    7
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2,5,"[4, 28, 3]",168,168,196

====================================================================================================
..\data\raw\4_3_r6_architectures.csv
rows: 5
is_full_dimension counts:
is_full_dimension
True     3
False    2
Name: count, dtype: int64
status counts:
status
NaN    5
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,6,"[4, 42, 3]",252,252,294

====================================================================================================
..\data\raw\4_3_r7_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True     2
False    1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,7,"[4, 60, 3]",360,360,420

====================================================================================================
..\data\raw\4_3_r8_architectures.csv
rows: 8
is_full_dimension counts:
is_full_dimension
False    4
True     4
Name: count, dtype: int64
status counts:
status
NaN    8
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2,8,"[4, 83, 3]",495,495,581

====================================================================================================
..\data\raw\4_3_r9_architectures.csv
rows: 9
is_full_dimension counts:
is_full_dimension
True     7
False    2
Name: count, dtype: int64
status counts:
status
NaN    9
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
8,2,9,"[4, 110, 3]",660,660,770

====================================================================================================
..\data\raw\4_4_r1_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
False    2
True     1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
0,2,1,"[4, 4, 4]",16,16,32

====================================================================================================
..\data\raw\4_4_r2_architectures.csv
rows: 5
is_full_dimension counts:
is_full_dimension
True     4
False    1
Name: count, dtype: int64
status counts:
status
NaN    5
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,2,"[4, 6, 4]",40,40,48

====================================================================================================
..\data\raw\4_4_r3_architectures.csv
rows: 7
is_full_dimension counts:
is_full_dimension
True     5
False    2
Name: count, dtype: int64
status counts:
status
NaN    7
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2,3,"[4, 12, 4]",80,80,96

====================================================================================================
..\data\raw\4_4_r4_architectures.csv
rows: 5
is_full_dimension counts:
is_full_dimension
True     3
False    2
Name: count, dtype: int64
status counts:
status
NaN    5
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,4,"[4, 20, 4]",140,140,160

====================================================================================================
..\data\raw\4_4_r5_architectures.csv
rows: 5
is_full_dimension counts:
is_full_dimension
True     3
False    2
Name: count, dtype: int64
status counts:
status
NaN    5
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,5,"[4, 32, 4]",224,224,256

====================================================================================================
..\data\raw\4_4_r6_architectures.csv
rows: 8
is_full_dimension counts:
is_full_dimension
True     4
False    4
Name: count, dtype: int64
status counts:
status
NaN    8
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2,6,"[4, 48, 4]",336,336,384

====================================================================================================
..\data\raw\4_4_r7_architectures.csv
rows: 6
is_full_dimension counts:
is_full_dimension
True     4
False    2
Name: count, dtype: int64
status counts:
status
NaN    6
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,7,"[4, 69, 4]",480,480,552

====================================================================================================
..\data\raw\4_4_r8_architectures.csv
rows: 7
is_full_dimension counts:
is_full_dimension
False    4
True     3
Name: count, dtype: int64
status counts:
status
NaN    7
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2,8,"[4, 95, 4]",660,660,760

====================================================================================================
..\data\raw\4_4_r9_architectures.csv
rows: 11
is_full_dimension counts:
is_full_dimension
True     7
False    4
Name: count, dtype: int64
status counts:
status
NaN    11
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
10,2,9,"[4, 126, 4]",880,880,1008

====================================================================================================
..\data\raw\4_5_r1_architectures.csv
rows: 2
is_full_dimension counts:
is_full_dimension
False    1
True     1
Name: count, dtype: int64
status counts:
status
NaN    2
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2,1,"[4, 4, 5]",20,20,36

====================================================================================================
..\data\raw\4_5_r2_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True     2
False    1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,2,"[4, 7, 5]",50,50,63

====================================================================================================
..\data\raw\4_5_r3_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True     2
False    1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2,3,"[4, 13, 5]",100,100,117

====================================================================================================
..\data\raw\4_5_r4_architectures.csv
rows: 6
is_full_dimension counts:
is_full_dimension
True     5
False    1
Name: count, dtype: int64
status counts:
status
NaN    6
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2,4,"[4, 22, 5]",175,175,198

====================================================================================================
..\data\raw\4_5_r5_architectures.csv
rows: 4
is_full_dimension counts:
is_full_dimension
True     2
False    2
Name: count, dtype: int64
status counts:
status
NaN    4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,5,"[4, 35, 5]",280,280,315

====================================================================================================
..\data\raw\4_5_r6_architectures.csv
rows: 7
is_full_dimension counts:
is_full_dimension
True     5
False    2
Name: count, dtype: int64
status counts:
status
NaN    7
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2,6,"[4, 53, 5]",420,420,477

====================================================================================================
..\data\raw\4_5_r7_architectures.csv
rows: 6
is_full_dimension counts:
is_full_dimension
False    3
True     3
Name: count, dtype: int64
status counts:
status
NaN    6
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2,7,"[4, 75, 5]",600,600,675

====================================================================================================
..\data\raw\4_5_r8_architectures.csv
rows: 10
is_full_dimension counts:
is_full_dimension
False    5
True     5
Name: count, dtype: int64
status counts:
status
NaN    10
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
8,2,8,"[4, 104, 5]",825,825,936

====================================================================================================
..\data\raw\4_5_r9_architectures.csv
rows: 5
is_full_dimension counts:
is_full_dimension
True     3
False    2
Name: count, dtype: int64
status counts:
status
NaN    5
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,9,"[4, 138, 5]",1100,1100,1242

====================================================================================================
..\data\raw\4_6_r1_architectures.csv
rows: 2
is_full_dimension counts:
is_full_dimension
False    1
True     1
Name: count, dtype: int64
status counts:
status
NaN    2
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2,1,"[4, 4, 6]",24,24,40

====================================================================================================
..\data\raw\4_6_r2_architectures.csv
rows: 4
is_full_dimension counts:
is_full_dimension
True     3
False    1
Name: count, dtype: int64
status counts:
status
NaN    4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,2,"[4, 7, 6]",60,60,70

====================================================================================================
..\data\raw\4_6_r3_architectures.csv
rows: 6
is_full_dimension counts:
is_full_dimension
True     4
False    2
Name: count, dtype: int64
status counts:
status
NaN    6
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2,3,"[4, 14, 6]",120,120,140

====================================================================================================
..\data\raw\4_6_r4_architectures.csv
rows: 5
is_full_dimension counts:
is_full_dimension
True     3
False    2
Name: count, dtype: int64
status counts:
status
NaN    5
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,4,"[4, 24, 6]",210,210,240

====================================================================================================
..\data\raw\4_6_r5_architectures.csv
rows: 5
is_full_dimension counts:
is_full_dimension
True     3
False    2
Name: count, dtype: int64
status counts:
status
NaN    5
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,5,"[4, 38, 6]",336,336,380

====================================================================================================
..\data\raw\4_6_r6_architectures.csv
rows: 7
is_full_dimension counts:
is_full_dimension
False    4
True     3
Name: count, dtype: int64
status counts:
status
NaN    7
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2,6,"[4, 56, 6]",504,504,560

====================================================================================================
..\data\raw\4_6_r7_architectures.csv
rows: 4
is_full_dimension counts:
is_full_dimension
True     3
False    1
Name: count, dtype: int64
status counts:
status
NaN    4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,7,"[4, 80, 6]",720,720,800

====================================================================================================
..\data\raw\4_6_r8_architectures.csv
rows: 6
is_full_dimension counts:
is_full_dimension
True     4
False    2
Name: count, dtype: int64
status counts:
status
NaN    6
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2,8,"[4, 110, 6]",990,990,1100

====================================================================================================
..\data\raw\4_6_r9_architectures.csv
rows: 5
is_full_dimension counts:
is_full_dimension
True     3
False    2
Name: count, dtype: int64
status counts:
status
NaN    5
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,9,"[4, 147, 6]",1320,1320,1470

====================================================================================================
..\data\raw\4_7_r1_architectures.csv
rows: 2
is_full_dimension counts:
is_full_dimension
False    1
True     1
Name: count, dtype: int64
status counts:
status
NaN    2
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2,1,"[4, 4, 7]",28,28,44

====================================================================================================
..\data\raw\4_7_r2_architectures.csv
rows: 2
is_full_dimension counts:
is_full_dimension
True    2
Name: count, dtype: int64
status counts:
status
NaN    2
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2,2,"[4, 7, 7]",70,70,77

====================================================================================================
..\data\raw\4_7_r3_architectures.csv
rows: 4
is_full_dimension counts:
is_full_dimension
True     3
False    1
Name: count, dtype: int64
status counts:
status
NaN    4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,3,"[4, 14, 7]",140,140,154

====================================================================================================
..\data\raw\4_7_r4_architectures.csv
rows: 5
is_full_dimension counts:
is_full_dimension
True     3
False    2
Name: count, dtype: int64
status counts:
status
NaN    5
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,4,"[4, 25, 7]",245,245,275

====================================================================================================
..\data\raw\4_7_r5_architectures.csv
rows: 4
is_full_dimension counts:
is_full_dimension
True     2
False    2
Name: count, dtype: int64
status counts:
status
NaN    4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,5,"[4, 40, 7]",392,392,440

====================================================================================================
..\data\raw\4_7_r6_architectures.csv
rows: 8
is_full_dimension counts:
is_full_dimension
True     5
False    3
Name: count, dtype: int64
status counts:
status
NaN    8
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2,6,"[4, 59, 7]",588,588,649

====================================================================================================
..\data\raw\4_7_r7_architectures.csv
rows: 7
is_full_dimension counts:
is_full_dimension
True     4
False    3
Name: count, dtype: int64
status counts:
status
NaN    7
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,7,"[4, 84, 7]",840,840,924

====================================================================================================
..\data\raw\4_7_r8_architectures.csv
rows: 7
is_full_dimension counts:
is_full_dimension
True     4
False    3
Name: count, dtype: int64
status counts:
status
NaN    7
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2,8,"[4, 116, 7]",1155,1155,1276

====================================================================================================
..\data\raw\4_7_r9_architectures.csv
rows: 10
is_full_dimension counts:
is_full_dimension
True     8
False    2
Name: count, dtype: int64
status counts:
status
NaN    10
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
9,2,9,"[4, 154, 7]",1540,1540,1694

====================================================================================================
..\data\raw\4_8_r1_architectures.csv
rows: 2
is_full_dimension counts:
is_full_dimension
False    1
True     1
Name: count, dtype: int64
status counts:
status
NaN    2
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2,1,"[4, 4, 8]",32,32,48

====================================================================================================
..\data\raw\4_8_r2_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True     2
False    1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,2,"[4, 8, 8]",80,80,96

====================================================================================================
..\data\raw\4_8_r3_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True     2
False    1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2,3,"[4, 15, 8]",160,160,180

====================================================================================================
..\data\raw\4_8_r4_architectures.csv
rows: 4
is_full_dimension counts:
is_full_dimension
True     2
False    2
Name: count, dtype: int64
status counts:
status
NaN    4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2,4,"[4, 26, 8]",280,280,312

====================================================================================================
..\data\raw\4_8_r5_architectures.csv
rows: 5
is_full_dimension counts:
is_full_dimension
True     3
False    2
Name: count, dtype: int64
status counts:
status
NaN    5
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,5,"[4, 41, 8]",448,448,492

====================================================================================================
..\data\raw\4_8_r6_architectures.csv
rows: 6
is_full_dimension counts:
is_full_dimension
False    3
True     3
Name: count, dtype: int64
status counts:
status
NaN    6
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2,6,"[4, 62, 8]",672,672,744

====================================================================================================
..\data\raw\4_8_r7_architectures.csv
rows: 9
is_full_dimension counts:
is_full_dimension
True     5
False    4
Name: count, dtype: int64
status counts:
status
NaN    9
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
8,2,7,"[4, 88, 8]",960,960,1056

====================================================================================================
..\data\raw\4_8_r8_architectures.csv
rows: 11
is_full_dimension counts:
is_full_dimension
True     8
False    3
Name: count, dtype: int64
status counts:
status
NaN    11
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
10,2,8,"[4, 120, 8]",1320,1320,1440

====================================================================================================
..\data\raw\4_8_r9_architectures.csv
rows: 10
is_full_dimension counts:
is_full_dimension
True     6
False    4
Name: count, dtype: int64
status counts:
status
NaN    10
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
7,2,9,"[4, 160, 8]",1760,1760,1920

====================================================================================================
..\data\raw\4_9_r1_architectures.csv
rows: 2
is_full_dimension counts:
is_full_dimension
True     1
False    1
Name: count, dtype: int64
status counts:
status
NaN    2
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
0,2,1,"[4, 4, 9]",36,36,52

====================================================================================================
..\data\raw\4_9_r2_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
False    2
True     1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,2,"[4, 9, 9]",90,90,117

====================================================================================================
..\data\raw\4_9_r3_architectures.csv
rows: 4
is_full_dimension counts:
is_full_dimension
True     3
False    1
Name: count, dtype: int64
status counts:
status
NaN    4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,3,"[4, 15, 9]",180,180,195

====================================================================================================
..\data\raw\4_9_r4_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True     2
False    1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,4,"[4, 27, 9]",315,315,351

====================================================================================================
..\data\raw\4_9_r5_architectures.csv
rows: 5
is_full_dimension counts:
is_full_dimension
True     4
False    1
Name: count, dtype: int64
status counts:
status
NaN    5
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,5,"[4, 42, 9]",504,504,546

====================================================================================================
..\data\raw\4_9_r6_architectures.csv
rows: 8
is_full_dimension counts:
is_full_dimension
True     7
False    1
Name: count, dtype: int64
status counts:
status
NaN    8
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
7,2,6,"[4, 63, 9]",756,756,819

====================================================================================================
..\data\raw\4_9_r7_architectures.csv
rows: 9
is_full_dimension counts:
is_full_dimension
True     5
False    4
Name: count, dtype: int64
status counts:
status
NaN    9
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
8,2,7,"[4, 90, 9]",1080,1080,1170

====================================================================================================
..\data\raw\4_9_r8_architectures.csv
rows: 7
is_full_dimension counts:
is_full_dimension
True     4
False    3
Name: count, dtype: int64
status counts:
status
NaN    7
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,8,"[4, 124, 9]",1485,1485,1612

====================================================================================================
..\data\raw\4_9_r9_architectures.csv
rows: 7
is_full_dimension counts:
is_full_dimension
True     5
False    2
Name: count, dtype: int64
status counts:
status
NaN    7
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2,9,"[4, 165, 9]",1980,1980,2145

====================================================================================================
..\data\raw\5_1_r1_architectures.csv
rows: 1
is_full_dimension counts:
is_full_dimension
True    1
Name: count, dtype: int64
status counts:
status
NaN    1
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
0,2,1,"[5, 1, 1]",5,5,6

====================================================================================================
..\data\raw\5_1_r2_architectures.csv
rows: 892
is_full_dimension counts:
is_full_dimension
False    596
True     296
Name: count, dtype: int64
status counts:
status
NaN    892
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2,2,"[5, 5, 1]",15,15,30
35,3,2,"[5, 9, 6, 1]",70,70,105
214,4,2,"[5, 12, 22, 14, 1]",495,495,646
263,4,2,"[5, 14, 24, 9, 1]",495,495,631
316,4,2,"[5, 9, 25, 14, 1]",495,495,634
...,...,...,...,...,...,...
870,5,2,"[5, 16, 55, 53, 33, 1]",4845,4845,5657
871,5,2,"[5, 43, 51, 55, 39, 1]",4845,4845,7397
877,5,2,"[5, 32, 55, 55, 27, 1]",4845,4845,6457
883,5,2,"[5, 15, 54, 53, 52, 1]",4845,4845,6555
891,5,2,"[5, 40, 55, 52, 38, 1]",4845,4845,7274

====================================================================================================
..\data\raw\5_1_r3_architectures.csv
rows: 84
is_full_dimension counts:
is_full_dimension
True     42
False    42
Name: count, dtype: int64
status counts:
status
NaN    84
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,3,"[5, 8, 1]",35,35,48
24,3,3,"[5, 19, 36, 1]",715,715,815
25,3,3,"[5, 27, 23, 1]",715,715,779
35,3,3,"[5, 24, 26, 1]",715,715,770
50,3,3,"[5, 28, 22, 1]",715,715,778
51,3,3,"[5, 18, 38, 1]",715,715,812
66,3,3,"[5, 20, 32, 1]",715,715,772
67,3,3,"[5, 17, 39, 1]",715,715,787
71,3,3,"[5, 15, 44, 1]",715,715,779
74,3,3,"[5, 26, 25, 1]",715,715,805
78,3,3,"[5, 23, 28, 1]",715,715,787
81,3,3,"[5, 22, 29, 1]",715,715,777
82,3,3,"[5, 16, 41, 1]",715,715,777
83,3,3,"[5, 29, 21, 1]",715,715,775

====================================================================================================
..\data\raw\5_1_r4_architectures.csv
rows: 10
is_full_dimension counts:
is_full_dimension
True     8
False    2
Name: count, dtype: int64
status counts:
status
NaN    10
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
9,2,4,"[5, 15, 1]",70,70,90

====================================================================================================
..\data\raw\5_1_r5_architectures.csv
rows: 9
is_full_dimension counts:
is_full_dimension
True     6
False    3
Name: count, dtype: int64
status counts:
status
NaN    9
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
8,2,5,"[5, 26, 1]",126,126,156

====================================================================================================
..\data\raw\5_1_r6_architectures.csv
rows: 12
is_full_dimension counts:
is_full_dimension
True     9
False    3
Name: count, dtype: int64
status counts:
status
NaN    12
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
10,2,6,"[5, 42, 1]",210,210,252

====================================================================================================
..\data\raw\5_1_r7_architectures.csv
rows: 12
is_full_dimension counts:
is_full_dimension
True     9
False    3
Name: count, dtype: int64
status counts:
status
NaN    12
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
9,2,7,"[5, 66, 1]",330,330,396

====================================================================================================
..\data\raw\5_1_r8_architectures.csv
rows: 13
is_full_dimension counts:
is_full_dimension
True     8
False    5
Name: count, dtype: int64
status counts:
status
NaN    13
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
9,2,8,"[5, 99, 1]",495,495,594

====================================================================================================
..\data\raw\5_1_r9_architectures.csv
rows: 15
is_full_dimension counts:
is_full_dimension
True     12
False     3
Name: count, dtype: int64
status counts:
status
NaN    15
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
14,2,9,"[5, 143, 1]",715,715,858

====================================================================================================
..\data\raw\5_2_r1_architectures.csv
rows: 1
is_full_dimension counts:
is_full_dimension
True    1
Name: count, dtype: int64
status counts:
status
NaN    1
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
0,2,1,"[5, 2, 2]",10,10,14

====================================================================================================
..\data\raw\5_2_r2_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True    3
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,2,"[5, 5, 2]",30,30,35

====================================================================================================
..\data\raw\5_2_r3_architectures.csv
rows: 7
is_full_dimension counts:
is_full_dimension
True     5
False    2
Name: count, dtype: int64
status counts:
status
NaN    7
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2,3,"[5, 12, 2]",70,70,84

====================================================================================================
..\data\raw\5_2_r4_architectures.csv
rows: 10
is_full_dimension counts:
is_full_dimension
True     8
False    2
Name: count, dtype: int64
status counts:
status
NaN    10
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
9,2,4,"[5, 24, 2]",140,140,168

====================================================================================================
..\data\raw\5_2_r5_architectures.csv
rows: 9
is_full_dimension counts:
is_full_dimension
True     6
False    3
Name: count, dtype: int64
status counts:
status
NaN    9
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
7,2,5,"[5, 42, 2]",252,252,294

====================================================================================================
..\data\raw\5_2_r6_architectures.csv
rows: 12
is_full_dimension counts:
is_full_dimension
True     7
False    5
Name: count, dtype: int64
status counts:
status
NaN    12
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
9,2,6,"[5, 70, 2]",420,420,490

====================================================================================================
..\data\raw\5_2_r7_architectures.csv
rows: 14
is_full_dimension counts:
is_full_dimension
True     10
False     4
Name: count, dtype: int64
status counts:
status
NaN    14
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
13,2,7,"[5, 110, 2]",660,660,770

====================================================================================================
..\data\raw\5_2_r8_architectures.csv
rows: 9
is_full_dimension counts:
is_full_dimension
False    5
True     4
Name: count, dtype: int64
status counts:
status
NaN    9
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
7,2,8,"[5, 165, 2]",990,990,1155

====================================================================================================
..\data\raw\5_2_r9_architectures.csv
rows: 10
is_full_dimension counts:
is_full_dimension
True     7
False    3
Name: count, dtype: int64
status counts:
status
NaN    10
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
7,2,9,"[5, 239, 2]",1430,1430,1673

====================================================================================================
..\data\raw\5_3_r1_architectures.csv
rows: 2
is_full_dimension counts:
is_full_dimension
True     1
False    1
Name: count, dtype: int64
status counts:
status
NaN    2
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
0,2,1,"[5, 3, 3]",15,15,24

====================================================================================================
..\data\raw\5_3_r2_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True     2
False    1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2,2,"[5, 7, 3]",45,45,56

====================================================================================================
..\data\raw\5_3_r3_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True     2
False    1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,3,"[5, 15, 3]",105,105,120

====================================================================================================
..\data\raw\5_3_r4_architectures.csv
rows: 7
is_full_dimension counts:
is_full_dimension
True     5
False    2
Name: count, dtype: int64
status counts:
status
NaN    7
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2,4,"[5, 30, 3]",210,210,240

====================================================================================================
..\data\raw\5_3_r5_architectures.csv
rows: 10
is_full_dimension counts:
is_full_dimension
True     7
False    3
Name: count, dtype: int64
status counts:
status
NaN    10
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
8,2,5,"[5, 54, 3]",378,378,432

====================================================================================================
..\data\raw\5_3_r6_architectures.csv
rows: 8
is_full_dimension counts:
is_full_dimension
True     6
False    2
Name: count, dtype: int64
status counts:
status
NaN    8
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
7,2,6,"[5, 90, 3]",630,630,720

====================================================================================================
..\data\raw\5_3_r7_architectures.csv
rows: 7
is_full_dimension counts:
is_full_dimension
True     5
False    2
Name: count, dtype: int64
status counts:
status
NaN    7
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2,7,"[5, 142, 3]",990,990,1136

====================================================================================================
..\data\raw\5_3_r8_architectures.csv
rows: 13
is_full_dimension counts:
is_full_dimension
True     7
False    6
Name: count, dtype: int64
status counts:
status
NaN    13
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
12,2,8,"[5, 213, 3]",1485,1485,1704

====================================================================================================
..\data\raw\5_3_r9_architectures.csv
rows: 13
is_full_dimension counts:
is_full_dimension
True     10
False     3
Name: count, dtype: int64
status counts:
status
NaN    13
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
12,2,9,"[5, 307, 3]",2145,2145,2456

====================================================================================================
..\data\raw\5_4_r1_architectures.csv
rows: 2
is_full_dimension counts:
is_full_dimension
False    1
True     1
Name: count, dtype: int64
status counts:
status
NaN    2
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2,1,"[5, 4, 4]",20,20,36

====================================================================================================
..\data\raw\5_4_r2_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True     2
False    1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2,2,"[5, 8, 4]",60,60,72

====================================================================================================
..\data\raw\5_4_r3_architectures.csv
rows: 4
is_full_dimension counts:
is_full_dimension
True     3
False    1
Name: count, dtype: int64
status counts:
status
NaN    4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,3,"[5, 18, 4]",140,140,162

====================================================================================================
..\data\raw\5_4_r4_architectures.csv
rows: 5
is_full_dimension counts:
is_full_dimension
True     4
False    1
Name: count, dtype: int64
status counts:
status
NaN    5
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,4,"[5, 35, 4]",280,280,315

====================================================================================================
..\data\raw\5_4_r5_architectures.csv
rows: 8
is_full_dimension counts:
is_full_dimension
True     6
False    2
Name: count, dtype: int64
status counts:
status
NaN    8
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
7,2,5,"[5, 63, 4]",504,504,567

====================================================================================================
..\data\raw\5_4_r6_architectures.csv
rows: 7
is_full_dimension counts:
is_full_dimension
True     4
False    3
Name: count, dtype: int64
status counts:
status
NaN    7
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2,6,"[5, 105, 4]",840,840,945

====================================================================================================
..\data\raw\5_4_r7_architectures.csv
rows: 10
is_full_dimension counts:
is_full_dimension
True     5
False    5
Name: count, dtype: int64
status counts:
status
NaN    10
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,7,"[5, 165, 4]",1320,1320,1485

====================================================================================================
..\data\raw\5_4_r8_architectures.csv
rows: 8
is_full_dimension counts:
is_full_dimension
False    4
True     4
Name: count, dtype: int64
status counts:
status
NaN    8
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,8,"[5, 248, 4]",1980,1980,2232

====================================================================================================
..\data\raw\5_4_r9_architectures.csv
rows: 13
is_full_dimension counts:
is_full_dimension
True     11
False     2
Name: count, dtype: int64
status counts:
status
NaN    13
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
12,2,9,"[5, 358, 4]",2860,2860,3222

====================================================================================================
..\data\raw\5_5_r1_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
False    2
True     1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
0,2,1,"[5, 5, 5]",25,25,50

====================================================================================================
..\data\raw\5_5_r2_architectures.csv
rows: 6
is_full_dimension counts:
is_full_dimension
True     5
False    1
Name: count, dtype: int64
status counts:
status
NaN    6
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,2,"[5, 9, 5]",75,75,90

====================================================================================================
..\data\raw\5_5_r3_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True     2
False    1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,3,"[5, 20, 5]",175,175,200

====================================================================================================
..\data\raw\5_5_r4_architectures.csv
rows: 6
is_full_dimension counts:
is_full_dimension
True     4
False    2
Name: count, dtype: int64
status counts:
status
NaN    6
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2,4,"[5, 39, 5]",350,350,390

====================================================================================================
..\data\raw\5_5_r5_architectures.csv
rows: 6
is_full_dimension counts:
is_full_dimension
True     3
False    3
Name: count, dtype: int64
status counts:
status
NaN    6
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,5,"[5, 70, 5]",630,630,700

====================================================================================================
..\data\raw\5_5_r6_architectures.csv
rows: 9
is_full_dimension counts:
is_full_dimension
True     5
False    4
Name: count, dtype: int64
status counts:
status
NaN    9
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2,6,"[5, 117, 5]",1050,1050,1170

====================================================================================================
..\data\raw\5_5_r7_architectures.csv
rows: 13
is_full_dimension counts:
is_full_dimension
True     8
False    5
Name: count, dtype: int64
status counts:
status
NaN    13
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
10,2,7,"[5, 184, 5]",1650,1650,1840

====================================================================================================
..\data\raw\5_5_r8_architectures.csv
rows: 8
is_full_dimension counts:
is_full_dimension
True     5
False    3
Name: count, dtype: int64
status counts:
status
NaN    8
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2,8,"[5, 275, 5]",2475,2475,2750

====================================================================================================
..\data\raw\5_5_r9_architectures.csv
rows: 9
is_full_dimension counts:
is_full_dimension
False    5
True     4
Name: count, dtype: int64
status counts:
status
NaN    9
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
8,2,9,"[5, 398, 5]",3575,3575,3980

====================================================================================================
..\data\raw\5_6_r1_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
False    2
True     1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
0,2,1,"[5, 5, 6]",30,30,55

====================================================================================================
..\data\raw\5_6_r2_architectures.csv
rows: 4
is_full_dimension counts:
is_full_dimension
True    4
Name: count, dtype: int64
status counts:
status
NaN    4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,2,"[5, 9, 6]",90,90,99

====================================================================================================
..\data\raw\5_6_r3_architectures.csv
rows: 4
is_full_dimension counts:
is_full_dimension
True     3
False    1
Name: count, dtype: int64
status counts:
status
NaN    4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,3,"[5, 21, 6]",210,210,231

====================================================================================================
..\data\raw\5_6_r4_architectures.csv
rows: 5
is_full_dimension counts:
is_full_dimension
True     3
False    2
Name: count, dtype: int64
status counts:
status
NaN    5
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,4,"[5, 42, 6]",420,420,462

====================================================================================================
..\data\raw\5_6_r5_architectures.csv
rows: 9
is_full_dimension counts:
is_full_dimension
True     6
False    3
Name: count, dtype: int64
status counts:
status
NaN    9
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
8,2,5,"[5, 76, 6]",756,756,836

====================================================================================================
..\data\raw\5_6_r6_architectures.csv
rows: 13
is_full_dimension counts:
is_full_dimension
True     8
False    5
Name: count, dtype: int64
status counts:
status
NaN    13
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
12,2,6,"[5, 126, 6]",1260,1260,1386

====================================================================================================
..\data\raw\5_6_r7_architectures.csv
rows: 7
is_full_dimension counts:
is_full_dimension
True     5
False    2
Name: count, dtype: int64
status counts:
status
NaN    7
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2,7,"[5, 198, 6]",1980,1980,2178

====================================================================================================
..\data\raw\5_6_r8_architectures.csv
rows: 8
is_full_dimension counts:
is_full_dimension
True     4
False    4
Name: count, dtype: int64
status counts:
status
NaN    8
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2,8,"[5, 297, 6]",2970,2970,3267

====================================================================================================
..\data\raw\5_6_r9_architectures.csv
rows: 12
is_full_dimension counts:
is_full_dimension
True     8
False    4
Name: count, dtype: int64
status counts:
status
NaN    12
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
11,2,9,"[5, 429, 6]",4290,4290,4719

====================================================================================================
..\data\raw\5_7_r1_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
False    2
True     1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,1,"[5, 5, 7]",35,35,60

====================================================================================================
..\data\raw\5_7_r2_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True     2
False    1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,2,"[5, 10, 7]",105,105,120

====================================================================================================
..\data\raw\5_7_r3_architectures.csv
rows: 7
is_full_dimension counts:
is_full_dimension
True     6
False    1
Name: count, dtype: int64
status counts:
status
NaN    7
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
6,2,3,"[5, 23, 7]",245,245,276

====================================================================================================
..\data\raw\5_7_r4_architectures.csv
rows: 6
is_full_dimension counts:
is_full_dimension
True     5
False    1
Name: count, dtype: int64
status counts:
status
NaN    6
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
5,2,4,"[5, 45, 7]",490,490,540

====================================================================================================
..\data\raw\5_7_r5_architectures.csv
rows: 6
is_full_dimension counts:
is_full_dimension
False    4
True     2
Name: count, dtype: int64
status counts:
status
NaN    6
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,5,"[5, 81, 7]",882,882,972

====================================================================================================
..\data\raw\5_7_r6_architectures.csv
rows: 8
is_full_dimension counts:
is_full_dimension
True     6
False    2
Name: count, dtype: int64
status counts:
status
NaN    8
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
7,2,6,"[5, 134, 7]",1470,1470,1608

====================================================================================================
..\data\raw\5_7_r7_architectures.csv
rows: 12
is_full_dimension counts:
is_full_dimension
True     8
False    4
Name: count, dtype: int64
status counts:
status
NaN    12
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
11,2,7,"[5, 210, 7]",2310,2310,2520

====================================================================================================
..\data\raw\5_7_r8_architectures.csv
rows: 7
is_full_dimension counts:
is_full_dimension
False    4
True     3
Name: count, dtype: int64
status counts:
status
NaN    7
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,8,"[5, 315, 7]",3465,3465,3780

====================================================================================================
..\data\raw\5_7_r9_architectures.csv
rows: 11
is_full_dimension counts:
is_full_dimension
False    6
True     5
Name: count, dtype: int64
status counts:
status
NaN    11
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
8,2,9,"[5, 455, 7]",5005,5005,5460

====================================================================================================
..\data\raw\5_8_r1_architectures.csv
rows: 2
is_full_dimension counts:
is_full_dimension
False    1
True     1
Name: count, dtype: int64
status counts:
status
NaN    2
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
1,2,1,"[5, 5, 8]",40,40,65

====================================================================================================
..\data\raw\5_8_r2_architectures.csv
rows: 4
is_full_dimension counts:
is_full_dimension
True    4
Name: count, dtype: int64
status counts:
status
NaN    4
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
3,2,2,"[5, 10, 8]",120,120,130

====================================================================================================
..\data\raw\5_8_r3_architectures.csv
rows: 6
is_full_dimension counts:
is_full_dimension
True     4
False    2
Name: count, dtype: int64
status counts:
status
NaN    6
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,3,"[5, 24, 8]",280,280,312

====================================================================================================
..\data\raw\5_8_r4_architectures.csv
rows: 5
is_full_dimension counts:
is_full_dimension
True     4
False    1
Name: count, dtype: int64
status counts:
status
NaN    5
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,4,"[5, 47, 8]",560,560,611

====================================================================================================
..\data\raw\5_8_r5_architectures.csv
rows: 11
is_full_dimension counts:
is_full_dimension
True     8
False    3
Name: count, dtype: int64
status counts:
status
NaN    11
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
10,2,5,"[5, 84, 8]",1008,1008,1092

====================================================================================================
..\data\raw\5_8_r6_architectures.csv
rows: 11
is_full_dimension counts:
is_full_dimension
True     7
False    4
Name: count, dtype: int64
status counts:
status
NaN    11
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
10,2,6,"[5, 140, 8]",1680,1680,1820

====================================================================================================
..\data\raw\5_8_r7_architectures.csv
rows: 10
is_full_dimension counts:
is_full_dimension
True     7
False    3
Name: count, dtype: int64
status counts:
status
NaN    10
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
9,2,7,"[5, 220, 8]",2640,2640,2860

====================================================================================================
..\data\raw\5_8_r8_architectures.csv
rows: 11
is_full_dimension counts:
is_full_dimension
True     6
False    5
Name: count, dtype: int64
status counts:
status
NaN    11
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
10,2,8,"[5, 335, 8]",3960,3960,4355

====================================================================================================
..\data\raw\5_8_r9_architectures.csv
rows: 13
is_full_dimension counts:
is_full_dimension
True     9
False    4
Name: count, dtype: int64
status counts:
status
NaN    13
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
12,2,9,"[5, 477, 8]",5720,5720,6201

====================================================================================================
..\data\raw\5_9_r9_architectures.csv
rows: 7
is_full_dimension counts:
is_full_dimension
True     4
False    3
Name: count, dtype: int64
status counts:
status
NaN    7
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
4,2,9,"[5, 495, 9]",6435,6435,6930

====================================================================================================
..\data\raw\6_1_r1_architectures.csv
rows: 1
is_full_dimension counts:
is_full_dimension
True    1
Name: count, dtype: int64
status counts:
status
NaN    1
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
0,2,1,"[6, 1, 1]",6,6,7

====================================================================================================
..\data\raw\6_1_r2_architectures.csv
rows: 3
is_full_dimension counts:
is_full_dimension
True     2
False    1
Name: count, dtype: int64
status counts:
status
NaN    3
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
2,2,2,"[6, 6, 1]",21,21,42

====================================================================================================
..\data\raw\6_1_r3_architectures.csv
rows: 177
is_full_dimension counts:
is_full_dimension
True     94
False    83
Name: count, dtype: int64
status counts:
status
NaN    177
Name: count, dtype: int64
Recorded MFAs:

,h,exponent,architecture,dimension_computed,ambient_dimension,num_parameters
7,2,3,"[6, 10, 1]",56,56,70
24,3,3,"[6, 38, 48, 1]",2002,2002,2100
43,3,3,"[6, 23, 83, 1]",2002,2002,2130
70,3,3,"[6, 46, 39, 1]",2002,2002,2109
76,3,3,"[6, 45, 40, 1]",2002,2002,2110
79,3,3,"[6, 32, 58, 1]",2002,2002,2106
91,3,3,"[6, 25, 76, 1]",2002,2002,2126
105,3,3,"[6, 34, 54, 1]",2002,2002,2094
109,3,3,"[6, 37, 50, 1]",2002,2002,2122
120,3,3,"[6, 36, 51, 1]",2002,2002,2103
124,3,3,"[6, 49, 36, 1]",2002,2002,2094
127,3,3,"[6, 29, 65, 1]",2002,2002,2124
130,3,3,"[6, 24, 79, 1]",2002,2002,2119
132,3,3,"[6, 22, 86, 1]",2002,2002,2110
134,3,3,"[6, 28, 67, 1]",2002,2002,2111
135,3,3,"[6, 35, 53, 1]",2002,2002,2118
137,3,3,"[6, 26, 72, 1]",2002,2002,2100
143,3,3,"[6, 41, 44, 1]",2002,2002,2094
147,3,3,"[6, 33, 56, 1]",2002,2002,2102
153,3,3,"[6, 48, 37, 1]",2002,2002,2101
154,3,3,"[6, 27, 70, 1]",2002,2002,2122
156,3,3,"[6, 42, 43, 1]",2002,2002,2101
159,3,3,"[6, 40, 46, 1]",2002,2002,2126
163,3,3,"[6, 30, 62, 1]",2002,2002,2102
164,3,3,"[6, 47, 38, 1]",2002,2002,2106
169,3,3,"[6, 43, 42, 1]",2002,2002,2106
170,3,3,"[6, 39, 47, 1]",2002,2002,2114
171,3,3,"[6, 31, 60, 1]",2002,2002,2106
176,3,3,"[6, 44, 41, 1]",2002,2002,2109

====================================================================================================
..\data\raw\6_8_r9_architectures.csv
rows: 0
is_full_dimension counts:
Series([], Name: count, dtype: int64)
status counts:
Series([], Name: count, dtype: int64)
Recorded MFAs:

KeyError: "None of [Index(['h', 'exponent', 'architecture', 'dimension_computed',\n       'ambient_dimension', 'num_parameters'],\n      dtype='str')] are in the [columns]"

## Post-Run entries with Codimension = 1

In [263]:
# for path in csv_paths:
#     df = read_architecture_csv(path)
#     df = df[df['dimension_computed'] == df['ambient_dimension']-1]
#     df = df[df['h']==2]
#     if len(df)>0:
#         display(df)

dfs = []
for path in csv_paths:
    df = read_architecture_csv(path)
    df = df[df['dimension_computed'] == df['ambient_dimension'] - 1]
    # df = df[df['h'] == 2]
    if len(df) > 0:
        dfs.append(df)

merged_df = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
display(merged_df)

,h,exponent,architecture,num_parameters,dimension_computed,ambient_dimension,is_full_dimension,is_minimal,expected_dimension,defect_expected,defect_ambient,backend,primes,elapsed_seconds,status,covered_by_mfa
0,3.0,12.0,"[2, 9, 15, 1]",168.0,144.0,145.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3.0,12.0,"[2, 8, 17, 1]",169.0,144.0,145.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,12.0,"[2, 6, 23, 1]",173.0,144.0,145.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2.0,2.0,"[2, 1, 1]",3.0,2.0,3.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7.0,2.0,"[2, 4, 3, 4, 5, 5, 10, 1]",137.0,64.0,65.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1327,3.0,3.0,"[7, 36, 133, 1]",5173.0,5004.0,5005.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1328,2.0,7.0,"[7, 245, 1]",1960.0,1715.0,1716.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1329,2.0,2.0,"[8, 7, 1]",63.0,35.0,36.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1330,3.0,2.0,"[8, 20, 14, 1]",454.0,329.0,330.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1331,2.0,2.0,"[9, 8, 1]",80.0,44.0,45.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [265]:
merged_df.to_csv('../data/processed/codimension_one.csv')